### ISSUE TITLE
Breadcrumb: Don't include a link on the current page & add title to links 

### ISSUE THREAD

**Issue by darwinp** [ckan/ckan#1050]
On dataset and resource pages the current page is linked in the breadcrumb.  It should not be

Truncated names should have a title attribute. 

See for example
http://master.ckan.org/dataset/adur_district_spending 
http://master.ckan.org/dataset/adur_district_spending/resource/281dffa6-ea9b-4446-be41-05dced06591f

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.
