### ISSUE TITLE
Problems with resetting passwords

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1053]
If you forget your password you can reset it by typing your username at CKAN's reset password page, e.g.

http://demo.ckan.org/en/user/reset

In practice, however, you don't have to type your username: you can type anything that matches part of your profile (e.g. part of your e-mail address). If *either* the match is unique, *or* you have typed your whole username, CKAN e-mails you a password reset link and redirects you to the home page. If not it gives an error: "xxx matched more than one user" or "No such user: xxxx".

This behaviour is not very transparent. Also, the e-mail sent does not tell you what your username is. This cropped up when a user was unable to log in despite repeatedly resetting their password. In fact they had misremembered their username, but CKAN did not give any clue about this (their misremembered version matched part of their e-mail address).

# Suggested fixes

1. The match should exactly match a whole username. (Matching e-mail addresses leads to headache-causing complications, especially since more than one username can be registered to one e-mail address.)

2. If the reset is unsuccessful, the error on the page returned should read as follows:

      "No such user: xxx. Forgotten your username? <a>Search users</a>"

  with the link going to /user.

3. After a successful reset, the page should redirect to a new page saying "A reset link has been sent to your e-mail address."

4. The password reset e-mail should say what your username is, i.e.

  You have requested the password for user xxxx on CKAN Demo to be reset."

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
