### ISSUE TITLE
CKAN style guidelines

### ISSUE THREAD

**Issue by johnmartin** [ckan/ckan#1069]
There should be a page which showcases all the GUI elements that a theme designer, extension developer and core developer needs to understand in order to build pages/templates.

Should include:

* [ ] What are the core concepts/ideas behind the CKAN UI? and how new pages/features for CKAN should feel.
* [ ] What the main template blocks of pages are and what they are for?
* [ ] What are the HTML snippets you should use?
* [ ] When can I add to `main.css`

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
