### ISSUE TITLE
Some CKAN dependencies are not thread-safe, but deployment document recommends using threads

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#1077]
[CKAN Apache deployment document](http://docs.ckan.org/ca/latest/deployment.html#create-the-apache-config-file) states:

```
    # Deploy as a daemon (avoids conflicts between CKAN instances).
    WSGIDaemonProcess ckan_default display-name=ckan_default processes=2 threads=15
```

Deploying this way has lead to a number of intermittent issues on our server, including failures related to [one shared "stash" list in webhelpers.markdown](https://bitbucket.org/bbangert/webhelpers/src/9ad434bec9a16c06c1cfeed38cde02f00a95685d/webhelpers/markdown.py?at=trunk#cl-966)

Other less frequent issues seem to have been resolved by switching to a single thread per process as well.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
