### ISSUE TITLE
Why am I seeing this notification?

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1097]
Notifications should make it clear why you are seeing them. Is this a dataset I follow, or in a group I follow, or what?

E.g. " **Fred** updated the dataset Foo in the organization **Bar**" could show that I follow Fred and Bar, but not Foo.

(Are the little icons supposed to tell me this? I can't understand them, so they are no use if so.)

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
