### ISSUE TITLE
Gender specific messages untranslatable

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#1108]
Messages like:

```
{actor} updated the {related_type} {related_item}
```

can not be properly translated in languages with different grammatical genders, eg:

```
{actor} actualizó el Articulo {related_item}
{actor} actualizó la Visualización {related_item}

```

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
