### ISSUE TITLE
Letters with accents in vocabularies tags

### ISSUE THREAD

**Issue by gduportail** [ckan/ckan#1134]
Hello,

I'm using vocaularies to store lists of options. For example, I have a special dataset field "Category". This is a select field whose options are stored into the tags of the vocabulary "category". But, I would like to put special characters into these options (eg. : letters with accents).
Vocabulary tags are currently limited to alphanumeric characters and a couple of other characters. Could you add the functionality to use letters with accents in vocaluray tags as it is already allowed in free tags?

Thanks.

Version used : 2.0.1

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
