### ISSUE TITLE
organization_update changes all its packages' capacity to 'public' from 'organization'

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#1145]
I wrote a test to see if organization_update will accept the result of organization_show and not change anything. It uses test data from #1038 branch. 

    def test_44_organization_update(self):
        CreateTestData.create_group_hierarchy_test_data()
        context = {'model': model, 'user': 'testsysadmin'}
        group = get_action('organization_show')(context,
                                                {'id': 'national-health-service'})
        del group['display_name'] # confuses organization_update!
        updated_group = get_action('organization_update')(context, group)
        # nothing of substance should have changed
        assert_equal(group['packages'], updated_group['packages'])
        for key in group:
            if key in ('display_name', 'num_followers'): continue
            assert_equal(group[key], updated_group[key])

The main issue is that it appears to change packages' capacity from 'organization' to 'public' (failing the test).

BTW organization_update doesn't accept the 'display_name' key, hence the del line in the test.

I might tackle this after #1038.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.
