### ISSUE TITLE
URI parameter for tag_create

### ISSUE THREAD

**Issue by barthanssens** [ckan/ckan#1181]
It would be helpful if ckan.logic.action.create.tag_create() would have an optional parameter "uri". 

tag_create(context, tag_dict, uri)

This comes in handy when exporting / federating ckan repositories and matching vocabularies.

**Comment by rossjones** [comment]
This ticket's currently likely to be closed due to age, is there any possibility that you might submit a PR for this?

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
