### ISSUE TITLE
Creating term translations for dataset values result in Server Error 

### ISSUE THREAD

**Issue by guetux** [ckan/ckan#1203]
Hi there!

I'm kinda new to the CKAN project, yet I think I may have discovered a bug ;-). Not sure if it's a duplicate but a quick search showed nothing similar.

When adding term translations of terms that happen to be the ID of a dataset, visiting the that dataset in the translated language result in a HTTP 500 Server Error. The error occurs only when the tranlations contains spaces or other non-valid id characters.

It's arguable that translating IDs doesn't make a lot of sense. However, since it's possible to set custom IDs on datasets this can happen quite quickly. I detected the issue while hacking on a custom harvester.

Unfortunatley I don't have a failing testcase, but i may provide you a stacktrace if this would help.

I'm running on branch ``release-v2.0.1``

I hope this is comprehensible ;-)

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
