### ISSUE TITLE
API key stored as plain text

### ISSUE THREAD

**Issue by bakersemail** [ckan/ckan#1212]
Hi CKAN devs and OKFN,

Noticed that the API key is stored as plain text in the database. Since the API key is essentially being treated as a username/password for Data API functions (creating and changing datasets, resources, etc) the API is very sensitive.
I am concerned that if our database is leaked, we would need to update all the API keys ASAP or risk data being updated until we do so.

Should the API key be stored encrypted or hashed to increase the attack time potential if such a leak occurs?

**Comment by LaurentGoderre** [comment]
I agree with @nigelbabu, if it acts like a password, it should be treated as a password

**Comment by wardi** [comment]
Symmetric encryption of our current API keys in the DB is a great idea. Let's do this.

Removing the default creation of the current API keys for users is a good idea, but I'd want a configuration option for the behaviour, or sites that depend on new users having readable API keys will break.

When we add support for multiple API keys for users we could store them labelled (users give them names like "used by my import script im12345") and hashed so they can't be recovered after they are generated. It should still be possible to create a legacy API key for users that need them.

**Comment by LaurentGoderre** [comment]
I like that idea

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by michab23** [comment]
Hi,
Is there any solution for this problem with the newest CKAN versions?
Does API key still is stored as plain text in DB?

**Comment by wardi** [comment]
As far as I'm aware no one has worked on the code to better manage users API keys, but it'd certainly be a welcome contribution.

**Comment by boykoc** [comment]
> Symmetric encryption of our current API keys in the DB is a great idea. Let's do this.
> 
> Removing the default creation of the current API keys for users is a good idea, but I'd want a configuration option for the behaviour, or sites that depend on new users having readable API keys will break.
> 
> When we add support for multiple API keys for users we could store them labelled (users give them names like "used by my import script im12345") and hashed so they can't be recovered after they are generated. It should still be possible to create a legacy API key for users that need them.

I like this approach. It in theory could be implemented incrementally in this way and start flagging for deprecation in future versions of CKAN.
- [ ] treat API keys like passwords (encrypt of current key setup in DB) with config option to prevent breakage (possibly show API key only once to user on generation, never store key unhashed/unencrypted and still allow re-generation of key)
- [ ] multiple keys for users
- [ ] ability to revoke individual keys (user or sysadmin)
- [ ] labeled keys for users

**Comment by wardi** [comment]
one last thing would be tracking the last time each key was used. I find this feature really handy on other sites to weed out unused keys
