### ISSUE TITLE
ConfigParser is case insensitive - LIST_PARAMS in celery_app.py are upper case

### ISSUE THREAD

**Issue by benscott** [ckan/ckan#1227]
In lib/celery_app.py, LIST_PARAMS are specified as upper case:

```
10. LIST_PARAMS = """CELERY_IMPORTS ADMINS ROUTES""".split()
```

So when searching for the keys in config, they'll never be matched as ConfigParser returns all keys in lower case.

```
52.    for key, value in config.items('app:celery'):     
53.        if key in LIST_PARAMS:
```

You could use config.optionxform=str to force case to be honoured.

Cheers,
Ben

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
