### ISSUE TITLE
Would be good to find another solution for the dataset URL rather than one generated from the dataset title

### ISSUE THREAD

**Issue by natasab** [ckan/ckan#1233]
The feature for user to define the data set URL , thus having a very friendly URL is great. However i was not able to create a dataset with same name as another user.

The system informs me about existence of a dataset with same URL - but I could not see this dataset as the other user made it private.

**Comment by themowski** [comment]
This discussion may be of interest to anyone who comes across this and needs this feature: https://github.com/ckan/ckan/discussions/8091
