### ISSUE TITLE
Multilingual plugin hard-codes the language list

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1342]
There's a ```LANGS``` array in https://github.com/okfn/ckan/blob/master/ckanext/multilingual/plugin.py#L9 that hard-codes multilingual's supported languages. It'll break if you use another (check http://lists.okfn.org/pipermail/ckan-dev/2013-November/006181.html and http://pastebin.com/qxZLQt83).

To avoid having to keep this list in sync with CKAN's supported languages list, and  follow DRY principles, we could init it with, for example, ```ckan.locale_order``` or something like that.

This should avoid this problem from happening again.

/cc @amercader @joetsoi What do you think?

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
