### ISSUE TITLE
Customise featured image and text via config

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1367]
The default setup has a box on the home page with the text 'This is a featured section'. This text, and the uploaded image to go in the box, should be config options, and should be editable by a sysadmin on /ckan-admin/config.

It seems @tobes fixed this in #500 but didn't merge, as he didn't like the fact that it didn't integrate with translations. This is a valid concern but applies to other config things too (about, intro text, etc). We shouldn't hold up fixing this issue while we address it.

**Comment by mapmeld** [comment]
@seanh do you have a link? When I search for featured sections, this content comes up first. The theming tutorial jumps into custom templates right away, and when I searched the docs for 'featured' it didn't give me any useful results.
