### ISSUE TITLE
Typing tags gives random results

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1370]
When I type free-form tags while editing a dataset, CKAN tries to do some clever auto-completion. I don't know how this works but the result is that if I type too fast, I can end up with a random tag that begins with letters vaguely similar to the ones I've typed. This is very annoying. It happens quite a lot but is not reliably reproducible, but, for example: at 

http://demo.ckan.org/dataset/edit/afghanistan-election-data

I tried typing in some tags: `<addi>` `<adds>` `<addition>` `<add>`

The first three were fine. The fourth one mysteriously came out as `<additio>`. It's a mystery where this even comes from - it's not an existing tag.

The same happens with the 'format' drop-down when editing a resource (see also #1371).

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
