### ISSUE TITLE
Make resource name default to file name

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1372]
Users are usually not sure what to enter as the 'resource name' and it ends up being blank. It's mildly helpful for a resource to have a name, however.

I suggest the field should be pre-populated with the filename, or (for a linked file) component of the name after the last "/". E.g. for <http://example.com/this/that/theother.csv> the "name" would be "theother.csv", unless the user changed it.

Obviously, if the URL ends with a / like <http://example.com/this/that/theother/>  the default name should be "theother", rather than being blank.

**Comment by rossjones** [comment]
@smotornyuk is this fixed now?

**Comment by wardi** [comment]
No, there's a PR to address this with client side JS, but it overwrites the name even if it has been given so I haven't merged it

**Comment by rossjones** [comment]
Will assign to Sergey then in case he wants to finish it off.

**Comment by smotornyuk** [comment]
@rossjones , i've fixed problem mentioned by Ian and updated pull request.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
