### ISSUE TITLE
Config option for naming Groups and Orgs

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1395]
The words 'Group' and 'Organization' are not useful for most CKAN instances. See

https://lists.okfn.org/pipermail/ckan-discuss/2013-December/003157.html

Different catalogues use them in different ways so these terms should be configurable via a config option. To get the best functionality and translatablility each concept should have a list of alternatives (see below), plus the option to choose a new word. An instance owner who chooses their own word can also choose one of the standard alternatives as the 'fallback', which is used when a translated version of the interface is used.

Alternatives:

Organisation | Publisher | Department | Team | Project

Group | Theme | Category | List

**Comment by rossjones** [comment]
https://github.com/ckan/ckan/pull/2674 is a WIP PR for deleting routes.  Making the naming configurable came up again and we've asked for a PR.  Close in a couple months if this doesn't arrive.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
