### ISSUE TITLE
Bad response codes from `package_revision_list`

### ISSUE THREAD

**Issue by nigelbabu** [ckan/ckan#1405]
This issue was created from #1385 by @rshk.

I was testing the API, while I found this:

```
% http http://127.0.0.1:5000/api/3/action/package_revision_list             
HTTP/1.0 409 Conflict
```

The same happens with other methods that require the ``id`` argument. This indeed should return an error, but the code should be ``400 Bad Request``, not ``409 Conflict`` (which isn't supposed to be returned in response to a GET request, btw..)

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.
