### ISSUE TITLE
Add support package relationships in UI.

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#1406]
PackageRelationships are not exposed via the API, although they are implemented and have supporting tests.

There is currently no UI to support setting these relationships.

**Comment by neothemachine** [comment]
+1
What's the status here? Quite old this topic. I found the following related pages:

https://github.com/ckan/ckan/wiki/Dataset-relationships
http://trac.ckan.org/ticket/253
http://trac.ckan.org/ticket/256

Is this just a question of creating a UI? Is there still demand for this?

**Comment by rossjones** [comment]
I think this is just waiting for UI.  There are action functions for them now in the logic layer, and the package_create/update handle them (https://github.com/ckan/ckan/blob/master/ckan/logic/action/create.py#L102-L107).  It should be possible to just implement this properly in the package templates (https://github.com/ckan/ckan/tree/master/ckan/templates/package) and have the controller do 'the right thing'.  More specifically it should probably be added to https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/package_form.html (which is used for new and edit package) and https://github.com/ckan/ckan/blob/master/ckan/templates/package/read.html (ideally with use a snippet) for presentation.

It may be that there's a need to show this relationships somehow in the search results, but I guess that can wait until it's actually possible to create them.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
