### ISSUE TITLE
Add possibility to add help text to textareas

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1410]
For example, we have a ```markdown``` template macro [1] that creates a textarea with a pretty help message, telling the user that she can use markdown there, as in:

![Markdown Textarea](https://f.cloud.github.com/assets/76945/1785029/15544c10-68dd-11e3-87d2-9f71494d9ba2.png)

It would be good to have a macro that allowed me to create a textarea with a help text like that. It could be as simple as adding an optional ```help_text``` parameter in the textarea macro [2]. If it's not set, everything is as it is now.

Thoughts?

[1] https://github.com/okfn/ckan/blob/master/ckan/templates/macros/form.html#L118-L127
[2] https://github.com/okfn/ckan/blob/master/ckan/templates/macros/form.html#L148-L156

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
