### ISSUE TITLE
Nicer logical deletion

### ISSUE THREAD

**Issue by rshk** [ckan/ckan#1415]
Some thoughts about things I don't like with the logical deletion (through the API)

- trying to retrieve a deleted package as anonymous user returns a 403 (while I'd expect a 404)
- trying to retrieve a deleted package as sysadmin user returns 200; the only hint that the object is deleted is ``{"state": "deleted"}``. Personally, I find that this behavior might be confusing; I'd return 404 anyways, unless the users explicitly specifies he'd like to retrieve deleted datasets too (through some request argument).

Of course they're not returned in the main list of objects (which is what I expect), but still it might be worth adding some parameter to retrieve the ids even of deleted objects (might be handy in things like external administration tools / scripts)

**Comment by rossjones** [comment]
This is now being addressed in #2805
