### ISSUE TITLE
api doc improvements

### ISSUE THREAD

**Issue by joetsoi** [ckan/ckan#1423]
split from #1022 

ckan.activity_list_limit can be referenced correctly in

dashboard_activity_list_html
package_activity_list
group_activity_list
recently_changed_packages_activity_list
user_activity_list_html
package_activity_list_html
group_activity_list_html
recently_changed_packages_activity_list_html
dashboard_activity_list_html

related_lists needs it's parameters highlighted for 'sort' and 'featured'

package_search: for the results section, should search_facets parameter have'title' 'items' etc highlighted?

member_list ckan.logic.NotFound (do we have a exceptions reference? infact I think it's the only one that mentions raising any kind of exception. We either add raises for the other functions or remove it and mention that action functions can raise a ActionError/ValidationError/NotFound)

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
