### ISSUE TITLE
No limits on revision_list

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#1431]
The revision_list action has no limits in place, it attempts to download every single revision in the database. For systems with hundreds of thousands of revisions, this makes things explode before the data is returned, or when it is returned it takes a v.long time.

Perhaps enforcing a reasonable limit by default would be better?

**Comment by rossjones** [comment]
https://github.com/ckan/ckan/pull/2522 provides a way to page this call.  

----

This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.

**Comment by davidread** [comment]
This is fixed :) The limit of 50 was added in this PR: https://github.com/ckan/ckan/pull/2522 and was released in ckan 2.5.

**Comment by rossjones** [comment]
Thanks for clarifying @davidread
