### ISSUE TITLE
AGPL compliance on about page

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#1438]
Let's add a new list on the about page that shows for CKAN and all of the active extensions:
 * home page
 * license
 * version
 * git branch and commit running (if available)

the first three we can get from
```python
import pkg_resources
d = pkg_resources.require(name)[0]
info = dict(info.split(': ', 1)
    for info in d.get_metadata_lines['PKG-INFO'])
```

the last we can read with something like:
```python
git = os.path.join(os.path.dirname(module.__file__), '.git')
branch = open(os.path.join(git, 'HEAD')).read()
if branch.startswith('ref: '):
    commit = open(os.path.join(git, branch[5:])).read()
```

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
