### ISSUE TITLE
«not logged in» is not translated in the activity stream

### ISSUE THREAD

**Issue by gawel** [ckan/ckan#1516]
A string is not translated here: https://github.com/ckan/ckan/blob/master/ckan/lib/activity_streams_session_extension.py#L64

This result in a good frenglish sentence on http://www.nosdonnees.fr/fr/ :)

I'll be happy to provide a pull request but I don't know if wrapping it in a `_()` will be enough/is the right thing to do. Any thought ?

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
