### ISSUE TITLE
Add a dynamic javascript view to serve globals

### ISSUE THREAD

**Issue by gawel** [ckan/ckan#1524]
For now some stuff is hard coded in the javascript

https://github.com/ckan/ckan/blob/master/ckan/public/scripts/application.js#L766

https://github.com/ckan/ckan/blob/master/ckan/public/scripts/application.js#L1461

I want to propose a dynamic view to make those urls configurable.

At least we'd like to add to this view:

- the dataproxy service url

- assets base url (even if this should probably use css classes instead of hard coded image urls)

- global timeout value (both for ajax request and service calls)

This way users will be able to increase timeout value if the response is too slow; Use theyr own dataproxy; host all the assets

The reason is that the csv preview does not work on http://www.nosdonnees.fr/dataset/historique-de-consommation-lectricit-en-france-nov-2011-juin-2013/resource/fcf79197-ee2d-47ef-b632-164ba33761cf mostly because the request timeout.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
