### ISSUE TITLE
Invite to organization has hard-coded email text

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#1527]
Would be useful if the email text in get_invite_body() (from mailer.py) loaded a template with the text so that extensions can override it.  When working around https://github.com/ckan/ckan/issues/1506 it is likely that the email template will need to be changed, and/or other users might want to change the text of the email.

**Comment by hbunke** [comment]
What's the status of this issue? The code has been in master for some time now (https://github.com/ckan/ckan/commit/66549991119191fb00a7aaf907e4027036df4561), but nothing seems to have made it into a release so far.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
