### ISSUE TITLE
Feature: Preview Handler for Google Spreadsheets

### ISSUE THREAD

**Issue by hannesgassert** [ckan/ckan#1536]
Nice to have: inline preview (iframe) for data sets that have google spreadsheet as type 

Example: http://datahub.io/dataset/fc-basel/resource/3094a953-f1ab-4f69-816b-a4b76c5603ed

**Comment by rossjones** [comment]
Using ckanext-googledocs or ckanext-officedocs should fulfill this.

This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
