### ISSUE TITLE
Restrict input boxes to accepted length

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1537]
If I try to create a group with a very long title, I can cheerfully type as much as I want but when I hit 'create group' I get an error:

The form contains invalid entries:
Name: Name must be a maximum of 100 characters long

If the name is restricted in length (here or in other input boxes in the UI) it would be better to use the maxlength attribute to stop me typing more in the first place.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
