### ISSUE TITLE
Wrong error when cookies are rejected

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1542]
If I try to log in while not accepting cookies, using a correct username and password, the result is

     * Login failed. Bad username or password. (Or if using OpenID, it
       hasn't been associated with a user account.)

CKAN should instead give some error like 'Please enable cookies to log in'.

**Comment by joetsoi** [comment]
done with the open id stuff

**Comment by NicolaiMogensen** [comment]
We share the same IP in-office and sometimes users are not allowed to log in to CKAN. Using incognito mode or another browser  clears up the problem (But we still get the wrong username/password mention) Is this still a problem, or are logins not invalidated upon new request?
