### ISSUE TITLE
'Site tag line' appears redundant

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1543]
What is the 'site tag line' for at http://demo.ckan.org/ckan-admin/config? It is not mentioned in the explanatory text and whatever I write there doesn't seem to appear anywhere.

If it is used, the explanatory text should be changed. If not, delete it.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
