### ISSUE TITLE
Guidance for sysadmins

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1546]
The sidebar at /ckan-admin has an unhelpful text called 'What are sysadmins?' that tells you how to create new sysadmins. Instead it should guide the user (who must already be a sysadmin, and probably doesn't have the power to create new ones) in how to use their Awesome Power. Suggested text:

    Administer CKAN

    As a sysadmin user you have full control over this CKAN instance. Proceed with care!

    For guidance on using sysadmin features, see the CKAN [sysadmin guide](...).

The link should be to the sysadmin guide (http://docs.ckan.org/en/latest/sysadmin-guide.html) in the version of the docs corresponding to their CKAN version.

**Comment by rossjones** [comment]
This seems to have been fixed by https://github.com/ckan/ckan/pull/1562
