### ISSUE TITLE
Meaningless 'source' field

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1551]
The dataset creation process has a 'source' field that has no apparent meaning.

The only clue is that the example text pre-populating it is a URL with a .json extension. This suggests a data file, but in CKAN, these are added as resources.

(Background: this appears to be new in 2.2. A very old version of CKAN had a 'source' field that was intended for a link to a web page about the data, not the actual data. It was rarely used and, because of the bad naming, even more rarely understood.)

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
