### ISSUE TITLE
Refactor trash

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#1559]
kindly: automatically purge deleted datasets after a certain period of being touched to stop a build-up and the trash page loading slowly. paster command needed to do this, which can be run by cron.

davidread: how about prefixing the name with the uuid on deletion, so the namespace is cleared. then undelete and remove those chars if possible.

issue with trashing a dataset where harvester has a foreign key to the dataset - would need to delete the harvest_object.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.
