### ISSUE TITLE
API lacks a package_purge function

### ISSUE THREAD

**Issue by Vilsepi** [ckan/ckan#1572]
The CKAN API has delete and purge functions for organizations and groups, but dataset only has package_delete. Deleting a dataset using package_delete leaves it in the system with a "deleted" state. If one tries to to create a new dataset with the same dataset URL, the operation fails, claiming that the URL is already in use.

There should be a __package_purge__ function in the API to completely remove a dataset from the database.

Context: For development and testing purposes, I want to be able to create thousands of datasets, delete them, and later on create more datasets (with the same names). This pollutes the database as the old datasets are left in the database.

**Comment by wardi** [comment]
Looks like I might need to add this, so I've assigned myself

**Comment by wardi** [comment]
@mattleduc has done some work on this but ran into a performance issue we'll need to resolve that before adding this to the API.

Somewhat related, I've added an issue to discuss renaming deleted datasets when they conflict with a new one being created: #2438

**Comment by rossjones** [comment]
I think we can close this - @davidread has implemented in b5b8cc5daeb23d432d67ae9defa08bbce06c47ac and it's fast enough (paster takes longer to load than the purge takes).
