### ISSUE TITLE
Ability to specify which fields to return in CKAN API would be really useful

### ISSUE THREAD

**Issue by markbrough** [ckan/ckan#1575]
Under CKAN2 it was possible to do this:
http://iatiregistry.org/api/2/search/dataset?fl=id,name,revision_id

Now it doesn't appear to be possible to do this:
http://iatiregistry.org/api/3/action/package_search?fl=id,name,revision

... it returns every field, not just those specified. This would be a useful feature if you're trying to query a large number of datasets - I just want the id, name, and url of the first resource.

This is stated as a limitation in the help text on the API: 

    The parameter that controls which fields are returned in the solr query cannot be changed.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
