### ISSUE TITLE
Write documentation on migrating CKAN to a new host

### ISSUE THREAD

**Issue by adamamyl** [ckan/ckan#1586]
It appears that there's no documentation outlining how to migrate CKAN to a new host, for example, when one wants to change hosting company.

This should be provided, and take into account permissions on things such as the filestore, and keeping the db servers on private addressing.

I would suggest this lives in the Maintainer's guide.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
