### ISSUE TITLE
Allow CKAN (and paster) to find config from envvar

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#1597]
I would much rather do `export CKAN_INI=....` once than have to type `-c /etc/ckan/default/production.ini` all the time.  

I'm aware I could just set it in my profile and -c $CKAN_INI but I think finding config from a environment var is a useful feature, _not just for paster_. It would mean:
- No more hard-coding config in wsgi file
- config can be set per-host in Apache using SetEnv
- Less typing when using paster (for single instance environments)

The first two of these would be very useful in a multi-instance environment.

**Comment by KrzysztofMadejski** [comment]
Doesn't work for me on CKAN 2.6, but everything seems configured properly:

```
(ckan) ckan@openlviv:~/src/ckan$ echo $CKAN_INI
/etc/ckan/prod.ini

(ckan) ckan@openlviv:~/src/ckan$ paster datastore set-permissions
Config file not found: /home/ckan/.virtualenvs/ckan/src/ckan/development.ini
(Given by: -c parameter)

(ckan) ckan@openlviv:~/src/ckan$ paster --version
PasteScript 2.0.2 from /home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages (python 2.7.6 (default, Jun 22 2015, 17:58:13))
```

I'm on Ubuntu 14.04

**Comment by davidread** [comment]
Yeah it's not worked for me for a while now on master. I find it really handy on my older version of ckan.

Please do open a new issue, and if you have a chance provide a fix too.

**Comment by davidread** [comment]
@KrzysztofMadejski I've done a PR to fix this here: https://github.com/ckan/ckan/pull/3522
