### ISSUE TITLE
Documentation incorrect on use of Format field

### ISSUE THREAD

**Issue by JayDaley** [ckan/ckan#1599]
The documentation for 2.2 says at http://ckan.readthedocs.org/en/ckan-2.2/user-guide.html#datasets-and-resources the following:

>Step 5. Add the other information on the page. CKAN does not require this information, but it is good practice to add it:
>    Name – a name for this resource, e.g. “Population density 2011, CSV”. Different resources in the dataset should have different names.
>    Description – a short description of the resource.
>    Format – the file format of the resource, e.g. CSV (comma-separated values), XLS, JSON, PDF, etc.

There is no mention of the fact that Format is used to initiate Dataproxy and only the values "xls" and "csv" can be used to initiate a call to Dataproxy.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
