### ISSUE TITLE
A regular user can place his organization under any organization

### ISSUE THREAD

**Issue by Vilsepi** [ckan/ckan#1633]
We are using CKAN 2.2 with code from the [ckanext-hierachy](https://github.com/datagovuk/ckanext-hierarchy) to provide a UI for handling organization hierarchy.

It seems that a regular user (without sysadmin rights) is able to select any organization as the parent organization. Consider userAlice who has created organization cutePets, and then userEve who has created organization bunnySlaughterhouse. Now userEve can move her organization to be a suborganization of cutePets, and to the rest of the users, this looks like a valid, "official" suborganization.

I am not sure whether this is by design or a bug, but we have a case where we cannot completely trust every CKAN user, and thus it would probably be better if users can only select those organizations in which they are already admins.

**Comment by rossjones** [comment]
This issue is being closed as it is nearly more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
