### ISSUE TITLE
Explain API's package_show auth rules in our docs

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1688]
The relative docs are in http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.package_show, and the auth rules are in https://github.com/ckan/ckan/blob/master/ckan/logic/auth/get.py#L97-L117 .

**Comment by souravsingh** [comment]
I would like to work on this issue.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
