### ISSUE TITLE
api/action/related_list ignoring parameters to filter related items

### ISSUE THREAD

**Issue by the42** [ckan/ckan#1769]
Reported against CKAN 2.2a

Whatever value I give for id or type, all related items get returned. Works for related_show.

However, if a valid id is entered, the values get filtered. I would have expected that entering a non-existend id would result in an empty result set.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old, and related items have recently been removed from master in favour of ckanext-showcase.  If you are still experiencing this problem and wish to help investigate further, please feel free to re-open it.
