### ISSUE TITLE
CKAN on SSL

### ISSUE THREAD

**Issue by nigelbabu** [ckan/ckan#1773]
This is a metabug for issues related to SSL with CKAN at the moment and documentation for setting up SSL.

First cut of configuration for fully SSL CKAN instance: https://gist.github.com/nigelbabu/076ad12c13b2071de8e1

Additionally, there are a couple of places the URL needs to be protocol independent as well (reported on mailing list).

**Comment by pstarace** [comment]
Hi @nigelbabu any news on that topic?
Thanks
Paolo

**Comment by Aung-Myint-Thein** [comment]
Hi @nigelbabu, I am serving CKAN 2.3.1 on ssl and data explorer stopped working at recline_view. When I changed the iframe url to https, it shows only "loading" and the console shows "http://xxx/api/i18n/en" is blocked. And I saw all main.js, client.js and a lot of js are not loaded too. Is there a way to fix the HTTPS over all the ckan site? .. thanks!

**Comment by nigelbabu** [comment]
Okay, I'm going to get back to actively working on this. My initial goal is to get a pull request up with documentation for 

* Setting up Nginx
* CKAN config changes required.
* Problems you might hit and how to fix them (This will need help from you!)

**Comment by nigelbabu** [comment]
@Aung-Myint-Thein Please post support issues onto the mailing list. That one is because ckan.site_url is `http://` rather than `https://`

**Comment by florianm** [comment]
@nigelbabu thanks for reviving this issue, comes at a good time for us. Happy to test on my end. I'm working on a datacats-based [deployment](http://govhack2015.readthedocs.org/en/latest/) that would greatly benefit from SSL.

**Comment by Starl3n** [comment]
@nigelbabu Can you let me know if you have a wiki page setup for further discussion? We have some problems we've hit and solved, some we've hit and not yet solved.

**Comment by mattfullerton** [comment]
@starl3n let me know if you want some help, I waded through a very difficult ssl install (behind a proxy) a month or two ago with lots of help from @nigelbabu

**Comment by mattfullerton** [comment]
+1 for wiki page/faq/troubleshooter

**Comment by florianm** [comment]
+1 for wiki & walkthrough - working on the same here with some extra headache from corporate proxy / split horizon DNS and other non-trivial things I'm not in direct control of.

**Comment by corebits** [comment]
Nigel, Can you post a link here to the wiki page for SSL configuration, I am working through some issues with SSL now and would like to confirm how others are working around some of the issues encountered.

**Comment by nigelbabu** [comment]
Hello, my day job has less to do with CKAN these days, so I this sort of dropped out of my list. I've dumped a simple page here: https://github.com/ckan/ckan/wiki/SSL.

It needs a better Nginx configuration with dhparams and OSCP stapling. If anyone has the patience to try it out and write instructions, I'd be very grateful!

**Comment by corebits** [comment]
Thanks Nigel. I will review and provide updates as required.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by jimhive** [comment]
Hi... We're using 2.5.2.

We're using nginx.

We have updated /etc/ckan/default/production.ini ckan.site_url  to use https:// ... 

However... the <body ....  data-site-root  and data-locale-root  >  properties are still using http:// as the protocol and we are getting "Mixed Content" request errors, due to AJAX requests, from files such as "image-upload". This is causing some of the JavaScript to fail, such as the file upload button on the secure site.

I'm unsure if I've missed anything in our configuration. Any help would be appreciated.

**Comment by torfsen** [comment]
@jimhive We're serving CKAN 2.5.2 using Apache for WSGI and an Nginx reverse proxy. While Nginx serves the site via HTTPS to the public, the communication between Apache and Nginx uses HTTP. So far that seems to work nicely and I haven't encountered any failing scripts or mixed content errors, yet. Our `ckan.site_url` is set to `https://...`.

> However... the properties are still using http:// as the protocol and we are getting "Mixed Content" request errors, due to AJAX requests, from files such as "image-upload". This is causing some of the JavaScript to fail, such as the file upload button on the secure site.

Can you give us some more details about your setup and the errors that you get? What are the "properties" that you are talking about?

**Comment by jimhive** [comment]
@torfsen Sorry. Typing things too quickly, words getting mixed up. The properties... the sentence structure is wrong. It should have just read that "CKAN is using http:// as the protocol...."

The server is using Apache to proxy and nginx as a reverse caching proxy. This mostly follows the configuration as outlined in the wiki page above.

The errors we are seeing are in the Chrome console.

"Mixed content. The page at 'https://...' was  was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://..../api/i18n/en' This request has been blocked; the content must be served over HTTPS."

With some stack traces through jQuery....
into
getLocaleData	@	image-upload.min.js:78
ckan.initialize	@	image-upload.min.js:92
(anonymous function)	@	image-upload.min.js:93
... and back into jQuery

**Comment by amercader** [comment]
@jimhive Is your `ckan.site_url` setting set to `https://....` ?

**Comment by jimhive** [comment]
@amercader Yes... it is.

Is this the only thing that is required for CKAN to use the correct protocol? 
Or is there some detection of the current protocol? (and partially ignoring the configured protocol?)

**Comment by torfsen** [comment]
@jimhive We're redirecting HTTP to HTTPS in Nginx, so perhaps that's why it's working for us. (I don't know whether the browsers block mixed content before getting it based on the URL, or if they try to download it in case it get redirected to HTTPS as in our case)

**Comment by nigelbabu** [comment]
@jimhive It sounds like you haven't setup the `X-Forwarded-Proto` header. See this page for details: https://github.com/ckan/ckan/wiki/SSL

**Comment by jimhive** [comment]
@nigelbabu Thank you... that fixed it. Thank you for the fast response.

**Comment by wardi** [comment]
We could set the `X-Forwarded-Proto` header in the WSGI environment ourselves when the `site_url` starts with `https://`. It's no good to have part of CKAN returning https urls and another part returning http ones.

**Comment by wardi** [comment]
@nigelbabu I think that's a really common way to set up SSL. I also think CKAN shouldn't be inconsistent about the URLs it's returning. We have the information so why not do it right all the time instead of depending on external configuration?

**Comment by nigelbabu** [comment]
I don't think we should set `X-Forwarded-Proto` at CKAN because it should be set by the load balancer rather than the app (It's not actually a published standard, sadly). This will let us serve HTTP and HTTPS simultaneously, for instance (whether someone would actually want that at all is a different story).

**Comment by nigelbabu** [comment]
I've updated the wiki page so the two problematic configuration are the two top things to watch out for - https://github.com/ckan/ckan/wiki/SSL

**Comment by wardi** [comment]
I think I don't understand.

If I use `https://..` in the `site_url` then ckan will generate absolute URLs with `https://` (e.g. for uploaded file urls). There is some other case (redict from another middleware? more info would be great) that isn't generating URLs with `https://` unless this `X-Forwarded-Proto` is set. That seems like a bug to me.

**Comment by wardi** [comment]
I believe this is fixed on master and will be backported to the next patch release of the supported ckan versions. https://github.com/ckan/ckan/pull/2998#issuecomment-224615278

**Comment by gustavomwk** [comment]
Hi, I am having the same problem reported by @Aung-Myint-Thein 
after I have set the SSL using the tutorial, I cannot explore the data. (using data visualizer)
does anyone know how to fix this issue?
