### ISSUE TITLE
Will the real authenticated user please stand up?

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#1780]
We're using too many different ways of finding the user that is logged in, including:

* User model query with name from context['user']
* context['auth_user_obj']
* c.user (user name)
* c.user_obj

Instead let's have a single function that returns the user object and caches it in a safe place for the next time the function is called from the same request.

**Comment by wardi** [comment]
I think this is still worth fixing at least by documenting the recommended + supported ways to get user information.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
