### ISSUE TITLE
Modifications in Organizations

### ISSUE THREAD

**Issue by aitormagan** [ckan/ckan#1788]
Hello!

I've found two problems with the organizations module. The first of all is that when you delete an organization you can access the organization via the URL given. The organization does not appear in the list of organizations anymore, but you are able to see it, if you know its name. What I expect is a 404. 

The second one is a little bit tricky. Here you have the steps to reproduce the bug:
1. Create an organization
2. Only the user that creates the organization is given the option to create datasets for this organization in the page to create datasets. 
3. Add a user to this organization. You must choose either the Edit or the Admin role.
4. This user is given the option to create datasets for this organization in the page to create datasets.
5. Delete the user form the organization.
6. When creating a dataset, the user can see the organizations from which he/she has been deleted. Nevertheless, an error arises when the "Next" button is clicked.

In addition, when users are deleted from an organization, they can still see the list of private datasets. However, they cannot open them.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
