### ISSUE TITLE
There's no place to see guessed types of a datastore resource

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1794]
With the resource views (#1251), making sure your data is clean and its columns were guessed with the correct type became more important. I've received a few bug reports for the barcharts at http://github.com/ckan/ckanext-basiccharts where the problem was that a column that should be numeric was recognized as text because it had some problem like a row with "x" in it, or not using the dot as a decimal separator.

These problems are hard to debug if you're not technical. It would be good to have somewhere to point people to and ask them to see if every column was correctly identified.

When you first submit a CSV to the DataStore, it shows you the columns and types it guessed. But if you try to submit the same file again, it won't show you anymore, just displaying:

![pakistan education 2013 ckan](https://cloud.githubusercontent.com/assets/76945/3384458/7c9cb590-fc5a-11e3-951e-463982a239e8.png)

I'd like somewhere that will always display the resource's columns and its guessed types.

**Comment by rossjones** [comment]
This is being covered by ckan/ideas-and-roadmap#106 now
