### ISSUE TITLE
Installing extensions in Docker

### ISSUE THREAD

**Issue by seanh** [ckan/ckan#1805]
Figure out and document how to install CKAN extensions in a Docker install of CKAN.

There are two cases:

1. I already have a CKAN site running in Docker, now I want to add a new extension to it

2. I want to build a custom Docker image that contains some extensions

**Comment by fullergalway** [comment]
Regarding scenario 1, I think you can do it by changing your configuration slightly - use some data volumes. For example, first copy out the folders out of your running docker:

    sudo docker cp ckan:/usr/lib/ckan /usr/lib
    sudo docker cp ckan:/var/lib/ckan /var/lib
    sudo docker cp ckan:/etc/ckan /etc

Now stop your ckan docker and verify that everything looks good in a new docker instance using volumes:

    docker stop ckan
    docker run -d -p 80:80 -v /var/lib/ckan:/var/lib/ckan \
                                        -v /usr/lib/ckan:/usr/lib/ckan \
                                        -v /etc/ckan:/etc/ckan \
                                        --link ckan-db:db \
                                        --link ckan-solr:solr ckan/ckan

If it all works your data should be present in the now running ckan. Verify, then kill that docker process. If it failed you could fail back using: docker start ckan

If it all worked, then you should be able to install your plugins as usual. Start a bash shell in a docker vm.

    docker run -d -p 80:80 -v /var/lib/ckan:/var/lib/ckan \
                                        -v /usr/lib/ckan:/usr/lib/ckan \
                                        -v /etc/ckan:/etc/ckan \
                                        --link ckan-db:db \
                                        --link ckan-solr:solr ckan/ckan \
                                        /bin/bash

Now running in the docker bash shell you can see what's already there, and install your modules (I had to install git in mine to use pip freeze)

    . /usr/lib/ckan/default/bin/activate
    apt-get update && apt-get -y install git
    pip freeze
    mkdir -p /var/lib/ckan/extras
    cd /var/lib/ckan/extras
    git clone https://github.com/ckan/ckanext-dcat.git
    cd ckanext-dcat
    pip install -e ./
    pip install -r ckanext-dcat/requirements.txt
    pip install celery
    vi /etc/ckan/default/ckan.ini
    exit

Now start a new docker container and enjoy your newly installed extension.

    docker run -d -p 80:80 -v /var/lib/ckan:/var/lib/ckan \
                                        -v /usr/lib/ckan:/usr/lib/ckan \
                                        -v /etc/ckan:/etc/ckan \
                                        --link ckan-db:db \
                                        --link ckan-solr:solr ckan/ckan

Obviously some modules will be more complicated for example if they require a redis server you'll need to start your ckan-redis docker and create a docker link to that.

Hope this helps!

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by cascaoSDC** [comment]
my question is if we can pre install the extencions before run the docker build, i cant find doc's about that

**Comment by Ik-Emmanuel** [comment]
@cascaoSDC  Hi, did you find a solution to getting your generated extension installed during build?  Facing a similar challeng.  I have adirectory with the generated extension files (after running ckan generate extension)  , I particulary want to use the plugins and templates  in the generated extension, to overide the default templates and I need to install this custom extension, during the docker build. But I keep getting plugin not found when I add it to the list of ckan plugins env variable during  build.
