### ISSUE TITLE
can not load resources with file name containing Chinese character

### ISSUE THREAD

**Issue by Feng-Gao** [ckan/ckan#1820]
I recently set up a new CKAN instance (package install) for the community and found when I uploaded a file with a file name containing Chinese character, CKAN can not handle it. 

The problem is after I uploaded the file successfully, the file can not be loaded in datapreview through either dataproxy or datastore, and it even can not be downloaded. 

The error message in ckan_default.error.log is:

[Tue Jul 01 11:36:45 2014] [error] 2014-07-01 11:36:45,681 INFO  [ckan.lib.base]  /dataset/04f75f12-045c-4791-8f75-349d898ce4e1/resource/ec9b994a-e7c7-4895-a6e5-360dfae5d04a/download/.xls rend$
[Tue Jul 01 11:36:45 2014] [error] [client 127.0.0.1] mod_wsgi (pid=57245): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Tue Jul 01 11:36:45 2014] [error] [client 127.0.0.1] TypeError: expected byte string object for header value, value of type NoneType found

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
