### ISSUE TITLE
/group/follow/<ID> doesn't work for organizations

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#1821]
On the organization page, if for some reason you have JS disabled, and click 'Follow' then it redirects you to /group/follow which doesn't work for organizations.

e.g. http://master.ckan.org/group/follow/4e768617-0f1b-48ed-a092-6e516d525c56
which is from http://master.ckan.org/organization/ross-test

**Comment by wardi** [comment]
Group+org customization should be working now. Un-assigning myself and leaving this as good for contribution

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by deepak-thinqq** [comment]
any updates on this issue. im facing the same error in v2.6.1

**Comment by davidread** [comment]
@deepak-thinqq it's marked 'good for contribution' so it's waiting for someone who needs this to contribute a fix. Do you have a chance to contribute this?
