### ISSUE TITLE
Custom extra fields in package form are not stored when starting with letters from "a" - "ma"

### ISSUE THREAD

**Issue by reicharm** [ckan/ckan#1833]
**Steps to reproduce:**

Enable an IDatasetForm plugin that has extra fields with names that sort both before and after the string 'metadata_linkage', such as the one in https://github.com/OpenDataPortal-AT/ckanext-odpat-form/blob/master/ckanext/odpat_form/templates/package/snippets/package_metadata_fields.html#L24
Create a dataset
Save the dataset 

**What happens:**

Fields on the 3rd step of dataset creation that start with letters lower than "metadata_linkage" are not being saved.

**Workaround:**

Rename the fields (starting with "z" for example) and the fields are saved correctly
OR Edit the dataset after saving and enter the values of the fields - they are stored correctly when edited...

**Comment by wardi** [comment]
I haven't had time to look at this, but it may have been fixed by changing to a two-stage dataset form. If not please reopen.
