### ISSUE TITLE
Updating datasets via API removes dataset resources and extras when they are not included in the payload

### ISSUE THREAD

**Issue by aitormagan** [ckan/ckan#1839]
I've found a very annoying problem using the API to update a dataset. The problem is that some dataset fields are deleted when they are not included in the payload. 

How to reproduce the error:
1. Create a dataset called `example` with one resource and two extras. (for example: 
"example1: val1", "example2: val2").
2. Edit this dataset via API: 

**URL**: `http://HOST:PORT/api/action/package_update`
**Payload**: `{"id":"example"}`

The result is that the dataset has no resources an no extras but what I expected is a dataset with the same resources and the same extras as the initial one.

**Comment by dimmichel** [comment]
Hi,

Is this work still in progress?

(A) I run package_show(id=dummy_id)
(B) I replace the empty 'extras' key in the returned dictionary (dummy_data_dict) with the following extras:[{'value': 'None', 'key': 'dummy_key_1'}, {'value': 'None', 'key': 'dummy_key_2'}]
(C) I run package_update(id=dummy_id,data_dict=dummy_data_dict)
(D) Packages are updated but they are missing all the 'extras' that I include.

Is there an example I could use that works?

Regards
