### ISSUE TITLE
HTTP Basic auth leaks into CKAN's auth

### ISSUE THREAD

**Issue by nigelbabu** [ckan/ckan#1850]
When setting an HTTP basic auth for a CKAN site, if there exists a CKAN user with the same username, they will be logged in. Fairly sure this is undesirable and I suspect has everything to do with repoze.who.

**Comment by davidread** [comment]
I think interest in this has wained

**Comment by torfsen** [comment]
I just ran into this on CKAN 2.5.2. However, my HTTP Basic Auth user account names do *not* match the CKAN accounts, and this confuses CKAN: I can successfully login to CKAN (i.e. no error messages) but afterwards CKAN will treat me as being logged in (login button is still showing, no buttons for creating datasets, etc.). However, if I try to login again CKAN  tells me that I'm already logged in.

I tried to figure out if one can disable HTTP Basic Auth in repoze.who but couldn't find any good documentation. It seems that the basicauth-plugin is already disabled in CKAN's [`who.ini`](https://github.com/ckan/ckan/blob/7363a402c4506520e8b163998e426f2de1b4e6e5/ckan/config/who.ini), but I don't know enough about repoze.who to fully understand the situation.

In my opinion, CKAN should not use information from Basic Auth at all. Let the web server handle Basic Auth and use the standard cookie-based authentication inside CKAN. Anything else is a potential security problem, especially in its current undocumented form.

**Comment by davidread** [comment]
I agree. You can fix it on your instance by adding a couple of lines of middleware:

http://stackoverflow.com/questions/36557516/basic-auth-issue-with-ckan/36570038

or if you'd like to create a PR in CKAN to fix this for everyone that might use HTTP Basic Auth, that would be even better.
