### ISSUE TITLE
Organization custom fields removing bug

### ISSUE THREAD

**Issue by razz0** [ckan/ckan#1868]
An organization can have custom fields and in the organization admin page there is a "Remove" checkbox next to each custom field. However the checkbox often doesn't seem to do what's expected.

For example when only the uppermost "Remove" is checked, and you are not adding more custom fields, the field doesn't get removed. If you add a new custom field at the same time, it is removed. Also when you have checked "Remove" for all your custom fields, nothing gets removed. With some combinations of checked and unchecked checkboxes they do function as expected.

The problem exists atleast in CKAN versions 2.1.2 and 2.2 (demo.ckan.org).

**Comment by rossjones** [comment]
This PR just looks like it needs test fixing to account for the change.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
