### ISSUE TITLE
Add resource views' styling to all default CKAN styles

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1869]
In the default theme, there's a carroussel for the resource's views, as in:
![pakistan population ckan](https://cloud.githubusercontent.com/assets/76945/3799095/e476ea82-1bea-11e4-9329-5161d0fa8f61.png)

But if we change that to, for example, the green style in the sysadmin page, we get an unstyled carroussel as in:
![pakistan population ckan-green](https://cloud.githubusercontent.com/assets/76945/3799096/e47a8aca-1bea-11e4-859c-4a9bb60c571f.png)

We should keep them all the same, just changing the colors.

**Comment by amercader** [comment]
Fixed with latest CSS rebuild
