### ISSUE TITLE
Modifying resource doesn't update it's last updated timestamp

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#1874]
Resources show their creation date and last updated date which are the same. If the resource is modified, the last updated date should change but it is not updated.

**Comment by wardi** [comment]
I think we should update this value when users upload files too. It's displayed to end users as the resource's "last updated" date, and users expect that date to change when they upload a new file.

**Comment by augusto-herrmann** [comment]
I think the meaning and presentation of the fields should be more clear and consistent.

last_modified: the date and time when the actual data has been last changed
revision_timestamp: the date and time when the resource metadata has been last changed

If this is the correct meaning for the fields, the visual label on the templates for the resource should be consistent with that:

last_modified -> "Data last updated"
revision_timestamp -> "Metadata last updated"

Currently these fields are used interchangeably to display the same label "Last updated". See

`<td>{{ h.render_datetime(res.last_modified) or h.render_datetime(res.revision_timestamp) or h.render_datetime(res.created) or _('unknown') }}</td>`
https://github.com/ckan/ckan/blob/master/ckan/templates/package/resource_read.html#L158

**Comment by dmichelakis** [comment]
I just noticed that the last modified date does not update when editing or replacing a link in a resource but does change when editing or replacing a file. Is this a bug or is this suppose to happen?
