### ISSUE TITLE
Failed to Load Proxy Related JavaScript Files

### ISSUE THREAD

**Issue by mlpassos** [ckan/ckan#1884]
Hi there,

First of all congratulations on the terrific work with CKAN. It's superb.

Also, sorry if this has already been pointed out ( erase the issue please :] ), but if it doesn't, in proxy enabled enviroments, CKAN fails to load some JS files like jquery-proxy-all, because of the "proxy" keyword being blacklisted in most proxy servers and firewalls. 

I know it's a local issue but I guess some work-around would be nice. Maybe? =]

That's all for now... keep up the excelent work you guys!

Cheers from Brazil!!!

**Comment by wardi** [comment]
I apologise for not getting back to you!

I can't see merging a change just to accommodate deep-packet-inspecting firewalls that block a list of "naughty" words, so I'm closing this issue.
