### ISSUE TITLE
Make consistent all forms of RDF output from CKAN

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckan#1890]
## Problem

CKAN currently has 3 kinds of RDF output, all completely different from each other.

a) RDFa

Descrbes the dataset by using Dublin Core and Open Graph vocabularies. Only very minimal metadata is displayed. At least it does link to the resources of the dataset. See, e.g., with RDFa Distiller:

http://www.w3.org/2012/pyRdfa/extract?uri=http%3A%2F%2Fdatahub.io%2Fdataset%2Fminas-gerais-spending-data&format=turtle&rdfagraph=output&vocab_expansion=false&rdfa_lite=false&embedded_rdf=true&space_preserve=true&vocab_cache=true&vocab_cache_report=false&vocab_cache_refresh=false

b) N3

Describes the dataset with DCAT alongside Dublin Core and FOAF. But it's a buggy mess. Has unprocessed template code in place of URIs. Has leftover placeholder text (i.e. every dataset in existence has `foaf:homepage <http://127.0.0.1:5000/dataset/testt>`). See, e.g.,

http://datahub.io/dataset/minas-gerais-spending-data.n3

c) RDF/XML

This is a little better and uses DCAT, DC and FOAF to display some more metadata (such as resources titles). See, e.g.

http://datahub.io/dataset/minas-gerais-spending-data.rdf

I think this should be fixed in future versions of CKAN, to make RDF support for the catalog metadata more consistent.

## Proposed solution

1. Have an internal mapping of every property of the data structures of CKAN (catalog, groups, organizations, datasets and resources) to RDF. Possibly reuse some of what already existing ones in [ckanext-dcat](https://github.com/ckan/ckanext-dcat/blob/master/ckanext/dcat/converters.py).

2. Change the html templates to use these mapping for generating the RDFa markup.

3. Also change the templates that output .rdf and .n3 to use the same mappings.

Then RDF would be consistent among all three formats.

**Comment by rossjones** [comment]
Given we now have ckanext-dcat, and there has been no PR for microdata ..

----

This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.

**Comment by danbri** [comment]
Related - see https://github.com/ckan/ckanext-dcat/issues/75#issuecomment-264140088 where I propose handling Schema.org (likely in JSON-LD) alongside DCAT. I'd argue that this would then be a strong candidate for going into core, but step-by-step eh? :)

FWIW I agree with @cygri's comment above that there is scope for multiple different kinds of RDF description. I suggest the unification we should look for is not in terms of getting a single kind of description, but more on the software engineering side - it would be counter productive to have for example a schema.org-oriented addon and the DCAT addon competing for attention, installation, distribution. While I would love to have schema.org support within CKAN HTML pages it would be counter-productive for that to come at the cost of undermining DCAT's existing deployment success.

See also https://developers.google.com/search/docs/data-types/datasets which outlines our current focus at Google on these issues. It follows our general focus on schema.org but anticipates at least some partial DCAT support (at least in Microdata/RDFa/JSON-LD; Turtle would probably require a clientside Javascript convertor).
