### ISSUE TITLE
Customizing Docker images doesn't work as described in the documentation

### ISSUE THREAD

**Issue by cygri** [ckan/ckan#1904]
The Docker installation instruction has a [section on customising the image](http://docs.ckan.org/en/latest/maintaining/installing/install-using-docker.html#customizing-the-docker-image)

The example shows a custom `ckan.ini` being added to the image.

But this can't work. In the Docker startup (`/contrib/docker/myinit.d/50_configure`), there is a check whether a `ckan.ini` is already present. If not, then a new one is created, and initialised with the Solr and Postgresql coordinates. But if a `ckan.ini` *is* already present, then it is not touched and the connection information is not updated.

The effect is that when you run the example image, the startup script leaves `ckan.ini` untouched, and CKAN startup will fail because the Solr and Postgresql connection information is still pointing to whatever was in the custom ini file.

To get a custom image working, I had to build my own CKAN base image with a modified `50_configure` file. I changed the logic so that it will *always* run those gnarly `sed` commands, even if a `ckan.ini` is already present.

See this commit: [Always update ckan.ini with DATABASE_URL and SOLR_URL](https://github.com/cygri/ckan/commit/b317d4b2338e4c9c8c40bd085c025bd078837389)

(My base image is for CKAN 2.2, which is what we currently use. The Docker stuff from `master` worked on 2.2 without changes.)

**Comment by wardi** [comment]
core docker instructions have been removed as unmaintained
