### ISSUE TITLE
Index resource name in Solr

### ISSUE THREAD

**Issue by george-sattler** [ckan/ckan#1905]
The resource name is not indexed and thus not searchable.
Example: If a resource is created with the name, 'my interesting resource', the resource can not be found by searching for the term 'interesting'. 

Currently the best solution for someone wanting to make the resource searchable by the name, would be to duplicate the name in the resource Description field.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
