### ISSUE TITLE
group and org update: treat missing 'users' key as "don't change"

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#1907]
This is a breaking change to the `group_update` and `organization_update` APIs for anyone that relies on clearing the list of users in organizations and groups, but enables the much more common use of changing some organization fields without changing the list of users.

There is currently a workaround in the ckanapi cli that allows this behaviour when running 'ckanapi load organizations ..' from a master list.

Raised by @joetsoi yesterday

**Comment by wardi** [comment]
@joetsoi do you still have this change in a branch somewhere?

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
