### ISSUE TITLE
Allow homepage placeholder to be modified in the admin UI

### ISSUE THREAD

**Issue by marks** [ckan/ckan#1912]
Currently, you can change the home page image in https://github.com/ckan/ckan/blob/master/ckan/templates/home/snippets/promoted.html while the text can be edited in the Admin UI. 

@wardi and I agree that this should be able to be done from the Admin UI:

> 9:16 AM <SkramX_> whats the rationale for not letting that be changed in the online system like the text right above it?
> 9:25 AM <wardi> SkramX: good question. want to submit a pr to change that?

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
