### ISSUE TITLE
Page view tracking update issues with recent_views

### ISSUE THREAD

**Issue by FuhuXia** [ckan/ckan#1913]
If a dataset is not visited, the recent_views should decrease and eventually reset to 0 after 14 days. This is not the case based on the current implementation.

If a dataset is not visited, it won't get into `tracking_raw` and `tracking_summary` tables, therefore `running_total` and `recent_views` will not be updated.

Please confirm my finding, and I will submit a Pull Request to patch the issue. Thanks.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by Gauravp-NEC** [comment]
@FuhuXia,  I have followed the doc: https://docs.ckan.org/en/2.7/maintaining/tracking.html#enabling-page-view-tracking and enabled page view tracking in CKAN v2.7.12. I am trying to get the tracking summary of dataset using package_show() API i.e., curl http://localhost:5000/api/3/action/package_show?id=[ ]&include_tracking=true , but tracking_summary is not included in the API response. How can I get the tracking_summary?

**Comment by FuhuXia** [comment]
@Gauravp-NEC The only thing I can think of is that you haven't run commands `tracking update` and `search-index rebuild` at least once?
