### ISSUE TITLE
Documentation for ckan.site_about config option is misleading

### ISSUE THREAD

**Issue by cygri** [ckan/ckan#1927]
Problems with the documentation for `ckan.site_about`:

1. It turns out you can't have empty lines in ckan.ini configuration options. Empty lines in multi-line ini values [will be swallowed by the config file parser](http://python.6.x6.nabble.com/ConfigParser-and-newlines-td1565679.html). There should be a warning about this.
2. The documentation shows a default value for this option, but it's incorrect. The default value of the config option is (none). The value shown is the *HTML* snippet that CKAN uses if the option is *not set*. Its presence here suggests that HTML markup such as `<p>` can be used in CKAN's Markdown syntax to work around the problem above, but that doesn't work either because such HTML markup is stripped. The docs should state that the default is (none), and the misleading HTML snippet should be removed.

I note that in practice, these issues make the `ckan.site_about` option is unusable from the ini file. The documentation should IMO discourage users from trying to use this option in the ini file, and instead refer them to other ways of setting the about page contents, in particular through the Administration config form.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
