### ISSUE TITLE
Docker image for Solr doesn't build due to use of schema.xml symlink

### ISSUE THREAD

**Issue by cygri** [ckan/ckan#1933]
Background: There's a Dockerfile for Solr in `contrib/docker/solr`. This is used to build the official CKAN Solr image available on the Docker Hub as `ckan/solr`. The directory contains a symlink to the Solr `schema.xml`, as that file is needed to build the image. However, this doesn't actually work, because Docker [doesn't allow symlinks](https://github.com/docker/docker/issues/1676) (nor any other way of referring to files outside of the Dockerfile's directory) here, so `docker build contrib/docker/solr` will fail with an error about `schema.xml` not being found.

As a workaround, replacing the symlink with a simple copy of the file does work, but then we have two copies of the same file in the repository.

Other alternatives:

- Move the Dockerfile to the same directory as `schema.xml`: `ckan/config/solr`. Then build the Solr image from there.
- Remove the Solr Dockerfile altogether from the `ckan` repository, and put it into a separate git repository that has the `ckan` repository as a git submodule. Then have the Dockerfile reference the `schema.xml` in the submodule.

**Comment by wardi** [comment]
core docker instructions have been removed as unmaintained
