### ISSUE TITLE
Create an "Account Lockout" mechanism

### ISSUE THREAD

**Issue by adamamyl** [ckan/ckan#1939]
Security best-practice is including the idea to lock users out of accounts after n tries (between 3-5) -- usually within a defined time period. At the moment, this would be hindered by CKAN. And in particular, the 'states' user accounts can be in. 

It might be useful to extend the model we have around users, to include a locked-out user type (e.g., for those who've been suspended (by an admin) or locked out (due to say, brute-force'ing password attempts -- or PEBKAC).

(2.3 : can't add labels here)
(origin: pentest)

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.
