### ISSUE TITLE
Cannot sort the recline grid on fields containing spaces

### ISSUE THREAD

**Issue by aliceh75** [ckan/ckan#1961]
`DatastorePlugin._is_valid_sort` and `DatastorePlugin._sort` both expect field names to be escaped (using quotes). This is obvious from the usage of `shlex.split`.

However the recline grid sends the sort string with un-escaped field names. This causes sorts on fields with spaces in them to fail.

Given that:
- This is an API, not an SQL interface, the intuitive approach is to not quote field names;
- Other parts of the API (for instance when selecting fields to return) expect fields to not be escaped
I think the best in terms of consistency is to not escape the fields for the sort string.

For backward compatibility, the API could handle both.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
