### ISSUE TITLE
Numeric column with field with whitespace is recognized as timestamp

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1964]
This is the CSV:

```csv
value,timestamp
28,3121545343
77,2312511241
,3213465345
 ,3213465345
```

The Datastore recognizes it as:

```python
[
  {'type': u'timestamp', 'id': u'value'},
  {'type': u'numeric', 'id': u'timestamp'}
]
```

**Comment by Aaron-M** [comment]
#1963 Added another example of data wrongly interpreted by Datapusher/Datastore (value A8301 interpreted as a date/time...)

**Comment by amercader** [comment]
We have improved the information on messages on #2145 for 2.3. On next releases we can try and improve the actual handling of wrong data. Bumping the milestone for now.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
