### ISSUE TITLE
Crash when site_url not set

### ISSUE THREAD

**Issue by seanh** [ckan/ckan#1976]
Lots of stuff breaks with site_url is not set in the config file. Email notifications, FileStore... Make site_url mandatory and make CKAN crash at startup if it's not set or not valid.

**Comment by Jan-Marcek** [comment]
Hi 
https://github.com/ckan/ckan/commit/4a046aee93e78d69362e3abc02df780ba8890f3d#commitcomment-9821429

I'll be really grateful to hear a answer from you guys.

**Comment by davidread** [comment]
Done

**Comment by rossjones** [comment]
The original problem seems to have been fixed by #1976
