### ISSUE TITLE
Add phrase search to datastore

### ISSUE THREAD

**Issue by aliceh75** [ckan/ckan#1979]
Hello,

It would be nice to be able to have phrase search when doing datastore searches - that is, being able to search for exact phrases by surrounding them in double quotes as is common. 

This is actually quite easy to implement, and can be implemented in a plugin (see below). However I was wondering if it wouldn't be better in core? Let me know if so, and I'll do a PR for this. Otherwise I'll create a new plugin.

How to implement: In a plugin, implement `IDatastore` and in `datastore_search` add the code:

```python
        if 'q' in data_dict and not isinstance(data_dict['q'], dict):
            for match in re.findall('"[^"]+"', data_dict['q']):
                query_dict['where'].append((
                    '"{}"::text LIKE %s'.format(resource['id']),
                    '%' + match[1:-1] + '%'
                ))
```

Note that we don't modify the existing query statements - this way we benefit from the full text search indexes which reduce the dataset before we do the LIKE query.

**Comment by wardi** [comment]
Marking good for contribution.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
