### ISSUE TITLE
registration form validation, confusing reference to "Url"

### ISSUE THREAD

**Issue by harry-wood** [ckan/ckan#1980]
Minor thing. When you're registering an account on ckan, and you choose a bad user name, it gives you the message
"Name: Url must be purely lowercase alphanumeric (ascii) characters and these symbols: -_"

Which is confusing... "what Url?"  ...It should say "username must be"

...But then this is part of generic validation logic for various object types ([here?](https://github.com/ckan/ckan/blob/19565de81e70173270052c1e34e89ed5dd76b5c2/ckan/logic/validators.py#L350)), so maybe this is a low impact pain-in-the-ass to fix bug. Feel free to ignore.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
