### ISSUE TITLE
Un-mingle bootstrap from main.css

### ISSUE THREAD

**Issue by johnmartin** [ckan/ckan#1993]
Needed as prefix to #1849

**Comment by wardi** [comment]
there's no PR for this branch https://github.com/ckan/ckan/compare/1993-unmingle-bootstrap has this been abandoned?  Possibly related to #2602

**Comment by LaurentGoderre** [comment]
I don't think we will need for the upgrade.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
