### ISSUE TITLE
Recline preview calls datastore_search three times when once would suffice

### ISSUE THREAD

**Issue by aliceh75** [ckan/ckan#2009]
1. The problem
--------------------

When viewing the grid preview for a dataset, the Recline grid component makes three calls to the `datastore_search` API. This can be a major performance issue when doing slow queries (two of the three queries are identical and include all the search terms).

2. How to reproduce
--------------------------

From a browser with development tools, look at the network connections made when opening a grid preview page. The last three connections are three POST calls to `datastore_search/api/3/action`.

For example, if searching for the word 'little', the following three queries are made:

1. **Request URL**: `http://.../api/3/action/datastore_search`

    **Form Data**: `{"resource_id":"...","q":"little","filters":{},"limit":100,"offset":0}`

2. **Request URL**: `http://.../api/3/action/datastore_search`

    **Form Data** `{"resource_id":"...","filters":{},"limit":10,"offset":0}`

3. **Request URL**: `http://.../api/3/action/datastore_search`

    **Form Data**: `{"resource_id":"...","q":"little","filters":{},"limit":100,"offset":0}`

Not only are there three requests when one would suffice, two of them are actually the same. Performance wise, this can be quite a significant hit - and it is not possible to cache the result of the query when the third query is fired before the first one has finished.

3. Notes
-----------

The second query is generated by Recline. While it is not necessary, I'm not so concerned about that one as it is always the same for a given dataset and be cached easily.

The first and the third query on the other hand and generated because of CKAN code, and include custom search terms so cannot be cached easily. I will create a PR for this.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.
