### ISSUE TITLE
Allow sort option in all recline views

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#2030]
As it is, certain [recline.js query attributes](http://okfnlabs.org/recline/docs/models.html) are already supported (e.g. offset, filters, size, etc.).

This is especially useful in creating map and chart views (e.g. sort by date, and render the newest 500 records), if the user does not want to do the data explorer view where sorting can be done interactively.

Of course, creating a flexible sort interface in in the view forms is non-trivial.  Perhaps, just give the user a text field where they can enter the sort expression?

**Comment by mattfullerton** [comment]
:+1:

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
