### ISSUE TITLE
Use DataExplorer grid type interface when defining views

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#2032]
It'd be nice to use something like the classic DataExplorer grid tab to interactively define the data that will be rendered by a view.

Right now, the view definition forms are form-driven and not interactive.

This will make view definition more intuitive, and solves the issue of how to create a sorting UI for recline views (#2030)

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
