### ISSUE TITLE
Add crosstab/pivot resource view

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#2039]
Right now, the current views are primarily UI-type views (e.g. maps, charts, etc.)

What about adding a pivot view of the data using PostgreSQL's tablefunc function?
http://stackoverflow.com/questions/3002499/postgresql-crosstab-query

This will be quite useful in showing aggregations using pivot tables.  These aggregations are better suited to doing visualizations anyway.

And to make sure the crosstab query is up-to-date and performant, it can be defined in the datastore as a PostgreSQL materialized view.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by jqnatividad** [comment]
Reopening this as its now possible with https://github.com/ckan/ckan/tree/3816-query-based-views!

We actually were able to do pivot tables in testing, but we had to install the tablefunc module.
https://www.compose.com/articles/metrics-maven-creating-pivot-tables-in-postgresql-using-crosstab/

It not a resource view though, but a query-based CKAN resource.
