### ISSUE TITLE
Document CKAN data model

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2053]
Here's a start with the bits that I feel are most important:

![ckan_data_model](https://cloud.githubusercontent.com/assets/153258/5126883/8a7a06f0-709e-11e4-9e53-c0dcd26ebf1c.png)

Source: https://gist.github.com/wardi/201c5c768ca7cc9495a7

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
