### ISSUE TITLE
Really long file names kill the datapusher

### ISSUE THREAD

**Issue by tobes** [ckan/ckan#2057]
if you upload a resource in CKAN and the file name is very long (over 90ish chars) then the datapusher gets called with a url that causes a 500 error  (the url contains a truncated filename).

I am not sure if the url is incorrectly produced or that the datapusher has issues around trying to get the extension for the file type.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
