### ISSUE TITLE
Further Mapping Drupal and Other CMS Integration Points

### ISSUE THREAD

**Issue by acouch** [ckan/ckan#2074]
I was talking to Steven De Costa who is interested in spreading the word about CKAN with other open source communities including the Drupal community. I think cataloging some of the existing integration points would be helpful with that effort and helpful for adopters in general.

Creating this ticket to start that. If there is a more appropriate place to organize this let me know.

EDIT:

Seems like comments here aren't the best format. I've created a google sheet that should be editable by anyone: https://docs.google.com/a/nuams.co/spreadsheets/d/1hCsU_tWd_SiQGnLIM-ZunDmVdc3udxTq8PIgeSplQxs/edit#gid=0

Please update or comment.

**Comment by davidread** [comment]
Moved to https://github.com/ckan/ideas-and-roadmap/issues/76
