### ISSUE TITLE
Error when I store a new data in his set

### ISSUE THREAD

**Issue by mariohm** [ckan/ckan#2081]
Hello, 
sometimes, I've got an error when I put a CSV data in a set. The file, that I upload, always has got the same style and format.
This is the error in the datastore:

Error: [u' File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job\n retval = job.func(*job.args, **job.kwargs)\n', u' File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 278, in push_to_datastore\n row_set = table_set.tables.pop()\n', u"IndexError('pop from empty list',)"]

And in the log's file:

[Fri Nov 21 12:10:18 2014] [error] Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
[Fri Nov 21 12:10:18 2014] [error] Traceback (most recent call last):
[Fri Nov 21 12:10:18 2014] [error] File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _ru$
[Fri Nov 21 12:10:18 2014] [error] retval = job.func(*job.args, **job.kwargs)
[Fri Nov 21 12:10:18 2014] [error] File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 278, in push_to_datastore
[Fri Nov 21 12:10:18 2014] [error] row_set = table_set.tables.pop()
[Fri Nov 21 12:10:18 2014] [error] IndexError: pop from empty list

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
