### ISSUE TITLE
datastore plugin lame write test

### ISSUE THREAD

**Issue by teodorescuserban** [ckan/ckan#2082]
Hi guys,

Datastore plugin is testing for write permission by creating a table named _foo and then drop it.

However, this creates a race condition when ckan is running on more than one thread, making the other(s) thread's datastore plugins init error out with "table _foo already exists".

Suggestion: use a pseudo random name for the table.

Thank you!

**Comment by wardi** [comment]
@teodorescuserban it looks like you've worked on a fix but I don't see a pull request. Would you mind creating that?

**Comment by teodorescuserban** [comment]
I was sure this was fixed somewhere in 2.3. We backported the exact
solution to our 2.2.
But I will double check, Ian.

Mar, 12 ian. 2016, 17:17, Ian Ward <notifications@github.com> a scris:

**Comment by wardi** [comment]
even better! closing
