### ISSUE TITLE
API: Specifying groups by title for adding datasets doesn't work

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckan#2089]
the docs say:
groups (list of dictionaries) – the groups to which the dataset belongs (optional), each group dictionary should have one or more of the following keys which identify an existing group: 'id' (the id of the group, string), 'name' (the name of the group, string), **'title' (the title of the group, string)**, to see which groups exist call group_list()

However, specifying the group by title is not foreseen in the code, and this does not work

**Comment by jrmyr** [comment]
Hello,
in our ckan project we need to define groups by title.
I did a little fix for the 'package_membership_list_save' method which is working well.
Would you be interested in getting it? Maybe it's useful for other people as well. If yes, how shall I provide it?

**Comment by mattfullerton** [comment]
I doubt group _titles_ have to be unique in CKAN, even though it would seem sensible to enforce that as well.

**Comment by jrmyr** [comment]
In our use case, group titles are unique. So it does not matter if CKAN enforces it or not.
Maybe it could be enough to check if a title is unique at ingestion time. As long as titles are unique, everything is fine, if not the package is rejected and the user is adviced to use name or id reference.
This would be my suggestion. Don't know if this is reasonable from CKAN's business point of view.
