### ISSUE TITLE
Nav pills are mis-aligned with grey/fuzzy font

### ISSUE THREAD

**Issue by florianm** [ckan/ckan#2099]
In CKAN 2.3a, nav pills "Datasets", "Organisations" etc. and the search box align to the navbar's top rather than centering it vertically as it was in 2.2 which looked better.

The nav pills and search box can be centered vertically again by adding a .content div wrapping blocks `header_site_navigation` and `header_site_search` in template header.html.

The css defines .navbar .nav > li > a with color #777777 and text-shadow, which makes the font fuzzy and poor in contrast. Unless there was a reason to change the font, a color:white and text-shadow:none (or dropping both rules entirely) would make the nav pills much more readable. I guess that needs to be fixed in all five themes.

Should I submit a pull request or could someone fix these four lines?

**Comment by brew** [comment]
Fixed in ea816a9145d037e45d7d6457b9dcc8050133e4a7.
