### ISSUE TITLE
datastore_search_sql chokes on resources containing registered trademark symbol

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#2103]
If we upload a file resource containing a registered trademark symbol (hexadecimal representation ae), datastore_search_sql fails to retrieve it with an error like the following:

Error - <type 'exceptions.UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xc5 in position 492: ordinal not in range(128)

**Comment by arirusakko** [comment]
Hello
I've just tackled a bug in our ckan installation (2.3-8) for datastore API's search_sql not handling utf8 characters.
Basically this manifests as "internal server error" when you do a GET query like this:
http://<site>/api/action/datastore_search_sql?sql=%C3%A4
(That's character 'ä')

Solution was to edit /usr/lib/ckan/default/src/ckan/ckanext/datastore/helpers.py
...and change line 82 containing:
'EXPLAIN (FORMAT JSON) {0}'.format(sql)).fetchone()

..to:
u'EXPLAIN (FORMAT JSON) {0}'.format(sql)).fetchone()

I suspect it might solve this issue too.

**Comment by u10313335** [comment]
I also have the problem that @arirusakko stated and fixed using the same method.

**Comment by NicolaiMogensen** [comment]
Can confirm that the fix @arirusakko stated worked like a charm (Was trying to include the danish æ ø å characters)

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
