### ISSUE TITLE
memory leak on master

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2109]
We've had multiple reports of ckan (datastore?) memory leak. I've used https://pypi.python.org/pypi/meliae before to dig in to memory usage.

**Comment by wardi** [comment]
@joetsoi I guess this is a duplicate of #1847 @george-sattler was able to reproduce on production it seems, and most memory was consumed by strings like what you're seeing

**Comment by wardi** [comment]
closing based on https://github.com/ckan/ckan/issues/1847#issuecomment-70132484

Our only fix might be to set a maximum response size, or stream the data instead of creating massive strings in memory. Those are new features not a memory leak.

**Comment by amercader** [comment]
Although it may well be, I'm not entirely sure that this and #1847 are the same issue. This was originally reported on master.ckan.org, a low traffic standard deploy, and @george-sattler tests involved uploading a file and push data to the DataStore. If I understood correctly @joetsoi reasoning on #1847 the problem occurred when requesting massive responses in succession. This doesn't seem to fit @george-sattler test case (unless I misunderstood)
No need to reopen, but let's keep an eye on master to see if the issue reappears
