### ISSUE TITLE
Assumption in logic/auth/create.py can lead to internal error

### ISSUE THREAD

**Issue by clementmouchet** [ckan/ckan#2120]
Just came across a  case where CKAN would die on a logic.NoFound without explanation when I'm adding a dataset as an Editor of an organisation. (on an up to date master, with ckanext-scheming is enabled)

I traced the bug in `logic/auth/create.py` : `resource_create(context, data_dict)`

```python
    package_id = data_dict.get('package_id')
    if not package_id and data_dict.get('id'):
        # This can happen when auth is deferred, eg from `resource_view_create`
        resource = logic_auth.get_resource_object(context, data_dict)
        package_id = resource.package_id

    if not package_id:
        raise logic.NotFound(
            _('No dataset id provided, cannot check auth.')
        )
```

There is an assumption that if `package_id` is not present, a resource will be found, and therefore we can get a package id. If no resources are found, you get a logic.NoFound which is not caught and leads to an internal error.
I fixed the immediate issue by adding a try catch. In my case the package id is passed as `id`, if I get a NoFound exception, I us the key id as a package id, and leave the next block do the check.

```python
    package_id = data_dict.get('package_id')
    if not package_id and data_dict.get('id'):
        # This can happen when auth is deferred, eg from `resource_view_create`
        try:
            resource = logic_auth.get_resource_object(context, data_dict)
            package_id = resource.package_id
        except logic.NotFound:
            package_id = data_dict.get('id')

    if not package_id:
        raise logic.NotFound(
            _('No dataset id provided, cannot check auth.')
        )
```

The advantage of that call is that you get a proper message, and it doesn't really change the behaviour of the check.

Let me know if you want me to submit a PR for that.

---

Portal details:
```javascript
ckan_version: "2.3a",
site_url: "http://ckan.localdomain",
locale_default: "fr",
extensions: [
"datastore",
"datapusher",
"archiver",
"harvest",
"ckan_harvester",
"stats",
"synchronous_search",
"resource_proxy",
"text_view",
"recline_view",
"recline_grid_view",
"recline_graph_view",
"recline_map_view",
"pdf_view",
"viewhelpers",
"dashboard_preview",
"linechart",
"barchart",
"piechart",
"navigablemap",
"choroplethmap",
"spatial_metadata",
"spatial_query",
"cnaf_theme",
"geoconverter",
"geojson_preview",
"hierarchy_organization_form",
"hierarchy_group_form",
"hierarchy_display_forms",
"dcat_rdf_harvester",
"dcat_json_harvester",
"dcat_json_interface",
"scheming_datasets",
"disqus"
]
```

**Comment by amercader** [comment]
> In my case the package id is passed as `id`

@clementmouchet @florianm I'm sure there is something to fix there but I don't understand why the `package_id` should ever come from `data_dict['id']`. This is the `resource_create` auth function so I not see why it should receive a dataset dict instead of a resource dict. Where is `auth.resource_create` called from? Can you check your traceback without this patch?

Perhaps the wrong parameters are passed to the function somewhere, but this is where we should look to fix it.

Thanks

**Comment by amercader** [comment]
I've just found a similar issue on the 2.2.2 branch: c40c171ce12de02 Is this the version you are running? (2.2.x)

**Comment by clementmouchet** [comment]
Nope, was on 2.3 (release2.3) and master previously

Cheers

Clément

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
