### ISSUE TITLE
Changing dataset org to 'No organization' causes exception when attempting to add resource

### ISSUE THREAD

**Issue by brew** [ckan/ckan#2124]
1. From the Create Dataset interface (/dataset/new), complete Step 1 to create a dataset with an organization, with a visibility set to 'private'
2. Go back and edit the dataset so it has no organization: note, the ui appears to change the visibility to 'public'
3. Attempt to add a resource

This results in a `KeyError` when trying to return the value for `resources` from the `e.error_dict` of a `ValidationError` ([relevant code](https://github.com/ckan/ckan/blob/0fef8f5802ed964d58a3f593085a55914cb803f6/ckan/logic/action/create.py#L285-L286)) :

```bash
File '/Users/brew/virtualenvs/ckan2.6/src/ckan/ckan/controllers/package.py', line 708 in new_resource
  get_action('resource_create')(context, data)
File '/Users/brew/virtualenvs/ckan2.6/src/ckan/ckan/logic/__init__.py', line 424 in wrapped
  result = _action(context, data_dict, **kw)
File '/Users/brew/virtualenvs/ckan2.6/src/ckan/ckan/logic/action/create.py', line 286 in resource_create
  errors = e.error_dict['resources'][-1]
KeyError: 'resources'
```

The original `ValidationError` occurs because the dataset is no longer part of an organisation, but is still private (despite what the ui indicated):

```python
>>> e
ValidationError()
>>> e.error_dict
{'private': [u"Datasets with no organization can't be private."]}
```

**Comment by brew** [comment]
Editing a private dataset by removing `owner_org`, so that it no longer belongs to an organisation, isn't being correctly validated by `ckan.logic.validators.datasets_with_no_organization_cannot_be_private`.

It looks like only sysadmins are able to change a dataset's owner_org from the package edit page, as a `check_access('sysadmin')` check is performed before rendering the organization dropdown.

Form data being passed to `datasets_with_no_organization_cannot_be_private` may not contain data for `owner_org` (for example, when a user has no organisations that they are entitled to add datasets to), so the validator is instead fetching the dataset with `package_show` and checking for `owner_org` in the resulting dataset dict. At this point the dataset will still have an `owner_org` so the validator passes, although the intension of the user is to remove `owner_org` and have the validator fail because `private` is true.

As only sysadmins can (currently) make this change, perhaps it's enough to ensure that the private dropdown is forced to public if no organization is selected. There is currently an attempt to do this, but it disables the whole dropdown, which means the new public value isn't submitted.

Related to #1188 and #2218 and #953.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
