### ISSUE TITLE
refactor fanstatic_resources

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2126]
fanstatic_resources is a module being used as a dictionary with setattr/getattr. It's also a module that contains code for interacting with fanstatic. The attribute names used with setattr/getattr are URL paths e.g. 'mystaticdir/foo.css'.

I suggest we separate the resource-dictionary from the module containing fanstatic interface code.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
