### ISSUE TITLE
Fix/Remove TestActionAuth

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2128]
TestActionAuth (in test_coding_standards.py) checks whether each action has a corresponding auth function, not all do. In additing auth functions for these just returning success: True is probably the right thing to do so that they can easily be overridden. Otherwise these *may* cause problems when trying to override auth functions unless the auth_audit_exempt decorator is used.  

Sometimes it is because actions like organization_activity_list check auth against organization_show, perhaps we should have the organization_activity_list auth function and have *it* decide to delegate to organization_show?

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
