### ISSUE TITLE
Eradicate use of c.pkg

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2132]
c.pkg is the most user occurring instance of sqlalchemy models being passed to the templates alongside pkg_dict.  Persuading everyone to stop using c in extensions would take a very long time, but at least we can remove the Package model from the context passed to the template.  We can then stop package_show stuffing the Package model into the context that it was passed.

This would be a breaking change, so perhaps some notice in an upcoming version and then removal in the next would be a good approach.

**Comment by davidread** [comment]
General agreement - let's pick this off as we come across it.
