### ISSUE TITLE
Datastore doesn't update if we upload file a new but it has same name as the existing file.

### ISSUE THREAD

**Issue by tobes** [ckan/ckan#2147]
I have a fix for this to follow

If we change a resource by uploading a new file and it has the same name ckan does not see the resource as having changed and therefore there is no trigger for IResourceUrlChange therefore we do not update the datastore

**Comment by wardi** [comment]
@tobes I've fixed this a different way in #2519, let me know if this works for you.

**Comment by tobes** [comment]
@wardi shall we close this?

reopen if you disagree
