### ISSUE TITLE
Solr error when adding a new resource to an existent dataset

### ISSUE THREAD

**Issue by jgrocha** [ckan/ckan#2161]
Hi,

I've installed last CKAN from source and when I was adding a second resource to an existing dataset, the SOLR complains with the error: `multiple values encountered for non multiValued field res_name`

I'm using the schemas provided in `ckan/ckanext/multilingual/solr/`

To solve this problem, I added the following line to `ckan/ckanext/multilingual/solr/schema.xml`: `<field name="res_name" type="textgen" indexed="true" stored="true" multiValued="true"/>`

I'm quite new to CKAN, so please check if this is really a problem with CKAN or with the Solr configuration. Probably it is just a problem with my installation.

**Comment by metaodi** [comment]
Any update on this issue? cc @davidread @rossjones

**Comment by rossjones** [comment]
I think it's waiting for someone to submit a PR. Perhaps @davidread might add the 'Good for contribution' label?

**Comment by davidread** [comment]
The fix was merged and went into ckan 2.4 release, so closing.
