### ISSUE TITLE
Cannot Purge a Package That Has Been in a Relationship

### ISSUE THREAD

**Issue by jayhuggins** [ckan/ckan#2186]
I have a package that was the object of a depends_on relationship.  The relationship was deleted, then the package was deleted, but I cannot purge this package from trash because of the persistent foreign key constraint in package_relationship_revision.  Here's the error message:

Problem purging revision 96e0eff2-25c6-458a-a9ec-8585689fe72a: (IntegrityError) update or delete on table "package" violates foreign key constraint "package_relationship_revision_object_package_id_fkey" on table "package_relationship_revision" DETAIL: Key (id)=(9b72f897-3518-49ae-8bc4-f15e2c842cef) is still referenced from table "package_relationship_revision". 'DELETE FROM package WHERE package.id = %(id)s' {'id': u'9b72f897-3518-49ae-8bc4-f15e2c842cef'}

and here are the relevant table rows (which I will delete to get around this issue):

select \* from package_relationship_revision where object_package_id='9b72f897-3518-49ae-8bc4-f15e2c842cef';

```
              id                  |          subject_package_id          |          object_package_id           |    type    | comment |             revision_id              |            continuity_id             |  state  |              expired_id              |     revision_timestamp     |     expired_timestamp      | current 
```

--------------------------------------+--------------------------------------+--------------------------------------+------------+---------+--------------------------------------+--------------------------------------+---------+--------------------------------------+----------------------------+----------------------------+---------
 6c283d69-b16d-4dff-ab7a-ba1800b45c2e | 97c3d54d-7ff6-4434-ac50-b31e34aac34e | 9b72f897-3518-49ae-8bc4-f15e2c842cef | depends_on |         | c36adebf-de1e-4150-a38e-803beb3b4594 | 6c283d69-b16d-4dff-ab7a-ba1800b45c2e | deleted |                                      | 2014-09-29 20:59:54.309275 | 9999-12-31 00:00:00        | t
 6c283d69-b16d-4dff-ab7a-ba1800b45c2e | 97c3d54d-7ff6-4434-ac50-b31e34aac34e | 9b72f897-3518-49ae-8bc4-f15e2c842cef | depends_on |         | 4737f0a4-e7c9-46f7-b911-0f256fb2504f | 6c283d69-b16d-4dff-ab7a-ba1800b45c2e | active  | c36adebf-de1e-4150-a38e-803beb3b4594 | 2014-09-29 20:59:20.227423 | 2014-09-29 20:59:54.309275 | f
(2 rows)

**Comment by rossjones** [comment]
We need to address purging in it's entirety.  This involves

* Purging packages and groups/organisations entirely
* Making ckan-admin trash work.
* Making sure we have action methods for all the purges.
* Making sure we have CLI commands for all the purges.

We may as well fix all of these at once.

**Comment by wardi** [comment]
related work for purge and member #2460

**Comment by gleb-rudenko** [comment]
@wardi, is it still topical or can be closed?

**Comment by wardi** [comment]
@jackmaney was this not fixed by #3112 ? What version are you using, what error are you seeing and what steps did you take to trigger the issue?

**Comment by jackmaney** [comment]
Looks like we're on version 2.5.2 of the API (according to the `CKAN API` link at the bottom of the server's main page). 

I had two tables with a `parent_of` relationship, I deleted them both, but when I tried to purge either one, I got essentially the same error message as @jayhuggins above.

Has #3112 been merged into a release since 2.5.2?

**Comment by wardi** [comment]
Looks like it hasn't been backported to 2.5.x . @amercader any objection to backporting to 2.5?

**Comment by TkTech** [comment]
@wardi #3112 does *not* resolve this issue. This issue relates to revisions of relationships, not the relationship itself. We need to go one level deeper :(

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
