### ISSUE TITLE
RFE: include hidden form fields when confirming actions

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#2187]
We would like to implement token-based CSRF protection on POST requests; however, actions that involve confirmation (like deleting a resource) use JavaScript to assemble a POST without incorporating the token.

Would it be reasonable for confirmation requests to incorporate all hidden fields from the form containing the link that was clicked?

Suggested implementation is to add the following line to performAction function in confirm-action.js, immediately after constructing the form (line 69 as at 2015-01-07):

    $(this.el).closest('form').find('input[type=hidden]').appendTo(form);

**Comment by ThrawnCA** [comment]
The JQuery snippet appears to need an update:

 $('form[method=POST]').find('input[type=hidden]').appendTo(form);

**Comment by ThrawnCA** [comment]
Won't be implemented

**Comment by ThrawnCA** [comment]
If anyone is interested, our CSRF filter now works without this patch, and is available at https://github.com/ThrawnCA/ckanext-qgov/blob/master/ckanext/qgov/common/anti_csrf.py

**Comment by saurabhjangir** [comment]
@ThrawnCA I was looking for CSRF protection in CKAN code and I came to know about this issue. I was just wondering why this isn't implemented and not a part of core CKAN code. Could you please help me out regarding this.

**Comment by ThrawnCA** [comment]
@saurabhjangir The discussion at https://github.com/ckan/ckan/pull/2359 concluded with the core developers deciding that this would conflict with their future CSRF protection plans.

It should be possible to use the extension with core code in its current state; however, if I recall correctly, it needs a bugfix to make the 'remove member from organisation' links work.
