### ISSUE TITLE
Deleted groups remain visible by direct URL access

### ISSUE THREAD

**Issue by jammycakes** [ckan/ckan#2188]
It appears that after deleting a group, you can still access it if you know its exact URL.

To replicate:

 * Create a new group at http://localhost:5000/group/new - call it "test" with a url of localhost:5000/group/test
 * Click "Edit" on the group's home page then "Delete". The group will disappear from the list of groups at http://localhost:5000/group as expected; the "state" value of the corresponding row in the "group" table in the database will be set to "deleted".
 * *Unexpected:* Return to http://localhost:5000/group/test - the group will still be visible. The activity stream will also be visible (showing no record of the deletion) as will the "About" page.
 * *Unexpected:* The deleted group remains visible even to a logged-out user (as can be verified, for example, using a private browsing session in Firefox or Chrome).

CKAN version affected: 2.1.3. I have not yet determined whether other CKAN versions are affected.

**Comment by Aaron-M** [comment]
Same experience on CKAN version 2.2.1

**Comment by rossjones** [comment]
This has been fixed, see #785 for solution to general 403/404 error.
