### ISSUE TITLE
Update documentation telling to manually install JDK before installing solr

### ISSUE THREAD

**Issue by opensas** [ckan/ckan#2189]
Following the instructions in http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#setting-up-solr

On Ubuntu 12.04 you get the following error:

> HTTP ERROR 500
> Problem accessing /solr/. Reason:
>     Unable to find a javac compiler;
> com.sun.tools.javac.Main is not on the classpath.
> Perhaps JAVA_HOME does not point to the JDK.
> It is currently set to "/usr/lib/jvm/java-6-sun-1.6.0.26/jre"

The problem is that Solr package in ubuntu is missing the jdk as a dependency. This is a known issue (see https://bugs.launchpad.net/ubuntu/+source/solr/+bug/901165) and the correct workaround it to manually install the jdk running

```
sudo apt-get install openjdk-6-jdk
```
A note should be added to the documentation to troubleshoot this issue.

**Comment by joetsoi** [comment]
http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#install-the-required-packages

I think we've already got it in the first line for under the step 'installed required packages'

**Comment by opensas** [comment]
Yes, I noticed it later, at first I followed the package installation and I
stumbled with that issue. Perhaps adding a troubleshooting section in the
package install pointing to the requirements for a source installation.
