### ISSUE TITLE
Failed to connect to repository

### ISSUE THREAD

**Issue by fommil** [ckan/ckan#2192]
Sometime yesterday (possibly day before) I stopped being able to download the archive from ckan.exe (Debian Jessie):

```
Downloading https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip
8149 [1] ERROR CKAN.ErrorDialog (null) - Failed to connect to repository. Exception: Exception has been thrown by the target of an invocation.
```

I can see a few entries up to Biza if I try to download from a clean install.

I can download the master.zip manually, but I don't know what to do with it. Looks like a parsing problem rather than a network one, and I don't know where you keep the logs.

```
mono --version
Mono JIT compiler version 3.10.0 (tarball Wed Nov  5 12:50:04 UTC 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```

**Comment by wardi** [comment]
@fommil I think you're looking for the [other ckan](https://github.com/KSP-CKAN)

**Comment by fommil** [comment]
ha, yes
