### ISSUE TITLE
Upgrade bundled PDF.js

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#2193]
[The bundled version is pre-1.0 (v 0.8.229)](https://raw.githubusercontent.com/ckan/ckan/master/ckanext/pdfview/theme/public/vendor/pdfjs/pdf.js) which dates back to [June 2013](https://github.com/mozilla/pdf.js/commits/b996e1b) and not marked stable.

The latest stable version is at v1.10.907 (https://github.com/mozilla/pdf.js/releases).  It has hundreds of bug fixes, [lower memory reqts](https://blog.mozilla.org/nnethercote/2014/06/16/an-even-slimmer-pdf-js/), better compatibility and performance since 0.8.229

**Comment by jqnatividad** [comment]
The bundled, customized PDF.js also enables the "Open File"  control.  This allows the user to open another PDF from the local filesystem.  Not necessarily harmful, but confusing.  It also has the "Current View" control which is supposed to open the PDF in a new window, but does not work.

The preset zoom control is also floating over the PDF body.  Shouldn't it be in the toolbar? 

If the bundled PDF.js is going to be replaced, it'd be nice to disable the Open File control and the Current View, and consider enabling more useful controls like Document Properties, Fullscreen and Print, and all the other applicable controls in the Tool submenu (rotate, enable hand control,  go to first/last page) as is the case with the latest PDF.js (http://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by amercader** [comment]
@jqnatividad I would love to include this in 2.3, do you have time to send a PR?

Apart from the update, I'm not familiar with the PDF viewer but I guess you could implementing it on the template / js files of the extension:

https://github.com/ckan/ckan/blob/master/ckanext/pdfview/theme/templates/pdf.html
https://github.com/ckan/ckan/blob/master/ckanext/pdfview/theme/public/pdf_view.js

**Comment by jqnatividad** [comment]
@amercader I actually started putting together one :)

Won't be able to send it in until this weekend though.

**Comment by amercader** [comment]
great! no worries, there should be plenty of time to get in

**Comment by Aaron-M** [comment]
Just FYI, this will hopefully solve and issue with pdf previews on Chrome/IE which I raised on the dev email list -  I note Domink appears to have begun some work on updating PDF.js (see below), so +1. 
---
Hi,
     further to the issue of some pdfs not previewing correctly in IE and Chrome (but worked in Firefox).  We got advice from the manufacturer of the software that produced the pdfs that gave a problem.  They advised 

"... We were able to reproduce the issue. You will need to update your PDF.js from version 0.8.229 to latest (1.0.712). With the latest version the PDF is displayed correctly.

You can check you are using an obsolete version at this link:
http://datastore.landcareresearch.co.nz/fanstatic/ckanext-pdfpreview/:version:2014-02-20T11:38:22.26/vendor/pdfjs/pdf.js
Line 19 - PDFJS.version = '0.8.229';"

So, I found this page https://github.com/ckan/ckan/wiki/Upgrade-PDF.js from Dominik in June 2013 which seems to explain (at least in part) what we need to do - is there anything else to be aware of? 
The page notes " try to work out the remaining issues (Sorry, it's not that easy)" so sounds a bit daunting.

If indeed this is the issue, then perhaps the newer version of PDF.js could be incorporated in v2.3?

Cheers
Aaron

------------------------------

Message: 2
Date: Tue, 2 Dec 2014 16:19:03 +0800

**Comment by jqnatividad** [comment]
Hi @Aaron-M, can you send me some sample PDFs that were not previewing correctly with the current bundled PDF.js?  I need them for testing. Thanks!

**Comment by jqnatividad** [comment]
Sorry about the big diff, but the files that were changed to make PDF.js work with CKAN, beyond the many internationalization, character maps and other PDF.js dependencies are:

* [ckanext/pdfview/theme/templates/pdf.html](https://github.com/jqnatividad/ckan/blob/f732326b6b4b35a8869c0ec33165ea32d228f9fd/ckanext/pdfview/theme/templates/pdf.html) - adapted from PDF.js viewer.html. [(diff)](https://rawgit.com/jqnatividad/f95aaa309ab3a0ef8909/raw/b5e5c1c180a5b144b6290279ca8dffcaaa7767bc/pdf-html_changes.html)
* [ckanext/pdfview/theme/templates/package/snippets/resource_view.html](https://github.com/jqnatividad/ckan/blob/f732326b6b4b35a8869c0ec33165ea32d228f9fd/ckanext/pdfview/theme/templates/package/snippets/resource_view.html) -
Override snippet to allow presentation mode (full screen). Just added allowfullscreen to iframe.
* [ckanext/pdfview/theme/public/vendor/pdfviewer/viewer.js](https://github.com/jqnatividad/ckan/blob/f732326b6b4b35a8869c0ec33165ea32d228f9fd/ckanext/pdfview/theme/public/vendor/pdfviewer/viewer.js) - adapted latest viewer.js [(diff)](https://rawgit.com/jqnatividad/f95aaa309ab3a0ef8909/raw/viewer-js_changes.html)
* [ckanext/pdfview/theme/public/vendor/pdfviewer/viewer.css](https://github.com/jqnatividad/ckan/blob/f732326b6b4b35a8869c0ec33165ea32d228f9fd/ckanext/pdfview/theme/public/vendor/pdfviewer/viewer.css) [(diff)](https://rawgit.com/jqnatividad/f95aaa309ab3a0ef8909/raw/a435b7a52fef73421aa510bc5603d7e314b25384/viewer-css_changes.html)
* [ckanext/pdfview/theme/public/resource.config](https://github.com/jqnatividad/ckan/blob/f732326b6b4b35a8869c0ec33165ea32d228f9fd/ckanext/pdfview/theme/public/resource.config) [(diff)](https://rawgit.com/jqnatividad/f95aaa309ab3a0ef8909/raw/c4825d3607206f6528c9b1e2f8a521817b9b9929/resource-config_changes.html)

The diff was exported from smartgit.

**Comment by amercader** [comment]
PDF viewer has been moved to https://github.com/ckan/ckanext-pdfview
