### ISSUE TITLE
/related gives Internal Server Error

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#2194]
E.g. http://master.ckan.org/related

Looking at the error log, there's a  NameError: name 'request' is not defined in line 38 of related.py.

This seems to have snuck in when #2062 was merged.

**Comment by rossjones** [comment]
Grr. That's me. I'll look at the PR. Thanks.

Also, I think related is being retired at some point in favour or https://github.com/ckan/ckanext-showcase so it might be worth bearing in mind before investing too much time in it.
