### ISSUE TITLE
Retrieving RDF in n3 format gives faulty contents

### ISSUE THREAD

**Issue by xgfd** [ckan/ckan#2196]
In the n3 file internal variable names are shown than their values.

For example `curl -L http://demo.ckan.org/dataset/us-national-foreclosure-statistics-january-2012.n3` gives the following content:

```
<${ h.url_for(controller='package',action='read',id=c.pkg_dict['name'], qualified=True)}>
a dcat:Dataset;
     dct:description "${c.pkg_dict['notes']}";
     dct:identifier "${c.pkg_dict['name']}";
...
```

**Comment by rossjones** [comment]
The template for this is entirely broken, and has been forever.  If using the .rdf version isn't appropriate then you might be able to fix this by implementing the read.n3 template (https://github.com/ckan/ckan/blob/master/ckan/templates/package/read.n3).

I think most of the energy around linked-data is being focussed on https://github.com/ckan/ckanext-dcat/ right now.

**Comment by rossjones** [comment]
This is related to #1890

**Comment by xgfd** [comment]
Thanks for the update!


--
Xin Wang
University of Southampton
Electronics and Computer Science
Home page: *http://www.ecs.soton.ac.uk/people/xw4g08
<http://www.ecs.soton.ac.uk/people/xw4g08>*
Mail: xwang@soton.ac.uk

**Comment by rossjones** [comment]
On master I get the following with a quick test dataset 

```
@prefix : <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://localhost:5005/dataset/wombles>
a dcat:Dataset;
     dct:description "A wombles dataset";
     dct:identifier "wombles";
     dct:relation  [
         rdf:value "";
         :label "change_note" ],
             [
         rdf:value "";
         :label "definition_note" ],
             [
         rdf:value "";
         :label "editorial_note" ],
             [
         rdf:value "";
         :label "example_note" ],
             [
         rdf:value "";
         :label "history_note" ],
             [
         rdf:value "";
         :label "scope_note" ],
             [
         rdf:value "";
         :label "skos_note" ],
             [
         rdf:value "";
         :label "temporal_granularity" ],
             [
         rdf:value "";
         :label "type_of_dataset" ],
             [
         rdf:value "";
         :label "update_frequency" ];
     dct:title "Wombles";
     :label "wombles";
     = <urn:uuid:9680bfd9-3683-4526-b5d2-d1f3910210ae>;
     foaf:homepage <http://localhost:5005/dataset/wombles> .
```

It looks incomplete, but at least the template renders.

**Comment by rossjones** [comment]
This works on 2.3, although it may well require more effort by someone to correctly fill in the template.  Any effort around this should really be spent on github.com/ckan/ckanext-dcat
