### ISSUE TITLE
Errors when running less in debug development mode

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#2197]
There are two errors:

The first one is ckan.less still imports resource-view-embed.less [public/base/less/ckan.less](https://github.com/ckan/ckan/blob/7fb017a551a9616be8ace3db7f48ca7019254825/ckan/public/base/less/ckan.less#L23), even though it was removed as part of #1920 

Also,  [Line 199 of navbar.less](https://github.com/ckan/ckan/blob/7fb017a551a9616be8ace3db7f48ca7019254825/ckan/public/base/vendor/bootstrap/less/navbar.less#L199) causes a NameError.

**Comment by jqnatividad** [comment]
This was on Ubuntu 14.04, with the softlink workaround for nodejs (i.e. sudo ln -s /usr/bin/nodejs /usr/bin/node) mentioned in #1829 

In my sandbox instance, I removed the resource-view-embed.less reference in ckan.less and line 199 in navbar.less, and debug development mode seemed to work.

**Comment by brew** [comment]
Thanks for your report. The redundant import has been fixed in #2220. 

The NameError issue has been addressed in #2101. The version of Bootstrap CKAN uses can't be compiled with less V2+, so we suggest using less 1.7.5: `npm install less@1.7.5`.
