### ISSUE TITLE
UTF-8 CSV preview when column name is ascii, but content is UTF-8

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan#2203]
There is a bug (or intended behaviour) that results for utf-8 symbols in CSV preview to be lost when column names are all ascii.

**Comment by rossjones** [comment]
Do you have a URL I can use to replicate this? I'd like to replicate the *exact* same issue you have with the same data if possible.

**Comment by Vanuan** [comment]
http://datahub.io/dataset/administrative-services/resource/765e1e6d-8ead-41f0-8183-1559b6fc546b

**Comment by rossjones** [comment]
Great thanks.  On datahub, it uses the external jsondataproxy on appspot to convert the CSV to JSON so that recline can view it.  It does this by making the following request

```
http://jsonpdataproxy.appspot.com/?callback=jQuery17204580959139857441_1421249306921&url=http%3A%2F%2Fckannet-storage.commondatastorage.googleapis.com%2F2015-01-14T15%3A25%3A35.793Z%2Fservices.csv&max-results=1000&type=csv&_=1421249311731
```

Have set up a dataset at ```http://master.ckan.org/dataset/utf-8-test``` to test once the issue with creating views is fixed.

**Comment by Vanuan** [comment]
Don't see a preview on http://master.ckan.org/dataset/utf-8-test

**Comment by rossjones** [comment]
to test once the issue with creating views is fixed.

It will be in master/2.3

We're trying to stop using the appspot server because it is so limited (size limits etc).

**Comment by rossjones** [comment]
Adding encoding=utf-8 to the URL like 

```
http://jsonpdataproxy.appspot.com/?callback=jQuery17204580959139857441_1421249306921&url=http%3A%2F%2Fckannet-storage.commondatastorage.googleapis.com%2F2015-01-14T15%3A25%3A35.793Z%2Fservices.csv&max-results=1000&type=csv&encoding=utf-8&_=1421249311731
``` 
shows all the unicode chars.

**Comment by rossjones** [comment]
#2215 explains why it is failing in master.ckan.org so no immediate solution there.

**Comment by Vanuan** [comment]
Oh, I got it.
So, there will be no CSV preview in CKAN 2.3?

**Comment by rossjones** [comment]
There will (see http://master.ckan.org/dataset/gold-prices/resource/b9aae52b-b082-4159-b46f-7bb9c158d013?view_id=8c766e19-4893-42c3-9ec4-1176ceb2890f for example). 

It's just not handling UTF very well atm.  I'll fix it soon.

**Comment by amercader** [comment]
Fixed in https://github.com/ckan/ckan/pull/2182
