### ISSUE TITLE
group_create does not return results of group_show

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2210]
When calling group_create, the action layer returns the result of calling group_dictize (which ignores the schema). The same is also true for group_list.

When calling package_create it returns the result of package_show.

It feels like it should be more consistent so that group_create definitively returns the same as group_show.

**Comment by rossjones** [comment]
As per package, provide an option just to return the ID/IDs

**Comment by davidread** [comment]
Agreed, it should return the result of group_show instead of the dictize.

**Comment by davidread** [comment]
PR #2214
