### ISSUE TITLE
User_show doesn't display  users draft datasets  anymore

### ISSUE THREAD

**Issue by benjaminlaot** [ckan/ckan#2216]
After this commit : https://github.com/ckan/ckan/commit/b2dfccc8932947711d4f9b0f2500be4c40208b21  , user_show displays only users active datasets and not users draft datasets anymore. 
So if we delete these filters : filter_by(state='active'), filter_by(private=False), users draft datasets could be displayed again, but deleted ones too...

**Comment by amercader** [comment]
@davidread you did the original work on #2130 so you might know more about this. What do you think about these filters? Considering the authorization should allow only the same user and sysadmins to see these datasets it sounds like at least private datasets and drafts could be visible.

**Comment by davidread** [comment]
@benjaminlaot thanks for raising this. I've done a PR: https://github.com/ckan/ckan/pull/2256 - what do you think?

**Comment by benjaminlaot** [comment]
I think you did a good job doing this and I think we have now the right behaviour.
