### ISSUE TITLE
Enable a logged in user to move dataset to another organization

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan#2218]
In #953 this change was introduced:

> User is logged in, and is a member of an organization, and dataset is a
member of any org: Visibility shows but Organization does not show when
updating a dataset.

So, this prevents a logged in user to change dataset's organization.

Why can't a legitimate user to move datasets around organizations?

**Comment by myroslav** [comment]
Under "legitimate" I'd suggest "Admin of both organizations".

**Comment by Vanuan** [comment]
That's correct: https://github.com/ckan/ckan/blob/e9e56ddf44d22f63c1eb4667f1a4f4efc0541215/ckan/logic/action/get.py#L579

**Comment by wardi** [comment]
@brew in scheming we decided to just show the org and private form fields all the time: https://github.com/open-data/ckanext-scheming/issues/19

**Comment by brew** [comment]
@wardi Thanks - so that matches with what's enabled by the API.

**Comment by wardi** [comment]
@brew Yes, I can't think of any reason the form should be more restrictive than the API

(Repeating myself for the benefit of those not on the developer call)

**Comment by brew** [comment]
@wardi It may not be appropriate to show the org dropdown for users who don't belong to an org (in an install that has `create_dataset_if_not_in_organization` set to true). And likewise, the visibility dropdown if a user is not allowed to make their dataset private, ie no org can be set, as they don't belong to one. Or we show the dropdowns, but they can't be set, and return a validation error if inappropriate data is submitted.

The ability to set the org and visibility does need to allowed for more than just sysadmins though.

**Comment by Vanuan** [comment]
>  It may not be appropriate to show the org dropdown for users who don't belong to an org

Easily fixable by checking for "organization_list_for_user" length.
