### ISSUE TITLE
Render_datetime can't handle dates before year 1900

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#2228]
Due to the python 2.7 feature datetime.strftime won't handle dates before year 1900 (http://bugs.python.org/issue1777412)

https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L947

**Comment by wardi** [comment]
What are the chances users would accept rendering ISO8601 format all the time? We wouldn't need strftime for that.

**Comment by Zharktas** [comment]
At least it should be documented that if users are allowed to input dates, use of render_datetime might create issues.

**Comment by wardi** [comment]
@Zharktas at the developer meeting today it was suggested to catch the exception for such dates and fall back to a manual rendering of YYYY-MM-DD in this helper. What do you think?

**Comment by Zharktas** [comment]
Sounds good, at least it would not cause an error anymore. We went with manual date render in our implementation: https://github.com/yhteentoimivuuspalvelut/ytp/blob/master/modules/ckanext-ytp-main/ckanext/ytp/common/helpers.py#L47 since we only need one date format.

**Comment by gleb-rudenko** [comment]
@wardi, what is the progress of this one? can it be closed?

**Comment by wardi** [comment]
Still not fixed, and a really easy thing to contribute. I'll mark it as such

**Comment by klikstermkd** [comment]
@wardi Can I take this one?

**Comment by wardi** [comment]
@klikstermkd absolutely! anything marked good for contribution is up for grabs
