### ISSUE TITLE
datastore does not correctly type the response

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2239]
As you can see from the image below, 'Available' is a numeric field (and the database stores it as such) but the JSON response converts it to a string before sending it to the client.  Where the types are supported by JSON, they should be returned as that type.

![dgu_5000_api_3_action_datastore_search_resource_id_054892bc-a795-43f3-b19f-d031879d10bb_limit_50_sort__loan_20size_](https://cloud.githubusercontent.com/assets/118063/5858175/1bc873a4-a249-11e4-8e44-540e6b239133.png)

**Comment by davidread** [comment]
Just a concern that the number could be too big for a javascript float/int, so need test?

**Comment by rossjones** [comment]
I can't see a way around this, and it looks like isn't biting anybody else, so this is safe to close.
