### ISSUE TITLE
Package_update does not change the revision_id when editing a custom field of a dataset

### ISSUE THREAD

**Issue by benjaminlaot** [ckan/ckan#2240]
During the edition of a dataset, if I modify the description or the title for instance, the revision_id will change and the dataset will be updated correctly, whereas when I modify a custom field (I am using ckanext-scheming) or the tag field, the dataset is updated but the revision_id doesn't change. 
It can be a problem if we want to compare old_revision_id and New_revision_id for example.

**Comment by wardi** [comment]
@benjaminlaot the revision_id is an implementation detail and might change or be removed in the future. Would you be able to use the last_modified field instead?

**Comment by benjaminlaot** [comment]
I used the metadata_modified field. It partially worked for me because I need to differentiate two behaviours.
So I wondered if there was a way to differentiate those two : 

1) the user update the dataset whithout even modify a metadata

2) the user update the dataset modifying at least one metadata

metadata_modified field is changing no matter what. That's why I asked for the revision_id. In this case it would have helped me to make the difference between behaviour 1) and 2) .

**Comment by benjaminlaot** [comment]
But as you said revision_id might be removed so if there is an other way it is perfect, otherwhise I will just do it with metadata_modified.

**Comment by wardi** [comment]
Making metadata_modified only change when the metadata changes as a result of a package_update call would be a nice feature. Consider submitting a PR or an issue on the ideas-and-roadmap repository to suggest it. I'm closing this issue for now because using metadata_modified instead is a good interim solution.
