### ISSUE TITLE
How to install CKAN in MAC OS X Yosemite 10.10

### ISSUE THREAD

**Issue by chackaldana** [ckan/ckan#2281]
For those who had tried and never complete the mission to install CKAN this are the steps working on me to install CKAN in MAC OS X Yosemite 10.10

https://github.com/chackaldana/CKAN-Mac-OSX-Yosemite-10.10.1

**Comment by amercader** [comment]
Hi @chackaldana, thanks, but a better place for this is the wiki. Feel free to add it yourself to this page:

https://github.com/ckan/ckan/wiki/How-to-Install-CKAN

**Comment by chackaldana** [comment]
Excellent best!
