### ISSUE TITLE
Uploading to datastore files with utf-8 native chars crashes

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2282]
It results in 500 Server internal error shown in *Update resource/Datastore* or in `datapusher.log`:
```
Error: CKAN DataStore bad response. Status code: 500 Internal Server Error. At: http://localhost:5000/api/3/action/datastore_create. Response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> <title>Server
```

Calling `ckanext.datastore.logic.dataset_create` which in the end calls `ckanext.datastore.db._to_full_text` [code](https://github.com/ckan/ckan/blame/7c79bde0b83ecb5398c94129764dd5d8ecc45ab8/ckanext/datastore/db.py#L760).

I don't know if *Full-text index* should consist only of ascii values or if utf-8 is supported?

If it's not supported text should be encoded:
```python
u'aあä'.encode('ascii', 'ignore')
```

If it is supported these lines should be changed to:
```python
        if field['type'].lower() in ft_types and unicode(value):
            full_text.append(unicode(value))
```
which was probably broken in https://github.com/ckan/ckan/commit/7c79bde0b83ecb5398c94129764dd5d8ecc45ab8

**Comment by KrzysztofMadejski** [comment]
If it's the latter case here's the commit resolving that:
https://github.com/DanePubliczneGovPl/ckan/tree/2282-datastore-handling-utf-8-content

**Comment by wardi** [comment]
@KrzysztofMadejski thanks, i've already been assigned to a pull request that does this #2182

**Comment by KrzysztofMadejski** [comment]
Great. So I'm closing this one. Thanks!
