### ISSUE TITLE
sql syntax error when I create dataset via RestApi

### ISSUE THREAD

**Issue by Jan-Marcek** [ckan/ckan#2291]
Hi, 

Prerequisites:
ckan 2.2.1 with no record. 
steps via RestApi:
1. create organization
2. create dataset owned by organization created in 1

I get this:

```
[Tue Feb 17 13:12:42 2015] [error] [client ::1] Error - <class 'sqlalchemy.exc.ProgrammingError'>: (ProgrammingError) operator does not exist: text = text[]
[Tue Feb 17 13:12:42 2015] [error] [client ::1] LINE 3: WHERE "group".id = ARRAY['14ea4a7d-0380-45a5-9226-afe3272bed...
[Tue Feb 17 13:12:42 2015] [error] [client ::1]                          ^
[Tue Feb 17 13:12:42 2015] [error] [client ::1] HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
[Tue Feb 17 13:12:42 2015] [error] [client ::1]  'SELECT "group".id AS group_id, "group".name AS group_name, "group".title AS group_title, "group".type AS group_type, "group".description AS group_description, "group".image_url AS group_image_url, "group".created AS group_created, "group".is_organization AS group_is_organization, "group".approval_status AS group_approval_status, "group".state AS group_state, "group".revision_id AS group_revision_id \\nFROM "group" \\nWHERE "group".id = %(id_1)s \\n LIMIT %(param_1)s' {'id_1': [u'14ea4a7d-0380-45a5-9226-afe3272bed3c'], 'param_1': 1}

``` 

Bu when I run it second time then it works with no problem.

Thanks for your help

**Comment by joetsoi** [comment]
hey could you guys us some more detail? it'd be nice to know the exact end point you are using and/or the exact code you are using, makes it easier to debug

**Comment by Jan-Marcek** [comment]
we are developing this extension: https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/tree/ODN_v0.10.0 


1. create organization - https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/blob/b0740aefcfba8e394cba0ea911e6609de7d6505a/ckanext/publishing/ckan_sync.py#L62

2. create dataset owned by organization - https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/blob/b0740aefcfba8e394cba0ea911e6609de7d6505a/ckanext/publishing/ckan_sync.py#L75

**Comment by Jan-Marcek** [comment]
BUT the stacktrace is from a ckan log. It is NOT from the extension log.

**Comment by Jan-Marcek** [comment]
but I could try curl. Maybe It'll work. However, I'm a bit skeptic...

**Comment by Jan-Marcek** [comment]
but when I have tried via curl https://gist.github.com/Jan-Marcek/81bacd258bb2b5568152 it has worked. Any hint what could be wrong?

**Comment by Jan-Marcek** [comment]
Yeah, I have found the problem. 
this line https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/blob/b0740aefcfba8e394cba0ea911e6609de7d6505a/ckanext/publishing/ckan_sync.py#L67

has to same as https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/blob/b0740aefcfba8e394cba0ea911e6609de7d6505a/ckanext/publishing/ckan_sync.py#L64

Otherwise owner_org = [[id]] array of arrays...correct is owner_org = [id] of course

Thank you very much for  consultancy.

**Comment by joetsoi** [comment]
oh wow awesome, I go away for lunch and you solve the problem by the time get back, great work!
