### ISSUE TITLE
Automatic Views (previews) stopped working in v2.3

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2299]
I uploaded a text file, with extension .txt.  In previous versions of CKAN the txt format would be recognised and a preview of the text file offered automatically.  In v2.3. when I uploaded the file no preview was available.  I found that I had to edit the record and go to the new 'Views' tab, and manually tell it to provide a preview of the text file.

When I created the dataset I was not prompted to enable a text file view.  I had to create the dataset in full, then go back and manage it and add the view.  This is not user friendly.

Does not work for PDF file either - had to go back in and manually configure to use PDF View.

As a user I want all the current automatic recognition of file format extensions to continue to work and to automatically provide grid, text, graph,map, and pdf previews as appropriate.

The ability to manually configure views for exceptions is good, but we do not want have to configure views for every single file we upload.

Works for CSV and XLS.  We have edited our configuration file in v2.2 to also load to datastore and preview TSV (tab separated values) and XLSX spreadsheets, and to text preview some other defined text file extensions.  These configuration settings need to continue to work as well.

Possibly related to #2298

**Comment by amercader** [comment]
See #2298 for more details.

Basically the text and pdf views were not added to the ones to be [created by default](http://docs.ckan.org/en/latest/maintaining/data-viewer.html#defining-views-to-appear-by-default) on beta.ckan.org. I've updated the setting now and they should be created by default now:

http://beta.ckan.org/dataset/xmlfile/resource/e89f7de4-f7f1-4501-bf8c-fe1fe60cce9b
http://beta.ckan.org/dataset/group/resource/fa1319d6-fd07-45ba-a71b-9a935f21dbf0

Apologies again for not having linked to the docs before.
