### ISSUE TITLE
PDF Preview (in chrome and IE)

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2300]
Preview of some pdf files which display perfectly in Firefox, are messed up in IE and Chrome.  This is still evident in V2.3 beta.  Will the new work on PDF viewing in #2231 and #2270 make it into v2.3 final release?
![pdf view](https://cloud.githubusercontent.com/assets/4842751/6238431/e1f71e9c-b75f-11e4-9881-e294e702472d.jpg)

**Comment by jqnatividad** [comment]
Hi @Aaron-M, I'm waiting on pdf.js project to have a more recent stable release (https://github.com/ckan/ckanext-pdfview/issues/2).

However, it seems that it will take them a while, so we'll just go with pdf.js v1.0.1040.

Do you mind sending me sample PDFs with the problems above, so I can check if they've been resolved in my test instance?

**Comment by Aaron-M** [comment]
Hi @jqnatividad 
   You can grab a pdf which is affected by this from https://datastore.landcareresearch.co.nz/dataset/nzflora-fife-2014-hylocomiaceae/resource/256d3fbf-aa7b-40ab-817c-21a3ee97e68f
You'll see a number of other pdfs in that organisation as well, most if not all are similarly affected.

**Comment by jqnatividad** [comment]
Hi @Aaron-M,
Just wanted to confirm that this [PR](https://github.com/ckan/ckanext-pdfview/pull/4) fixes your issue :smile:

**Comment by jqnatividad** [comment]
Hi @Aaron-M,
Can you confirm if a Development Installation of https://github.com/ckan/ckanext-pdfview in your CKAN instance works?

I tested it in my 2.3 development sandbox and it works:

![test_pdfs_-_flora_file_test_-_ckan](https://cloud.githubusercontent.com/assets/1980690/6794148/a6bb5438-d1a4-11e4-95b9-c934c67ea6bb.jpg)

**Comment by Aaron-M** [comment]
Thanks Joel!
