### ISSUE TITLE
ckan.plugins.core.PluginNotFoundException: recline_view

### ISSUE THREAD

**Issue by badbruce07** [ckan/ckan#2305]
I have a problem here. When I enter `paster serve --reload /etc/ckan/default/development.ini` to run the server, I get this error:

![screenshot from 2015-02-19 13 12 10](https://cloud.githubusercontent.com/assets/1694078/6272859/f359e29e-b838-11e4-904c-79b3eb112e31.png)

Can anyone explain why do I get this error? Both plugin.py and setup.py are all correct in order.

**Comment by deniszgonjanin** [comment]
Are you using the master branch or a release branch of CKAN?

`recline_view` may not exist in the CKAN codebase depending on how old the code you are running is.

**Comment by badbruce07** [comment]
oh ok. i figured out what was wrong. The server was running elsewhere than my machine. Problem is resolved now. Thanks!
