### ISSUE TITLE
Cannot get through with ckan-config

### ISSUE THREAD

**Issue by badbruce07** [ckan/ckan#2310]
Hey I have an issue here. I was following the jinga2 steps and I placed `{% ckan_extends %}` inside the empty index.html file but it doesn't redirect to the default CKAN page. Also when I ran the serverip:port#/ckan-config/admin I get this error: 

![screenshot from 2015-02-20 13 40 03](https://cloud.githubusercontent.com/assets/1694078/6307023/6716627a-b906-11e4-9b13-13063aa3eb05.png)

How can I fix this problem?

My debug was already set to true in the development.ini file

**Comment by nigelbabu** [comment]
This seems to have nothing to do with your extension. Please delete the folder /tmp/default and try again. If you need more help, please email ckan-dev mailing list instead of filing a bug.
