### ISSUE TITLE
Add ckanext-fluent-style handling of core fields to ckan's templates

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2325]
I'm using (and promoting use of) ckanext-fluent on a number of sites. ckanext-fluent provides validators that store and retrieve multilingual text, markdown and tag values as dictionaries instead of simple strings. This is the approach discussed with @kindly as an ideal way to store and share multilingual metadata in ckan, and fortunately can be implemented entirely with IDatasetForm validators.

One remaining problem is that when this type of validator is used on certain core fields such as "title", "notes" significant template overriding and duplication is required in a theme in order to display the correct language values to end users.

A workaround is to not store multilingual values in core fields, as I've done on one site, but that's not a very nice solution.

I propose adding handling for ckanext-fluent-style multilingual values in the templates for some core fields to avoid the significant template overriding currently required by users wishing to have multilingual metadata.

This is the logic that would apply to these fields before they are displayed:

1. if value is a string, pass it to gettext/ckanext-multilingual for conversion to the users language before displaying
2. if value is a dict, select the key appropriate for the users language (falling back to the site default language then the first language alphabetically if not available) before displaying

**Comment by bzar** [comment]
Currently considering how we should implement exactly this for our project. Has anyone tried the above solution? Is there a branch somewhere? 

I'm currently considering just hiding the default description field and using a fluent field in its stead. This, of course would require changing all templates that do anything with the description field.

**Comment by metaodi** [comment]
Yes we are currently implementing this for the next version of the Swiss open data portal. You can find our current progress here: https://github.com/ogdch/ckanext-switzerland

**Comment by bzar** [comment]
Hey, great! I'll look into what you've done :)

**Comment by wardi** [comment]
closed in favour of #2678
