### ISSUE TITLE
KeyError 'resources' in error handler

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckan#2331]
https://github.com/ckan/ckan/blob/master/ckan/logic/action/create.py#L305

Extension-code dependent, it can happen that a perfectly normal validation error leads to this block and CKAN throws an exception concerning a missing resources key when there is no resources key in the dictionary. This can lead to serious confusion for a developer.

**Comment by maxious** [comment]
I went with a hacky patch for this; if there's not a resource error, there must be a package validation error so assume that and dump the error dict for good measure https://github.com/datagovau/ckanext-agls/blob/master/patches/resource-edit-error.patch
At least it doesn't just Error 500 on the user then.

**Comment by wardi** [comment]
Yes I've run into this too.

What we need is to check for errors outside that last resource and include a message something like what @maxious suggests. "Can't save resource because of validation errors in the dataset/other resource fields: {field_names}"

Anyone care to submit a PR?

**Comment by CarlQLange** [comment]
Ugh, I just hit this, it's pretty horrible. PR incoming

**Comment by CarlQLange** [comment]
PR here https://github.com/ckan/ckan/issues/3027
