### ISSUE TITLE
Solr

### ISSUE THREAD

**Issue by bryanhumphreys** [ckan/ckan#2333]
Hi
I am installing ckan from source when I try to access  http://localhost:8983/solr/ I receive the following error
HTTP ERROR 404
Problem accessing /solr/. Reason: 

```
NOT_FOUND
```

If I access  http://localhost:8983/
I receive Welcome to Jetty 6 on Debian

Regards
Bryan

**Comment by badbruce07** [comment]
I had a similar problem like that before so what I did was I installed solr-tomcat instead of solr-jetty. Solr-jetty for me is definitely a pain

**Comment by bryanhumphreys** [comment]
Thanks
How do you associate solr-tomcat with ckan.
Apologies but I'm new to this

Regards
Bryan



On 10 Mar 2015, at 16:15, badbruce07 <notifications@github.com<mailto:notifications@github.com>> wrote:


I had a similar problem like that before so what I did was I installed solr-tomcat instead of solr-jetty. Solr-jetty for me is definitely a pain

**Comment by florianm** [comment]
Bryan,

getting SolR to play ball was a major headache. I finally got it to work,
although in a multi-tenant scenario, see my write-up at
https://github.com/opendata/CKAN-Multisite/issues/10#issuecomment-70068327

Hope that helps,
Florian

**Comment by rleir** [comment]
Bump!

I think this is a documentation issue. Would someone with privileges please add a 'doc' tag to this issue.

Going from Solr 4 to Solr 5, the Solr project dropped Jetty/Tomcat, and Solr is now a standalone server.
 ref https://cwiki.apache.org/confluence/display/solr/Major+Changes+from+Solr+4+to+Solr+5#MajorChangesfromSolr4toSolr5-SolrisNowaStandaloneServer

Now Solr is at 6.2. The CKAN doco does not specify which version of Solr is recommended, but it mentions Jetty in several places.

CKAN needs to be compatible with several versions of Solr. Do we have agreement on which versions of Solr CKAN will support?

**Comment by florianm** [comment]
@rleir while I'm chasing through my backups, we moved on to an architecture based on the (now abandoned) datacats - docs at http://datawagovau.readthedocs.io/en/latest/

The latest thinking is to follow http://ckan.org/2016/10/13/enterprise-ckan-stack-for-aws-is-now-available-on-github/ 

Both of these solutions address the SolR headache, although the datacats-based one will not work with latest CKAN due to a SolR version conflict.

More next week if I find my write-up!

**Comment by rossjones** [comment]
This issue (Solr versions) is being discussed in https://github.com/ckan/ckan/issues/3673 so I'm going to close this ticket (due to inactivity) - please contribute on the other issue if this is still causing you problems.
