### ISSUE TITLE
DatapusherPlugin implementation of notify() can call 'datapusher_submit' multiple times

### ISSUE THREAD

**Issue by clementmouchet** [ckan/ckan#2334]
Hi,

Currently `DatapusherPlugin` implements `notify()` from `IDomainObjectModification` & `IResourceUrlChange`.

On our CKAN 2.3 portal this this means it's called twice; the first time, because operation == model.domain_object.DomainObjectOperation.new (IDomainObjectModification) and the second time because operation is not passed (IResourceUrlChange).

It's been like that for a [long time](https://github.com/ckan/ckan/blame/8f298cd9e658d788b031a4059271210aff6a3d94/ckanext/datapusher/plugin.py) and I wonder it this has not been picked up before because it has not been tested with extensions that implement other interfaces leading to notify being called multiple times ? 

In my case implementing IResourceUrlChange sounds like a quick fix, but I'm wondering if this doesn't highlight that the logic in DatapusherPlugin should be re-considered?

What do you think?

**Comment by clementmouchet** [comment]
I think I've come up with a better answer to that problem. The datapusher doesn't check is there is a pending task before submitting a new one, so rather than fixing the hook, I've fixed that.

```diff
diff --git a/ckanext/datapusher/logic/action.py b/ckanext/datapusher/logic/action.py
index 1af23c3..21d72bd 100644
--- a/ckanext/datapusher/logic/action.py
+++ b/ckanext/datapusher/logic/action.py
@@ -64,19 +64,22 @@ def datapusher_submit(context, data_dict):
         'error': '{}',
     }
     try:
-        task_id = p.toolkit.get_action('task_status_show')(context, {
+        existing_task = p.toolkit.get_action('task_status_show')(context, {
             'entity_id': res_id,
             'task_type': 'datapusher',
             'key': 'datapusher'
-        })['id']
-        task['id'] = task_id
+        })
+        task['id'] = existing_task['id']
     except logic.NotFound:
         pass
 
+    if existing_task.get('state') == 'pending':
+        log.info("A pending task was found %r, ignoring" % task['id'])
+        return True
+    
     context['ignore_auth'] = True
-    result = p.toolkit.get_action('task_status_update')(context, task)
-    task_id = result['id']
-
+    p.toolkit.get_action('task_status_update')(context, task)
+    
     try:
         r = requests.post(
             urlparse.urljoin(datapusher_url, 'job'),
```

What do you think? Will you take a PR for that?

**Comment by davidread** [comment]
@clementmouchet thanks for this, I've created the PR: https://github.com/ckan/ckan/pull/3526

Are you able to give it a try?
