### ISSUE TITLE
create-test-data annakarenina dataset links to nasty page that hijacks browser

### ISSUE THREAD

**Issue by marcesher** [ckan/ckan#2336]
after running `paster create-test-data`, I viewed the Tolstoy dataset and tried to preview the data. My browser was then hijacked by some nasty-looking popups as a result of annakarenina.com

Seems this dataset should either link to somewhere nonexistent, or to a real thing (which presumably it did at one point)

**Comment by rossjones** [comment]
@marcesher Thanks for letting us know, I've submitted a PR to fix.

**Comment by marcesher** [comment]
Thanks!
