### ISSUE TITLE
"No datasets found" when upgrading 2.2 -> 2.3

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan#2339]
Steps to reproduce:

1. Backup pg database in 2.2
2. Install 2.3
3. Restore pg database in 2.3

"Datasets" screen shows "No datasets found", but they are available by url, in user profile, dashboard, activity, etc.

**Comment by Vanuan** [comment]
/api/3/action/package_list also show complete list of datasets.

**Comment by mattfullerton** [comment]
The immediate fix is probably to do:
paster --plugin=ckan search-index rebuild -c /path/to/config.ini

If the upgrade procedure can be improved, I don't know

**Comment by Vanuan** [comment]
It worked, thanks!
