### ISSUE TITLE
Datastore _table_metadata view recreated on every startup

### ISSUE THREAD

**Issue by maxious** [ckan/ckan#2345]
We fixed the read/write test having conflicting table names by randomizing them (https://github.com/ckan/ckan/pull/1397, https://github.com/ckan/ckan/issues/2082) but there's still another database call that can cause problems on busy sites: creating the _table_metadata view.
https://github.com/ckan/ckan/blob/b1c12f74b09c4703407563861e089e37ec0e19e2/ckanext/datastore/plugin.py#L80

My understanding of PostgreSQL views was once it's created, they update automatically without any further interaction. And if it's being recreated, all read queries against that view are locked until it is done?

Does this view really need to be created and/or recreated every time the plugin is loaded? 
Could it be done once on installation (either with documentation for a paster command or checking that it does not exist/is not the right structure before proceeding)?

**Comment by wardi** [comment]
@maxious You're right, this doesn't seem to make sense.

Should we introduce migrations for the datastore database to avoid this "live migration" thing we seem to be doing now?  Maybe start a directory under the datastore extension.
