### ISSUE TITLE
Proxypass /ckan

### ISSUE THREAD

**Issue by STOIE** [ckan/ckan#2348]
Hi guys,

Having a bit of an issue and hoping someone could please help.

I have apache on my host forwarding https://foo.bar/ckan -> docker-container:9322/

And unfortunately, all the includes for ckan are broken... the relative urls are missing the "/ckan"

Any ideas, I am sure this is a x-forwarded-for issue, but, can't seem to get the right combo working...

Thanks in advance,
Aaron.

**Comment by nigelbabu** [comment]
Have you updated `ckan.site_url` so that it says "https://foo.bar/ckan"? Please email the list instead of opening an issue for support requests including any followup to this.
