### ISSUE TITLE
No clear way to add a tab to ckan-admin page

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2351]
If you go to /ckan-admin (as a sysadmin) there are some tabs for config, trash etc.  As a plugin author, there's no obvious way for me to provide info about a tab that I would like adding to that page. For instance if I need a config page for my plugin, it seems like ckan-admin would be the perfect place - but I will need to override the admin template just to insert a link.

Perhaps it would be better if there was a way of doing this without copying/overriding templates?

**Comment by brew** [comment]
I guess the problem with overriding the templates, is that if two or more extensions each want to add a tab to the admin pages, only the last loaded extension's tab will display?

Each plugin could, within its `update_config` method, add a route/name pair to a config setting; `admin_tabs` or something. Then the admin base template could have a helper method that iterates over `admin_tabs` to create these tab links when it renders the `content_primary_nav` block.

**Comment by brew** [comment]
Trying to be clearer what I'm proposing:

* A new config option: `ckan.admin_tabs`. This is a list of route-name/label pairs separated by a colon and each pair separated by a comma, eg. 

    `ckan.admin_tabs = ckanext_myext_config:My Extension, ckanext_otherext_config:Other Extension` 

* A new toolkit method: `add_ckan_admin_tab` takes the route name and label, and appends them them as a new value to the `ckan.admin_tabs` option in the above format.

* A new template helper that interprets the values in `ckan.admin_tabs` and outputs the appropriate `h.build_nav_icon` after the default content in `template/admin/base.html`

A sysadmin can either edit the config file directly to add the new admin tab for an extension their using, or the extension author can use `IConfigurer.update_config` and the new `toolkit.add_ckan_admin_tab` to add their own admin pages.

**Comment by wardi** [comment]
my idea. @amercader 's idea might be better

```
ckan.admin_tabs = ckanext_myext_config ckanext_otherext_config
ckan.admin_tabs.ckanext_myext_config = My Extension
ckan.admin_tabs.ckanext_otherext_config = Other Extension
```

**Comment by rossjones** [comment]
Too much config :) 

How about IAdminPage ?

**Comment by brew** [comment]
I thought mostly the config changes would be done through the toolkit method in the extension, rather than directly editing the ini file:

```python
class MyExtensionPlugin(plugins.SingletonPlugin):
    plugins.implements(plugins.IConfigurer)
    plugins.implements(plugins.IRoutes)

    update_config(self, config):
        tk.add_ckan_admin_tab(config, 'ckanext_my_config', 'My Label') # new tk method!

    def before_map(self, map):
        with SubMapper(map, controller='ckanext.myext.controller:MyController') as m:
            m.connect('ckanext_my_config', '/ckan-admin/my_config', action='myext_config', ckan_icon='picture')
```

**Comment by wardi** [comment]
@brew I like it

**Comment by tryggvib** [comment]
For what it's worth, I like @brew's idea as well. It's a lot cleaner imo than messing about with the ``.ini`` file.

@rossjones could you elaborate a little about your ``IAdminPage`` suggestion. Is that kind of what @brew is suggesting or are you suggesting something different?

**Comment by rossjones** [comment]
I think I like @brew's suggestion, I was thinking a plugin where you provide it the same details but adding it to toolkit seems simpler, more easily extendable to package pages etc.

**Comment by amercader** [comment]
OK, I had missed the toolkit function bit and assumed that people would be messing with the ini file.

It's a slightly different pattern to the one that extensions generally use to register things like helpers, facets, etc (implement interface + some methods returning the relevant dicts) but it does seem straight-forward to implement for extension writers.

I guess some form of docs / tutorial and example extension will be helpful, as there are some things missing on your snippet (eg you need to have a custom controller, and a template)

**Comment by brew** [comment]
Perhaps I should drop the option to edit the config file directly. It's confusing, and likely not useful.

**Comment by wardi** [comment]
I can imagine a user that will want their admin tabs in a particular order, or perhaps hide some. How about an optional config option that lists the (only)tabs to display in the order preferred

**Comment by wardi** [comment]
or I guess the same could be accomplished by overriding a template, so maybe not worth doing

**Comment by jqnatividad** [comment]
While thinking about implementing this major feature for the ckan-admin page, it may pay to think about storing [Config in the Database](https://github.com/opendata/CKAN-Multisite/issues/8) as well.

**Comment by brew** [comment]
> it may pay to think about storing Config in the Database as well

@jqnatividad that may be out of scope for this particular ticket :wink:, but it's under active discussion at the moment.

**Comment by LingboTang** [comment]
@brew I tried your example and it seems like a duplicated "config" tab has been added to the admin page. What should I do if I just want to replace it with my customized content without duplicate the tab?

**Comment by brew** [comment]
@LingboTang Could you create a separate issue explaining what you're trying to achieve, with the code you've added, so someone can take a look.

**Comment by LingboTang** [comment]
@brew NVM, I've already solved the problem. Basically I just replaced the entire 'template' by calling `toolkit.add_template_directory(config_, 'templates')`
