### ISSUE TITLE
cache sql query results using dogpile/beaker

### ISSUE THREAD

**Issue by joetsoi** [ckan/ckan#2353]
I don't believe we actually cache any of our sql queries, as a result we end up with repeated requests, for example `model.User.get()` is run when we run check_access anywhere in the templates, so on some pages we end up fetching the user a couple of dozen times.

I haven't had an indepth look, but we have the beaker caching middleware [enabled](https://github.com/ckan/ckan/blob/master/ckan/config/middleware.py#L10), but as far as I can tell, we don't actually use it anywhere to cache results returned by sqlalchemy. The sqlalchemy docs now recommend using [dogpile](http://docs.sqlalchemy.org/en/rel_0_9/orm/examples.html?highlight=cache#module-examples.dogpile_caching) over beaker I think both were at some point written by the [sqlalchemy guys](http://techspot.zzzeek.org/2012/04/19/using-beaker-for-caching-why-you-ll-want-to-switch-to-dogpile.cache/)

http://beaker.readthedocs.org/en/latest/configuration.html
http://dogpilecache.readthedocs.org/en/latest/

**Comment by rossjones** [comment]
This is worse than it appears, as we were actively avoiding the local sqlalchemy 'cache'.

For .get() calls this should be fixed by https://github.com/ckan/ckan/pull/2824 and https://github.com/ckan/ckan/pull/2825 where the ID is passed (because the 'cache' is an identity map on the PK).
