### ISSUE TITLE
search index not updated with new Organization information

### ISSUE THREAD

**Issue by george-sattler** [ckan/ckan#2360]
Not a show-stopper but if you edit the details for an Organization (e.g name, description) then these changes don't get reflected in the "organization" section for a dataset's search-index.

I'm thinking the solution could be that when an Organization's data changes, then a re-indexing occurs for the Organisations' datasets.

Can do a PR for this.

**Comment by amercader** [comment]
Yes, this has been discussed in the past. The main reason not to this is that if the organization has many datasets this could potentially take a long time, causing timeouts. 

This was one of the main use cases on the discussion about having  a generic queu for performing async tasks like this one.

Background:
https://github.com/ckan/ckan/issues/1796
https://github.com/ckan/ideas-and-roadmap/issues/66

Closing this in favour of the two mentioned, but thanks for flagging this @george-sattler. Feel free to add your comments to  ckan/ideas-and-roadmap#66

**Comment by george-sattler** [comment]
no problems!
