### ISSUE TITLE
Add OpenDocument presentation mimetype

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#2366]
All the other OpenDocument mime types are in https://github.com/ckan/ckan/blob/master/ckan/config/resource_formats.json

**Comment by jqnatividad** [comment]
Also, when the user does upload an ODP file...
![edit_-_testodp_-_nyc_zoning_districts_-_betanyc_s_community_data_portal](https://cloud.githubusercontent.com/assets/1980690/6899735/4c3dd5fe-d6d0-11e4-9a82-09e575fb51c0.jpg)

**Comment by amercader** [comment]
@jqnatividad can you create a separate issue for formats overflowing?
