### ISSUE TITLE
ckan added custom fields in default schemas not appears on UI

### ISSUE THREAD

**Issue by NileshKhule** [ckan/ckan#2369]
Added the custom fields "subject' in default schemas json in ckan in /usr/lib/ckan/default/src/ckan/ckan/logic/schema.py fun default_create_package_schema()  in json
added same in templates for custom fields "subject"
/templates/package/snippets//additional_info.html
package/snippets/package_metadata_fields.html
so when I checked on UI,  additional info page throws internal server error while creating datasets.

**Comment by joetsoi** [comment]
Hi. please run through the tutorial here http://docs.ckan.org/en/latest/extensions/adding-custom-fields.html

if you have any troubles, please send them to ckan-dev mailing list, we try to keep general support queries there.
