### ISSUE TITLE
Password reset token are not invalidated [security]

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2370]
I can use generated token multiple times to reset password. It should be invalidated after first successful password change!

Concerns: CKAN 2.3

**Comment by wardi** [comment]
@KrzysztofMadejski absolutely, you're right. Do you have time to submit a fix?

For security related issues like this one please send your future reports to security@ckan.org

**Comment by KrzysztofMadejski** [comment]
sorryy, I will use it in the future!

I see it's already PRed.

**Comment by tino097** [comment]
Looks like this was fixed, also its targeting old release. Closing
