### ISSUE TITLE
Add num_followers to ckan.logic.action.get.package_show

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#2374]
Should we add num_followers to ckan.logic.action.get.package_show to prevent from using deprecated h.get_action() in ckan/templates/package/snippets/info.html? I will send a pull request later.

**Comment by wardi** [comment]
see https://github.com/ckan/ckan/pull/2375#issuecomment-88950394

**Comment by u10313335** [comment]
Just wondering if it is okay to change:
h.SI_number_span(h.get_action('dataset_follower_count', {'id': pkg.id})) }} in ckan/templates/package/snippets/info.html
to something like
h.SI_number_span(h.follow_count('dataset', pkg.id)) to get the number of followers of a dataset (the h.follow_count is a built-in helper function).

**Comment by wardi** [comment]
@u10313335 sounds perfect

**Comment by u10313335** [comment]
Thanks @wardi, I will create a new issue and work on it.
