### ISSUE TITLE
Package activity list shows nothing, but there are activities

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2385]
See: https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L2410

Scenario is:
1. Pull one page of activities - `_activity_objects = model.activity.package_activity_list(package.id,
            limit=limit, offset=offset)`
2. Filter them by users to filter out: `activity_objects = _filter_activity_by_user(_activity_objects,
            _activity_stream_get_filtered_users())`

If all activites on first page are done by filtered out users it results in "No activities are within this activity stream" which is false, when there are other user activities on following pages.

It probably affect other activity views as well.

Solution: filtering should be done before paging, best if they are one sql step.

**Comment by KrzysztofMadejski** [comment]
Maybe `action.get._activity_stream_get_filtered_users` should be moved to model.activity and be applied in base queries. Depends where and when we would like to see unfiltered view (for sysadmins?)

**Comment by wardi** [comment]
I suspect #2034 broke this. As a better fix to the underlying issue I was hoping to rewrite the activity queries, including moving much of the code to the model, and removing the unions-of-unions-of-unions in the query.

@KrzysztofMadejski Are you interested in taking a look at that?

**Comment by KrzysztofMadejski** [comment]
I did this (https://github.com/DanePubliczneGovPl/ckan/commit/340e8b1a7d367e6de65ce29aa1254bec8ec563b2) which should resolve that. I didn't write test for it though.

It would be cleaner to move filtered_out_users completly to `activity.py`. Maybe even to make this `user_id NOT in <filtered out>` as a default Activity filter (I'm not sure if sth like this functions in SQLAlchemy/pylons; I remember Django have it).

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
