### ISSUE TITLE
SSL - previews not possible 

### ISSUE THREAD

**Issue by Lynngre** [ckan/ckan#2404]
Previewing data is not possible with SSL activated.

We're using CKAN v 2.3.

**Comment by mattfullerton** [comment]
I had a similar problem: I had to update my ckan.site_url to use https://
to get it working again.

**Comment by nigelbabu** [comment]
I'd also recommend looking at this [sample configuration](https://gist.github.com/nigelbabu/076ad12c13b2071de8e1#file-ckan_nginx-conf-L33), particularly the line highlighted.

**Comment by amercader** [comment]
Is the data you are trying to preview stored on the DataStore (is there a green "Data API" button on the resource page)? If not you are probably proxing the data through DataProxy, which is an external service served under http, which may cause the browser to block it if your site is run under https.

I recommend making sure the DataStore and DataPusher are set up and enabled.

**Comment by Lynngre** [comment]
We are using the DataStore & DataPusher.  The Api button appears too.  I'll check the sample config.  Thanks.
![screen shot 2015-04-23 at 19 04 25](https://cloud.githubusercontent.com/assets/2675262/7302738/c673b838-e9eb-11e4-9d9a-40b884c04dd3.png)

**Comment by amercader** [comment]
@Lynngre the screenshot you provided shows the data being previewed. Can you elaborate on what is exactly the issue?

**Comment by Lynngre** [comment]
Our devops guy did a hack apparently.  I'll check what exactly he set to allow it, he's not around right now.

**Comment by Lynngre** [comment]
So the hack was the one you suggested @nigelbabu https://gist.github.com/nigelbabu/076ad12c13b2071de8e1#file-ckan_nginx-conf-L33 but it seems the API option is then not available for use as if the site url parameter is set to https the site doesn't work.

**Comment by Lynngre** [comment]
For now we've added a workaround http://opendata.akvo.org:8080/ but then the api is not using ssl.

**Comment by nigelbabu** [comment]
@Lynngre That's not a hack, that's how you actually get HTTPS working :)

I'm still not sure what you mean by the API option not available. I'm looking at [this](https://opendata.akvo.org/dataset/ghana/resource/9e6a56ad-b560-4671-aadd-76b92c4e46b5) dataset and everything seems to be working. Can you link me to one where you're noticing a problem?

**Comment by Lynngre** [comment]
The API links are not https://
![screen shot 2015-05-27 at 14 41 47](https://cloud.githubusercontent.com/assets/2675262/7836189/bcb5cc7a-047e-11e5-924d-054fb8797de4.png)
![screen shot 2015-05-27 at 14 41 55](https://cloud.githubusercontent.com/assets/2675262/7836188/bcb3ac88-047e-11e5-896f-bbeafee17e6e.png)

**Comment by nigelbabu** [comment]
Your `site_url` setting is set to `http://opendata.akvo.org:8080`. Change that to `https://opendata.akvo.org` and it'll work correctly.

**Comment by Lynngre** [comment]
Ah yes, as simple as that :-)  Thank you.
