### ISSUE TITLE
multilingual_dataset plugin breaks API search

### ISSUE THREAD

**Issue by acorbi** [ckan/ckan#2405]
Tested on CKAN v2.3 fork https://github.com/OpenDevelopmentMekong/ckan-2.3
(In 2.2.1 fork Issue could not be reproduced)
Using out-of-the-box schema.xml shipped with CKAN 2.3
Identified multilingual_dataset as error source by removing all plugins and then adding one by one on ckan.plugins variable.

---

If multilingual_dataset plugin is present among the plugin list on the ckan.plugins variable on production.ini/development.ini files, calls to package_search method via API v3 do not return any results:

```
api/3/action/package_search?q=a
```

Without multilingual_datasets on ckan.plugins:

```
{
help": "http://192.168.33.10:8081/api/3/action/help_show?name=package_search",
"success": true,
"result": {
"count": 16,
"sort": "score desc, metadata_modified desc",
"facets": { },
"results": [
{
.... DATASET INFO HERE ....
}]
}
```

With it:

```
{
"help": "http://192.168.33.10:8081/api/3/action/help_show?name=package_search",
"success": true,
"result": 
{"count": 0,
"sort": "score desc, metadata_modified desc",
"facets": { },
"results": [ ],
"search_facets": { }}
}
```

**Comment by acorbi** [comment]
pinging @amercader, we were discussing this today on IRC

**Comment by TkTech** [comment]
For anyone finding this issue in the future, take a look at ckanext-scheming (JSON/YAML schemas) + chanext-fluent (thorough multilingual support)
