### ISSUE TITLE
Clustering markers in CKAN 2.3

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2410]
Specific markers are not shown when zooming in, while when clicking the area they are shown ok. 

After zooming in and out clusters don't come back to theri original position.

Problem:
http://dp-dev.epf.p5.tiktalik.io/dataset/testowa-baza/resource/e5a1e2ef-49e8-463a-bf9b-44070d5085d2

While it work ok in http://demo.ckan.org/dataset/mazowieckie-jst/resource/e06d2626-a5c7-420f-8238-570f0dc21b36

I see that Leaflet was updated from 0.4.4 to 0.7.3. Maybe some code around it was not updated?

![markers_ok](https://cloud.githubusercontent.com/assets/849975/7392287/4c35430c-ee87-11e4-9f9d-4296437ab4bf.png)
![markers_problem](https://cloud.githubusercontent.com/assets/849975/7392297/584b47fe-ee87-11e4-89ee-1f476a382040.png)

**Comment by mattfullerton** [comment]
Yes, I have a suspicion that the markers code is either not Leaflet 0.7 compatible or needs to be updated. See also: https://github.com/okfn/dataportals.org/issues/46#issuecomment-93893279

I'll look into it.

**Comment by mattfullerton** [comment]
My fault. Pull request sent.
