### ISSUE TITLE
resource proxy fails when server can't cope with the headers only request

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckan#2412]
I want to proxy a WMS service:
http://geodienste-hamburg.de/HH_WMS_BWVI_opendata?REQUEST=GetCapabilities&SERVICE=WMS

This link works (GET). But making a HEAD request results in the failure:
400 Invalid method in request

This is, in and of itself, not a CKAN problem. The problem is that the resource proxy gives up if this type of request is not supported:
https://github.com/ckan/ckan/blob/master/ckanext/resourceproxy/controller.py#L46

Is this intended behaviour? The comment on https://github.com/ckan/ckan/blob/master/ckanext/resourceproxy/controller.py#L40 implies (to me) not.

**Comment by amercader** [comment]
That sounds sensible @mattfullerton do you want to send a patch that does a GET request if the HEAD fails?

**Comment by mattfullerton** [comment]
will do

**Comment by mattfullerton** [comment]
The problem is not so fundamental, it's just that we should check for 400 as well as 405. PR sent (#2416).
