### ISSUE TITLE
celery command from command line forces you to use SQLAlchemy as broker

### ISSUE THREAD

**Issue by mostrovoi** [ckan/ckan#2418]
If I understood it correctly the usage of SQLAlchemy as broker/message transport for celery is experimental and thus optional:
http://docs.celeryproject.org/en/latest/getting-started/brokers/index.html#broker-overview

However, according to the current implementation the view and clean commands expects us to use SQLAlchemy:

https://github.com/ckan/ckan/blob/master/ckan/lib/cli.py#L1030
https://github.com/ckan/ckan/blob/master/ckan/lib/cli.py#L1049

We are using Redis as broker and face the problem that this current solution is not working for us. What would be a valid workaround for this? Do you think it is possible to reimplement this functionality by using celery workers?
Thank you!

**Comment by davidread** [comment]
It doesn't force you at all! However yes there are SQLAlchemy references in the view and clean commands, which are optional to use. If using redis broken, you can use the redis client to do these operations instead. Here's my cheat sheet, for a queue named 'bulk':

Number of items in the queue:

    redis-cli -n 1 LLEN bulk

See item 0 in the queue (which is the last to go on the queue & last to be processed):

    redis-cli -n 1 LINDEX bulk 0

To delete all the items on the queue:

    redis-cli -n 1 DEL bulk

However no doubt there are some celery calls which do the same, and therefore work with all brokers. If you can get this working and edit the code here then I'd be delighted.

**Comment by mostrovoi** [comment]
Thank you for the prompt response. I think we will try to reimplement this feature as it is rather important to us. We'll try to make it in a more generic way so that can be used by the community as well.
As a side note, we are trying to expand the current functionality offered by original CKAN and using this branch from datagovuk:
https://github.com/datagovuk/ckan/tree/release-v2.2-dgu

However, seems to me that the current implementation is faulty isn't it? 
Here we are trying to define a single queue:
https://github.com/datagovuk/ckan/blob/release-v2.2-dgu/ckan/lib/cli.py#L1417

But according to celeryd documentation it is only possible to define queues so this does not seem to work. 

https://github.com/celery/celery/blob/2.3-archived/celery/bin/celeryd.py

Am I missing something? How can several queues be initialized with this code? Thanks

**Comment by davidread** [comment]
I'm not sure what you think is faulty. We use all this on the ckan branch
you mention.

We run two queues by running each one in a different process. We use
supervisord to start them both.

**Comment by mostrovoi** [comment]
Hi,
Yes, that is quite correct. But if I understand it correctly you use celeryd, so this:
https://github.com/celery/celery/blob/2.5-archived/celery/bin/celeryd.py#L29

If you see, according to their implementation, there is --queues parameter, no --queue (singular):

.. cmdoption:: -Q, --queues
    List of queues to enable for this worker, separated by comma.
    By default all configured queues are enabled.
    Example: `-Q video,image`

However, in your implementation you are parsing and calling celeryd with '--queue' where is should be '--queues'.  '--queue' parameter does not seem to be supported:
https://github.com/datagovuk/ckan/blob/release-v2.2-dgu/ckan/lib/cli.py#L1466

Am I misunderstanding something ?
Thank you!

**Comment by davidread** [comment]
@mostrovoi both singular and plural work in celery 2.4.2.
