### ISSUE TITLE
SSO Auth via Username Header

### ISSUE THREAD

**Issue by STOIE** [ckan/ckan#2419]
Hi all,

I currently have ckan sitting in a docker container and an apache running on the host machine with kerberos.

Now, like most of our apps we use apache to manage kerberos SSO while proxy-passing to the actual app location, if it picks up a user and authenticates them via kerberos, apache then writes a header with the username and passes it on with the request through to the app.

So the next part would be, we need a way for ckan to first try to pickup this header object.

If the username header exists with a value, it then checks if that user already exists in the db.
If they don't, it would then need to create them with a bunch of default values.
If they do exist in the db, it then sets up their session.

On the other hand, if the username header doesn't exist or is of null value, send the request to the login page.

Unfortunately, I'm NOT a python dev and as a result don't really think I have any chance of digging myself out of this hole alone... but, I was really hoping someone out there could help out?!?

Aaron.

**Comment by mattboehm** [comment]
Here's my quick and dirty implementation of SSO via http header: https://github.com/cfpb/ckanext-cfpb-extrafields/pull/34/files . We have python_ldap installed and configured already, and ckan will fall back to that when the header is not set.
