### ISSUE TITLE
Rename deleted datasets when they conflict with one a user wants to create

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2438]
It's common for users to want to delete a dataset then create one with the same name (URL slug) only to have CKAN tell them they can't do that.

But they should be able to do that! And, we shouldn't have to purge the first package and its history first.

Why don't we munge the name of an existing conflicting deleted dataset from package_create (in a safe way) that would allow the creation of the new dataset?

Munging could be something like `popular-name` -> `popular-name-deleted-1`, `popular-name-deleted-2` and would only happen on package_create, not package_delete.

**Comment by joetsoi** [comment]
I have spoken to two groups of people who want this recently, so I'm going to plus one this twice.
+1
+1

**Comment by amercader** [comment]
Big +1 as well

It's still possible for sysadmins to edit a deleted dataset (they can find them via their dashboard) and edit it to be active again. Should we have a `popular-name-resurrected-1` munging as well? :)

**Comment by rossjones** [comment]
Isn't the problem with doing this rename in package_create that the check for existing package is done in validation with the ```package_id_does_not_exist``` validator. This means either an explicit check for a specific validation error in package_create, or the validator doing more than it should.

Renaming to some version of the existing name then makes it difficult to undelete as the name will be in used.  If we are expecting the user to have to rename during undelete - we may as well just set the name to the id when it is deleted.  On undelete we can follow the usual munging of the title to reset it?

**Comment by wardi** [comment]
yeah, I was thinking of doing the explicit check for a specific validation error in package_create.

The problem with renaming immediately on delete is it's hard to go back and undelete when you deleted by mistake. We could work around that by redirecting to the new package edit url after delete, but once you lose that url how do you find your dataset?

**Comment by rossjones** [comment]
I wish we had numbers on whether anyone actually ever undeletes, or uses history, etc etc.

**Comment by wardi** [comment]
history has been pretty broken for a while, so probably not many users there. Breaking things is a pretty good way of finding out who's using a feature :-/

**Comment by rossjones** [comment]
I think this problem may only actually be one-way.  We've had lots of 'complaints' that package_create doesn't allow people to use the name of a 'deleted' dataset, perhaps we should optimise for that and worry less about people having to change the name field when it is undeleted?  

How about on package_delete we just change the name to ```'__deleted__%s' % package['name']``` and document it for users wanting to find the deleted dataset to undelete?

**Comment by wardi** [comment]
@rossjones we still need to avoid name conflicts so it would be `popular-name-deleted-X` where you'll have to guess X to go back and undelete.

**Comment by rossjones** [comment]
How about we have a paster command to lookup (from partial name) and undelete stuff and just go with that?

**Comment by wardi** [comment]
I'm worried about users without paster access. Is there a page like the sysadmin's trash for normal users? As long as they can find it renaming on delete would be fine with me.

**Comment by TkTech** [comment]
1) New controller path, `/deleted/<uuid>`
2) If a name collides with a deleted dataset it is no longer a validation failure.
3) If a deleted package is restored and would collide, we `flash()` a message saying that the name on one or the other must be edited, linking to the colliding dataset in the message.

Why?

1) Changing names automatically is risky. Restoring them automatically even worse.
2) It's a deleted package, we no longer need an SEO-friendly name for it. Improving the admin trash page should be sufficient for discovery. We can also provide a filter on searches shown only to admins to return deleted items (this is part of our multi facet work)
3) This activity is done so infrequently that a "simple" approach is probably best. Lets not spend months over thinking this.

**Comment by wardi** [comment]
don't think we need the new controller path. We can use the uuid anywhere we can use the package name, `/dataset/<uuid>` is fine

**Comment by rossjones** [comment]
Can we change step 2 to 'on undeleting a package you are sent to the edit for the package (where the name clash will be shown)' ? Would that work?

**Comment by wardi** [comment]
that would allow the name clash to continue to be a validation error (and I can imagine other validation errors appearing when undeleting with custom validation)
