### ISSUE TITLE
Use SemVer spec

### ISSUE THREAD

**Issue by reubano** [ckan/ckan#2439]
According to the [Semantic Versioning Specification (SemVer)](http://semver.org/), all versions must follow the `MAJOR.MINOR.PATCH` style. So `2.3` would be `2.3.0`.

**Comment by wardi** [comment]
@amercader your opinion?

**Comment by amercader** [comment]
Sounds sensible, we can start with 2.4.0

**Comment by k-nut** [comment]
@wardi @amercader it seems to me like we are doing this now. So can this issue be considered solved?

**Comment by amercader** [comment]
Yes, thanks @k-nut
