### ISSUE TITLE
Install ckan via pip module in docs

### ISSUE THREAD

**Issue by reubano** [ckan/ckan#2440]
The docs install ckan via the github url, i.e., `pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.3#egg=ckan'`. Why not install via pip, i.e., `pip install ckan`?

**Comment by wardi** [comment]
@reubano we don't recommend installing through pip because that makes it difficult to install ckan's dependencies from the requirements.txt file. We also don't want to use `install_requires` because we depend on exact versions of many libraries and enforcing versions within setup.py causes problems when we want to try newer versions or install alongside other projects.

**Comment by reubano** [comment]
@wardi you can solve the first issue with a `setup.py` similar to the following (or less complex if you don't need as robust a `parse_requirements` func)

```python
import re

from os import path as p


def read(filename, parent=None):
  parent = (parent or __file__)

  try:
    with open(p.join(p.dirname(parent), filename)) as f:
      return f.read()
  except IOError:
    return ''


def parse_requirements(filename, parent=None, dep=False):
    parent = (parent or __file__)
    filepath = p.join(p.dirname(parent), filename)
    content = read(filename, parent)

    for line_number, line in enumerate(content.splitlines(), 1):
        candidate = line.strip()

        if candidate.startswith('-r'):
            for item in parse_requirements(candidate[2:].strip(), filepath, dep):
                yield item
        elif not dep and '#egg=' in candidate:
            yield re.sub('.*#egg=(.*)-(.*)', r'\1==\2', candidate)
        else:
            yield candidate.replace('-e ', '')


setup(install_requires=parse_requirements('requirements.txt'))
```

I'm not sure I understand the second issue. But would it still be a problem since exact versions are specified in `requirements.txt` and not `setup.py`?

**Comment by wardi** [comment]
When exact versions are in requirements.txt the user is in control of when they "pip install -r requirments.txt" When exact versions are in install_requires setuptools remembers those versions actively prevents the user from ever installing newer versions of any of those libraries, even for testing purposes.
