### ISSUE TITLE
Implement a RESTful API

### ISSUE THREAD

**Issue by reubano** [ckan/ckan#2441]
http://dev.socrata.com/docs/verbs.html

**Comment by maxious** [comment]
http://docs.ckan.org/en/latest/api/legacy-api.html#model-methods ?

**Comment by reubano** [comment]
```
The legacy APIs documented in this section are provided for backwards-compatibility, 
but support for new CKAN features will not be added to these APIs.
```

Doesn't really encourage usage of this API. Seems like its support could be dropped at any time.

**Comment by wardi** [comment]
The current version of the API "version 3" is JSON RPC, and that's unlikely to change.

JSON RPC neatly wraps CKAN's logic layer, exposing virtually all of the functionality of CKAN with almost no extra work for the developers. The REST API was a layer that needed to be maintained, frequently broke, and never exposed the complete feature set.

JSON RPC is easier to extend in plugins http://docs.ckan.org/en/ckan-docs-theme/writing-extensions.html#ckan.plugins.interfaces.IActions and easier to wrap for clients https://github.com/ckan/ckanapi than a REST API.

CKAN's API also behaves the same if you pass arguments as GET parameters (making it easier to use with just a web browser), as multipart form data (great for posting directly from browsers, including file upload streams) or as a single flat JSON object.

I don't see the value in implementing a REST API given all the benefits we have from the current API.

**Comment by reubano** [comment]
@wardi doesn't this contradict https://github.com/ckan/ideas-and-roadmap/issues/42 where you suggest a move to REST? I can't comment on plugins, but REST API's are quite easy to wrap in clients via curl, requests, etc. The biggest upside to REST is that it plays nicely with frontend MVC frameworks like [angular.js](http://fdietz.github.io/recipes-with-angular-js/consuming-external-services/consuming-restful-apis.html) and [backbone.js](http://stackoverflow.com/a/18506418/408556). And tools like [flask-restless](https://flask-restless.readthedocs.org/en/latest/), [eve](https://github.com/nicolaiarocci/eve), and [others](https://github.com/vinta/awesome-python#restful-api) take the hard work out of maintaining it.

**Comment by wardi** [comment]
@reubano In ckan/ideas-and-roadmap#42 I'm saying let's make our JSON RPC interface more consistent so we can build a generic REST layer on top.

**Comment by reubano** [comment]
@wardi ah, ok I misunderstood it then.

**Comment by wardi** [comment]
@reubano it's also possible I was rambling and contradicting myself. I tend to do that in ideas tickets. :smiley:

Closing in favour of ckan/ideas-and-roadmap#42 Happy to reopen if someone is planning to work on revamping our old REST API
