### ISSUE TITLE
Can't get server to run on Mac OS X (source install)

### ISSUE THREAD

**Issue by reubano** [ckan/ckan#2442]
tried all ckan versions 2.0 on up. Running Mac OS X 10.9.5.

**Comment by davidread** [comment]
This OS is not supported I'm afraid. Try using Docker or Virtualbox with an ubuntu image.

**Comment by reubano** [comment]
Do you know why it doesn't work on macs? Python is cross platform.

**Comment by davidread** [comment]
What error message did you get?

**Comment by reubano** [comment]
No error. Everything installed fine. But when I run the server and open the link, it is just a blank page.

**Comment by davidread** [comment]
Other people have kindly contributed suggested ways to do it, such as: https://github.com/ckan/ckan/wiki/Installing-CKAN-2.2.1-on-Mac-OS-X-10.10.1 The python part isn't the problem, it is installing and configuring the dependencies which varies most between platforms, which is why we put our limited resources into supporting ubuntu only.

**Comment by wardi** [comment]
Echoing @davidread: we just don't have the resources to handle support requests for multiple operating systems, and most of the difficulties are related to installing solr and postgres on OSX. Also, CKAN is more than just a python program: It's a platform with a large number of third-party extensions. Making sure all those work across operating systems is a huge task.

http://docs.datacats.com/ might be an option for you. We're using it to develop CKAN sites on OSX. It lets you work on CKAN sites like they are local applications.

**Comment by reubano** [comment]
I've installed the dependencies via macports so that isn't the issue. Just that when I try to actually run the ckan server it doesn't do anything. I'm now trying the ckan docker image to see if it makes a difference. If that fails I'll try the datacats option @wardi mentioned. What would help is some kind of diagnostic tool to run so that ckan will tell you if it can properly detect everything that should be there. For example, if I run `paster serve /etc/ckan/default/development.ini`. It starts a server regardless of whether or not I have `cd`d into the proper folder or not.

**Comment by davidread** [comment]
If anything's wrong then you should get meaningful errors in the log, just like any app. However the core team will not divert resources to help every single platform. Try the list.

**Comment by reubano** [comment]
Got it working now. I think the issue may have been a missing config option but who knows. Am in the process of creating a [wiki page](https://github.com/ckan/ckan/wiki/Howto-install-CKAN-2.3-from-source-on-Mac-OS-X-10.9.5-with-macports). CR https://github.com/ckan/ideas-and-roadmap/issues/148
