### ISSUE TITLE
tutorial: handling multiple dataset schemas using IDatasetForm

### ISSUE THREAD

**Issue by joetsoi** [ckan/ckan#2446]

**Comment by wardi** [comment]
cool. maybe will help users with issues like https://github.com/open-data/ckanext-scheming/issues/55

**Comment by joetsoi** [comment]
yeah that's ones of the things I'll cover in it. I'll try and tie some stuff in about ckanext-scheming as well, but I'll probably add that stuff into scheming itself.

**Comment by wardi** [comment]
@joetsoi do you think CKAN should implement separate buttons for each IDatasetForm types that are enabled in its default templates?

**Comment by joetsoi** [comment]
we already add the routes, so we probably should do something like that.

**Comment by rossjones** [comment]
Closing this ticket due to inactivity.  Suspect the tutorials_* tickets should be in https://github.com/ckan/ideas-and-roadmap
