### ISSUE TITLE
Translation for mn_MN contains translation of placeholder

### ISSUE THREAD

**Issue by nigelbabu** [ckan/ckan#2454]
See the following. It should say `{number}`, instead it says `{тоо}`.

https://github.com/ckan/ckan/blob/master/ckan/i18n/mn_MN/LC_MESSAGES/ckan.po#L4143
https://github.com/ckan/ckan/blob/master/ckan/i18n/mn_MN/LC_MESSAGES/ckan.po#L4143

This means that group and organization pages with more than one item will throw a traceback straight up.

**Comment by davidread** [comment]
As a start, I've corrected this string in Transifex for CKAN 2.4 (there were about 3 of them that had mistakenly translated "{number}").

**Comment by amercader** [comment]
It's a little worse than that I'm afraid. I'll post more details once I get the patch releases out

**Comment by amercader** [comment]
Closing in favour of #2613
