### ISSUE TITLE
RDF rendering fails if extra field is none

### ISSUE THREAD

**Issue by mostrovoi** [ckan/ckan#2456]
The following code is incomplete:

 {% for extra_dict in c.pkg_dict.get('extras',None) %}

https://github.com/ckan/ckan/blob/master/ckan/templates/package/read.rdf#L62

It makes no sense to return None as default and it is missing a prior checking if extras is None
Another option is to return "" instead None as placeholder

**Comment by davidread** [comment]
Agreed. However we've now moved RDF rendered to ckanext-dcat - please use that instead.

See https://github.com/ckan/ckan/pull/2560

**Comment by mostrovoi** [comment]
ok, thank you. we will
