### ISSUE TITLE
Datapusher: CSV with BOM causes creation of column with BOM

### ISSUE THREAD

**Issue by mvi-eea-sk** [ckan/ckan#2463]
When uploading CSV file (maybe XLS too, didn't check) that has BOM at the beginning of the file, datapusher creates the first column with the BOM.

CSV like:
```
\ufeffColumn1,Column2,Column3
value1,value2,value3
```

would create datastore resource table with column ```\ufeffColumn1```

This is quite troublesome when you want use API to retrieve / manipulate data from datastore.
For example: datastore_search_sql with sql parameter ```select Column1 from resource_id``` would return error saying there is no Column1.

**Comment by brew** [comment]
This is an issue with messytables, as discussed previously in #2401. Closed as duplicate.
