### ISSUE TITLE
Cross Site Scripting Attack (XSS) via fileupload

### ISSUE THREAD

**Issue by ajay027** [ckan/ckan#2464]
CKAN has "Add dataset" functionality which uses file upload to upload files. File which is getting uploaded is not getting validated on the server side for restricted content-type. It is possible to upload a html file containing malicious javascript code. Using which an attacker can steal cookie of logged in user and much more. 
It is recommended to check content-type of the uploaded files on the server-side code.

![ckanxss](https://cloud.githubusercontent.com/assets/12871872/8144228/40c5d874-11f0-11e5-839d-18f74bb2d5c8.png)

**Comment by amercader** [comment]
Thanks for the report, we are aware of this issue. Please submit security related issues to security@ckan.org
