### ISSUE TITLE
Update requirements.txt for requests and six to avoid version conflict with ckan-galleries

### ISSUE THREAD

**Issue by florianm** [ckan/ckan#2470]
When installing [ckan-galleries](https://github.com/DataShades/ckan-galleries), ckan's requirements of python packages requests and six collide with flickrapi's requirements (via ckan-galleries), also reported [here](https://github.com/DataShades/ckan-galleries/issues/2).

Would anything speak against increasing the versions to the following? I haven't got a sane test environment atm so will have to send a PR to let Travis do the testing.
```
requests==2.7.0
six==1.9.0
```

**Comment by davidread** [comment]
requests upgrades need coordination, as several common extensions use it and need to be upgraded in step. So someone need to go through them carefully and make any necessary changes to include support for the later requests version.

**Comment by florianm** [comment]
What would be the best procedure for this, @davidread ? 

I'll see which of the 133 extensions from http://extensions.ckan.org/ depend on requests and/or six, but I'll probably need help to test them all against requests 2.7.0 and six 1.9.0. 

I can't see any breaking changes in python-request's [release notes](http://docs.python-requests.org/en/latest/community/updates/#software-updates), all the listed behavioural changes look more like additional features and bug fixes but I could be wrong.
There seem to be no release notes for six so I've got no clear idea of possible breaking changes.

**Comment by joetsoi** [comment]
I wouldn't go through and test all the extensions, as david said we should probably test the more common extensions.

**Comment by wardi** [comment]
Also, the version in ckan's requirements.txt doesn't prevent you from requiring a newer version in one of your extensions. That's the reason we pin versions in requirements.txt and not in install_requires

**Comment by davidread** [comment]
I imagine six is purely for ckan - if it passes the tests then that's probably enough.

ckanext-archiver was my particular concern, although it's only used by uk, us and some old OKF project afaict. But if it is still at 1.1 then it's not going to be much worse at 2.7.

I'd have thought doing some basic checks with ckan including datapusher, ckanext-harvest, ckanext-spatial and ckanapi is probably sufficient.

This should probably miss the 2.4 branching next week to let it bed in.

**Comment by florianm** [comment]
@joetsoi I'll go through the list of extensions to at least identify which ones depend on requests and six so we can choose which ones to test
@wardi I had the opposite experience - ckan-galleries's newer versions of requests and six collided with ckan's older versions (in my local datacats install)
@davidread yup, ckanext-archiver pinned requests==1.1.0 in Feb 2013, when that was presumably the latest requests version. I'm hopeful requests didn't break backwards compatibility since then.

Who wants to add urls to extensions' requirements to [the extensions CSV](https://docs.google.com/spreadsheets/d/1izCpljO6Et7zLUKcUlB4BzsMZTurENp56Iqi9kXOtgs/edit#gid=0)? That would simplify checking for cross-dependencies.

**Comment by florianm** [comment]
@davidread @joetsoi @wardi going through dependencies manually is a bit tedious, so I've listed them all here: http://rshiny.yes-we-ckan.org/ckan-pip-collisions/ - more to come soon.

**Comment by davidread** [comment]
Ooh that is a neat app!

**Comment by davidread** [comment]
I've just tested the DGU fork of ckanext-archiver with requests 2.7.0 and had to make only a tiny change:

https://github.com/ckan/ckanext-archiver/commit/86b6007f18046ce47fb4fa92137e71974497dc99

and the same change was made also on master:

https://github.com/ckan/ckanext-archiver/commit/86b6007f18046ce47fb4fa92137e71974497dc99

which suggests it is probably ok.

**Comment by davidread** [comment]
@KrzysztofMadejski what version of requests are you using and can you confirm it is working with ckanext-archiver and possibly also ckanext-qa and ckanext-spatial too?

**Comment by florianm** [comment]
The extensions listed at http://govhack2015.readthedocs.org/en/latest/2_CKAN_extensions/ work fine with the latest versions of requests, lxml, six and python-dateutils as documented [here](http://govhack2015.readthedocs.org/en/latest/2_CKAN_extensions/#manage-dependency-conclicts).

**Comment by davidread** [comment]
Thanks @florianm . This is what I gather from that:

ckanext-qa works fine. Everything is pointing to this extension being ok so satisfied on that one.

ckanext-spatial works fine with florian's fork. The fork is not concerned with the areas which requests is used though, which is the CSW harvester. Have you tested that part by chance? (Fork is: https://github.com/ckan/ckanext-spatial/compare/master...florianm:master)

**Comment by florianm** [comment]
@davidread I haven't gotten ckanext-qa to work, but that's an issue with the datacats/celery daemon side, not the requests version. 
I haven't gotten around to get spatial harvesting to work either, but aim to do so in the coming two weeks. I'll keep you posted.

**Comment by florianm** [comment]
@davidread I'm not through yet, but here's an update:
* since last week, datacats/datacats#334 is breaking the datapusher but the 'cats are working on it
* related to ckan/ckan-service-provider#30 (ping @seanh )
* ckanext-spatial is broken in my datacats environment with a completely [new error](https://github.com/datacats/datacats/issues/334#issuecomment-146057590) around the geoalchemy upgrade (I miss my monkeypatch using chokoswitch's geoalchemy fork)
* I'll re-fork ckanext-spatial and start over with my work on the georeferencing widget, debugging the geoalchemy error first
* I'm harvesting using ckanapi in ipython notebooks as my harvesting is too bespoke to be of general value (custom WMS through custom proxy into custom schema)

Overall, my gut feeling is that requests==2.7.0 is a workable version for everyone to pin. Six seems to be ckan only, and it works fine on my end, so I'd say that's safe to upgrade too. There are other version conflicts I'd like to fix (libxml, dateutil, and recently sqlalchemy/geoalchemy breaking spatial).

**Comment by davidread** [comment]
Ok I've just tested ckanext-spatial with requests 2.7 (it was the WAF harvester that used it, not CSW after all), and that's fine.

So we've tested its ok with:
* ckanext-harvest
* ckanext-spatial
* ckanext-qa

According to your app, other extensions are:
* ckanext-barnet
* ckanext-govdatade
* ckanext-iati
* ckanext-publicamundi
* ckanext-realtime
* ckanext-themeSmartStreets
* ckanext-themeUrbanOpus
* ckanext-wotkit

Since those are mostly customizations for one site only, I think they can look after themselves on this one.

Notably ckanext-galleries isn't mentioned because its dependencies are in setup.py and your dependencies app only covers *requirements*.txt files, so there may be a few more extensions like this, but I'm not too worried as we know about the main ones.

I'm going to do a PR for upgrading ckan's requests, and if that passes travis then I'll do it for the extensions.

**Comment by florianm** [comment]
Great news! Yeah I need to include setup.py and add a refresh button. Also
I'm only considering the master branches.

**Comment by florianm** [comment]
As @amercader mentioned, putting requirements into requirements.txt is
preferred over requs in setup.py. Could that be part of the extensions
guide if it isn't already?

**Comment by davidread** [comment]
Good idea about mentioning that in the extensions guide - perhaps you could
create a PR to do that?

**Comment by davidread** [comment]
All 'requests' version changes merged, hooray!

'six' version upgrade is being done as part of: https://github.com/ckan/ckan/pull/2561

so closing this.

**Comment by florianm** [comment]
@davidread docs PR sounds good, will do! Thanks for merging the request for the requests.
