### ISSUE TITLE
Provide dummy English translation

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#2475]
Currently, if you load CKAN with the "en" locale, there is a conditional, that prevents a translation to be loaded (see https://github.com/ckan/ckan/blob/master/ckan/lib/i18n.py#L132-133).

In order to make it easier to customize the English translation (i.e. we want to replace "Groups" with "Projects") it would be very handy to remove this special case, and just provide an empty English translation. This way, you could add a custom translation for English, without having to change a CKAN core file.

Of course, we can currently just "abuse" en_GB for instance, and change the values there, but this feels very hackish.

Any opinions on that?

**Comment by joetsoi** [comment]
@metaodi, i thought exactly the same thing see https://github.com/ckan/ckan/pull/2461#discussion_r32520972

If you want to just replace the strings, it would be good if you could try out that pull request as we've had the same requirement a few times.

If other people do agree, I'm happy to change the implementation to use a dummy english translation instead of catching the AttributeError

**Comment by metaodi** [comment]
@joetsoi that looks good, I'll try that out and provide you with feedback. Nonetheless, I think it's not worth to handle "en" in such a special way. I personally think the long term goal should be to replace the English terms with truly unique keys, something like `ckan.organization_title`, and then provide a translation in every language, including English e.g. `Organization`.

This would make it possible to provide different translations for the same string, depending on where it is used. I'm pretty sure, there are translations that would benefit from this, if the original would be more "precise".

**Comment by joetsoi** [comment]
yeah, I think that might be a nice way of doing things, there will be issues, I think transifex always makes you define a source language and you have to specify the a language locale for the source.

**Comment by wardi** [comment]
That's going to make editing the templates much harder. I always grep around for text I see to find the template to edit, how will that work if all the text is replaced with tokens?

**Comment by joetsoi** [comment]
that's true as well. The other way I've seen is to use different gettext domains to specify different contexts for different strings. We could also probably choose some better terminology in some places. My current favourite is "View view" in resource views.

**Comment by wardi** [comment]
Ha! I can just hear the translators crying about that one.

**Comment by metaodi** [comment]
@wardi Yeah, you're probably right. But I'm sure there could be a work around like the possibility to load the page without any translations, hence you would see the tokens that you could search for.

Anyway: my original issue is to have an empty English translation and not treat it in a special way.

**Comment by tedstrauss** [comment]
@metaodi  Did you find some way to modify strings on the default english translation? I'm in the same situation.

**Comment by tedstrauss** [comment]
(huh?!... I didn't unassign anyone ... nor should i have permissions to do so ... github bug?)

**Comment by wardi** [comment]
@tedstrauss my mistake! this was a change I thought had been merged into master but it's only on my fork of ckan at the moment and in an unmerged PR https://github.com/ckan/ckan/pull/2909

I'll unassign it since @joetsoi is no longer active on ckan.

**Comment by metaodi** [comment]
@tedstrauss for those instances where I need this, I simply patched the i18n.py file to not treat 'en' in a special way and hence load the translation. This is not a clean solution, so this issue is still open.

**Comment by tedstrauss** [comment]
So just to be clear, if I replace the file i18n.py with the version on PR #2909 ([here](https://github.com/LaurentGoderre/ckan/blob/3a99ebd62d2c6e81dff8d07032f05d6a3adf613a/ckan/lib/i18n.py)) and compile that, then the overriding of the default language should work. Right?

**Comment by metaodi** [comment]
@tedstrauss I'm using a different version, but I have no link to it atm. But from quickly looking at it, the version you linked to should work as well. Maybe also check [the extra-directory config](http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-i18n-extra-directory)

**Comment by tedstrauss** [comment]
It appears to be working!

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.

**Comment by saikarthikp9** [comment]
[ckanext-customizer](https://github.com/saikarthikp9/ckanext-customizer)
Use this extension to replace the terms "group" and "organization" in English. It is a hacky solution. PR/requests are welcome!
