### ISSUE TITLE
If you change licence URL, the dataset sees it only when it's updated

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2479]
> If the value of your licence picklist choices stays the same, but you update the URL associated with them in the json file (e.g. to point to the newest version of the license conditions), then IF you edit/update a dataset the license type chosen will not be changed, BUT the URL it now points to will get changed. 

If you change a licence's URL then all datasets with that license would show the new license URL straight away, if it wasn't for caching. Editing it refreshes the cache, but it could be done manually. So ideally the cache would be purged for the relevant datasets automatically (PR welcome).

@Aaron-M Does that cover it, or is there something else amiss here?

Originally from here: https://github.com/ckan/ideas-and-roadmap/issues/153

**Comment by metaodi** [comment]
That would mean that only the `license_id` would be saved on the dataset, and the URL and the title would be resolved via the loaded license file, correct?

**Comment by Aaron-M** [comment]
Hi, the behaviour of NOT changing the underlying URL of a chosen licence is (usually*) desired (ideally if you update our picklist you want existing records to retain both their licence label, and the URL they were pointed too, even if the record is edited for some other change.

As the per ckan/ideas-and-roadmap#153 we have updated our licence picklist so licence choices applied to past records no longer appear in the drop down (we don't want them in the drop down, as they should no longer be selected for new records).  Changing the dropdown does not affect the functionality of 'old' licence choices UNLESS a record is edited for whatever reason - then the licence might get changed completely (if a matching license value is no longer in the list ref #2472), or only the URL may get changed (if the license value is in the list but the link has been updated to a newer version - this can occur if the license value is underspecified (#2478) say just as CC-BY (attribution) and the license type is the same but the version has been updated via the URL).

[*Of course there could be occasions where say the link to the license is moved and you want to change the stored URL to a new location, but that is a slightly different issue.]

Ultimately licenses in the picklist should be more fully specified, and the license value and URL assigned should remain in place even if a license choice is subsequently removed from the picklist.

Hope that makes sense.

**Comment by davidread** [comment]
> the behaviour of NOT changing the underlying URL of a chosen licence is (usually*) desired
In which case, I say don't change the definition of the licence. 

What is stored in the CKAN db against a dataset is the licence_id e.g. 'cc-by', and when you do package_show it looks up the rest of the details from the licences it knows about. If @Aaron-M knew that then he'd simply have created a new licence for the new URL and we'd avoid this problem.

I think @Aaron-M had imagined that when you pick a licence, all of the licence properties are copied into the dataset. This is clearly less efficient than the dataset just holding a reference, and it seems strange holding possibly conflicting information about a licence between different datasets. e.g. you could have the same CC-BY URL in two datasets, but one could say it is open and has no version number, and another with a version number. This method really seems to go against the grain.

I hope that clears things up - if there's any way we can make this clearer in the code or docs then do suggest.

**Comment by davidread** [comment]
Probably just need a note in the config docs to say reindex solr if you change the licence info.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
