### ISSUE TITLE
Package schema erroneously passed to resource_view_create when updating

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#2482]
The same issue as described in #2421, happens when updating a package here:
https://github.com/ckan/ckan/blob/master/ckan/logic/action/update.py#L364-366

I guess a similar fix should do the trick:
- Move this https://github.com/ckan/ckan/blob/master/ckan/logic/action/update.py#L375-376
- up some lines before calling `package_create_default_resource_views`

I didn't look at this in depth, but it failed for me in a custom harvester in CKAN 2.3, so a backport to 2.3 just like #2421 would be nice.

If I find the time, I can help with the PR:

**Comment by wardi** [comment]
/me mutters something about https://github.com/ckan/ideas-and-roadmap/issues/53

**Comment by metaodi** [comment]
Okay, here is the PR: #2484

**Comment by rossjones** [comment]
This appears to have been fixed by https://github.com/ckan/ckan/pull/2503 
If this is not the case, please re-open this ticket.
