### ISSUE TITLE
Exported .ckan should use 'suggests' instead of 'depends'.

### ISSUE THREAD

**Issue by QuickBASIC** [ckan/ckan#2488]
It's frustrating going to a fresh install and using a .ckan if a KSP version has recently changed. If any of the modules have not been updated to the new KSP version it chokes and none of the modules gets installed.

>About to remove:
>
>Done!
>
>Module KerbalEngineerRedux required, but not listed in index, or not available for your version of KSP
>
>
>
>Error!

**Comment by brew** [comment]
Wrong CKAN :)

**Comment by amercader** [comment]
I think you want this https://github.com/KSP-CKAN/CKAN
