### ISSUE TITLE
ReclineView: Bug: Column name with special chars (star, braces, etc.)

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2490]
On https://danepubliczne.gov.pl/dataset/baza_teleadresowa_administracji_zespolonej/resource/f051b7ab-2780-441c-a39b-ce02d7b8d8fa

in console you can see error: `bootstrap.js:3 Uncaught Error: Syntax error, unrecognized expression: GEOGRAFICZNA*)` which is caused by column `SZEROKOŚĆ GEOGRAFICZNA*)` while invoking: 

https://github.com/ckan/ckan/blob/0f145a54629287a6f7764b8fd73963bda62260ef/ckanext/reclineview/theme/public/vendor/recline/recline.js#L3225

    function sanitizeFieldName(name) {
      var sanitized = $(name).text();
      return (name !== sanitized && sanitized !== '') ? sanitized : name;
    }

BTW: `$(name)` never seems to return anything.

Problem arises in CKAN 2.3 (reclineview).
This work correctly in CKAN 2.2.1 (reclinepreview) as you can see in demo: http://demo.ckan.org/dataset/lubuskie/resource/42f569fc-6da1-4eea-9ab7-1b1f43a836b2

**Comment by mattfullerton** [comment]
Looks like this is fixed in upstream Recline: https://github.com/okfn/recline/issues/473

I tried CKAN with latest Recline recently and had no problems. Should I make a PR?

**Comment by brew** [comment]
A PR updating Recline would be great. We probably won't be able to pull it into the upcoming 2.4, but should be fine for 2.5.

**Comment by maxious** [comment]
Could the patch from this ticket (https://gist.github.com/maxious/41b32a05581d1656a154 for CKAN specifically) be applied to the bundled recline for 2.4 rather than waiting for a full recline upgrade? 
Users are running into this issue immediately when using beta 2.4/2.3. 
As you would guess, there is a lot of data given in percentages and dollar amounts ;)

**Comment by amercader** [comment]
@maxious can you send a PR with the patch? I'll see if I can squeeze it before the release

**Comment by amercader** [comment]
Also can you upload a failing file to beta.ckan.org? This is working for me: http://beta.ckan.org/dataset/csv-with-special-characters-on-header/resource/9823f342-2c7e-419f-8c77-8d0ffce50764

**Comment by maxious** [comment]
Sure, made PR #2549 and added example to gist https://gist.github.com/maxious/41b32a05581d1656a154 and loaded link into beta.ckan.org

http://beta.ckan.org/dataset/csv-with-bracket-header/resource/3ef49677-a764-4621-8f92-23a757d9b9a8 fails to display recline view with JS error "bootstrap.js:3 Uncaught Error: Syntax error, unrecognized expression:"
http://beta.ckan.org/api/action/datastore_search?resource_id=3ef49677-a764-4621-8f92-23a757d9b9a8&limit=5 shows data exists

**Comment by amercader** [comment]
Merged and backported to 2.3.1 and 2.4.0
