### ISSUE TITLE
stats extension has both templates and legacy_templates

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2492]
These two seem the same:
- ckanext/stats/templates_legacy/ckanext/stats/index.html
- ckanext/stats/templates/ckanext/stats/index.html

We got rid of ckan's legacy templates - maybe we can do the same for this extension?

**Comment by davidread** [comment]
Tech meeting: agreed, let's get rid of legacy.

**Comment by davidread** [comment]
PR is waiting for review: https://github.com/ckan/ckan/pull/2500

**Comment by rossjones** [comment]
The associated PR was merged, so closing.
