### ISSUE TITLE
Timezone setting

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2494]
Add a config setting for the timezone for the site. So times that appear correctly in the Last Updated / Created fields, Activity Stream and extensions such as ckanext-harvest's harvest errors. Until now they all appear in UTC, as it is in the database, I believe.

Perhaps it should default to the timezone of the server? Although that's probably not helpful for cloud servers.

**Comment by wardi** [comment]
JS will save us all. let the user's browser decide how to display times

**Comment by brew** [comment]
Something like: http://momentjs.com/timezone/

**Comment by davidread** [comment]
If not JS, then perhaps by default we can have "UTC". And maybe we display the timezone after the time?

**Comment by metaodi** [comment]
I'll look into that. As far as I know, there is no other way but JavaScript to determine a users timezone. But apart from that, there should be a server side setting to either explicitly set the timezone or use the default timezone of the server.

**Comment by metaodi** [comment]
PR for this issue: #2505

**Comment by metaodi** [comment]
@davidread  #2505 got merged, so I think we can close this issue.
