### ISSUE TITLE
Dataset creation page generates incorrect URLs with Chrome autocomplete

### ISSUE THREAD

**Issue by JackMc** [ckan/ckan#2501]
Expected:
CKAN will give a url like /dataset/a-descriptive-dataset when faced with a title like "A descriptive dataset"
![Normal behaviour](http://i.imgur.com/2Ji45k5.png)

Real:
CKAN gives a URL based on what was typed prior to the autocomplete coming into effect
![Real behaviour](http://i.imgur.com/DhbzuHg.png)

**Comment by joetsoi** [comment]
@JackMc , this happens in firefox as well, are you able to help fix this at all?

**Comment by JackMc** [comment]
For sure! :) I will try and fix and submit a PR

**Comment by joetsoi** [comment]
wow, cool, this one has annoyed me for a while everytime i'm creating test datasets.

**Comment by gleb-rudenko** [comment]
@joetsoi, @amercader, is it still topical?

**Comment by gleb-rudenko** [comment]
same is still happening

**Comment by TkTech** [comment]
The JavaScript for this needs to listen for both `change` and `input` instead of `keypress` to work on all browsers.

**Comment by klikstermkd** [comment]
@gleb-rudenko @TkTech I will work on this.
