### ISSUE TITLE
How to get datapusher work with CKAN 2.4

### ISSUE THREAD

**Issue by khanh78** [ckan/ckan#2506]
Hello,
I have an issue while trying to add plugin datapusher.

the trace show : cannot load Python module

[Sat Jun 27 09:57:39.735336 2015] [authz_core:debug] [pid 17168] mod_authz_core.c(835): [client 127.0.0.1:49924] AH01628: authorization result: granted (no directives)
[Sat Jun 27 09:57:39.742611 2015] [wsgi:info] [pid 17162] mod_wsgi (pid=17162): Create interpreter 'default.yourdomain.com|'.
[Sat Jun 27 09:57:39.743802 2015] [wsgi:info] [pid 17162] [remote 127.0.0.1:512] mod_wsgi (pid=17162, process='ckan_default', application='default.yourdomain.com|'): Loading WSGI script '/etc/ckan/default/apache.wsgi'.
[Sat Jun 27 09:57:41.039617 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512] mod_wsgi (pid=17162): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Sat Jun 27 09:57:41.039813 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512] mod_wsgi (pid=17162): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Sat Jun 27 09:57:41.039883 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512] Traceback (most recent call last):
[Sat Jun 27 09:57:41.039943 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]   File "/etc/ckan/default/apache.wsgi", line 10, in <module>
[Sat Jun 27 09:57:41.040044 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]     application = loadapp('config:%s' % config_filepath)
[Sat Jun 27 09:57:41.040086 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Sat Jun 27 09:57:41.040252 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]     return loadobj(APP, uri, name=name, **kw)
[Sat Jun 27 09:57:41.040291 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Sat Jun 27 09:57:41.040336 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]     return context.create()
[Sat Jun 27 09:57:41.040373 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Sat Jun 27 09:57:41.040553 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]     return self.object_type.invoke(self)
[Sat Jun 27 09:57:41.040671 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Sat Jun 27 09:57:41.040759 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Sat Jun 27 09:57:41.040873 2015] [wsgi:error] [pid 17162] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/

Datapusher seems to be correct because I'm get the message with curl

root@debian:/# curl 0.0.0.0:8800
{
  "help": "\n        Get help at:\n        http://ckan-service-provider.readthedocs.org/."
}root@debian:/# 
when I try 127.0.0.1:8080 I have Internal Server error

Thanks for any help or advices

**Comment by florianm** [comment]
Hi,

if apache.wsgi can't be loaded, there might be an error tripping over CKAN
or one of your installed extensions. Your stack trace looks truncated at
the end - there are unclosed quotation marks. Is there more of that stack
trace? If so, it'll probably tell you where the problem lies.
DId you run CKAN with the default extensions (only)?
Does your .ini say "ckan.datapusher.url = http://127.0.0.1:8800/"?
Mind that the datapusher goes fully outside your machine and comes in as a
regular HTTP request on port 8800 (or whatever your set it to). See also
https://github.com/ckan/datapusher/issues/18 and a diagram of the HTTP
traffic at
http://data-demo.dpaw.wa.gov.au/dataset/dpaw-ckan-multi-site-architecture/resource/ae26b6f2-5ad5-46f1-b91d-3d40a19a77c4
(see how SolR stays local as opposed to datapusher). Did you open that port
8800 in your firewall?
Why do you get an internal server error on the tomcat port 8080?

HTH,
Florian

**Comment by khanh78** [comment]
Hi Florian,

Thanks for your answer.
If I remove datapusher on the line plugin then everything is working fine

#               same origin policy
#ckan.plugins = stats text_view image_view recline_view datastore datapusher
ckan.plugins = stats text_view image_view recline_view datastore

as soon as I add datapusher then I cannot access to my site on port 80 or 8080 and use CKAN.
I can also upload file but I cannot make a preview because datapusher is not there.

I am ruuning on Debian 8
I also have installed Ubuntu 12.04 and install CKAN from package and the plugin is working fine.
I do not know why on Debian it cannot load Python module when the plugin is added.

I run on the same server so no issue with firewall.

Regards 
Khanh

**Comment by khanh78** [comment]
Hi Florian,

Could you advice me which CKAN version on Debian 8 ?
Where can I get package CKAN installation Debian instead of installation from source ?


Thanks for your helps

**Comment by florianm** [comment]
Hi Khanh,

unfortunately I'm only familiar with CKAN on Ubuntu 14.04 LTS. Without any
further error logs (and in my case, without knowledge of Debian 8) it's
hard to tell where this Debian-specific problem lies. Your best option
might be to look what the web server logs say about the datapusher error
(/var/log/apache2/error.log or as configured in your .wsgi), and turning
the log level up to INFO or DEBUG at the bottom of your ckan .ini.

Re same server: your datapusher (default: running on port 8800) will be
accessed from your CKAN (running on port 5000 or as configured) through an
HTTP request which will leave the localhost, and come in through the front
door like a request from an entirely different machine (in the view of your
firewall). So if your machine has any sort of firewall, port 8800 has to be
open.

If you want to go with a Ubuntu source install, I've written up my setup at
[0], feel free to follow along these lines.

Re Debian package, according to the CKAN 2.5.0a docs [1], there is only the
option of a Ubuntu package or a source install (which is way more fun).

As I'm only a simple user, not a core CKAN developer, that's all I can tell
you.

Good luck, and feel free to post your error logs showing where the problem
happens!
Florian

[0]
https://github.com/opendata/CKAN-Multisite/issues/10#issuecomment-70068327
[1]
http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html

**Comment by khanh78** [comment]
Thanks Florian for your answer.

I am a beginner on CKAN.
I have configure datapusher folowing this URL
http://docs.ckan.org/projects/datapusher/en/latest/
the test on port 8800 is working fine 
when I run http://127.0.0.1/8800 I can get those message in file log file /var/log/apache2/datapusher.error.log

Sat Jun 27 15:24:35.768438 2015] [authz_core:debug] [pid 8666] mod_authz_core.c(835): [client 127.0.0.1:57042] AH01628: authorization result: granted (no directives)
[Sat Jun 27 15:24:35.783821 2015] [wsgi:info] [pid 8663] mod_wsgi (pid=8663): Create interpreter 'ckan:8800|'.
[Sat Jun 27 15:24:35.788585 2015] [wsgi:info] [pid 8663] [remote 127.0.0.1:512] mod_wsgi (pid=8663, process='datapusher', application='ckan:8800|'): Loading WSGI script '/etc/ckan/datapusher.wsgi'.
[Sat Jun 27 15:24:36.658903 2015] [authz_core:debug] [pid 8666] mod_

Everything seems to work fine with the following message on my page
{
  "help": "\n        Get help at:\n        http://ckan-service-provider.readthedocs.org/."
}
If I run curl I got the same message as showing in the documentation
root@debian:/var/log/apache2# curl 0.0.0.0:8800
{
  "help": "\n        Get help at:\n        http://ckan-service-provider.readthedocs.org/."
}root@debian:/var/log/apache2# 

The issue is it when I add this plugin in the file /etc/ckan/default/production.ini
               
ckan.plugins = stats text_view image_view recline_view datastore datapusher
I can start apache2 , nginx
then I see a message on my log file when trying to access to my url http://127.0.0.1
Got : Internal Server Error
log : /var/log/apache2/ckan_default.error.log

[Sat Jun 27 15:31:03.981366 2015] [authz_core:debug] [pid 9068] mod_authz_core.c(835): [client 127.0.0.1:58876] AH01628: authorization result: granted (no directives)
[Sat Jun 27 15:31:03.981790 2015] [wsgi:info] [pid 9064] [remote 127.0.0.1:64418] mod_wsgi (pid=9064, process='ckan_default', application='ckan.home.com|'): Loading WSGI script '/etc/ckan/default/apache.wsgi'.
[Sat Jun 27 15:31:04.031167 2015] [wsgi:error] [pid 9064] [remote 127.0.0.1:64418] mod_wsgi (pid=9064): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Sat Jun 27 15:31:04.031313 2015] [wsgi:error] [pid 9064] [remote 127.0.0.1:64418] mod_wsgi (pid=9064): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Sat Jun 27 15:31:04.031370 2015] [wsgi:error] [pid 9064] [remote 127.0.0.1:64418] Traceback (most recent call last):
[Sat Jun 27 15:31:04.031443 2015] [wsgi:error] [pid 9064] [remote 127.0.0.1:64418]   File "/etc/ckan/default/apache.wsgi", line 10, in <module>
[Sat Jun 27 15:31:04.031505 2015] [wsgi:error] [pid 9064] [remote 127.0.0.1:644

it seems that when I add this plugin , the script /etc/ckan/default/apache.wsgi cannot load Pyhton module.
Could you tell me which version are you using ?
and on which kind of OS Linux ?

Thanks 
Khanh

**Comment by florianm** [comment]
That last trace is hacked off, there are some lines missing. Could you post
the full one up until the line that failed? These logs are tricky to read.

I'm using ubuntu, see above.

**Comment by khanh78** [comment]
Florian

Hope that you can get it now :)

![ckan-datapushererror](https://cloud.githubusercontent.com/assets/13070189/8392297/308e413e-1ce6-11e5-8087-11ee6df08dda.jpg)

**Comment by khanh78** [comment]
![ckan-datapushererror-2](https://cloud.githubusercontent.com/assets/13070189/8392304/7313f710-1ce6-11e5-965c-cdf204f0816f.jpg)

**Comment by florianm** [comment]
Thanks, that's better!
 
First, a generic Python error: "Attribute error: 'module' object has no attribute XXX" means that a Python package (installed with pip install package_name) can't find some function. This happens when your installed package version differs from the version that the software (here: datapusher) expects, or the python package wants to use a (missing) system package.

The third last line of your error log indicates that pyopenssl.py fails in line 70. Look at the code (vim /usr/lib/ckan..../contrib/pyopenssl.py) and see what it does there. From the path you see it's the python package "requests" that causes the problem.

If you google "debian 8 pyopenssl module has no attribute" you'll find a Debian bug regarding this error, and suggestions to install various system packages like python-openssl (try these first), and to upgrade the python package "requests", which I have suggested in #2470 (you could comment on that explaining why you need a newer requests version).

If all fails, create a Ubuntu 14.04 VM and do a source install (feel free to follow my guide where the docs are sketchy), at least that one works.

**Comment by khanh78** [comment]
Thanks a lot Florian
I'll try and make update

**Comment by khanh78** [comment]
Hello Forian

Thanks for your help.
I just have remove python-openssl and update request to 2.6

apt-get --purge remove python-openssl
  pip install requests==2.6.0

I can now add plugin : datapusher in the file production.ini
It work :)

**Comment by florianm** [comment]
Great to hear! You did it!
