### ISSUE TITLE
CKAN.InconsistentKraken

### ISSUE THREAD

**Issue by 0111narwhalz** [ckan/ckan#2509]
The CKAN client throws this error upon use of a .ckan file. If I try to load from a .ckan, it will throw the error. After this, any interaction with the repository results in a popup dialog with this error. It would appear to stem from a discrepancy between the repository and the .ckan regarding version numbers. Using version 1.8.4.

**Comment by ClaireBozic** [comment]
Thank you narwhale for sending the message about the kraken.
