### ISSUE TITLE
ckanext-dataproxy  DataProxyPlugin' object has no attribute 'before_create'

### ISSUE THREAD

**Issue by khanh78** [ckan/ckan#2511]
Hello,
I'm trying to configure  ckanext-dataproxy and got an error while creating a dataset with UPLOAD

![dataproxy-error-1](https://cloud.githubusercontent.com/assets/13070189/8429618/cfcb1340-1f29-11e5-9fc7-e6509f3a4358.JPG)

**Comment by khanh78** [comment]
![dataproxy-error-2](https://cloud.githubusercontent.com/assets/13070189/8429626/dae75c8e-1f29-11e5-87c2-41586efa653c.JPG)

**Comment by khanh78** [comment]
![dataproxy-error-3](https://cloud.githubusercontent.com/assets/13070189/8429631/e140956e-1f29-11e5-85b3-f25ec6560b81.JPG)

**Comment by khanh78** [comment]
![dataproxy-error-4](https://cloud.githubusercontent.com/assets/13070189/8429632/e6a6ba06-1f29-11e5-8be9-8a7c4943d585.JPG)

**Comment by joetsoi** [comment]
@khanh78 you should probably open the issues at ckanext-dataproxy insteaad of here.
