### ISSUE TITLE
remove non-release-branch docs from rtd

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2516]
If nothing comes of  https://github.com/rtfd/readthedocs.org/issues/1325 I can think of a dirty way to remove the docs from these branches: create a branch that removes the docs dir and force all the old built branches to that commit on our repo then rebuild each on rtd so that they are returning 404 instead of old docs

**Comment by wardi** [comment]
This does work, e.g. http://docs.ckan.org/en/2516-purge-the-docs/ is being redirected to the latest home page. http://docs.ckan.org/en/2516-purge-the-docs/api.html is being redirected to the new api reference. I can add the rest of the redirects on the https://readthedocs.org/dashboard/ckan/redirects/ page.

I've tested forcing an old built branch to 2516-purge-the-docs and built it on rtd to confirm that the pages are removed and the redirects take effect.

It's a bit of work to find all the branches and redirects we need.. any requests?

**Comment by joetsoi** [comment]
#847, #1485 and #1377
