### ISSUE TITLE
Datastore: failing to insert big data

### ISSUE THREAD

**Issue by mvi-eea-sk** [ckan/ckan#2525]
This problem involves two API functions:
- datastore_create
- datastore_upsert (with method parameter = 'insert')

Both call the same function: https://github.com/ckan/ckan/blob/ckan-2.3/ckanext/datastore/db.py#L630-L653

When inserting too many records (tested on 1 million), it takes all records and creates one big insert sql statement, which takes too long and is interrupted because the timeout is set to 60 sec.

The timeout is taken from context 'query_timeout' (i guess this is set to correspond postgres 'statement_timeout') and default value of this timeout is https://github.com/ckan/ckan/blob/ckan-2.3/ckanext/datastore/db.py#L40

Solution?
1. The postgres statement_timeout can be set in its configuration file, but it affects all sessions. So no, we can't use this.
2. increasing the _TIMEOUT is not option either, we don't want to allow simple operations (like inserting one row) to take several minutes
3. define new variable (maybe from CKAN config) just for the insert - not exactly desirable, how big it should be? 5, 10, 15 minutes?
4. insert each record/row separately - easy to implement
5. insert records in smaller chunks - should be little bit quicker, too big size of chunk can lead to the same problem

**Comment by joetsoi** [comment]
the datapusher already does 5. https://github.com/ckan/datapusher/blob/master/datapusher/jobs.py#L383-L387 it'd be nice if that was configurable.

**Comment by wardi** [comment]
@mvi-eea-sk since we don't have a streaming api yet, I think the fix is to add a hard limit on the number of records that datastore_create and datastore_upsert will accept.

Users will need to batch large datastore loads themselves, or use means other than the upsert API if the data is truly large, such as using COPY or pg_bulkload directly into the DB. @jqnatividad mentioned a project for this I can't remember the name of.

**Comment by maxious** [comment]
pgloader http://pgloader.io/
Very keen to see a way to use pgloader with datapusher although https://github.com/ckan/ideas-and-roadmap/issues/150 goes into some further workflows that could enable after the data is loaded.

**Comment by mvi-eea-sk** [comment]
@wardi and what about the inconsistency?
* I do datastore_create with 1M records - TIMEOUT ERROR
* I do datastore_create without records and after it datastore_upsert, method parameter = 'insert' with 1M records - TIMEOUT ERROR
* I do datastore_create without records and after it datastore_upsert, method parameter = 'upsert' with 1M records - runs really long but is OK

**Comment by mattfullerton** [comment]
Do you have datastore_create working with *any* number of records?

**Comment by mvi-eea-sk** [comment]
@mattfullerton yes, because with upsert method, it does it per row
see: https://github.com/ckan/ckan/blob/ckan-2.3/ckanext/datastore/db.py#L660-L667

insert in one big sql: https://github.com/ckan/ckan/blob/ckan-2.3/ckanext/datastore/db.py#L630-L650

**Comment by mattfullerton** [comment]
OK, sorry, I was getting mixed up with another problem where creating the resource at the same time as creating the datastore table doesn't work (for me).

**Comment by wardi** [comment]
closing in favour of work being done on #3556
