### ISSUE TITLE
Bulk operation on organization datasets don't triger after_update

### ISSUE THREAD

**Issue by mvi-eea-sk** [ckan/ckan#2527]
When editing organization, there is tab "Dataset": /organization/bulk_process/{organization_name}
There you can make operation on several organization datasets at once:
- Make public
- Make private
- Delete

Here are the action called: https://github.com/ckan/ckan/blob/ckan-2.3/ckan/logic/action/update.py#L1273-L1310

The problem these operation make changes directly in DB, so extensions implementing IPackageController after_update function (http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IPackageController.after_update) isn't called at all.

**Comment by wardi** [comment]
@mvi-eea-sk the bulk operations were designed to be limited to setting a single flag and need to be fast even if there are hundreds of records being operated on.

If we call every plugin (IPackageController, IDatasetForm, ...) with the serialized version of every dataset and resource and process each one as a separate update it would take much, much longer.

What work are you doing in after_update that needs to watch for the private flag change? Maybe there's a better way to handle your specific needs.

**Comment by mvi-eea-sk** [comment]
@wardi We have plugin that pushes only public datasets to another CKAN. So if the dataset is changed from private to public (or other change on public dataset is done), it is automatically pushed to the other CKAN.

**Comment by wardi** [comment]
@mvi-eea-sk good to know. I do the same thing but with a batch job that follows the activity feed. Would that work in your case or does publishing not record an activity?

How about a new method on the same plugin interface that will be called when bulk updates happen?

**Comment by wardi** [comment]
It's now possible to override the bulk actions so you can trigger your publishing events, see #3494
