### ISSUE TITLE
paster views create fails for non-default dataset types

### ISSUE THREAD

**Issue by deniszgonjanin** [ckan/ckan#2532]
`paster views create` does a `package_search` with a [hardcoded `dataset_type:dataset`](https://github.com/ckan/ckan/blob/master/ckan/lib/cli.py#L2421).

If datasets are of a different type, the command will fail. While it's possible to add extra search parameters to the paster command, the documentation doesn't mention that a default dataset type will be inserted, and that the user must explicitly override it if they have datasets of a different type. So one must dig through the code to figure out why the command is silently failing.

Removing the mentioned block that inserts a default type seems to work perfectly fine. Can that block be safely removed, or is there a reason why a dataset type must be specified?

**Comment by deniszgonjanin** [comment]
Even with specifying a dataset type in extra search parameters, `dataset_type:dataset` will always be appended to the query. So this is definitely broken for all datasets not of type 'dataset'

**Comment by amercader** [comment]
@deniszgonjanin You are correct, fix is in #2535 (basically remove the filter). If we can get it reviewed and merged it'll go into 2.4 and backported to 2.3.x

**Comment by deniszgonjanin** [comment]
@amercader that's awesome, thanks for the quick fix!
