### ISSUE TITLE
Search buttons need accessible labels

### ISSUE THREAD

**Issue by smth** [ckan/ckan#2550]
- Search button in header has no text label
- Search button in the larger search bar has a label, but it is hidden with `display:none` (inaccessible by screen readers)

**Comment by davidread** [comment]
Are you working on a pull request for this?

**Comment by mintcanary** [comment]
Not currently. It's something I see myself doing when I get a moment, but that might not be any time soon.

**Comment by k-nut** [comment]
This might be helpful here: http://wave.webaim.org/report#/http://beta.ckan.org/

**Comment by k-nut** [comment]
Also this: https://egghead.io/lessons/css-accessible-icon-buttons

**Comment by gleb-rudenko** [comment]
@davidread, is it still topical?

**Comment by davidread** [comment]
@gleb-rudenko This seems a valuable enough job to do, if you're offering?

**Comment by Engerrs** [comment]
I will start working on creating PR for this one.

**Comment by amercader** [comment]
Done in #3581
