### ISSUE TITLE
Include the main.debug.css

### ISSUE THREAD

**Issue by LaurentGoderre** [ckan/ckan#2556]
Hi, I'm new to CKAN in my organization and turned debug to true for development and encountered the `AttributeError: 'module' object has no attribute 'css/main.debug.css'` error. It took me a while to figure out that I had to compile the less to get it.

Wouldn't it be easier to include this file so that debug mode automatically works without needing to change anything else?

**Comment by wardi** [comment]
I don't see any difference between the main.css and the main.debug.css that I generate from the less files. Should there be a difference? If not, why do we have two versions at all?

**Comment by davidread** [comment]
if it is the same then let's kill it

**Comment by wardi** [comment]
@Laurent we agreed at the dev meeting that we're better off without the .debug versions. Do you have time to contribute a PR that removes this?

**Comment by LaurentGoderre** [comment]
Sure!
