### ISSUE TITLE
Duplicate Dataset URL after search-index rebuild

### ISSUE THREAD

**Issue by gallexme** [ckan/ckan#2559]
Hello,
On our Ckan (2.2) production website we had a problem with the search-index rebuild,
before the search index rebuild, the URLs of the dataset download button were in this pattern:
**http://website/dataset/LONGID/resource/LONGID/download/file.json**
However, after re-indexing, they were like this:
**http://website/dataset/http://website/dataset/LONGID/resource/LONGID/download/file.json**
Or:
**http://website/dataset/://website/dataset/LONGID/resource/LONGID/download/file.json**
 
To temporally fix it I changed this in **‘ckan\logic\action\get.py’** in the function
#### def package_show(context, data_dict):
 
before
```python
return package_dict
```
I added this:
```python
if 'resources' in package_dict:
        for key, value in enumerate(package_dict["resources"]):
            package_dict["resources"][key]["url"] = value["url"].replace("http://{url}/dataset/".format(url=config.get('ckan.site_url')),"",).replace("://{url}/dataset/".format(url=config.get('ckan.site_url')),"",).replace("http","",)
 
```
which definitly fixed it but i know its not a good way to fix it so it would be great if someone from ckan could fix it the right way

king regards gallexme

**Comment by davidread** [comment]
Just a thought, what's your ckan.site_url set to?

**Comment by gallexme** [comment]
its set to
sub.example.com

**Comment by davidread** [comment]
Is the resource.url mangled when stored in the database level? You can use psql to look.

Are you using a custom package schema that might be doing this? View the dataset in the v1 (REST) API to see what it is like pre-schema-validation

**Comment by amercader** [comment]
Does the ckan.site_url setting include the `http://` bit? ie `http://sub.example.com`

**Comment by gallexme** [comment]
@amercader 
no its just sub.example.com
@davidread 
could you provide a better explanation how i should test it(best step by step), as im not working that long with ckan yet, i just got told to do so

**Comment by amercader** [comment]
@gallexme `ckan.site_url` must include the http:// bit. Please update your configuration and reindex your datasets to see if that solves the issue

**Comment by gallexme** [comment]
@amercader 
Thank you this fixed it.

**Comment by amercader** [comment]
Good to hear it @gallexme
