### ISSUE TITLE
free-form extras clobber converted extras on update/create

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2565]
This results in converted extra fields inexplicably going missing, starting with fields with names that sort towards the beginning when multiple convert_to/from_extras fields are defined.

**Comment by amercader** [comment]
Is this on master? This sounds like the issue described in #1894

Also does this help? https://github.com/ckan/ckan/pull/2151

**Comment by wardi** [comment]
Yes, #2151 looks like it might fix my issue too. I'm seeing it in ckan 2.2 and 2.3 but it must also apply to master if this hasn't been merged yet. I'll try this out.

**Comment by wardi** [comment]
No, #2151 doesn't solve my issue. I'll work on a fix and a test.

**Comment by wardi** [comment]
Sorry. Problem isn't in ckan it's in the extension I'm working on
