### ISSUE TITLE
Exporting information from stats extension

### ISSUE THREAD

**Issue by KidDavidacus** [ckan/ckan#2566]
So I just installed the stats extension for my ckan instance and it works perfectly fine. I was wondering if there was a way for my export the information from the stats page into a JSON/CSV file?

For example, exporting the data from Largest Groups?

Thanks!

**Comment by davidread** [comment]
I'm afraid the stats extension is old and doesn't provide an API or anything. However you could write some code to call the stats library in the same way as StatsController does.

Closing this as it is not an issue it is a question - these should be sent to the ckan-dev list.
