### ISSUE TITLE
how to disable dataproxy, use ckanext-datapreview instead

### ISSUE THREAD

**Issue by johnxue2013** [ckan/ckan#2568]
when i view .xls file on page, i got an error : Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)，i google this error,konwing that i should config dataproxy, but i don't want to use dataproxy, i use ckanext-datapreview instead. i have install ckanext-datapreview and it's requements. however when i view the resource agin。i get an error above. could someone tell me what should i do?  thanks!

**Comment by rossjones** [comment]
If you're using the datagovuk/ckanext-datapreview you might want to check the notes in the README at https://github.com/datagovuk/ckanext-datapreview#problems and possibly file a bug over there?

You may also be better using the new CKAN resource previews - http://docs.ckan.org/en/latest/maintaining/data-viewer.html

**Comment by johnxue2013** [comment]
thank u, i had read two of them already, still confuesd,the problem is when i view the .xls file, an erroe occurred:Could not load view: DataProxy returned an error (Data transformation failed. error: An error occured while connecting to the server: Unable to connect to server at URL: http://127.0.0.1:5000/dataset/fe4f3943-fd32-4565-ab1f-38db26fd2434/resource/8e793d52-3929-4487-bed2-b2fbd30e3144/download/2015.xls).

**Comment by rossjones** [comment]
@johnxue2013 This is because the default dataproxy is hosted on Google Appengine, and if your site isn't web-accessible it isn't able to retrieve the resource file.  When the URL for the resource is 127.0.0.1, google appengine will likely try and retrieve the file from itself (as 127.0.0.1 is localhost).  

For testing purposes you may get further by using something like [ngrok](https://ngrok.com) which will give you a hostname that makes your local site accessible to the internet (you'd need to remember to use the name that ngrok gives you in the config ckan.site_url.

**Comment by johnxue2013** [comment]
you konw, in china, i can't get acess to google, google is blocked since many years ago, that's the reason use  ckanext-datapreview instead, even there still not work, i still want to thank you any way!

**Comment by rossjones** [comment]
Unfortunately I don't know how to work around the firewall issue.  The only alternatives are:

1. Try filing a bug at https://github.com/datagovuk/ckanext-datapreview (although this is pretty specific to data.gov.uk at the moment).
2. Follow http://docs.ckan.org/en/latest/maintaining/data-viewer.html to use the in-built previews which I don't believe rely on the Google service, especially if you are also using the datastore.

I think option 2 is probably the best to try.

**Comment by KrzysztofMadejski** [comment]
Is there a configuration option to completely disable jsondataproxy? So when the view is created, but there is not data in Datastore the ckan won't show broken (meaning it won't serve data) DataExplorer to users?

**Comment by amercader** [comment]
@KrzysztofMadejski not AFAIK. I guess you can add a config option and check it on the `can_view` method of the `ReclineView` plugin to return False if data is not on the DataStore.

DataProxy should be phased out really, but there are a ton of sites using it.

**Comment by dkelsey** [comment]
I'm looking into somehow making the data proxy url a configuration setting 
https://github.com/ckan/ideas-and-roadmap/issues/217
