### ISSUE TITLE
Install ckan on a mac

### ISSUE THREAD

**Issue by zachmayer** [ckan/ckan#2569]
You can also:
```{bash}
brew tap homebrew/games & brew install ckan
```

This is a lot easier than the guide in the wiki, and seems to work just fine!

**Comment by mattwagstaff** [comment]
Nice work. I ended up using a VirtualBox Ubuntu install to get mine working. I'll give this a go soon!

**Comment by zachmayer** [comment]
Hahha, yup.  This the wrong ckan page.  Sorry!

(Your ckan looks interesting too!)
