### ISSUE TITLE
use ckan In distributed environment

### ISSUE THREAD

**Issue by johnxue2013** [ckan/ckan#2573]

**Comment by rossjones** [comment]
I think possibly that this type of issue might best be recorded as an idea at https://github.com/ckan/ideas-and-roadmap/issues as there's no built in clustering for CKAN.  Alternatively you may find more conversation at the [mailing list](https://groups.google.com/forum/#!forum/ckan-global-user-group)

**Comment by johnxue2013** [comment]
um...,thanks!
