### ISSUE TITLE
markdown_extract only expects strings

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#2578]
When using [ckanext-fluent](https://github.com/open-data/ckanext-fluent) to define a multilingual markdown field, the output currently fails with the following error:

    Error - <type 'exceptions.AttributeError'>: 'dict' object has no attribute 'strip'

I could trace this error back to the [following line of code](https://github.com/ckan/ckan/blob/13b8befcd8a8eed566509179a09f3d31d1a2b60d/ckan/lib/helpers.py#L810):

    if (text is None) or (text.strip() == ''):

PR follows to make sure the site doesn't break because of this.

**Comment by rossjones** [comment]
I haven't checked that overriding helpers is possible, but perhaps it might be better to override ```markdown_extract``` in ckanext-fluent instead?

**Comment by metaodi** [comment]
@rossjones well monkey patching could work yes. I'll check if this is possible. But maybe it would be good to have a "proper" way of doing this.

**Comment by rossjones** [comment]
I don't think you need to monkey-patch, you could use ITemplateHelpers - https://github.com/ckan/ckan/blob/master/ckan/plugins/interfaces.py#L888-L910  but it appears that it does stop you overwriting  helpers at https://github.com/ckan/ckan/blob/9bf61b4b2707ff943d38a4f6035114272638a42b/ckan/config/environment.py#L70 :(

**Comment by wardi** [comment]
You can use an IPackageController before_show method to replace the any core fluent fields with a single-language version. I'm planning to add one of these to ckanext-fluent when I can make it work well enough to handle fluent with core dataset fields like title and notes.

@metaodi I've tried to pitch the idea of core ckan adopting the ckanext-fluent behaviour for dicts in place of text but haven't been able to sell it to the others yet :-) Maybe move this issue to ckanext-fluent for now.

**Comment by metaodi** [comment]
@wardi Okay I'll look into that to replace the dict with a single language version. For now, I'll try to implement that in my own extension, if I can make it work, I'll try to integrate that in fluent as well.

**Comment by wardi** [comment]
closing in favour of #2678
