### ISSUE TITLE
Extend CKAN

### ISSUE THREAD

**Issue by wide-awake** [ckan/ckan#2586]
Hey community, 
I have architecture question. Need to extend basic CKAN functionality. It will be better to extend CKAN code or integrate it with Django (for example) true the API and write all new features in Django apps? 

The idea is to test API hard so it will be easy to update ckan in feature. 

I need some e-commerce,  wider account functionality and much more.

Thank you for your time.

**Comment by amercader** [comment]
I would suggest building your custom features in a CKAN extension. These docs should get you started: http://docs.ckan.org/en/latest/extensions/index.html

If you need more help please contact the mailing list:

https://lists.okfn.org/mailman/listinfo/ckan-dev
