### ISSUE TITLE
Create/Edit resource - Upload dialog opens when I click Link

### ISSUE THREAD

**Issue by nbtetreault** [ckan/ckan#2590]
![sans titre](https://cloud.githubusercontent.com/assets/2699085/9410488/91419192-47ee-11e5-9137-814e39740016.jpg)

When we click on the Upload button an Upload dialog open. The clickable area is bigger than the button itself as illustrated in red.

I got the issue on **Chrome only**. IE and FF are fine. I tested it on http://demo.ckan.org/ (Using abe2de0 from branch release-v2.4.0)

**Comment by amercader** [comment]
We can't reproduce this on the latest Chrome. Please reopen if still an issue or you have more details.
