### ISSUE TITLE
Fileupload removes underscores from filenames

### ISSUE THREAD

**Issue by mbellotti** [ckan/ckan#2597]
There doesn't seem to be any reason to forbid underscores in filenames, especially since munge allows them elsewhere. Looks like someone just forgot to add an underscore to the replace function. Have a PR all ready to go with fix and updated test, just need to know what branch to submit it to ;)

**Comment by gjlawran** [comment]
Has the PR been submitted? Would be great to resolve.

**Comment by mbellotti** [comment]
Yup... coming up on its one year birthday very soon: https://github.com/ckan/ckan/pull/2600
