### ISSUE TITLE
Confusing folder structure for assets (CSS, Javascript and Images)

### ISSUE THREAD

**Issue by LaurentGoderre** [ckan/ckan#2601]
There seems to be a great deal of duplication in the assets in these two folders. I was wondering why these two separate folder structure exist and if they could be combined?

https://github.com/ckan/ckan/tree/master/ckan/public
https://github.com/ckan/ckan/tree/master/ckan/public/base

**Comment by amercader** [comment]
The ones at the base of /public are assets for the old pre-2.x theme, kept for compatibility but I'm pretty sure they can go.

**Comment by LaurentGoderre** [comment]
Interesting!

**Comment by wardi** [comment]
Delete them!

**Comment by LaurentGoderre** [comment]
Music to my ears!
