### ISSUE TITLE
URL to resource incorporates full path when using IE (11)

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2603]
(On both Ckan 2.2 and 2.3) I have encountered a situation whereby a user using IE uploads a resource file.  It uploads correctly, however when someone subsequently goes to download that resource, the download link is full of rubbish as instead of the normal behaviour of the file being at URL ckan install url/dataset/xxxx/resource/yyyy/download/filename.ext 
e.g. normal = http://datastore.landcareresearch.co.nz/dataset/6455858b-b7ba-47d9-b867-d0ae7d400dcb/resource/89e759ff-ca17-4666-b621-43b45ef62e02/download/hopkinshuxleyseedlingdata.tsv

It was (I have fixed it since) getting stored as http://datastore.landcareresearch.co.nz/dataset/6455858b-b7ba-47d9-b867-d0ae7d400dcb/resource/89e759ff-ca17-4666-b621-43b45ef62e02/download/richardhadleeuser1richardsonsdocumentsworktraitsbarkthicknessnzbarkmsamericanjournalofbotanys

Due to the lengthy file structure the user had, the actual filename and extension where truncated, so there is no indication of the filetype if you download such a resource.  If the file path is not so long/deep, then the filename and extension do get stored, but it is stored along with the full filepath incorporated into the actual filename.

This only seems to occur in Internet explorer (tested using v11.0.21).  Using both Chrome and Firefox the file uploaded as expected (did not incorporate the path into the filename).

**Comment by wardi** [comment]
@Aaron-M was this not fixed by #2257

**Comment by Aaron-M** [comment]
@wardi What versions was issue #2257 patched in?  I first noticed in our production instance running CKAN 2.2.1 and replicated in our test instance running CKAN 2.3.  I just tested it on the demo.ckan.org site which is running CKAN 2.4.0 and it worked fine using IE.  Maybe we need to patch or upgrade our instances and it will fix - thanks!

**Comment by euniceong** [comment]
Hi I tried to upload on demo.ckan.org and it stills include the full path when using IE 11 (v 11.0.96) - The extension is retained but it still stores the first part of the part e.g. (c://....).
