### ISSUE TITLE
File Upload UX issue

### ISSUE THREAD

**Issue by deniszgonjanin** [ckan/ckan#2604]
Not related to #2590. We are upgrading a client from 2.2 to 2.3 and they raised an issue about how the File Upload/Link has changed in 2.3:
<img width="954" alt="screen shot 2015-08-28 at 4 29 55 pm" src="https://cloud.githubusercontent.com/assets/209316/9556353/1641d718-4da2-11e5-8741-e1081d9cd2a3.png">
<img width="965" alt="screen shot 2015-08-28 at 4 29 01 pm" src="https://cloud.githubusercontent.com/assets/209316/9556355/18b91402-4da2-11e5-8bb5-a700501abc9b.png">

The reasoning is that the 2.2 interface is more user friendly, especially for non-technical users. The 2.3 interface turns the file label into 'URL', and then also sets that URL to the file name. What could confuse editors is that the file didn't turn into a URL, and even once it does the filename that the input field gets populated with is not the URL that the file will be available on. It also replaces the large and unambiguous Remove button with an 'X' at the end of the field.

In CKAN 2.2, this interface is more intuitive.

I know these aren't the kind of issues CKAN usually deals with, but I thought it'd be worth raising. I'd love to get a couple of opinions on this issue, and depending on the discussion I'm happy to submit a patch to revert the interface back to 2.2.

**Comment by Aaron-M** [comment]
I noticed this too, and tend to agree with Denis that the way 2.2 handled removing/replacing/updating a resource file is clearer/simpler/nicer...

**Comment by davidread** [comment]
Suggested compromise - we keep the filename displayed, but instead of the [x] button we bring back the big 'Remove' button?

Could someone to contribute something like this?

**Comment by davidread** [comment]
Great, just need a volunteer now... ;-)

**Comment by deniszgonjanin** [comment]
I will talk with the client who raised this, and if they are happy with the proposed solution I am happy to cook something up.
