### ISSUE TITLE
organization_link is missing from __allowed_functions__?

### ISSUE THREAD

**Issue by ckylape** [ckan/ckan#2608]
Is `organization_link` deprecated? It seems to be missing from [helpers.py](https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L2051-L2169)? 

```
Template helper function `organization_link` is not available because it has been deprecated.
```

Also [organization_link](https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L1170-L1172) seems like it should be returning the organization title instead of the name similar to `tag_link` and `group_link`.

``` python
def organization_link(organization):
    url = url_for(controller='organization', action='read', id=organization['name'])
    # return link_to(organization['name'], url)
    return link_to(organization['title'], url)
```

**Comment by gleb-rudenko** [comment]
@wardi, is is still topical?

**Comment by wardi** [comment]
looks like it's there to me. https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L1381 closing
