### ISSUE TITLE
Delete related items code in favour of ckanext-showcase

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2609]
The related items code is no longer necessary now that the ckanext-showcase extension exists.  We should delete the related-items code.

There is a migration from related-items to using showcase (in ckanext-showcase) but we probably wouldn't want to deleted related-items before people have a chance to perform the migration.

Perhaps the best approach would be to mark it as deprecated in the next release, and apply any PRs afterwards so that people have a chance to migrate.

**Comment by wardi** [comment]
implemented in #2610

**Comment by davidread** [comment]
I've let people know on ckan-dev that related-items is deprecated now and will be removed in the next release. Had one response - positive.

The plan is:
*  CKAN 2.5 release the front-end is removed #2618 
*  CKAN 2.6 release we remove the rest #2610

**Comment by rossjones** [comment]
The associated PRs are all merged now, closing this ticket.
