### ISSUE TITLE
group_followee_count returns incorrect amount

### ISSUE THREAD

**Issue by trickvi** [ckan/ckan#2628]
The function `logic.action.get.group_followee_count` returns the amount of groups **and** organization the user follows. This is incorrect because according to the documentation (and function name) it should **only** return organisations.

This is because organisations are also groups and the function `logic.action.get._followee_count` doesn't filter the groups like `logic.action.get.group_followee_list` and `logic.action.get.organization_followee_list` do.

**Comment by amercader** [comment]
Do you want to submit a quick PR @trickvi ? Seems pretty easy to fix

**Comment by wildcatzita** [comment]
I'll fix

**Comment by wildcatzita** [comment]
Made [PR](https://github.com/ckan/ckan/pull/3458)

**Comment by rossjones** [comment]
The associated PR looks okay, but needs tests.
