### ISSUE TITLE
Unicode decode error when creating an extension

### ISSUE THREAD

**Issue by trickvi** [ckan/ckan#2636]
I have a weird name. It has a weird letter: *ö* in it. Trying to create an extension:

    paster --plugin=ckan create -t ckanext ckanext-example

and providing my real name when asked for it ends up with a ``UnicodeDecodeError``:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)

This could be solved with me changing my name. But that's not going to happen for everyone with weird characters in their names.

**Comment by rossjones** [comment]
Is there any chance you could try this PR out? 

https://github.com/ckan/ckan/pull/2639

**Comment by trickvi** [comment]
Works for me. Seems to have solved the issue so now it seems you only need to verify that you're only setting the paster encoding instead of a system global (my system is set to utf-8 so it seems like you're only setting paster's encoding but I find it weird that it doesn't just inherit from the system).

**Comment by rossjones** [comment]
I find it weird too, and not overly happy with my fix, but I don't want to dive into the depths of paster.

**Comment by rossjones** [comment]
Going to investigate asking for the locale so we're not making assumptions on the user's system setup.

**Comment by florianm** [comment]
apologies for butting in, what about mixed encodings? If users copy-paste via MS Word, Unicode can get mixed up with cp1512 in the same string. Got some code to defuse that somewhere if that's any good.

**Comment by rossjones** [comment]
@florianm that would be great, I think the problem was that although this works (and wont' break for people that use ascii), nobody was going to find time to support other encodings when using the paster templates to create a new extension.

Also, don't apologise for butting in ;) PRs welcome if you've got one.

**Comment by wardi** [comment]
@florianm IIUC this is a very specific case of unicode in a unix user's name. Unlikely that a pasted value from Word will appear, but entirely possible that the system is not in UTF-8

In that case, though, the code will continue to crash so no worse than it was before the change.
