### ISSUE TITLE
Link to CKAN API not available for 2.4.1

### ISSUE THREAD

**Issue by brew** [ckan/ckan#2656]
The CKAN API link in the footer of the templates for the 2.4.1 release points to: http://docs.ckan.org/en/ckan-2.4.1/api/, which doesn't exist.

**Comment by joetsoi** [comment]
2.3.2 isn't built in read the docs either, I've switched up to build them both

**Comment by joetsoi** [comment]
fixed!

**Comment by brew** [comment]
:sparkles:
