### ISSUE TITLE
API calls allows modifications of internal system records

### ISSUE THREAD

**Issue by trickvi** [ckan/ckan#2658]
I have not taken a look at all of the API calls but we do not seem to restrict much when it comes to making changes on the API. For example, I can do this 

    http --json POST http://127.0.0.1:5000/api/3/action/resource_update id=78a8e205-a9be-4fcc-8f95-5f11708ae09f url=http://a.url.must/always/be/provided/even/in/resource/updates created="2015-10-18T17:18:03.488178" last_modified="2015-09-18T17:18:03.488178" Authorization:api_key 

Which will make last_modified be set in the past while created is set in the future:

![created_vs_updated](https://cloud.githubusercontent.com/assets/3489241/10190299/252189d6-675b-11e5-8416-d17bf79bbb0b.png)

I feel this gives me too much power but I may of course be wrong and there's a perfectly legitimate reason for allowing me to modify internal system records.

**Comment by davidread** [comment]
Tech team doesn't see a reason to enforce this. It's potentially useful if you harvest from elsewhere and want to set these values.

**Comment by wardi** [comment]
internal meddling is part of ckan's charm
