### ISSUE TITLE
ckan 2.4 Internal server error after add some data in group/organization/dataset

### ISSUE THREAD

**Issue by 0100110** [ckan/ckan#2667]
HI, i have receive errors when I try to add data. 

Using debug Web erro traceback:

`File '/usr/lib/ckan/default/src/ckan/ckan/controllers/group.py', line 173 in index
  results = self._action('group_list')(context, data_dict)`
`File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 429 in wrapped
  result = _action(context, data_dict, **kw)`
`File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 508 in organization_list
  return _group_or_org_list(context, data_dict, is_org=True)`
`File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 423 in _group_or_org_list
  group_list.append(logic.get_action(action)(context, data_dict))`
`File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 429 in wrapped
  result = _action(context, data_dict, **kw)`
`File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 1232 in organization_show
  return _group_or_org_show(context, data_dict, is_org=True)`
`File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 1171 in _group_or_org_show
  packages_field=packages_field)`
`
File '/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_dictize.py', line 423 in group_dictize
  group, just_the_count=True)
`
`File '/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_dictize.py', line 414 in get_packages_for_this_group
  q)
`
`File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 429 in wrapped
  result = _action(context, data_dict, **kw)`

`File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 1771 in package_search
  query.run(data_dict)
`
`File '/usr/lib/ckan/default/src/ckan/ckan/lib/search/query.py', line 364 in run
  (query, e.reason))`
`

`SearchError: SOLR returned an error running query: {'sort': 'score desc, metadata_modified desc', 'fq': [u'owner_org:"73bffc86-3b1f-46c3-85d2-0fa0084ac53e" +site_id:"default" +state:active'], 'facet.mincount': 1, 'rows': 0, 'facet': u'false', 'facet.limit': '50', 'wt': 'json', 'q': '*:*', 'fl': 'id validated_data_dict'} Error: 'Server Error'`

ckan.log:

`SolrException: HTTP code=500, reason=Server Error
2015-10-01 09:51:41,489 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2015-10-01 09:51:41,636 CRITI [ckan.lib.uploader] Please specify a ckan.storage_path in your config
                         for your uploads`
`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)`
  `File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)`
`  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()`
`  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()`
`  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()`
`  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])`
`error: [Errno 32] Broken pipe
Traceback (most recent call last):`
`  File "/usr/lib/python2.7/dist-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)`
`  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)`
`  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()`
`  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()`
`  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()`
`  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe`

**Comment by joetsoi** [comment]
hey sounds like you need to enalbe the ckan.storage_path in your config, there error is there but hidden in the nose of he ckan.log you posted

    please specify a ckan.storage_path in your config for your uploads

http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-storage-path

if you have any further problems, please move it to the ckan-dev mailing list as we try to keep github issues for code
