### ISSUE TITLE
Logging issue

### ISSUE THREAD

**Issue by Almalerik** [ckan/ckan#2687]
Hi,
i installed ckan 2.4.1 from source on debian 7.1.0 with apache.
All it's ok but there is a little problem with apache log: ckan info log got to error log file.
This is a line of my var/log/apache2/ckan_default.error.log:
`<[Thu Oct 15 10:47:48.797562 2015] [:error] [pid 14100] 2015-10-15 10:47:48,797 INFO  [ckan.lib.base]  /ckan-admin render time 0.085 seconds>`

My Virtualhost is equal to the doc ( http://docs.ckan.org/en/latest/maintaining/installing/deployment.html#create-the-apache-config-file)

Thanks
Alma

**Comment by davidread** [comment]
Are you asking why it says "[:error]"? That is normal.

If you have further questions, please use stackoverflow.
