### ISSUE TITLE
No way of limiting users creating dataset via gui

### ISSUE THREAD

**Issue by bunnis** [ckan/ckan#2693]
There should be an option to restrict users adding datasets via web UI and only by API. and vice-versa,
such as 
ckan.auth.create_dataset_by_api
ckan.auth.create_dataset_by_webui

**Comment by davidread** [comment]
Can you explain the use case for this?

**Comment by bunnis** [comment]
We use lots of custom fields for our metadata. We don't want users to be allowed to add by hand any field, they might do a typo. Instead we want users to use our API which basically filters their content and then we create a dataset using ckan API. Also this way i can control vocabs for extra fields.

**Comment by davidread** [comment]
There is plenty of scope to do custom validation in CKAN. You can easily have extras which only take values from controlled vocabularies etc.

**Comment by bunnis** [comment]
Can you tell me how do i do that?

**Comment by wardi** [comment]
Yes, if you're using validators with an IDatasetForm it applies both to the form and the API. If you want to remove the forms you can override the default routes with your own controller and override the templates that link to the edit screens.

**Comment by bunnis** [comment]
Thanks. Still on this auth question, there isn't a way of limiting all api requests to only authenticated users? Say I only want users to be able to search if they are logged in.

**Comment by wardi** [comment]
@bunnis if you override the site_read auth function you might get what you're looking for. This isn't a common way to run ckan though, so you might run into problems.

**Comment by bunnis** [comment]
you are talking about function line 13 at https://github.com/ckan/ckan/blob/91e41b2e68faa3df5296a632f4862f5a55e69e62/ckan/logic/auth/get.py

**Comment by davidread** [comment]
Please continue any discussion on the mailing list
