### ISSUE TITLE
Files with special characters on the name are not uploaded via the API

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#2695]
As reported by @danmihaila on the mailing list.

Consider this minimal script:

``` python
  # -*- coding: utf-8 -*-
  import requests
  import StringIO
  from pprint import pprint

  url = 'http://localhost:5001/api/3/action/resource_create'
  api_key = '3869cb71-96da-46f1-b5a9-767ca73af73f'
  package_id = '9c99ca2c-3cf5-497b-9c3e-54882af0d6f2'

  name = u'tèst.txt'
 #name = u'test.txt'

  content = StringIO.StringIO(u'Test content')

  r = requests.post(url,
                    data={'package_id': package_id, 'url': name, 'url_type': 'upload'},
                    headers={'X-CKAN-API-Key': api_key},
                    files=[('upload', (name, content))])

  pprint(r.json())

```

When using `tèst.txt` as name the resource gets created but the file isn't uploaded. When using `'test.txt` the file is uploaded.

In the first case [this check](https://github.com/ckan/ckan/blob/master/ckan/lib/uploader.py#L199) is failing because indeed the `upload` field is not what is supposed to be.

Going down to the API controller, on the [`_get_request_data`](https://github.com/ckan/ckan/blob/master/ckan/lib/uploader.py#L199) method it seems like the problem is coming from the Pylons `request.POST` object:
-  When using `tèst.txt`, `request.POST`is:

```
UnicodeMultiDict([('url', u't\xe8st.txt'), ('package_id', u'9c99ca2c-3cf5-497b-9c3e-54882af0d6f2'), ('url_type', u'upload'), ('upload', u'Test content')])
```
-  When using `test.txt`, `request.POST`is:

```
UnicodeMultiDict([('url', u'test.txt'), ('package_id', u'9c99ca2c-3cf5-497b-9c3e-54882af0d6f2'), ('url_type', u'upload'), ('upload', FieldStorage('upload', u'test.txt'))])
```

Uploading a file with special characters from the frontend works fine.

This do feels like a bug, but maybe not in CKAN but probably in the WebOb version that we are using (I doubt that this is requests fault)

**Comment by gleb-rudenko** [comment]
@amercader , is this still need to be investigated or work?

**Comment by amercader** [comment]
@gleb-rudenko it would be good to test if it it's still happening on the current lib versions used in master. But considering that we are moving away from Pylons I'm not sure it's worth chasing it unless it's something that can be easily fixed on the CKAN controller.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
