### ISSUE TITLE
package_autocomplete only find packages that start with the given search query

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#2697]
The [current implementation of package_autocomplete](https://github.com/ckan/ckan/blob/2f8d75c4da1ce5bf1fe9c59ab0f9aa8e3cd32270/ckan/logic/action/get.py#L1611) looks like that:

```python
like_q = u"%s%%" % q
```

So only packages that start with the given string will be returned.
I expected something like `%searchterm%'` to get better results. E.g. `format_autocomplete` uses this format as well.

Or was this intentional?

**Comment by metaodi** [comment]
PR for this issue: #2698

**Comment by rossjones** [comment]
I merged this and then reverted it when wardi pointed out that it doesn't have the right type of index.  As punishment I'll make it work with Solr tomorrow and send a PR.  Sorry again.

**Comment by wardi** [comment]
I don't think this action is used anywhere in core CKAN at the moment, maybe we should consider deprecating it instead of updating it?

@metaodi if you use this action and want it to behave differently why not add it to your own extension?

**Comment by metaodi** [comment]
@wardi Ah sure I can put it in my extension, I just thought this was a bug. I'm fine with deprecating it.
