### ISSUE TITLE
Aesthetic Change

### ISSUE THREAD

**Issue by bunnis** [ckan/ckan#2699]
When visiting ckan demo or others, on the Language bar to change language on the bottom right, the languages are given in a random order rather then in an alphabetic order

**Comment by florianm** [comment]
IIRC the languages are offered as configured in the .ini file. This way, the catalogue maintainer can bump most used languages to the top of the select box.

**Comment by bunnis** [comment]
I suggest you could have an option for selecting "top languages" and the other ones should be sorted by alphabetical order. Looks clean and intuitive and easier for the user to select their language

**Comment by amercader** [comment]
This option exists, check `ckan.locale_order` (plus `ckan.locale_offered` and `ckan.filtered_out`)

http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-locale-order

I'm not sure if the alphabetical order is a good default, as some languages name don't use the latin alphabet (中文 (中国), монгол (Монгол улс), ...).

Closing, feel free to reopen if you have further input on this issue.
