### ISSUE TITLE
Can only follow groups, users and datasets.

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2704]
In an extension, we have an object that we'd like to be able to have users follow.  Unfortunately the 'following' code ensures that only the objects above can be followed.  

We'd like to either:
- Implement the __followee_list and _am_following__, etc in our extension,and then CKAN can use those, or 
- Have CKAN not put a constraint on what can be followed.

We'd like not to have to re-implement all the same code in the extension.

**Comment by davidread** [comment]
Sounds good

**Comment by davidread** [comment]
Sounds good

**Comment by gleb-rudenko** [comment]
Is this issue actual?

**Comment by davidread** [comment]
This issue was simply created to get agreement to add this feature. However the feature didn't get progressed, so I'll simply close it.
