### ISSUE TITLE
Number of datasets on the front page incorrectly includes harvest sources

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2715]
> The stats on the front page of CKAN include the harvest sources as datasets, however when I click on datasets the number then exclused the sources. It should also exclude the sources on the start page.

(Issue moved here from https://github.com/ckan/ckanext-harvest/issues/161 )

**Comment by davidread** [comment]
@neothemachine thanks for this. Can you clarify what you mean by:

> It should also exclude the sources on the start page.

**Comment by neothemachine** [comment]
Sure, have a look:
Front page: http://ckan-demo.melodiesproject.eu/
Search page: http://ckan-demo.melodiesproject.eu/dataset?q=

**Comment by davidread** [comment]
Ah got you now, "front page" = "start page" so the second sentence is just reinforcing to the point in the first sentence.

**Comment by amercader** [comment]
Fixed in ckan/ckanext-harvest#221
