### ISSUE TITLE
Auth function resource_delete calls CKAN's own package_delete

### ISSUE THREAD

**Issue by pkoskinen** [ckan/ckan#2719]
Auth function resource_delete calls package_delete in the same file  (authorized = package_delete(context, pkg_dict).get('success')) instead of using the check_access. Thus it doesn't respect modifications made in extensions. As a result any modifications made to the package_delete auth function require overwriting the resource_delete auth function as well.

**Comment by davidread** [comment]
Agreed, it should call package_delete auth function using check_access. Could you write a PR for it?

**Comment by gleb-rudenko** [comment]
@amercader, I'll work on it

**Comment by gleb-rudenko** [comment]
@amercader , i guess it can be closed this was done already.

from **logic/auth/delete.py**
`authorized = authz.is_authorized('package_delete', context, pkg_dict).get('success')` - line 37

**Comment by TkTech** [comment]
Fixed in https://github.com/ckan/ckan/commit/2cc254d3bfe704b5d797acc2e1388d56b9a6c171
