### ISSUE TITLE
DataPusher does not lock table while uploading data

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#2721]
Create a dataset with a CSV file with 3 rows.
Go to the resource page > Manage > DataStore, Click on "Upload to DataStore" many successively

Result:

![pgb4oo5](https://cloud.githubusercontent.com/assets/200230/10910630/62eca78a-8238-11e5-95c2-fa79affda795.png)

**Comment by davidread** [comment]
Right before doing a load, datapusher calls delete_datastore_resource (previously called delete_resource). This went in in 2013, so maybe there was a problem at some point.

Or maybe you had you ckan.site_url set to a completely different instance, and it deleted it off that instance yet added the rows to the correct datastore?

**Comment by davidread** [comment]
Ah, is this to do with it running twice concurrently?
