### ISSUE TITLE
Encoded Equal Sign in CKAN_CURRENT_URL

### ISSUE THREAD

**Issue by FabiApfelkern** [ckan/ckan#2732]
The equal sign, like other special characters is encoded in the CKAN_CURRENT_URL constant. It seems CKAN cannot deal with this. When you have a filtered search, like http://demo.ckan.org/de/dataset?organization=adela-mxabierto and then change the language it leads to: http://demo.ckan.org/en/dataset?organization%3Dadela-mxabierto. The filtering is then not working anymore.

**Comment by Meepu** [comment]
Language selector URLs are quoted at https://github.com/ckan/ckan/blob/01727cbbdb7078e29f7b04b767ef0843b031da6a/ckan/config/middleware.py#L414 but they don't ever appear to be unquoted.

I worked around the problem by creating an unquoting helper function that's called from the template: https://github.com/yhteentoimivuuspalvelut/ytp/commit/1c761538e887cedb6c5c034a10bc0adda6a02461

**Comment by wardi** [comment]
Yes, this looks like a url_for bug introduced some time between 2.3 and 2.4. Unquoting the url with a  helper shouldn't be necessary.

**Comment by wardi** [comment]
@FabiApfelkern @Meepu do either of you have time to investigate and submit a fix?

**Comment by wardi** [comment]
fixed by #3595
