### ISSUE TITLE
package.metadata_created() should be a field

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2735]
Currently metadata_created is a property that calls the metadata_created function - which in turn queries PackageRevision to find the earliest one.  This means that modifying it becomes a chore (for instance, when harvesting).

This should be turned into a column on the model (similar to metadata_modified).  Will need a migration.

**Comment by davidread** [comment]
@wardi says this would help when harvesting.

Maybe it was originally like this and changed - can you look at the history?

**Comment by rossjones** [comment]
Checked the migrations, and it looks like metadata_modified was turned into a DB field a few dozen migrations ago, perhaps it is that which you remember?

**Comment by davidread** [comment]
Ah, that rings a bell. I have a feeling no-one could be bother to do metadata_created too at the time, so it is worth doing.
