### ISSUE TITLE
Wordwrap/break of Organisation Titles

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2754]
After upgrading we have found that on the Organisations page (e.g. https://datastore.landcareresearch.co.nz/organization) the headings of the organisations are not breaking correctly at word breaks, but rather cutting words into bits e.g. below.  We have discovered that this is browser influenced – it displays correctly in Chrome, as below (Fig1) in Firefox, and partly OK in IE (the word breaks are correct, but it only displays 2 columns (Fig2).  
Firefox:
![fig1 firefox](https://cloud.githubusercontent.com/assets/4842751/11353299/c823bfde-92a6-11e5-9d71-80ab84c965d9.png)  
IE:
![fig2 ie](https://cloud.githubusercontent.com/assets/4842751/11353304/d4d3ad3e-92a6-11e5-88bd-99f40078b194.png)  

The word break issue also occurs elsewhere Organisation names are displayed e.g. https://datastore.landcareresearch.co.nz/dataset/nzflora-fife-2014-anomodontaceae, not just the Organisation Page(s).  

This issue has developed in the update path from CKAN 2.2.1 to 2.3, and continued into 2.4.1.  

This problem is also evident on demo.ckan.org  http://demo.ckan.org/organization?sort=&q=&page=2 (and e.g. http://demo.ckan.org/organization/department-of-agriculture). 
 ![fig4 ie - ckan demo](https://cloud.githubusercontent.com/assets/4842751/11353474/4328cf98-92a8-11e5-9dea-66d16c8f4edf.png)  

Behaviour is not consistent e.g In IE this organisation displays OK on the Organisation page . http://demo.ckan.org/organization?sort=&q=&page=2  

![fig5 ie ckan demo](https://cloud.githubusercontent.com/assets/4842751/11353510/abb0f1bc-92a8-11e5-8a09-f0bdde4fa872.png)  

But, click into the organisation and the words break incorrectly (http://demo.ckan.org/organization/consumer-financial-protection-bureau).  

![fig6 ie ckan demo](https://cloud.githubusercontent.com/assets/4842751/11353518/c2b5dd1e-92a8-11e5-8172-32f2ddec77a7.png)  

In Firefox I get the split P  rotection in both ‘views’. In Chrome is fine.

**Comment by k-nut** [comment]
This behavior was introduced by commit 50c31142d1b5db898795ae3b19bfb36a4f01fd03 which was a part of PR #1667 which was supposed to fix #1538.

Unfortunately the original issue did not contain any screenshots so it is not easy to see what they were referring to with `make a mess of the display`.

**Comment by TkTech** [comment]
`reallylongonewordorganizationtitlebecausesomelanguagesarelikethat`

**Comment by k-nut** [comment]
@TkTech yep, I also just realized that here are screenshots that display before and after behavior with a group called `Groupwithatveryveryverylongnamethatprobablybreakthedisplay`:
## Before the change
<img width="968" alt="screen shot 2016-05-27 at 17 18 29" src="https://cloud.githubusercontent.com/assets/1096357/15612499/53e904ba-242f-11e6-9543-c1afda90382b.png">

## After the change 
<img width="965" alt="screen shot 2016-05-27 at 17 19 02" src="https://cloud.githubusercontent.com/assets/1096357/15612503/57f6ef5e-242f-11e6-97c6-55de02b7993c.png">

It would probably be best if we could limit this to only break words that are much too long. Or use automatic hyphenation which unfortunately only has medium support: http://caniuse.com/#feat=css-hyphens

**Comment by TkTech** [comment]
Support word word breaks have historically been slowly and painful implemented. The only "portable" way I know of at the moment is to use a css rule to always break-on-character and use a bit of javascript to fix it live, which can cause redrawing and a visually jarring user experience when the page loads. Boundary analysis is a real pain when working with multiple languages.

**Comment by wardi** [comment]
burn all the grids!

**Comment by k-nut** [comment]
We could for example include the [hyphenator](https://github.com/mnater/hyphenator) polyfill to make this work on browsers that do not support `hyphen: auto` by default. 
At first glance it seems like it weighs in at 134 KB 
Whats the CKAN-policy on things like this?

**Comment by TkTech** [comment]
https://github.com/mnater/Hyphenator/blob/wiki/en_AddNewLanguage.md#what-we-have-now

It seems it has considerable multilanguage support, thus I'm in favour of it. 134kb of static content is irrelevant compared to the weight of existing uncached pages.

**Comment by wardi** [comment]
or we could use a list instead of a grid and just show the whole group name in a nice easy-to-scan way. Less space wasted on group images too.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
