### ISSUE TITLE
2.5 release

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2758]
Full instructions here: https://github.com/ckan/ckan/blob/master/doc/contributing/release-process.rst

## Doing a beta release
* [x] Create a new release branch
* [x] Update beta.ckan.org to run new branch.
* [x] Make latest translation strings available on Transifex.
* [x] Send an annoucement email with a call for translations to ckan-dev list.
* [x] Create debian packages.

## Leading up to the release
* [x] Update the CHANGELOG.txt with the new version changes.
* [x] A week before the translations will be closed send a reminder email.
* [x] Once the translations are closed, sync them from Transifex.
* [x] A week before the actual release, announce the upcoming release(s).

## Doing the final release
* [x] Run the most thorough tests.
* [x] Do a final build of the front-end and commit the changes.
* [x] Review the CHANGELOG to check it is complete.
* [x] Check that the docs compile correctly.
* [x] Remove the beta letter in the version number.
* [x] Tag the repository with the version number.
* [x] Create and deploy the final deb package.
* [x] Upload the release to PyPI.
* [x] Enable the new version of the docs on Read the Docs.
* [x] Write a CKAN blog post and announce it to ckan-announce & ckan-dev.
* [x] Cherry-pick the i18n changes from the release branch onto master.

**Comment by davidread** [comment]
@amercader do you have a chance to create the debian packages?

**Comment by amercader** [comment]
@davidread sure, will do it tomorrow

**Comment by davidread** [comment]
Adria did the beta deb packages: http://packaging.ckan.org/build/

**Comment by amercader** [comment]
@davidread Patch releases are ready, including packages

**Comment by davidread** [comment]
Super, I'll do the changelog.
Dave

**Comment by davidread** [comment]
All done
