### ISSUE TITLE
Changing user password in web interface

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2760]
We are running CKAN 2.4.1.  There is a discrepancy between the documentation, and reality, and this discrepancy prevents a sysadmin changing/resting a users password via the web interface. 
  
Documentation http://docs.ckan.org/en/latest/sysadmin-guide.html#managing-users suggests that sysdmin just needs to enter a new password twice, and the users password will be changed.  
  
However, in CKAN 2.4.1 we are presented with an additional box, requesting the Old Password, as well as setting the new password. This box is redundant, and prevents the sysadmin maintaining the users record.  ie. if the user has forgotten their old password then they cannot tell it to the sysdmin to allow them to change the password, and if they remembered their old password then the user would not need to ask the sysadmin to change the password for them.  
  
Can the Old password box be removed from the manage user screen.  If the user can get to that screen, then clearly they know their own password as they are logged in already, and the sysadmin should not need to know a users old password.

**Comment by wardi** [comment]
You're right, this is a problem. We would like to prevent accidental or malicious password changes when someone is already logged in, though.

At the meeting @brew suggested having sysadmin users enter their *own* password instead of the user's password in this form. How does that sound?

**Comment by Aaron-M** [comment]
Yes - having to confirm the sysadmin password would work.

**Comment by wardi** [comment]
@k-nut would you have time to take a look at this issue?

**Comment by k-nut** [comment]
Yes. I will take a look at it now.

**Comment by k-nut** [comment]
Actually this is how it works already. The field has the label `old password` but what it really means is `your current password`. So if an admin wants to make changes to a username they already have to input **their** password, not the users. Can you confirm that @Aaron-M ?

If you can confirm that maybe we can find a better wording for this.

**Comment by Aaron-M** [comment]
@k-nut I just tested, logged in as sysadmin attempted to change another users password - yes it works when I put in my sysadmin password where it says old password.  To cater for this situation, as well as when a user wants to change their own password, I suggest what we need is something like putting "(or sysadmin password") in small writing underneath "Old Password".  Alternately if it was very clever it could detect if you are looking at your own user record, or if you are a sysadmin looking at another useres record, and label appropriately.
