### ISSUE TITLE
Improve warning messages when user tries to create a dataset but there're no organizations

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#2767]
When installing CKAN, there're no organizations created by default. In that case, when I go and try to add a new dataset, it'll complaing with a somewhat cryptic `Owner org: A organization must be supplied` (see screenshot):

![ckan-without-orgs](https://cloud.githubusercontent.com/assets/76945/11559386/3e0a07b6-99b0-11e5-9a65-acfe22746910.png)

Notice there isn't even a field for setting the organization (because there're no organizations at all). If the user isn't assigned for an organization and CKAN is configured to require one, it would be good to let the user know that as soon as he goes to the dataset creation page.

**Comment by wardi** [comment]
consensus at the meeting is we need somethg like a flash message to appear above this form when no orgs are available but the configuration requires them. Even better if it includes a link to the new org page since this page will only ever be visible for sysadmins

**Comment by k-nut** [comment]
This is duplicated by #3046 an will hopefully be fixed by #3054

**Comment by wardi** [comment]
fixed by #3054
