### ISSUE TITLE
group_controller() on IGroupForm not in interface

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#2771]
In `plugins.py`, there is a [call to a function `group_controller`](https://github.com/ckan/ckan/blob/bdbb5a851d4ae23c778f1c64c310331f796e68d2/ckan/lib/plugins.py#L155) on IGroupForm plugins.

This method is not mentioned on the [IGroupForm interface](https://github.com/ckan/ckan/blob/bdbb5a851d4ae23c778f1c64c310331f796e68d2/ckan/plugins/interfaces.py#L1170). This leads to a strange bug: I'm using ckanext-scheming and this implements IGroupForm for a custom organization schema. But because this method is not present, it will use the `group` controller instead of the `organization` controller to generate links (e.g. for the pagination).

I guess this method just went missing and should be added to the interface and can then be implemented by extensions as needed.

**Comment by davidread** [comment]
Sounds good, are you ok to implement this?

**Comment by metaodi** [comment]
Sure, just wanted to ask first if I understood the concept correctly. PR follows.
