### ISSUE TITLE
Switch the css pre-processor from LESS to SASS

### ISSUE THREAD

**Issue by LaurentGoderre** [ckan/ckan#2772]
As part of the upgrade to Bootstrap3 (#2602) I would like to propose changing the CSS pre-processor from LESS to SCSS (SASS). The reasoning is that future version of Bootstrap will be using SASS/SCSS as it's preporcessor.

**Comment by amercader** [comment]
@LaurentGoderre Unless I'm missing something this would involve rewriting all less files (https://github.com/ckan/ckan/tree/master/ckan/public/base/less) and changing the compiler we use to build the frontend right?

I'm definitely not an expert on the frontend side of things but if you are up for it it sounds like a good move. What I do think it would be an improvement is if we could drop the node [requirement](http://docs.ckan.org/en/latest/contributing/frontend/index.html#install-frontend-dependencies) that we currently have for building the CSS. Perhaps there is a better Python library support for SASS?

**Comment by LaurentGoderre** [comment]
Actually, for front-end development, Node is what has the best tools for the job, but it would be possible to manage the front-end stuff separately and include in in CKAN so only the front-end people need to deal with node.

**Comment by TkTech** [comment]
The work for this is being done as part of #3547.
