### ISSUE TITLE
Headless CKAN - Moving front-end controllers to an extensions

### ISSUE THREAD

**Issue by LaurentGoderre** [ckan/ckan#2773]
As part of the upgrade to Bootstrap 3 (#2602) I was thinking we could move the front-end controllers to an extensions to make CKAN headless. In this approach, the new Bootstrap3 would be the default rendering extensions but it would be possible for implementers to implement their own front-end engine. There are plenty other benefits of this approach and I am wondering what is everyone's thought on this.

**Comment by wardi** [comment]
Initially we could leave the code where it is (in ckan) but add the routes from a plugin instead of `config/routing.py`. This would allow extensions that import these controllers to continue work for a little longer.

**Comment by LaurentGoderre** [comment]
Can this be phased in by duplicating the code for the time being? How often do these controller change?

**Comment by davidread** [comment]
Team says: can you explain more? I don't understand any benefit to moving controllers to an extension. Surely that's harder for another extension to overwrite some of the controllers?

**Comment by LaurentGoderre** [comment]
It's not just the controller but the entire front-end that we could move to a plugin. The plugin would be installed automatically as a dependency of ckan and the development.ini would enable it by default. To the default user, the entire thing would be invisible.

It would also move the templates away from the core repo which would deal only with the business logic and API. It would simplify the repo and would allow the front-end and back-end to move a different speeds. For example, it would allow implementers to ditch the default front-end and create an entirely new one if they wanted.

**Comment by LaurentGoderre** [comment]
Is there a time that would work best for me to join the IRC channel to discuss this further?

**Comment by wardi** [comment]
The best time to be on IRC is all the time. You're not supposed to leave IRC.

**Comment by LaurentGoderre** [comment]
Yes I know.....

**Comment by wardi** [comment]
soon to be merged BS3 migration #3547 is taking a simpler approach, closing this issue.
