### ISSUE TITLE
Vulnerability: html resources

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan#2778]
It seems like by default any registered user can post html resources and put some malicious code there.
http://demo.ckan.org/dataset/6581a37e-2a32-415f-aae3-363cd4570a2b/resource/354bbf01-0c67-4204-a04d-888e079d81f5/download/eeraheader.html

This makes vector attack of stealing admin cookies credentials possible. Did you see all those "Hacked by Muslims" datasets? I think it should not be possible to view html files uploaded by users.

**Comment by amercader** [comment]
This is a known issue, thanks.

Please use security@ckan.org to report this kind of issues
