### ISSUE TITLE
Can't set tags' `display_name` when creating dataset

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#2781]
When calling `package_create`, I would like to be able to pass something like:

``` json
{
    "name": "gdp",
    "tags": [
        { "name": "gdp", "display_name": "國內生產總值" }
    ]
}
```

There are some limitations to the `name` (i.e. they can only be alphanumeric plus `.-_`), but these limitations don't exist for `display_name`. I suppose that's because `name` is used as a kind of primary key for the tag.

When I try to create a dataset like the JSON above, the `display_name` I passed is ignored, and it's set equal to the `name` attribute.

**Comment by amercader** [comment]
AFAICT tags don't have these limitations if created via the frontend form:

http://demo.ckan.org/dataset/demo-health
http://demo.ckan.org/api/action/package_show?id=demo-health

Maybe there is some magic in the package controller that is allowing it

**Comment by wardi** [comment]
The Tag model only has a "name". You can change the "display_name" with the multilingual extension by registering a translation for your "gdp" value.

Note that multilingual will then translate the complete string value "gdp" the same way everywhere it finds it.

**Comment by wardi** [comment]
Closing because this is a feature request that isn't currently being worked on.
