### ISSUE TITLE
Can't purge large number of datasets via web ui

### ISSUE THREAD

**Issue by bunnis** [ckan/ckan#2786]
Hi
Using ckan 2.4, I deleted all my datasets (~10k) using ckanapi for python. Now since this version does not contain purge_dataset api call, I went to the web admin UI, and after pressing the purge button, the browser keeps waiting for a server responde. After a while (3k s), ckan stops the thread and doesn't delete the datasets. Any thoughts on how to purge the datasets?

2015-12-11 15:09:09,094 WARNI [paste.httpserver.ThreadPool] Thread 139948856215296 hung (working on task for 3477 seconds)
Debug at: http://100.100.0.201:5000/_debug/view/1449846549

URL: http://100.100.0.201:5000/ckan-admin/trash
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/home/bunny/ckan/lib/default/src/ckan/ckan/config/middleware.py', line 389 in inner
  result = application(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/home/bunny/ckan/lib/default/src/ckan/ckan/lib/base.py', line 338 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/home/bunny/ckan/lib/default/src/ckan/ckan/controllers/admin.py', line 155 in trash
  difference(set(c.deleted_packages))
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py', line 70 in instances
  process[0](row, rows)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py', line 484 in _instance
  populate_state(state, dict_, row, isnew, attrs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py', line 309 in populate_state
  populator(state, dict_, row)
SystemExit:

**Comment by bunnis** [comment]
some more info

2015-12-11 15:24:20,585 INFO  [ckan.lib.base]  /ckan-admin/trash render time 11.483 seconds
----------------------------------------
Exception happened during processing of request from ('100.100.2.91', 33410)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
2015-12-11 15:24:23,470 INFO  [ckan.lib.base]  /api/i18n/en render time 0.001 seconds

**Comment by davidread** [comment]
Suggest you use the dataset_purge action via the API.

**Comment by bunnis** [comment]
im working with ckan 2.4.0. no mention of dataset_purge on documentation (http://docs.ckan.org/en/ckan-2.4.0/api/). trying to evoke the action results in

Traceback (most recent call last):
  File "purge_datasets.py", line 22, in <module>
    ckan.action.dataset_purge(id=dataset_id)
  File "/usr/local/lib/python2.7/dist-packages/ckanapi-3.6.dev0-py2.7.egg/ckanapi/common.py", line 51, in action
    return self._ckan.call_action(name, data_dict=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ckanapi-3.6.dev0-py2.7.egg/ckanapi/remoteckan.py", line 83, in call_action
    return reverse_apicontroller_action(url, status, response)
  File "/usr/local/lib/python2.7/dist-packages/ckanapi-3.6.dev0-py2.7.egg/ckanapi/common.py", line 131, in reverse_apicontroller_action
    raise CKANAPIError(repr([url, status, response]))
ckanapi.errors.CKANAPIError: ['http://100.100.0.201:5000/api/action/dataset_purge', 400, u'"Bad request - Action name not known: dataset_purge"']

**Comment by davidread** [comment]
It's in 2.5.0, out later today.

**Comment by bunnis** [comment]
I get that. But im using 2.4.0... Its a problem on 2.4.0, not 2.5

**Comment by davidread** [comment]
I can't see an easy way to do this on 2.4, so I think you're best bet is to upgrade.
