### ISSUE TITLE
JSON files and their mimetype - known issue?

### ISSUE THREAD

**Issue by natasab** [ckan/ckan#2787]
Dear all,
 

i am not sure if this is a known issue, so posting here for a help. 
We harvest JSON data, these are stored in CKAN with correct extension, see https://repository.cendari.dariah.eu/dataset/a2692501-c9da-474a-b5cd-ab9967f7610a/resource/e7a0e2d9-d26c-463b-a836-286b3472042b
 
OS:
Linux pro2 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

In the storage directory itself, the mimetype is actually "text" and no longer application/json. This causes troubles with indexing of documents, json is not processed, it is processed rather as text.

Would appreciate information if this has happened to someone before as well and what were the fixed. 

Thanks a lot..

**Comment by wardi** [comment]
I don't understand. Your file is being served with `Content-Type: application/json`

```bash
curl -v https://repository.cendari.dariah.eu/dataset/a2692501-c9da-474a-b5cd-ab9967f7610a/resource/e7a0e2d9-d26c-463b-a836-286b3472042b/download/0862312925.json \
  -O /dev/null 2>&1 | grep Content-Type
< Access-Control-Allow-Headers: X-CKAN-API-KEY, Authorization, Content-Type
< Content-Type: application/json
```

Where are you seeing this "text" mimetype?

**Comment by natasab** [comment]
in the storage: as the file is saved without any extension - the mimetype is guessed as text.
In meantime i found another solution to overcome this problem. thank you.
