### ISSUE TITLE
Tell search engines to favour the latest CKAN docs in readthedocs

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2793]
Apparently we can tell Google to heavily favour the latest docs in readthedocs, rather than older versions, by using a 'canonical link'.

https://read-the-docs.readthedocs.org/en/latest/faq.html#can-i-make-search-engines-only-see-one-version-of-my-docs

https://support.google.com/webmasters/answer/139066?hl=en

Are we happy to do this?

**Comment by rossjones** [comment]
I'm +1, it's confusing to be sent to the old versions of pages.

**Comment by rossjones** [comment]
This looks like it is fixed by https://github.com/rtfd/readthedocs.org/issues/1955 as the canonical link is present on pages at docs.ckan.org.
