### ISSUE TITLE
Missing documentation in 'interfaces' reference.

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2797]
http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IDomainObjectModification (and IResourceUrlChange) documentation have no documentation for the methods they expose.

**Comment by bwanglzu** [comment]
This part of documentation is generated automatically, I think we can add documentation by change the comment in **./ckan/plugins/interfaces.py**

**Comment by wardi** [comment]
closed by #2897
