### ISSUE TITLE
Harvest sources are listed on organization detail page

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#2803]
By default the CKAN search is filtered, so that only datasets with the type "dataset" are displayed (see https://github.com/ckan/ckan/blob/4dbfa464f7c9582094ba2e341745b50b8137ba38/ckan/controllers/package.py#L234). But if you are on the organization detail page, all kinds of datasets are shown.

I think this is inconsistent and I consider this a bug. I think the bug is, that the group controller does not set the `dataset_type` parameter in `fq` here: https://github.com/ckan/ckan/blob/bdbb5a851d4ae23c778f1c64c310331f796e68d2/ckan/controllers/group.py#L300

**Comment by wardi** [comment]
@brew fixed this for showcase with an IPackageController before_search that filter that removes the type. At the meeting we discussed adding a config option with a list of types that should be excluded from search by default.

It *is* nice to let a plugin decide not to show some of its dataset types in search though, so we could adopt @brew's solution as the standard, or extend IDatasetForm to let it declare its types to exclude.

**Comment by metaodi** [comment]
@wardi I think this is not directly related here, as it's actually CKAN core, which should only show datasets by default. I don't think there is a good reason for the current implementation.

I agree that plugins should still be able to use `before_search` to change this behavior, but it's up to the plugin to enable/disable search for any "new" dataset type it introduces.

**Comment by metaodi** [comment]
Btw, the code that @wardi mentioned is here: https://github.com/ckan/ckanext-showcase/blob/da5e28b91c011aa8f5417082a6320d4d23021e78/ckanext/showcase/plugin.py#L244-L255

**Comment by amercader** [comment]
Fixed in ckan/ckanext-harvest#221
