### ISSUE TITLE
Allow webpageview on external URLs

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#2806]
Right now, webpageview only works for files with format HTM/HTML.

https://github.com/ckan/ckan/blob/master/ckanext/webpageview/plugin.py#L27-L31

Why not just allow webpageview for an external URL?

This could be a great generic way to handle external resources without having to create a special purpose preview handler (see #1536)

For example, [Google Sheets](http://data.beta.nyc/dataset/hack4heat-2015-related-datasets/resource/bb4924bf-26cd-4b60-8006-e15038205b95), Docs, [Slides](http://data.beta.nyc/dataset/hack4heat-2015-related-datasets/resource/5cd5fd78-ade7-4223-b402-82408e814805), etc. and anything that can live in an iframe.

e.g. http://data.beta.nyc/dataset/hack4heat-2015-related-datasets

We actually allowed this on this CKAN instance.

**Comment by florianm** [comment]
With a "Fullscreen" button that simply opens the resource URL in a new tab?

**Comment by rossjones** [comment]
Was discussed during the techteam meeting today, but I think we may have misinterpreted this as 'allow full page HTML' rather than 'render any URL in an iframe'.  

Would be open to reviewing a PR if someone had the time, you might get away with just changing those lines mentioned above.

**Comment by mattfullerton** [comment]
Would you like the fullscreen button in core? (e.g. https://smartlane.io/dataset/different-geo-visualizations/resource/49f0fcff-b3c8-48c8-b1c6-ddc33e4a83fe). For all resource views or just for webpage view? I find small template additions as extensions problematic because of inter-extension conflicts.

**Comment by rossjones** [comment]
I think a full-screen button for all resource views would be very useful.

The other part of this issue though is that webview currently only shows HTML pages in a webview, I think @jqnatividad was asking that any URL could be viewed in the webview (for dataviz etc). That way URLS that are links to Google Docs (and not necessarily identified as format=html) would work.

**Comment by florianm** [comment]
@mattfullerton +1 on fullscreen button in core would be better than my little [hack](http://catalogue.beta.data.wa.gov.au/dataset/benthic-sampling-sites-of-dpaw-at-ningaloo-mpa/resource/74acc596-fc5b-40c5-aa0a-9f71706d6304) of an extension.

**Comment by rossjones** [comment]
Anyone up for a PR? ;)
