### ISSUE TITLE
Usernames cannot have dots in them -- but some middleware can violate this rule

### ISSUE THREAD

**Issue by zephod** [ckan/ckan#2826]
https://github.com/ckan/ckan/blob/master/ckan/authz.py#L438

This line detects the anonymous user by looking for a dot in his username (ie. it's looking for an IP address). That's okay because the vanilla web interface (and, I assume, the API) probably disallows usernames from containing a dot. 

But users are pluggable via middleware, and so depending on how exotic your CKAN setup is, users might be coming from an external database, or LDAP, or (as in DataPress) a WordPress integration. The point is that it's hard to be sure that the rules have been followed.

Is there any reason why this anon function can't be changed to something like this? eg.

    return context.get("auth_user_obj") is None

**Comment by amercader** [comment]
@zephod I believe that @wardi's changes in https://github.com/ckan/ckan/pull/2817 address this. 
Feel free to reopen if that's not the case. Cheers.
