### ISSUE TITLE
Group names are globally unique, even across types.

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2850]
If I implement IGroupForm to introduce a new group type, say 'Collections', I am unable to use any name that is in use by any other type of group, for instance organisations. 

Ideally the group 'name' field would be unique with the group 'type' field so that it is possible to use names across different implementations on groups.

Would suggest something like

```sql
ALTER TABLE "group" DROP CONSTRAINT group_name_key;
CREATE UNIQUE INDEX  group_name_type_key on "group"(name,type);
```

**Comment by wardi** [comment]
`organization_list` and `group_list` endpoints would be broken by this

**Comment by rossjones** [comment]
Do you mean broken-broken, or just 'pay attention to these two functions when submitting a PR' ?

**Comment by wardi** [comment]
I mean we would at least need to make them return a list of group/org ids instead of names the way they do now.

Maybe the larger breakage is that group_show and organization_show would require the type to be passed if using id=name

**Comment by rossjones** [comment]
Most of the group_* and organization_* functions set data_dict['type'] = 'whatever' before delegating to a shared function, so that should be fixable.  

I'm not sure I see the issue with organization_list returning names, because you should then use organization_show (once fixed) which would automagically set the type.

**Comment by rossjones** [comment]
It looks like there'd be more breakage in places like _group_or_org_delete where it just does ```model.Group.get(id)``` and as pointed out, if this is a name, it will potentially return multiple Groups.  Would need changing to query with id and type.

**Comment by wardi** [comment]
But right now you can create custom group and org types *and* look up those groups and orgs by their names. With this change that would only work for orgs with type='organization' and groups with type='group'

**Comment by rossjones** [comment]
This is true but I think the group controller sometimes sets data_dict['type'] = guessed_type and sometimes not.  If it was consistent so it set it in the ```read``` action,  group_show would do the right thing (apart from issues with ```model.Group.get``` mentioned above. 

The group_show API call would definitely need the type setting.

**Comment by wardi** [comment]
right, so we're talking about a breaking API change for anyone using non-default group and org types. The number of people that will affect might be small, but I don't know for sure.

**Comment by rossjones** [comment]
It just feels wrong to me that things that are conceptually different, say themes, collections and organizations are so tightly bound that they can't share names. It's entirely possible that this isn't worth the effort, or the breakage.

**Comment by rossjones** [comment]
We decided that although this isn't great, it isn't likely to be possible without a breaking change, and that now isn't the time to do that.
