### ISSUE TITLE
Using Jinja2 filters / tests in CKAN extension templates

### ISSUE THREAD

**Issue by RadoRado** [ckan/ckan#2858]
Hi there!

While I was developing a CKAN extension, I decided to use cusstom template helpers as described here - http://docs.ckan.org/en/latest/theming/templates.html#adding-your-own-template-helper-functions

Everything worked great, but then, I tried to use custom [filters](http://jinja.pocoo.org/docs/dev/templates/#filters) and [tests](http://jinja.pocoo.org/docs/dev/templates/#tests) from Jinja2 API

Sadly, it didn't work.

When I tried to use something as a filter or tests like that:

```
{{ something | h.some_filter }}
```

Got the following error:

```
<class 'jinja2.exceptions.TemplateAssertionError'>: no filter named 'some_filter'
```

Same with tests.

I looked up at the documentation but didn't find anything.

Is it supported?

p.s. This is not a breaking issue, because you can always use `{{ h.some_filter(something)}}` or `{% if h.some_test(something) %}`

Just something that is good to have.

**Comment by amercader** [comment]
This is not supported, but if you are really keen on it and find an easy way to activate it feel free to send a PR.

I imagine that any custom filter would need to be registered in the Jinja2 environment. Here's [a bit of code](https://github.com/ckan/ckan/blob/1d665023c03ca9f7404af807a9b55e140f58fde3/ckan/config/environment.py#L294) in CKAN core that might be relevant.

**Comment by RadoRado** [comment]
@amercader thanks for the suggestion! Will look at the code.

**Comment by amercader** [comment]
Closing for now, feel free to reopen if there are some news on this front.
