### ISSUE TITLE
Sanitize offset when listing group activity

### ISSUE THREAD

**Issue by drmalex07** [ckan/ckan#2859]
This is a very minor problem, apart that it causes `HTTP 500` errors where it should simply ignore the `offset` parameter (or reply with a `HTTP 400`). It happens at https://github.com/ckan/ckan/blob/master/ckan/controllers/group.py#L860 because `offset` is not validated and passed as-is to the action api function. 

We have encountered this type of errors several times in our production site, since crawling robots insist on trying URLs like http://labs.geodata.gov.gr/group/activity/imagery-base-maps-earth-cover/None

The above is tested on CKAN 2.2, but seems to be exactly the same at the master branch.

**Comment by amercader** [comment]
You are right, we have a couple of these on some actions. The best thing is to add [this decorator](https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L3254) to the [relevant action](https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L2695) and try / except a ValidationError on the group controller.

Do you want to submit a small PR for this?

**Comment by drmalex07** [comment]
That's ok, and is roughly what we've done in our fork to overcome it. I think the same problem also shows up in user activity lists (https://github.com/ckan/ckan/blob/master/ckan/controllers/user.py#L550). 

So, i will return with a PR.
