### ISSUE TITLE
User email can be changed without verifying password

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#2870]
Since user passwords can be changed using email addresses through reset links, changing email address should be verified against current password. 

We will fix this in our environment so will probably supply a PR.

**Comment by rossjones** [comment]
You should be aware of the work mentioned in #2838 as well.  Perhaps it might also get covered there?

**Comment by Zharktas** [comment]
It probably should be also covered in there, but the change was quite simple so I made PR #2872 for it also.

**Comment by davidread** [comment]
@rossjones might you add @Zharktas to this github org so that we can assign him this ticket?

**Comment by Zharktas** [comment]
Fixed in https://github.com/ckan/ckan/pull/2872
