### ISSUE TITLE
Incorrect 'download resource' hyperlink when a resource is unable to upload to datastore 

### ISSUE THREAD

**Issue by Mbrownshoes** [ckan/ckan#2873]
When a dataset cannot be previewed in the Data Explorer - e.g. when the dataset it too large, or has not been loaded to the DataStore (e.g. http://demo.ckan.org/dataset/bad-hyperlink-example/resource/36a112c0-7a4e-40da-aa0d-8e0c67e64957) the Data Explorer is providing an incorrectly addressed "Download resource" hyperlinked button
![image](https://cloud.githubusercontent.com/assets/1154765/12952293/d5c9a624-cfca-11e5-9a18-754d1f0e928a.png)
 
The hyperlink URL  http://demo.ckan.org/dataset/bad-hyperlink-example/resource/36a112c0-7a4e-40da-aa0d-8e0c67e64957 is missing the terminating text /download/

**Comment by amercader** [comment]
@smotornyuk @Engerrs can either of you have a look at this one? It should be easy to track where the URL is coming from. The template used is this one:

https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/resource_view.html

Thanks!

**Comment by smotornyuk** [comment]
I will take that one

**Comment by amercader** [comment]
Thanks @smotornyuk!

**Comment by wardi** [comment]
Was this not fixed by https://github.com/ckan/ckan/pull/2599

**Comment by smotornyuk** [comment]
No, problem here in variable that not passed into template

**Comment by amercader** [comment]
Fixed by #2930
