### ISSUE TITLE
ckan-2.4.2 tag misses commits

### ISSUE THREAD

**Issue by tremblaysimon** [ckan/ckan#2874]
ckan 2.4.2 seems to miss some commits about markdown to work properly like that one https://github.com/ckan/ckan/commit/2bd13792a561d9dc38681e95443f63f1255944f9 and https://github.com/ckan/ckan/commit/eef140ba9525afc74ef2548b490a78f8df9ceb3d.

**Comment by amercader** [comment]
@tremblaysimon the commits you mention involved installing new libraries and that is something that we don't do on patch releases as a policy. The approach on previous releases was to embed the new library in the code to avoid having to install it. This is the commit that included this change on 2.4:

https://github.com/ckan/ckan/commit/1b30332efb746200ac89a2a645aaac55b18bdda6

The effect should be the same. Are you noticing any particular issues with Markdown on 2.4?

**Comment by tremblaysimon** [comment]
With 2.4.2 markdown doesn't seem to work. But maybe it's an error on our side. My co-worker who reports that issue with markdown on 2.4.2 will be there next week, I will post a concrete example of what doesn't work.

**Comment by amercader** [comment]
Any news on this front? Markdown renders fine for me on 2.4.2. 
If you have a specific example of what's is not working please reopen, thanks!
