### ISSUE TITLE
Paster command db simple-dump-json fails with out of memory error

### ISSUE THREAD

**Issue by raphaelstolt** [ckan/ckan#2878]
When dumping large datasets (~17.000) the paster command `db simple-dump-json` fails with an out of memory error. 

System: 

- Ubuntu 14.04.2 LTS 
- 64-bit platform
- RAM 8 GB

I tried to patch the local install with an implementation writing only some JSON chunks to the output file, which still fails in the way that the process gets killed, also by an out of memory error.

```python
def dump_json(self, dump_file_obj, query):
    for pkg in query:
        pkg_dict = pkg.as_dict()
        for chunk in json.JSONEncoder(indent=4).iterencode(pkg_dict):
            dump_file_obj.write(chunk)

    dump_file_obj.close()
```

My way of avoiding failing dumps is currently using a combination of `ckanapi dump datasets` and some post `jq` manipulation via `cat dump.jsonl | jq --slurp . > dump.json`.

**Comment by TkTech** [comment]
@raphaelstolt simple-dump-json has been removed in PR #2879 - if you want this same functionality, take a look at ckan/ckanapi.

**Comment by raphaelstolt** [comment]
Since `simple-dump-json` has been removed and we also switched to utilising the `ckanapi` CLI, this ticket can be closed.
