### ISSUE TITLE
Activity timestamps are stored in local time instead of UTC

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#2882]
https://github.com/ckan/ckan/blob/master/ckan/model/activity.py#L41

If server has local time set to some timezone that differs from UTC, activity streams show -1 days ago instead of just now, since datetime.now() return local time instead of UTC. There probably are others as well which use local time instead of UTC, at least based on a quick search https://github.com/ckan/ckan/search?utf8=%E2%9C%93&q=datetime.now%28%29&type=Code

**Comment by wardi** [comment]
That's not good.

A fix would include a migration that updates the times in the db (using the current time offset should be close enough for the activity stream) and updating the templates to use the snippet that adjusts the display to the client's time zone

**Comment by Zharktas** [comment]
@wardi and apparently "-1 days ago" is returned from here https://github.com/ckan/ckan/blob/master/ckan/lib/formatters.py#L71 if server time is in UTC but ckan.display_timezone is something else like Europe/Helsinki

**Comment by framon** [comment]
I confirm that activity timestamps are always stored in server local timezone guessing it is UTC.

Given server timezone is `America/Sao_Paulo` (-03:00). When `ckan.display_timezone` is `server` then a difference of -6 hours is shown. When `ckan.display_timezone` is `UTC` then the difference becomes -3 hours (still incorrect).

**Comment by scardine** [comment]
According to this ticket the issue may be more than 4 years old: http://trac.ckan.org/ticket/331.html
