### ISSUE TITLE
How to fetch resource as xml

### ISSUE THREAD

**Issue by khanmuqeetkhan** [ckan/ckan#2887]
### CKAN Version if known (or site URL)
http://demo.ckan.org

### Please describe the expected behaviour
If suppose you have inserted data into datastore using CKan API

curl -X POST http://demo.ckan.org/api/3/action/datastore_create -H "Authorization: <Api-key>" -d @mycompanydata.json

With help of action api I could fetch data as follows:
http://demo.ckan.org/api/action/datastore_search?resource_id=<my-resouce-id>&filters={“hid”:”23455-XJ31”}

Can i fetch the same resource as XML? How?

### Please describe the actual behaviour
As xml

**Comment by rossjones** [comment]
Unfortunately, the datastore doesn't support XML output.  If you're interested in submitting a PR, I'm sure it is something that can discussed in this ticket.  Otherwise, I'll close it in a couple of days.

**Comment by khanmuqeetkhan** [comment]
Okay. I will do it. Closing issues.
