### ISSUE TITLE
Limits for CKAN datastore ?

### ISSUE THREAD

**Issue by ckan-user1** [ckan/ckan#2888]
### CKAN Version if known (or site URL)
http://demo.ckan.org

### Please describe the expected behaviour

Is it the same limits  (see below) for datastore using CKan API?

 Some general PostgreSQL limits are included in the table below.
Limit	Value
Maximum Database Size	Unlimited
Maximum Table Size	32 TB
Maximum Row Size	1.6 TB
Maximum Field Size	1 GB
Maximum Rows per Table	Unlimited
Maximum Columns per Table	250 - 1600 depending on column types
Maximum Indexes per Table	Unlimited

### Please describe the actual behaviour
The datastore using Postgres database.

### What steps can be taken to reproduce the issue? 
Have you done any tests for the internal database.

**Comment by rossjones** [comment]
I'm unaware of any tests on the limits, but datastore doesn't do anything to limit beyond this values. You should also be aware that postgres has a field-name limit of 63 characters (which has been tested, by accident ;) ).
