### ISSUE TITLE
Problems with translations in plugins

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#2895]
(This came up together with #2893, see there for more details)

I found two issues regarding translations in plugins:

1. `ckan.lib.plugins.DefaultTranslation.i18n_directory` relies on the extension package's `__file__` attribute (`ckanext.my_extension.__file__`). However, many extensions are distributed using namespace packages, and namespace packages don't have a `__file__` attribute.

2. It seems that `.mo` compiled translation files are not automatically picked up when an extension is packaged using `setup.py`.

I will prepare a PR for this.

**Comment by amercader** [comment]
@torfsen Issue 2 makes perfect sense. But is issue 1 still relevant after your discussion with @wardi on #2894?

**Comment by torfsen** [comment]
@amercader You're correct that with our fix for #2894 issue 1 is not a problem. However, during my research I've found multiple extensions which declared both `ckanext` and the extension main package as namespace packages. For these extensions issue 1 is still a problem.

I guess you could tell their developers to just overwrite `i18n_directory`, but on the other hand the change in my PR fixes the problem and is fully backwards compatible.
