### ISSUE TITLE
SOLR usage in CKAN

### ISSUE THREAD

**Issue by khanmuqeetkhan** [ckan/ckan#2899]
### CKAN Version if known (or site URL)
CKAN 2.6.0a documentation

### Please describe the expected behaviour
There is no detail information about SOLR usage in CKAN documentation. CKAN provides Action API and REST API. According to documentation REST API is dead and it's CKAN Action API which is active. But SOLR also provides RESTful API. What about that?

### Please describe the actual behaviour
Clearity on how SOLR is used by CKAN. CKAN Action API and SOLR API usage

### What steps can be taken to reproduce the issue? 
See documentation 2.6.0a

**Comment by wardi** [comment]
CKAN uses SOLR as an internal search index (and cache of json blobs). While you can use CKAN's SOLR index, that's pretty much the same as accessing CKAN's database directly.  CKAN's SOLR index is not meant as a public API that is stable across CKAN releases, and it's also often customized by extensions, so it's pretty risky to rely on it for external applications.
