### ISSUE TITLE
BugFix: default value of created by resource

### ISSUE THREAD

**Issue by t2-yoshida** [ckan/ckan#2903]
### CKAN Version if known (or site URL)

2.5.1
### Please describe the expected behaviour

e.g. current time is 2016-03-10 15:30 in Japan (UTF+9:00)
A value of the created column on the resource table is 2016-03-10 06:30:00.000
May 10, 2016 is displayed by the Additional Info
### Please describe the actual behaviour

A value of the created column on the resource table is 2016-03-10 15:30:00.000
May 11, 2016 is displayed by the Additional Info
### What steps can be taken to reproduce the issue?

modify ckan/model/resource.py

Before: Column('created', types.DateTime, default=datetime.datetime.now),
After: Column('created', types.DateTime, default=datetime.datetime.utcnow),

**Comment by wardi** [comment]
This little change would be great. Even better if it includes a migration for the data in the DB too.

**Comment by hbunke** [comment]
I'm not sure about the migration. Without having the timezone information in 'created' there's no way to migrate it reliably to UTC. Getting the current local timezone would be correct in let's say 95%, but it's not for sure that it is the same tz as when the resource has been created.

**Comment by bblackifyme** [comment]
FYI looks like the recommended fix was updated inside the resource.py file https://github.com/ckan/ckan/blob/master/ckan/model/resource.py

**Comment by amercader** [comment]
Fixed in #3447
