### ISSUE TITLE
Failed to pull image datacats/web

### ISSUE THREAD

**Issue by sckott** [ckan/ckan#2922]
### CKAN Version if known (or site URL)

none yet, trying to install

### Please describe the expected behaviour

I'm hoping installation will work

### Please describe the actual behaviour

Trying to follow installation guide at http://docs.datacats.com/guide.html  on Ubuntu 14.04 on DigitalOcean. But I'm running in to a problem here http://docs.datacats.com/guide.html#download-the-necessary-docker-containers on the command `datacats pull`, where I get `Failed to pull image datacats/web` - This happens whether I am as root or if I remove root and login as a non-root user.

The same thing happened whether I used DO's docker droplet (which comes with Docker installed), or removing their Docker install and installing via `wget ...`  as per your instructions. 

`sudo datacats pull` gave the same error on the non-root account

And I made sure to `sudo usermod -aG docker USERNAME`

### What steps can be taken to reproduce the issue? 

* spin up DO droplet ubuntu 14.04 1 gb size w/ or w/o docker installed
* I then ran `pip install virtualenv`, then `virtualenv myckan`, then `. myckan/bin/activate`
* Then `pip install datacats`
* Then `datacats pull`
* then the error `Failed to pull image datacats/web`

**Comment by wardi** [comment]
Would you report this on datacats/datacats instead? This doesn't look like it's related to CKAN

**Comment by sckott** [comment]
Woops, meant to open there, sorry
