### ISSUE TITLE
Error returns when using API to search data based on facet.field

### ISSUE THREAD

**Issue by haoliangyu** [ckan/ckan#2924]
I am using the CKAN APIs of [data.gov](http://www.data.gov/) on my [data visualization project](https://github.com/OpenDataDiscovery/opendatadiscovery.github.io). In brief, I use the API to get the number of datasets for different tags and organizations. Here are the examples:
- get total number
  `http://catalog.data.gov/api/3/action/package_search?rows=0`
- get number by tags
  `http://catalog.data.gov/api/3/action/package_search?facet.field=tags&facet.limit=10&rows=0`

The first one works well for [data.gov](http://www.data.gov/) and many other CKAN instances. But I couldn't use the second request for any other instance except [data.gov](http://www.data.gov/).

I always get an error:

``` json
{
    "help": "...",
    "success": false,
    "error": {
        "facet.field": [
            "Could not parse as valid JSON",
            "Not a list"
        ],
        "__type": "Validation Error"
    }
}
```

I wonder if the searching based on facet.field is a customized function, or a function without general support.

**Comment by amercader** [comment]
The default `facet.field

**Comment by amercader** [comment]
The default

**Comment by amercader** [comment]
The default `facet.field` behaviour is a bit rubbish, you need to always pass a full JSON list:

http://demo.ckan.org/api/3/action/package_search?facet.field=[%22tags%22]&facet.limit=10&rows=0

I guess that our friends at data.gov have applied a patch to make it suport simple values, or a regression has come up between the version data.gov is running and the current one.

**Comment by haoliangyu** [comment]
Confirmed with the developer of [data.gov]. They are using an older version (2.0) of CKAN. Where could I find the legacy API documentation? The links at the API guide seem to be broken.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
