### ISSUE TITLE
After install jetty-solr fails to run on Ubuntu 14.04 LTS 

### ISSUE THREAD

**Issue by lperepol** [ckan/ckan#2939]
I am getting this error: 
JSP support not configured.
### CKAN Version if known (or site URL)

python-ckan_2.5-trusty_amd64.deb
### Please describe the expected behaviour

solr-jetty runs without the "JSP support not configured" error. 
### Please describe the actual behaviour

I was following install instructions here: 
http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html

and testing with 
            lynx  http://localhost:8983/solr/
### What steps can be taken to reproduce the issue?

I was following install instructions here: 
http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html

and testing with 
lynx http://localhost:8983/solr/

**Comment by wardi** [comment]
@lperepol would you update the issue description? which CKAN version? which step of the instructions fails? What does it say when it fails?

**Comment by lperepol** [comment]
I think this is same jetty-solr issue users commented on here: 
https://github.com/ckan/ckan/issues/1651
The some the workarounds I tried all result in other issues.

**Comment by amercader** [comment]
Just to double check, I think there is an issue with the web admin app of Solr not working fine (because of JSP not being configured), but Solr should work fine with CKAN.

We definitely need to find the way to fix the JSP issue, but in the meantime you can use CKAN normally.

**Comment by amercader** [comment]
To test that Solr itself is working you can use `curl http://localhost:8983/solr/select\?q\=\*:\*`

**Comment by mstantoncook** [comment]
@lperepol please try:
```
cd /tmp
wget https://launchpad.net/~vshn/+archive/ubuntu/solr/+files/solr-jetty-jsp-fix_1.0.2_all.deb
sudo dpkg -i solr-jetty-jsp-fix_1.0.2_all.deb
sudo service solr restart
```
It's the basis for a doc change provided in #2966.

**Comment by xapple** [comment]
Same thing for me. Using Ubuntu 14.04 LTS. Got the JSP error. Had to install `tomcat6-solr` instead.

**Comment by peaz** [comment]
@mstantoncook: Your steps worked for me but the last line should be a jetty restart
`sudo service jetty restart`

**Comment by KattaOmkareshwar** [comment]
do we need anything to previously installed for installing solr-jetty
