### ISSUE TITLE
CKAN API documentation

### ISSUE THREAD

**Issue by palcu** [ckan/ckan#2944]
### CKAN Version if known (or site URL)

release-v2.4-final
http://ec2-52-87-202-213.compute-1.amazonaws.com:5000
## Story

I've tried today to create a simple API example for an institution, that only contained creating a dataset and creating a resource for that dataset. However, I've gone through two problems and it took me a lot more time than expected.

First, the [example](http://docs.ckan.org/en/latest/api/index.html#example-importing-datasets-with-the-ckan-api) for creating a new dataset does not work because it's missing the `owner_org` [key](https://github.com/govro/ckan-api-upload-example/blob/master/script.py#L18). I think we should, at least, patch the documentation till https://github.com/ckan/ckan/issues/2789 is ready.

Second, there is the problem with the `URL` field for a resource https://github.com/ckan/ckan/pull/2844. I think we should also patch the [documentation](http://docs.ckan.org/en/latest/maintaining/filestore.html#filestore-api).

Is it okay if I go and change the docs and add to-do items within the corresponding issues?

**Comment by wardi** [comment]
These issues are pretty easy to work around.

You can change your ckan.auth.create_unowned_dataset and ckan.auth.create_dataset_if_not_in_organization settings if you want to allow datasets to be created with no owner_org value, or you can provide the owner's id or name field value as the owner_org value.

Resources need a url to be set until I finish work on #2844, but you can put any value you want in there for now.

Yes please, feel free to update the current docs if it's unclear how to successfully create a dataset with the API.

**Comment by klikstermkd** [comment]
@wardi I'll update the docs for missing `owner_org` in the example for importing datasets with the CKAN API.
