### ISSUE TITLE
Old docs misguiding people

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2946]
I think we should stop showing old CKAN docs on readthedocs - just have the latest (or at least only the last couple of versions that we are releasing patch releases for). I think it confuses more people than it helps.

It's not too bad if you search for something that is still current:

e.g. https://www.google.co.uk/?q=ckan%20install%20source returns results:
- docs.ckan.org/en/latest/maintaining/installing/install-from-source.html
- docs.ckan.org/en/ckan-2.2/install-from-source.html
- docs.ckan.org/en/ckan-1.3.3/maintaining/installing/index.html
- docs.ckan.org/en/ckan-1.8/install-from-source.html
- docs.ckan.org/en/latest/maintaining/installing/install-from-package.html
- docs.ckan.org/en/ckan-2.0/install-from-source.html
- docs.ckan.org/en/latest/maintaining/upgrading/upgrade-source.html

although you just hope people will click the top answer and ignore the rest.

If they search for something CKAN doesn't do any more then it's a problem:
- https://lists.okfn.org/pipermail/ckan-dev/2016-April/009891.html
- https://lists.okfn.org/pipermail/ckan-dev/2016-April/009879.html

I think the latest docs are plenty tbh. It's usually the best source of info, even for older versions, since descriptions are improved over time. We've always written docs with that in mind. And it's rare that we drop features or break anything - backward compatibility rules. But if a feature _has_ been changed/dropped, and someone still wants to read about how it was documented back then, then they have the .rst on their disk to refer to. And I think that is better balance than having people ask about dropped features forever because they came across it on google.

Let's hear views/votes @brew @amercader @wardi:
a) keep all the versions
b) keep latest & last 2 point releases (about what we support with patch releases)
c) keep only the latest

**Comment by corebits** [comment]
I would vote for option B) maintaining the latest release and the currently supported releases. 

I have found it confusing in the past with obsolete documentation versions coming up in searches. Also if the older documentation goes away it could help promote upgrading to current versions.

**Comment by torfsen** [comment]
In general I don't like the idea of removing documentation. I often come across systems with installations of very outdated software (not necessarily CKAN) and even if my only goal is to update them to something more recent I may still need to read the documentation to figure out the meaning of these configuration options that were deprecated and removed long ago...

Would it be possible to display a warning on the outdated documentation instead with a link to the current stable version?

And is there some data w.r.t. which CKAN versions are currently used in production installations? In particular, do the versions from B) cover almost all of these installations?

**Comment by wardi** [comment]
I vote we keep the official releases, but for anything older than a version or two we add a warning banner like the one Django has. Let's purge all the branches that have been built that are still hosted on RTD.

**Comment by davidread** [comment]
@wardi A banner like this?: https://docs.djangoproject.com/en/1.7/

I couldn't see a way to do this in `sphinx_rtd_theme/layout.html` to get this div inserted at the top of the page. We'd need a block in the middle of here:
```
<body class="wy-body-for-nav" role="document">

  <div class="wy-grid-for-nav">
```
I don't fancy doing this with JS as I'd prefer google to see it.

It does seem to work if putting it at the top of the HTML file (above the <head>) but that is very naughty.

Any more ideas?

**Comment by davidread** [comment]
Ah, I found a way. Someone added a suitable block in the master version of the sphinx theme.

**Comment by davidread** [comment]
So I created a modified theme which includes the banner: https://github.com/snide/sphinx_rtd_theme/compare/master...ckan:unsupported-banner?expand=1

And I worked out how to insert it using a submodule: https://github.com/ckan/ckan/commit/05208eef256d6de470c7f70dbe48062f25a0f391

The result is here:
http://docs.ckan.org/en/release-v2.2.3/

Questions:

1. Does this look ok enough to go live for all the old versions? It can be easily improved by editing the theme and rebuilding on readthedocs.

2. RTD identifies versions (in the version selector and the URL) using tags e.g. "ckan-2.2.3" or branches e.g. "release-v2.2.3" and we've always used the former. However adding this change to the old branches, I need to either move the tags (which apparently cause git tag conflicts) or use new tag names like "ckan-2.2.3-unsupported" or tell RTD to use the branch names instead. Does anyone know how bad tag conflicts are for everyone? Any other thoughts from people?

3. Have we agreed what versions are supported? If no-one objects I would just say the most current 3 point releases - currently 2.5.2, 2.4.3 and 2.3.4.

4. 2 people said that we keep all the old versions on RTD (but we will show the warning banner). It still seems a bit mad to me that we still have pre-2.0 versions still there. I did a quick survey of old sites on ckan.org/instances and asked on the list and the only pre 2.0 CKANs I learnt of were a couple of obscure ones in Brazil. But still, we can review it if the warning doesn't deter people from getting confused by old docs.

**Comment by davidread** [comment]
> Let's purge all the branches that have been built that are still hosted on RTD.

@wardi I see your comment about this here: https://github.com/rtfd/readthedocs.org/issues/1325#issuecomment-118363654
and there doesn't seem to be an progress in this or related issues. HOWEVER there is a "Clean" button next to about 40 inactive branches here: https://readthedocs.org/projects/ckan/versions/
and I pressed it for "1197-rtd-fi" and it did turn this page from docs to a 404:
https://ckan.readthedocs.org/en/1197-rtd-fix/changelog.html
So I can go and "Clean" those inactive branches, if that's ok with you?

**Comment by wardi** [comment]
@davidread removing the old branches sounds good to me. Is marking the last three releases as supported what we decided? I can't remember how that meeting ended.

**Comment by davidread** [comment]
Inactive branches are now cleaned.

**Comment by torfsen** [comment]
Nice! I would also add a link to the front page of the latest version's documentation.

**Comment by amercader** [comment]
hey @davidread thanks for working on this, I agree we need to sort it out, my suggestion would be to

* keep old versions up to 1.8, but with a big banner:
  - for unsupported versions (more on this later): "This version is no longer supported, please upgrade"
  - [optional] for supported versions: "This is not the latest release"
* Make the latest stable release the one that people get by default
* Show a banner on master "This is a development version, etc"

See below for comments:

> http://docs.ckan.org/en/release-v2.2.3/
> 1 - Does this look ok enough to go live for all the old versions? It can be easily improved by editing the theme and rebuilding on readthedocs.

It is a bit annoying that the banner clips the content, and you can't read it on mobile. Where's the code for this

> 2 - RTD identifies versions (in the version selector and the URL) using tags e.g. "ckan-2.2.3" or branches e.g. "release-v2.2.3" and we've always used the former. However adding this change to the old branches, I need to either move the tags (which apparently cause git tag conflicts) or use new tag names like "ckan-2.2.3-unsupported" or tell RTD to use the branch names instead. Does anyone know how bad tag conflicts are for everyone? Any other thoughts from people?

Changing git tags is bad, and changing URLs on each patch release is bad as well. What about if we build the docs from branches that always run the latest patch release? That way docs can be updated if necessary without breaking URLs or messing with tags. We already have these branches, they are called `release-v2.X-latest` and are updated after each patch release. This doesn't look too good on a URL though (http://docs.ckan.org/en/release-v2.5-latest) and the `latest` bit might be confusing. Perhaps we can change them to `release-v2.5.x` or simply `2.5`.

> 3 - Have we agreed what versions are supported? If no-one objects I would just say the most current 3 point releases - currently 2.5.2, 2.4.3 and 2.3.4.

That is the same that I suggested back in January, with a support period of 18 months, which will give us:

| Version | Release Date | End of support date
|------------- | ---------------------- | -------------- 
| CKAN 2.5 | December 2015 | June 2017
| CKAN 2.4 | July 2015 | January 2017
| CKAN 2.3 | March 2015 | September 2016
| CKAN 2.2 | February 2014 | No longer supported
| CKAN 2.1 | August 2013 | No longer supported
| CKAN 2.0 | May 2013 | No longer supported

If everyone is happy with this it'd good to display prominently in the docs and/or website

> 4 - 2 people said that we keep all the old versions on RTD (but we will show the warning banner). It still seems a bit mad to me that we still have pre-2.0 versions still there. I did a quick survey of old sites on ckan.org/instances and asked on the list and the only pre 2.0 CKANs I learnt of were a couple of obscure ones in Brazil. But still, we can review it if the warning doesn't deter people from getting confused by old docs.

I think that pre-2.0 versions don't cause that much confusion but I don't have any strong feeling about keeping them or not.

**Comment by torfsen** [comment]
One small addition since this we're starting to talk about official support times: Fixed support intervals (e.g. 18 months) only make sense if you have regular release intervals, too. I wouldn't use a software that tells me "This version will only be supported X months, but we can't tell you when the next release is".

If you can't promise a fixed release interval I suggest you use a more flexible support limit, e.g. "Supported are the current release, the previous two minor releases and any version released in the last 18 months" (note that only supporting "the current release and the previous two minor releases" is bad as well, since that leads to a very short support span if you're releasing frequently).

**Comment by wardi** [comment]
@torfsen all of this is best-effort and based on contributions from a number of entities that are supporting CKAN development. We're just trying to communicate what we are able to support given our available resources. As you might expect, we're interested in spending as much of our time as possible on improvements and new features for the latest version of CKAN.

Anyone is free to support any version of CKAN as far back as they like, and we're happy to point users of those older versions to that maintainer's fork. This might be a good thing for one of the commercial CKAN companies offer as a paid service as an alternative to upgrading sites, which can be very expensive.

**Comment by torfsen** [comment]
@wardi: I totally understand that and didn't want to devalue any of your efforts (sorry if my wording left that impression, not a native speaker). I just think that support cycles are an important topic for many people and should be considered carefully.

**Comment by mstantoncook** [comment]
Can I ask why the current docs refer to '2.6.0a'? 

<img width="768" alt="screen shot 2016-04-18 at 9 17 24 am" src="https://cloud.githubusercontent.com/assets/14989121/14590769/9e412d92-0546-11e6-848d-4874da774d13.png">

Am I correct in thinking it should really be '2.5.2' and additionally a 'master'? I have found that 2.6.0a confuses people (think that 2.6.X has been released).

**Comment by davidread** [comment]
@mstantoncook it's a good point, but separate - would you mind opening a separate issue for it?

**Comment by davidread** [comment]
* [ ] Banner look ok on mobile
* [ ] Stop the banner covering up a bit of the page
* [ ] Link to latest docs

**Comment by davidread** [comment]
I'm just noting the commands I was using for this, since this work is parked for the time being:
```
git submodule add -b unsupported-banner https://github.com/ckan/sphinx_rtd_theme doc/_themes/sphinx-theme-rtd-unsupported
git submodule init
git submodule update

vim docs/conf.py
sys.path.append(os.path.abspath('_themes'))
html_theme_path = ['_themes/sphinx-theme-rtd-unsupported']
html_theme = 'sphinx_rtd_theme'

python setup.py build_sphinx
git commit -a -m '[#2946] Docs marked as unsupported.'
git push -u origin release-v2.2.3
https://readthedocs.org/projects/ckan/builds/ # and trigger the build
```

**Comment by Zharktas** [comment]
Hi,

We got issue report in our instance (vrk-kpa/api-catalog#3) which has broken api docs link in templates since only latest point releases have active documentation. We are currently running ckan 2.5.1 and the api docs link is linking to http://docs.ckan.org/en/ckan-2.5.1/api/ which gives permission denied since 2.5.2 is the latest point release. It should be also fixed in templates so that the links actually would be working even though the latest bug fix release has not been installed.

**Comment by davidread** [comment]
Yeah, I think on reflection I shouldn't have got rid of the docs for old point releases.

However we strongly discourage using versions like 2.5.1 without the security patches, so maybe that's the easiest and best fix for you and any others?

**Comment by Zharktas** [comment]
I agree that point releases should be installed, but there will always be cases where they aren't installed right after the release. Maybe the api docs link in templates should be pointing to something like docs for 2.4 or 2.5 or what ever the installed version is? The api won't be changing in patch releases anyway.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
