### ISSUE TITLE
Datasets not listed in group feed

### ISSUE THREAD

**Issue by martinburchell** [ckan/ckan#2955]
### CKAN Version if known (or site URL)
2.5.1

### Please describe the expected behaviour
/feeds/group/group-name.atom should list datasets

### Please describe the actual behaviour
/feeds/group/group-name.atom does not list any datasets. My understanding is that this should be the same as /feeds/custom.atom?groups=group-name

Some public examples:
https://data.hdx.rwlabs.org/feeds/group/nepal-earthquake.atom
https://data.hdx.rwlabs.org/feeds/custom.atom?groups=nepal-earthquake

http://demo.ckan.org/feeds/group/data-explorer.atom
http://demo.ckan.org/feeds/custom.atom?groups=data-explorer

### What steps can be taken to reproduce the issue? 
Create a dataset in a group
Go to
/feeds/group/name-of-group.atom

**Comment by amercader** [comment]
@martinburchell Fix for this is in #2960

Also please upgrade to 2.5.2 :)
