### ISSUE TITLE
Current documentation is at version 2.6.0a NOT 2.5.2

### ISSUE THREAD

**Issue by mstantoncook** [ckan/ckan#2967]
### CKAN Version if known (or site URL)

Not applicable
### Please describe the expected behaviour

The 'current' docs should be **2.5.2** NOT 2.6.0a (which doesn't exist as a [release](https://github.com/ckan/ckan/releases)).
#### As indexed by Google:

<img width="755" alt="screen shot 2016-04-18 at 11 16 49 pm" src="https://cloud.githubusercontent.com/assets/14989121/14605401/be37bdda-05bb-11e6-8a1f-1c9f89453e1e.png">
#### 'Version' dropdown/options:

<img width="519" alt="screen shot 2016-04-18 at 11 18 23 pm" src="https://cloud.githubusercontent.com/assets/14989121/14605454/fd144ca8-05bb-11e6-9af7-225a3411095a.png">
### What steps can be taken to reproduce the issue?

As above. From http://read-the-docs.readthedocs.org/en/latest/versions.html: "Read the Docs supports multiple versions of your repository. On the initial import, we will create a latest version. This will point at the default branch for your VCS control: master, default, or trunk.

We also create a stable version, if your project has any tagged releases. stable will be automatically kept up to date to point at your highest version".

I'm still trying to workout how stable can replace current...

**Comment by wardi** [comment]
I've updated the default to point to the last released version. We'll have to do this on an ongoing basis
