### ISSUE TITLE
Display time is not properly shown on the front-end (-1 day ago)

### ISSUE THREAD

**Issue by aitormagan** [ckan/ckan#2970]
### CKAN Version if known (or site URL)

CKAN 2.5 and the current `master` version
https://data.lab.fiware.org
### Actual behaviour

Display time is not properly shown on the front-end. Just after creating a resource the front-end shows "-1 day ago" for at least one hour. I have tried to modify the value of `ckan.default_timezone` but nothing changes. 
### Expected behaviour

The front-end to display the time information properly. Just after creating a resource, "some seconds ago" must be shown (as it did in the past).
### What steps can be taken to reproduce the issue?

This is just an example. The error can be reproduced with any operation when the time is saved and displayed later (updating an organization, creating a dataset, ...)
1. Create an organization
2. Go to your Activity Stream
3. Something like this will appear "USER created the organization ORGANIZATION -1 days ago"

**Comment by aitormagan** [comment]
It seems to be related with https://github.com/ckan/ckan/issues/2882

**Comment by jrods** [comment]
Is anybody currently working on this?

**Comment by wardi** [comment]
@jrods no, do you have time to submit a PR?

**Comment by fanderegg** [comment]
My workaround for this is to set the server time to UTC and not set 
ckan.display_timezone or ckan.default_timezone in the config. This seems to fix the problem.

**Comment by amercader** [comment]
This was fixed by #3240
