### ISSUE TITLE
Solr url change in test-core.ini breaks tests in extensions

### ISSUE THREAD

**Issue by brew** [ckan/ckan#2972]
Many extensions use ckan's `test-core.ini` as the base for automated testing. A recent change to `test-core.ini`[1] changes the `solr_url` setting to assume a separate solr core is available in the testing environment.

Extensions now fail if they use `test-core.ini` from master because the testing environment hasn't been set up to use a separate core, e.g. https://travis-ci.org/ckan/ckanext-showcase/jobs/122704917

[1] https://github.com/ckan/ckan/commit/536a98b0f4d17b37de9267db4f62ac927ed3fa71#diff-28d7d03245b4b1b19e2acab0c903dc29R32

**Comment by wardi** [comment]
I think we should update the extension tests to set up a separate core. Modern versions of solr no longer support single-core operation, and we will want to upgrade one day. Here's what I'm doing in ckanext-scheming: https://github.com/ckan/ckanext-scheming/blob/master/circle.yml#L35 This uses the new script provided for setting up solr, and it works for testing against 2.3, 2.4, 2.5 and master.

**Comment by brew** [comment]
How does it work against CKAN test-core.ini previous to this change (older than current master)?

**Comment by wardi** [comment]
I update the test-core.ini https://github.com/ckan/ckanext-scheming/blob/master/.circleci-matrix.yml#L10 so it's always got the same solr url, but I suppose I could just copy that value into my own test.ini instead, that would be simpler.

**Comment by TkTech** [comment]
```
sudo su - solr -c "/opt/solr/bin/solr create -c ckan_test -d <config_directory>"
```

`ckan_test` is the name of the core, `confi_directory` is a directory (ideally the example folder in CKAN) to copy in place of the cores config.

**Comment by davidread** [comment]
I didn't work out where Travis installs its SOLR and how to make it multicore. But I fixed my extensions' build by simply running tests in the default SOLR core, by adding a single line to `bin/travis-build.bash`:

    sed -i -e 's/solr_url.*/solr_url = http:\/\/127.0.0.1:8983\/solr/' ckan/test-core.ini

e.g.
https://github.com/ckan/ckanext-issues/compare/74745...travis-multicore-solr

which is probably slightly easier than adding a new .ini file just for travis tests https://github.com/ckan/ckanext-showcase/commit/e482cc4c9742878581dbbbcf15d0f5c61309d0dd
