### ISSUE TITLE
Resources Metadata not Indexed

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#2975]
### CKAN Version if known (or site URL)
2.5 http://demo.ckan.org/

### Please describe the expected behaviour
I'm expecting that when I search something, metadata of the resources where indexed and custom_text as well

### Please describe the actual behaviour
Actualy, CKAN is indexing only the name of the resources.

### What steps can be taken to reproduce the issue? 
Not an issue, probably i'm doing something wrong.

**Comment by yingqiaogit** [comment]
@deinok I did some experiments using the demo site. It seems that the name and the description of the resources are indexed. Do you want to add the other fields (i.e., url and format) to the indexes?

**Comment by deinok** [comment]
I meen the _extras fields

**Comment by yingqiaogit** [comment]
@deinok The extras fields are indexed already in CKAN (ref: https://github.com/ckan/ckan/pull/1732). I created a scenario and tested this function successfully just now. The steps are as follows: 
1) add ckan.extra_resource_fields = <interested_field> in the .ini
2) through API, package_create with a resource containing the <interested_field>:<value>
3) through API, package_search with a query param as q=res_extras_<interested_field>:<value> 

Is it what you want?

**Comment by deinok** [comment]
@yingqiaogit that was exactly what i want, thanks for your help. Issue Closed

**Comment by yingqiaogit** [comment]
@deinok You are welcome.
