### ISSUE TITLE
Resource Recline View Bug - shows 404 Error, Once Language is Changed

### ISSUE THREAD

**Issue by HilariousGil** [ckan/ckan#2976]
### CKAN Version
2.5.2, 2.5.3b

### Expected behaviour
The Resource Recline View should be equal and be available. The language change should not interfere with it.

### Actual behaviour
Shows the translated page but in the frame where it should be the Recline View, there is a Page with a 404 Error.

### Reproduce the issue
##Quick and easy
(Works) 1 - http://demo.ckan.org/dataset/car-data-set/resource/9e1a2f16-7511-4132-b840-d0816476c662
(NOT Work) 2 - http://demo.ckan.org/nl/dataset/car-data-set/resource/9e1a2f16-7511-4132-b840-d0816476c662

##Normal
1 - Go to the Datasets and chose a dataset with csv resource for example
2 - Choose the resource
3 - Once you are in the Resource view (recline view should be working), change the language to any other language.
4 - You Get your 404.

Extra:
5 - If you do some Inception-like exploring on the 404 error page and go to ckan->datasets->same dataset-> change language. You are able to see the resource recline view working in any language.

**Comment by amercader** [comment]
@HilariousGil This was caused by a misconfigured `ckan.site_url` value (it didn't match the one actually used in the domain).

Should be working now, thanks for flagging it.
