### ISSUE TITLE
Provide support for background tasks

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2977]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=33227756)](https://www.bountysource.com/issues/33227756-provide-support-for-background-tasks?utm_source=33227756&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**If you are interested in the bounty, please mark yourself as 'working on it' at [https://www.bountysource.com/issues/33227756-provide-support-for-background-tasks](https://www.bountysource.com/issues/33227756-provide-support-for-background-tasks)**

Currently running background tasks (sending email and so forth) is a bit too complicated.  

There is an incomplete PR at https://github.com/ckan/ckan/pull/2706 which introduces support for this using python-rq. There is also more discussion at https://github.com/ckan/ideas-and-roadmap/issues/66
### CKAN Version if known (or site URL)

Based off `master`
### Please describe the expected behaviour

Support as per Ideas issue and PR 
### Please describe the actual behaviour

PR to be completed, with basic documentation and tests.

**Comment by GildedHonour** [comment]
@rossjones , how can I work on it, should I just start and then push a PR? What if some else will start working on it at the same, will only one of us get the bounty?

**Comment by rossjones** [comment]
I think you need to go to BountySource ( https://www.bountysource.com/issues/33227756-provide-support-for-background-tasks ) and mark yourself as working on it ... will update the original message to warn people.

**Comment by torfsen** [comment]
@GildedHonour Are you still working on this? BountySource [says so](https://www.bountysource.com/issues/33227756-provide-support-for-background-tasks) but it also says you expected to be done by end of May.

**Comment by GildedHonour** [comment]
Sorry, no.

Sent from my ASUS

-------- Mensaje original --------
De:Florian Brucker <notifications@github.com>
Enviado:Mon, 11 Jul 2016 21:18:07 +0800
Para:ckan/ckan <ckan@noreply.github.com>
Cc:Alex Maslakov <me@gildedhonour.com>,Mention <mention@noreply.github.com>
Asunto:Re: [ckan/ckan] Provide support for background tasks (#2977)

**Comment by torfsen** [comment]
I've started working on this, see #3165. Note that I'm not interested in the bounty.

**Comment by rossjones** [comment]
@torfsen It'd be cool if you did take the bounty, you could always give it to charity, or attach it as a bounty elsewhere?

**Comment by torfsen** [comment]
@rossjones I'm already being paid for the work that I'm doing here through other means, and accepting the bounty would probably be a lot of work from a legal perspective. Feel free to give it to charity or re-assign it to another issue!

**Comment by deinok** [comment]
@rossjones  @torfsen Hi, in my job im working on a scrapper inside CKAN that reads datasets from other webpages.

If you want and my boss let do it, i can try to give it opensource, or at least the part of the background task

Also, I can't take the bounty and Im happy with give it to charity or for another task

**Comment by rossjones** [comment]
@deinok This sounds like it might be a better fit for https://github.com/ckan/ckanext-harvest than for CKAN core.  I've created an idea ticket at https://github.com/ckan/ideas-and-roadmap/issues/184 so feel free to claim it there.  

As an aside, because of the CKAN licence (AGPL) if you writes scrapers inside CKAN, you are required to release it under the same open source licence.  

If nobody wants the bounty, I'll donate it to CKAN Assoc to help someone with travel costs to the next CKANCON :)

**Comment by rossjones** [comment]
https://github.com/ckan/ckan/pull/3165 was merged, so closing this. Thanks @torfsen
