### ISSUE TITLE
Group pagination does not preserve sort order

### ISSUE THREAD

**Issue by martinburchell** [ckan/ckan#2981]
### CKAN Version if known (or site URL)
2.5.2

### Please describe the expected behaviour
On group page, eg http://demo.ckan.org/group the pagination links at the foot of the page should preserve the sort order

### Please describe the actual behaviour
The sort order is set to the default

### What steps can be taken to reproduce the issue? 
Create 22 groups (currently available at http://demo.ckan.org/group)
Go to the group page
Change the sort order to "Name Descending"
Go to page 2

The group on page 2 should be the first alphabetically - instead it's the last

This has already been fixed for organizations - see https://github.com/ckan/ckan/pull/2141 and https://github.com/ckan/ckan/pull/2153

**Comment by amercader** [comment]
@martinburchell That makes sense, do yo want to send a PR with the group fixes you mention?

**Comment by martinburchell** [comment]
Yes if I get time I will. Also happy for others to pick up.
