### ISSUE TITLE
handle error on download cancel/failure

### ISSUE THREAD

**Issue by dhardy** [ckan/ckan#2996]
### CKAN Version if known (or site URL)
1.16.1;0;g2e91715

### Please describe the actual behaviour
Clicking 'cancel' while CKAN is downloading a mod, or if a download fails, brings up a generic 'error occured' box and messes up the GUI: it appears that the mod has been installed/updated when it hasn't. Fortunately restarting CKAN fixes this, but it shouldn't be necessary.

### What steps can be taken to reproduce the issue? 
1.  Click to install a new mod, apply, then cancel while download is in progress

**Comment by dhardy** [comment]
Uh, sorry about this!

**Comment by TkTech** [comment]
Happens often enough that we have a label for it. Worry not.
