### ISSUE TITLE
[DataStore] Not found: Resource {0} was not found, but work fine use http GET

### ISSUE THREAD

**Issue by lincecumHao** [ckan/ckan#2999]
### CKAN Version if known (or site URL)
2.6

### Please describe the expected behaviour
CKAN use this url to get data from MySQL I connect via ckanext-dataproxy
[http://192.168.109.128:5000/api/action/datastore_search?resource_id=0cda49c7-4ce3-47fc-b382-0f566fd646fa&limit=5]()

but return 

`{"help": "http://192.168.109.128:5000/api/3/action/help_show?name=datastore_search", "success": false, "error": {"message": "Not found: Resource \"0cda49c7-4ce3-47fc-b382-0f566fd646fa\" was not found.", "__type": "Not Found Error"}}`

But I try use

[http://192.168.109.128:5000/api/3/action/datastore_search?resource_id=0cda49c7-4ce3-47fc-b382-0f566fd646fa&limit=5]()

and it work find.

The different between 2 url is a **/3** version description in url, how can I fixed this?

**Comment by amercader** [comment]
@lincecumHao This is a ckanext-dataproxy issue as they are overriding the core `/api/3/action/datastore_search` route but not the `api/action/datastore_search` one:

https://github.com/cphsolutionslab/ckanext-dataproxy/blob/master/ckanext/dataproxy/plugin.py#L33:L37

They should probably just override the core `datastore_search` action via `IActions` instead.

In any case please file an issue on that repo as this is not a core issue.
Cheers.
