### ISSUE TITLE
Unqualified URLs contain both WSGIScriptAlias and ckan.root_path

### ISSUE THREAD

**Issue by MrkGrgsn** [ckan/ckan#3001]
### CKAN Version if known (or site URL)
2.3.4 Not tested in other recent versions yet

### Please describe the expected behaviour
Unqualified URLs returned by `ckan.lib.helpers._add_i18n_to_url()` should contain only `ckan.root_path`.  

This is based on the assumption the `ckan.root_path` _must_ contain `WSGIScriptAlias` to provide the proper environment information for generating URLs when running in either WSGI or from the command line.

### Please describe the actual behaviour
Unqualified URLs contain both WSGIScriptAlias and ckan.root_path.

### What steps can be taken to reproduce the issue? 
Configure CKAN with
1. `WSGIScriptAlias /data ..`
2. `ckan.root_path = /data`

Open the website. Generated URLs will start with the prefix `/data/data'.

**Comment by MrkGrgsn** [comment]
I've created a [patch for 2.3.4|https://gist.github.com/MrkGrgsn/37876a279565da07de2bb8c6b143929b]. It's a work in progress. It needs new tests (for unqualified URLs and to ensure both WSGI and command line environments are test) and the documentation for ckan.root_path should be updated. I haven't tested in master, 2.4 or 2.5 but I suspect they will all be affected.

**Comment by wardi** [comment]
@MrkGrgsn have you tried this on master? https://github.com/ckan/ckan/pull/2998 went in recently

**Comment by MrkGrgsn** [comment]
Thanks @wardi I missed that one. I'll check master and confirm the fix.

**Comment by TkTech** [comment]
@MrkGrgsn Any update?

**Comment by MrkGrgsn** [comment]
I've found some time for a quick look at master (05eb241). I'm having trouble just getting the a fresh site to load with a root_path serving it with httpd 2.4 and mod_wsgi.  The site will load if I configure it to run from the site root so I think the server setup is okay.  I'll try to get some more details soon.

**Comment by MrkGrgsn** [comment]
I can't replicate this in up-to-date master but I needed the fix from #3090 to login.
What's the plan for backporting #2998 to 2.3 and 2.4?

**Comment by wardi** [comment]
I've flagged them for backporting, but IIRC there are a few other related PRs. I'll make a note of all the commits tomorrow
