### ISSUE TITLE
Activity log doesn't show resource creation message, if dataset has multiple resources

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#3003]
### CKAN Version if known (or site URL)

Tested with 2.5.1 and 2.5.2
### Please describe the expected behaviour

Creating multiple resources in dataset should create "{user} added the resource {resource} to the dataset {dataset}" message to the activity log from each of them.
### Please describe the actual behaviour

Resources after the first one appear as "{user} updated the dataset {dataset}" due to the that the previous resource gets new revision.

Created a example in demo.ckan.org:

http://demo.ckan.org/dataset/activity/activity-test

where activity_detail_list returns multiple updates when resource has been added:

http://demo.ckan.org/api/3/action/activity_detail_list?id=97d967c3-ba8a-4f42-be58-a21c01cbc115
http://demo.ckan.org/api/3/action/activity_detail_list?id=7748f887-7ff4-4594-8069-9299c9e9144a
### What steps can be taken to reproduce the issue?

Create dataset
Add multiple resources.
Check activity log

**Comment by amercader** [comment]
> Resources after the first one appear as "{user} updated the dataset {dataset}" due to the that the previous resource gets new revision.

Can you clarify what do you mean with "the previous resource gets new revision" and how this affects the activity list? 

In any case as it is not a critical issue and it's unlikely that the core devs will find time to look into it, if you could provide a patch that would be great

**Comment by Zharktas** [comment]
At least i think it creates a new revision since revision id changes in activity details, I haven't actually found out the reason for this. I have to discuss with our client about how critical issue this is, if we can allocate time to fix it.

**Comment by Zharktas** [comment]
Reason for this might be in 
https://github.com/ckan/ckan/blob/master/ckan/lib/activity_streams_session_extension.py#L28
since this function detects two or more changed packages every now and then.
 
Either database is too slow for this, or there is missing database commit somewhere.

I'm not exactly sure if this functionality is still needed or could it be done with the api as it is done in organizations and users, but this could use a rewrite anyway.

This is not critical for our client, so we won't be making a PR, at least for now.

**Comment by wildcatzita** [comment]
@amercader , is it still needed to be done?

**Comment by amercader** [comment]
@wildcatzita This is not a priority, so unless it's an obvious easy fix I would focus on other issues.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
