### ISSUE TITLE
Encrypt IRC channel for Travis to stop forks spamming the channel

### ISSUE THREAD

**Issue by Psykar** [ckan/ckan#3009]
https://docs.travis-ci.com/user/encryption-keys/

As mentioned in
https://github.com/travis-ci/travis-ci/issues/1094

eg:
https://github.com/mozilla/build-tools/commit/c13a297

Cannot commit a PR, because this requires access to the ckan Travis account to implement.

**Comment by amercader** [comment]
We switched to [CircleCI](https://circleci.com/gh/ckan/ckan) a while ago, I guess we should just delete the .travis.yml file

**Comment by Psykar** [comment]
That I can open a PR for!
