### ISSUE TITLE
Default view is re-added when removed before DataStore upload is complete

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3011]
I'm doing the following via the API on a CKAN 2.5.2 installation that has DataStore + DataPusher enabled:

1. Create a CSV resource
2. Remove the default `recline_view`
3. Add a new `recline_grid_view` view

I'd expect the resource to end up with a single view (the one I added in step 3). However, it ends up with *two* views: the one I created and a *new* default view (ID is different from the original default view).

It seems that the default view is added again once the data has been uploaded to the DataStore by the DataPusher. If steps 1-3 are done quickly enough (before the upload to the DataStore has completed) then the resource has only the intended `recline_grid_view`, which at that point shows an error (because the data is not yet available). As soon as the data is available (i.e. as soon as the error is gone after a reload) the resource has gotten an additional `recline_view`.

Here's a small script to demonstrate the problem:
```python
ckan = ckanapi.RemoteCKAN(CKAN_URL, apikey=API_KEY)

res_dict = ckan.action.resource_create(package_id=PKG_ID, url=CSV_URL,
                                       name='Test', format='CSV')
view_dicts = ckan.action.resource_view_list(id=res_dict['id'])
for view_dict in view_dicts:
    ckan.action.resource_view_delete(id=view_dict['id'])
ckan.action.resource_view_create(resource_id=res_dict['id'], title='My View',
                                 view_type='recline_grid_view')

# Uncomment to make assertion fail
#import time
#time.sleep(10)

assert len(ckan.action.resource_view_list(id=res_dict['id'])) == 1
```
If you uncomment the `sleep` lines (to wait until the data is in the DataStore) then the assertion fails.

**Comment by amercader** [comment]
This is another side-effect of #2234 (which I'm very much starting to regret to ever have implemented). Essentially we added a call to `resource_patch` on `datastore_create` to set the `datastore_active` extra on the resource.

So what happens is:

* Resource is created, default views are created
* You delete the default view you don't want
* In the meantime, DataPusher is doing its thing
* When the data is uploaded to the DataStore, `datastore_create` calls `resource_patch` (to set up the `datastore_active` extra) which calls `resource_update` which calls `package_update` which calls `package_create_default_resource_views` and recreates the view.

@wardi I know you hate it but the only thing I can think of is passing a `create_views = False` entry on the context that ends up in `package_update` and avoids the default views creation.

@torfsen I know it's not ideal but on the meantime you can delete the extra view via the API if you are doing it as part of a script

**Comment by wardi** [comment]
So datapusher is deleting and recreating the datastore table. That shows up as a new table so the default views are created, or are we calling package_create_default_resource_views on every package_update?

**Comment by amercader** [comment]
> are we calling package_create_default_resource_views on every package_update?
This. It has no relation with the DataPusher creating or dropping tables, other than it triggers an update when it imports data to the DataStore

**Comment by wardi** [comment]
So.. anyone editing a dataset will cause all the default resource views to reappear too, right?

We need something like a white-out for resource views that have been removed so they don't get re-added, or we just need to me more selective about when that code is run, not on every package_update

**Comment by amercader** [comment]
You are right.
Neither of the two options are easy as things stand right now. Views are not marked as deleted on the DB, they are just removed entirely so the white-out option is probably the hardest.

Thinking on when we want default views to be created, I think the most common cases are:

* Creating a package (if resources are provided, ie creating it via the API or a custom combined form)
* Creating resource on an existing package (like on the default UI)
* When we finish pushing data to the DataStore (DataPusher does that now)

So just on `package_create`, `resource_create` and `datapusher_hook`.

If we only cover these cases, and not any updates we will miss situations like people changing the format of a resource and new views for that format not appearing, but that might be preferable to the current behaviour.

**Comment by wardi** [comment]
:+1: That sounds like a simpler solution.

**Comment by amercader** [comment]
@torfsen Do you have time to work on patch along those lines?

**Comment by amercader** [comment]
@k-nut this is also a good one to get an introduction about how DataPusher / DataStore / Resource views work

**Comment by torfsen** [comment]
@amercader Sorry, I'm currently busy with other stuff.

As a workaround I'm currently polling [`datastore_info`](http://docs.ckan.org/en/latest/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_info) until the resource has been uploaded to the datastore before deleting the default views.

**Comment by k-nut** [comment]
@amercader I am taking a look at this now.

**Comment by k-nut** [comment]
I pushed some changes to my branch now. https://github.com/ckan/ckan/compare/master...k-nut:3011-do-not-always-create-default-views

Essentially I removed the view creation from the `update.py` and added it to the `resource_create` function. 

To be honest though I am not entirely sure what the parameters that are passed to `add_views_to_resource` should contain and if I am passing the right ones. The tests seem to pass with the current configuration. 

But with those changes the assertion in the script provided by @torfsen does not fail anymore and only the wanted view is created.

**Comment by amercader** [comment]
@k-nut Rather than calling `ckan.lib.datapreview` functions directly in [here](https://github.com/ckan/ckan/compare/master...k-nut:3011-do-not-always-create-default-views#diff-19f9f59b2186e64b6eb3afab61a557a7R316) call the `resource_create_default_resource_views` action a similar way that was done on `package_update`, passing the resource dataset dicts in the data_dict:

```python
logic.get_action('resource_create_default_resource_views')(
    {'model': context['model'], 'user': context['user'],
     'ignore_auth': True},
    {'resource': resource, 'package': updated_package_dict})

```

This way people can override the action in their extensions if they want to modify the behaviour. And add a couple of tests on resource creation to replace the ones deleted for package update :+1:

**Comment by k-nut** [comment]
@amercader as mentioned in the PR already there already is the [`test_default_views_created_on_resource_create`](https://github.com/k-nut/ckan/blob/master/ckan/tests/lib/test_datapreview.py#L339) test. Do you think this needs more tests?

**Comment by amercader** [comment]
No, sorry I missed that. Existing tests are fine

**Comment by k-nut** [comment]
It seems like the tests for the recline view extension are now failing because the `datastore_create` does not create the default views anymore?! https://circleci.com/gh/k-nut/ckan/9

**Comment by k-nut** [comment]
Which is weird because it is calling `resource_create` https://github.com/ckan/ckan/blob/master/ckanext/datastore/logic/action.py#L96 Maybe something is wrong with the test?

**Comment by k-nut** [comment]
So the problem in the test seems to be that `can_view` is called on `ReclineView` but this goes into the last `else` branch and returns `False`. That leads to the plugin not beeing discovered as a view and not being registered consequently.

**Comment by k-nut** [comment]
This can be fixed by specifying the format of the resource in the test like this. 
```
'resource': {'package_id': dataset['id'], 'format': 'csv'},
```
I am not sure if it is fine to change the test here or if the test points us to something being actually wrong with the code...
