### ISSUE TITLE
"Data API" button disappears on resource page after empty update

### ISSUE THREAD

**Issue by NicolaiMogensen** [ckan/ckan#3012]
ckan_version: 2.5.2

### Please describe the expected behaviour
When updating a resource without changing any fields, url or description, the green "Data API" button should still be there, because the data is still in the datastore (And API calls of this type confirms that it still is). Not sure if it is expected of the datapusher to trigger its update or not. 

### Please describe the actual behaviour
The green "Data API" button disappears, as if data is now removed from the datastore for the particular resource. It would seem like CKAN thinks this triggers the datapusher hook, even though it does not (logs confirm it nothing happens).

### What steps can be taken to reproduce the issue? 
Push .CSV file to the datastore using the web interface, then update the resource using either the `resource_update` API call or the web interface, without changing anything.

I'm curious to see if i'm the only one with this issue, i can reproduce over several CKAN installations running 2.5.2. If i need to post this in the datapusher github issue tracker instead, close this and i will post it there instead.

**Comment by amercader** [comment]
@NicolaiMogensen this is indeed a bug.

The "Data API" button relies on the `datastore_active` resource extra being present and True. When editing via the frontend (or the API) this field is not passed and so it's dropped from the db. We need to persist the value when updating if the resource already has it and it's not provided.

PR incoming

**Comment by amercader** [comment]
Fix in #3020

**Comment by NicolaiMogensen** [comment]
@amercader That was fast! Thanks for correcting this, as it broke the buttons on all resources when doing `resource_update` through some automated jobs.
