### ISSUE TITLE
Fails to download a mod I'm not choosing to install?

### ISSUE THREAD

**Issue by Evochron** [ckan/ckan#3013]
Plasma Window

Installing mods using ckan

Fails to download - "https://github.com/Signatum/SXT/releases/download/v25.1/SXT25pre.zip"
even though i do not select to install that in the suggested mods.

Every time i install
 * Active Texture Management - X86 - Basic 5-0(cached)
 * Advanced Jet Engine v2.6.1(cached)
 * B9 Aerospace Procedural Parts - Fork 2.1(cached)
 * Distant Object Enhancement v1.6.4(cached)
 * Distant Object Enhancement Real Solar System config v1.6.4(cached)
 * DMagic Orbital Science 1.2(cached)
 * FASA - Frizzank's Aeronautics and Space Administration 1:5.44(cached)
 * Ferram Aerospace Research 3:0.15.5.7(cached)
 * Filter Extensions - Default Configuration 2.4.1.3(cached)
 * Firespitter v7.1.5(cached)
 * Firespitter Core v7.1.5(cached)
 * ForScience Continued! 1.1.0(cached)
 * Magic Smoke Industries Infernal Robotics v0.21.4(cached)
 * Kerbal Attachment System 0.5.5(cached)
 * Kerbal Engineer Redux 1.0.19.4(cached)
 * Kerbal Joint Reinforcement v3.1.4(cached)
 * Kerbal Inventory System 1.2.6(cached)
 * KSP AVC 1.1.5.0(cached)
 * KW Rocketry 2.7.0-community(cached)
 * KW Rocketry - Community Fixes 0.4.9(cached)
 * MechJeb 2 2.5.6.0(cached)
 * MechJeb Modules for FAR 1.0.0(cached)
 * Module Manager 2.6.20(cached)
 * Procedural Wings 0.10.1(cached)
 * Procedural Fairings v3.15(cached)
 * Procedural Fairings - For Everything! v0.1.1(cached)
 * Procedural Parts v1.1.11(cached)
 * RCS Build Aid 0.7.7(cached)
 * RCS Sounds 4.4(cached)
 * RealChute Parachute Systems 1.3.2.7(cached)
 * Real Fuels rf-v10.8.5(cached)
 * RealHeat v3(cached)
 * Realism Overhaul v10.9.6(cached)
 * Real Plume 2:v10.5.1(cached)
 * Real Scale Boosters 0.9(cached)
 * Real Solar System v10.6.2(cached)
 * RemoteTech v1.6.9(cached)
 * Soviet Probes v1.9(cached)
 * Soviet Rockets - R7/Proton/Zenit Rockets v1.7(cached)
 * US Probes Pack v0.47(cached)
 * US Rockets v0.3(cached)
 * Realistic Progression Zero v0.47(cached)
 * Real Solar System Textures - 2048 x 1024 v10.4(cached)
 * SCANsat v14.9(cached)
 * scatterer 2:v0.0235(cached)
 * SmokeScreen - Extended FX Plugin 2.6.13.0(cached)
 * Soviet Pack Core 1:v1.1(cached)
 * TAC Life Support (TACLS) - Realism Overhaul Config v11.0.0(cached)
 * TestFlight 1.5.5.0(cached)
 * TextureReplacer v2.4.12(cached)
 * Ven's Stock Part Revamp v1.9.1(cached)
 * [x] Science! 4.14(cached)
 * Contracts Window + 6.1(cached)
 * RasterPropMonitor v0.24.2.1(cached)
 * TweakScale - Rescale Everything! v2.2.6(cached)
 * Connected Living Space 1.2.0.2(cached)
 * Deadly Reentry Continued v7.3.3(cached)
 * Hangar Extender 1:v3.4.6(cached)
 * KSC Switcher 0.5(cached)
 * Engine Lighting 1.4.1(cached)
 * Salyut Stations v2.3.5(cached)
 * Salyut Stations - Soyuz, Progress, Vostok/Voskhod, TKS/VA v1.1(cached)
 * Kerbal Construction Time 1.3.2(cached)
 * Adjustable Landing Gear v1.2.0(cached)
 * Taerobee - Stockalike X-1 & More 2.3
 * Kerbal Renamer 0.5(cached)
 * ShipManifest 5.0.1.0(cached)
 * Contract Configurator 1.9.11_KSP1.0.5(cached)
 * Solver Engines plugin v1.15(cached)
 * ModularFlightIntegrator 1.1.2.0(cached)
 * Filter Extensions - Plugin 2.4.1.3(cached)
 * Firespitter Resources config v7.1.5(cached)
 * KerboKatz - Utilities 1.2.11(cached)
 * Community Resource Pack 0.5.1.1(cached)
 * Kopernicus Planetary System Modifier 1:beta-06-3(cached)
 * Reflection Plugin for KSP 1.2(cached)
 * Klockheed Martian General Plugin Functions - Gimbal module 3.0.7.0(cached)
 * BahamutoD Animation Modules v0.6.2(cached)
 * Stock Extension v25.1
 * Custom Barn Kit 1.1.4.0(cached)
 * Community Tech Tree 2.3(cached)
 * Asteroid Day 1.0.5(cached)
 * TAC Life Support (TACLS) v0.11.2(cached)
 * Progress Parser 2.0(cached)
 * Contract Parser 1.0(cached)
 * RasterPropMonitor Core v0.24.2.1(cached)

it happens

**Comment by torfsen** [comment]
I think you're looking for [KSP-CKAN/CKAN](https://github.com/KSP-CKAN/CKAN).
