### ISSUE TITLE
Feeds has bug (extra '/' added to <id>)

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#3017]
### CKAN Version if known (or site URL)
https://datahub.io

### Please describe the expected behaviour
`<id>` returned from https://datahub.io/feeds/dataset.atom (for example) should be in format
`<id>`https://datahub.io/dataset/65ac1ebf-7da9-4700-b64d-a24e3c8abfd2</id>

### Please describe the actual behaviour
it includes an extra / after the base URL
`<id>`https://datahub.io//dataset/65ac1ebf-7da9-4700-b64d-a24e3c8abfd2</id>

### What steps can be taken to reproduce the issue? 
Go to https://datahub.io/feeds/dataset.atom and look for `<id>`  ...

**Comment by TkTech** [comment]
https://github.com/ckan/ckan/blob/master/ckan/controllers/feed.py#L148

**Comment by Aaron-M** [comment]
https://github.com/ckan/ckan/blob/master/ckan/controllers/feed.py#L379

**Comment by Aaron-M** [comment]
Also an issue for tags, organization etc etc feed info

e.g. https://datahub.io/feeds/organization/270a.atom 

https://github.com/ckan/ckan/blob/master/ckan/controllers/feed.py#L200
https://github.com/ckan/ckan/blob/master/ckan/controllers/feed.py#L191
https://github.com/ckan/ckan/blob/master/ckan/controllers/feed.py#L266
https://github.com/ckan/ckan/blob/master/ckan/controllers/feed.py#L332

**Comment by k-nut** [comment]
The more I think about this the more I come to the conclusion that this should actually not be changed.

The specification is very clear that the atom id of an element can **never** change 
```
When an Atom Document is relocated, migrated, syndicated,
   republished, exported, or imported, the content of its atom:id
   element MUST NOT change.
```
 (from Page 19 of [RFC4287](http://www.ietf.org/rfc/rfc4287))

So the ids that ckan is currently creating are not valid urls but at least they never change.

If we removed that duplicate slash all the ids of all elements in all ckan instances would suddenly change which could lead to unwanted side effects. 

What do you all think?

**Comment by wardi** [comment]
@k-nut that's a good point. Maybe we can fix all this when we re-write the controller as a flask view by changing the ids and the endpoint for the feed at the same time.

**Comment by k-nut** [comment]
So should we mark this issue closed for now?

**Comment by wardi** [comment]
Yes, if we change these ids in place people using the feeds will get a flood of old items shown.
