### ISSUE TITLE
Ambiguity in UI labels for the last_modified and revision_timestamp fields

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckan#3028]
The meaning and presentation of the fields should be more clear and consistent.

last_modified: the date and time when the actual data has been last changed
revision_timestamp: the date and time when the resource metadata has been last changed

If this is the correct meaning for the fields, the visual label on the templates for the resource should be consistent with that:

last_modified -> "Data last updated"
revision_timestamp -> "Metadata last updated"

Currently these fields are used interchangeably to display the same label "Last updated". See

`<td>{{ h.render_datetime(res.last_modified) or h.render_datetime(res.revision_timestamp) or h.render_datetime(res.created) or _('unknown') }}</td>`
https://github.com/ckan/ckan/blob/master/ckan/templates/package/resource_read.html#L158

This problem was mentioned in passing on #1874 but was not fixed there as it was not the main topic of discussion.

**Comment by amercader** [comment]
@augusto-herrmann You are right, what you are proposing makes more sense. Do you want to submit a pull request? It seems like a very small change

**Comment by gleb-rudenko** [comment]
I can work on it

**Comment by augusto-herrmann** [comment]
Thanks for the [PR](https://github.com/ckan/ckan/pull/3455), @gleb-rudenko !

**Comment by gleb-rudenko** [comment]
@augusto-herrmann, np 👍

**Comment by gleb-rudenko** [comment]
@amercader, any progress with this one?
