### ISSUE TITLE
Creation of groups/organizations is failing

### ISSUE THREAD

**Issue by polarp** [ckan/ckan#3040]
### CKAN Version if known (or site URL)
2.5.1

### Please describe the expected behaviour
When importing datasets from remote CKAN instance using the ckan harvesters all groups and organizations from the remote instance should be created.

### Please describe the actual behaviour
Multiple errors occur when trying to import/create the groups/organizations.

### What steps can be taken to reproduce the issue?
Create new harvest source with the following config:

`{
	"organizations_filter_include": ["organization_name"],
	"remote_orgs": "create",
	"remote_groups": "create"
}`

 and try to start the harvester.

This is related to [this](https://github.com/ckan/ckanext-harvest/issues/240) issue in CKAN harvester.

**Comment by amercader** [comment]
This is a ckanext-harvest issue. Moving to ckan/ckanext-harvest#240
