### ISSUE TITLE
Attempting to access non-existing helpers should raise HelperException

### ISSUE THREAD

**Issue by brew** [ckan/ckan#3041]
### CKAN Version if known (or site URL)

2.6a, master

### Please describe the expected behaviour

If helper function is called in a template, but the function doesn't exist, a `ckan.exceptions.HelperError` should be raised.

### Please describe the actual behaviour

A `jinja.exceptions.UndefinedError` is raised.

### What steps can be taken to reproduce the issue? 

Add `{{ h.not_here() }}` to the base.html template and request the index page.

PR on its way.

**Comment by TkTech** [comment]
👍
