### ISSUE TITLE
Should we use quantifiedcode.com?

### ISSUE THREAD

**Issue by k-nut** [ckan/ckan#3063]
The quantifiedcode.com service automatically finds code quality issues and reports them. I set it up for my fork of the repository and wanted to see what your opinion about it is. It's free for open source so we could just try it. [Link to my setup](https://www.quantifiedcode.com/app/project/6c6df51bc5284839b2ac8115dfba200f?groups=code_patterns%3A3LKECaRv,code_patterns%3AswQ4yi5C,code_patterns%3A3MEPnhL3%3Af0)

You can even have it create pull requests for some issues such as this one: https://github.com/k-nut/ckan/pull/1

**Comment by deinok** [comment]
I think its a good idea, but probably we should not let the bot send PR, even if it pass all the tests.
Its a good way to view what can be improved. I will help if its enabled.

**Comment by k-nut** [comment]
The bot will only send a PR if you explicitly tell it to fix a certain type of issues. We can totally use it without the PR-to-fix feature :)

**Comment by wardi** [comment]
It seems like anyone can add the CKAN repo to quantifiedcode by punching in the github url. Is there any action required for this ticket?

**Comment by k-nut** [comment]
@wardi I think if its done not via url but via github authentication that will also enable automatic feedback on pull requests. The question is if we want that.

**Comment by wardi** [comment]
@k-nut I couldn't figure out how to do that. All my user account's repos were shown but not the CKAN org ones when I try to add a project. I certainly could have missed something

**Comment by k-nut** [comment]
@wardi I think you need to give it access to your private repositories. Github does not distinguish between private and organization access. I just did that and surprisingly was able to also add the `ckan/ckan` repository. So I hope that I managed to hereby inlcude the integration and will close this as done 🚀
