### ISSUE TITLE
Update Requirements

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3070]
### CKAN Version if known (or site URL)
master-branch

### Please describe the expected behaviour
Requirements should be the latest stable release

### Please describe the actual behaviour
There are a lot of requirements not updated

### What steps can be taken to reproduce the issue? 

I think it should help the migration to Python3, and simplify future issues

**Comment by amercader** [comment]
This might be helpful https://requires.io/github/ckan/ckan/requirements/?branch=master

Requirements are a tricky issue in CKAN :)

`requirements.in` contains the actual requirements for CKAN. `requirements.txt` contains all requirements' requirements and it's generated using [pip-tools](https://github.com/nvie/pip-tools) (`pip-compile --upgrade > requirements.txt`)

There are some versions that are pinned to an old version on `requirements.in`. They have a comment explaining why (except for Pylons, for which we need 0.9.7).

So to upgrade requirements, it needs to be done on `requirements.in`. Some of them should be straightforward, but for others it might be worth testing that everything is working as expected.

`dev-requirements.txt` can be upgraded without problems although things like the docs should be tested if we upgrade Sphinx.

@deinok Take this into account do you want to have a go?

**Comment by deinok** [comment]
@amercader I can upgrade the requirements, migration from Pylons to Flask will be done?

Should I send PR for each requirement upgrade or send it for small groups of upgrades?

**Comment by amercader** [comment]
@deinok don't take the Flask migration into account (eg don't upgrade Flask
to 0.11)

If they don't involve code changes, you can send a PR for the
dev-requirements and one for requirements.in. If they do it's best to send
a PR with just the specific library changes

**Comment by deinok** [comment]
@amercader Ok, I will try to upgrade all the requirements, and only left Pylons and Flask
