### ISSUE TITLE
Regenerating API Key fails for users missing required columns (ex: email)

### ISSUE THREAD

**Issue by TkTech** [ckan/ckan#3071]
### CKAN Version if known (or site URL)

All supported.
### Please describe the expected behaviour

User API key regenerated successfully.
### Please describe the actual behaviour

`update_user` fails due to missing columns.
### What steps can be taken to reproduce the issue?
1. `paster sysadmin add test_user` (use a name that does not exist)
2. Login as new syadmin user.
3. Go to Manage User
4. Click `Regenerate API Key`
5. _boom_

`sysadmin add` is allowing us to create accounts that do not have all required fields. This is both an interface problem (cli should have asked for an email) and an update_user problem (emails should be allowed to be `Null`, because not all authentication methods will populate it).

**Comment by wildcatzita** [comment]
@TkTech, I can take a look at it.

**Comment by TkTech** [comment]
Fixed in #3445
