### ISSUE TITLE
site_url vs. root_path vs. WSGIScriptAlias

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3081]
I'm running a CKAN instance in a sub-"directory" of my host (at ``/data``). Therefore, I have set ``ckan.site_url`` to ``https://example.com/data``, as [described by the docs for `site_url`](http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-site-url):

> If you want to mount CKAN at a path other than /, then this setting should reflect that, but the URL you mount it at is determined by your apache config (your WSGIScriptAlias path) (or equivalent for other servers).

That worked perfectly for quite some time, until I started uploading resource files via a script that called the action functions directly via `toolkit.get_action` (instead of using web requests). The generated download URLs would end up missing the `data` part of the URL. These URLs are constructed using `ckan.lib.helpers.url_for`, which only uses the host, port and scheme from `site_url` but not the path:

    from pylons import config
    from ckan.lib.helpers import url_for
    config['ckan.site_url'] = 'http://example.com/data'
    print(url_for(controller='package', action='search', qualified=True))
    # prints 'http://example.com/dataset'

Instead, `url_for` uses the [`ckan.root_path`](http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-root-path) setting for that:

    config['ckan.site_url'] = 'http://example.com'
    config['ckan.root_path'] = '/data/{{LANG}}'
    print(url_for(controller='package', action='search', qualified=True))
    # prints 'http://example.com/data/dataset'

Unfortunately, the documentation of `root_path` is rather fuzzy and mostly talks about where the locale code is placed in the URL. In addition, since `site_url` is a much more prominent setting, it's easy to miss `root_path`.

After moving ``/data`` from `site_url` to `root_path`, my resource URLs were indeed generated correctly. However, no everything else is broken, because `url_for` seems to also take the WSGI root into account: If I set

    WSGIScriptAlias /my-wsgi-prefix /etc/ckan/default/apache.wsgi

in my Apache configuration for illustration (in reality it's `/data`) then I end up with URLs like `/my-wsgi-prefix/data/dataset`, which contain both the WSGI prefix and `root_path`. This only happens when the code runs via WSGI. which explains why my resources had URLs without the prefix while all other URLs were working: I hadn't set `root_path`, so the web UI only took the WSGI prefix plus the scheme, host and port from `site_url`. My resource creation script did not run under WSGI, so it only used scheme, host and port from `site_url`, resulting in the missing `data` prefix. Once I set `root_path`, the script starts working (no WSGI, so no double prefix), but the web UI breaks.

So something won't work, no matter how I'm doing things. Here's a suggestion on how things should work. What information do we need?

* For constructing fully qualified URLs (e.g. download URLs for uploaded resource data) we need the scheme, host, and port. On a web server, these values could be inferred from the environment, but since the code should also work standalone (e.g. for tests, paster scripts, etc.) they should be fixed in the configuration.
* In addition, we need to know how to construct URLs on that host. That includes a potentially non-root `WSGIScriptAlias` and a place for the locale code.

The important point here is that we should ignore values that come from the environment, since these may change depending on how the code is run.

There are multiple ways on how to map these values to configuration options. We could continue to use the existing approach of separate options for the host and the path, or we could combine them into a single setting, e.g.

    ckan.site_url = http://example.com/my-wsgi-prefix/{{LANG}}

The main goal should be a consistent behaviour across all environments and clear documentation.

Note that this and similar issues have been encountered many times before, see #2866, #2592, #2599, #2832, #2644, #3001, #2260, #3035.

**Comment by torfsen** [comment]
As a workaround, I'm now creating my resources via true web requests (instead of using the Python API). While this isn't as comfortable it works because the actual resource creation code runs on the web server, which constructs a valid URL from `site_url` and `WSGIScriptAlias` as described above.

**Comment by wardi** [comment]
We're using CKAN in "sub directories". Docs notwithstanding the way that works for us is:
```
ckan.site_url = http://example.com
ckan.root_path = /my-prefix/{{LANG}}
```
Combining them into a single option would be easier. I like that suggestion.

**Comment by torfsen** [comment]
@wardi: Does  that work for you both with and without WSGI (i.e. in the web UI and in e.g. paster)?

**Comment by wardi** [comment]
@torfsen would you like to submit a PR to combine site_url and root_path into a single option?

**Comment by torfsen** [comment]
@wardi Since the underlying problems (e.g. #3001) seem to have been fixed the only thing that's really necessary at the moment from my point of view is a documentation update to clarify the meaning of `root_path` and `site_url`. I'll prepare a PR for that.

Regarding the merging of `site_url` and `root_path`: That would be nice-to-have, but is currently not a priority for me.

**Comment by wardi** [comment]
@torfsen a fix for the docs sounds great
