### ISSUE TITLE
ImportError: No module named vdm.sqlalchemy

### ISSUE THREAD

**Issue by brylie** [ckan/ckan#3086]
### CKAN Version if known (or site URL)
CKAN 2.5

### Please describe the expected behaviour
When configuring Jetty, with the following command `paster db init -c /etc/ckan/default/development.ini` the command should succeed.

### Please describe the actual behaviour
When configuring Jetty, the `paster db init -c /etc/ckan/default/development.ini` command produces the following error:

```
ImportError: No module named vdm.sqlalchemy
```

### What steps can be taken to reproduce the issue? 
I am following the [Setting up Solf](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#setting-up-solr) instructions.

**Comment by brylie** [comment]
I ran the following command: `easy_install vdm` and get a new error:

```
ImportError: No module named sqlalchemy
```

**Comment by k-nut** [comment]
Are you still inside the virtual environment and did you `pip install` the `requirements.txt`?

**Comment by brylie** [comment]
I installed SQAlchemy with `sudo pip install SQAlchemy`, and get the following error:

```
ValueError: VDM only works with SQLAlchemy versions 0.4 through 0.8, not: 1.0.13
```

**Comment by brylie** [comment]
Thanks for your reply @k-nut. The installation instructions do not mention to do `pip install` on the `requirements.txt`.

**Comment by k-nut** [comment]
That step should have been done with [step 2](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#install-ckan-into-a-python-virtual-environment) part `c)` of the documentation. ( `pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt` )

Maybe you missed it? Or do we need to point this out in another way?

**Comment by brylie** [comment]
OK, basically the [install CKAN from package](http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html) instructions are incomplete, since they rely heavily on steps in the [install CKAN from source](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) instructions.

**Comment by brylie** [comment]
In effect, I cannot install CKAN from package without reading through the installation from source instructions.

**Comment by k-nut** [comment]
Yes, the `install CKAN from package` documentation sometimes redirects you to shared parts that are only documented in the `install CKAN from source` tutorial...

**Comment by brylie** [comment]
OK, where does it direct me to step two part c of the installation from source instructions?

**Comment by brylie** [comment]
Also, this level of manual configuration seems to defeat the purpose of packaging an application.

**Comment by k-nut** [comment]
Ah sorry. Now I am mixing up source and package installation documentation. If you are installing from package you do not need to run `paster db init -c /etc/ckan/default/development.ini` as it is part 6 of the from source documentation already. 
After following step 5 (solr) and 3 (postgres) from the `from source` documentation you can go back to [step 3](http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html#update-the-configuration-and-initialize-the-database) of the `from package` documentation and continue with the steps mentioned there.

**Comment by k-nut** [comment]
So basically the process should be as follows:
- Follow step 1,2 from `package install`.
- Follow step 5, 3 from `source install`
- Follow the remaining steps 3 to 5 from `package install`

Does that make sense to you? Aport from the obvious usability problem here...

**Comment by amercader** [comment]
@brylie @k-nut you are right that this is disconcerting, I've consolidated all steps in their own files for both package and source install on https://github.com/ckan/ckan/pull/3087, but for now @brylie please follow the steps that @k-nut mentioned.

If you find any more support requests during the install please report them on [StackOverflow](http://stackoverflow.com/questions/tagged/ckan), the [mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or on IRC (#ckan at freenode). We use the issues on this repo to track bugs and features.

Thanks!

**Comment by brylie** [comment]
Thanks @amercader and @k-nut for your quick and helpful support.
