### ISSUE TITLE
"No datasets found" on "Datasets" screen

### ISSUE THREAD

**Issue by xapple** [ckan/ckan#3091]
### CKAN Version if known (or site URL)
2.5.2 installed at http://anaerobes.science

### Please describe the expected behavior
A full list of all datasets appears, searchable.

### Please describe the actual behavior
The "Datasets" screen says "No datasets found" and whatever search is performed, nothing is returned. Even if you enter the name of a dataset package in the search field for instance.
Though many datasets are visible throught the "Organizations" or "Groups" screens.
No error messages appear on the STDOUT of the `paster serve` command.

I tried running `paster --plugin=ckan search-index rebuild -c /path/to/config.ini` but it made no difference.

Going to `http://localhost:8983/solr` shows that SOLR seems to be running though `tomcat6` (the jetty installation didn't work).

It really seems broken. For instance, if you click on one of the "popular tags" as is suggested on the home page, you just get to the same "No datasets found" page.

Any help appreciated,

**Comment by amercader** [comment]
By default only datasets of type `dataset` will be displayed on the main search page unless you set [`ckan.search.show_all_types`](http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-search-show-all-types) to True. Your metadata has `type = dna_sequence` 

In any case, unless you want to implement a custom metadata time via [`IDatasetForm`](http://docs.ckan.org/en/latest/extensions/adding-custom-fields.html) I suggest you just store the type as an extra field.

Tomcat is absolutely fine.

Closing for now, feel free to reopen if you find another issue. BTW it's probabley best to report support requests on [StackOverflow](http://stackoverflow.com/questions/tagged/ckan), the [mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or on IRC (#ckan at freenode). We use the issues on this repo to track bugs and features.

Thanks!

**Comment by xapple** [comment]
OK thanks a lot for your answer ! I understand the tracker is for bugs... but in a way it's hard for the user to know if something is a bug or a feature until the problem is solved.

**Comment by amercader** [comment]
@xapple Totally agree, and it's fine to create an issue here if you are not sure

Good luck!

**Comment by xapple** [comment]
Come to think of it, there is a bug component to this, because I do have a "popular tags" category that got auto-generated on the front page. Yet, clicking on one of those popular tags brings you to a page saying "No dataset found".
