### ISSUE TITLE
IUploader/Uploader interface missing deletion interface.

### ISSUE THREAD

**Issue by TkTech** [ckan/ckan#3095]
The `IUploader` interface is currently usable for uploading resources, as well as removing now-useless resources *when a resource is changed*, however deleting a resource will leave orphaned resources behind as the `IUploader` plugin has no way of knowing that a deletion occurred.

This is currently a blocking issue for completion of https://github.com/open-data/ckanext-cloudstorage

Additionally, the `old_filename` being passed in when an uploaded file is removed in favour of a link is actually the complete resource URL, not the filename. This is behaviour we might want to change but may be unable to due to legacy plugins.

We could possibly expand the interface a bit, so when we are deleting resources we do something like:

```python
uploader = get_resource_uploader(...)
if hasattr(uploader, 'remove_resource'):
    uploader.remove_resource(old_resource)
```

**Comment by MrkGrgsn** [comment]
A workaround would be to use the iResourceController method `before_delete` to remove the resource from the cloud storage provider.

**Comment by MrkGrgsn** [comment]
@TkTech have you made any progress with this? Link needs to make progress on delete capability for ckanext-cloudstorage for a client so we could help out on this one, either on the CKAN or cloudstorage side or both, sometime in the next 3-4 weeks, I'd guess.

**Comment by TkTech** [comment]
@MrkGrgsn haven't had a chance to work on this at all, feel free.

The quickest solution would be to add use IResourceController (http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IResourceController.before_delete) in ckanext-cloudstorage, assuming it works correctly. Assuming it does, this would also be the most flexible and support older versions of CKAN.

Implementing it as part of the uploader interface (as described in this issue) in CKAN would be the best way.

The "proper" way would be both, to handle current and older versions of CKAN and future releases.

**Comment by MrkGrgsn** [comment]
Okay, sounds good. I'll chat to @smotornyuk but I'm inclined to focus on the `iResourceController.before_delete` option  - it meets our need, cutting out a CKAN update simplifies the process for us, and backward compatibility provides a better return for everyone else.

**Comment by smotornyuk** [comment]
I've created (pull request)[https://github.com/open-data/ckanext-cloudstorage/pull/5] with IResourceController way

**Comment by TkTech** [comment]
I'm going to go ahead and close this. While it would be nice to have a fully CRUD interface for uploads, the interfaces already exist to handle everything via the IResourceController. This is something that could be revisited in the far future.
