### ISSUE TITLE
SQLAlchemy sessions not being closed ? Google bot causes crash.

### ISSUE THREAD

**Issue by xapple** [ckan/ckan#3115]
I set up a fresh CKAN installation from source and put it online at a publicly reachable IP and with a registered DNS. Sure enough, after a couple days, the google bot came along to crawl it. CKAN did not like this. Especially when the google bot decided to request the pages in every possible different languages. Here is a excerpt of when it tried Japanese:

https://gist.github.com/xapple/fcc04eaf8c217ca4f74f4ed904070e5b

Sometimes the error ended in "SystemExit:" with no other message, other times the final error was:

```
TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30
```

In the end the process become unresponsive, the website went down and I needed to restart the paster command.

This may be due to SQLAlchemy sessions not being closed ? 

Is this information useful to you guys to fix the issue ?

**Comment by NicolaiMogensen** [comment]
I would like to also chime in here. Experiencing the same exact thing.

**Comment by TkTech** [comment]
@NicolaiMogensen are you using the most recent version of CKAN? A few leaks were [relatively] recently fixed.

**Comment by NicolaiMogensen** [comment]
Do you have an issue number or commit id? Doing an entire package update is not something i can do at this point @TkTech

**Comment by seferovic** [comment]
Hi,

we are using the latest version of CKAN (2.7.2) and are experiencing intermitent failures that end up with the above mentioned error (QueuePool limit reached).

Is it possible to configure the pool size?

**Comment by TkTech** [comment]
@seferovic are you also using Paster like the original poster? Paster should only ever be used for local development, never for a public or production server.

**Comment by seferovic** [comment]
@TkTech - sorry for leaving that out.. No - we are not using paster! We set up Apache with WSGI process as recommended by CKAN documentation.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
