### ISSUE TITLE
Remove example theme plugins

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#3131]
I believe https://github.com/ckan/ckan/blob/master/setup.py#L114-L137 have no test coverage, don't appear in the documentation and are likely broken.

Any objections to removing them?

**Comment by wardi** [comment]
Oh, my mistake. they are included in the theming docs. Would be nice to test that they keep working at some point, though

**Comment by TkTech** [comment]
I would rather we just remove them.

**Comment by wardi** [comment]
v01-v11 have parts `literalincluded` in the theming doc. We might be safe to remove v12-v21 if they are broken
