### ISSUE TITLE
Organization admins can't send invites if free registering is disabled

### ISSUE THREAD

**Issue by bzar** [ckan/ckan#3142]
### CKAN Version if known (or site URL)

CKAN 2.5.2
### Please describe the expected behaviour

With free registration disabled...

```
ckan.auth.create_user_via_api = false
ckan.auth.create_user_via_web = false
```

...creating users by inviting is still possible. Organization admins should be able to create users by sending invites.
### Please describe the actual behaviour

The organization admin gets a 403 (or 401, depending on CKAN version) error when attempting it because they don't have the privileges to create new users.
### What steps can be taken to reproduce the issue?
1. Disable free registration
2. Create a new organization O
3. Create a new admin user A for O
4. Log in as A
5. Attempt to create a new member for O using an email invite
6. Error should reproduce

**Comment by bzar** [comment]
Two pieces of code I've identified as a cause:

https://github.com/ckan/ckan/blob/e171528b8e4a9220dd3b2245a4b2a0a7d1a64a07/ckan/authz.py#L274-L286
Shouldn't the capacity-filtering also always include 'admin' roles?

https://github.com/ckan/ckan/blob/e171528b8e4a9220dd3b2245a4b2a0a7d1a64a07/ckan/logic/auth/create.py#L136-L150
Actual user creation privilege check. Should this have some condition for organization admins creating new members?

**Comment by amercader** [comment]
I guess you meant

> ..creating users by inviting is still possible. Organization admins should NOT be able to create users by sending invites.

I'm not sure that this use case should be covered by these particular config settings, we'll discuss it on the next dev meeting (which you are welcome to join)

**Comment by bzar** [comment]
No, we need only organization admins and sysadmins to be able to create new users. Sysadmins assign admins to new organizations, who in turn invite other necessary people.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
