### ISSUE TITLE
Ckan non-ASCII tags on Apache

### ISSUE THREAD

**Issue by bunnis** [ckan/ckan#3147]
### CKAN Version if known (or site URL)
2.5.1, apache with nginx

### Please describe the expected behaviour
/dataset?tags=Precipitação
Should show all datasets with that tag

### Please describe the actual behaviour
Internal Server Error

### What steps can be taken to reproduce the issue? 
Install ckan, move it to production using documentation from ckan, with apache and nginx. Create a tag with special characters, try and filter datasets by tag, gives error. Works fine on tags with no special chars.

**Comment by torfsen** [comment]
Can you please post your full traceback?

**Comment by bunnis** [comment]
Stack Trace:
[Fri Jun 24 12:29:28.033085 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] Error - <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)
[Fri Jun 24 12:29:28.035745 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] URL: http:///dataset?tags=Precipita%C3%A7%C3%A3o
[Fri Jun 24 12:29:28.035970 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__
[Fri Jun 24 12:29:28.036081 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   app_iter = self.application(environ, sr_checker)
[Fri Jun 24 12:29:28.036200 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Fri Jun 24 12:29:28.036419 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   resp = self.call_func(req, *args, **self.kwargs)
[Fri Jun 24 12:29:28.036515 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Fri Jun 24 12:29:28.036619 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   return self.func(req, *args, **kwargs)
[Fri Jun 24 12:29:28.036879 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
[Fri Jun 24 12:29:28.036983 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   return request.get_response(self.app)
[Fri Jun 24 12:29:28.037122 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Fri Jun 24 12:29:28.037434 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   application, catch_exc_info=False)
[Fri Jun 24 12:29:28.037532 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Fri Jun 24 12:29:28.037676 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   app_iter = application(self.environ, start_response)
[Fri Jun 24 12:29:28.037771 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Fri Jun 24 12:29:28.037883 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   resp = self.call_func(req, *args, **self.kwargs)
[Fri Jun 24 12:29:28.037968 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Fri Jun 24 12:29:28.038097 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   return self.func(req, *args, **kwargs)
[Fri Jun 24 12:29:28.038281 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
[Fri Jun 24 12:29:28.038386 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   response = request.get_response(self.app)
[Fri Jun 24 12:29:28.038490 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Fri Jun 24 12:29:28.038684 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   application, catch_exc_info=False)
[Fri Jun 24 12:29:28.038784 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Fri Jun 24 12:29:28.038894 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   app_iter = application(self.environ, start_response)
[Fri Jun 24 12:29:28.039081 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/home/pegg/ckan/lib/default/src/ckan/ckan/config/middleware.py', line 389 in inner
[Fri Jun 24 12:29:28.039169 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   result = application(environ, start_response)
[Fri Jun 24 12:29:28.039246 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
[Fri Jun 24 12:29:28.039440 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   return self.app(environ, start_response)
[Fri Jun 24 12:29:28.039547 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
[Fri Jun 24 12:29:28.039625 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   return self.wrap_app(environ, session_start_response)
[Fri Jun 24 12:29:28.039834 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
[Fri Jun 24 12:29:28.040030 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   response = self.app(environ, start_response)
[Fri Jun 24 12:29:28.040122 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
[Fri Jun 24 12:29:28.040284 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   response = self.dispatch(controller, environ, start_response)
[Fri Jun 24 12:29:28.040447 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
[Fri Jun 24 12:29:28.040606 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   return controller(environ, start_response)
[Fri Jun 24 12:29:28.040696 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/home/pegg/ckan/lib/default/src/ckan/ckan/lib/base.py', line 337 in __call__
[Fri Jun 24 12:29:28.040877 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   res = WSGIController.__call__(self, environ, start_response)
[Fri Jun 24 12:29:28.040997 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
[Fri Jun 24 12:29:28.041103 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   response = self._dispatch_call()
[Fri Jun 24 12:29:28.041304 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
[Fri Jun 24 12:29:28.041499 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   response = self._inspect_call(func)
[Fri Jun 24 12:29:28.041694 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
[Fri Jun 24 12:29:28.041860 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   result = self._perform_call(func, args)
[Fri Jun 24 12:29:28.042035 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
[Fri Jun 24 12:29:28.042199 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   return func(**args)
[Fri Jun 24 12:29:28.042403 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/home/pegg/ckan/lib/default/src/ckan/ckan/controllers/package.py', line 268 in search
[Fri Jun 24 12:29:28.042559 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   query = get_action('package_search')(context, data_dict)
[Fri Jun 24 12:29:28.042736 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/home/pegg/ckan/lib/default/src/ckan/ckan/logic/__init__.py', line 416 in wrapped
[Fri Jun 24 12:29:28.042889 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   result = _action(context, data_dict, **kw)
[Fri Jun 24 12:29:28.043009 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/home/pegg/ckan/lib/default/src/ckan/ckan/logic/action/get.py', line 1894 in package_search
[Fri Jun 24 12:29:28.043174 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   data_dict = item.before_search(data_dict)
[Fri Jun 24 12:29:28.043394 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] File '/home/pegg/ckan/lib/default/src/ckanext-harvest/ckanext/harvest/plugin.py', line 95 in before_search
[Fri Jun 24 12:29:28.043559 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   fq = "{0} -dataset_type:harvest".format(search_params.get('fq', ''))
[Fri Jun 24 12:29:28.043738 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)
[Fri Jun 24 12:29:28.043886 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] 
[Fri Jun 24 12:29:28.044037 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] 
[Fri Jun 24 12:29:28.044197 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] CGI Variables
[Fri Jun 24 12:29:28.044362 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] -------------
[Fri Jun 24 12:29:28.044500 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   AUTH_TYPE: 'cookie'
[Fri Jun 24 12:29:28.044847 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   CKAN_CURRENT_URL: '/dataset?tags%3DPrecipita%25C3%25A7%25C3%25A3o'
[Fri Jun 24 12:29:28.045209 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   CKAN_LANG: 'en'
[Fri Jun 24 12:29:28.045400 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   CKAN_LANG_IS_DEFAULT: True
[Fri Jun 24 12:29:28.045461 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   CONTENT_TYPE: '; charset=utf-8'
[Fri Jun 24 12:29:28.045504 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   CONTEXT_DOCUMENT_ROOT: '/var/www'
[Fri Jun 24 12:29:28.045541 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   DOCUMENT_ROOT: '/var/www'
[Fri Jun 24 12:29:28.045577 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   GATEWAY_INTERFACE: 'CGI/1.1'
[Fri Jun 24 12:29:28.045627 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
[Fri Jun 24 12:29:28.046008 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_ACCEPT_ENCODING: 'gzip, deflate, sdch'
[Fri Jun 24 12:29:28.046054 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_ACCEPT_LANGUAGE: 'pt-PT,pt;q=0.8,en-US;q=0.6,en;q=0.4'
[Fri Jun 24 12:29:28.046093 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_CACHE_CONTROL: 'max-age=0'
[Fri Jun 24 12:29:28.046129 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_CONNECTION: 'close'
[Fri Jun 24 12:29:28.046167 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_COOKIE: 'auth_tkt="45b3d30b98752b5b106436ef5e45af3e572897f7deimos!userid_type:unicode"; ckan=cfa2ace029b20c8c2d6971311ca2054f1bebdcbe54d13592f53341f7b4e7b5815f1dcc29'
[Fri Jun 24 12:29:28.046542 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_HOST: ''
[Fri Jun 24 12:29:28.046595 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_REFERER: 'http:///dataset/arome_pt2_025_prec_2016062200_036-nc'
[Fri Jun 24 12:29:28.046637 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_UPGRADE_INSECURE_REQUESTS: '1'
[Fri Jun 24 12:29:28.046676 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_USER_AGENT: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
[Fri Jun 24 12:29:28.046713 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   HTTP_X_FORWARDED_FOR: '10.0.2.2'
[Fri Jun 24 12:29:28.047037 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   PATH_INFO: '/dataset'
[Fri Jun 24 12:29:28.047121 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   PATH_TRANSLATED: '/etc/ckan/default/apache.wsgi/dataset'
[Fri Jun 24 12:29:28.047161 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   QUERY_STRING: 'tags=Precipita%C3%A7%C3%A3o'
[Fri Jun 24 12:29:28.047201 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   REMOTE_ADDR: '127.0.0.1'
[Fri Jun 24 12:29:28.047236 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   REMOTE_PORT: '50238'
[Fri Jun 24 12:29:28.047272 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   REMOTE_USER: u'deimos'
[Fri Jun 24 12:29:28.047306 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   REMOTE_USER_DATA: 'userid_type:unicode'
[Fri Jun 24 12:29:28.047780 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   REMOTE_USER_TOKENS: ['']
[Fri Jun 24 12:29:28.047838 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   REQUEST_METHOD: 'GET'
[Fri Jun 24 12:29:28.048150 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   REQUEST_SCHEME: 'http'
[Fri Jun 24 12:29:28.048205 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   REQUEST_URI: '/dataset?tags=Precipita%C3%A7%C3%A3o'
[Fri Jun 24 12:29:28.048245 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   SCRIPT_FILENAME: '/etc/ckan/default/apache.wsgi'
[Fri Jun 24 12:29:28.048283 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   SERVER_ADDR: '127.0.0.1'
[Fri Jun 24 12:29:28.048319 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   SERVER_ADMIN: '[no address given]'
[Fri Jun 24 12:29:28.048606 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   SERVER_NAME: ''
[Fri Jun 24 12:29:28.048660 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   SERVER_PORT: '80'
[Fri Jun 24 12:29:28.048700 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   SERVER_PROTOCOL: 'HTTP/1.0'
[Fri Jun 24 12:29:28.048737 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   SERVER_SIGNATURE: '<address>Apache/2.4.7 (Ubuntu) Server at  Port 80</address>\\n'
[Fri Jun 24 12:29:28.049135 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   SERVER_SOFTWARE: 'Apache/2.4.7 (Ubuntu)'
[Fri Jun 24 12:29:28.049332 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] 
[Fri Jun 24 12:29:28.049380 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] 
[Fri Jun 24 12:29:28.049426 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] WSGI Variables
[Fri Jun 24 12:29:28.049464 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] --------------
[Fri Jun 24 12:29:28.049502 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   application: <fanstatic.publisher.Delegator object at 0x7f18b125fb50>
[Fri Jun 24 12:29:28.049538 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   beaker.cache: <beaker.cache.CacheManager object at 0x7f18b125fbd0>
[Fri Jun 24 12:29:28.049956 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   beaker.get_session: <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x7f18b12e2e10>>
[Fri Jun 24 12:29:28.050001 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   beaker.session: {'_accessed_time': 1466767768.033984, '_creation_time': 1466767768.033984}
[Fri Jun 24 12:29:28.050040 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   fanstatic.needed: <fanstatic.core.NeededResources object at 0x7f18b0d8bed0>
[Fri Jun 24 12:29:28.050079 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.application_group: 'ckan.simocean|'
[Fri Jun 24 12:29:28.050119 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.callable_object: 'application'
[Fri Jun 24 12:29:28.050153 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.enable_sendfile: '0'
[Fri Jun 24 12:29:28.050501 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.handler_script: ''
[Fri Jun 24 12:29:28.050544 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.input_chunked: '0'
[Fri Jun 24 12:29:28.050582 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.listener_host: ''
[Fri Jun 24 12:29:28.050620 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.listener_port: '8080'
[Fri Jun 24 12:29:28.050658 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.process_group: 'ckan_default'
[Fri Jun 24 12:29:28.051021 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.queue_start: '1466767768017181'
[Fri Jun 24 12:29:28.051075 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.request_handler: 'wsgi-script'
[Fri Jun 24 12:29:28.051115 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.script_reloading: '1'
[Fri Jun 24 12:29:28.051153 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   mod_wsgi.version: (3, 4)
[Fri Jun 24 12:29:28.051193 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   paste.cookies: (<SimpleCookie: auth_tkt='45b3d30b98752b5b106436ef5e45af3e572897f7deimos!userid_type:unicode' ckan='cfa2ace029b20c8c2d6971311ca2054f1bebdcbe54d13592f53341f7b4e7b5815f1dcc29'>, 'auth_tkt="45b3d30b98752b5b106436ef5e45af3e572897f7deimos!userid_type:unicode"; ckan=cfa2ace029b20c8c2d6971311ca2054f1bebdcbe54d13592f53341f7b4e7b5815f1dcc29')
[Fri Jun 24 12:29:28.051494 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   paste.parsed_dict_querystring: (MultiDict([('tags', 'Precipita\\xc3\\xa7\\xc3\\xa3o')]), 'tags=Precipita%C3%A7%C3%A3o')
[Fri Jun 24 12:29:28.051688 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   paste.parsed_querystring: ([('tags', 'Precipita\\xc3\\xa7\\xc3\\xa3o')], 'tags=Precipita%C3%A7%C3%A3o')
[Fri Jun 24 12:29:28.051987 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   paste.registry: <paste.registry.Registry object at 0x7f18b0d68290>
[Fri Jun 24 12:29:28.052070 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   paste.throw_errors: True
[Fri Jun 24 12:29:28.052110 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   pylons.action_method: <bound method PackageController.search of <ckan.controllers.package.PackageController object at 0x7f18c1d76790>>
[Fri Jun 24 12:29:28.052151 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   pylons.controller: <ckan.controllers.package.PackageController object at 0x7f18c1d76790>
[Fri Jun 24 12:29:28.052190 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   pylons.environ_config: {'session': 'beaker.session', 'cache': 'beaker.cache'}
[Fri Jun 24 12:29:28.052229 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   pylons.pylons: <pylons.util.PylonsContext object at 0x7f18c1d76e10>
[Fri Jun 24 12:29:28.052516 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   pylons.routes_dict: {'action': u'search', 'controller': u'package'}
[Fri Jun 24 12:29:28.052603 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   repoze.who.api: <repoze.who.api.API object at 0x7f18b0d68410>
[Fri Jun 24 12:29:28.052644 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   repoze.who.identity: <repoze.who identity (hidden, dict-like) at 139744021968112>
[Fri Jun 24 12:29:28.052682 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   repoze.who.logger: <logging.Logger object at 0x7f18b122cd10>
[Fri Jun 24 12:29:28.052722 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   repoze.who.plugins: {'ckan.lib.authenticator:UsernamePasswordAuthenticator': <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f18b122cb90>, 'friendlyform': <FriendlyFormPlugin 139744027790544>, 'auth_tkt': <CkanAuthTktCookiePlugin 139744027580688>}
[Fri Jun 24 12:29:28.052763 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   routes.route: <routes.route.Route object at 0x7f18b13c8210>
[Fri Jun 24 12:29:28.053161 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   routes.url: <routes.util.URLGenerator object at 0x7f18c1d766d0>
[Fri Jun 24 12:29:28.053218 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   webob._parsed_query_vars: (GET([('tags', 'Precipita\\xc3\\xa7\\xc3\\xa3o')]), 'tags=Precipita%C3%A7%C3%A3o')
[Fri Jun 24 12:29:28.053589 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   webob.adhoc_attrs: {'response': <Response at 0x7f18c1d76850 200 OK>, 'language': 'en-us'}
[Fri Jun 24 12:29:28.053641 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   wsgi process: 'Multi process AND threads (?)'
[Fri Jun 24 12:29:28.053680 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   wsgi.file_wrapper: <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f18b0cfca80>
[Fri Jun 24 12:29:28.053720 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881]   wsgiorg.routing_args: (<routes.util.URLGenerator object at 0x7f18c1d766d0>, {'action': u'search', 'controller': u'package'})
[Fri Jun 24 12:29:28.053761 2016] [:error] [pid 2267:tid 139744905996032] [remote 127.0.0.1:48881] ------------------------------------------------------------
[Fri Jun 24 12:29:28.135906 2016] [:error] [pid 2267:tid 139744905996032] 2016-06-24 12:29:28,135 INFO  [ckan.lib.base]  /dataset render time 0.080 seconds
[Fri Jun 24 12:29:28.436880 2016] [:error] [pid 2266:tid 139744964744960] [remote 127.0.0.1:49137] mod_wsgi (pid=2266): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Fri Jun 24 12:29:28.437288 2016] [:error] [pid 2266:tid 139744964744960] [remote 127.0.0.1:49137] IOError: failed to write data
[Fri Jun 24 12:29:28.626648 2016] [:error] [pid 2266:tid 139744981530368] [remote 127.0.0.1:43505] mod_wsgi (pid=2266): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Fri Jun 24 12:29:28.627690 2016] [:error] [pid 2266:tid 139744981530368] [remote 127.0.0.1:43505] IOError: failed to write data
[Fri Jun 24 12:29:28.630174 2016] [:error] [pid 2266:tid 139744964744960] [remote 127.0.0.1:48881] mod_wsgi (pid=2266): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Fri Jun 24 12:29:28.630323 2016] [:error] [pid 2266:tid 139744964744960] [remote 127.0.0.1:48881] IOError: failed to write data
[Fri Jun 24 12:29:28.884555 2016] [:error] [pid 2267:tid 139744880817920] [remote 127.0.0.1:48881] mod_wsgi (pid=2267): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Fri Jun 24 12:29:28.884706 2016] [:error] [pid 2267:tid 139744880817920] [remote 127.0.0.1:48881] IOError: failed to write data
[Fri Jun 24 12:29:29.210311 2016] [:error] [pid 2267:tid 139744880817920] 2016-06-24 12:29:29,210 INFO  [ckan.lib.base]  /api/i18n/en render time 0.003 seconds

**Comment by k-nut** [comment]
It seems like you are running into an old bug in ckanext-harvest. It should have been fixed with [this commit](https://github.com/ckan/ckanext-harvest/commit/afbf0f0dfead7d119eb10dcc9ea1f25016d4ff31) can you tell us which version of `ckanext-harvest` you are running or just try to run it with the lastest?

**Comment by bunnis** [comment]
That's it, I'm missing that commit. I'm using an older version, this fixed it. Thanks
