### ISSUE TITLE
Solr-jetty NO JSP Support for /solr

### ISSUE THREAD

**Issue by Twinko5** [ckan/ckan#3149]
### CKAN Version if known (or site URL)
Latest

### Please describe the expected behaviour
When clicking on datasets, I expect to see the datasets I have access to, and be able to search among them.

### Please describe the actual behaviour
The datasets section on my website never shows any dataset when they are in organisations I have access to, instead I have "No dataset found'.

_In my logs, I have this :_

[main] INFO org.mortbay.log - Deploy /etc/jetty/contexts/javadoc.xml -> org.mort
bay.jetty.handler.ContextHandler@65a45a7f{/javadoc,file:/usr/share/jetty/javadoc
}
[main] INFO org.mortbay.log - NO JSP Support for , did not find org.apache.jaspe
r.servlet.JspServlet
[main] INFO org.mortbay.log - NO JSP Support for /solr, did not find org.apache.
jasper.servlet.JspServlet

I get the same error (No jsp support) if I wget http://127.0.0.1:8983/solr

In spite of this, ckan seems to work well, I added other services without any concern, and jetty starts without any error.

What I already did : 

- Reindex Solr
- Added ckan.search.show_all_types to true in the ckan conf file
- Completly deleted jetty and reinstalled it
- Checked JAVA_HOME the environment variable 
- Read this bug, some said that it could be connected "https://bugs.launchpad.net/ubuntu/+source/jetty/+bug/1508562", but since noone here got this issue, I might be wrong.

I spent half a day on this, and couldn't find the solution.
Thanks in advance for your help,
If this doesn't work, I will try installing tomcat.

**Comment by deinok** [comment]
Are you sure that the Dataset is not private for organization members?

**Comment by Twinko5** [comment]
Thanks for your answer @deinok 

It is indeed private, but if I am logged in and admin of this organisation, am I not supposed to see it among datasets ? In addition with that, there is still the JSP error and I don't think this is normal.

I don't get this doc', I just think I shouldn't have followed the "package installation" because it is confusing.

Browsing stackoverflow, it seems that many people had the same issue, doing the package installation. However, I can't find a correct installation: I tried tomcat, different versions of solr, but as I am quite new to all this, I get lost. 
If anyone has clear steps to end solr installation on ubuntu 14.04, I would be pleased.

Thanks in advance,
Twinko5

**Comment by Twinko5** [comment]
Keeping you informed : After all the issues I had on solr, I swapped to tomcat, did a fresh installation and this worked like a charm.

 I still can't see private datasets on the main screen even if I am logged in as an admin of this organisation, but I think this is a normal behaviour, even if it's weird :)
Thanks to deinok and amercader

**Comment by amercader** [comment]
Great to hear you got it working @Twinko5. We definitely should switch to Tomcat at some point.
