### ISSUE TITLE
Updating username logs user out

### ISSUE THREAD

**Issue by bzar** [ckan/ckan#3155]
### CKAN Version if known (or site URL)
demo.ckan.org

### Please describe the expected behaviour
Username is changed, user is redirected to profile page

### Please describe the actual behaviour
Username is changed, user is logged out

### What steps can be taken to reproduce the issue? 
1. Create a user
1. Log in
1. Go to user settings
1. Change username
1. Click "Update profile"

**Comment by TkTech** [comment]
We're using the username in the authentication cookie, so if your username changes you currently get logged out.

Gladly accept a PR that updates this to use the IDs.

**Comment by amercader** [comment]
This was fixed recently in https://github.com/ckan/ckan/pull/3030
