### ISSUE TITLE
Lost all data of Datastore after shutdown or reboot

### ISSUE THREAD

**Issue by jcballesteros** [ckan/ckan#3156]
CKAN 2.5.2

These are the extensions that I have enabled: 
-         "datastore",
-         "datapusher",
-         "stats",
-         "text_view",
-         "image_view",
-         "recline_view",
-         "recline_map_view",
-         "recline_graph_view",
-         "webpage_view",
-         "resource_proxy",
-         "pdf_view",
-         "geo_view",
-         "navigablemap",
-         "choroplethmap",
-         "linechart",
-         "barchart",
-         "piechart",
-         "viewhelpers",
-         "dashboard_preview",
-         "basicgrid",
-         "pages",
-         "showcase",
-         "surrey",
-         "surreyfacet",
-         "surreyextrapages",
-         "malaga",
-         "cartodbmap"

I just upgrade a CKAN 2.2 to actual version. I added manually all CSVs to the datastore.

After reset the machine (Amazon Instance with Ubuntu 14 LTS) I have this error: Error: cannot connect to datapusher . If add again the data, the data is pushed correctly. But I must do that with all datasets.

That happens after a reboot or shutdown. 

If I stop all the services and then I start all, the problem not exists:
1. service apache2 stop
2. service nginx stop
3. service jetty stop
4. service postgresql stop
5. service postgresql start
6. service jetty start
7. service nginx start
8. service apache2 start

If I stop all and then I reset the machine the problem appears again.

What do you think about it?

**Comment by jcballesteros** [comment]
The data are not lost, the problem is only the visualizacion of datasore in the "datastore tab". 

When you are edit the resource the message: "Error: cannot connect to datapusher" appears in all resources.

But the views are working well.

**Comment by amercader** [comment]
Looks like it is a problem with the DataPusher not running or CKAN not reaching it. Can you check the value of `ckan.datapusher.url`? Does it work when you ping this URL directly?

**Comment by jcballesteros** [comment]
The datapusher is up and running. But it´s so strange because in the datapusher´s log appears an error 404. If I try, I have an job_id not found.

But if there are a visualization that use the data from datastore (the same data with the connect error), the visualization works well.

**Comment by davidread** [comment]
This is an error during Datapusher's datapusher_status action. It looks in its ckan-service-provider database. However the default place for this is wiped on reboot:

    SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/job_store.db'

I've raised a ticket to improve this: https://github.com/ckan/datapusher/issues/129
