### ISSUE TITLE
Redefine form.html macros in cusom theme extension

### ISSUE THREAD

**Issue by nabiltntn** [ckan/ckan#3157]
### CKAN Version if known (or site URL)
2.5.2

### Please describe the expected behaviour
Being able to extend macros defined in form.htm in my custom theme extension

### Please describe the actual behaviour
I want to redefine `macros/form.html` in my custom theme extensions by having the same structure in my extension templates folder and a :  

```html

{% ckan_extends %}

{# Copying the {% macro  %} with the custom implementation #}

```

I see the CKAN default form.html is still applied instead of the custom one.

How is it possible to force extenion form.html ?

**Comment by wardi** [comment]
You'll probably have to copy the whole file and make changes to the macros because `macros/form.html` isn't set up with blocks for you to override with `{% ckan_extends %}`.

**Comment by hantongliu** [comment]
But when I copy everthing in macro/form.html in my templetes and reload. The style is gone. Each column is stick to each other.
