### ISSUE TITLE
DataStore Map and Explorer not displaying map tiles since 11 July 2016

### ISSUE THREAD

**Issue by MrkGrgsn** [ckan/ckan#3162]
Direct tile access to MapQuest maps has been discontinued as of 11 July 2016 and the DataStore Map and Explorer previews no longer display map tiles. 

The issue actually lies with recline.js and it has been logged https://github.com/okfn/recline/issues/500  and there is a referenced patch to replace MapQuest with Open Street Map frodrigo/recline@3df0c2a2bb8897124bdbbca715b2be1fd99cb08f

Thought it would be useful to have a record here and request the packaged recline.js should be updated.

**Comment by kfishwick** [comment]
We have another solution, implemented for bcgov, that allows you to customize the map tiles for the recline view based on ini parameters (similar to the geoview & spatial extensions).  If no customized parameters are set, the default configuration (Stamen) would be used.  

Would this be suitable for anyone else, we can do a pull request?

**Comment by MrkGrgsn** [comment]
I think that would be great @kfishwick

**Comment by nibecker** [comment]
Sounds good @kfishwick

**Comment by kfishwick** [comment]
Great we will put it together and submit this week.

**Comment by amercader** [comment]
Super stuff, added some comments to the PR

**Comment by kfishwick** [comment]
Thanks, we have updated the code to address the comments @amercader.  Please let us know if it can be incorporated into 2.5.x.
