### ISSUE TITLE
Filestore and sessions on High Availability deploy

### ISSUE THREAD

**Issue by mkuder** [ckan/ckan#3168]
Hello, 

We are planning on deploying two instances of CKAN (with Drupal, based on data.gov.uk) behind a load balancer with a shared database. 

On the [High Availability wiki page](https://github.com/ckan/ckan/wiki/CKAN-High-Availability), there is no mention of the filestore duplication/synchronization and how to handle that. Besides the filestore, I believe there are also some other directories that should be shared (sstore from who.ini for instance) and possibly even ckan.ini. 

Would you recommend syncing these directories between the frontend servers via something like [lsyncd](https://github.com/axkibe/lsyncd)? Or should we use a network file server that would be shared by both instances?

#### CKAN Version
2.2 (data.gov.uk)

**Comment by TkTech** [comment]
Is external storage an option for you? https://github.com/open-data/ckanext-cloudstorage is an easy way to plug-and-play with S3, Azure Storage, etc...

**Comment by mkuder** [comment]
Thanks for the suggestion, it seems an option, but we weren't planning on using external storage. Configuring internal storage with a compatible API seems viable, although I'm not sure whether the time needed to set up would be any less that using remotely mounted directories of a networked file server.

How about the sstore directory and possibly anything else that should be shared? Or is this a specific of data.gov.uk and not in pure ckan?

In any way, were high availability deployments already tested or is the documentation currently a work-in-progress, with possible issues still to be ironed out?

**Comment by TkTech** [comment]
`sstore` sounds like something you guys have brewed up internally. The base CKAN storage doesn't care where you point it as long as it's a +rw directory. Inside of this directory it'll create `/resource` and `/uploads` folders which contain dataset resources and things like group images, respectively.

You could, absolutely, point this to a a large NFS-mount and be done with it if it suits your needs. Keep in mind that CKAN will serve these files up itself. You'll want to look into using gunicorn and possibly some small patches if you intend to serve many large files at once, or you will run out of processes available to respond to requests. File uploads do not currently support resuming either, so if you're pushing large resources you'll want to do something custom or shore up the existing code.

**Comment by mkuder** [comment]
OK, thanks. We'll test the NFS approach first and see if it performs ok, I don't expect the file traffic to be too heavy.
