### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by Twinko5** [ckan/ckan#3170]
### CKAN Version if known (or site URL)
Latest

### Please describe the expected behaviour
Data get uploaded to the datastore.

### Please describe the actual behaviour

**In the datapusher logs, I get the following :**
_"SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"_
when trying to upload anything to the datastore, no matter the datatype or what's in it.

**On my website, I get :**

_"Error: Process completed but unable to post to result_url "_

The ssl certificate is self signed, but I believe doing the steps described in https://github.com/ckan/datapusher/issues/83 and https://github.com/tanmaythakur/datapusher/tree/toggle_ssl_verification#configuration  should have solved this issue.

However, I still get this error even after I changed these files ..

The config without https and basicauth was working perfectly.
I added them with https://github.com/ckan/ckan/wiki/SSL and a normal working basic auth installation on the apache server. 
I get all the ckan instance running on https, but the datapusher is sending this error.

I would be glad if you could help me on this one, 
Thanks in advance,
Twinko5

**Comment by mattfullerton** [comment]
Hi,
The instructions in issues/83 are only ideas - there is nothing merged into
Datapusher yet to allow this.

The other instructions assume you have switched to the
https://github.com/tanmaythakur/datapusher project instead of the standard
datapusher. Have you done this? Are you using a source install?

I shouldn't recommend it, but the quick way to solve this is to add the
option "verify= false" to every call of requests.post in
datapusher/jobs.py...

Best,
Matt

**Comment by Twinko5** [comment]
Thanks @mattfullerton, 

It was indeed quite a newbie question, I didn't know it hadn't been merged yet.
It is quite troubling though, because the error occurs as described on ckan/datapusher#83 even for perfectly healthy certificates.

Do all the people that use ssl and datapusher have to switch to https://github.com/tanmaythakur/datapusher ?
Thanks for your quick and right answer,
Twinko5

**Comment by Twinko5** [comment]
Okay, I talked too fast. 

I am using a package install, and instead of the normal datapusher, I now use  https://github.com/tanmaythakur/datapusher . However, the error still appears : 

_"SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"_

I have to say that my certificate is a healthy one.
Here is the content of my datapusher_settings.py : 
"import uuid

DEBUG = False
TESTING = False
SECRET_KEY = str(uuid.uuid4())
USERNAME = str(uuid.uuid4())
PASSWORD = str(uuid.uuid4())

NAME = 'datapusher'

# database

SQLALCHEMY_DATABASE_URI = 'postgresql://ckan_default:my_password@localhost/datastore_default'

# webserver host and port

HOST = '0.0.0.0'
PORT = 8800

# logging

#FROM_EMAIL = 'server-error@example.com'
#ADMINS = ['yourname@example.com']  # where to send emails

#LOG_FILE = '/tmp/ckan_service.log'
STDERR = True

# Set this to False if you dont want SSL verification
SSL_VERIFY = False "

I don't know why I keep running in problems with this ..
Thanks in advance for any idea, 
Twinko5

**Comment by mattfullerton** [comment]
Have you restarted apache (assuming you're using apache) and ensured the right wsgi script is being linked to after making the change?

As you said that the certificate should be working, the problem might be another one, which is that pre-Python 2.7.9 stock install seems to have problems with some certificates. You might be able to do this by activating the datapusher environment (. bin/activate) and then installing some extra packages:
pip install pyopenssl ndg-httpsclient pyasn1

**Comment by Twinko5** [comment]
Thanks for your help @mattfullerton .

I did everything you said, but figured the problem was on me.

My installation of the new datapusher was not clean, I still had some parts of the old one.
So I did a clean installation, removed everything from the old one, which resulted in the disappearance of the SSL3 error.

I still have one more issue though (I feel we're getting close) :

I tried to put a basic auth on the server, but since, from what I understand, the datapusher is calling the ckan api from the outside url, it needs to log in. 

So I changed the ckan url to : https://username:password@my.domain.com but it's still saying 
"client used wrong authentication scheme".

What I'd like is to force the people that want to access ckan to log in somewhere, and I'd rather this auth to use google_auth.
There are plugins for ckan that use google_auth, but people can still access ckan as anonymous, see the names of my organisations and stuff.

Do you or anyone have any suggestion about it ? I can't use it if information is not secured somehow ..

Thanks in advance, 
Twinko5

**Comment by Twinko5** [comment]
For those interrested, I ended up using https://github.com/pingidentity/mod_auth_openidc to put an auth on the apache server.

Everything seems to work fine, except it seems that the datapusher can't push anymore.
I tried to add the network ip, the extern ip, but it doesn't work.
As soon as I add the host localhost, there is no google+ authentification anymore.
Here is my ckan conf file :

WSGISocketPrefix /var/run/wsgi
OIDCProviderMetadataURL https://accounts.google.com/.well-known/openid-configuration
OIDCClientID My_client_id
OIDCClientSecret My_secret

OIDCRedirectURI Uri_of_redirect
OIDCCryptoPassphrase ck4n

<VirtualHost 127.0.0.1:8080>

    ServerName myservername
    WSGIScriptAlias / /etc/ckan/default/apache.wsgi

    # pass authorization info on (needed for rest api)
    WSGIPassAuthorization On

    # Deploy as a daemon (avoids conflicts between CKAN instances)
    WSGIDaemonProcess ckan_default display-name=ckan_default processes=2 threads=15

    WSGIProcessGroup ckan_default
    ErrorLog /var/log/apache2/ckan_default.error.log
    CustomLog /var/log/apache2/ckan_default.custom.log combined

    <IfModule mod_rpaf.c>
        RPAFenable On
        RPAFsethostname On
        RPAFproxy_ips 127.0.0.1
    </IfModule>

<Location />

   <RequireAny>
        <RequireAll>
        AuthType openid-connect
        Require valid-user
        </RequireAll>
        <RequireAll>
        Require ip 10.1.0.8
        </RequireAll>
        <RequireAll>
        Require ip my_ip
        </RequireAll>
        <RequireAll
        Require host localhost
        </RequireAll>
   </RequireAny>
</Location>

</VirtualHost>

I don't know if it has a place here, but i'd have loved to find it here.

Plus if anyone stepping by can tell me what Require I have to set up to make the datapusher work again, that would be great.

Thanks in advance, 
Twinko5

**Comment by Twinko5** [comment]
So, I'll keep talking to myself and the future hypothetical visitor who wants to put a google+ sign in on a ckan instance.

Putting it on apache was not wise, because apache can't make the difference between external requests and requests from the datapusher since it is behind the nginx proxy.

So, I added a google+ auth on the nginx proxy instead with https://github.com/pingidentity/lua-resty-openidc , with an if test on the ip to check if the request is coming from my ckan or not, and it's working :)

Plus the extension to log into ckan with it : http://extensions.ckan.org/extension/googleauth/

There is a trick too, because it automatically logs you in, but the problem is solved with a google search .

Hope it helps someone,
Twinko5

**Comment by wardi** [comment]
@Twinko5 looks like you've sorted out your issue, and I don't know how this affects our repo other than possibly documentation. Please submit a PR along those lines if you like.

**Comment by mattfullerton** [comment]
@wardi For as long as we don't have Python =<2.7.9, we should add pyopenssl, ndg-httpsclient and pyasn1 to the ckan and datapusher requirements. @nigelbabu knows more.
