### ISSUE TITLE
A user can't list all private datasets via the API

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#3176]
### CKAN Version if known (or site URL)
Master

### Please describe the expected behaviour
A user should be able to get a list of all the datasets available to him/her - including private ones via the API.

### Please describe the actual behaviour
The only way I can see to get private ones is by using user_show include_datasets=True. However that only includes private ones created by that user. It excludes other private ones created in the organization by other users.

### What steps can be taken to reproduce the issue? 
I was just answering this question on SO by reading the code. http://stackoverflow.com/questions/38625786/how-to-obtain-a-given-users-dateset-listboth-public-and-private-through-ckan/38629242#38629242

**Comment by LinJianping** [comment]
In my opinion, the organization administrator should have privileges to decide whether the members can access all the datasets or those created by themselves.

**Comment by wardi** [comment]
package_search should return private datasets when you specify an organzation you're a member of like the organization pages do, except that our org controller is using a context parameter to make that work. We should fix that. https://github.com/ckan/ckan/blob/master/ckan/controllers/group.py#L297-L303

**Comment by wardi** [comment]
fixed by #3191
