### ISSUE TITLE
Private datasets not shown correctly in data explorer

### ISSUE THREAD

**Issue by chrism0dwk** [ckan/ckan#3177]
### CKAN Version if known (or site URL)
Ubuntu 14.04 with CKAN version 2.5.2 installed from package.

### Please describe the expected behaviour
Private datasets should be displayed correctly in data explorer

### Please describe the actual behaviour
One column appears in data explorer with no data displayed.  Studying the http requests, it appears the frontend is proxying the request through jsonpdataproxy.appspot.com.  If the dataset is private, the request by the proxy fails.

### What steps can be taken to reproduce the issue?
Add a /private/ dataset containing CSV files.  Try to visualise the CSVs using Data Explorer.

### Requested solution
Is it possible to circumvent the proxy request?

Thanks.

**Comment by Aaron-M** [comment]
I also experienced this in CKAN 2.4.1.  A dataset that had previously been fine, I noticed was only displaying a single blank column when previwing the resource (in this case it was a tsv (tab separated) text file).  The record was set as Private.  I manually forced an upload to datastoe - and that worked, no erroers, but the preview still did not work. I temporarily changed the dataset to public, and hey presto the preview worked, after I changed the visibility back to private it continues to work.

**Comment by amercader** [comment]
Resources from private datasets won't be able to be display the previews if they are using jsondataproxy, as this is an external service to which the authorization headers are not forwarded. To display private datasets data must be on the DataStore http://docs.ckan.org/en/latest/maintaining/datastore.html. The DataStore it's also a much more reliable backend than jsondataproxy so I strongly encourage you to set it up.

**Comment by chrism0dwk** [comment]
Thanks Adrià, most helpful.  

Chris
