### ISSUE TITLE
fetch_consumer error: <User at 0x7f542635c350> is not bound to a Session; attribute refresh operation cannot proceed

### ISSUE THREAD

**Issue by francescomangiacrapa** [ckan/ckan#3183]
Hello *,
I'm trying to perform an harvesting between two CKAN.
CKAN gather works fine:
`
[ckanext.harvest.harvesters.ckanharvester] Creating HarvestObject for...
etc..
`

CKAN fetcher prints the following logs for all object received:
`
INFO  [ckanext.harvest.queue] Received harvest object id: 586407e8-59f5-4002-8512-04685708f016
DEBUG [ckanext.harvest.harvesters.ckanharvester] In CKANHarvester import_stage
DEBUG [ckanext.harvest.harvesters.ckanharvester] Using config: {u'read_only': True, u'api_version': 2, u'remote_orgs': u'create'}
DEBUG [ckanext.harvest.model] Instance <User at 0x7f542635c350> is not bound to a Session; attribute refresh operation cannot proceed
`

The problem seems the (sqlalchemy python) session (However, I'm not a python expert):

**Instance <User at 0x7f542635c350> is not bound to a Session; attribute refresh operation cannot proceed**

then the fetcher does not harvest nothing

My Configurations are:

- CKAN Version 2.5.1

- production.ini:

ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = false
ckan.auth.create_dataset_if_not_in_organization = false
ckan.auth.user_create_groups = false
ckan.auth.user_create_organizations = true
ckan.auth.user_delete_groups = true
ckan.auth.user_delete_organizations = true
ckan.auth.create_user_via_api = false
ckan.auth.create_user_via_web = true
etc.

I've also performed:
- apache2 restart/reload;
- postgresql service restart;
- kill and restart gather and fetcher services.

But the problem is still present!

Can you help me to reset/restart CKAN session (or in particular the fetcher consumer)? 
Thx a lot.

**Comment by amercader** [comment]
Closed in favour of https://github.com/ckan/ckanext-harvest/issues/262
