### ISSUE TITLE
Incorrect instance description on the CKAN instance page

### ISSUE THREAD

**Issue by haoliangyu** [ckan/ckan#3186]
In [CKAN instance list](http://ckan.org/instances/#), both [DadosRS](http://dados.rs.gov.br/) and [Data.rio](http://data.rio/) have the same description
```
Portal for the brazilian state Rio Grande do Sul. Using CKAN 2.2.
```
But the later one is actually the portal of Rio de Janeiro, not Rio Grande do Sul. Let me know where I can update it and I can submit a PR. I am working on a project that requires me to go through the list and may find more in the future.

**Comment by amercader** [comment]
Hi @haoliangyu, you can update the metadata used on the instances page by editing this JSON file: https://github.com/ckan/ckan-instances/blob/gh-pages/config/instances.json
