### ISSUE TITLE
Problems with relationships between packages

### ISSUE THREAD

**Issue by CostantinoPerciante** [ckan/ckan#3188]
### CKAN Version if known (or site URL)

2.5.1
### Please describe the expected behaviour

Given two datasets A and B, I made the following relationships tests (with child_of and parent_of relationships, but I guess that similar problems are present with the other relationships), by using the REST API  package_relationship_create http://docs.ckan.org/en/ckan-2.5.2/api/index.html?highlight=relationship#ckan.logic.action.create.package_relationship_create

| Subject | Object | Relation | Expected Result |
| --- | --- | --- | --- |
| A | B | parent_of | parent_of |
| B | A | parent_of | parent_of |
| B | A | child_of | child_of |
| A | B | child_of | child_of |
### Please describe the actual behaviour

The relationships that are actually created are the following ones. It seems that the child_of relationship is correctly managed (and correctly reversed when needed) but the parent_of is not

| Subject | Object | Relation | Correct |
| --- | --- | --- | --- |
| A | B | child_of | NO(reversed) |
| A | B | parent_of | NO |
| A | B | parent_of | YES(reversed) |
| A | B | child_of | YES |
### What steps can be taken to reproduce the issue?

see below for more details

**Comment by amercader** [comment]
The datasets (packages) relationships features has not been maintained in a long time. It will probably get deprecated and removed unless someone who is using it regularly does a proper audit and clean up. Feel free to investigate more and provide patches, but the members of the tech team are unlikely to have time to fix this.


Thanks!

**Comment by TkTech** [comment]
Alternatively, this would make a great extension since it doesn't necessarily have to live in the core.

**Comment by metaodi** [comment]
I'll look into this. I pretty sure it's because the "reverse types" are missing here: https://github.com/ckan/ckan/blob/e171528b8e4a9220dd3b2245a4b2a0a7d1a64a07/ckan/model/package_relationship.py#L47-L51

I'll use the package relationships for a new project, so I'll check if it'll work for me.

I can see both pros and cons for having it in core. I guess it all boils down to the question, if all parts that are in core need to be maintained by the core team or not.

**Comment by metaodi** [comment]
@CostantinoPerciante I was **not** able to reproduce your results. I tested this with 2.5.1, 2.5.2 and the current master branch.

I used the following command to create a relationships between two datasets "aa" and "bb":

dependency_of:
```bash
curl -X POST -H "Authorization: <API key>" -d '{"subject": "aa", "object": "bb", "type": "dependency_of"}' "http://ckan.dev/api/3/action/package_relationship_create"
```

parent_of:
```bash
curl -X POST -H "Authorization: <API key>" -d '{"subject": "aa", "object": "bb", "type": "parent_of"}' "http://ckan.dev/api/3/action/package_relationship_create"
```

For both cases, the correct "reverse" relationship was created as well:

```bash
curl -X GET "http://ckan.dev/api/3/action/package_relationships_list?id=bb"
```

```json
{
  "help": "http://ckan.dev/api/3/action/help_show?name=package_relationships_list",
  "success": true,
  "result": [
    {
      "comment": "",
      "object": "aa",
      "type": "child_of",
      "subject": "bb"
    },
    {
      "comment": "",
      "object": "aa",
      "type": "depends_on",
      "subject": "bb"
    }
  ]
}
```

Did you do something different?

**Comment by CostantinoPerciante** [comment]
These are the steps I followed (There is something different wrt the first post but there are still some misbehaviours):
1) Create fresh datasets A and B
2) Create relationship A parent_of B (OK)
3) Delete relationship at point 2) (OK)
4) Create relationship B parent_of A (FAILS: it recreates relationship at point 2 again...)
5) Delete relationship at point 4) (that means remove the one at point 2)
6) Create relationship B child_of A (OK, it creates A parent_of B)
7) Delete relationship at point 6) (That is remove A parent_of B)
8) Create relationship A child_of B (OK, it is created correctly)
9) Delete relationship at point 8) (OK!)
10) Restart at point 2... fails, it creates A child_of B

**Comment by fredpedro** [comment]
There is a problem with purging trash in the administration panel. It returns an error saying that it can't purge the package revision because of a foreign key in the "package_relationship_revision" table.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
