### ISSUE TITLE
Hitting enter on step two of dataset creation submits form and sends you back to step 1

### ISSUE THREAD

**Issue by shevski** [ckan/ckan#320]
1. Go to create a new dataset
2. Fill in name, click on next
3. type in an example or any URL and click enter
4. Screen takes you back to step one of your dataset, however, resource has been added
5. repeat
6. don't click enter to actually finish process and click on buttons
7. you get a page with multiple resources

![Screen Shot 2013-01-30 at 12 48 54](https://f.cloud.github.com/assets/1260289/110899/79dce1de-6adb-11e2-8716-0854c8ceaa77.png)

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
