### ISSUE TITLE
Deploying a Source Install references nonexistant activate_this.py script

### ISSUE THREAD

**Issue by Kyle-Falconer** [ckan/ckan#3202]
### CKAN Version if known (or site URL)
2.5.2 (source install)

### Please describe the expected behaviour

The script at `/usr/lib/ckan/default/bin/activate_this.py`  should exist and exist at that location if it is referenced in the documentation.

### Please describe the actual behaviour

The script at `/usr/lib/ckan/default/bin/activate_this.py` does not exist and there is nothing anywhere in the CKAN documentation about this file.

The file at `/usr/lib/ckan/default/bin/` does not exist as part of the source installation, so therefore the `activate_this.py` script cannot exist at that location. 

Additionally that file is nowhere to be found anywhere in the filesystem.

### What steps can be taken to reproduce the issue? 

Following the instructions on the [Installing CKAN from source](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) page, then follow the instructions on the [Deploying a Source Install](http://docs.ckan.org/en/latest/maintaining/installing/deployment.html) page to step 5.

Observe the WSGI script creation content. and attempt to locate the `activate_this.py` script within the operating system.

**Comment by Kyle-Falconer** [comment]
Looks like this is a non-issue... was caused by not using a virtualenv.

It would be nice if there were instructions for deploying without the use of virtualenv.

**Comment by amercader** [comment]
@Kyle-Falconer virtualenv is part of the supported installation process as it offers many advantages to  most scenarios. Of course you can choose not use it but we can't cover all scenarios in our instructions. 

Cheers

**Comment by Kyle-Falconer** [comment]
@amercader I get what you're saying, but I disagree that this is the best approach. I think virtualenv should be an "opt-in" choice rather than the default.

Over the last week I have been trying to deploy CKAN to AWS and also build up some Docker containers for CKAN using docker-compose (the official docker containers and the compose images are out of date and need to be re-written), and most of my troubles have come from variations in the virtual environment and with pip not being able to resolve dependencies, or with some dependencies being installed in certain directories but not being accessible on either the system level or in another module.

I think by default the Python dependencies should be handled at the system level, that way if someone wants to encapsulate the installation for development, they can do so with a virtualenv.

If a certain CKAN module requires a particular version of a dependency, virtualenv can be used within that module alone (I've run into situations where a module's dependency, or version of, conflicted with CKAN's dependencies.)
