### ISSUE TITLE
Delete Dataset Permanently  ? 

### ISSUE THREAD

**Issue by Prasanthmv** [ckan/ckan#3209]
How can delete ckan dataset Permanently   . I have deleted the dataset http://{my-ckanserver-url}/ckan-admin/trash . But still the PostgreSQL database size not decreasing . What will be the problem .  Please suggest a solution.

**Comment by TkTech** [comment]
Please use the IRC channel or the mailing list for these kinds of questions :)

In all common databases, simply removing a row does not cause the database to resize. Doing so would cause immense performance penalties and is often not what you actually want to happen.

I recommend you read the documentation available here - https://www.postgresql.org/docs/9.1/static/sql-vacuum.html
