### ISSUE TITLE
Update bleach requirement for released ckan

### ISSUE THREAD

**Issue by erlingbo** [ckan/ckan#3214]
### CKAN Version if known (or site URL)
2.5 from source

### Please describe the expected behaviour
everything working :)

### Please describe the actual behaviour
bleach 1.4.2 does not seem to have proper pinning of dependencies. HTML5Lib has changed, making it incompatible with older code. 
`ImportError: No module named sanitizer`

Updating bleach to 1.4.3 should fix this.  This is already done in master. 

### What steps can be taken to reproduce the issue? 
Install 2.5.* from source

**Comment by bribroder** [comment]
Also see https://github.com/ckan/ckan/pull/3181

**Comment by amercader** [comment]
Thanks @erlingbo. Fixed on the 2.5.3 branch

**Comment by erlingbo** [comment]
Hi. Could you please update the 2.5-latest branch as well?

**Comment by wardi** [comment]
@erlingbo that branch will be updated as soon as the 2.5 point release is out

**Comment by erlingbo** [comment]
thanks for the answer :)

Any estimate on when that will happen? I have failing tests for my plugin ;)

**Comment by wardi** [comment]
@erlingbo as a stopgap you can add the same requirement to your extension's setup for its tests

**Comment by davidread** [comment]
This change also fixed a problem we had with ckanext-harvest. html5lib-0.999999999 was demanding a newer version of setuptools than travis gave it by default:

    html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 12.0.5)

 But hacking the build script to use ckan branch release-2.5.3, it gets bleach 1.4.3 and now pulls in html5lib-0.9999999 which doesn't have this error.

https://travis-ci.org/ckan/ckanext-harvest/jobs/160993944

I won't merge the ckanext-harvest hack though, but rest assured it'll go green when the ckan release is done.
