### ISSUE TITLE
Anonymous user should be redirected to login page when trying to access /dashboard instead of "404 Not Found" page.

### ISSUE THREAD

**Issue by gleb-rudenko** [ckan/ckan#3220]
### CKAN Version if known (or site URL)

All versions.
### Please describe the expected behaviour

When anonymous user tries to access /dashboard page, CKAN redirects him to login page.
### Please describe the actual behaviour

When anonymous user tries to access /dashboard page, CKAN returns "404 Not Found" page.
### What steps can be taken to reproduce the issue?

While not logged in try to access /dashboard page, you will face "404 Not Found".

**Comment by wardi** [comment]
I'm ok with the current behaviour.

Some sites will include text in their 404 page like "We can't seem to find the page you're trying to access, maybe you need to log in to see it? [login form]" Maybe that would solve your problem more generally?

**Comment by gleb-rudenko** [comment]
I think the redirection behaviour would be more user intuitive, so instead of saying to user that the page does not exist, we'll tell them that the page does exist BUT you'll need to login to view it.

**Comment by wardi** [comment]
fixed by #3224
