### ISSUE TITLE
More values in state field of dataset?

### ISSUE THREAD

**Issue by yongjiel** [ckan/ckan#3222]
### CKAN Version if known (or site URL)
2.5.2

### Please describe the expected behaviour
Can we have more states for the state field? We require that field has more values, like 'modified', 'pending', 'rejected', 'approval', 'published'.  Can the ckan core make it easy to changed or have to override in my own extension?

### Please describe the actual behaviour
Currently I can find that state fields has values "draft", "active", "deleted".  We can actually fill in more values when submit dataset, such like "OK". But if we do that, the record is not shown up in UI. 

### What steps can be taken to reproduce the issue? 
Use package_create,   it will be able to post data with that state field with "OK".

**Comment by amercader** [comment]
Updating the default `state` field may have unintended consequences, as some features like showing the relevant datasets in the search results rely on it., or the record not showing up on the UI as you described. I recommend that you use a custom field on your own schema to deal with any workflow needs that you have. Does this make sense?

**Comment by yongjiel** [comment]
Got it. thanks
