### ISSUE TITLE
Access level: portal members?

### ISSUE THREAD

**Issue by donthebike** [ckan/ckan#3227]
We are looking for a way to provide a third level of access to datasets besides Public and Private.
We want some datasets to be open to all portal members only.

Is there a way to do this or is someone working on such functionality?

**Comment by wardi** [comment]
@donthebike you might be looking for #3192 

It should be very easy to make an IPermissionLabels plugin that adds a "portal-members" label. There's an example in that PR here https://github.com/ckan/ckan/pull/3192/files#diff-31d39df909b2876cdd26aa71a97fbcb5R8

**Comment by wardi** [comment]
I'm going to close this because ckan-dev is a better place for technical discussions than our issue tracker
