### ISSUE TITLE
Reset link not including site_url

### ISSUE THREAD

**Issue by erlingbo** [ckan/ckan#3230]
### CKAN Version if known (or site URL)

master
### Please describe the expected behaviour

The reset email should include the complete link to reset a users password. e.g  http://mydomain.com/user/reset/<id>?key=<somekey>
### Please describe the actual behaviour

The email only includes the subpath. e.g  /user/reset/<id>?key=<somekey>
### What steps can be taken to reproduce the issue?

Try to send a password recovery email.

I think the fix lies in https://github.com/ckan/ckan/blob/master/ckan/lib/mailer.py#L147 Shouldn't it use `ckan.site_url` instead of just `site_url`

**Comment by torfsen** [comment]
The code should probably just pass `qualified=True` to `url_for` instead of manually adding the host.
