### ISSUE TITLE
Multiple background jobs that access the database fail

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3243]
(This problem was originally reported by @wardi in #3165)

Accessing the database from a background job succeeds once, but subsequent runs of the same job fail:
```
DatabaseError: (DatabaseError) SSL error: decryption failed or bad record mac
 ```

**Comment by TkTech** [comment]
An `engine.dispose()` at the start of the task should be the "quick" fix. Ideally each worker gets its own engine and thus its own pool.

**Comment by torfsen** [comment]
For me, calling `ckan.model.meta.engine.dispose()` in the worker's child process after forking solves the problem within the worker, but afterwards database access in the main process fails with a
```
OperationalError: (OperationalError) SSL connection has been closed unexpectedly
```
Not sure if we also need to reset some stuff in the main process, although I don't see a reason why that should be necessary as of now. 

However, in addition to SQLAlchemy's non-support for forks (which requires the call to `engine.dispose`), there may be [issues with SSL and forking](https://github.com/ui/django-rq/issues/123). I haven't examined that in detail, yet.
