### ISSUE TITLE
datastore_active is being rewritten due to race condition

### ISSUE THREAD

**Issue by ZtF** [ckan/ckan#3245]
### CKAN Version if known (or site URL)

2.5.2
### Please describe the expected behaviour

When file resource saved to FileStore, datapusher is notified about it, downloads the resource, process the file, create new table in DataStore and sets datastore_active flag for the particular resource. 
### Please describe the actual behaviour

It's working as described, though when uploading multiple resources (eg. through API), there is a race condition probably in `ckan.lib.dictization.model_save.package_dict_save` (or somewhere in the stack trace).
Sometimes the problem can even produce "Resource not found" in logs though it's most certainly there at the time. That's a case where datapusher tries to patch the resource and set datastore_active to True.
### What steps can be taken to reproduce the issue?

In httpd conf file, the race condition can be "resolved" with forcing one process and one thread for CKAN.
Something like this in ckan httpd config file:
`
WSGIDaemonProcess ckan display-name=ckan processes=1 threads=1
`
If it's eg. 15 threads and 2 processes, the described issue appears.

**Comment by torfsen** [comment]
This might be the same issue as ckan/datapusher#100.

**Comment by wardi** [comment]
A nice solution would be to make package_update atomic, but that needs a new error class (and API version) for conflicts that should be retried.

A less-nice solutions is making sure datapusher only updates one resource at a time per dataset. Not a perfect solution, but will be much less likely to fail.

A quick hack would be to sneak the datastore_active change past package_patch/package_update so it doesn't update all the other dataset metadata fields, then make sure to re-index the dataset.

**Comment by amercader** [comment]
> to sneak the datastore_active change past package_patch/package_update

@wardi what do you mean by this?

**Comment by wardi** [comment]
@amercader package_patch calls package_show+package_update to change the values passed. When the datastore just needs to set datastore_active=True on a resouce that's a lot of extra work and a much larger chance of conflict with action in progress.

Skipping all the validation and work done by package_update by changing the model directly would be a layering violation, but I could see the argument for it in this case, and it's unlikely to harm any real ckan instances. We are already doing something like this in our bulk actions that set the state to public/private.

**Comment by amercader** [comment]
I see, sounds very sensible. +1

**Comment by wardi** [comment]
I might not get to this very quickly, so if someone wants to submit a PR, here is the code that bulk updates the dataset private flag without going through package_update: https://github.com/ckan/ckan/blob/master/ckan/logic/action/update.py#L1138-L1149

And the place we need the resource-updating code is: https://github.com/ckan/ckan/blob/master/ckanext/datastore/logic/action.py#L147-L153

**Comment by smotornyuk** [comment]
While i tried to reproduce issue, i wrote script that creates ~20 resource in different threads and it turned out that just one resource appears in package(as result of this issue). So i decided, that quickest fix won't work - it solution just for datastore. And i implemented simplest(but, in other hand, there are less chances to break anything) decorator for atomic actions that uses conditional lock. How about this?

(but i don't know how to test it... creating threads inside CKAN test looks quite cumbersome...)

**Comment by wardi** [comment]
@ZtF are you able to reproduce the issue with the #3331 applied?

**Comment by janantk** [comment]
Hi @wardi, #3331 solved the original issue, but we discovered that the same race condition appears when deleting a resource (and setting datastore_active flag to False). I took the simplest approach and applied the code from #3331 to this case too, see #3481.

**Comment by wardi** [comment]
mitigated by #3331 and #3481

**Comment by ThrawnCA** [comment]
> Skipping all the validation and work done by package_update by changing the model directly would be a layering violation, but I could see the argument for it in this case, and it's unlikely to harm any real ckan instances.

This has now come back to bite `ckanext-xloader` as a result of the changes made by #8395.

**Comment by wardi** [comment]
@ThrawnCA thanks for pointing this out. xloader will need to be updated to use `resource_patch` to set `datastore_active` so that it gets indexed properly with this change.
