### ISSUE TITLE
could not store dataset and data to default_datastore database on ckan web interface

### ISSUE THREAD

**Issue by yagi815** [ckan/ckan#3248]
### CKAN Version if known (or site URL)
ckan 2.2.1 + solr 3.6 + postgresql 9.1 + rhel 6.6

### Please describe the actual behaviour

If i add new dataset by ckan web interface, the datasets are stored ckan_default database not datastore_default in postgresql. 

Also I could not see any dataset which stored in datastore_default database in ckan webpage .

### What steps can be taken to reproduce the issue? 

This is my contents of my ini

[DEFAULT]
debug = false
[server:main]
use = egg:Paste#http
host = 0.0.0.0
port = 5000
[app:main]
use = egg:ckan
full_stack = true
cache_dir = /tmp/%(ckan.site_id)s/
beaker.session.key = ckan
beaker.session.secret = RbprKOc/E2EAsG8D6e1J7volk
app_instance_uuid = {50507179-94cd-4a8c-9492-53c0f5188ceb}
who.config_file = %(here)s/who.ini
who.log_level = warning
who.log_file = %(cache_dir)s/who_log.ini
sqlalchemy.url = postgresql://ckan_defaul:tMYPASS@localhost/ckan_default
ckan.datastore.write_url = postgresql://ckan_default:MYPASS@localhost/datastore_default
ckan.datastore.read_url = postgresql://datastore_default:MYPASS@localhost/datastore_default
ckan.site_url = http://default.inje.com
ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = true
ckan.auth.create_dataset_if_not_in_organization = true
ckan.auth.user_create_groups = true
ckan.auth.user_create_organizations = true
ckan.auth.user_delete_groups = true
ckan.auth.user_delete_organizations = true
ckan.auth.create_user_via_api = false
ckan.auth.create_user_via_web = true
ckan.auth.roles_that_cascade_to_sub_groups = admin
ckan.site_id = default
solr_url = http://127.0.0.1:8080/solr/core0
ckan.plugins = stats text_preview recline_preview datastore datapusher synchronous_search
ckan.site_title = CKAN
ckan.site_logo = /base/images/ckan-logo.png
ckan.site_description =
ckan.favicon = /images/icons/ckan.ico
ckan.gravatar_default = identicon
ckan.preview.direct = png jpg gif
ckan.preview.loadable = html htm rdf+xml owl+xml xml n3 n-triples turtle plain atom csv tsv rss txt json
ckan.locale_default = en
ckan.locale_order = en pt_BR ja it cs_CZ ca es fr el sv sr sr@latin no sk fi ru de pl nl bg ko_KR hu sa sl lv
ckan.locales_offered =
ckan.locales_filtered_out = en_GB
ckan.feeds.authority_name =
ckan.feeds.date =
ckan.feeds.author_name =
ckan.feeds.author_link =
ckan.storage_path = /var/lib/ckan
ckan.max_resource_size = 10
ckan.max_image_size = 2
ckan.datapusher.url = http://127.0.0.1:8800/
email_to = you@yourdomain.com
error_email_from = paste@localhost
smtp.server = localhost
smtp.starttls = False
[loggers]
keys = root, ckan, ckanext
[handlers]
keys = console
[formatters]
keys = generic
[logger_root]
level = WARNING
handlers = console
[logger_ckan]
level = INFO
handlers = console
qualname = ckan
propagate = 0
[logger_ckanext]
level = DEBUG
handlers = console
qualname = ckanext
propagate = 0
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s

Am I missing any configuration? 
Anybody have an idea for my issues?

Thanks.
Daniel.

**Comment by amercader** [comment]
@yagi815 in the future please use the [mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the `ckan` tag on StackOverflow to ask this kind of support requests.

The datastore database holds data for certain types of resources, eg CSV or Excel files (not datasets). If you mean that for this resources data is not automatically imported to the datastore you might have some issues with the DataPusher.

I strongly encourage you to upgrade to the latest CKAN version, as CKAN 2.2 is no longer supported.

Please follow up in the mailing list to get more help.

Thanks!
