### ISSUE TITLE
Add interface for database engine/process initialization

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3249]
In #3243 it became clear that we need to re-initialize the SQLAlchemy engine on background job processes. That's easy for CKAN's core database, but it also needs to be done for the datastore database (in case that's being used) and, potentially, for other resources introduces by extensions which cannot be shared among processes. We therefore need a way to let extensions re-initialize things after a fork.

For that we need to check how such a per-process initialization relates to the existing [`IConfigurable.configure`](http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IConfigurable), which is currently called once during startup by `load_environment`: Is it enough to call `IConfigurable.configure` after a fork or do we need a separate interface function?

**Comment by wardi** [comment]
If `IConfigurable.configure` is all datastore needs to set up its engine let's use that. We could add a note in the interface docs to say that this is the appropriate place to initialise resources that can't be shared between processes.

**Comment by torfsen** [comment]
Re-using `IConfigurable.configure` would be the easiest way, but I'm wondering whether there are cases where you want to do some initialization once during startup but not after forking. But I guess even if there are any then one can always check inside the initialization code whether the relevant fields already have been initialized.

**Comment by wardi** [comment]
Yes, and I think this interface already gets called multiple times from tests that change the configuration, right? Let's just better document when it will be called and leave it up to the extension to do the right thing.

**Comment by torfsen** [comment]
This has been fixed by #3247.
