### ISSUE TITLE
what is purpose of default_datastore database?

### ISSUE THREAD

**Issue by yagi815** [ckan/ckan#3251]
### CKAN Version if known (or site URL)
2.2.1

In ckan installation guide, have to create two database (ckan_default, datastore_default)

I set datastore seting in configuration file then I create new dataset by ckan web interface.
But all datasets are stored in ckan_default database not datastore_default database.
The datastore_default database is empty. How to use datastore_default database for dataset?

This is snippet of my ini configuration files

sqlalchemy.url = postgresql://ckan_default:PASS@localhost/ckan_default
ckan.datastore.write_url = postgresql://ckan_default:PASS@localhost/datastore_default
ckan.datastore.read_url = postgresql://datastore_default:PASS@localhost/datastore_default
ckan.datastore.default_fts_lang = english
ckan.datastore.default_fts_index_method = gist
ckan.site_url = http://ckan.inje.com
ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = false
ckan.auth.create_dataset_if_not_in_organization = false
ckan.auth.user_create_groups = false
ckan.auth.user_create_organizations = false
ckan.auth.user_delete_groups = true
ckan.auth.user_delete_organizations = true
ckan.auth.create_user_via_api = false
ckan.auth.create_user_via_web = true
ckan.auth.roles_that_cascade_to_sub_groups = admin
ckan.site_id = default
solr_url = http://127.0.0.1:8080/solr/core0
ckan.redis.url = redis://localhost:6379/0
ckan.plugins = datastore stats text_view image_view recline_view
ckan.views.default_views = image_view text_view recline_view

**Comment by amercader** [comment]
The datastore_default database is used to store actual data (not metadata) from tabular resources of certain formats (CSV, Excel, etc). You need to have the DataStore and the DataPusher set up and enabled for it to work. Please check the documentation to learn more: http://docs.ckan.org/en/latest/maintaining/datastore.html

**Comment by Gauravp-NEC** [comment]
@amercader , Did DataStore have a Linux process or its a background job? Did DataStore database i.e., datastore_default have connection with CKAN database i.e., ckan_default??
