### ISSUE TITLE
no module named datetime

### ISSUE THREAD

**Issue by Moqri** [ckan/ckan#3255]
When trying to install ckan from package (http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html), at the step 4:
sudo dpkg -i python-ckan_2.5-trusty_amd64.deb on ubunto 16.04 running from a virtualbox 
results in the following error:
no module named datetime.

Full Error:
Setting up python-ckan (2.5.2-trusty3) ...
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 7, in <module>
    from paste.script.command import run
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 3, in <module>
    import pkg_resources
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import plistlib
  File "/usr/lib/python2.7/plistlib.py", line 62, in <module>
    import datetime
**ImportError: No module named datetime**
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
Enabling site ckan_default.
To activate the new configuration, you need to run:
  service apache2 reload
Enabling site datapusher.
To activate the new configuration, you need to run:
  service apache2 reload

**Comment by Moqri** [comment]
1- pip/easy_install datetime doesn't help
2- replacing the virtualenv python with another copy of python does't help

**Comment by wardi** [comment]
would you post the full error you're seeing? 'no module named datetime' is very strange.

**Comment by Moqri** [comment]
I already did. This is the full error:
Full Error:
Setting up python-ckan (2.5.2-trusty3) ...
Traceback (most recent call last):
File "/usr/lib/ckan/default/bin/paster", line 7, in 
from paste.script.command import run
File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 3, in 
import pkg_resources
File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/init.py", line 36, in 
import plistlib
File "/usr/lib/python2.7/plistlib.py", line 62, in 
import datetime
ImportError: No module named datetime

**Comment by torfsen** [comment]
Strange. There are some posts regarding this issue ([1](http://askubuntu.com/questions/509283/python-no-module-named-datetime), [2](http://stackoverflow.com/questions/26031160/importerror-no-module-named-datetime)) and they boil down to virtualenvs invalidated by package updates. Did you try to remove your virtualenv and rebuild it from scratch?

**Comment by Moqri** [comment]
Thanks torfsen,
Yes, but regardless of my virtualenv, it seems the sudo dpkg -i python-ckan_2.5-trusty_amd64.deb command create it's own virtualenv (under /usr/lib/ckan/default) with a copy of python with no datetime package. Even when I follow this trick mentioned it your number 2 ref: 
$ cp /usr/bin/python2.7 $(which python2.7)
The command replace the python and revert it to the old veriosn

**Comment by amercader** [comment]
As mentioned in the [documentation](http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html) Ubuntu packages are currently targeting Ubuntu 14.04 (trusty), so the problem is likely caused by trying to install it on 16.04.

If you have time, it should be easy to update the packaging scripts to support 16.04, generate some test packages and make sure they work as expected: https://github.com/ckan/ckan-packaging

Let me know if you are interested and I can give you a hand getting started.

**Comment by terchris** [comment]
Having the same problem when installing on Ubuntu 16.04.

**Comment by ashishsingal1** [comment]
Same issue 16.04. Is that the issue? Do we downgrade to 14.04 to get this working?

**Comment by TkTech** [comment]
See https://github.com/ckan/ckan/pull/3544 for updated source install instructions. An updated package will likely come after this.

If at all possible I always highly recommend you just install from source. It is simple and reliable across all platforms and versions.

**Comment by carlitosfioravante** [comment]
Same issue in Ubuntu 14.04 using: sudo dpkg -i python-ckan_2.6-trusty_amd64.deb

**Comment by flazx** [comment]
Same issue 16.04.

**Comment by arifulhaqueuc** [comment]
Same issues faced in building Python/Flask app in Ubuntu 16.04

**Comment by namgk** [comment]
any update here? I think the problem still exists in Ubuntu 16.04 package install.
