### ISSUE TITLE
Documentation does not show how to get resource id

### ISSUE THREAD

**Issue by Kyle-Falconer** [ckan/ckan#3256]
### CKAN Version if known (or site URL)
latest (2.5.2)

### Please describe the expected behaviour
Resource IDs are used throughout the API, particularly of note is with [resource_update](http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.update.resource_update), which the documenation shows the example usage as being:

    http --json POST http://demo.ckan.org/api/3/action/resource_update id=<resource id> upload=@updated_file.csv Authorization:<api key>

There should be a link or some additional information showing how to get this value to pass in as `<resource id>`.

The API does return the resource id when getting information about a dataset (as shown in this SO post about how to [obtain a dataset id/name of a resource in CKAN via a single API call](http://stackoverflow.com/questions/32899459/obtain-a-dataset-id-name-of-a-resource-in-ckan-via-a-single-api-call)), so this or alternative methods should be described in the documentation.

### Please describe the actual behaviour

The documentation does not show how to get the resource id.

### What steps can be taken to reproduce the issue? 

Visit the documentation and look for anything that shows how to get this resource id.

**Comment by amercader** [comment]
That sounds very reasonable, do you want to send a quick PR updating the `resource_update` [docstring](https://github.com/ckan/ckan/blob/master/ckan/logic/action/update.py#L45) to mention how to get the id from `package_show` (this is where the docs are generated from)?

**Comment by amercader** [comment]
Closing for now, @Kyle-Falconer feel free to reopen if you find time to send that documentation change
