### ISSUE TITLE
Organizations are sorted by name instead of title.

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#3259]
### CKAN Version if known (or site URL)

2.5.2
### Please describe the expected behaviour

Organizations should be sorted by title since the title is the shown value in web interfaces.
### Please describe the actual behaviour

Organizations are sorted by name by default without any selected sorting and in the sorting dropdown.
### What steps can be taken to reproduce the issue?

Create or modify organizations so that its title starts with different letter than its name. Open Organizations list and the organization is in position which does not make sense with the shown data.

**Comment by gleb-rudenko** [comment]
@amercader, I can take a look at it.

**Comment by gleb-rudenko** [comment]
@amercader , PR is ready for this issue, its quite straightforward.

**Comment by Engerrs** [comment]
Hi @amercader , can this update be backported to CKAN 2.5 and CKAN 2.6.

**Comment by MasaGon** [comment]
Sorting by title is so embarrassing for multi-byte languages. We Japanese use MB characters for title and name is alphabetic only. MB characters are sorted with its character codes that is totally not associated with semantics nor pronunciation. In Addition, API specification says default is "name asc". I personally think it should return back to "name asc". (I found this problem when updating from 2.5)
