### ISSUE TITLE
Documentation: get latest added resources

### ISSUE THREAD

**Issue by orinciog** [ckan/ckan#3262]
Hi,

I want to retrieve latest added resources (not datasets) from a ckan instance from a timestamp, using API. 

I saw that there is a function "revision_list", that retrieves all revisions after a timestamp, but there is no function to see what resources are in that revision.

"revision_show" shows only metadata about one resource_id (packages, message), but it doesn't show the added resources.

So my question is how to retrieve latest added resources, using the API?

Thank you,

**Comment by amercader** [comment]
I'm afraid that's not available via the API. The closest I can think of is keep track of the latest modified datasets and check if they are new or the resources in them changed.
