### ISSUE TITLE
Data invalid error while the data is valid

### ISSUE THREAD

**Issue by moqri** [ckan/ckan#3263]
### CKAN Version if known (or site URL)

http://52.41.50.184/dataset/california-01/resource_data/09e74ee2-19ea-4fe5-bb41-12170bfefb55
### Please describe the actual behaviour

Data invalid error
### What steps can be taken to reproduce the issue?

Download and upload the file on CKAN

Error: The data was invalid (for example: a numeric value is out of range or was inserted into a text field). 
HTTP status code: 409 
Response: {"help": "http://52.41.50.184/api/3/action/help_show?name=datastore_create", "success": false, "error": {"message": "The data was invalid (for example: a numeric value is out of range or was inserted ... 
Requested URL: http://52.41.50.184/api/3/action/datastore_create

**Comment by Moqri** [comment]
The data is valid since when I split the data into 2, I can upload them without any issue

**Comment by Moqri** [comment]
Found the issue!
If there is a white space (" ") in a column where all other values are numeric, DataPusher will determine that column as a numeric and then it choke when it reaches the row with a white space!

**Comment by Moqri** [comment]
Any fix for the code (without changing my data)?

**Comment by amercader** [comment]
This looks like a DataPusher error, probably guessing the type of one of the fields incorrectly. Can you check the Datapusher log for more clues?

**Comment by davidread** [comment]
This is covered in: https://github.com/ckan/datapusher/issues/48
