### ISSUE TITLE
Users are not removed in related tables (i.e. Institution users) if the main user entry is deleted

### ISSUE THREAD

**Issue by tsufz** [ckan/ckan#3265]
### CKAN Version if known (or site URL)
2.4

### Please describe the expected behaviour
An user assigned to different organisations / roles should be removed from each group / role if the user is deleted. If not, zombie user entries persist in the system.

### Please describe the actual behaviour
The users are not deleted from groups / roles if the main user entry is deleted.

### What steps can be taken to reproduce the issue? 
Check the relations between main user tables and the related tables. In detail, is the relation a real relational one or not (is the delete flag set or not)?

**Comment by amercader** [comment]
Fix in #3284, would be great if you could test it
