### ISSUE TITLE
ne translations have been merged incorrectly

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3270]
It seems that [`ckan/i18n/ne/LC_MESSAGES/ckan.po`](https://github.com/ckan/ckan/blob/dbf5173c1b8c2e64048435de35d190e47441ac29/ckan/i18n/ne/LC_MESSAGES/ckan.po) has been merged incorrectly, the file still contains Git conflict markers. The offending commit seems to be 8f38725138e629c22a6d2170b7cb00c9e778f66f by @amercader. As far as I can tell the other files in that commit are fine.

**Comment by amercader** [comment]
PR is here: https://github.com/ckan/ckan/pull/3246 @TkTech maybe you can push the button on that one?

**Comment by torfsen** [comment]
@amercader Must have missed that one, sorry for the noise!
