### ISSUE TITLE
Update a datastore resource from UI results in broken resource

### ISSUE THREAD

**Issue by namgk** [ckan/ckan#3277]
### CKAN Version if known (or site URL)

2.5.2
### Please describe the expected behaviour

Should be able to modify metadata of a resource created via Datastore API from the CKAN web interface.
### Please describe the actual behaviour

When modify a Datastore resource from the web interface, it is immediately that the resource cannot be viewed from the default viewer. 
### What steps can be taken to reproduce the issue?
1. Use datastore API to create a datastore resource
2. Use datastore API to insert some records to the newly created resourrce
3. View the resource on CKAN web interface (the default data explorer)
4. Click on Manage, add or modify some descriptions
5. Click Update Resource to save the changes
6. Get back to the data viewer at step 3.
7. Nothing shows up!

**Comment by amercader** [comment]
I believe this was fixed by #3012, which was backported to 2.5.3

Can you upgrade and see if that solves the issue? For resources where you already "lost" the datastore_active flag the easiest is to resubmit them again to the DataStore.

**Comment by namgk** [comment]
thanks
