### ISSUE TITLE
Users shouldn't be able to create datasets without a organization

### ISSUE THREAD

**Issue by gallexme** [ckan/ckan#3278]
### CKAN Version if known (or site URL)
2.5.1

### Please describe the expected behaviour
Users shouldn't be able to create datasets without a organization when
ckan.auth.create_dataset_if_not_in_organization is false

### Please describe the actual behaviour
Users still can create Datasets without a Organization

### What steps can be taken to reproduce the issue? 
ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = false
ckan.auth.create_dataset_if_not_in_organization = false
ckan.auth.user_create_groups = false
ckan.auth.user_create_organizations = false
ckan.auth.user_delete_groups = false
ckan.auth.user_delete_organizations = false
ckan.auth.create_user_via_api = false
ckan.auth.create_user_via_web = false
ckan.auth.roles_that_cascade_to_sub_groups = admin

**Comment by amercader** [comment]
Can you provide the exact way in which you are creating the dataset? Is it via the UI or via the API?

This might have been solved in https://github.com/ckan/ckan/pull/3054

p.s Please ugprade to the latest [patch release](http://docs.ckan.org/en/latest/maintaining/upgrading/upgrade-package-to-patch-release.html) if you can

**Comment by gallexme** [comment]
UI
Datasets
->Create Dataset

**Comment by amercader** [comment]
I tried to reproduce this with your exact same version and with these settings. The only way I could get the Create Dataset button to show up was with the user being a Sysadmin (which makes sense as they have all permissions). On newer versions that include #3054 you'll get a message that you need to create an organization first.

Let me know if this makes sense and feel free to reopen if there's another issue
