### ISSUE TITLE
LanguageError: IOError: [Errno 2] No translation file found for domain: 'ckan'

### ISSUE THREAD

**Issue by coreyerickson** [ckan/ckan#3282]
Hi, 

We are noticing some 500 errors are being generated when  /e or /n are being passed instead of /en

Passing other letters such as /a /b /c will trigger a 404

### CKAN Version if known (or site URL)
Ckan 2.3.X -  2.5.2+

### Please describe the expected behaviour

http://demo.ckan.org/en = 200
http://demo.ckan.org/e = 404
http://demo.ckan.org/n = 404

### Please describe the actual behaviour

http://demo.ckan.org/en = 200
http://demo.ckan.org/e = 500
http://demo.ckan.org/n = 500

### What steps can be taken to reproduce the issue? 

pass /e or /n in any ckan instance url and you can trigger a 500 internal server error.

http://demo.ckan.org/en/dataset = 200

http://demo.ckan.org/e/dataset = 500

**Comment by amercader** [comment]
Good catch @coreyerickson. Fix is in #3285
