### ISSUE TITLE
Error 500: An internal server error occurred

### ISSUE THREAD

**Issue by arquelaup** [ckan/ckan#3283]
Hi all, 

I've recently installed CKAN (2.5.2) on my Windows machine, but in the "datasets" tab, I get `There was an error while searching. Please try again.`.
I also get the error below when trying to access some parts of CKAN (I get this when clicking in 'view profile', for example).

```

    Server Error

    An internal server error occurred
```

As I am a complete beginner, I dont know where to find the log file in Windows to provide more info, so I would also appreciate if anyone could give me instructions on where to find this file so I can give you more details.

Thank you.

**Comment by rahul-nath** [comment]
Did you figure out the solution to this problem?

**Comment by goparklubanic** [comment]
I have the same problem. running ckan 2.7.2. Error 500 always occured after submitting data from a form. But the submitted data stored in database.
Here is the contoent of error.log:
[Tue Oct 31 23:05:58.543759 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363] mod_wsgi (pid=29257): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Tue Oct 31 23:05:58.543801 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363] Traceback (most recent call last):
[Tue Oct 31 23:05:58.543822 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 136, in __call__
[Tue Oct 31 23:05:58.543861 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     return self.apps[app_name](environ, start_response)
[Tue Oct 31 23:05:58.543875 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
[Tue Oct 31 23:05:58.543894 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     return self.apps[-1](environ, start_response)
[Tue Oct 31 23:05:58.543905 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 61, in __call__
[Tue Oct 31 23:05:58.543929 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     return self.app(environ, start_response)
[Tue Oct 31 23:05:58.543969 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
[Tue Oct 31 23:05:58.544030 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     app_iter = self.application(environ, start_response)
[Tue Oct 31 23:05:58.544049 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 117, in __call__
[Tue Oct 31 23:05:58.544073 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     wrapper.finish_response(remember_headers)
[Tue Oct 31 23:05:58.544084 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 177, in finish_response
[Tue Oct 31 23:05:58.544110 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     write = self.start_response(self.status, headers, self.exc_info)
[Tue Oct 31 23:05:58.544134 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363] TypeError: expected byte string object, value of type unicode found

**Comment by aliwaqas333** [comment]
any solutions yet?
