### ISSUE TITLE
[Question] GitHub Branches

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3289]
Why is there so many branches?

**Comment by torfsen** [comment]
According to the [contribution guidelines](http://docs.ckan.org/en/latest/contributing/pull-requests.html), each pull request should be contained in a separate branch. While the branch can be deleted after the PR has been merged this is often forgotten.

**Comment by deinok** [comment]
Exact, somebody should delete Merged/Closed Branchs

**Comment by amercader** [comment]
We'll try to be more mindful of deleting merged branches. If someone is really interested on **safely** cleaning up the core repo of old branches please go ahead (ping other devs first)
