### ISSUE TITLE
Docker - Automated Build

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3290]
Automated build of ckan/postgresql and ckan/solr are the same as ckan/ckan

As you can see:
 [https://hub.docker.com/r/ckan/postgresql/~/dockerfile/](https://hub.docker.com/r/ckan/postgresql/~/dockerfile/)
[https://hub.docker.com/r/ckan/solr/](https://hub.docker.com/r/ckan/solr/)

Automated build of postgresql should point to: https://github.com/ckan/ckan/blob/master/contrib/docker/postgresql/Dockerfile

Automated build of solr should point to:
https://github.com/ckan/ckan/blob/master/contrib/docker/solr/Dockerfile

@wardi I think you should have the right permissions to change it ;)

**Comment by wardi** [comment]
Hmm. In "build settings" the Dockerfile location is set to: `/contrib/docker/solr` for branch master of ckan/solr and `/contrib/docker/postgresql` for postgresql. Did I not enter it in the right place?

**Comment by deinok** [comment]
Mmm seems like the location its okey. I will make a try and post images of the settings

**Comment by wardi** [comment]
I've given you "write" access on docker hub, does that let you make the changes yourself?

**Comment by deinok** [comment]
@wardi Ok, seems like I have some type of access to cloud.docker but the changes must be done in hub.docker :(

Try to change `/contrib/docker/solr` to `/contrib/docker/solr/` and `/contrib/docker/postgresql` to `/contrib/docker/postgresql/`

If didn't work, i will post images of the settings :)

**Comment by wardi** [comment]
I've upped your permission to admin on each of the images, mind trying again?

**Comment by deinok** [comment]
@wardi Fixed :)

**Comment by wardi** [comment]
Was it the trailing slash? We've got a branch now for the the latest work on the 2.6 release: `dev-2.6`, do you want to start building that now too?

**Comment by deinok** [comment]
Yes, the only change is put the / at the end of the path.

Do you want a 2.6 docker build without touching the master build? I can configure it

**Comment by wardi** [comment]
yes a dev-2.6 build would be great, and once the release is out one for 2.6-latest too.

**Comment by deinok** [comment]
@wardi Done. New tag is "dev-2.6" from branch "dev-2.6"

Bugfixing and Redist support should be done in "master" or "dev-2.6" branch?

**Comment by wardi** [comment]
redist support? bugs are always fixes on master first then backported to dev-X.X branches in preparation for the next point release

**Comment by deinok** [comment]
Well, seems like Redist Support is going to be done.

In the installation instructions here ->[http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#install-the-required-packages](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#install-the-required-packages)

The last package of apt-get is redist.

And the .ini of ckan creates a `#ckan.redis.url = redis://localhost:6379/0
`

**Comment by wardi** [comment]
oh, redis! yes, master and the future 2.7 will need a redis image for sure. If you've got time to add that we really do need one of those, or we might be able to depend on an official image.

**Comment by amercader** [comment]
The [official Redis](https://hub.docker.com/_/redis/) image should be fine for that, we don't need any customization.

@deinok Are there any major issues left for Docker support? If we are confident it works we should re-add it to the installation documentation as an option.

Also going forward it would be great to have some kind of automated tests that check that the images build fine (I guess the automated builds on docker hub can help with that) but also that CKAN works (eg no Solr schema problems etc). Any ideas on how to do that?

**Comment by deinok** [comment]
@amercader There are some issues with dev-2.6 and master. I'm working on it :)

Also, is redis connection a mandatory for CKAN-master? Seems like it try to connect even if the option in the .ini is disabled

**Comment by amercader** [comment]
Redis is a requirement on Master yes. If you don't define a value on the ini file a default connection will be used.

Can you briefly list what issues do you have? We might be able to help with them.
