### ISSUE TITLE
Create a file filesize function as a part of iUploader interface

### ISSUE THREAD

**Issue by gleb-rudenko** [ckan/ckan#3292]
### Please describe the expected behaviour
This PR was merge https://github.com/ckan/ckan/pull/3205 recently, and it works great!
The only problem is that other extensions that override the default upload functionality don't have those alts, and it would be cool to implement a function that would be a part of an interface so that further extensions development will require this function.

**Comment by amercader** [comment]
@gleb-rudenko If I remember correctly, the IUploader interface just returns an Uploader class. In the default uploader that was modified in #3205 the `self.filesize` and `self.mimetype` properties are set on the `__init__()` method, so I guess that any custom implementation could do the same, using whatever logic applies to their backend.

I don't think we need to have a separate function, just [document on the interface](https://github.com/ckan/ckan/blob/master/ckan/plugins/interfaces.py#L1610:L1639) that extensions can set these two properties if they want to support it.

Does this make sense? Do you want to send a quick PR with these changes?

**Comment by gleb-rudenko** [comment]
@amercader , sounds good

**Comment by gleb-rudenko** [comment]
@amercader , Hi, can you take a look at the PR please.

**Comment by gleb-rudenko** [comment]
@amercader, done, text changed
