### ISSUE TITLE
Can't scroll "Contents" treeview

### ISSUE THREAD

**Issue by rkagerer** [ckan/ckan#3297]
CKAN Version: 1.20.1-0-gd41fe54 (beta)

The tree view control showing the contents of a mod is disabled.  As a result you can't scroll it (either horizontally or vertically).  For example, try highlighting the "Filter Extensions - Plugin" mod, then clicking Contents, then Download.  There are a lot of files and it's impossible to preview them all.

Also the Download button doesn't go away after you download it.  CKAN doesn't seem to realize the mod has been added to the cache.

Screenshot [here](http://i.imgur.com/M16pQyx.png).

**Comment by amercader** [comment]
Sorry, wrong CKAN

**Comment by rkagerer** [comment]
Whoops, my bad, sorry!
