### ISSUE TITLE
Feature request: CKAN API should allow for data append

### ISSUE THREAD

**Issue by Kyle-Falconer** [ckan/ckan#3300]
The current (CKAN 2.6.0) API has endpoints for:

* uploading a new resource
* deleting a resource
* updating a resource (which just replaces the data associated with the resource)

The CKAN API has no operation for appending a resource, which would be useful for very large data sets with millions of rows. The [Socrata DataSync](https://socrata.github.io/datasync/) utility supports this operation, uploading the data provided and appending it to the end of the existing data resource.

The proposed API endpoint and documentation might look like this:

>`ckan.logic.action.append.resource_append(context, data_dict)`
>
> Append a resource.
> 
> To append data to a resource you must be authorized to update the dataset that the resource belongs to.
> 
> For further parameters see resource_create().
> 
> Parameters:	id (string) – the id of the resource to update
> Returns:	the updated resource
> Return type:	string
> 

Expected behavior would work like this:

Given a dataset A, with resource A1, where A1 is a CSV or other table-based data structure containing 500 rows of data (in rows 1..500), the data owner uses the CKAN API to append 100 new rows of data to A1. The input provided to the CKAN API contains the API Key, the Resource ID, and the 100 rows of data to be appended to resource A1. Once the append operation takes place, the original 500 rows of data previously present in A1 are still there, in the same rows (1..500), followed by the 100 new rows of data (in rows 501..600).

**Comment by TkTech** [comment]
Resources are nothing but dumb storage. They're either a URL or a file upload.

What you're thinking of is the [DataStore](http://docs.ckan.org/en/latest/maintaining/datastore.html). The DataStore does in fact allow you to append via the API.
