### ISSUE TITLE
cannot reproduce exemple in api doc page

### ISSUE THREAD

**Issue by datalocale** [ckan/ckan#3302]
### CKAN Version if known (or site URL)
2.7

### Please describe the expected behaviour
In the doc/api/index.rst page it states that one can execute the following command line via the httpie client
http http://demo.ckan.org/api/3/action/group_list id=data-explorer
In the api resference guide the id parameter is not listed 
http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.group_list
### Please describe the actual behaviour
when issuing this command the result is not filtered by the value of the group specified in the id param

### What steps can be taken to reproduce the issue? 
Install httpie
Run the command
http http://demo.ckan.org/api/3/action/group_list id=data-explorer
then
http http://demo.ckan.org/api/3/action/group_list

the results are identical

**Comment by amercader** [comment]
You are right,the `id=data-explorer` bit needs to be removed. Probably just a typo. Do you want to send a quick PR?

**Comment by datalocale** [comment]
ok no problem. But it means there is no ways to filter the results to get only a subset of the existing groups ?

**Comment by amercader** [comment]
No, that's not currently supported
