### ISSUE TITLE
Replace nose with py.test

### ISSUE THREAD

**Issue by sirex** [ckan/ckan#3310]
[nose](https://nose.readthedocs.io/) is no longer supported:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using [Nose2](https://github.com/nose-devs/nose2), [py.test](http://pytest.org/), or just plain unittest/unittest2.

It looks, that [py.test](http://pytest.org/) is the most active test runner project.

**Comment by amercader** [comment]
> Can run unittest (including trial) and nose test suites out of the box

@sirex It looks like at least we would not have to rewrite all tests :)

The main blocker for that is that we are using the `--with-pylons` option on nose, which essentially loads up a CKAN environment. We would need to create a similar [plugin](http://docs.pytest.org/en/latest/writing_plugins.html#writing-plugins) for py.test.

If you or someone else is up for investigating a bit more please go ahead!

**Comment by sirex** [comment]
@amercader if the team agrees to move to py.test, then I can look into that.

**Comment by amercader** [comment]
@wardi @TkTech @davidread any objections? ^

**Comment by TkTech** [comment]
None. nose works for us and will probably keep working, but it would be nice to get access to py.test plugins.

**Comment by sirex** [comment]
If you plan to continue writing unittest style tests, then I guess it is not worth changing nose to py.test.

IMHO migration to py.test only worth the effort if tests gradually will be replaced with py.test style tests. For example this:

```python
class MyTest(unittest.TestCase):
    def setUp(self): # ...
    def tearDown(self): # ...
    def test_me(self):
        self.assertEqual(foo, 'bar')
```

should be replaced with this:

```python
def test_me(setup_teardown):
    assert foo == 'bar'
```

If tests will stay written in unittest style, then these important features won't work:

- powerful py.test fixtures
- better assertion error output
- integration with existing py.test plugins and fixtures

py.test does support unittest style tests, but it really shines only with py.test style tests.

**Comment by wardi** [comment]
py.test style looks great to me

**Comment by amercader** [comment]
I'm less excited now if this means that we will have tests written in two very different styles, with 90% of them written in the "old" nose style that should not be used for new tests. It's very unlickely that the current 1500 or so tests (or the half that are not in `legacy` rather) will be migrated to the new style. 
I guess it depends on how different are they though.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
