### ISSUE TITLE
[Enchancement] - PEP8 to PyCodeStyle

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3312]
Seems like the library pep8 has been moved to pycodestyle

[https://pypi.python.org/pypi/pep8](https://pypi.python.org/pypi/pep8)
[https://pypi.python.org/pypi/pycodestyle](https://pypi.python.org/pypi/pycodestyle)

**Comment by amercader** [comment]
Nice catch, and the [original discussion](https://github.com/PyCQA/pycodestyle/issues/466) is amusing.
AFAICT we only use this for the PEP8 coding standards test, can you submit a PR to update the requirement?

**Comment by deinok** [comment]
@amercader Yes, I will send the PR ASAP
