### ISSUE TITLE
Translate resource-view-filters.js

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#3315]
`Add filter` is not translated: https://github.com/ckan/ckan/blob/master/ckan/public/base/javascript/modules/resource-view-filters.js#L180

Default template should be moved to `initialize` method and i18n should be added. Solution: https://github.com/DanePubliczneGovPl/ckan/commit/c70cd20aec13057fde5a9ef2825e7335e0d0638d

**Comment by torfsen** [comment]
That's something I also noticed. Similarly, it also contains an untranslated `'Select a field'`.

Fixing that should wait until #3211 is merged since that changes the translation API.

**Comment by amercader** [comment]
Looks like you have a patch for this @KrzysztofMadejski. Now that #3211 would you mind sending a PR?

**Comment by KrzysztofMadejski** [comment]
If I have time next week I'll try
