### ISSUE TITLE
docker-compose up will fail on initial database timeout

### ISSUE THREAD

**Issue by rwillmer** [ckan/ckan#3319]
### CKAN Version if known (or site URL)
2.6.0 (docker images tagged dev-v2.6)

### Please describe the expected behaviour
With contrib/docker/docker-compose.yml modified to add required environment variables (#3075)
'docker-compose up' should bring up a working system

### Please describe the actual behaviour
The 3 containers all appear to be able to start. The use of depends_on starts them in the correct order.

However, the db container has not fully started by the time the ckan container looks for it.

It fails with 
```
ckan    | sqlalchemy.exc.OperationalError: (OperationalError) could not connect to server: Connection refused
ckan    | 	Is the server running on host "db" (172.18.0.3) and accepting
```

### What steps can be taken to reproduce the issue? 
```
$ cd contrib/docker
$ docker-compose up
```

**Comment by rwillmer** [comment]
I shall add a 'wait-until-ready' into my ckan entry point, as suggested by docker

https://docs.docker.com/compose/startup-order/

However, I wonder whether ckan needs, or already has, a reconnect option which is used if the database connection fails at a later stage.

**Comment by rwillmer** [comment]
I'll also add a link to https://github.com/dmfenton/ckan-docker, which is a working implementation.

**Comment by deinok** [comment]
@rwillmer Working on it, thanks

**Comment by deinok** [comment]
@rwillmer Should be fixed, can you check it?

**Comment by frafra** [comment]
Still need to reboot ckan because the db is not ready.
