### ISSUE TITLE
No easy way to delete a draft dataset

### ISSUE THREAD

**Issue by shevski** [ckan/ckan#332]
If a dataset is in draft state, e.g. http://beta.ckan.org/dataset/ghgfhfgd
clicking on 'edit' takes you back to the add dataset process (http://beta.ckan.org/dataset/edit/ghgfhfgd) which you have to complete before being able to delete the dataset.

**Comment by benthorner** [comment]
We're seeing this as well on data.gov.uk, and it's confusing our users. +1 to support this.

**Comment by ipimpat** [comment]
I just installed CKAN to try it for my first time.

I ran into to this right away - it is VERY confusing.

Do I need to "complete" it in order to delete it ?

**Comment by kabeza** [comment]
Same problem here. No good UX about this
