### ISSUE TITLE
[SOLR] - Change to a ManagedSchema

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3321]
This will delete some of the biggest problems of have a schema.xml

Some Info:
[https://cwiki.apache.org/confluence/display/solr/Schema+Factory+Definition+in+SolrConfig#SchemaFactoryDefinitioninSolrConfig-Switchingfromschema.xmltoManagedSchema](https://cwiki.apache.org/confluence/display/solr/Schema+Factory+Definition+in+SolrConfig#SchemaFactoryDefinitioninSolrConfig-Switchingfromschema.xmltoManagedSchema)

**Comment by wardi** [comment]
@TkTech why close this? Is it a duplicate?

**Comment by deinok** [comment]
@TKTech something wrong?

**Comment by TkTech** [comment]
Sorry, guess I closed the page too fast and my comment didn't post.

This is a duplicate of #3118
