### ISSUE TITLE
Errno 13 uploading resources

### ISSUE THREAD

**Issue by arquelaup** [ckan/ckan#3326]
Hi, 

I've been trying to upload some resources from file to CKAN, but I keep getting `[:error] [pid 4130:tid 140444504823552] [remote 127.0.0.1:60878] Error - <type 'exceptions.OSError'>: [Errno 13] Permission denied: '/var/lib/ckan/default/resources/920'`.
I have followed the [documentation](http://docs.ckan.org/en/latest/maintaining/filestore.html), that is, I have `ckan.storage_path = /var/lib/ckan/default` and also set the permissions with 
```
sudo chown www-data /var/lib/ckan/default
sudo chmod u+rwx /var/lib/ckan/default
```

I dont know what is causing this error, and any help will be apreciated.

**Comment by wardi** [comment]
try with with `-R` to change the subdirectory permissions too
