### ISSUE TITLE
Local set to 'fr' doesn't work correctly when visualising a dataset

### ISSUE THREAD

**Issue by stephane-lapointe** [ckan/ckan#3327]
### CKAN Version if known (or site URL)
CKAN version 2.6.0

### Please describe the expected behaviour
Dataset should adjust datetime when locale is set to 'fr'.

### Please describe the actual behaviour
An error is generated while accessing a dataset when local is set to fr. (http://my-domain/fr/dataset/dataset-name)

Logs show this message:

File '/usr/lib/ckan/default/src/ckan/ckan/lib/formatters.py', line 152 in localised_nice_date
.format(**details))
KeyError: u'heure'

The problem doesn't exist with locale different than 'fr'.

The problem can be fixed temporarily by changing the value in  ckan/i18n/fr/LC_MESSAGES/ckan.po. 

#: ckan/lib/formatters.py:148
msgid "{month} {day}, {year}, {hour:02}:{min:02} ({timezone})"
msgstr "{month} {day}, {year}, {**heure**:02}:{min:02} ({timezone})"

#: ckan/lib/formatters.py:148
msgid "{month} {day}, {year}, {hour:02}:{min:02} ({timezone})"
msgstr "{month} {day}, {year}, {**hour**:02}:{min:02} ({timezone})"

Note that the catalog is marked as fuzzy, so you'll have to force catalog compiling:
python setup.py compile_catalog -f --locale fr

**Comment by amercader** [comment]
Thanks @stephane-lapointe 

Fixed on Transifex and backported to the dev-v2.6 branch, will be part of 2.6.1

**Comment by wardi** [comment]
@amercader did you intend to merge this instead?
