### ISSUE TITLE
Ckan creates ErrorHandler route before calling plugins before_map method, making it impossible to customize error handling.

### ISSUE THREAD

**Issue by Khalegh-H3** [ckan/ckan#3328]
Ckan documentation states [here](http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html?highlight=before_map#ckan.plugins.interfaces.IRoutes.before_map) that IRoutes.before_map gets called before the routes map is generated. However, in routing.make_map  code, the error handler route is generated before calling the IRoute methods :

    # The ErrorController route (handles 404/500 error pages); it should
    # likely stay at the top, ensuring it can always be resolved.
    map.connect('/error/{action}', controller='error', ckan_core=True)
    map.connect('/error/{action}/{id}', controller='error', ckan_core=True)

    map.connect('*url', controller='home', action='cors_options',
                conditions=OPTIONS, ckan_core=True)

    # CUSTOM ROUTES HERE
    for plugin in p.PluginImplementations(p.IRoutes):
        map = plugin.before_map(map)

This prevents connecting error actions to a customized error controller.

**Comment by amercader** [comment]
That sounds reasonable. Do you want to submit a PR that moves the routes below the extension point?

**Comment by Khalegh-H3** [comment]
Sure, I will make the changes and I will do the PR.
