### ISSUE TITLE
tutorial: Implementing the IAuthFunctions plugin interface

### ISSUE THREAD

**Issue by GuidoS** [ckan/ckan#3329]
### CKAN Version if known (or site URL)
    "ckan_version": "2.6.0"

### Please describe the expected behaviour
The tutorial seems to suggest that you can have a user that can create a group but is not the sysadmin.

### Please describe the actual behaviour
Sysadmin is the only account that can create a group.

### What steps can be taken to reproduce the issue? 
run the through the tutorial (which does not match the current files being created in 2.6.0) and try testing the create group.

**Comment by smotornyuk** [comment]
@GuidoS , i've just checked it:
Yes, with default settings common user have no access to group creating. But, you can change this behavior - just change [ckan.auth.user_create_groups](http://docs.ckan.org/en/latest/maintaining/authorization.html?highlight=user_create_groups%20#ckan-auth-user-create-groups) in config file to `true`.
@wardi , this already described in docs, so i think that no additional work required

**Comment by amercader** [comment]
The default value is that users are not allowed to create groups or orgs, and that's correct. We need to 

1. Update the configuration option docs to show the default value as Falsw
1. Update the IAuthFunctions tutorial to mention that you should turn this option to True
