### ISSUE TITLE
[CircleCI] - Test fails - SSL connection has been closed unexpectedly

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3332]
Sometimes CircleCI test fails, the cause is that SSL connection has been closed unexpectedly.

**Comment by torfsen** [comment]
I *think* I've finally figured this one out. See #3337.

**Comment by deinok** [comment]
im happy to see it :)

**Comment by deinok** [comment]
Still not working

**Comment by wardi** [comment]
@deinok I'm disabling the test until @torfsen or one of us has time to investigate #3359
