### ISSUE TITLE
Revision list generates broken links for organizations

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckan#3333]
### CKAN Version if known (or site URL)
Tested on [2.2.2](http://dados.gov.br/revision/8bac2318-6cbb-42b4-bd0f-094a305e2366), [2.5.2](http://demo.ckan.org/revision/e19fa361-3320-454e-8210-d11cb21d44d3) and [2.5.3](http://datos.gob.mx/busca/revision/b99d1d93-ec37-429e-9acb-00a45c0c1e8b)

### Please describe the expected behaviour
Open the /revision/list page.

* Changes to organizations should point to the organization by the proper link (/organization/{organization_name}).

Follow the link to the revision page (/revision/{revision_id}).

* Under the "groups" section there should be a link to changes to a group, and not changes to organizations.
*There should be an "organizations" section.

### Please describe the actual behaviour
Open the /revision/list page.

* Changes to organizations point to a broken link (/group/{organization_name}) that returns a 404 error.

Follow the link to the revision page (/revision/{revision_id}).

* Changes to organizations appear under the "groups" section with a broken link (/group/{organization_name}) that returns a 404 error.

### What steps can be taken to reproduce the issue? 
1. Create an organization or edit anything within it (edit the description, add a member, etc.).
2. Open /revision/list
   * There will be an entry in the revision list, where the organization name appears with a broken link to a non-existing group.
3. Open the revision entry corresponding to a change in an organization.
   * There will be a link, under the "groups" section, pointing to a broken link of a non-existing group.

### Possible fix
There should probably be some logic in the [revision controller](https://github.com/ckan/ckan/blob/master/ckan/controllers/revision.py#L147),

```python
    grps = model.Session.query(model.GroupRevision).\
        filter_by(revision=c.revision)
    c.groups = [grp.continuity for grp in grps]
    return base.render('revision/read.html')
```

and [corresponding template](https://github.com/ckan/ckan/blob/master/ckan/templates/revision/snippets/revisions_list.html#L25),

```
    {% for group in rev.groups %}
      <a href="{{ h.url_for(controller='group', action='read', id=group.name) }}">{{ group.display_name }}</a>
    {% endfor %}
```

to differentiate between revisions to groups and revisions to organizations.

There should probably be an "organizations" section on the [revision page template](https://github.com/ckan/ckan/blob/master/ckan/templates/revision/diff.html#L14) as well.

```
  {% elif c.diff_entity == 'group' %}
    {% set group = group.display_name or group.name %}
    <li>{% link_for _('Groups'), controller='group', action='index' %}</li>
    <li>{% link_for group, controller='group', action='read', id=group.name %}</li>
    <li class="active"><a href="" title="{{ _('Revision Differences') }}">{{ _('Revision Differences') }}</a></li>
  {% endif %}
{% endblock %}
```

**Comment by amercader** [comment]
@augusto-herrmann The revisions UI hasn't really been supported for a long time. All the changes you suggest sound really sensible. If you are using this interface and find it useful I encourage you to submit a pull request.

FYI here's some discussion about the future of revisions. Feel free to add a comment if you have an opinion on that: https://github.com/ckan/ideas-and-roadmap/issues/41

**Comment by augusto-herrmann** [comment]
Actually we just use it for a "what's new" kind of link on the site footer at [dados.gov.br](http://dados.gov.br). If there is a similar UI in CKAN, based on the activities flow, that could serve that role, we could just change the link in the footer.

Otherwise, we have to consider either asking our team of developers to do a patch, or to remove the link at the footer altogether.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.

**Comment by augusto-herrmann** [comment]
Looking at the code, and considering that [/ckan/blob/master/ckan/controllers/revision.py](/ckan/ckan/blob/master/ckan/controllers/revision.py) and [/ckan/templates/revision/snippets/revisions_list.html](/ckan/ckan/blob/master/ckan/templates/revision/snippets/revisions_list.html) only mention datasets and groups, and not organizations, I'd say that the bug still stands in current code.

I can't really set up a development environment to make sure, but the steps to reproduce it are really simple:

1. Create an organization.
2. Edit an organization.
3. Go to /revisions/list.
4. Click on the link corresponding to the change to the organization we've just made. This link will be broken.
