### ISSUE TITLE
Concept of "package" not documented - API documentation lacks basic data structure explanations

### ISSUE THREAD

**Issue by mohmad-null** [ckan/ckan#3336]
I'm trying to use the API to find some datasets. I'm not familiar with either CKAN or Solr.

The API allows searches of things like "resources", "packages", "tags" and "groups".

However, the word "package" doesn't appear even once in the user guide - http://docs.ckan.org/en/latest/user-guide.html - making it hard to understand what I'm actually searching when I try and use the "package_search" or "package_list" functions.
A search using the search function doesn't reveal anything either.
I'm *guessing* that a package is actually a dataset, but that's not explicitly stated anywhere.

I would suggest the API documentation would benefit from explaining some the data structures that CKAN uses; the folks using the API likely won't be the same as the folks who set it up in the first place.

**Comment by amercader** [comment]
@mohmad-null You are correct that this should be explained. I'm pretty sure it's mentioned somewhere but I have made it much more prominent in https://github.com/ckan/ckan/pull/3339

If you think that should be mentioned elsewhere let me know
