### ISSUE TITLE
Dataset: issue related to "Searchable" field

### ISSUE THREAD

**Issue by francescomangiacrapa** [ckan/ckan#3341]
Hi,

I've a problem with the field "searchable" related to a dataset.
In the last months, I used different ckan versions starting from 2.5.1 until to latest 2.6.0.

I'm the sysadmin and I'm using the Create Product interface via CKAN GUI.

This is the scenario:
Create a dataset (e.g. "Product-A") using Visibility = Private and Searchable = True
into an Organisation (e.g "Org") where the user (e.g. "User1")  he/she an ADMIN.

Adding the "Product A" to a group:

In 2.5.1 
- User1 performs browsing on the group. The Product-A (its title) is not visible and not even counted. Moreover, using the API action/package_show?id=Product-A the field "searchable" is not present in the json returned.

In 2.5.3
- the browsing issue is resolved and  the API action/package_show?id=Product-A returns "extras_searchable": "True".

In 2.6.0
- the problem shown in 2.5.1 is again present.

Do you think there was a problem during CKAN upgrade? However during each upgrade we have used the latest version downloading it from .github repo.
Can I/You fix the issue on CKAN 2.6.0?

Thanks in advance,
Best regards
F.

**Comment by amercader** [comment]
@francescomangiacrapa "Create Product" and "searchable" are not part of the standard CKAN model, so you must be customizing the default schema via an extension

You mention "Adding the "Product A" to a group". Groups have no effect on visibility, they are just meant to aggregate dataset thematically. Only adding datasets to organizations affects their visibility (members can see private datasets).

Also the output of action/package_show should show extras as a list of dicts, eg

```
{
...
extras: [
{key: "searchable", value: true},
...
]
...
```

It's really hard to debug what might be wrong in a customized CKAN without a public URL or the source code. Can you provide any of these? Cheers

**Comment by francescomangiacrapa** [comment]
Hi amercader,

thanks for your reply.
After read your response, I investigated on ckan plugins.. and I found that the plugin "privatedataset" performs a schema update adding "serchable" field (and other).
I think that the conflict is between "my plugin" and "privatedataset" and I've a strategy to fix the problem.

I'm going to close this issue. Thanks again for your response.
Cheers
