### ISSUE TITLE
Recline Grid View / SlickGrid column label/key breaks when label == "A"

### ISSUE THREAD

**Issue by mckaydavis** [ckan/ckan#3349]
### CKAN Version if known (or site URL)
Confirmed on 2.4.3 (internal site) and 2.5.2 (demo.ckan.org)

### Please describe the expected behaviour
The column header label/name in the Recline Grid View / SlickGrid component should show the proper column name of `A`

### Please describe the actual behaviour
When viewing a datastore resource with a label of `A` via the `recline_grid_view` extension:
   The column label is displayed as `<< - To >>`

When viewing the same datastore resource via the `recline_view` extension:
  The `A` column is displayed with label `GridGraphMapFilters`.  Clicking on the label to sort the column results in the label changing to `GridGraphMap<< - To >>FiltersRemove+-LeafletMapQuest`

### What steps can be taken to reproduce the issue? 
You can view this behaviour on a sample dataset I've placed on the demo.ckan.org site:

`recline_view` version (click on the column to sort to see the label change):

http://demo.ckan.org/ne/dataset/dataview-bug/resource/7f5bfc2f-b37a-407f-a87c-8bde69fd1de1?view_id=fa970612-bd62-4211-bc5b-ce2f3959193d

`recline_grid_view` version:

http://demo.ckan.org/ne/dataset/dataview-bug/resource/7f5bfc2f-b37a-407f-a87c-8bde69fd1de1?view_id=74c1cba6-9990-46d5-844c-8c87dff31073

If that dataset/resource has been deleted, just create a new resource by uploading a csv file with the contents:
```
"A","B","C"
"10","20","30"
"10","20","30"
```

**Comment by smotornyuk** [comment]
This bug was fixed and backported to older versions.  @mckaydavis , you can either switch to v2.4.4 or v2.5.3 in order to get rid of this

Issue can be closed
