### ISSUE TITLE
Add a user_list option that returns just names instead of dicts

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#3352]
user_list currently returns a dict for each user and the enhancement is to add an option to allow returning the user names.

DGU has 30k users and it takes 3 minutes, which is no good for a web request. Whereas returning just the names takes 10 seconds, skipping the dictization and the additional parts of the query that adds up revisions by the user.

package_list and group_list both return either names or dicts, depending on the `all_fields` parameter, so the proposal is to do the same, the only difference being that the default is True, for backward compatibility. (Other list actions just return dicts.)

**Comment by amercader** [comment]
Sounds good, merged. TBH I'd up for a change in default behaviour to be consistent with other endpoints, with appropiate deprecation notices of course. That can be a separate task.
