### ISSUE TITLE
render_markdown() breaks links with ampersands

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#3356]
### CKAN Version if known (or site URL)
2.5.3

### Please describe the expected behaviour
If a field supports markdown (e.g. the notes field), a user should be able to link to all valid URLs include something like http://example.com?test=bla&1=2

### Please describe the actual behaviour
If the field is rendered using the [`render_markdown` method](https://github.com/ckan/ckan/blob/9b5bf5d3accc147c90348f210a261cace00f8199/ckan/lib/helpers.py#L1846) and no extra parameters, this will not work, as the resulting link will be rendered as http://example.com?test=bla&amp;1=2.

### What steps can be taken to reproduce the issue? 
1. Render the following markdown with the [`render_markdown` method](https://github.com/ckan/ckan/blob/9b5bf5d3accc147c90348f210a261cace00f8199/ckan/lib/helpers.py#L1846) of CKAN

```
[Test Link](http://example.com?test=bla&1=2)
```

I think the reason for this is the [call to `clean_html`](https://github.com/ckan/ckan/blob/9b5bf5d3accc147c90348f210a261cace00f8199/ckan/lib/helpers.py#L1862) from the bleach module before actually rendering the the markdown, but I'm not sure.

In my case, I'm not dealing with user input, so I could simply pass `allow_html=True` as parameter to `render_markdown`, and the links were generated correctly. But this is certainly not a solution for everyone.

Maybe there is a way to keep the ampersands when cleaning the HTML through bleach?

**Comment by metaodi** [comment]
This change has been introduced here: https://github.com/ckan/ckan/pull/2766

**Comment by smotornyuk** [comment]
I think, it because `clean` itself aimed to sanitize HTML, not markdown. So, if we change it to something like ` clean_html(markdown(data), strip=True)`, than this problem will be resolved.

i've just checked default parameters of `clean`:
```python
clean(
    text, 
    tags=[u'a', u'abbr', u'acronym', u'b', u'blockquote', u'code', u'em', u'i', u'li', u'ol', u'strong', u'ul'], 
    attributes={u'a': [u'href', u'title'], u'abbr': [u'title'], u'acronym': [u'title']}, 
    styles=[], 
    protocols=[u'http', u'https', u'mailto'], 
    strip=False, strip_comments=True)
```
For suggested solution, few tags(p, pre) should be added to tags list

**Comment by smotornyuk** [comment]
Created PR #3364 with fixes and tests
