### ISSUE TITLE
How are solr and postgreSQL connected?

### ISSUE THREAD

**Issue by july7vivian** [ckan/ckan#3362]
### CKAN Version if known (or site URL)
2.5.2

### Please describe the expected behaviour
I can't find how solr link to postgreSQL.Definitely, it's not a issue, but I don't know where to raise a quetion, is there a forum?

### Please describe the actual behaviour
I wrote `solr_url = http://127.0.0.1:8983/solr `, and `sqlalchemy.url = postgresql://ckan_default:123456@localhost/ckan_default` in my development.ini file, but I'm confused how does solr know that its dataset is ckan_default.

### What steps can be taken to reproduce the issue? 
I didn't find config file for solr,` src/ckan/ckan/config/solr/schema.xml `only have filed message. `/var/lib/solr/data` and `/etc/solr/conf/solrconfig.xml` have no dataset message either.

I am confused, can anyone do me a favour, or where can I go for help. Thanks.

**Comment by deinok** [comment]
https://stackoverflow.com/questions/tagged/ckan

**Comment by july7vivian** [comment]
@deinok I raised a question on the website that you recommended me, but I didn't get a satisfied answer? May I ask a favour of you? Could you please give me some tips？Thanks！

**Comment by july7vivian** [comment]
I understood, in CKAN, Solr is not directly linked to PostgreSQL. The Solr index is maintained by the CKAN code itself, see ckan.lib.search.index.
