### ISSUE TITLE
Columns in the data explorer table preview do not use the full width

### ISSUE THREAD

**Issue by fanderegg** [ckan/ckan#3369]
### CKAN Version if known (or site URL)
CKAN 2.5.2
Example:
https://opentransportdata.swiss/en/dataset/bhlist/resource/911a4eb7-9d10-440f-904b-b0872b9727c1

### Please describe the expected behaviour
The columns in the data explorer table should use the entire available place.

### Please describe the actual behaviour
The columns only use a small part of the space and users have to increase the size of the column.

If someone has pointers how and where to fix this, we could probably make a pull request.

**Comment by TkTech** [comment]
https://github.com/ckan/ckan/issues/557 - see the [old] discussion in this ticket. It's an issue with the Recline library.
