### ISSUE TITLE
HTTP Response Splitting vulnerability

### ISSUE THREAD

**Issue by vgarciag** [ckan/ckan#3371]
### CKAN Version if known (or site URL)
CKAN 2.5.2. 

In a recent security audit of our CKAN server we have security vulnerability related to the http headers.

This seccurity vulnerability is related to a [HTTP Response Splitting](https://www.owasp.org/index.php/HTTP_Response_Splitting)

This vulnerability is more datailed here https://prakharprasad.com/crlf-injection-http-response-splitting-explained/. 

To fix this issue there are several ways but the better way is to sanitize the http headers in 
the CKAN code as is explained here in this Java code: http://stackoverflow.com/questions/16439618/how-to-fix-the-http-response-splitting-vulnerability-with-esapi

**Comment by wardi** [comment]
Thank you @vgarciag, please email security@ckan.org with the specifics. That's the best way for us to get a fix out quickly.
