### ISSUE TITLE
Dataset follower can't see new item counter at dashboard link, when the dataset is updated.

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3373]
### CKAN Version if known (or site URL)

master(ckan 2.7) branch
### Please describe the expected behaviour

When user follows dataset and this dataset is updated, new dashboard item counter should be changed, so user can see that new notifications appeard.
### Please describe the actual behaviour

When user follow dataset and this dataset is updated, new dashboard item counter is still on 0 items.
### What steps can be taken to reproduce the issue? 
Create a new user that follows some dataset, update this dataset. Reload the page with new user and no items appear at the link to dashboard.

**Comment by amercader** [comment]
@Engerrs was this fixed by https://github.com/ckan/ckan/pull/3374?

**Comment by Engerrs** [comment]
@amercader yes.

**Comment by amercader** [comment]
Great, closing this then.
