### ISSUE TITLE
Status of docker images?

### ISSUE THREAD

**Issue by rwillmer** [ckan/ckan#3375]
### CKAN Version if known (or site URL)
2.6.0 and later

### Please describe the expected behaviour
I'd like to run CKAN using official docker images

### Please describe the actual behaviour
I'm unsure whether official docker images exist.

### What steps can be taken to reproduce the issue? 
Read these documents and attempt to reconcile into a consistent answer

OK, so the problem is that the official website still says
```
There used to be an ‘official’ Docker install of CKAN. There are legacy docker images at https://hub.docker.com/u/ckan/ which are not maintained and use out-of-date unpatched versions of CKAN. 
```

But issue #3290 implies that @deinok has built them. However, he then says 
```
There are some issues with dev-2.6 and master. I'm working on it :)
```

But the issue is closed without any comment to say that the issues have been resolved.

So I am unsure whether the dev-2.6 images available at hub.docker.com are officially approved and working.

I'm also unsure about the name; dev-2.6 implies that it hasn't been released yet, but 2.6 is an official release, isn't it?

If there are still issues with the 2.6.0 docker images, please let me know what they are; I may be able to help.

**Comment by deinok** [comment]
@rwillmer The PR #3346 Will fix everything related with Docker issues and also should allow override the CKAN and run it on any HttpServer (Nginx, Apache, etc...)

At this moment its working pretty well, the command `docker-compose up` will setup everything.

The only thing left until the PR is merged is decide how to test that docker is working well. This will mean no more broken docker images.

**Comment by rwillmer** [comment]
Two comments/questions:

1/ I noticed that you switched from phusion/baseimage:0.9.15 to debian:jessie; does jessie solve the "PID 1 zombie reaping problem" that the phusion were addressing with base image? 

https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

2/ Have you tried running the test suite yet? You may find you hit the ANSI charmap problem I just encounter with the ubuntu:trusty image in #3372. If you hit unicode problems, that fix might help.

**Comment by rwillmer** [comment]
I'll close this now since I got my answer (thanks for the fast response, @deinok). Feel free to ping me if you run into any docker-related problems, I'm working on this at the moment, so may have already hit the same problem.

**Comment by deinok** [comment]
Thanks @rwillmer , the PR is already ready for merge.
About the PID 1 i never found an issue like this, but thanks for the information. I will give it a more detailed look. ;)
