### ISSUE TITLE
None-Type Handling in ckan

### ISSUE THREAD

**Issue by AnjaStemme** [ckan/ckan#3386]
### CKAN Version if known (or site URL)
2.5.2 (but still present in 2.7)

### Please describe the expected behaviour
If an object type is None (as opposed to an empty string for example) ckan should not crash

### Please describe the actual behaviour
Various functions in ckan crash when called with a None-Type object.
One example can be found in ckan/ authz.py   get_user_id_for_username(user_name, allow_none=False)

If this function is called with a None-Type object (and allow_none parameter set to true) it delivers a crash page with the message:
TypeError: expected string or buffer

The reason is the function call:     user = model.User.get(user_name)
with user_name being None. 

A workaround is very easy:

     if user_name != None:
        user = model.User.get(user_name)
    else:
        user = None

However, there are various other places where this kind of "NoneType Handling" appears to be missing. For example if the field /maintainer/maintainer_email is of type None an error is thrown at
Module ckan.controllers.package:392 in read
with the message: TypeError: cannot concatenate 'str' and 'NoneType' objects
(see attached file)

### What steps can be taken to reproduce the issue? 
We detected the None problem in authz.py in conjunctions with a "package_show" on a private dataset when the user_name was not set.

The problem regarding maintainer/maintainer_email (and potentially other default ckan_fields) might be reproduced by using the ckanext-scheming extension (https://github.com/ckan/ckanext-scheming): 
1) Omit the ckan-fields maintainer/maintainer_email in the schemings json file;
2) Create a dataset (eg: "test_no_maintainer")
3) insert the fields again in the schemings json file;
4) try to view  the dataset "test_no_maintainer"

However, besides the two above named examples there might be more issues regarding the "None-Type-Handling" in ckan (not explicitly referred to here) and hence it might make sense to check  None-object handling at other places in ckan as well.

[None-Type-Handling.txt](https://github.com/ckan/ckan/files/684419/None-Type-Handling.txt)

**Comment by wardi** [comment]
Happy to address specific issues, but I don't see how to address a broad bug description like this.

I expect `get_user_id_for_username(None, allow_none=False)` to fail so I'm not sure what you're suggesting.

Many places in our controllers expect that values that are part of the normal dataset schemas (like maintainer_email) will be present. Specific change PRs or issues are welcome and we can discuss them on the issue or PR.

**Comment by AnjaStemme** [comment]
In File authz.py, function get_user_id_for_username(None, allow_none=False)

Change:

user = model.User.get(user_name)

To:

if user_name != None:
    user = model.User.get(user_name)
else:
    user = None

**Comment by wardi** [comment]
@AnjaStemme from your description it sounds like there is code that sometimes has None instead of a username (or empty string). We haven't run into this before, so which part of ckan does this? Would you paste the full traceback you're seeing?

**Comment by AnjaStemme** [comment]
One example traceback  is attached above;  (https://github.com/ckan/ckan/files/684419/None-Type-Handling.txt)

However we are using ckan quite intensively (including scheming and many other plugins) and  have harvested datasets as well as datasets send to us via the API. We ran into this "None" problem also at serveral other occasions (another occasion was the view on a private dataset with the spatial plugin enabled, which lead to the crash in authz.py described above.) that's why I suggested to maybe check this "None-Problem" of objects in ckan in general. Actually I think that such a crash should not happen respectively is easy to omit. We patched the code in authz.py ourselves but of course would have to do this manually with every update we install.

Further more I tried to reproduce the error again actively. A "None-Handling-error" appears to happen as well within the scheming display-snippet email.html and is reproducible by omitting the maintainer_email eg. (create dataset without maintainer_email; include field maintainer_email again in json file; try to view the previously created dataset.)

From your earlier comment:
"I expect get_user_id_for_username(None, allow_none=False) to fail so I'm not sure what you're suggesting."  
At least get_user_id_for_username(None, allow_none=True) should return "None" and not a crash page or "Server Error" respectively? But maybe this should be the same for get_user_id_for_username(None, allow_none=False)? 
A "Server error" is always an unwanted response and actually everything is fine so far.

Sorry for any unclear descriptions. Hope it is clearer now.

**Comment by wardi** [comment]
@AnjaStemme The traceback you linked looks more like a problem with ckanext-scheming's display snippet, please report or send a PR that fixes it to that repo.

I'm interested in seeing a traceback related to the `get_user_id_for_username` change you're suggesting because the problem might not be where you think it is. Silently passing None through functions that aren't expecting them can lead to harder to find problems in the future, so it's something I try to be careful about.
