### ISSUE TITLE
Dictionary Fields

### ISSUE THREAD

**Issue by vithalalapati** [ckan/ckan#3396]
I would Like to add a grid of fields at the resource level. Similar to that of ckanext-dictionary at the resource level instead of package level. https://github.com/cmuphillycapstone/ckanext-dictionary/issues/13

And, CKAN out of box have key-value fields in the add dataset page, can we extend the that to more like a dicitionary fields at resource edit page

![capture3](https://cloud.githubusercontent.com/assets/17446326/21855917/14232c16-d7ee-11e6-84dd-9a864176d515.PNG)

**Comment by wardi** [comment]
@vithalalapati resources support adding extra fields just fine. All you need to do is extend the form and values you add to resources should be saved without requiring any change to the validation.

Are you interested in working on this? It sounds like it would be a good addition to ckanext-dictionary. If you're looking for a way to describe the columns of resource data then this might align with work @amercader or @jqnatividad have started too.

**Comment by vithalalapati** [comment]
Thank you, @wardi Is it possible to dynamically add more number of rows when you tab cursor to last row, like the similar functionality in the dictionary extension. So, in that case how can I add extra fields which are dynamic and count may vary for each resource. Is there anything there yet or I need o start from the scratch. @amercader  and @jqnatividad

**Comment by wardi** [comment]
resources let you store arbitrary JSON, so you can have a dynamic list if you're willing to write a validator that does the conversion from the form data.

**Comment by wardi** [comment]
Closing this issue (not the best place to discuss future work) If you are interested in working on this feel free to open an issue on the https://github.com/ckan/ideas-and-roadmap repo
