### ISSUE TITLE
[Documentation] User guide still mentions the "related items" tab

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckan#3412]
### CKAN Version if known (or site URL)
Affects CKAN Documentation for versions 2.5.3, 2.6.0 and "latest".
See http://docs.ckan.org/en/latest/user-guide.html#exploring-datasets

### Please describe the expected behaviour
Documentation should only mention existing functionality.

### Please describe the actual behaviour
The "[exploring datasets section of the User Guide](http://docs.ckan.org/en/latest/user-guide.html#exploring-datasets)" mentions the "related items" tab. It no longer exists on these versions.

### What steps can be taken to reproduce the issue? 
Open and read the online documentation at http://docs.ckan.org

**Comment by amercader** [comment]
Fixed in #3424
