### ISSUE TITLE
CKAN required packges and their roles? (On RHEL7)

### ISSUE THREAD

**Issue by vithalalapati** [ckan/ckan#3416]
I have installed ckan from source and everything just works fine. **I want to run the ckan on apache server, for that I am not sure where to start.** 

I have installed all the packages mentioned in source installation page. **Please help me with what exactly does these following package do. Jetty and Redis.?** 

And, Jetty says its used for solr. Even If I stop jetty service and restart the solr service. I can still see the solr admin page and ckan home page(after restart). **What's happening?**

And, I am looking to go ahead in development route on RHEL7

**Comment by TkTech** [comment]
Hello.

Please use the bug tracker for technical issues related to CKAN. We have other options for [technical questions.](http://ckan.org/contact/)
