### ISSUE TITLE
TypeError: do_truncate() takes at least 2 arguments (4 given)

### ISSUE THREAD

**Issue by markdturner** [ckan/ckan#3419]
### CKAN Version if known (or site URL)

2.6.0 and 2.7.1a (Master Branch)

### Please describe the expected behaviour

User can view any object via a get request, examples are user, organization or dataset, but basically trying to view any overview page of a CKAN 'thing'.

### Please describe the actual behaviour

Jinja template throws 500 error performing the do_truncate operation (see screenshot). For example, if I click on my username in the header toolbar or on the name of a dataset the error occurs.

![screen shot 2017-01-30 at 12 03 30](https://cloud.githubusercontent.com/assets/6863551/22423991/5a95ebfe-e6ec-11e6-9a1d-318b8f9c4df7.png)

### What steps can be taken to reproduce the issue? 

So far I've built docker images with both 2.6.0 and the master branch built from source. The Jinja repository released a 2.8.1 on 29 December which could be the root cause of this issue. The CKAN requirements list a dependency on Jinja 2.8, so it's possible a breaking change was introduced in 2.8.1. I'm going to try to update to Jinja 2.9 to see if that helps.

**Comment by markdturner** [comment]
Using version 2.9.5 of Jinja with CKAN 2.6.0 has the same issue

**Comment by TkTech** [comment]
One moment.

**Comment by markdturner** [comment]
Thanks @TkTech, is it just a case of me waiting for your pull request to be merged into the master branch?

**Comment by amercader** [comment]
@markdturner I've reviewed the Jinja2 versions and 2.8 or 2.8.1 don't cause the error ([Jinja2 2.8.1](https://github.com/pallets/jinja/blob/209fd39b2750400d51bf571740fe5ba23008c20e/jinja2/filters.py#L459)]. This exception occurs if using Jinja >= 2.9.4 which is where the change in args was introduced (https://github.com/pallets/jinja/commit/fb47dfac606f8067b77db1e805ad2cbd5cd6cd7f).

So it looks like you were using the latest Jinja2 version by mistake. If you downgrade it should be fine. Having said that what @TkTech suggests in #3420 is the most sensible approach anyway so we'll merge it anyway.

**Comment by markdturner** [comment]
@TkTech @amercader thanks for your help, I've been able to build the master branch in docker and the problem has gone.
