### ISSUE TITLE
If a resource is deleted, the corresponding data in the DataStore should be deleted as well

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#3422]
### CKAN Version if known (or site URL)
2.5.3

### Please describe the expected behaviour
If a resource is deleted, the corresponding data in the DataStore should be deleted as well. Otherwise the DataStore will quickly overflow if you harvest a big source and for each resource a new table is created and the old one still in place.

### Please describe the actual behaviour
Currently the deletion of a ressource does not affect the DataStore at all. But every table in the DataStore is linked to a resource in CKAN, so it's safe to assume they share the same lifecycle.

### What steps can be taken to reproduce the issue? 

1. Create a resource in CKAN (with DataStore enabled)
2. Upload a CSV & upload to DataStore
3. Delete the resource in CKAN

The resource is still available in the DataStore

**Comment by amercader** [comment]
@metaodi You are of course absolutely correct. @smotornyuk will have a go at implementing this. It would be great if you could test this once there is a PR/

**Comment by wardi** [comment]
We could also use a command for cleaning out orphaned datastore tables

**Comment by metaodi** [comment]
@wardi maybe additionally, to cleanup "old" databases. But I think to have this implemented _properly_ makes sense, doesn't it?

**Comment by wardi** [comment]
Absolutely! (that's why I used the word "also")

**Comment by jqnatividad** [comment]
+1 to having a CLI command to clean orphaned datastore tables.

**Comment by metaodi** [comment]
I created a "quick & dirty" paster command to empty the orphaned tables, which saves us a lot of space on our DB server: https://github.com/opendata-swiss/ckanext-switzerland/pull/137

It does not drop the tables, but simply calls the `datastore_delete` API. It's good enough for now for us.

cc @wardi @jqnatividad

**Comment by amercader** [comment]
Fixed in #3425

**Comment by jqnatividad** [comment]
Any chance the "quick & dirty" paster command to clean up orphaned datastore tables that @metaodi put together will be folded into core?

**Comment by metaodi** [comment]
@jqnatividad if there is a need, I can create a PR with the command for this repository.

**Comment by joeldouglass** [comment]
This appears to be fixed if you directly delete a resource. But if you delete and purge a data set (which also deletes its resources), the datastore tables are still there.
