### ISSUE TITLE
Unable to configure ckan for SSL

### ISSUE THREAD

**Issue by tedstrauss** [ckan/ckan#3429]
### CKAN Version if known (or site URL)

2.6

### Please describe the expected behaviour

Serving the CKAN app over HTTPS, with SSL cert.

### Please describe the actual behaviour

Unable to configure nginx and apache to work together with SSL. 
Most common bug appears in nginx log: /var/log/nginx/error.log

```
2017/02/02 16:07:12 [emerg] 27390#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/02/02 16:07:12 [emerg] 27390#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/02/02 16:07:12 [emerg] 27390#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/02/02 16:07:12 [emerg] 27390#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/02/02 16:07:12 [emerg] 27390#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/02/02 16:07:12 [emerg] 27390#0: still could not bind()

```

### What steps can be taken to reproduce the issue? 

I am following the steps provided in the CKAN wiki here: https://github.com/ckan/ckan/wiki/SSL
I have tried tweaking these settings in many ways, but it doesn't work.

**Comment by smotornyuk** [comment]
@tedstrauss , did you tried to check, which process is on this port?
{code}netstat -lp | grep 443{code}

**Comment by tedstrauss** [comment]
@smotornyuk checking this, will get back to you asap with the results.

**Comment by amercader** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

Thanks!
