### ISSUE TITLE
CKAN successfully running with Solr5.5.3

### ISSUE THREAD

**Issue by LeonanCarvalho** [ckan/ckan#3431]
### CKAN Version if known (or site URL)
2.6.0 (Over CentOS7)
### Please describe the expected behaviour
Not work

### Please describe the actual behaviour
Working
### What steps can be taken to reproduce the issue? 

My software infrastructure is running with Solr5.5, so I got few problems to install a ckan there without a docker or a second solr instance, so I fixed it  5.5.3 after few changes on schema:

- https://gist.github.com/LeonanCarvalho/a7bd73fe9632873c1bd7898c73d4b218#file-schema-xml
- https://gist.github.com/LeonanCarvalho/a7bd73fe9632873c1bd7898c73d4b218#file-solrconfig-xml

Basically I used this guide https://github.com/ckan/ckan/wiki/Install-and-use-Solr-5-in-GNU-Linux-for-CKAN but for http://it.apache.contactlab.it/lucene/solr/5.5.3/solr-5.5.3.tgz   instead. I fix the other things in style, trial and error.

Re-index was necessary 
```
paster --plugin=ckan search-index rebuild -r --config=/etc/ckan/default/development.ini
```

In addiction,  I put ckan as a service with proxy to lighttpd instead conventional apache way:
- https://gist.github.com/LeonanCarvalho/a7bd73fe9632873c1bd7898c73d4b218#file-ckan_lighttpd_vhost-conf
- https://gist.github.com/LeonanCarvalho/a7bd73fe9632873c1bd7898c73d4b218#file-ckand-service

I'm not sure about the impact of that, but its working fine till now.
I know the recent version of solr is not compatible, but tomcat and apache way took too many resources and made installation tedious.
How could I test this environment as a stable?

**Comment by amercader** [comment]
Hi @LeonanCarvalho, glad you got it working.

Do you have any suggestion for changes on the `schema.xml` file or the documentation to improve things?

As for testing your setup I'd suggest running the test suite and manually testing the site for a while covering different functionality.
If you want to discuss further you can contact the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev)  or the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode.

Thanks!
