### ISSUE TITLE
adding link to file to a resource does not work

### ISSUE THREAD

**Issue by rgommers** [ckan/ckan#3434]
### CKAN Version if known (or site URL)
2.7.0a

### Please describe the expected behaviour
Under a resource you can link to a file. This works as expected for ``http://`` links, but not for ``file://`` links. It should work the same for both. 

### Please describe the actual behaviour
``file://`` strings are not rendered as links, and not even wrapped so for long file links the end of the link is invisible on a page. The docs for adding a new dataset (http://docs.ckan.org/en/latest/user-guide.html?highlight=link%20to%20file#adding-a-new-dataset) only talk about uploading local files, but linking to files on a shared drive is useful (for very large files for which you only want to put metadata in CKAN for example, or for files with restricted permissions). 

### What steps can be taken to reproduce the issue? 
For any Resource, go to "Manage" and change the resource link to ``file:///C:/``. Then press "Update resource" - the link text will be light grey text rather than a hyperlink.

**Comment by TkTech** [comment]
Modern browser will not allow you to link to a `file://` URI from a `http[s]://` URI for security reasons.

**Comment by rgommers** [comment]
Thanks for the quick reply @TkTech 

Other browsers than Chrome will still ask you to download that file, which may be useful (http://stackoverflow.com/questions/18246053/how-can-i-create-a-link-to-a-local-file-on-a-locally-run-web-page). But I can understand you don't want to implement that; other browsers may follow what Chrome does.

There's still a bug here though - the file location really should not be cut off (``file:///some_very_long_link`` now gets translated to a string ``file:///some_ve...``) so you can't even copy-paste the location.

**Comment by TkTech** [comment]
Yup I agree the truncation is an issue, I'll pop a fix in tonight.

**Comment by TkTech** [comment]
@rgommers I've fixed the display issue with truncation when it's an invalid link.

If you really, really want to make them links you can do that yourself, it's an ini setting, [valid_url_schemes,](http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-valid-url-schemes). Just add `file` to this list.

**Comment by rgommers** [comment]
Thanks for the quick fix @TkTech !
