### ISSUE TITLE
[API] rest datasets

### ISSUE THREAD

**Issue by Germanaz0** [ckan/ckan#3438]
### CKAN Version if known (or site URL)

2.6.0

### Please describe the expected behaviour

I am trying to use `/api/rest/dataset` as a logged in user and should return all the datasets that the user can see, private and public.

### Please describe the actual behaviour

The api only returns an array of public datasets

### What steps can be taken to reproduce the issue? 
 -

**Comment by wardi** [comment]
The rest part of the API is old and hasn't been maintained for a while. For Try `/api/action/package_search?include_private=True` instead

**Comment by Germanaz0** [comment]
And which endpoints do you recommend me to use ? like an alternative for rest apis

**Comment by TkTech** [comment]
http://docs.ckan.org/en/latest/api/

**Comment by Germanaz0** [comment]
Rest apis has more logic than the latest apis, for every single action there is a different endpoint. 😭

**Comment by TkTech** [comment]
I have no idea what the justification was, I just live with it.

**Comment by wardi** [comment]
http://graphql.org/ would be cool too. Whatever the standard it won't happen until someone is given the time to work on it.

CKAN's rest api died because there was no-one to maintain it. Our current action api is directly exposing the simple functions that CKAN uses itself, so it keeps working.
