### ISSUE TITLE
performance of large datastore tables

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#3450]
The `datastore_search` API involves a mandatory row count to produce the total record count for the table, but this operation involves a sequential scan that can add seconds to each request for tables with many rows.

A few approaches to solving this that I can think of:

1. don't return the total # records by default, only calculate it when the user requests it
2. cache the total # of records so that we only pay the cost once every cache timeout
3. keep a count of rows in another table, updated with a `after insert or delete` trigger
4. return an approximate count stored by postrgres and recalculated on each `vacuum`

There are drawbacks with any of these approaches but I'm leaning towards approach 2 because it's simple to implement and I can cache the table's column information at the same time, which we also query frequently.

If there are approaches I'm not thinking of, please reply. Maybe we can combine 3 and 4 to use a trigger to update count postgres stores instead of duplicating it?

**Comment by TkTech** [comment]
What's making this sequential? Since 9.2 a `COUNT(*)` with an indexed column will use the index for zippy counts. Is it a total count of the arbitrary query from datastore_search or an unfiltered count?

**Comment by jqnatividad** [comment]
This article on PostgreSQL counting is most instructive (https://www.citusdata.com/blog/2016/10/12/count-performance/).

It shows how expensive counts are, and looking up the value is so much faster.

Since CKAN is not an transactional/operational store, why not store rowcount as part of the resource metadata, the same way we store filesize, when the dataset resource is updated, perhaps, using techniques described here - https://wiki.postgresql.org/wiki/Introduction_to_VACUUM,_ANALYZE,_EXPLAIN,_and_COUNT#COUNT.28.2A.29.

Doing so, not only makes the datastore_seach API faster, the stored rowcount can be used by tabular viewers, and even end users themselves as useful metadata.

**Comment by wardi** [comment]
Haven't had a second look yet but I suspect @TkTech is right, there's probably a sort being applied to the query that we don't need that if removed will make the count much faster without any other change. I'll try that first.

**Comment by TkTech** [comment]
@jqnatividad While what you described would work fine, the quicker fix is figuring out why we're getting a `Seq scan` instead of `Index Only scan` since that's a sign of either a bug in the query or poorly defined indexes.

**Comment by jqnatividad** [comment]
Got it. Forgot this whole issue is for `datastore_search` API call.

But I still believe storing rowcount as metadata data is useful the same way we store filesize.  I'll create an issue on roadmap-ideas for storing rowcount.

**Comment by TkTech** [comment]
Yes, storing total counts all over the place would help with many queries (User.number_of_edits, User.number_of_packages, revision_total, etc...) And can be easily implemented via triggers.

**Comment by wardi** [comment]
I quickly hacked the datastore search code so that it sends a separate query for the total rows instead of embedding it on every result with `count(*) over()` (presumably it was done this way to save the extra query)

My query for a page of data went from 1.88s down to 0.35s (5.4 x faster) for a datastore table with 900k rows. The interactivity in the table viewer is *much* improved now. I'll clean up my change and prepare a PR.

**Comment by wardi** [comment]
separate count query is implemented in #3467

**Comment by wardi** [comment]
Closing as fixed by separate count query, include_count option and new datastore_search records_format option
