### ISSUE TITLE
On Organization/Group page, on dataset tab, filters that were chosen don't appear under the '(Number) datasets found' title as on Dataset search page.

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3456]
### CKAN Version
All versions

###Expected behaviour
When we are on organization/group page, dataset tab, trying to filter datasets for example by 'Tags', under the '(Number) Datasets Found' title, we can see the tags we were chosen and can remove some of them or all of them and we don't need to list down the page to remove the one we've chosen, as it done on Dataset search page.

### Please describe the actual behaviour
When we are on organization page, dataset tab, trying to filter datasets for example by 'Tags', under the '(Number) Datasets Found' title, we don't see the tags we've chosen and have to scroll down the page to remove them.

### What steps can be taken to reproduce the issue? 
1. Create Organization.
2. Create Dataset for this organization with tags.
3.Enter the Organization page on Dataset tab and try to filter by tags.
4. You can remove the filters only by scroll down the page and remove them.

**Comment by wardi** [comment]
@Engerrs do you have time to look at this too?

**Comment by Engerrs** [comment]
Me or @wildcatzita, will take a look at this.

**Comment by wildcatzita** [comment]
I'll take a look

**Comment by wildcatzita** [comment]
@wardi , fixed. Made [PR](https://github.com/ckan/ckan/pull/3460)

**Comment by gleb-rudenko** [comment]
@amercader, I think this one can be closed now.
