### ISSUE TITLE
Changing resource format for an existing resource, won't change/create new view for new format.

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3457]
### CKAN Version
All

### Expected behaviour
When we created new resource for dataset, with/without format, after updating the resource for new format it creates/changes view for it.

### Actual behaviour
When we created new resource for dataset, with/without format, after updating the resource for new format it doesn't create/change the view for resource.

### What steps can be taken to reproduce the issue? 
1.Create Dataset
2. Create new resource for it with format CSV
3. Enter the resource and update it's format to PNG
4. We can see that the view for the resource hasn't changed.

**Comment by Engerrs** [comment]
I can take a look at this one if need.

**Comment by wardi** [comment]
@Engerrs please do

**Comment by Engerrs** [comment]
Hi @wardi , created a fix for that one.

**Comment by gleb-rudenko** [comment]
@wardi, what is the progress of this one?

**Comment by wardi** [comment]
@Engerrs please create a PR so we can review it

**Comment by Engerrs** [comment]
Sorry @wardi , thought that  I've created one. Add it.

**Comment by wardi** [comment]
fixed by #3515
