### ISSUE TITLE
Typo in test_search.py breaks tests

### ISSUE THREAD

**Issue by snd297** [ckan/ckan#3465]
master branch ckan/ckanext/datastore/tests/test_search.py has 

```
u"'warandpeac'" 
```

and these two tests break

```
def test_select_basic(self):
def test_select_where_like_with_percent(self):
```

changing it to 
```
u"'warandpeace'"
```

fixes them.

**Comment by tino097** [comment]
If it looks at first glance as typo, this is related to postgres tsvector type. Please check postgres version for any dofferences

**Comment by snd297** [comment]
Failure is with TestDatastoreSQL, not TestDatastoreSearch as in link.

**Comment by tino097** [comment]
thank you for the note, i corrected the output.

**Comment by snd297** [comment]
I don't understand - was there an issue in the code or am I supposed to check my postgres version?

**Comment by tino097** [comment]
Please check it, because there is no typo

**Comment by snd297** [comment]
We're using postgres 9.5.4 and CKAN 2.6.0.

**Comment by snd297** [comment]
Here's some detail on my failures - I'm sure I'm missing something, but to me it looks like u"'warandpeac'" should be u"'warandpeace'"

======================================================================
FAIL: ckanext.datastore.tests.test_search.TestDatastoreSQL.test_select_basic

line 886, in test_select_basic
assert ft_value in row['_full_text']

AssertionError:

assert u"'warandpeac'" in {u'b\xfck': u'warandpeace', u'author': u'tolstoy', u'_full_text': u"'a':1 'b':4 'tolstoy':3 'warandpeace':2", u'nested': {u'a': u'b'}, u'published': None, u'_id': 2}['_full_text']
======================================================================
FAIL: ckanext.datastore.tests.test_search.TestDatastoreSQL.test_select_where_like_with_percent

File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/tests/test_search.py", line 917, in test_select_where_like_with_percent
assert ft_value in row['_full_text']

AssertionError:

assert u"'warandpeac'" in {u'b\xfck': u'warandpeace', u'author': u'tolstoy', u'_full_text': u"'a':1 'b':4 'tolstoy':3 'warandpeace':2", u'nested': {u'a': u'b'}, u'published': None, u'_id': 2}['_full_text']

**Comment by tino097** [comment]
interesting, when i 'fixed' the typo this was my output

` assert u"'warandpeace'" in {u'b\xfck': u'warandpeace', u'author': u'tolstoy', u'_full_text': u"'b':4 'tolstoy':3 'warandpeac':2", u'nested': {u'a': u'b'}, u'published': None, u'_id': 2}['_full_text']
`

**Comment by snd297** [comment]
It looks to me like you have a different value on line 807 than 

https://github.com/ckan/ckan/blob/master/ckanext/datastore/tests/test_search.py

your output has 

'warandpeac':2  

but mine has

'warandpeace':2

**Comment by tino097** [comment]
no, have same value as you
spent some time debugging to see whats going on and there is a insert 
https://github.com/ckan/ckan/blob/master/ckanext/datastore/db.py#L658

not sure what is _to_scvector_ doing with the values

**Comment by snd297** [comment]
Okay. Thanks for all of your help - I'm going to assume this is a configuration issue on our end.

**Comment by tino097** [comment]
no problem, you could try to run tests again with --reset-db option

**Comment by TkTech** [comment]
The value are being [stemmed](https://en.wikipedia.org/wiki/Stemming). In this case that means `warandpeace` becomes `warandpeac` (as would `warandpeaces` or `warandpeacing`, etc...)

**Comment by tino097** [comment]
@TkTech thank you
