### ISSUE TITLE
metadata_modified is inconsistently set & updated

### ISSUE THREAD

**Issue by TkTech** [ckan/ckan#3475]
### CKAN Version if known (or site URL)

All

### Please describe the expected behaviour

On any kind of package change, we should see a correctly updated UTC timestamp in metadata_modified.

### Please describe the actual behaviour

metadata_modified becomes `null` (creation) or does not reflect the actual time of insertion (update).

### What steps can be taken to reproduce the issue? 

Create a package.

**Comment by TkTech** [comment]
Proposed PR does a few things:

1. We use the time the row is *actually* inserted as the metadata_modified value, since we can have some very long running transactions.
2. We properly use UTC timestamps.
3. We let Postgres ensure our metadata_modified is updated on the package both when the package is update or when a related package_extra is updated.
4. This avoids the VDM-workarounds to stop metadata_modified changes from triggering infinite revisions, removing a flush and SQL session reload.

**Comment by tino097** [comment]
is this fixed ?
im trying to reproduce the issue but no success, tried to create dataset via web and via api
