### ISSUE TITLE
Datastore dump of nested json returns strange characters

### ISSUE THREAD

**Issue by arvidT** [ckan/ckan#3477]
### CKAN Version if known (or site URL)
2.5.3

### Please describe the expected behaviour
I have a datastore resource that I'm trying to dump to CSV format using the /datastore/dump/[resource-id] url. The expected behaviour is to get a CSV representation of my resource returned.

### Please describe the actual behaviour
The problem is that any nested json within my resource will be formatted beginning with a "u"-character. See example:
```
_id,measureId,lastUpdated,validFrom,validTo,publiclyAvailableInformation,regionalIndicator,subCategoryDefinition,parentMeasureDefinition,author,authenticator
105,02c0ac9c-b26c-449c-b064-2a2da84fa763,2016-05-26T10:04:23,,,False,{},"{u'parentMeasureId': u'e101817d-2226-4f48-a1d2-fcb61fde050e', u'subCategoryCode': [{u'code': u'545779e637874129a8ef8af5', u'system': u'5457794537874129a8ef8aaf'}]}",,,
```

see `{u'parentMeasureId'` in the second row and in all the other nested json types. 
The "u"-character is not in the original resource and if I access the reource using the usual datastore API it is returned ok:

```json
{
"validFrom": null,
"measureId": "053eb6bf-3da5-4264-a056-87dc4deb3075",
"author": null,
"subCategoryDefinition": {
"parentMeasureId": "a87440aa-30c5-43f0-9e51-d07f5fccc131",
"subCategoryCode": [
{
"code": "fb9376b6-12fa-47b4-8a2a-031657a72a0d",
"system": "19bb7abe-7de4-420f-8259-7aca0a461b6f"
}
]
}
```

### What steps can be taken to reproduce the issue? 
Create a datastore resource using nested json and try to dump it to CSV.

**Comment by amercader** [comment]
Objects are being dumped as their Python representation instead of JSON strings.

This happens both on CKAN <= 2.6 and on master (with @wardi 's new datastore dump writers).

The following adds a test case and solves it for CKAN <= 2.6:

```diff
diff --git a/ckanext/datastore/controller.py b/ckanext/datastore/controller.py
index b872c1d..12f8a10 100644
--- a/ckanext/datastore/controller.py
+++ b/ckanext/datastore/controller.py
@@ -1,5 +1,6 @@
 # encoding: utf-8
 
+import json
 import StringIO
 import unicodecsv as csv
 
@@ -40,7 +41,13 @@ class DatastoreController(base.BaseController):
 
         header = [x['id'] for x in result['fields']]
         wr.writerow(header)
-
         for record in result['records']:
-            wr.writerow([record[column] for column in header])
+            values = []
+            for column in header:
+                if isinstance(record[column], (list, dict)):
+                    value = json.dumps(record[column])
+                else:
+                    value = record[column]
+                values.append(value)
+            wr.writerow(values)
         return f.getvalue()
diff --git a/ckanext/datastore/tests/test_dump.py b/ckanext/datastore/tests/test_dump.py
index b966bed..262a200 100644
--- a/ckanext/datastore/tests/test_dump.py
+++ b/ckanext/datastore/tests/test_dump.py
@@ -72,7 +72,8 @@ class TestDatastoreDump(object):
         expected = u'_id,b\xfck,author,published,characters,nested'
         assert_equals(content[:len(expected)], expected)
         assert 'warandpeace' in content
-        assert "[u'Princess Anna', u'Sergius']" in content
+        assert '"[""Princess Anna"", ""Sergius""]"' in content
+        assert '"{""a"": ""b""}"' in content
 
         # get with alias instead of id
         res = self.app.get('/datastore/dump/{0}'.format(str(
@@ -90,4 +91,4 @@ class TestDatastoreDump(object):
         content = res.body.decode('utf-8')
         expected = u'_id,b\xfck,author,published,characters,nested'
         assert_equals(content[:len(expected)], expected)
-        assert_equals(len(content), 148)
+        assert_equals(len(content), 153)
```

@wardi are you happy with a similar approach for master?

**Comment by wardi** [comment]
This won't handle strings or true/false/null stored as json. I think we need to json.dumps always when the type of the column is json instead.

**Comment by wardi** [comment]
and let's replace `assert_equals(len(content), 148)` with `assert_eqauls(content, <the actual thing we're expecting>)` assertion failures on length checks just force us to insert debugging to find out what actually went wrong.

**Comment by amercader** [comment]
Agreed better implementation: dump as JSON all columns with type `json` or that are arrays (Start with `_` or end with `]`, see http://docs.ckan.org/en/latest/maintaining/datastore.html#valid-types). Fix the dodgy len test.

A separate issue is that the DataPusher should be able to interpret these dumped values and store them as `json` on the DataStore ( I don't think we can tell apart `json` or array fields reliably). But that can be a separate issue.

@smotornyuk is this something you would have time to work on? (the output issue, not the input one)

**Comment by smotornyuk** [comment]
Yeah, no problem :construction_worker_man:

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
