### ISSUE TITLE
Reindex Performance Is Unnecessarily Slow

### ISSUE THREAD

**Issue by TkTech** [ckan/ckan#3482]
### CKAN Version if known (or site URL)

All

### Please describe the expected behaviour

A reasonable rate of updates to solr with minimal commits and search warmers.

### Please describe the actual behaviour

1. `index_package` reconnects to solr for each document.
2. `index_package` does a wide variety of unnecessary post-processing that was already done by the caller.
3. Weird document updates meant to support multiple sites in a single solr core (we should deprecate this it's incredibly broken and has never worked right with things like facets).
4. Most importantly, we're doing a separate `update` for each document instead of bulking.

### What steps can be taken to reproduce the issue? 

Run reindex with any set of options.

**Comment by TkTech** [comment]
I'll be rewriting the reindex process, it'll be more work to rejigger what's there than do it with bulk loading in mind from the get go.

**Comment by LingboTang** [comment]
Can't agree more. It is unexpectedly slow. Even for 10k dataset CKAN site, the rebuild search-index will take around 16 hours to finish. Not sure if this problem has been fixed in the new version yet.

**Comment by wardi** [comment]
I've *ahem* accidentally re-indexed a site with about 80k datasets with extensive metadata and it took about an hour. @LingboTang maybe you're indexing the document contents with ckanext-extractor or something that slows it down even more?

**Comment by wardi** [comment]
closing as this is no longer a work in progress. If someone has the time to investigate this please open a new issue or PR.
