### ISSUE TITLE
Removal of deprecated revision controller.

### ISSUE THREAD

**Issue by TkTech** [ckan/ckan#3484]
The revision UI (/revision/list, /revision/{id}, /revision/edit/{id}) has long been unsupported. For several release versions the UI has not even been [themed correctly](http://demo.ckan.org/revision/list). I'm proposing the immediate removal of this controller and associated templates.

1) The UI is not "useful". When even small sites generate millions of revisions showing 12000+ pages is not great. The fields on individual revision details have not displayed properly in years. Most comments will always either be blank or "REST API" (which is also a bug).
2) The page performs very, very poorly and a bot crawling all pages is responsible for disabling large CKAN instances.
3) The end-user functionality of this page is provided by activity feeds.
4) ~No~ Limited test coverage.

TODO:

- [x] Remove controller, templates, routes, tests.
- [ ] Remove translation strings.
- [x] Update the `controllers/package.py:history` view to use activities instead of the revision controller diff. Or just remove it entirely.

**Comment by TkTech** [comment]
@amercader @wardi @davidread I just noticed a possible bug, tested and confirmed it. This is now critical and once merged a security backport/release should be made. It's possible to get all packages in their entirety including private datasets.

**Comment by wardi** [comment]
This has long been planned, just no-one got around to implementing a history page based on activities.

:+1: from me

**Comment by davidread** [comment]
Good one! This is long overdue.

**Comment by jqnatividad** [comment]
Hopefully, this will set the stage to do revisions properly.

Its one of the features govt CDOs/CIOs look for - 
http://datasmart.ash.harvard.edu/news/article/an-open-letter-to-the-open-data-community-988

**Comment by TkTech** [comment]
This also closes #3333

**Comment by TkTech** [comment]
The PR attached to this has been updated. Activities should now be able to support the history functionality that was removed.

1) The history package (which is not used at all in default CKAN) just redirects to the package's activity steam page.
2) Package activity events now display a "View this version" link to go back in time.
3) Activites store the post-`package_show` dict instead of the incomplete `package_dictize` result. Only new activities will have the complete view, but old activities will not crash.
4) Package-related activities now store the username of the user who made the change, so that displaying activities when a user has been deleted no longer crash with no info.
5) Activities are now *just jinja2 snippets* meaning you can override them in your themes and adding new activities is much, much, much simpler.
6) All of the odd `_html` action methods are gone.

Looking at an activity stream looks like this (note the "view this version" link):

![image](https://cloud.githubusercontent.com/assets/72590/25201631/6030caa8-2520-11e7-8de7-09b488cc87ff.png)

Looking at an old version of a package now looks like this:

![image](https://cloud.githubusercontent.com/assets/72590/25201595/42be6f16-2520-11e7-9e74-14fd24b83fe0.png)

I need to fix the infinite scrolling behaviour but otherwise this is "done" and ready for comments and reviews. I'm sure I've missed something.

**Comment by TkTech** [comment]
@wardi @amercader @davidread any final feedback/review before I get this ready to merge?

**Comment by amercader** [comment]
I added some comments but overall this makes me so happy, specially all that red...

We definitely need to list this on the changelog and I'm sure there are some details to polish but I think it looks great.

**Comment by wardi** [comment]
also a huge fan of all the red :+1:

Do the existing activity tests cover the changes or should this include some new tests?

**Comment by davidread** [comment]
-700 lines FTW!

**Comment by amercader** [comment]
@TkTech would be great to get this ready to merge. Do we need new tests for the activities?

**Comment by TkTech** [comment]
Currently the feature is fully functional (and being used in production) but yes, the tests are holding it back. The old revision ones need to be removed and a new activity test for "view this version" needs to be added. I just don't have the time at the moment.

**Comment by davidread** [comment]
I'd like to do the remaining test work, to push it over the line - is everyone happy with that? @TkTech

**Comment by TkTech** [comment]
Yes absolutely, I'm currently receiving no funding to work on CKAN at the moment, so I have no time :( More then happy to review!

**Comment by davidread** [comment]
Reopening - this is the issue attached to ongoing work in PR #3972
