### ISSUE TITLE
Ckan release-v2.4.x got no fix for package_search method that exists in versions 2.5 and higher

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3489]
### CKAN Version
all ckan 2.4.x versions

### Expected behaviour
We've got user in this way "user = context.get('user')", witch wont lead to KeyError when such key is not there. Such implementation is already on version 2.5 and higher.

### Actual behaviour
We've got user in this way "user = context['user']", witch leads to KeyError when it not exists.

**Comment by MrkGrgsn** [comment]
Was fixed in master for 2.5, the original commit was a523b44ccbef3b18157d2684137fb0aa92295d32

**Comment by amercader** [comment]
Backported to 2.4.7
