### ISSUE TITLE
Redirecting to same page in non-root hosted ckan adds extra root_path to url 

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#3499]
### CKAN Version if known (or site URL)
2.6.0, 2.6.1, master

### Please describe the expected behaviour
In ckanext-harvest reharvest and clear buttons and in ckanext-report button redirect to the same page, if ckan is hosted in for example /data, I expect the redirection to /data/harvest/admin/someharvestname.

### Please describe the actual behaviour

Resulting url is /data/data/harvest/admin/someharvestname

### What steps can be taken to reproduce the issue? 

Clear or reharvest non-root hosted ckan.

### Some additional info

https://github.com/ckan/ckan/pull/2998 is probably the culprit since redirection works in ckan 2.3.5.
Will supply PR which should be validated for not breaking anything else.

**Comment by wardi** [comment]
@fanjinfei would you look at this when you have some time?

**Comment by fanjinfei** [comment]
for a none root such as `/data/{{LANG}}`, `h.url_for('/data/user/logoin')` is wrong (`/data/data/user/login`).  `h.url_for(controller='user', action='login')` is correct. 
h.redirect_to() should have the same problem.

**Comment by Zharktas** [comment]
Yes, this issue can circumvented by modifying the extensions to redirect to controller actions instead of urls.

For ckanext-harvest https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/controllers/view.py#L77 and for ckanext-report https://github.com/datagovuk/ckanext-report/blob/master/ckanext/report/controllers.py#L46

But since the helper functions accept urls as parameters and the issue does not manifest itself when ckan is hosted in root path, I suspect there is a bug in ckan core with url amending which should be fixed or at least prohibit urls as parameters.

**Comment by fanjinfei** [comment]
The other way is to make the doc clear. All the url arguments in h.()...  should not include the root path.

**Comment by wardi** [comment]
When passing urls to redirect_to I agree with @Zharktas, we should never add the root path. That way existing code that does `redirect_to(url_for(...))` will work, `redirect_to('http://some.other.place/..')` will work and `redirect_to('/user/login')` won't work because it should be written with the controller and action parameters as @fanjinfei suggests. We should also document this on redirect_to.

**Comment by Zharktas** [comment]
This issue might manifest itself with ckan 2.7 as there is now new handler [helpers.py](https://github.com/ckan/ckan/blob/ckan-2.7.0/ckan/lib/helpers.py#L162]) if the path starts with /-character.

If the root path is set, both ckan 2.6 and 2.7 will generate urls incorrectly with url_for:

    h.url_for('http://example.com')
    '/datahttp://example.com'

When calling redirect_to with 'http://example.com', 2.6 redirects just fine, but 2.7 adds site_url to the final url and redirection no longer works. I'll take a look if this is actually caused by the same issue and try fix it. If it's not, I'll create separate issue.
