### ISSUE TITLE
Tests sometimes just hangs. I suspect HTTPretty 

### ISSUE THREAD

**Issue by smotornyuk** [ckan/ckan#3502]
I checked timeouts in CircleCI and make some local tests with `release-v2.5.5` branch and it seems, that v0.8.3 is the main problem here. It works with v.0.6.2 but there some issues on Ubuntu14. Newest v0.8.14 throws BadStatus error.  So we need either upgrade or downgrade. Or another library

I suggest using another similar library, for example [mocket](https://github.com/mindflayer/python-mocket). It was inspired by httpretty and looks almost the same, so it will be quite straightforward change

PS I'm not against HTTPretty, but it looks like no one in internet like it :)

**Comment by TkTech** [comment]
Doubt it I do not, I already have monkey patches in there to keep HTTPretty from failing.

**Comment by amercader** [comment]
I've found tons of issues with HTTPretty so happy to replace it with something more robust. But for 2.5.5 have you identified what are the tests that get stucked? Perhaps we can just mock the calls so we don't have to change the branch that much.

**Comment by smotornyuk** [comment]
Yeah, good idea. There are 3-4 tests from `ckanext.datapusher.tests.test:TestDatastoreCreate` that cause this problem, i'll update them for now

**Comment by smotornyuk** [comment]
I checked newer version - it seems that 0.8.7 fixes our problem and it not yet throws BadStatus error as 0.8.14. So is it ok to update dev-requirements for 2.5.5 branch ? or this should be applied for other two release branches as well?

**Comment by davidread** [comment]
@smotornyuk sounds like you have everyone's support, so please do a PR. If it passes circleci then I will merge it.

**Comment by smotornyuk** [comment]
Sorry, forgot to mention it here. As we discussed on one of the last meetings, i added commit with version upgrade while preparing patch-release for branch 2.5.5, so it already [there](https://github.com/ckan/ckan/commit/5e0ddde76dd58431330df5246ea24942878e1de4)

**Comment by davidread** [comment]
Great! I'll close this then :)
