### ISSUE TITLE
mod_wsgi: Partial results are valid but processing is incomplete -> IOError: request data read error

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#3504]
### CKAN Version if known (or site URL)
2.3.5

### Please describe the expected behaviour
No errors in the apache log.

### Please describe the actual behaviour
An error is thrown quite often, mostly for the tracking requests:

```
[Mon Mar 27 07:57:52.035163 2017] [:error] [pid 14948] (70008)Partial results are valid but processing is incomplete: [client 193.xx] mod_wsgi (pid=14948): Unable to get bucket brigade for request., referer: https://danepubliczne.gov.pl/application
[Mon Mar 27 07:57:52.035285 2017] [:error] [pid 12328] [remote 193.xx] mod_wsgi (pid=12328): Exception occurred processing WSGI script '/etc/ckan/ckan.py'.
[Mon Mar 27 07:57:52.035320 2017] [:error] [pid 12328] [remote 193.xx] Traceback (most recent call last):
[Mon Mar 27 07:57:52.035341 2017] [:error] [pid 12328] [remote 193.xx]   File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/config/middleware.py", line 340, in __call__
[Mon Mar 27 07:57:52.035386 2017] [:error] [pid 12328] [remote 193.xx]     payload = environ['wsgi.input'].read()
[Mon Mar 27 07:57:52.035406 2017] [:error] [pid 12328] [remote 193.xx] IOError: request data read error
```

### What steps can be taken to reproduce the issue? 
It's not easy to reproduce

### Diagnosis

In current CKAN it's [this line](https://github.com/ckan/ckan/blob/master/ckan/config/middleware/common_middleware.py#L194).

I've Googled a bit and found this: https://groups.google.com/forum/#!topic/modwsgi/ycwTB7wQz_8
`you are seeing the messages because you are using the write()
callback and not catching the IOError and aborting the request
cleanly. [...] Note that write() is not considered best practice and you should try
and return an iterable from WSGI application instead.`

Anyone has experience in that?

**Comment by wardi** [comment]
I'm not familiar with this code but it might just be clients closing the connection but that error not being handled in the middleware. How about we just catch and ignore this exception right there? Would you mind trying that and submitting a PR?

**Comment by nabobnagari** [comment]
We got the same issue using IHS 8.5.5.11 

getting (70008)Partial results are valid but processing is incomplete: proxy preftech request body failed to IP

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
