### ISSUE TITLE
Treat resources independently while adding/updating

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#3505]
### CKAN Version if known (or site URL)
I'm using CKAN 2.3.5, but I see that in master (2.7) it works the same.

### Please describe the expected behaviour
When I add or update many resource I do not want race conditions between resources of the same dataset.

### Please describe the actual behaviour
All the datasets' resources data are pulled, [one resource data is changed](https://github.com/ckan/ckan/blob/master/ckan/logic/action/update.py#L107), everything is saved.

### What steps can be taken to reproduce the issue? 
Create a dataset with 100+ resources. Open several tabs to add resources, fire them at once, error 500 may happen. 
I know such scenarios seems like a case for implementing an API access, but we have this problem with our users using web interface. Also I feel like it's really a poor design to save everything together, but I don't know the context. What was the rationale behind it?

**Comment by wardi** [comment]
datasets are the basic unit of metadata in CKAN. When you update a resource the metadata_modified of the dataset is updated. Validation is also applied across a complete dataset, e.g. depending on fields at the dataset level you might not be allowed to upload certain types of resources. The whole dataset needs to be updated in solr as well, even for a single resource change.

It is wasteful to be doing unnecessary work though. If you've got time to implement the same behaviour without updating all resources (validate across the whole dataset but update just the one resource plus the metadata_modified on the dataset in the db) please do. That would especially help for sites that have many resources in a single dataset.

**Comment by wardi** [comment]
Let me know if you need more direction here. Datasets with 100+ resources aren't well supported by CKAN for updating (noted above), searching (mentioned in resource_search issue) and displaying (no pagination), but if you have a site with such large datasets and some time I'd love to see that fixed.

**Comment by KrzysztofMadejski** [comment]
Thank you @wardi, it's quite clear now. Polish Ministry of Digital Affairs plans bigger development around data portal, so it could be tackled then.

**Comment by TkTech** [comment]
Agreed, this is usual a sign of a bigger underlying model issue (our updates are stateful) would be great to see this improved.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
