### ISSUE TITLE
Document undocumented interface methods

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3508]
There are several methods in the interfaces of [`ckan.plugins.interfaces`](https://github.com/ckan/ckan/blob/af2f061fdd08219d5070415be118d6063d38341f/ckan/plugins/interfaces.py) which are undocumented and therefore do not show up in the [interface reference](http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html). This is problematic, since implementing an interface partially will raise an exception sooner or later (unless you inherit the default implementations by explicitly passing `inherit=True` to `plugins.implements`).

Steps that should be taken:

1. Document all interface methods
2. Tell Sphinx not to hide undocumented methods (will also help if an undocumented method is added in the future)

**Comment by smotornyuk** [comment]
Resolved in #3519
