### ISSUE TITLE
Files uploaded in IE11 contain full file path in filename

### ISSUE THREAD

**Issue by david-nguyen** [ckan/ckan#3509]
I seem to be running into an issue with file uploads using IE11 (11.0.9600). The filename being passed through includes the full file path in the upload name. I've tested this on the demo site (2.5.2) and I cannot reproduce the issue there.

Similar to https://github.com/ckan/ckan/issues/2603

### CKAN Version if known (or site URL)
2.6.0

### Please describe the expected behaviour
Upload files keep the original name.

### Please describe the actual behaviour
When uploading a file through IE11 the full file path is included in the file name.

eg: `//shared drive/desktop/filename.ext` is displayed, actual link strips the slashes.

### What steps can be taken to reproduce the issue? 
Add resource to a dataset and upload a file using IE11  (11.0.9600).

I've tested this on a base install of 2.6 (no additional extensions) and the issue exists.

**Comment by david-nguyen** [comment]
Sorry after reviewing the changes this should be resolved in 2.62...I'll see if I can set up an instance to test this.

**Comment by amercader** [comment]
Thanks @david-nguyen, feel free to reopen the issue if it still happening.
