### ISSUE TITLE
Minimum setuptools version

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#3513]
CKAN requires a recent version of setuptools ever since some of CKAN's dependencies were upgraded. However there's nothing in the install instructions to sort this out. The default setuptools for our recommended distro, Ubuntu Trusty 14.04, is 2.2, which is too old.

Specifically:
* repoze.who needs setuptools 11.3 or later https://github.com/repoze/repoze.who/issues/26
* html5lib needs setuptools 18.5 or later https://github.com/ckan/ckan/issues/3232

**Comment by thenets** [comment]
I had the same problem. I did not find any tutorial about it and after some time I found a setuptools version. The version 20.4 worked for me, but the latest version raises many errors.

**Comment by davidread** [comment]
Maybe we should suggest people use a particular version then, rather than the latest.

24.2.1 was the latest when we discussed this on ckan-dev in July 2016. I used that and it seemed ok, but it [sounded like @thenets you had an issue with that or similar](https://lists.okfn.org/pipermail/ckan-dev/2016-July/010144.html).

18.5 is the version suggested then by @thenets, along with the older version of html5lib==0.999.

I think the safest thing then is to suggest people use 18.5 then, until we have the need and can test something newer.

**Comment by thenets** [comment]
Hi, @davidread. I had problems with setuptools on CKAN 2.5.x and 2.6.x versions.

**CKAN 2.5.2**
The version setuptools=18.5 worked for me. I didn't know why this specific version.

**CKAN 2.6.1**
I got errors with setuptools=18.5 on CKAN 2.6.1. I tried to install a lot of setuptools versions and the 20.4 was the first version that worked for me.

I have scripts of both versions, if you need.
If you choose a specific version and want someone to test, let me know. :)

**Comment by davidread** [comment]
Thanks @thenets I'll change the recommended version to 20.4. Do you have a record of when or how the error occurred with setuptools 18.5? It would be good to be accurate with the minimum version, even if the recommended one is later.

**Comment by thenets** [comment]
CKAN 2.6.1 with 

```

**Comment by thenets** [comment]
I don't remember :/ I'm using a lot of plugins on my test environment.

I just remember to change two thing from 2.5.2 to 2.6.1.
 - ADD apt-get install -y libmemcached-dev zlib1g-dev
 - CHANGE pip install setuptools==20.4
I don't know if all those modifications are really required.
