### ISSUE TITLE
[DataPreview] Excel embed redirects parent page on mobile

### ISSUE THREAD

**Issue by DavidLemayian** [ckan/ckan#3527]
### CKAN Version if known (or site URL)
v2.5-latest - [openAFRICA](https://africaopendata.org/)

### Please describe the expected behaviour
After embedding an Excel sheet view in a blog post or website, a user should be able to see the content of the website on desktop or mobile.

### Please describe the actual behaviour
On mobile, when you load the parent website / blog post that has embedded the view, it redirects immediately without warning.

### What steps can be taken to reproduce the issue? 
Embed data view of [this](https://africaopendata.org/dataset/mine-closure-certificates-in-south-africa/resource/320a0921-c92c-4409-ac99-d5bc371b38a9) resource to a blog post and load the blog post on mobile.

**Comment by amercader** [comment]
Yes, I can reproduce it myself, but this is an issue with this particular view extension:

https://github.com/jqnatividad/ckanext-officedocs

I suggest you open an issue there as this is not related to CKAN core.
Good luck!

**Comment by DavidLemayian** [comment]
Oh crap. Apologies. I thought it was being done by DataPreview.
