### ISSUE TITLE
Creation of dataset - different behaviour between Web API & CKAN Interface functionality

### ISSUE THREAD

**Issue by dmichelakis** [ckan/ckan#3528]
### CKAN Version if known (or site URL)
ckan_version: "2.5.2b"

### Please describe the expected behaviour
Create Dataset through the web interface & the function` ckan.logic.action.create.package_create(context, data_dict)` should both allow the use of underscores in dataset names.

### Please describe the actual behaviour
Create Dataset using the web interface transforms dynamically (i.e. while typed) underscores to hyphens however when using the `ckan.logic.action.create.package_create(context, data_dict)` I am allowed to create a dataset with underscores in their name.

### What steps can be taken to reproduce the issue? 
Create dataset using the web interface and attempt the same using the following function:
`ckan_instance.action.package_create(name='test_dataset',title=Test Dataset,extras=[{'key':'attribute_1','value':'name_1'},{'key':'attribute_2,'value':'name_2'}],notes = 'This is a dataset description',author='John Doe',owner_org = 'organisation-name',private=publicity)`

**Comment by amercader** [comment]
You can edit the name of the dataset when creating it via the web UI by clicking the "Edit" button next to the URL slug. This will accept underscores. The default formatting makes sense as in most cases you want the name to be URL friendly.

![tueah9g](https://cloud.githubusercontent.com/assets/200230/24657033/bf37fac0-193c-11e7-8f41-6b5729de0ba4.png)

Hope this makes sense.

**Comment by dmichelakis** [comment]
Hi,
I am familiar with the 'Edit' button. 
In your screenshot the title has underscores but the URL does not because they are not allowed (i.e. the default formatting that you mention). Using the CKAN web API I can generate URLs with underscores and hence the inconsistency that I mentioned in my previous post since the default formatting does not seem to apply in that case.
D.

**Comment by amercader** [comment]
Sorry, you are absolutely right. I wrongly assumed that when you clicked on Edit, you could edit the URL freely but this will also prevent underscores.

I think the relevant code that is enforcing this on the browser is this one:

https://github.com/ckan/ckan/blob/9db60058394569c232dde3b002d3768cedea45ff/ckan/public/base/javascript/plugins/jquery.url-helpers.js#L38

Perhaps if you have some time you can have a play with the regex to see if you can make it allow underscores.

**Comment by dmichelakis** [comment]
Np; thanks for pointing me to the right file for potentially fixing this.
D.

**Comment by klikstermkd** [comment]
@amercader @dmichelakis I'll take this one.
