### ISSUE TITLE
DataStore Map preview does not show plot markers from latitude / longitude fields

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#3540]
### CKAN Version if known (or site URL)
2.6.2

### Please describe the expected behaviour
The [DataStore Map](http://docs.ckan.org/en/ckan-2.6.2/maintaining/data-viewer.html#datastore-map) preview function should show plot markers from pairs of latitude / longitude fields.

### Please describe the actual behaviour
The map doesn't show anything. It seems that we don't get those markers.

### What steps can be taken to reproduce the issue? 
1. Upload a CSV file with pairs of latitude / longitude fields.
2. Create a DataStore Map view and specify latitude / longitude fields.
3. See the created map.

**Comment by u10313335** [comment]
I found that this issue can be solved by simply adding the `state` parameter to the `_reclineMapViewOptions` function in

https://github.com/ckan/ckan/blob/a6fc30979dd75890c3322006554a350102f6b10b/ckanext/reclineview/theme/public/recline_view.js#L124 like:

```javascript
view = new recline.View.Map($.extend(this._reclineMapViewOptions(dataset, this.options.map_config), {state:state}));
```

Not a good way though.

**Comment by tino097** [comment]
not able to reproduce, i can see the markers on the preview

`state,name,latitude,longitude
AL,Alabama,32.318231,-86.902298
AK,Alaska,63.588753,-154.493062
AR,Arkansas,35.20105,-91.831833
AZ,Arizona,34.048928,-111.093731
CA,California,36.778261,-119.417932
CO,Colorado,39.550051,-105.782067
CT,Connecticut,41.603221,-73.087749`

tried with this data as csv file

**Comment by u10313335** [comment]
@tino097 many thanks.
I forgot to mention that this issue only occurs when the name of latitude / longitude fields is NOT latitude / longitude.
For example, if I replace column names:
`state,name,latitude,longitude`
with
`state,name,latitude-a,longitude-a`,
then the markers will be gone.

**Comment by reitsma** [comment]
I work with 2.6.2 too, and I observe the same behavior with respect to the names of the fields. No markers when fields names are lat/lng.

**Comment by CarlQLange** [comment]
also had this issue, fix above worked great. thanks!

**Comment by anibalpacheco** [comment]
Why this is closed @tino097 ? It seems not fixed yet. Thanks

**Comment by Cheomm88** [comment]
Here with CKAN 2.7.2 I had the same issue with the change that @u10313335 said it works for me.

**Comment by amercader** [comment]
This needs to be patched and backported. If someone can create a PR targeting master with @u10313335 patch that would be awesome.

**Comment by Cheomm88** [comment]
@amercader how can I create a PR?? I dont find the way to create a branch

**Comment by tino097** [comment]
@Cheomm88 you should create a fork before

**Comment by Cheomm88** [comment]
@tino097 what about that 3 task for completion. Is it my fault?

**Comment by amercader** [comment]
@Cheomm88 thanks for helping out! If you are not familiar with how pull requests work this is a good place to start:

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

You created a fork and a pull request, but the pull request needs to be created in this repo. It should be really easy, have a look at the link above.
Don't worry about the tasks, you should only check the ones that apply to your changes.

**Comment by tino097** [comment]
@Cheomm88 you should make the PR against master branch in ckan repo
![pr](https://user-images.githubusercontent.com/2707446/38617818-45b202d2-3d98-11e8-8131-fa406af24571.png)

**Comment by Cheomm88** [comment]
@amercader @tino097 thanks for your help!
I see now my pull request in https://github.com/ckan/ckan/pulls, hope it helps to more people that uses CKAN and had this problem.
