### ISSUE TITLE
How to create default data (organization and editor)?

### ISSUE THREAD

**Issue by rwillmer** [ckan/ckan#3550]
### CKAN Version if known (or site URL)
2.6.2

### Please describe the expected behaviour
I would like to be able to supply a fixture for a set of default organisations and users,
to be created when the ckan server is first created.

### Please describe the actual behaviour
I cannot see how to do this without writing a bespoke paster command.

### What steps can be taken to reproduce the issue? 
Read documentation. Scratch head. Read code. Seek enlightenment in github.

Is there a recommended way to do this? The problem as far as I can see it, is that I need to be sysadmin to have the rights needed for this, which means AFAICS that it needs to be a paster command run locally on the instance.

**Comment by wardi** [comment]
`ckanapi load users | organizations` is what I use. You can create your fixtures with the `ckanapi dump` commands

**Comment by rwillmer** [comment]
Thanks!
