### ISSUE TITLE
Loading Time for dataset pages is very high [4-8] sec

### ISSUE THREAD

**Issue by francescomangiacrapa** [ckan/ckan#3561]
### CKAN Version
https://ckan-d-d4s.d4science.org/api/util/status
https://ckan-sobigdata.d4science.org/api/util/status
I'm comparing loading time of dataset pages to the two ckan above.
It seems there are some problems with sql queries.
DB is Postgres 9.4. Database schema are identical, there is no difference between them. Only data changes.
Ckan configurations and plugins are identical.
But the second ckan is very slow on rendering its dataset pages. It contains only 113 datasets.

### Please describe the actual behaviour
By clicking on Items (alias list of datasets https://ckan-sobigdata.d4science.org/dataset) response time is acceptable.
Instead, loading time for single dataset pages is very high (i.e. https://ckan-sobigdata.d4science.org/dataset/d2_1_ethics_board_establishment) circa [4-8]sec.

I've activated for a short time profiling and the results are the following:

For ckan-d.
```
Wed May 10 10:39:55 2017    /var/log/ckan-profiler/profiling.log
7382131 function calls (7128405 primitive calls) in 20.388 seconds
Ordered by: internal time
List reduced from 2760 to 100 due to restriction <100>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1873    2.562    0.001    2.606    0.001 {method 'execute' of 'psycopg2._psycopg.cursor' objects}
    29084    0.873    0.000    2.069    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/schema.py:770(__init__)
   691491    0.603    0.000    0.613    0.000 {isinstance}
   770282    0.533    0.000    0.533    0.000 {method 'pop' of 'dict' objects}
361089/350387    0.404    0.000    1.595    0.000 {getattr}
    29082    0.389    0.000    3.685    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/schema.py:1230(_make_proxy)
    90672    0.320    0.000    0.708    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/nodes.py:164(iter_child_nodes)
     6551    0.286    0.000    3.536    0.001 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py:317(corresponding_column)
    61089    0.238    0.000    0.368    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py:761(expire_instance)
    27070    0.207    0.000    0.428    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py:530(visit_column)
   150565    0.204    0.000    0.281    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/nodes.py:148(iter_fields)
```

For ckan-sobigdata.
```
Wed May 10 10:57:31 2017    /var/log/ckan-profiler/profiling.log
10204585 function calls (9912807 primitive calls) in 71.787 seconds
Ordered by: internal time
List reduced from 2967 to 100 due to restriction <100>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    68591    5.637    0.000   13.341    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/schema.py:770(__init__)
     1955    3.569    0.002    3.610    0.002 {method 'execute' of 'psycopg2._psycopg.cursor' objects}
  1661370    3.018    0.000    3.018    0.000 {method 'pop' of 'dict' objects}
    68589    2.621    0.000   23.930    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/schema.py:1230(_make_proxy)
   907270    2.301    0.000    2.317    0.000 {isinstance}
    14953    1.803    0.000   23.135    0.002 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py:317(corresponding_column)
   144367    1.589    0.000    2.405    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py:761(expire_instance)
   192823    1.146    0.000    1.963    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/elements.py:3261(_expand_cloned)
177194/139922    1.145    0.000   30.334    0.000 /usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py:709(__get__)
```

As you can see, sqlalchemy/sql/* performs its code/queries spending different time on ckan's reported.
Can you help me to understand why? Any idea?

**Comment by TkTech** [comment]
A regular stack trace isn't terribly useful here. Since it looks like you have physical access to these machines please update your Postgres config with slow query logging (the most basic of which is [setting `log_min_duration_statement `](https://www.postgresql.org/docs/current/static/runtime-config-logging.html). If you can post an example of what queries are being run when you hit that page we can better find the issue.

**Comment by amercader** [comment]
Hi, thanks for submitting your issue. 

This sounds like a specific issue with your particular deployment. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

Thanks!

**Comment by francescomangiacrapa** [comment]
@amercader, @TkTech 
I just posted this question on StackOverlflow.. adding more details regarding sql queries.
http://stackoverflow.com/questions/43921335/ckan-loading-time-for-dataset-pages-is-very-high-4-8-sec
Number of query is too much on ckan-sobigdata compared to ckan-d-d4s
I hope someone can help me on where I can investigate.

Thanks,
Francesco.

**Comment by florianm** [comment]
@francescomangiacrapa if your issue still persists, here's some troubleshooting which may or may mot be helpful: https://github.com/ckan/ckan/issues/3264

We experienced degraded performance when we accumulated a ton of revisions after some vigorous API / batch-updating.
