### ISSUE TITLE
My organizations on dashboard page show wrong number of datasets for organization.

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3579]
CKAN Version
All versions

Expected behaviour
When logged user switch to My organizations tab at dashboard, the number of datasets for the organization should match the number of datasets that found on **/organization** page.

Actual behaviour
The number of datasets are not match the number of datasets on **/organization** page.

To reproduce the issue there should be at least 1 organization with couple of public datasets and at least one private.

**Comment by tino097** [comment]
#3580
