### ISSUE TITLE
Trouble installing Ckan Extensions

### ISSUE THREAD

**Issue by goncaloGIT** [ckan/ckan#3585]
Hi

## CKAN Version if known (or site URL)

2.6.2

## Problem

Im trying to install an extension, to be specific 

- https://github.com/EUDAT-B2FIND/ckanext-b2find

- https://github.com/EUDAT-B2FIND/ckanext-datesearch

## Please describe the actual behaviour

Cant see the extension in Ckan, but the extension seem's to be enable because ckan is up and running, yet there's are no error in **/var/log/apache2/ckan_default.error.log**  

##What steps can be taken to reproduce the issue? 

In the extension folder i did **python** setup.py install
in **/etc/ckan/default/production.ini** added **b2find** and **datesearch** in line **ckan.plugins** 
restarted apache2

### Other information
Ubuntu 14.04
Apache2

Best Regards Gonçalo

**Comment by tino097** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!
