### ISSUE TITLE
resource view filter user filters JS error

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#3590]
### CKAN Version if known (or site URL)

master

### Please describe the expected behaviour

I define a new resource view with `filterable=True` and enable it in my plugins. The "Add Filter" interface available to users viewing the view be usable to add new filters.

### Please describe the actual behaviour

I get the following JS error when clicking on the "Add filter" text from the view view page:

```
resource-view-filters.js:52 Uncaught TypeError: Cannot read property '_' of undefined
    at HTMLAnchorElement.<anonymous> (resource-view-filters.js:52)
    at HTMLAnchorElement.dispatch (jquery.js:5095)
    at HTMLAnchorElement.elemData.handle (jquery.js:4766)
```

### What steps can be taken to reproduce the issue? 

Create and enable a view plugin with `filterable=True` and enable it. Create a resource view, and view that view.

reverting 9e4599b468d2c96a37a6d1f58d285d0494fae5c0 and 9533d7a6fe7ec6cbda530c3bca39bfc0de022584 seems to fix the problem.

**Comment by wardi** [comment]
@torfsen I'm sure there's a fix better than reverting the commits, do you have time to take a look?

**Comment by torfsen** [comment]
@wardi Sorry for the delay, I was on vacation. I'll take a look at it.

**Comment by torfsen** [comment]
That PR solves the issue for me.

**Comment by tino097** [comment]
@wardi @amercader This PR should be backported to 2.7 because we experienced issues on portals using ckan 2.7

**Comment by amercader** [comment]
@tino097 great, marked for backporting
