### ISSUE TITLE
ImportError: No module named werkzeug.test [Installation on Windows]

### ISSUE THREAD

**Issue by ddlam** [ckan/ckan#3591]
### CKAN Version if known (or site URL)
CKan 2.5.2
>git clone https://github.com/ckan/ckan.gif
>git checkout tags/ckan-2.5.2

### Please describe the expected behaviour
Setup Python 2.7.13, PostgreSQL newest version, solr-4.9.1, ckan2.5.2
Following https://github.com/ckan/ckan/wiki/How-to-Install-CKAN-2.5.2-on-Windows-7 on the step
"Create database tables"
(ckan) C:\src\ckan>paster db init -c development.ini

ImportError recieved

### Please describe the actual behaviour
By running:
(ckan2.5.2env) D:\src\ckan>paster db init -c development.ini

  File "d:\users\administrator.user1-pc\envs\ckan2.5.2env\lib\site-packages\pkg_
resources\__init__.py", line 2303, in load
    return self.resolve()
  File "d:\users\administrator.user1-pc\envs\ckan2.5.2env\lib\site-packages\pkg_
resources\__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\src\ckan\ckan\config\middleware\__init__.py", line 7, in <module>
    from werkzeug.test import create_environ, run_wsgi_app

Error Occurs:
ImportError: No module named werkzeug.test

After running >easy_install werkzeug
The error changed to :
ImportError: No module named flask

After running >easy_install flask
The error changed to :
ImportError: No module name config
and this cannot be resolved.

### What steps can be taken to reproduce the issue? 
13

**Comment by tino097** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the  #ckan tag on SlackOverflow as we dont officialy support Windows.
We would suggest to use Ubuntu on VM.
Thanks!

**Comment by ddlam** [comment]
Posted here:
https://stackoverflow.com/questions/44402273/importerror-no-module-named-werkzeug-test-installation-on-windows
