### ISSUE TITLE
Filter results button is not working

### ISSUE THREAD

**Issue by ZoranPandovski** [ckan/ckan#3593]
### CKAN Version if known (or site URL)
Tested in 2.5.3 and 2.6

### Please describe the expected behaviour
In organization datasets page if the user use mobile device he can see Filter results button. I am not sure what this button should do.

### Please describe the actual behaviour
The button doesn't do nothing, it only adds class to a body and nothing else.

### What steps can be taken to reproduce the issue? 
Just use mobile device to open ckan, or change browser to mobile view.

https://github.com/ckan/ckan/blob/master/ckan/templates/snippets/search_form.html#L73

**Comment by TkTech** [comment]
Added in https://github.com/ckan/ckan/commit/2654fbb8fb258fa15e39e16cd103aed522ebf8a0 for reference.

**Comment by ZoranPandovski** [comment]
This only works on home page when you search datasets, on organization page it's not working. Also tested also on http://demo1.ckan.io/ .

**Comment by klikstermkd** [comment]
The "Filter Results" button should only be displayed in the "Datasets" page and not in "Organizations" and "Groups" page, since filters are only available for the "Datasets" page. 

So I don't see this as an issue.
