### ISSUE TITLE
Smart/Quick way to delete "one shot" all dataset of an organization??

### ISSUE THREAD

**Issue by francescomangiacrapa** [ckan/ckan#3597]
Hi all,

I opened a ticket sorry for "abuse"
A simple question..
Is there a smart/quick way to permanently delete (“purge”) "one shot" all dataset belonging to an organization?
Is there a facility via GUI or also via sysadmin command..?

I've an organization within 100k dataset.. 

Thanks in advance for your feedback

Cheers,
Francesco

### CKAN Version if known (or site URL)
2.6.x

**Comment by TkTech** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!
