### ISSUE TITLE
IPackageController Interface don't have before_update and before_create methods

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3598]
### CKAN Version
All versions

### Expected behaviour
When user(admin) creates/updates dataset he can hook the dict that he got in method to modify the data that he gets before the actuall create/update.

### Actual behaviour
User can't hook dict before package creates/updates.

Those methods would be very useful for situations, when user got some hidden fields that need to get all data or part of the data from another field in the form. In a result user wont need a custom javascript to deal with such situations and can use CKAN hooks more often.
Issue that can appear after adding those methods related to naming issue, because **IResourceController** got same methods, so when user tries to use both of those methods he got naming conflict.

**Comment by HilariousGil** [comment]
I was looking for this functionality. Thanks @Engerrs 
@wardi I was wondering, is there a specific reason for this not to be merged into any release? or was simply overlooked...

**Comment by frafra** [comment]
Related pull request: https://github.com/ckan/ckan/pull/3599

**Comment by wardi** [comment]
conflicting methods have been renamed also this can be accomplished by customizing the schema or overriding package_create/package_update actions
