### ISSUE TITLE
Feature: new "private-only" role

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan#3608]
### CKAN Version if known (or site URL)

2.7

### Please describe the expected behaviour

"untrusted" users shouldn't be allowed to change visibility. Visibility should be private by default.

### Please describe the actual behaviour

The "bad" dataset is available to everyone

### What steps can be taken to reproduce the issue? 

1. Login as "untrusted" member of organization.
2. Publish "bad" dataset

**Comment by amercader** [comment]
@Vanuan With the default authorization configuration users need to belong to an organization and be made admins or editors from this organization to be able to edit datasets. This is essentially what you are describing (making someone and editor means you trust them).

More advanced authorization workflows where datasets need to be made public by administrators could be implemented in an extension.

Cheers
