### ISSUE TITLE
Serving CKAN over none root (http://example.com/ckan)

### ISSUE THREAD

**Issue by Danidude** [ckan/ckan#3618]
### CKAN Version if known (or site URL)
CKAN version 2.6.2
Tested with latest version too.

### Please describe the expected behaviour
In the configuration file (development.ini) I have set both 
ckan.site_url = http://example.com
ckan.root_path = /ckan/{{LANG}}

Fanstatic to serve the static files:
/ckan/fanstatic/vendor/....

### Please describe the actual behaviour
Fanstatic is not adding the '/ckan/' path to the static file url.
The static urls look like: /fanstatic/vendor/....
Since CKAN is only under the /ckan/ path it is not getting any static files.

### What steps can be taken to reproduce the issue? 
I have installed CKAN using this guide: http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html

and deplyed CKAN using this guide: http://docs.ckan.org/en/latest/maintaining/installing/deployment.html

In my Nignx config file, I have put the path to ckan to be: location /ckan, since the root serves an other python server.

I found that fanstatic have base_url in its configuration that can set the base url for the static files, however I did not find any place in CKAN to configure the fanstatic properties.

**Comment by amercader** [comment]
Mounting CKAN in a non root location is a recurring source of problems. @fanjinfei will try to find some time to investigate. And this is also perhaps related to something that @tino097 is working on currently.

**Comment by Danidude** [comment]
I did a workaround this problem by having the nginx server just redirect the missing paths to the ckan server.

When I did this I also found out that some more URLs do not have the /ckan path to their URL:
/base/images/ckan-logo-footer.png
/base/images/background-tile.png
/base/images/bg.png

Hope this is helpfull :)

**Comment by fanjinfei** [comment]
@Danidude Can you try https://github.com/ckan/ckan/pull/3628 ?

**Comment by Danidude** [comment]
Sorry for the late answer, I just tested the changes, and it works as I would expect now :)
Thanks for the quick fix for this problem.

Now I have an other question, not sure where to ask this and it is not related to this issue. :) 

I was looking at https://ckan.org/portfolio/search-and-discovery/, and it says CKAN supports Fuzzy-matching, is this possible in the API search (package_search), if so, how to enable it?

**Comment by amercader** [comment]
Fixed in #3628 

@Danidude Try the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

Thanks!

**Comment by iamarnavgarg** [comment]
Hi @Danidude I am also facing similar like issues,i.e I am unable to view the  text format type/pdf format type dataset while I am able to view only Image dataset ? Can you suggest me what all i can do? I have mounted my ckan on /ckan 

For more detailed explanation: https://opendata.stackexchange.com/questions/13671/text-view-and-graphics-not-being-displayed-properly-in-ckan-gui
