### ISSUE TITLE
Links to issues/PRs in Changelog page

### ISSUE THREAD

**Issue by klikstermkd** [ckan/ckan#3619]
In the docs in the [Changelog](http://docs.ckan.org/en/latest/changelog.html) page, at the end of every listed feature/bug fix for a particular release, there is a number of the issue/PR.

I think it would be nice so that those numbers have a link attached of the issue/PR on Github, so that it's much easier for someone to view directly the issue/PR, instead of manually copying the number.

**Comment by klikstermkd** [comment]
@amercader I can make the change :)

**Comment by amercader** [comment]
Thanks @klikstermkd
