### ISSUE TITLE
Resource titles cannot contain unicode when created via API

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckan#3632]
### CKAN Version if known (or site URL)
~2.6

### Please describe the expected behaviour
Resource can be created with the API

### Please describe the actual behaviour
Here is the result when using 'name': "Revenues received by government agencies - Cote d'Ivoire"

```
UPLOADING RESOURCE /government/cote-d-ivoire-government.csv TO DATASET eiti-summary-data-table-for-cote-d-ivoire
{u'help': u'http://li1665-139.members.linode.com/api/3/action/help_show?name=resource_create', u'success': True, u'result': {u'mimetype': u'text/csv', u'cache_url': None, u'hash': u'', u'description': u'', u'name': u"Revenues received by government agencies - Cote d'Ivoire", u'format': u'CSV', u'url': u'http://li1665-139.members.linode.com/dataset/ceb43947-d9a0-4c35-b5f1-90b0b1811a7b/resource/061a5a5f-4fba-4bc1-a770-031af10ca50e/download/revenues-received-by-government-agencies-cote-divoire.csv', u'datastore_active': False, u'cache_last_updated': None, u'package_id': u'ceb43947-d9a0-4c35-b5f1-90b0b1811a7b', u'created': u'2017-06-23T10:57:46.922239', u'state': u'active', u'mimetype_inner': None, u'url_type': u'upload', u'last_modified': u'2017-06-23T10:57:46.783743', u'position': 1, u'revision_id': u'c971f824-89df-44ec-bc0d-fcc5d4185d2a', u'type': u'file.upload', u'id': u'061a5a5f-4fba-4bc1-a770-031af10ca50e', u'resource_type': None, u'size': 53252}}
````

Here is the result when using 'name': "Revenues received by government agencies - C\u00f4te d'Ivoire"

```
{u'help': u'http://li1665-139.members.linode.com/api/3/action/help_show?name=resource_create', u'success': False, u'error': {u'url': [u'Missing value'], u'__type': u'Validation Error'}}
```

### What steps can be taken to reproduce the issue? 
API Post to resource_create with JSON body and a unicode character (e.g. `\u00f4`) in the "name" field

**Comment by mattfullerton** [comment]
I am using ckanext-scheming as well in case that's relevant

**Comment by smotornyuk** [comment]
I was unable to reproduce error using either ` C\u00f4te d'Ivoire`, `russian symbols or kanji at both 2.6 and 2.7 versions(i just checked - http://li1665-139.members.linode.com/api/action/status_show - looks like this instance uses v2.7. 
And the fact, that validation error complains on missing url is quite suspicious . @mattfullerton couldn't you please provide me with request body, you sent to sever in both cases?

**Comment by mattfullerton** [comment]
Now that you pointed out that the validation error is a missing URL, I rather suspect something is going wrong with the file upload with that name involved and then it wants to have a URL and then URL isn't there; so the bug is somewhere else and not directly with CKAN, I will take another look.

**Comment by mattfullerton** [comment]
@smotornyuk Looks like its the files['upload'] parameter of requests.post in my python script that can't cope with the funny letters. I was using the same variable name for both. Sorry for the bother.
