### ISSUE TITLE
No such file or directory: '/usr/lib/ckan/default/src/ckan/requirement-setuptools.txt' during installation from source

### ISSUE THREAD

**Issue by brylie** [ckan/ckan#3641]
### CKAN Version if known (or site URL)
Latest (setting up development environment)

### Please describe the expected behaviour
When following the CKAN [installation from source](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) instructions, I should be able to complete the development setup on Ubuntu 16.04. This implies that all requisite steps should be fully documented.

### Please describe the actual behaviour
I get the following error when creating the virtualenv:

```
$ virtualenv --no-site-packages /usr/lib/ckan/default
Using base prefix '/home/brylie/anaconda3'
New python executable in /usr/lib/ckan/default/bin/python
/usr/lib/ckan/default/bin/python: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable /usr/lib/ckan/default/bin/python is not functioning
ERROR: It thinks sys.prefix is '/home/brylie' (should be '/usr/lib/ckan/default')
ERROR: virtualenv is not compatible with this system or executable
```

I am getting an error on the step **2b: Install the recommended version of ‘setuptools’:**

```
 pip install -r /usr/lib/ckan/default/src/ckan/requirement-setuptools.txt

Could not open requirements file: [Errno 2] No such file or directory: '/usr/lib/ckan/default/src/ckan/requirement-setuptools.txt'

```

### What steps can be taken to reproduce the issue? 
Follow the steps on [Installing CKAN from source](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html)

**Comment by torfsen** [comment]
Which CKAN version are you installing? The docs you're quoting are for the current development version, which [does include the `requirement-setuptools.txt` file](https://github.com/ckan/ckan/blob/master/requirement-setuptools.txt).

If you're installing a specific release version then make sure that you use that version's documentation. For example [the instructions for installing CKAN 2.6.2 from source](http://docs.ckan.org/en/ckan-2.6.2/maintaining/installing/install-from-source.html), which doesn't mention `requirement-setuptools.txt`.

**Comment by brylie** [comment]
Thanks @torfsen.

Regarding the Python environment error:

```
ERROR: The executable /usr/lib/ckan/default/bin/python is not functioning
```

Should I open another support request? I think it may be related to using Anaconda for managing my Python packages/version.

**Comment by torfsen** [comment]
@brylie Yes, that would be a separate issue. Also note that traditional support requests should go to [StackOverflow using the `ckan` tag](https://stackoverflow.com/questions/tagged/ckan). GitHub issues, on the other hand, are intended for bug reports.

**Comment by brylie** [comment]
> pip install setuptools==20.4

@torfsen this addition seems to have been reverted in the [2.7.0 version of the CKAN docs](http://docs.ckan.org/en/ckan-2.7.0/maintaining/installing/install-from-source.html)

**Comment by torfsen** [comment]
@brylie: I've opened a new ticket (#3859).
