### ISSUE TITLE
revisit solr tracking summary values

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#3648]
@alexandru-m-g raised part of the change in #2207 as unnecessary in a recent mailing list post.

For the past few CKAN versions we no longer have the tracking summary details available from package_search, they're only being stored in solr and on request available from package_show. One use of the tracking summary in package_search is marking "hot" datasets in the results page.

Is anyone opposed to restoring the tracking summary information in package_search results? should package_show with include_tracking=False include the summary from solr instead of nothing (solr values aren't updated in real-time)?

**Comment by alexandru-m-g** [comment]
@wardi, indeed that's exactly how we're using the tracking summary on the results page ( to flag them as "hot").
P.S. I think you meant that "they're only stored in the database" (not solr)
Thanks for opening this discussion.

**Comment by wardi** [comment]
They are stored in solr for ordering by popularity: https://github.com/ckan/ckan/blob/master/ckan/lib/search/index.py#L192

**Comment by alexandru-m-g** [comment]
Right, didn't realize those 2 fields existed. 
I see now they are in solr with stored=false, indexed=true.

**Comment by groundrace** [comment]
@wardi Having total views and recent views data on the dataset list seems to me really usefull indeed I'm actually using on the CKAN instances I manage. Upgrading to the recent 2.8.0 looks like in the SOLR data_dict field the tracking_data for both the dataset and resources isn't properly stored. I've just patched my 2.8.0 and if needed I can submit a pull request to have it re-enabled

**Comment by wardi** [comment]
@groundrace yes please

**Comment by wardi** [comment]
tracking has been moved to its own extension #7772
