### ISSUE TITLE
Problem with Solr an proxy

### ISSUE THREAD

**Issue by davidheuckrodt** [ckan/ckan#3653]
### CKAN Version if known (or site URL)
2.6

### Please describe the expected behaviour
In the productive environment I have to go over a Proxy. I wrote the proxy details in the /etc/environment config. Later the harvester (ckanext-harvest and ckanext-spatial) should also go over the proxy settings. 
 
### Please describe the actual behaviour
Always I'am using the `export http_proxy='...'` over the command line i get the following error for solr after trying to make a http-request:

`ERROR [pysolr] Connection to server 'http://IP:8983/solr/select/?q=%2A%3A%2A&rows=1&wt=json' timed out: HTTPConnectionPool(host='IP', port=PORT): Read timed out. (read timeout=60)`

### What steps can be taken to reproduce the issue? 
1. Set the proxy settings in the `/etc/environment`

```
http_proxy=http://IP:PORT/
https_proxy=http://IP:PORT/
ftp_proxy=http://IP:PORT/
HTTP_PROXY=$http_proxy
HTTPS_PROXY=$https_proxy
FTP_PROXY=$ftp_proxy
```

2. I tried to make it work with `os.environ['HTTP_PROXY'] ` in the `/etc/ckan/default/apache.wsgi` file settings like written [here](https://github.com/ckan/datapusher/issues/60) - with this setting I always get am "504 Gateway Time-out" every time I reload the page!

**Comment by amercader** [comment]
Hi @davidheuckrodt , thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

Thanks!

**Comment by wardi** [comment]
you might be missing a NO_PROXY environment variable setting for your solr host

**Comment by davidheuckrodt** [comment]
Hey. Thanks for the support.

I got the problem solved by adding the NO_PROXY variable for the solr-port.

But the harvester does not work either... Her the information from the log... i will also open an thread in the harvester-repository...

`2017-07-05 09:21:29,158 DEBUG [ckanext.harvest.queue] Received harvest job id: fb70cddf-4d37-4690-9b66-d60363aeb3e4`

`2017-07-05 09:21:29,163 DEBUG [ckanext.harvest.harvesters.ckanharvester] In CKANHarvester gather_stage (https://opendata.swiss)`
`
2017-07-05 09:21:29,165 DEBUG [ckanext.harvest.harvesters.ckanharvester] Last error-free job: None`

`2017-07-05 09:21:29,165 DEBUG [ckanext.harvest.harvesters.ckanharvester] Searching for CKAN datassets: https://opendata.swiss/api/3/action/package_search?sort=id+asc&start=0&rows=100`

`2017-07-05 09:23:36,446 INFO  [ckanext.harvest.harvesters.ckanharvester] Searching for all datasets gave an error: Error sending request to search remote CKAN instance https://opendata.swiss using URL u'https://opendata.swiss/api/3/action/package_search?sort=id+asc&start=0&rows=100'. Error: URL error: [Errno 110] Connection timed out`

`2017-07-05 09:23:36,462 INFO  [ckanext.harvest.model] Unable to search remote CKAN for datasets:EError sending request to search remote CKAN instance https://opendata.swiss using URL u'https://opendata.swiss/api/3/action/package_search?sort=id+asc&start=0&rows=100'. Error: URL error: [Errno 110] Connection timed out url:https://opendata.swissterms:[]`

`2017-07-05 09:23:36,471 ERROR [ckanext.harvest.queue] Gather stage failed`

Has someone has an idea what the problem can be with `[Errno 110] Connection timed out` and the proxy setting. I put the proxy settings in the `/etc/environment`, `apache.wsgi` and `ckanharvester.py`
