### ISSUE TITLE
Disable preview for some reosource

### ISSUE THREAD

**Issue by aborruso** [ckan/ckan#3670]
Hi,
I have CKAN ckan 2.6.2 and I would like to disable preview for a GeoJSON resource. Is there a way to disable it only for a specific resource?

Thank you

**Comment by Aaron-M** [comment]
Would creating the resource (during which it automatically creates the preview), and then editing the resource and deleting the auto created view work for you?

**Comment by amercader** [comment]
@aborruso there is no way to prevent views from being prevented on particular resources. You can delete it manually as @Aaron-M suggests but if that doesn't work you can extend the relevant View plugin and override the [`can_view()`](https://github.com/ckan/ckanext-geoview/blob/master/ckanext/geoview/plugin.py#L219) method to add any logic you need.

Hope this helps.
