### ISSUE TITLE
Some comments on features while customizing CKAN

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#3671]
I've forgot to send comments I had while developing ckan for Polish gov. All what's below relates to CKAN 2.3, but maybe some of these "issues" hasn't been yet resolved.

I've put comments in the code: https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/search?utf8=%E2%9C%93&q=TODO+ckan-dev&type=

Briefly these are:
- [ ] ckan.new_authz should be overridable by IAuthFunctions as well
- [ ] add converters and validators as IValidator? should converters have their own Interface for extending to allow tk.get_converter?
- [ ] load all properties from SystemInfo at load, instead of using app_globals.auto_update; get_global_key should search also through plugin variables
- [ ] recode resources previews - it's sometimes quite memory demanding to just show labels "Preview' or "More information"

**Comment by amercader** [comment]
@KrzysztofMadejski thanks for your feedback

2.3 is no longer supported, so we encourage you to upgrade to the latest version of CKAN

> ckan.new_authz should be overridable by IAuthFunctions as well

Perhaps some of the stuff handled there can be moved up to the auth functions. Anything in particular?

> add converters and validators as IValidator? should converters have their own Interface for extending to allow tk.get_converter?

This was added on previous versions

> load all properties from SystemInfo at load, instead of using app_globals.auto_update; get_global_key should search also through plugin variables

Not sure I understand this one

> recode resources previews - it's sometimes quite memory demanding to just show labels "Preview' or "More information"

There has been a lot of of work on resource previews in recent versions. I suggest you check a newer version to see if this has been addressed.

Cheers
