### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#3672]
### CKAN Version if known (or site URL)
Any - latest documentation

### Please describe the expected behaviour
Links within documentation should work

### Please describe the actual behaviour
The links at http://docs.ckan.org/en/latest/maintaining/linked-data-and-rdf.html
to 
http://demo.ckan.org/dataset/newcastle-city-council-payments-over-500.xml
http://demo.ckan.org/dataset/newcastle-city-council-payments-over-500.ttl
http://demo.ckan.org/dataset/newcastle-city-council-payments-over-500.n3
http://demo.ckan.org/dataset/newcastle-city-council-payments-over-500.jsonld

do not work (need to relocate these example files to a stable location).

### What steps can be taken to reproduce the issue? 
Visit http://docs.ckan.org/en/latest/maintaining/linked-data-and-rdf.html and click on the links

**Comment by amercader** [comment]
Not sure where this dataset went, but yes, we should find a more permanent place for the links.

**Comment by amercader** [comment]
Fixed now, see https://github.com/ckan/ckan/issues/3707#issuecomment-316061042
