### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/var/lib/ckan/storage/uploads'

### ISSUE THREAD

**Issue by dassolkim** [ckan/ckan#3676]
I installed ckan latest version from source and using tomcat7 instead of jetty. 
but, When I tried to add a new organization, I got this error. There was an internal server error on the web, and this error occurred when I looked at the logs.

_
Error - <type 'exceptions.OSError'>: [Errno 13] Permission denied: '/var/lib/ckan/storage/uploads'
URL: http://114.70.235.44:5000/organization/new
File '/usr/local/lib/python2.7/dist-packages/weberror/errormiddleware.py', line 171 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/lib/python2.7/dist-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/lib/python2.7/dist-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/config/middleware/pylons_app.py', line 243 in inner
  result = application(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/beaker/middleware.py', line 156 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/local/lib/python2.7/dist-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/config/middleware/common_middleware.py', line 28 in __call__
  return self.app(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/lib/base.py', line 211 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/controllers/group.py', line 473 in new
  return self._save_new(context, group_type)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/controllers/group.py', line 541 in _save_new
  group = self._action('group_create')(context, data_dict)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/logic/__init__.py', line 457 in wrapped
  result = _action(context, data_dict, **kw)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/logic/action/create.py', line 868 in organization_create
  return _group_or_org_create(context, data_dict, is_org=True)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/logic/action/create.py', line 631 in _group_or_org_create
  upload = uploader.get_uploader('group')
File '/home/ckan/ckan/lib/default/src/ckan/ckan/lib/uploader.py', line 31 in get_uploader
  upload = Upload(upload_to, old_filename)
File '/home/ckan/ckan/lib/default/src/ckan/ckan/lib/uploader.py', line 107 in __init__
  os.makedirs(self.storage_path)
File '/usr/lib/python2.7/os.py', line 150 in makedirs
  makedirs(head, mode)
File '/usr/lib/python2.7/os.py', line 157 in makedirs
  mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/lib/ckan/storage/uploads'
_

I don't know why this error occured. I already tried 

> sudo chown -R www-data /var/lib/ckan
> sudo chmod -R u+rwx /var/lib/ckan

but, nothing was fixed. I think this is a problem with file uploads, but I already set up the guide as well please help me solve this error..

**Comment by smotornyuk** [comment]
@dassolkim , are you running CKAN using apache?  If not(i.e. you are using `paster serve ...`, then you need to change owner of `/var/lib/ckan` to you current user

**Comment by dassolkim** [comment]
@smotornyuk thank you for your advice!!!!
