### ISSUE TITLE
Overriding datastore authorization system

### ISSUE THREAD

**Issue by ggcatu** [ckan/ckan#3679]
Hello guys,

I've been looking through and found I can override ckan authorization system with a plugin that implements IAuthFunctions and just return the new fuction that I want.

But, as Datastore is already a plugin, how should I proceed in order to modify it s behaviour ?
Of course, I don't want to directly modify the Datastore functions but instead write a plugin.

In the examples, you show how to implement IDatastoreBackend but I want to override

![image](https://user-images.githubusercontent.com/9058818/28022519-b6756508-658b-11e7-95b4-57f288e6bf14.png)

Edit:

Actually I just found this:

https://github.com/ckan/ckan/blob/master/ckan/authz.py#L74

![image](https://user-images.githubusercontent.com/9058818/28022794-71aac124-658c-11e7-8f82-5e55e8e330b0.png)

Seems like having 2 plugins override the same auth function will raise an error.

**Comment by amercader** [comment]
This sounds totally reasonable.

@wardi @fanjinfei  you recently pushed code to allow chaining of action functions from extensions. Could the same principle be applied to auth functions?

**Comment by wardi** [comment]
@amercader absolutely. That's something we simply overlooked.

**Comment by CRImier** [comment]
I'm affected by this problem. Is there something I could do to help fix this? I want to have additional checks in 'datastore_search' auth function, but I can't for now, since checks are application-specific and customer desires to have them in a separate plugin.
