### ISSUE TITLE
Retire Google+ social network link

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#3680]
Google+, though still active, is for all intents and purposes, dead.

Why not replace it with a mailto link or even add LinkedIn Social Sharing? (https://developer.linkedin.com/docs/share-on-linkedin)

**Comment by amercader** [comment]
+1 to remove Google+, not a big fan of LinkedIn though :) 

In any case feel free to send a PR with the changes on the default theme

And just for the record, it is trivial to choose the sharing options by customizing the `snippets/social.html` snippet.
