### ISSUE TITLE
Scrollbar on "Create organization" button

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#3690]
### CKAN Version if known (or site URL)

master

### Please describe the actual behaviour

On the 'Create an Organization' page http://localhost:5000/organization/new
the 'Create Organization" (submit) button has a little scrollbar along its right edge for some reason. It's harmless, but no doubt should be removed.

![create](https://user-images.githubusercontent.com/307612/28207670-7c216178-6882-11e7-9ae6-e8b4acb2783c.png)

### What steps can be taken to reproduce the issue? 

This is on Ubuntu 16.04 / Chrome 59. It doesn't occur on Firefox.

**Comment by klikstermkd** [comment]
Can you attach a screenshot? I am using Ubuntu 16.04 / Chrome 59 as well and it looks ok to me.

**Comment by davidread** [comment]
I've added in a pic now. I have now learnt that it only occurs on 90% zoom. This may be too obscure to worry about.

**Comment by klikstermkd** [comment]
Are you sure you added a pic? I can't see it. 

Even on 90% it's displayed properly on my machine.

**Comment by davidread** [comment]
sorry, it's there now

**Comment by klikstermkd** [comment]
Actually it shows up on 110%.
