### ISSUE TITLE
Clipped buttons on resource/add page

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#3691]
### CKAN Version if known (or site URL)

master

### Please describe the actual behaviour

On the resource add page e.g. http://localhost:5000/dataset/new_resource/simple
the buttons at the bottom ("Previous", "Save & Add Another" and "Finish") have the bottom few pixels missing, so that the two buttons which are just outlines only have 3 sides.

![buttons](https://user-images.githubusercontent.com/307612/28207930-5868c02c-6883-11e7-94c3-8fceb481e024.png)

### What steps can be taken to reproduce the issue? 

1. Go to http://localhost:5000/dataset/new and give it a name.
2. Click Next. On this screen you see the problem with the buttons.
Occurs Ubuntu 16.04 / Chrome 59 at 100% zoom. Other zoom levels are ok. Browser width must be over 1000px. Firefox is ok.

**Comment by klikstermkd** [comment]
Can you attach a screenshot of what is actually wrong? I went to that page and the buttons seem ok to me.

**Comment by davidread** [comment]
pic added. browser width must be over 1000px for it to occur.

**Comment by klikstermkd** [comment]
For me it shows the clipping on 110%.

**Comment by davidread** [comment]
Yeah, one of those marginal things. If you or anyone else can look for a way to add a bit of tolerance to avoid this, then that'd be great.
