### ISSUE TITLE
Autocomplete only suggests tags once user stops typing

### ISSUE THREAD

**Issue by kmbn** [ckan/ckan#3693]
### CKAN Version if known (or site URL)
2.6.2

### Please describe the expected behaviour
Autocomplete suggests tags as the user types, e.g., if the tag `technology` already exists, and the user starts to type `technology`, autocomplete will suggest `technology` before the user finishes typing the word. Users can thus discover what tags exist and select the pre-existing or canonical verison and avoid creating tags with alternate spellings or abbreviations, which happens now and has led to reports that the autocomplete feature isn't working.

### Please describe the actual behaviour
Autocomplete only suggests tags once the user stops typing. For example, if the tag `technology` already exists, the user can type the entire word without autocomplete suggesting `technology`. It only returns a suggestion if the user stops typing, e.g., the user has to type `tech` and then stop typing for a second before `technology` is suggested. If the tag `infrastruktur` already exists, it's possible to type `infrastructure` without ever seeing a suggestion for the existing version, leading to the creation of an alternate version of the `infrastruktur` tag.

### What steps can be taken to reproduce the issue? 
Create or edit a dataset on http://demo.ckan.org and start entering tags. `technology` is one of the current tags, but this will work with any tag in the DB. Type `technology` as you usually would: you won't see a suggestion. Then type it very slowly: you won't see a suggestion. Then type part of the word and just stop typing. Only then will suggestions appear after a delay.

**Comment by klikstermkd** [comment]
I think this is intentionally implemented like this, i.e. it debounces the typing so that requests are not sent on every keystroke, because some users type fast and it will send many requests at once to the server (one request per letter).

In my opinion it should stay like this.

**Comment by kmbn** [comment]
The current implementation only sends a request if the user stops typing, though. Unless the user pauses for a second between keystrokes, they'll never see any suggestions at all. I think it could be less aggressive when it comes to limiting requests.

I'm assuming that autocomplete is enabled for the tags field to help users avoid creating misspelled tags or alternate versions of the same tag. But with the current implementation, if `technology` is the tag that already exists, a user can type and submit `technical` or `technologies` or `techology` without ever seeing a suggestion for `technology`. If they type `tech` and don't pause before submitting, they also won't see a suggestion for `technology`.

**Comment by klikstermkd** [comment]
It's clear to me what you mean now. If a user types fast `tech` and hits the Return key the suggestions will never show up.

The autocomplete module receives an [`interval`](https://github.com/ckan/ckan/blob/master/ckan/public/base/javascript/modules/autocomplete.js#L27) option which is used to set the interval between requests. The default is 1000ms, which is why is so slow to show up suggestions. 

This can be solved by lowering down the interval. I tested it with 100ms and it works better.
