### ISSUE TITLE
Documentation has dead links in API Guide (latest documentation)

### ISSUE THREAD

**Issue by dgmouris** [ckan/ckan#3707]
This was seen on the latest version of the documentation.

Under API Guide and "Get a full JSON representation of a dataset, resource or other object" all links should be 

Under the section mentioned above, 2 of the links display an error:
http://demo.ckan.org/api/3/action/package_show?id=adur_district_spending
http://demo.ckan.org/api/3/action/group_show?id=data-explorer

As I am new to the project, I'm unsure what links would be used but I'm more than happy to help!

**Comment by Aaron-M** [comment]
Similar to #3672

**Comment by TkTech** [comment]
These are just examples of how the URL is formed, the demo site is frequently wiped. Maybe we should disable auto-hotlinking on them?

**Comment by amercader** [comment]
I've recreated the examples datasets and the links now work again.

For reference, these datasets are created using the following script:

https://github.com/ckan/ckan-demo-data

```
python load.py -b https://demo.ckan.org -a API_KEY
```

This should be of course automated as part of the demo redeploy

**Comment by dgmouris** [comment]
Thanks! @amercader
