### ISSUE TITLE
Changing the Organization of a harvested dataset

### ISSUE THREAD

**Issue by Rjones8901** [ckan/ckan#3709]
### CKAN Version if known (or site URL)
2.6.2

### Please describe the expected behaviour
I would expect that I could set different organizations for different datasets harvested from the same source. The process would be to harvest the datasource with no organization selected then change the organization for each dataset harvested. When it re-harvest it would harvest to the correct organization.

### Please describe the actual behaviour
If you change the organization and then reharvest, the dataset is changed to the original organization that is defined in the harvest source.

### What steps can be taken to reproduce the issue? 
1. Add a harvest source with an organization (required because it will not let you select "no organization")
2. Change the organization of a dataset
3. Reharvest the source.

**Comment by smotornyuk** [comment]
@Rjones8901  No, it's not the way harvester supposed to work. It just pulls datasets and save all information locally. What about cases, when owner organization was changed at remote instance and you change it locally as well? 
Datasets are historical data objects and activity stream allows us to see, how data was changed during the time. Manual changes obscures data history. 
CKANHarvester was designed to synchronize data between portals, so manual data changes are undesirable. If you are planning to pull initial data and then change it - you should write your own harvester

**Comment by Rjones8901** [comment]
It changes the data anyways because it ignores any organization set downstream applies the organization that is selected when editing the harvesting source. We tried to set the organization in an ESRI ODP to something that was not in CKAN and it adopted the organization that was forced on it when you have to select an organization in CKAN.

**Comment by Rjones8901** [comment]
I am not talking about Organization wrt to metadata. I am saying the organizational structure used in CKAN to organize datasets and resources. When you create a harvesting source you have to select an organization that is in CKAN. You can cannot select "no organization" even though its an option. It returns an error. When you try to change them to the correct organizations because not all the harvested data belongs to a single organization and reharvest, it changes them all back to the single organization that was forced selected.

**Comment by smotornyuk** [comment]
Yeah, i see. I'll take a look at setting 'no organization' and add check what can be done in order to preserve owner changes during harvesting
