### ISSUE TITLE
Loading image duplicated 

### ISSUE THREAD

**Issue by pmartignoli** [ckan/ckan#3716]
The load image should not be duplicated

Go to any dataset preview, for example 

https://birmingham.ckan.io/dataset/cycling-sensors/resource/97ea705d-50b4-40e9-bcd0-1c02bbb04e45

Select one of the headings in the preview eg. Road Number, Location. 

The loading sign is duplicated.

**Comment by Aaron-M** [comment]
Is that not correct behaviour - when you click on a field heading, that sorts the data by that field, and hence the 'loading' indicator displays as the sorted view of the data is displayed?
