### ISSUE TITLE
Fanstatic path in debug mode is different with the path in prod mode

### ISSUE THREAD

**Issue by shilu911** [ckan/ckan#3717]
### CKAN Version if known (or site URL)
2.6

My fanstatic folder's structure is:
- fanstatic
    - css
        - jquery-ui.css
        - images
            - icon.png
In the jquery-ui.css file, one of the classes has ' background-image: url("images/icon.png")'
### Please describe the expected behaviour
The background image should show up in both debug mode and prod mode

### Please describe the actual behaviour
It does not show up in prod mode since the url of fanstatic in prod mode is different with the url in debug mode.

**Comment by klikstermkd** [comment]
Images should be put in `public` folder. `fanstatic` folder is only for CSS and JS files.

**Comment by wardi** [comment]
Yes, as mentioned in http://docs.ckan.org/en/ckan-2.6.2/theming/fanstatic.html
