### ISSUE TITLE
Not adequate error message when creating an organization through API

### ISSUE THREAD

**Issue by klikstermkd** [ckan/ckan#3728]
### CKAN Version if known (or site URL)
Any.

### Please describe the expected behaviour
When creating an organization through API, if an organization already exists for that `name`, the error message should be "Organization name already exists in database".

### Please describe the actual behaviour
When creating an organization through API, if an organization already exists for that `name`, the error message is "Group name already exists in database".

**Comment by tino097** [comment]
Changing the message will have impact on translations, so maybe it is good to keep it as it is
