### ISSUE TITLE
Autoform .checkbox

### ISSUE THREAD

**Issue by ggcatu** [ckan/ckan#3732]
### CKAN Version if known (or site URL)

Present in latest version and also in 2.6.2
https://github.com/ckan/ckan/blob/master/ckan/templates/macros/autoform.html#L28

### Please describe the expected behaviour
As for what I understand from documentation of autoform

> form_info       - A list of dicts describing the form field to build.
> data            - The form data object

In the source code we have, 
` {% set value = data.get(name) %} `

And a special case for form.select()
` {% call form.select(name, id=id, label=label, options=item.options, selected=value, error=error) %}`

But according to documentation we should be setting the selected parameter, in the form_info:
not in data,

> selected    - The value of the selected <option>.

So kinda weird...

As for checkbox, the checked parameter is never sent,

`{% call form[control](name, id=id, label=label, placeholder=placeholder, value=value, error=error, classes=classes) %}`

**Comment by ggcatu** [comment]
input_required() not defined in form.html

**Comment by amercader** [comment]
Hi @ggcatu. We discussed this on the [dev meeting](https://hack.allmende.io/ckan-meeting). The autoform module is not really used apart from some minor templates and we will deprecate it an remove it on 2.8. We don't think it's worth the extra complexity as opposed to plain form controls in templates.

**Comment by ggcatu** [comment]
Oh, that's good, then I guess there's no point into keep digging into it
