### ISSUE TITLE
Install from source lacks continuity between 2.b and 2.c

### ISSUE THREAD

**Issue by brylie** [ckan/ckan#3736]
When following the [installation from source instructions](http://docs.ckan.org/en/ckan-2.7.0/maintaining/installing/install-from-source.html), step 2.b says to install the CKAN package from Github and then step 2.c says to install requirements.txt.

However, running the `pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.6.2#egg=ckan'` command simply downloads a `src/` folder within the active directory. It should be noted to run the command from within the `/usr/lib/ckan/default/` folder, so that the subsequent command (`pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt`) would work.

**Comment by wardi** [comment]
@brylie do you mind submitting a PR to the docs with the change you're requesting? (it would have to be against master not 2.6 of course)

**Comment by brylie** [comment]
@wardi PR #3741 is ready for review.
