### ISSUE TITLE
Trouble setting up development environment from cloned repository

### ISSUE THREAD

**Issue by brylie** [ckan/ckan#3737]
When trying to set up a development environment from the latest version, I am getting the following error in console:

```
ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.7. Supported versions are [2.3]
```

The error is visible after running `paster serve /etc/ckan/default/development.ini`

How can I downgrade the 2.7 SOLR schema?

**Comment by tino097** [comment]
hey @brylie , you should copy the schema.xml as it is in documentation 

`sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak
sudo ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml`

**Comment by brylie** [comment]
Hm, I have tried that a few times. I must have messed something else up. I have previously installed the 'production' version, and am now attempting to install a version for development.

**Comment by brylie** [comment]
Also, from my interpretation, it is looking for a **2.3** schema. How can I make sure it allows the **2.7** schema? Should I be on a different branch than `master`?

**Comment by brylie** [comment]
Basically, I need to set up a local development environment from which I can make a PR against ckan/ckan. For now, I have forked the repository, and cloned from my fork. At that point, I started seeing the above error.

**Comment by tino097** [comment]
Are you sure that you have latest version of CKAN, as schema 2.3 is used prior CKAN 2.7

**Comment by brylie** [comment]
I had cloned directly from Github, and was on the `master` branch.

**Comment by brylie** [comment]
Now, I am following the instructions from *installing from source*, but don't understand how I can make a PR if I follow this process:

> If you’re installing CKAN for development, you may want to install the latest development version (the most recent commit on the master branch of the CKAN git repository). In that case, run this command instead:
>
> `pip install -e 'git+https://github.com/ckan/ckan.git#egg=ckan'`

**Comment by tino097** [comment]
yes, that could be misguiding a little bit

and if you have created fork, you should be on latest CKAN version
try with
```python
python setup.py develop
`
while in ckan directory

**Comment by brylie** [comment]
> and if you have created fork, you should be on latest CKAN version
> try with
>    python setup.py develop
> while in ckan directory

At what step in the installation from source document should I run `python setup.py develop`? E.g. 2.d?

**Comment by brylie** [comment]
Here is the output of `python setup.py develop`, which looks successful:

```
python setup.py develop
/home/brylie/anaconda3/envs/CKAN/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '2.8.0a' to '2.8.0a0'
  normalized_version,
running develop
running egg_info
creating ckan.egg-info
writing ckan.egg-info/PKG-INFO
writing namespace_packages to ckan.egg-info/namespace_packages.txt
writing top-level names to ckan.egg-info/top_level.txt
writing dependency_links to ckan.egg-info/dependency_links.txt
writing entry points to ckan.egg-info/entry_points.txt
writing manifest file 'ckan.egg-info/SOURCES.txt'
reading manifest file 'ckan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '.git'
warning: no files found matching 'CHANGELOG.txt'
warning: no files found matching '*' under directory 'ckan_deb'
writing manifest file 'ckan.egg-info/SOURCES.txt'
running build_ext
Creating /home/brylie/anaconda3/envs/CKAN/lib/python2.7/site-packages/ckan.egg-link (link to .)
Adding ckan 2.8.0a0 to easy-install.pth file
Installing ckan-admin script to /home/brylie/anaconda3/envs/CKAN/bin

Installed /home/brylie/ckan/lib/default/src/ckan
Processing dependencies for ckan==2.8.0a0
Finished processing dependencies for ckan==2.8.0a0
```

**Comment by tino097** [comment]
This looks good, can you double check that coping of SOLR schema from ckan to solr directory is actually happening? 
And which version of SOLR are you using ?

**Comment by brylie** [comment]
Here is a screenshot of my Solr info page

![screenshot_20170801_115208](https://user-images.githubusercontent.com/17307/28817106-db44b1c4-76af-11e7-8013-5b397ab780ca.png)

**Comment by brylie** [comment]
I think we can close this issue, since I somehow managed to get things working. However, these type of problems may be common for new developers. I am not sure specifically how to make it easier to set up a development environment, but *ideally* it would be something like running a single command.

**Comment by brylie** [comment]
I have started working on issue #3592. There are a few questions at the end of the discussion, that I can't quite figure out.
