### ISSUE TITLE
Support setuptools 36.x

### ISSUE THREAD

**Issue by brylie** [ckan/ckan#3738]
### CKAN Version if known (or site URL)
latest

### Please describe the expected behaviour
CKAN dependencies would be kept up to date.

The latest version of setuptools is 36.x

### Please describe the actual behaviour
The instructions for *installing from scratch* require a specific version of setuptools (20.4) that is rather old.

**Comment by smotornyuk** [comment]
We periodically have bugs related to setuptools package([latest one](https://github.com/ckan/ckan/issues/3513)) so we just cannot afford using the latest version. But your suggestion has sense, so i made some tests and updated setuptools to v36.1 in #3742
