### ISSUE TITLE
API Catalog feature

### ISSUE THREAD

**Issue by brylie** [ckan/ckan#3739]
# Summary
Many organizations use CKAN as a **data portal and catalog**. However, there is an emerging need to catalog data sources from remote **APIs** (e.g. REST, etc.). 

It would prove beneficial for CKAN to support some sort of API catalog.

# Background
There are national and EU-wide initiatives to standardize data infrastructure, and CKAN is well positioned. However, CKAN mainly lacks the API cataloging capabilities increasingly needed by governments and industry.

# Idea
An API Catalog would be a top-level feature, on the level of Organizations, Groups, Data Sets, etc.. An API manager could add information about the API, such as the endpoints and documentation in a standard format (such as OpenAPI Specification).

## Extension across CKAN features
Additional features could be built around the APIs, such as comments/feedback, branding, etc. Those features could be related to APIs, data sources, groups, organizations, etc.

*Full disclosure*: I work on an open-source project, called [APInf](https://github.com/apinf/platform), where we have built an API catalogue and community platform.

**Comment by TkTech** [comment]
Is there a missing feature preventing you from doing this as an extension?

**Comment by tino097** [comment]
@brylie this should be posted in [ideas and roadmaps](https://github.com/ckan/ideas-and-roadmap ) project for further discussion

**Comment by TkTech** [comment]
Never thought I'd say this but I miss JIRA. Can't move issues on github :(

**Comment by brylie** [comment]
@TkTech we have used a project called [Github issue mover](https://github-issue-mover.appspot.com/) in the past.
