### ISSUE TITLE
Exposed Server Local Files - Url Validator Needed

### ISSUE THREAD

**Issue by HilariousGil** [ckan/ckan#3740]
### CKAN Version if known (or site URL)
Latest

### Please describe the expected behaviour
Resources should not be able to access files from the server where the ckan is hosted as a valid url.

### Please describe the actual behaviour
You can add a URL like "file:///etc/passwd" and it will be a valid one. Pushed to the Datastore and Visible on the website.

### What steps can be taken to reproduce the issue? 
Click here -> https://demo.ckan.org/dataset/civity-finding-bugs-in-ckan/resource/fafce625-deb6-486b-b8b7-0fe4b79ef957

or 

Create a new resource with a path to a local file on your server. example: "file:///etc/passwd"

Urls starting with "file:///" should not be allowed as valid urls.

**Comment by wardi** [comment]
Thanks @HilariousGil.

Next time please submit this sort of issue to security@ckan.org so we can prepare and release a fix before we discuss in public. I think the best place for a fix is in the datapusher repo. Sites can override the dataset schema so preventing bad urls there isn't as safe.

**Comment by HilariousGil** [comment]
My bad. I wasn't aware of that. 
Should the issue be deleted then?
I think that approach is better than my suggestion yes.
Thanks!

**Comment by wardi** [comment]
fixed by https://github.com/ckan/datapusher/pull/140
