### ISSUE TITLE
[Bug] Silently ignores corrupt downloads.

### ISSUE THREAD

**Issue by dyleighba** [ckan/ckan#3743]
### CKAN Version if known (or site URL)
v1.22.3

### Please describe the expected behaviour
1. CKAN attempts to download mod.
2. Download is redirected but still outputs data which in this case is HTML.
3. CKAN saves the data as a ZIP in downloads.
4. CKAN checks the hash and attempts to re-download and on subsequent attempts errors.

### Please describe the actual behaviour
1. CKAN attempts to download mod.
2. Download is redirected but still outputs data which in this case is HTML.
3. CKAN saves the data as a ZIP in downloads.
4. CKAN attempts to install mod but errors due to file being 'corrupt'.

### What steps can be taken to reproduce the issue? 
1. Setup a HTTP server that always returns HTML.
2. Get CKAN to download a mod via that server.
Note: The cause of this in my setup is a proxy blocking ZIP files and returning a rejection page.

**Comment by TkTech** [comment]
Wrong CKAN.
