### ISSUE TITLE
2.7.0 DataProxy returned an error 

### ISSUE THREAD

**Issue by ggcatu** [ckan/ckan#3744]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
Data explorer should work with uploaded and external urls

### Please describe the actual behaviour
When dataset is uploaded, would receive message:

Could not load view: DataProxy returned an error (Data transformation failed. InvalidURL: Invalid request URL: http://localhost:500/dataset/d49e0da6-b9d2-4d85-b4ff-1325f38e5b65/resource/0d6fdbb6-892d-433d-a2f0-c3d1f6bbc934/download/sacramentocrimejanuary2006-1.csv)

If dataset is from external URL it works

### What steps can be taken to reproduce the issue? 
Install 2.7.0  (Not on production)
Create admin user
Create Organization
Upload dataset 
Try to preview it in Data Explorer

ckan.plugins = stats text_view image_view recline_view resource_proxy

If you click on the link, yes , you can actually download the file

**Comment by wardi** [comment]
Data proxy is an external service that can only access public URLs. You can either upload your csv (so data proxy is not necessary) or try hosting the file on a public site instead.

**Comment by ggcatu** [comment]
@wardi I'm telling you this behavior is actually happeing while uploading the csv to ckan.

**Comment by wardi** [comment]
If you have datapusher enabled the upload should be creating a datastore table for your data so you don't need data proxy. It is strange that recline is trying to use data proxy on a localhost url, though. Are you interested in investigating the cause?

**Comment by ggcatu** [comment]
The problem occurs if you have datapusher disabled and upload the dataset.

Shouldn't it just treat it as if it was an external resource, and show it in the Data Explorer ?
External resources can be previewed without having datapusher and datastore enabled

**Comment by wardi** [comment]
sure, but how could DataProxy access a URL like http://localhost:500/... when it's running on a different machine? If you set your SITE_URL to a valid location it should work (but you'll need to re-upload your files to update their URLs IIRC)

**Comment by ggcatu** [comment]
In my opinion that is currently a problem, sharing config between components.

For instance, DataPusher shouldn't be using the ckan.site_url but instead have it's own URL setting.
I was running a setup with 
- ckan container
- datapusher container

And had everything config, to localhost. So ckan container was working good, but datapusher wouldn't, since localhost:500 isn't valid for him.
Had to solve it using my public IP.


As for DataProxy I haven't checked it, but isn't it a ckan plugin? He should be running on the same server as ckan.
You should still be able to preview the files you uploaded without needing the help of datapusher / datastore.

**Comment by wardi** [comment]
No, as I said in https://github.com/ckan/ckan/issues/3744#issuecomment-319980364 data proxy is an external service, only used by the recline views IIUC.

You need to set SITE_URL to the external address for the ckan site. It's necessary for generating correct absolute URLs (e.g. when sending emails from a background job) and the rest of CKAN relies on it being correct.

If you either enable datapusher and datastore, or set a correct SITE_URL your views should work. We can't use this issue tracker to debug your specific docker or networking configuration, and setting multiple SITE_URLs is something that could be discussed in the ideas repository if you feel it's really necessary.

**Comment by jorarmarfin** [comment]
Error: Process completed but unable to post to result_url
please help

**Comment by kumarvivek1752** [comment]
I got the same error 
Could not load view: DataProxy returned an error (Data transformation failed. HTTPError: HTTP Error 403: Forbidden)
in my private dataset preview public dataset preview looks fine
