### ISSUE TITLE
new horizons mod in ckan not working

### ISSUE THREAD

**Issue by ilikegumballs** [ckan/ckan#3745]
CKAN Version 1.22.3

i downloaded the mod and selected all the other mods that is recommended for it and when i launched KSP the only planets that were there were the stock planets in different a arrangement and i have no idea what to do and the other times i downloaded the mod nothing happened to the system

**Comment by TkTech** [comment]
Wrong CKAN.

**Comment by ilikegumballs** [comment]
which version?

**Comment by TkTech** [comment]
The project you are commenting on has absolutely nothing to do with KSP.
