### ISSUE TITLE
Datapusher - paster set-permission - EOF

### ISSUE THREAD

**Issue by ggcatu** [ckan/ckan#3747]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
paster set-permission to correctly execute

### Please describe the actual behaviour
paster --plugin=ckan datastore set-permissions -c /etc/ckan/default/development.ini
Is not giving any error on the ckan side, but on postgresql is received this:

db       | LOG:  unexpected EOF on client connection with an open transaction

After this, operation is aborted and updates are not made to the table, nor _table_metadata is created.

If the output from set permission is copied an pasted into a file, and executed it works, so might be something in the connection and not the commands.

### What steps can be taken to reproduce the issue? 
http://docs.ckan.org/en/latest/maintaining/datastore.html#set-permissions

**Comment by smotornyuk** [comment]
@ggcatu , i can't reproduce suche errors. Do you redirect output to postgresql using pipe? i.e `paster datastore set-permissions -c development.ini |sudo -u postgres psql --set ON_ERROR_STOP=1` . or you copy output and paste it directly using psql client?

**Comment by ggcatu** [comment]
I was just running this command alone, not redirecting

paster --plugin=ckan datastore set-permissions -c /etc/ckan/default/development.ini

Im using paster to paster to db init, create users etc, and everything works good

**Comment by smotornyuk** [comment]
Yeah, this is just how datastore works) You need to run `paster datastore set-permissions -c development.ini | sudo -u postgres psql --set ON_ERROR_STOP=1`. paster command only generates SQL code that need to be executed under db root account (this is why paster can't do it - we do not want to expose db root credentials)

**Comment by ggcatu** [comment]
How do you think this process should be done in a Docker setup, where the ckan container doesn't have postgres installed , and postgres is in another container?

I ended up doing it like: 

> If you can’t use the psql command in this way, you can simply copy and paste the output of:
> 
> sudo ckan datastore set-permissions
> into a PostgreSQL superuser console.

Wouldn't it be better to just accept a postgres url, connect and execute?

>  postgresql://ckan:ckan@db:5432/ckan

**Comment by smotornyuk** [comment]
hm, you can install postgresql client on host image and connect to another one, but i agree, that simplest solution would be to copy paster output -> connect to image with postgresql -> connect to db -> insert copied commands.

as for using postgres url - if you are meaning that this url can be used in order to connect and perform necessary operations from paster command - no. You'll probably run into access problem and messages that your user(ckan) has not sufficient permission for managing access on schema `public`

**Comment by ggcatu** [comment]
Got it. Guess this can be closed then.
