### ISSUE TITLE
ckan.root_path doubled in new dataset form redirect

### ISSUE THREAD

**Issue by PointyShinyBurning** [ckan/ckan#3750]
CKAN Version 2.7

I have `ckan.root_path = /ckan/{{LANG}}` in my production.ini and `rewrite ^/ckan/?(.*)$ /$1 break;` in my nginx configuration to serve ckan from a subdirectory.

On 2.6 this worked fine, but on 2.7 clicking ![image](https://user-images.githubusercontent.com/5345844/29177102-ab2d4bd0-7de5-11e7-8667-39d867631743.png) on the new dataset form at `ckan/dataset/new` leads to `ckan/ckan/dataset/new_resource/test_dataset`, giving a 404 error, rather than `ckan/dataset/new_resource/test_dataset` i.e. it's adding the ckan.root_path to the dataset url twice. If I've set a language I get that twice as well e.g. `ckan/en/ckan/en/dataset/new_resource/test_dataset`

Everything else is working; visiting the right url manually allows you to add resources to the dataset and then ![image](https://user-images.githubusercontent.com/5345844/29177320-517d488c-7de6-11e7-9d40-2710b402ef35.png) it as normal.

**Comment by tino097** [comment]
#3749 would fix this issues
