### ISSUE TITLE
Uploading large files never frees tmp-file disk space (disk space leak)

### ISSUE THREAD

**Issue by curtisyallop** [ckan/ckan#3752]
### CKAN Version if known (or site URL)
2.6.0 and 2.7.0 (both versions tested)

### Please describe the expected behaviour
After uploading 1GB file repeatedly (and removing the old one each time), ckan should keep running just fine - not die due to running out of disk space. Restarting the web server should not free up all the missing space and make it work again.

### Please describe the actual behaviour
Uploading a 1GB file multiple times as described above makes ckan die after about 5-6 uploads. As I watch free disk space ("watch -n .2 df -h", Avail column) as the upload executes, I can see the free space dropping. Ignore the first upload. It often drops 2GB each 1GB upload (it drops 4-5GB in total but recovers a couple GB). But sometimes it stays the same for 1-2 uploads. But after about 4-6 uploads, ckan dies (I have 6GB free space in my virtual machine and both /tmp and datastore are on the root filesystem). If I restart ckan (either paster-serve or apache), the disk space immediately is all freed up.

I made a possible fix which prevents this leak. In /usr/lib/ckan/default/src/ckan/ckan/lib/uploader.py, `ResourceUpload.upload`, after "os.rename" and before "return", I do "self.upload_file.close()". In /usr/lib/ckan/default/lib/python2.7/site-packages/paste/cascade.py (pylons), `Cascade.__call__`, I altered the method to perform "f.close()" if file "f" was created (it is created on line "f = tempfile.TemporaryFile()"), just before returning from the method. I am trying to figure out if there is any better solution to preventing this disk-space-leak problem.

Note: "strace -f" on paster serve revealed 3 files were created "/tmp/tmpT_rCJn", "/tmp/tmpET4MoY", "/mnt/datastore/resources/e92/813/3a-8f09-4f2d-8900-e89d0de1ce7c~".

lsof -c python | grep /tmp
python  12815 vagrant    9u   REG     253,0 1073743123 26707027 /tmp/tmp0V5iAe (deleted)
python  12815 vagrant   10u   REG     253,0 1073743123 28579426 /tmp/tmp9DcPv0 (deleted)
Why are these files being held open?

### What steps can be taken to reproduce the issue? 
In ckan ini, set "ckan.max_resource_size = 1100". Restart web server. Create a dataset. Add a resource. Upload a 1GB file. Update the resource. Click "Remove". Upload a 1GB file again. Do this 6 times. The disk space from "df -h" (/tmp file system, "Avail" column) should not keep dropping a few GB each upload until ckan dies.

(I create the 1GB file using "dd if=/dev/zero of=test1g count=1 bs=1G")

(if I am using nginx, I also set "client_max_body_size 1100m;")

**Comment by smotornyuk** [comment]
thanks, @curtisyallop . What you are doing with ResourceUpload is ok, but as for changing `paste` source code - i propose additional middleware that will clean temporary files insted. I'm going to create PR with reference to this issue, so you can make patch or just take a idea and adapt it to you instance.

**Comment by curtisyallop** [comment]
This webob fix does not seem to fix our situation. On ckan 2.6.0, when I apply CloseWSGIInputMiddleware, it is never a FakeCGIBody so it does nothing. When I print it at that point it is a socket or a file descriptor. I think the unfreed one is the tempfile.TemporaryFile created in cascade.py.

Thanks for that ckan fix. That part works.

**Comment by curtisyallop** [comment]
Update: Your webob fix actually does work for me. I had to alter it slightly, perhaps due to the different version of ckan. I updated "if upload:" to "if upload is not None:" because otherwise it evaluated to false and skipped the "upload.fp.close()". When I printed "upload", it displayed "FieldStorage('upload', 'test60M')". It had a value but then evaluated to false.

**Comment by curtisyallop** [comment]
Thanks!
