### ISSUE TITLE
Missing upload GUI

### ISSUE THREAD

**Issue by nesnera** [ckan/ckan#3753]
### CKAN Version if known (or site URL)
ckan_version | "2.7.0"
-- | --
site_url | "http://< private ;) >.otevrenamesta.cz"
site_description | ""
site_title | "Katalog městských dat"
error_emails_to |  
locale_default | "cs_CZ"
extensions |  
0 | "stats"
1 | "text_view"
2 | "image_view"
3 | "recline_view"
4 | "hierarchy_display"
5 | "hierarchy_form"

### Please describe the expected behaviour
Have GUI for upload like at [your demo](https://demo.ckan.org). Have a look at attached file upload_GUI_OK.png
![upload_gui_ok](https://user-images.githubusercontent.com/1737463/29266591-b38f2ac0-80e5-11e7-8801-5e83ee84cc3a.png)

### Please describe the actual behaviour
GUI for upload is invisible as well as selected file (Pointer is placed over empty space). Have a look at upload_GUI_wrong.png
![upload_gui_wrong](https://user-images.githubusercontent.com/1737463/29266618-d1793508-80e5-11e7-9db4-151083448e16.png)

### What steps can be taken to reproduce the issue? 
Just install

**Comment by amercader** [comment]
Please check the documentation on how to set up [file uploads](http://docs.ckan.org/en/ckan-2.7.0/maintaining/filestore.html#setup-file-uploads). You need to specify a `ckan.storage_path` on your ini file.

As for the incorrect rendering, perhaps one of the extensions is interfering with the default fields?

Closing this for now. Feel free to reopen if you think this is an actual issue with CKAN core.

**Comment by nesnera** [comment]
Re: Amercader - thank for response.
The problem seems be solved by installing redis.. :-)

**Comment by nesnera** [comment]
Upps. Problem persist and I think it's at client side but it's very strange.
Steps to reproduce:

1. use default (Czech) language and create new dataset. Uploader is OK.
2. switch to Englis (correct) and back - "Error 404 Not Found" and wrong URL http://ckan.otevrenamesta.cz/en/cs_CZ/dataset/new_resource/
3. replace URL to http://ckan.otevrenamesta.cz (Czech language again)
4. now if you modify existing dataset and try to append new data resource you can see what I described in my first post.
5. and finally, if you create new dataset and after that modify existing resource uploader will be OK again :D

Tested with:
- Mozilla Firefox 55.0
- Chromium 59.0.3071.104 Fedora Project

**Comment by ggcatu** [comment]
Yes, this strange bug is happening also to me.
