### ISSUE TITLE
Bootstrap3 UI issues

### ISSUE THREAD

**Issue by smotornyuk** [ckan/ckan#3754]
Chromium v59:
#3620
This is how looks dataset search page when filters are enabled
![screenshot from 2017-07-27 16-18-29](https://user-images.githubusercontent.com/11091199/28672108-74c628cc-72e7-11e7-9b18-27b19073c46d.png)
And this is organization list(I have one organization):
![screenshot from 2017-07-27 16-19-45](https://user-images.githubusercontent.com/11091199/28672111-77bcf2fe-72e7-11e7-951a-562995e20683.png)

**Comment by amercader** [comment]
@klikstermkd can you have a look at this when you have a moment?

**Comment by klikstermkd** [comment]
@amercader Yes I will look into it.
