### ISSUE TITLE
Language switcher doesn't work

### ISSUE THREAD

**Issue by nesnera** [ckan/ckan#3757]
### CKAN Version if known (or site URL)
https://ckan.otevrenamesta.cz/api/util/status

### Please describe the expected behaviour
Be able to switch between languages.

### Please describe the actual behaviour
Just try to switch to another language.
But you can do that manually as https://ckan.otevrenamesta.cz/en or ../de, /sk

### What steps can be taken to reproduce the issue? 
Have a look https://ckan.otevrenamesta.cz

**Comment by nesnera** [comment]
related issue? - https://github.com/ckan/ckan/issues/3753

**Comment by ggcatu** [comment]
Yes, language switch is neither working on my instance of ckan, 2.7.0

**Comment by ggcatu** [comment]
Actually I made it work, by having my ckan url not local, I mean, using my public IP.

The problem is that it just keep appending names to the url instad of substituting the old one.
So fot example if I change my language to italian, it works, but if later i change it to nederlands, i get 
myurl:5000/it/nd
and if i then change it to spanish i get 
http://url:5000/it/nl/es/dashboard

**Comment by wardi** [comment]
Looks like your site_url should have `https://` not `http://`. The language switcher works on http://ckan.otevrenamesta.cz

**Comment by ggcatu** [comment]
@wardi  try what i said, its not working.

Go to http://ckan.otevrenamesta.cz/group/br_indikatory
Change the language 2 times.

**Comment by wardi** [comment]
that's different than the initial bug report. do you have a root_path setting?

**Comment by tino097** [comment]
possible relation to #3750

**Comment by nesnera** [comment]
@tino097 Good point. I have reverse proxy (nginx). But my redirection is very simple `proxy_redirect      http://[2a01:430:17:1::ffff:27] http://ckan.otevrenamesta.cz;`
1. I believe the protocol (http|https) should be isolated
2. I've tried direct access (by IP address and changing ckan.site_url to this IP). Switcher still return wrong URLs like [http://77.93.223.72 **/cs_CZ/en/** group/br_indikatory](http://77.93.223.72/cs_CZ/en/group/br_indikatory). Issue in URL parser?

@wardi 
- I fully agree with @ggcatu 
- Do I need root_path? This parameter is missing in [the ini template](https://github.com/ckan/ckan/blob/ee4621b1823018e96e73a99bdf3fc2d114dd8d5c/ckan/config/deployment.ini_tmpl)

**Comment by acorbi** [comment]
HI @nesnera, it seems that the issue is now fixed on https://ckan.otevrenamesta.cz/. Can you tell me how you managed to solve it? I am having the same issues you describe and could not find a solution at this point.
