### ISSUE TITLE
Unclear docs and/or bug in docker container

### ISSUE THREAD

**Issue by markburgess** [ckan/ckan#3759]
### CKAN Version if known (or site URL)

latest from docker ckan/ckan

### Please describe the expected behaviour

expect netstat to show port 80 service running. 

### Please describe the actual behaviour

No port 80 service running, though all docker containers running

### What steps can be taken to reproduce the issue? 

Follow the precise destructions from the website:

  466  docker run -d --name db ckan/postgresql
  467  docker run -d --name solr ckan/solr
  468  docker run -d -p 80:80 --link db:db --link solr:solr ckan/ckan

results in

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                          NAMES
5a9de3bc49d4        ckan/ckan           "/ckan-entrypoint...."   22 minutes ago      Up 22 minutes       0.0.0.0:80->80/tcp, 5000/tcp   unruffled_minsky
eb26f0764ade        ckan/solr           "docker-entrypoint..."   28 minutes ago      Up 28 minutes       8983/tcp                       solr
46053e787e21        ckan/postgresql     "docker-entrypoint..."   28 minutes ago      Up 28 minutes       5432/tcp                       db

But no service is running on port 80

Active Internet connections
Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)    
tcp4       0      0  192.168.1.118.49825    162.125.32.135.443     ESTABLISHED
tcp4       0      0  192.168.1.118.49820    84.208.20.52.443       ESTABLISHED
tcp4       0      0  192.168.1.118.49819    54.192.98.220.443      ESTABLISHED
tcp4       0      0  192.168.1.118.49818    31.13.72.12.443        ESTABLISHED
tcp4       0      0  192.168.1.118.49817    31.13.72.36.443        ESTABLISHED
tcp4       0      0  192.168.1.118.49816    54.230.99.236.443      CLOSE_WAIT 
tcp4       0      0  192.168.1.118.49809    192.168.1.49.445       ESTABLISHED
tcp4       0      0  192.168.1.118.49808    192.30.253.124.443     ESTABLISHED
tcp4       0      0  192.168.1.118.49661    162.125.34.137.443     LAST_ACK   
tcp4      31      0  192.168.1.118.49508    162.125.65.3.443       CLOSE_WAIT 
tcp4       0      0  192.168.1.118.49493    162.125.18.133.443     ESTABLISHED
tcp4       0      0  192.168.1.118.49424    50.17.63.78.443        CLOSE_WAIT 
tcp4       0      0  192.168.1.118.49344    162.125.18.133.443     ESTABLISHED
tcp4       0      0  192.168.1.118.62809    173.194.221.16.993     ESTABLISHED
tcp4       0      0  192.168.1.118.62808    173.194.221.16.993     ESTABLISHED
tcp4       0      0  192.168.1.118.62807    40.101.124.34.993      ESTABLISHED
tcp4       0      0  192.168.1.118.62762    54.72.231.185.443      ESTABLISHED
tcp4       0      0  192.168.1.118.62758    192.168.1.179.8009     ESTABLISHED
tcp4       0      0  192.168.1.118.62753    17.188.133.61.5223     ESTABLISHED
tcp4       0      0  192.168.1.118.62750    17.252.108.20.5223     ESTABLISHED
tcp4       0      0  192.168.1.118.54769    162.125.65.3.443       ESTABLISHED

And no webserver running

**Comment by wardi** [comment]
@mattfullerton any idea about this?

**Comment by markburgess** [comment]
Searching around, I found a compose file, (these docker compose files seem fragile), which works

# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
ckan:
  container_name: ckan
  # Note, if you are working on CKAN core, change this to
  # build ../../
  image: ckan/ckan:latest
  links:
      - db
      - solr
      - redis
  ports:
      - "80:5000"
  environment:
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis

db:
  container_name: db
  image: ckan/postgresql
  
solr:
  container_name: solr
  image: ckan/solr:latest
    
redis:
  container_name: redis
  image: redis:latest


It is not clear to me why the other attempts failed and this one succeeded.

**Comment by mattfullerton** [comment]
Can you paste the errors?

There is work going on to improve things: https://github.com/ckan/ckan/pull/3692

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
