### ISSUE TITLE
Found bug in docker ckan installation - CKAN_SOLR_URL env variable read problem

### ISSUE THREAD

**Issue by terchris** [ckan/ckan#3764]
### CKAN Version if known (or site URL)
https://hub.docker.com/r/ckan/ckan/

### Please describe the expected behaviour
expect ckan to start :)

### Please describe the actual behaviour
Installing ckan/ckan from https://hub.docker.com/r/ckan/ckan/

Getting this error:
"
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
InvalidURL: Invalid URL u'http://:/solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json': No host supplied
2017-08-17 20:33:10,545 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
"

### What steps can be taken to reproduce the issue? 

The error message comes from __init__.py
https://github.com/ckan/ckan/blob/a5408647c18bcc3a6317a8c83cfb37c72068e90c/ckan/lib/search/__init__.py
after calling the is_available() function in the common.py file
https://github.com/ckan/ckan/blob/9b5bf5d3accc147c90348f210a261cace00f8199/ckan/lib/search/common.py

In the common.py we see that DEFAULT_SOLR_URL = 'http://127.0.0.1:8983/solr' This is clearly not used. 

the init(cls, url, user=None, password=None) method tests whether url is None so it has a value. 
The value seems to me to be "" or an empty string (This is the first time I read python code so forgive my ignorance)

I would think that the get(cls) method would catch the error and print the error message 
raise SearchIndexError('SOLR URL is blank') 

But it does not. 

I have been trying to figure out where the empty solr_url is set in order to set it correctly.

Reading the documentation I see that the configuration files are named development.ini or production.ini
http://docs.ckan.org/en/latest/maintaining/configuration.html

But in the docker image (ckan/ckan) the only file in the /etc/ckan/default/ is ckan.ini

Why is the file named something else than is stated in the documentation ?

Copying the ckan.ini to development.ini or production.ini does not help.

Setting solr_url = http://www.sol.no:32774/solr in all files. But the error is still the same. 

Invalid URL u'http://:/solr/ckan/select/?q=%2A%3A%2A&rows=1&wt=json': No host supplied

Looking at the environment variables that is used by ckan (CONFIG_FROM_ENV_VAR) I see that CKAN_SOLR_URL is not defined in the docker image.

My solr is running at http://localhost:32782/solr/#/
When setting environment variable CKAN_SOLR_URL = http://localhost:32782/solr i see that the error message changes.
Now the URL is set. Error message is now:
"
SolrError: Failed to connect to server at 'http://localhost:32782/solr/select/?q=%2A%3A%2A&rows=1&wt=json', are you sure that URL is correct? Checking it in a browser might help: 
"

So this is bug 1 that needs to be fixed. 
1a - In get(cls) in the file ckan/lib/search/__init__.py you must do better testing to see if solr_url has a valid value
1b - When reading environment variables you must test if the variable exist. 
1c - clearly state in the documentation that values in env variables overrides those in config files

Second bug is related to the docker ckan/ckan. 
2 - why is there a ckan.ini file in /etc/ckan/default/ and not a development.ini or production.ini

Third bug is that the URL is not correct
3a - In ckan/ckan/lib/search/common.py the solr_datetime_decoder(d) is going to return some date and time formatted string. Put a sample txt here of what it returns as a documentation comment.
3b - When opening a bworser on http://localhost:32782/solr/select/?q=%2A%3A%2A&rows=1&wt=json i get:
"
HTTP ERROR 404
Problem accessing /solr/select/. Reason:

Not Found
"

**Comment by amercader** [comment]
@deinok is the version build on Docker Hub the one built from the last Dockerfiles you worked on? Does this problem ring a bell?

@terchris there's some work being done on https://github.com/ckan/ckan/pull/3651 and https://github.com/ckan/ckan/pull/3692 Perhaps the problem is fixed there?

**Comment by deinok** [comment]
@amercader The Dockerfile from https://hub.docker.com/r/ckan/ckan/~/dockerfile/ has been updated 8 days ago. And seems like it have been updates.

**Comment by deinok** [comment]
@terchris @amercader Bug 2:
Yep, the .ini it is set to ckan.ini . If @amercader is agree, i can change it to production.ini

**Comment by amercader** [comment]
@deinok yes, of course. Shouldn't this be covered by the Travis tests? which btw started failing a few days ago

**Comment by deinok** [comment]
@amercader  Yep, it have been detected by travis

**Comment by deinok** [comment]
Also, the docker seems failing to build cause this:
```
Compiling /tmp/pip-build-01JDRi/Jinja2/jinja2/asyncsupport.py ...
  File "/tmp/pip-build-01JDRi/Jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax
```

This is hitted when installing dev-requirements.txt

**Comment by deinok** [comment]
Also, i have found some things related to docker that can be done better.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
