### ISSUE TITLE
"Reorder Resource View" button is mising

### ISSUE THREAD

**Issue by JasminaPN** [ckan/ckan#3765]
### ckan 2.7 

Steps to reproduce the issue:
1. Go to Dataset page of the portal
2. Create Dataset (metadata +add resource (data)
3. Click "edit" on the newly created resource
4. Go to "Views" tab from edit/resource
5. There is a button "+New View" and in Ckan 2.6 right next to "+New View"  button was displayed "Reorder Resource Views" button.

Note:
In CKAN 2.7 "Reorder Resource View" is missing

**Comment by klikstermkd** [comment]
I will look into this.

**Comment by JasminaPN** [comment]
@klikstermkd  Konstantin will review this bug.

**Comment by tino097** [comment]
This issues caused by translation to the label
https://github.com/ckan/ckan/blob/dev-v2.7/ckan/public/base/javascript/modules/resource-view-reorder.js#L36

this PR is fixing it #3604

**Comment by tino097** [comment]
the #3604 should be backported to 2.7 too
