### ISSUE TITLE
"Name" of the uploaded resource is not added automatically in CKAN 2.7 

### ISSUE THREAD

**Issue by JasminaPN** [ckan/ckan#3766]
### CKAN 2.7

Steps to reproduce the issue:
1. Go to Dataset page of the portal
2. Create Dataset (metadata) 
3. Click "Next Add Data" button
4. Upload a resource 
5. The "Name" field under the "Upload Resource: filed by default is added automatically
6. In CKAN 2.7 no action was not taken and the name of the resource has to be added manually 

Note please check the attached image to this issue.
![name of the resource](https://user-images.githubusercontent.com/23238850/29478242-3fb9a000-846c-11e7-80b7-006d3b70c8c2.PNG)

**Comment by klikstermkd** [comment]
I will look into this.

**Comment by JasminaPN** [comment]
@klikstermkd  Konstantin will review this bug. Thanks.

**Comment by Engerrs** [comment]
Hi @smotornyuk , @amercader , can you please backport this fix to CKAN 2.6.
