### ISSUE TITLE
Create dataset with custom date

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan#3768]
### CKAN Version if known (or site URL)

1.6

### Please describe the expected behaviour

API package_update should accept custom date

### Please describe the actual behaviour

API package_update ignores creation date. It's impossible to change creation date of dataset.

### What steps can be taken to reproduce the issue? 

Call package_update with `created` field.

**Comment by Vanuan** [comment]
On the other hand, resource_create supports setting the `created` field

**Comment by amercader** [comment]
CKAN has two internal fields to track creation and modification date: `metadata_created` and `metadata_modified`. These are read-only and refer to the actual CKAN dataset on this catalog.

There was some discussion recently about whether these should be editable: https://github.com/ckan/ckan/pull/3476. (cc @TkTech)

The consensus seems to be that both the read-only and the editable fields have appropiate use cases so we could have two pairs of timestamps:

* `metadata_created` / `metadata_modified`: internal read-only timestamps that refer to this particular CKAN instance
* `created` / `last_modified` (for consistency with resources): editable versions for the same thing, that default to `metadata_created` / `metadata_modified` but can be changed when harvesting, creating datasets via API, etc

In the meantime of course you can add `created` and `last_modified` yourself with a custom schema (see [here](http://docs.ckan.org/en/ckan-2.7.0/extensions/adding-custom-fields.html) and [here](https://github.com/ckan/ckanext-scheming)).

**Comment by wardi** [comment]
if you *really* want to be able to overwrite the metadata_modified and metadata_created with package_update that can also be accomplished with a custom schema. e.g. you can copy the values to other fields on input then override them on output with some custom validators.

**Comment by Vanuan** [comment]
Looks like I also have to change dataset sorting behaviour to use new fields.
My use case is to mirror (harvest) datasets from multiple data sources to CKAN. And I want to preserve original dates, not the dates at the time of harvesting.
