### ISSUE TITLE
Multiple resources created for a dataset

### ISSUE THREAD

**Issue by klikstermkd** [ckan/ckan#3773]
### CKAN Version if known (or site URL)
All versions.

### Please describe the expected behaviour
When a new resource is created through the web UI, if the "Add" button in the form is clicked multiple times consecutively, only one resource should be created.

### Please describe the actual behaviour
When a new resource is created through the web UI, if the "Add" button in the form is clicked multiple times consecutively more than one resource is created.

**Comment by smotornyuk** [comment]
As was discussed, the simplest solution would be to disable **Add** button right after user's click. Do you want to do this?:)

**Comment by klikstermkd** [comment]
@smotornyuk Yes seems reasonable to me. Will do it :)
