### ISSUE TITLE
Using url_for in tests for various versions of CKAN

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#3780]
This issue is related to https://github.com/ckan/ckan/pull/3723.

I just changed the tests in ckanext-dcat to include the `test_request_context` for calls to `url_for`. Now the tests run fine with CKAN `master`. But tests with earlier versions of CKAN fail with `'TestApp' object has no attribute 'flask_app'` ([see details on Travis CI](https://travis-ci.org/ckan/ckanext-dcat/builds/267500801))

So I guess I should check if there is a flask_app. Maybe the documentation should have a comprehensive example of how to do this.

**Comment by amercader** [comment]
Good point @metaodi, let me have a think about the best way to handle this.

**Comment by metaodi** [comment]
@amercader I came up with [the following](https://github.com/ckan/ckanext-dcat/pull/94/commits/079ddc2976e560d4b2987b27afeb1178ffee8e0b):

```python
from contextlib import contextmanager

class NullApp():
    @contextmanager
    def test_request_context(self):
        yield
```

And then in the test:

```python
app = self._get_test_app()
with getattr(app, 'flask_app', NullApp()).test_request_context():
    url = url_for(....)
```

Which is arguably not very beautiful, but [it works](https://travis-ci.org/ckan/ckanext-dcat/builds/267514870).

**Comment by amercader** [comment]
@metaodi I'm leaning towards reverting this change entirely, see #3782

**Comment by amercader** [comment]
@metaodi This should no longer be an issue after #3782 was merged. Can you confirm it works as expected from extensions?

**Comment by metaodi** [comment]
@amercader yes perfect, it works like there was never any problem :stuck_out_tongue_winking_eye:
