### ISSUE TITLE
_mail_recipient header override

### ISSUE THREAD

**Issue by ggcatu** [ckan/ckan#3781]
### CKAN Version if known (or site URL)
https://github.com/ckan/ckan/blob/3fa8d9b7476a9f37761749804e4613c196f4fa26/ckan/lib/mailer.py#L30-L36
Mailer is actually adding more keys to the MIMEText, isntead of replacing them.

### Please describe the expected behaviour
To change the Content-Type to the new one

### Please describe the actual behaviour
The old Content-Type is kept, but a new Content-Type key is created

**Comment by amercader** [comment]
@ggcatu This sounds really sensible and looks like you know where the code should be changed. Do you want to submit a PR for this?

**Comment by ggcatu** [comment]
Check https://github.com/ckan/ckan/pull/3784

**Comment by amercader** [comment]
Thanks @ggcatu
