### ISSUE TITLE
Incorrect API link on /dataset

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckan#3796]
### CKAN Version if known (or site URL)
master

### Please describe the expected behaviour
Text at bottom of dataset listing (search.html template) should include a working API link

### Please describe the actual behaviour
A link of the form https://beta.ckan.org/packages?ver=%2F3 is generated
(https://beta.ckan.org/dataset)

This line is no longer working, I suspect because of the recent work to move the API over to Flask(?):
https://github.com/ckan/ckan/blob/master/ckan/templates/package/search.html#L52

**Comment by Zharktas** [comment]
Apparently the api link itself is also broken, which probably is caused by the same issue. For example https://beta.ckan.org/api/3 returns 404.

**Comment by Zharktas** [comment]
Master works now, but this should be backported to 2.7 ? There's bunch of commits that are not in 2.7 and 2.7 tries to get root api action from pylons.
