### ISSUE TITLE
Remove search box label?

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckan#3797]
I'm not a UI expert, but labelling this field when we already have a placeholder text to the same effect and a big search icon seems superfluous:

https://github.com/ckan/ckan/blob/760175a709c8d01f7fcd2f2fd2a83f31cad7ca32/ckan/templates/snippets/search_form.html#L13

But the real reason for my asking is I'm bumping into it on the topic of https://github.com/ckan/ckan/pull/3643 (labelling texts correctly when browsing non-dataset dataset types)

If you're in agreement I'll submit the PR.

**Comment by smotornyuk** [comment]
There are few reasons([a lot of them](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research)) that states, that placeholder and lablel are not interchangeable. But main concern is accessibility of the field, so label is almast always is desirable, even if it seems little bit redundant
