### ISSUE TITLE
Fix Travis build

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#3800]
There is a problem with the Docker tests and it makes all checks fail. @deinok is there a chance you could find some time to investigate and fix this? It would be good to reduce all the noise.

**Comment by deinok** [comment]
I think there is a PR updating the dockers. Should i fix that version or the actual version?

**Comment by amercader** [comment]
If we can fix current master first that would be great

**Comment by ggcatu** [comment]
Adding this line to the dockerfile helped me fix the error.

`apt-get install -y build-essential libssl-dev libffi-dev python-dev`

**Comment by amercader** [comment]
@ggcatu can you send a PR with the changes?

**Comment by ggcatu** [comment]
#3802
