### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by ggcatu** [ckan/ckan#3801]
1.  Is there a proper way to actually override validators?

For example, I want to override member_schema, because I want to add a new validator to one of it's fields.

2.  Why is it that:

> There cannot be more than one IDatasetForm plugin whose
        ``is_fallback()`` method returns ``True``, if this happens CKAN will
        raise an exception at startup.

Why shouldn't we be able to modify the same package though multiple plugins?

**Comment by amercader** [comment]
Hi @ggcatu 
To minimize the number of issues on this repo we encourage you to submit questions and support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

Thanks!
