### ISSUE TITLE
Add a `--skip-failures` flag to `paster search-index rebuild`

### ISSUE THREAD

**Issue by lwm** [ckan/ckan#3804]
We some times get errors when running an entire dataset re-index (with `paster search-index rebuild`). We then resort to listing all of the datasets (using `paster dataset check`) and indexing them individually (using `paster search-index rebuild <dataset-id>` and some `| xargs -i {}` machinery). 

It would be nice to be able to do `paster search-index rebuild --skip-failures` when rebuilding the entire dataset and not fail on any errors.

If we're in agreement, I'll go about submitting a PR.

**Comment by wardi** [comment]
sounds good to me

**Comment by lwm** [comment]
Cool! I'll give it a shot then. \cc @martinburchell

**Comment by amercader** [comment]
Isn't this what the existing `-i` does?

> -i, --force           Ignore exceptions when rebuilding the index

**Comment by lwm** [comment]
Oh! Lovely, nothing needed on our end then. Thanks @amercader!

(A `-i` for the usual `-f` is a bit confusing but probably has some reason!)

**Comment by amercader** [comment]
I think I didn't use `-f` because it is already used by another flag, but I agree it should be consistent, so we could rename `--force` to `--ignore-errors`
