### ISSUE TITLE
AttributeError: 'module' object has no attribute 'redirect' 

### ISSUE THREAD

**Issue by owl17** [ckan/ckan#3812]
CKAN Version : 2.7
Hi,
I am using ckanext-datarequests from [https://github.com/conwetlab/ckanext-datarequests](https://github.com/conwetlab/ckanext-datarequests) for dataset request application in my CKAN project. After user submit dataset request application, form has been submitted successfully but then webpage show **server error (An internal server error occurred)**  

Here is my apache2 error log.

![error](https://user-images.githubusercontent.com/4654433/30410631-e8a52d92-993e-11e7-8c5c-71731c3eb914.png)

I also look into base.py and I didn't found any redirect function also. 
Not only this extension, another extension that i used like ckanext-workflow [https://github.com/abgov/ckanext-workflow](https://github.com/abgov/ckanext-workflow) also encounter the same error. Is these extensions are outdated or did I missing something ?
Please help, thank you

**Comment by owl17** [comment]
@mattfullerton 
Here is the datarequests issue tracker [https://github.com/conwetlab/ckanext-datarequests/issues/26](url)

**Comment by owl17** [comment]
Issue solved. Refer to issue tracker in datarequests.

**Comment by robertocaires** [comment]
Hi there, i am getting the same problem with the extension: ckanext-dictionary
the error is:"redirect = base.redirect
AttributeError: 'module' object has no attribute 'redirect'"
The file is: "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/dictionary/controller.py"
Does anybody have a solution for this?

**Comment by mattfullerton** [comment]
As mentioned above, the solution for modifying extensions to cope with this change in CKAN is documented here:
https://github.com/conwetlab/ckanext-datarequests/issues/26#issuecomment-329382795
