### ISSUE TITLE
Probably useless file > /templates/datapreview_embed_dialog.html

### ISSUE THREAD

**Issue by dportoles** [ckan/ckan#3813]
### CKAN Version if known (or site URL)
2.6.2

### Please describe the expected behaviour
File /templates/snippets/datapreview_embed_dialog.html is not referenced
I think its content is now included in templates/package/snippets/resource_view.html
so I think it could be deleted or deprecated

### Please describe the actual behaviour

It causes no problem so it's no problem if theses file is 

### What steps can be taken to reproduce the issue? 

https://github.com/ckan/ckan/search?utf8=%E2%9C%93&q=datapreview_embed_dialog&type=

**Comment by amercader** [comment]
@dportoles this can definitely go. Do you want to submit a PR to remove it?
