### ISSUE TITLE
Organization/Groups missing close button on mobile/tablet view.

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3814]
### CKAN Version
2.5.6 and lower

### Expected behaviour
For Organizations and Groups on mobile/tablet version, when we click Filters, in the popup the close button should be shown.

### Please describe the actual behaviour
For Organizations and Groups on mobile/tablet version, when we click Filters, in the popup the close button is absent.

### To reproduce the issue:
1. Setup CKAN alt least version 2.5.6
2. Go to org/group page.
3. Change to modile/tablet screen.
4. Click Filters.
5. No close button is shown.

**Comment by Engerrs** [comment]
It seems that this style were wrongly added to lower versions where Font Awesome is not updated to new version.

**Comment by smotornyuk** [comment]
Backported in #3815
