### ISSUE TITLE
adding sysadmin to docker compose

### ISSUE THREAD

**Issue by hsibyani** [ckan/ckan#3817]
I'm running this using the development master. I'm trying to launch it using Docker Compose. However, since there's no sysadmin user, I create a development.ini and when I try to add a sysadmin user I get 

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
```

You can create this by:
1. `cd contib/docker`
2. `docker-compose up`
3. `docker exec -it ckan /bin/bash`
4. `ckan-paster make-config ckan /etc/ckan/default/development.ini`
5. `ckan-paster --plugin=ckan sysadmin add admin --config=/etc/ckan/default/development.ini`

I do not mean this to be a production setup more than an easy way to test UI changes but having a sysadmin account is essential to adding datasets.

PS: I'm having issues when logging in/out as it keeps directing to localhost:5000 from localhost:80 . It's minor but thought I would mention it in case it might helpful for this issue.

**Comment by amercader** [comment]
@hsibyani The whole docker-compose setup is being refactored in https://github.com/ckan/ckan/pull/3692. Can you try if using that branch helps?

**Comment by msmicker** [comment]
I am interested in the same. I am new to docker and ckan, but was able to add by the following steps. I would love to understand the way others are using the docker for dev or prod and adding a first user.

1 - login to ckan container following successful build/up of docker-compose
2 - printenv | grep DB_
      - get the ip adrress of the postgres DB - for me it was (172.17.0.4)
3 - installed vim so I could edit /etc/ckan/default/ckan.ini and update the sqlalchemy postgres url from localhost to the docker ip address
4 - run these command to set virtualenv
. /usr/lib/ckan/default/bin/activate
cd /usr/lib/ckan/default/src/ckan
5 - paster sysadmin add adminuser -c /etc/ckan/default/ckan.ini
6 - enter user info interactively

**Comment by SergK** [comment]
I believe it fails, because db image is not started yet, please see the comment from #3692 

>The ckan container no longer waits for the db container for two reasons: first, the wait sometimes times out, so it's missing its point in those cases; second, all db settings are combined into the CKAN_SQLALCHEMY_URL, so the elegant export of individual host, port, user, pw, db values followed by a psql ping is not available any more.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
