### ISSUE TITLE
CKAN API : Upload url link instead of files

### ISSUE THREAD

**Issue by carbowizzy** [ckan/ckan#3820]
Hi,

I developed this API to upload resources to my CKAN instance which works fine. However , i developed another API to upload url link and not files but it doesn't seem to work.

```
r = requests.post('http://mysite/api/action/resource_create',

		                      data={'package_id': package['id'],
		                            'name': resource_name,
		                            'description':description,
		                            'format': extension,
		                            'url': 'upload',  # Needed to pass validation
		                            },
		                      headers={'Authorization': APIKEY},
		                      files = {'upload': (filename, 'http://mysite/file.pdf' )})
```

Please kindly help me figure it out. Thanks

**Comment by carbowizzy** [comment]
@wardi @amercader  Thanks to you guys for great work, is there a way i can upload url links instead of files with ckan API?

**Comment by amercader** [comment]
Hi @carbowizzy , thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

On this particular thing, if you want to create a resource with just a URL, don't pass the `files` parameter:

```python
r = requests.post('http://mysite/api/action/resource_create',

		                      data={'package_id': package['id'],
		                            'name': resource_name,
		                            'description':description,
		                            'format': 'csv',
		                            'url': 'http://example.com/your.data.csv'
		                            },
		                      headers={'Authorization': APIKEY})
```
