### ISSUE TITLE
'rating_opts' is an undefined name in test_ratings.py

### ISSUE THREAD

**Issue by cclauss** [ckan/ckan#3823]
Undefined names are worth fixing because they have the potential to raise [NameError](https://docs.python.org/2/library/exceptions.html#exceptions.NameError) at runtime.  This fix can be useful for those just getting into the codebase because they often do not require a lot of context to resolve yet can help in learning the contribution process.

The second should be fixed by #4132 but the first is still unresolved.

flake8 testing of https://github.com/ckan/ckan on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./ckan/tests/legacy/functional/api/model/test_ratings.py:50:27: F821 undefined name 'rating_opts'
        assert_equal(res, rating_opts['rating'])
                          ^
./scripts/4042_fix_resource_extras.py:79:22: F821 undefined name 'raw_input'
            choice = raw_input(
                     ^
2     F821 undefined name 'rating_opts'
```

**Comment by wardi** [comment]
@cclauss I wonder why we haven't been getting test failures. Are you interested in submitting a fix for these issues?
