### ISSUE TITLE
[ckan.lib.search] Problems were found while connecting to the SOLR server

### ISSUE THREAD

**Issue by poliveiraIPB** [ckan/ckan#3829]
### CKAN Version if known (or site URL)
2.7.0
### Please describe the actual behaviour

I´m using last version of SOLR (6.6.0), with a core named (ckan) and it´s well configured and functioning at http://127.0.0.1:8983/solr/#/ckan

At /etc/ckan/default/development.ini I configured solr_url as:
 solr_url = http://127.0.0.1:8983/solr/#/ckan

But when starting ckan i get several errors ( JSONDecodeError: Expecting value: line 1 column 1 (char 0))

i think related with this one:
[ckan.lib.search] Problems were found while connecting to the SOLR server 

How can I solve this ?

**Comment by tino097** [comment]
Hi @poliveiraIPB , problem is the 
```http://127.0.0.1:8983/solr/#/ckan``` 
as the url contains ```#``` and causes the issue
you should try with 
```http://127.0.0.1:8983/solr/ckan```

**Comment by poliveiraIPB** [comment]
Yes,i have tried that before.

But with:  http://127.0.0.1:8983/solr/ckan

I give the error:
urllib2.HTTPError: HTTP Error 404: Not Found

Because that URL not exists.

**Comment by poliveiraIPB** [comment]
Ok, it´s working.

So at solr 6.6.0, to the ckan core can be created and work, I have to comment these lines from the schema.xml file.



With that and:

solr_url = http://127.0.0.1:8983/solr/ckan

Ckan works fine.

**Comment by amercader** [comment]
@poliveiraIPB glad you got it working. For reference, what lines did you have to comment on the schema.xml file?

**Comment by poliveiraIPB** [comment]
The lines commented are:

defaultSearchField>text /defaultSearchField>

solrQueryParser defaultOperator="AND"/>
