### ISSUE TITLE
Editor can change dataset visibility (private | public)

### ISSUE THREAD

**Issue by nesnera** [ckan/ckan#3837]
### CKAN Version if known (or site URL)
[CKAN 2.7
](https://ckan.otevrenamesta.cz/api/util/status)
### Please describe the expected behaviour
[Documentation](http://docs.ckan.org/en/latest/maintaining/authorization.html?highlight=ckan.auth#organizations)

### Please describe the actual behaviour
As seems, authorization doesn't work  in 2.7 release. I can change visibility as editor. Tested without any extensions.

### What steps can be taken to reproduce the issue? 
Nothing special. Create an organization and users with administrator role and another one set as editor. If administrator creates new private dataset, editor can change it's visibility to public.
If it's aim, documentation is confusing.

**Comment by tino097** [comment]
@nesnera it is the correct behavior and as it is stated in the documentation


> An editor can:
> View the organization’s private datasets
> Add new datasets to the organization
> **Edit** or delete any of the organization’s datasets

As the changing the visibility is under editing of the dataset, we believe the documentation is not  ambiguous

**Comment by nesnera** [comment]
OK. I see, both admin and editor can change visibility. But please, add "Make datasets public or private." to editor's competency or remove it from admin. Thanks.
_BTW - the reason why i hoped for different permitions is [this plugin](https://github.com/aptivate/ckanext-syndicate) which syndicates public dataset only._
