### ISSUE TITLE
Issue with redirect after updating fields via the GUI

### ISSUE THREAD

**Issue by smartcolumbus-ide** [ckan/ckan#3842]
### CKAN Version if known (or site URL)
2.7

### Please describe the expected behaviour
After updating the gui a redirect to the page with the text "profile update"

### Please describe the actual behaviour
Getting an internal server error

### What steps can be taken to reproduce the issue? 
Followed the steps for a source install.

Getting "expected byte string object for header name, value of type unicode found"

**Comment by amercader** [comment]
@smartcolumbus-ide Can you give us more details?

* What steps / pages are actually needed to reproduce the issue
* The full stack trace from the internal error.

Cheers

**Comment by smartcolumbus-ide** [comment]
We reinstalled on a new instance and was not able to reproduce the issue.
