### ISSUE TITLE
Update organization will clear member

### ISSUE THREAD

**Issue by owl17** [ckan/ckan#3849]
CKAN Version: 2.7

**URL**
_app_address/api/3/action/organization_update_

**Parameters**
_id: organization_id
description: "some description here"_

**Method**
_POST_

After I am using API (refer to above) to update organization, all of the members of the organization has been removed from the organization. 

Is it a bug or did I missed out something?

**Comment by TkTech** [comment]
You need to call organization_show to get the current organization, change what you want, then organization_update. organization_update updates the entire object, including the user list which you are leaving blank.

Most of the APIs are like that, legacy things unfortunately.

**Comment by owl17** [comment]
Thanks for quick reply and help. 
Problem solved.
