### ISSUE TITLE
Group image won't update

### ISSUE THREAD

**Issue by owl17** [ckan/ckan#3853]
CKAN Version: 2.7

**URL**
_app_address/api/3/action/group_patch_

**Parameters**
_id: group_id
title: "title text"
description: "some description here"
image_url: "image url"_

**Method**
_POST_

Group's title and description is updated except its image_url, remain unchanged.
Anyone encounter this kind of issue?

**Comment by tino097** [comment]
@owl17 you should add `"clear_upload"` flag set to `True` within this request

**Comment by owl17** [comment]
@tino097 thank you and it is working! May I know what is this flag for ? I couldn't find it in documentation.

**Comment by owl17** [comment]
I just find it in [here](http://docs.ckan.org/en/ckan-2.7.2/maintaining/filestore.html?highlight=clear_upload)
