### ISSUE TITLE
Setuptools installation instructions still broken on 2.7

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3859]
#3641 reported broken installation instructions for `setuptools`, which was fixed by #3642. However, it seems that the changes were [not merged into the 2.7 branch](https://github.com/ckan/ckan/blob/ckan-2.7.0/doc/maintaining/installing/install-from-source.rst). As a result, the docs for 2.7.0-2.7.2 still show the issue of #3641.

**Comment by smotornyuk** [comment]
Updated, now latest documentation is correct

**Comment by xapple** [comment]
This was first reported in June, and still appears to be wrong in the docs!

**Comment by smotornyuk** [comment]
@xapple , this update is merged into latest version of code, make sure you're using `latest` branch of docs - http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#install-ckan-into-a-python-virtual-environment

**Comment by amercader** [comment]
Additionally it has been backported to the dev-v2.7 branch so the 2.7.x docs will get updated on the next patch release.
