### ISSUE TITLE
CKAN's web GUI damages extended metadata fields

### ISSUE THREAD

**Issue by nesnera** [ckan/ckan#3861]
### CKAN Version if known (or site URL)
2.7.2

### Please describe the expected behaviour
Filled information should be preserved regardless if an plugin is enabled or not.

### Please describe the actual behaviour
If you fill metadata form extended by "extras plugin" (IDataset Form) and do the same but with disabled plugin, all extras information are lost.

### What steps can be taken to reproduce the issue? 
1. enable builded plugin "example_idatasetform"
2. edit an dataset and fill in a value into the "Custom Text" field (e.g. by value "extra"
3. check what is happened by API URL - http://<your_site>/api/3/action/package_show?id=<your_dataset>
You will see something like "custom_text": "extra"
4. disable plugin
5. open dataset for edit and save
6. reload previous API URL. The "custom_text" field is deleted

Compare it with bulk operation which works pretty nice

7. Edit your dataset and fill into "Custom Field:" Key: "custom_text" Value: "custom"
8. Save it and check API URL. Result is somethink like "extras": [{"key": "custom_text", "value": "custom"}],
9. turn-on plugin
10. run bulk operation "Make public" at http://<your_site>/organization/bulk_process/<your_organization> (Select appropriate document, of course.)
11. If you reload API URL, you can see 
"custom_text": "custom"
12. If you turn on and off again, "Make public" action will switch content between "custom_text": "custom" and "extras": [{"key": "custom_text", "value": "custom"}] but user's input is preserved.

I believe web GUI should do the same thing - move extras between "Custom Filed"s if plugin is turned off and back if enabled.

**Comment by amercader** [comment]
@nesnera just to confirm what you are reporting:

1. You enable `example_idatasetform` plugin
2. You create a dataset and fill the `custom_text` field
3. `package_show` shows the `custom_text` field
4. You disable the `example_idatasetform` plugin
5. *(something missing, see below)*
6. You go to edit the dataset and the custom text field is not there (obvioulsy), but it also doesn't show an extra with `[{"key": "custom_text", "value": "custom"}]`

What is happening here is that internally the custom field is indeed stored as an extra (all custom fields that are not part of the default CKAN schema are), but when loading the form after disabling the plugin, you are using the old cached version of the dataset metadata in the search index.

If you add an extra step between 4 and 6, you will get custom_text as an extra in the form:

5. Rebuild the search index: `paster search-index rebuild`.

This will update the metadata object (you can check the `extras` on `package_show`) and update what is displayed in the form. The custom fields are always stored as extras in the database, but the search index needs to be kept in sync.

Does this make sense? Please reopen if I misunderstood the issue.
Cheers

**Comment by nesnera** [comment]
Thank you @amercader . That's exactly the explanation I needed to hear. (y)
Can you mention it in [this article](http://docs.ckan.org/en/latest/extensions/adding-custom-fields.html), please? And the [limitation for multiple "extras" plugin](https://lists.okfn.org/pipermail/ckan-dev/2017-October/011145.html) should be mentioned too ;)
