### ISSUE TITLE
Permission labels are indexed by type text in SOLR

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#3863]
### CKAN Version if known (or site URL)
2.7, master

### Please describe the expected behaviour
Organization Admin should see organizations private datasets even when SOLR indexing has been changed to accommodate different languages. The permission label should not be index by language rules.

### Please describe the actual behaviour
If indexing rules are changed for example to use [EdgeNGram](https://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.EdgeNGramFilterFactory), the permission label id's are indexed by these rules and organization admin, editor or member can not see organizations private datasets.

### What steps can be taken to reproduce the issue? 
Apply EdgeNGram to solr indexing.

Create organization.
Create user.
Add user to organization.
Create private Dataset to organization.

### Possible fix
Use type textgen instead of text in the default schema.xml.

**Comment by wardi** [comment]
@Zharktas sounds right to me. Mind submitting a PR?

**Comment by TkTech** [comment]
Use `string` not `textgen`, which in CKAN's schema is not the same as the old Solr 1.* `textgen` FieldType (confusing I know).

**Comment by Zharktas** [comment]
@wardi submitted minor PR for this.
