### ISSUE TITLE
File uploads don't work on new Flask based API

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#3869]
For instance:

```
curl -X POST http://localhost:5000/api/action/resource_create \ 
-F "package_id=9222f234-2839-4864-8463-03dca09d6237" \ 
-F "name=Test upload API" \
-F "upload=@/home/adria/Downloads/valid.csv" \
-H "Authorization: API_KEY"
```

Works on 2.7 but not on master (the resource is created but no file is uploaded). The `data_dict` received by `resource_create` does not contain any `upload` key at all, so that is being lost in when [getting the request data](https://github.com/ckan/ckan/blob/master/ckan/views/api.py#L133).

**Comment by mattfullerton** [comment]
Do you intend to work on this? Anything I can do to help?

**Comment by amercader** [comment]
I had a quick look at this. We need to fix this at three levels:

1. We need to include incoming files in the `data_dict` passed to actions:

  ```diff
diff --git a/ckan/views/api.py b/ckan/views/api.py
index b9ed2e6..d7d73f2 100644
--- a/ckan/views/api.py
+++ b/ckan/views/api.py
@@ -198,6 +198,9 @@ def _get_request_data(try_url_params=False):
         raise ValueError(u'Invalid request. Please use the POST method for '
                          'your request')
 
+    for field_name, file_ in request.files.iteritems():
+        request_data[field_name] = file_
+
     log.debug(u'Request data extracted: %r', request_data)
 
     return request_data


  ```

2. `Upload` and `ResourceUpload` classes need to also check against the [class](http://werkzeug.pocoo.org/docs/0.12/datastructures/#werkzeug.datastructures.FileStorage) used by Flask/Werkzeug

  ```diff
diff --git a/ckan/lib/uploader.py b/ckan/lib/uploader.py
index f83817c..6de65c9 100644
--- a/ckan/lib/uploader.py
+++ b/ckan/lib/uploader.py
@@ -7,6 +7,8 @@ import logging
 import magic
 import mimetypes
 
+from werkzeug.datastructures import FileStorage as flask_FileStorage
+
 import ckan.lib.munge as munge
 import ckan.logic as logic
 import ckan.plugins as plugins
@@ -206,7 +208,8 @@ class ResourceUpload(object):
         if config_mimetype_guess == 'file_ext':
             self.mimetype = mimetypes.guess_type(url)[0]
 
-        if isinstance(upload_field_storage, cgi.FieldStorage):
+        if isinstance(
+                upload_field_storage, (cgi.FieldStorage, flask_FileStorage)):
             self.filesize = 0  # bytes
 
             self.filename = upload_field_storage.filename


  ```

3. We need to refactor the same classes so any operation we did against the current `FieldStorage` object is supported against the new one, eg this is the first error I'm getting without changing anything:

  ```
  File "/home/adria/dev/pyenvs/ckan/src/ckan/ckan/lib/uploader.py", line 46, in get_resource_uploader
    upload = ResourceUpload(data_dict)
  File "/home/adria/dev/pyenvs/ckan/src/ckan/ckan/lib/uploader.py", line 220, in __init__
    self.upload_file = upload_field_storage.file
  File "/home/adria/dev/pyenvs/ckan/local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 2723, in __getattr__
    return getattr(self.stream, name)
AttributeError: '_io.BytesIO' object has no attribute 'file'
  ```
  Not sure if we can handle each failing call individually or we need some kind of wrapper like the one @wardi mentioned.

4. And of course we need a test that uploads a file via the API to make sure this works going forward

**Comment by amercader** [comment]
@mattfullerton does this sound like something you could look into relatively soon? Otherwise @smotornyuk will work on it

**Comment by wardi** [comment]
here's what ckanapi.LocalCKAN does for file-like objects passed to the API: https://github.com/ckan/ckanapi/blob/master/ckanapi/localckan.py#L54-L69

There's a special case for streams. Some actions assume we can seek on uploaded files so in that case we need to create a temporary file.

**Comment by mattfullerton** [comment]
@amercader I would have volunteered if it wasn't going to get looked at soon, as I have one CKAN where I'd like to stay on master and we do a lot of file uploads. Happy to let @smotornyuk work on it.
