### ISSUE TITLE
docker install fail because www.pylonshq.com/download is down

### ISSUE THREAD

**Issue by terchris** [ckan/ckan#3873]
### CKAN Version if known (or site URL)
code as of 18 Oct 2017

### Please describe the expected behaviour
ckan dunning in docker container

### Please describe the actual behaviour
The site http://www.pylonshq.com/download/ is down and the install get a timeout when trying to download something from the page.

First:
 Running setup.py install for Pylons
    Searching for six
    Reading http://www.pylonshq.com/download/
    Reading http://www.pylonshq.com/download/0.9.7
    error: timed out

Then:

Searching for six
Reading http://www.pylonshq.com/download/
Reading http://www.pylonshq.com/download/0.9.7
error: timed out

----------------------------------------
Cleaning up...
Command /usr/lib/ckan/venv/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-py20Rc/Pylons/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0TzOS8-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/lib/ckan/venv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-py20Rc/Pylons
Storing debug log for failure in /root/.pip/pip.log
ERROR: Service 'ckan' failed to build: The command '/bin/sh -c ckan-pip install --upgrade -r $CKAN_VENV/src/ckan/requirements.txt &&     ckan-pip install -e $CKAN_VENV/src/ckan/ &&     ln -s $CKAN_VENV/src/ckan/ckan/config/who.ini $CKAN_CONFIG/who.ini &&     cp -v $CKAN_VENV/src/ckan/contrib/docker/ckan-entrypoint.sh /ckan-entrypoint.sh &&     chmod +x /ckan-entrypoint.sh &&     chown -R ckan:ckan $CKAN_HOME $CKAN_VENV $CKAN_CONFIG $CKAN_STORAGE_PATH' returned a non-zero code: 1

### What steps can be taken to reproduce the issue? 
Try opening the page http://www.pylonshq.com/download/ in a browser

**Comment by terchris** [comment]
imple FIX 
In ckan/setup.cfg change

this line:
[easy_install]
find_links = http://www.pylonshq.com/download/

To this line:
[easy_install]
find_links = https://pypi.python.org/pypi/six


Now the output during build seems to work. It finds six (whatever that is)

    Searching for six
    Reading https://pypi.python.org/simple/six/
    Best match: six 1.11.0
    Downloading https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz#md5=d12789f9baf7e9fb2524c0c64f1773f8
    Processing six-1.11.0.tar.gz
    Writing /tmp/easy_install-O9Rmdt/six-1.11.0/setup.cfg
    Running six-1.11.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-O9Rmdt/six-1.11.0/egg-dist-tmp-1E4PJx
    no previously-included directories found matching 'documentation/_build'
    zip_safe flag not set; analyzing archive contents...
    six: module references __path__
    
    Installed /tmp/pip-build-hqkfgf/simplejson/six-1.11.0-py2.7.egg

**Comment by mattfullerton** [comment]
Is this in anyway related to needing to install the setuptools requirements file? That doesn't seem to be in the CKAN Dockerfile. @florianm

**Comment by amercader** [comment]
I don't think this line should be there at all, we should just remove it from setup.cfg.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
