### ISSUE TITLE
Language switcher in CKAN (V2.5.7) webpages not working

### ISSUE THREAD

**Issue by declandunne** [ckan/ckan#3875]
### CKAN Version if known (or site URL)
V2.5.7

### Please describe the expected behaviour
I expect the language switcher to work

### Please describe the actual behaviour
But language switcher does not work

### What steps can be taken to reproduce the issue? 
Install CKAN V2.5.7

**Comment by declandunne** [comment]
I found a code issue in CKAN 2.5.6 and CKAN 2.5.7. The language switcher worked in previous 2.5.x versions. I have a temporary fix at: https://github.com/AQUACROSS/ckan/commit/49d202c474f2f27953768decc656598d7e38d0ae.

If there is no plan/need to fully backport issue https://github.com/ckan/ckan/issues/3073, then this fix should be OK and I can create a pull request. Otherwise, a full backport may solve this language switcher issue either. Please advise best approach. Thanks.

**Comment by amercader** [comment]
@declandunne you are right, there was a bad cherry-picking that introduced these changes. I think it's too late in the day for a full backport so just reverting this particular change in `language-selector.html` sounds like the best approach for 2.5.8. If you can submit a PR against `release-v2.5.8` that would be great.

**Comment by declandunne** [comment]
Pull request submitted against release-v2.5.8 #3887

**Comment by amercader** [comment]
Cherry-picked to 2.5.8, thanks @declandunne
