### ISSUE TITLE
Remove authorization_group tables

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#3879]
### CKAN Version if known (or site URL)
Newest.

### Please describe the expected behaviour
Tables authorization_group, authorization_group_role, authorization_group_user  should not exist. There are no migrations to delete them.

### Please describe the actual behaviour
I've seen some work on cleaning authz: @rossjones working on it here https://github.com/ckan/ckan/commit/45c31815ea3282d185bde284788baf5da1b1749d, @tobes here https://github.com/ckan/ckan/commit/dc2ca3fe7185126cd455a7b96c7c72ca958411da, plus a PR https://github.com/ckan/ckan/pull/349.

I don't see migrations to delete those tables.

**Comment by amercader** [comment]
Yes, these tables were used a long time ago. Feel free to submit a PR with a migration to get rid of them.

**Comment by smotornyuk** [comment]
Fixed by @rossjones  in #4309
