### ISSUE TITLE
CKAN 2.7 header not showing toggle bars

### ISSUE THREAD

**Issue by yibeihuang** [ckan/ckan#3880]
### CKAN Version if known (or site URL)
CKAN 2.7.2

### Please describe the expected behaviour
header button should show three bars when narrowing the window

### Please describe the actual behaviour
the three bars are not showing

### What steps can be taken to reproduce the issue? 
in header.html, inside button 'data-target=".nav-collapse"' we need to replace the three 'fa-bar' with one 'fa fa-bars'.

**Comment by amercader** [comment]
@yibeihuang that should be a really easy fix and looks like you already know what to change, do you want to submit a PR?

**Comment by yibeihuang** [comment]
Sure! I will.

**Comment by amercader** [comment]
Backported to 2.7.3
