### ISSUE TITLE
Move docker-compose.yml to project root

### ISSUE THREAD

**Issue by gerbyzation** [ckan/ckan#3894]
By moving the docker-compose file to the root of the project we can make the whole repo available in the build context. 

The first benefit is that it solves the issue when using a version of CKAN different from master, at the moment it's loading the `schema.xml` via a github url from the master branch, which will raise a schema conflict error. (https://github.com/ckan/ckan/issues/2255#issuecomment-336146034). By moving the docker-compose file up to the root we can reference the schema file present in `ckan/config/solr/`, ensuring it's referencing the correct version. 

Secondly it would also open up the opportunity to mount the local files into the container, which would be very helpful for local development.

Only `docker-compose.yml` and `.env` would need to be moved to the root, the remaining files can be referenced to in `contrib/docker`. 

Please let me know your thoughts or if I've missed anything. Happy to put together a PR if this seems acceptable.

**Comment by wardi** [comment]
It's fine with me

**Comment by gerbyzation** [comment]
Found out that docker-compose can actually assign a context higher in the file hierarchy, so it's not required to move up to the root. So for now I've left it where it is.
