### ISSUE TITLE
.env.template is missing

### ISSUE THREAD

**Issue by gjackson12** [ckan/ckan#3896]
The .env.template file in contrib/docker/ no longer appears to be there.

**Comment by emepetres** [comment]
Why is this issue closed? Where can we find the .env.template file?

**Comment by gjackson12** [comment]
I found it. I was just blind.

**Comment by sirex** [comment]
Actually, according to documentation if you checkout 2.6.2 version tag or even 2.7.2, `.env.template` does not exist, it only exists in master.

Also documentation for http://docs.ckan.org/en/ckan-2.7.2/maintaining/installing/install-from-docker-compose.html does not work.
