### ISSUE TITLE
ERROR 500 EVERY SUBMIT DATA

### ISSUE THREAD

**Issue by goparklubanic** [ckan/ckan#3902]
### CKAN 2.7.2 on Ubuntu 16.04 Server
Installation reference http://docs.ckan.org/en/ckan-2.7.2/maintaining/installing/install-from-source.html

### Return error 500 page every time submit data.
Ckan always showing error 500 page avery time user submit data. The only extension is datatstore. Here is the output of apache2 ckan error log:

> [Tue Oct 31 23:05:58.543759 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363] mod_wsgi (pid=29257): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
> [Tue Oct 31 23:05:58.543801 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363] Traceback (most recent call last):
> [Tue Oct 31 23:05:58.543822 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 136, in __call__
> [Tue Oct 31 23:05:58.543861 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     return self.apps[app_name](environ, start_response)
> [Tue Oct 31 23:05:58.543875 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
> [Tue Oct 31 23:05:58.543894 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     return self.apps[-1](environ, start_response)
> [Tue Oct 31 23:05:58.543905 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py", line 61, in __call__
> [Tue Oct 31 23:05:58.543929 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     return self.app(environ, start_response)
> [Tue Oct 31 23:05:58.543969 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
> [Tue Oct 31 23:05:58.544030 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     app_iter = self.application(environ, start_response)
> [Tue Oct 31 23:05:58.544049 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 117, in __call__
> [Tue Oct 31 23:05:58.544073 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     wrapper.finish_response(remember_headers)
> [Tue Oct 31 23:05:58.544084 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 177, in finish_response
> [Tue Oct 31 23:05:58.544110 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363]     write = self.start_response(self.status, headers, self.exc_info)
> [Tue Oct 31 23:05:58.544134 2017] [wsgi:error] [pid 29257:tid 140278908057344] [remote 127.0.0.1:34363] TypeError: expected byte string object, value of type unicode found
> 

Here is the wsgi config file. The same config as the guide:

singledata@singledata:~$ cat /etc/ckan/default/apache.wsgi

> import os
> activate_this = os.path.join('/usr/lib/ckan/default/bin/activate_this.py')
> execfile(activate_this, dict(__file__=activate_this))
> 
> from paste.deploy import loadapp
> config_filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'production.ini')
> from paste.script.util.logging_config import fileConfig
> fileConfig(config_filepath)
> application = loadapp('config:%s' % config_filepath)
> 

whish there are any solution to fix this. Thanks.

**Comment by tino097** [comment]
Hi @goparklubanic , thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!

**Comment by goparklubanic** [comment]
thanks for fast response
