### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('six')

### ISSUE THREAD

**Issue by kabeza** [ckan/ckan#3906]
### CKAN Version if known (or site URL)
2.7.2

### Please describe the expected behaviour
I went through the process of installing CKAN from source following this tutorial.
Changed every 2.5.2 reference to latest release, 2.7.2
https://github.com/ckan/ckan/wiki/How-to-install-CKAN-2.5-from-source-on-Debian-8-%22Jessie%22
I'm working behind a corporate proxy

### Please describe the actual behaviour
All went fine until it broke giving this output
**error: Could not find suitable distribution for Requirement.parse('six')**

![imagen_012](https://user-images.githubusercontent.com/274856/32448938-05ddea14-c2ef-11e7-931f-f48ef377817f.jpg)

### What steps can be taken to reproduce the issue? 
1. Set proxy for bashrc, environment, apt, git config, etc.
2. Execute:
```
. /usr/lib/ckan/default/bin/activate
pip install --proxy http://ip:port -r requirements.txt 
```

**Comment by tino097** [comment]
Hello @kabeza, please use the official documentation to [install](http://docs.ckan.org/en/ckan-2.7.2/maintaining/installing/install-from-source.html) CKAN

**Comment by kabeza** [comment]
Then please delete that wiki, it is available from google results

**Comment by tino097** [comment]
I've updated with notification that the tutorial should be used only if you want to install older version of CKAN
