### ISSUE TITLE
Resource's revision_timestamp is never set or updated

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckan#3907]
### CKAN Version if known (or site URL)

Tested on 2.6.4 (demo.ckan.org), but also noted on dados.gov.br (CKAN 2.6.3)

### Please describe the expected behaviour

In the resource view and also through the API (resource_show, package_show), one should be able to tell when has the resource last been edited - i.e., the timestamp of the resource's metadata.

### Please describe the actual behaviour

In the resource view UI, the "Last modified" attribute is either displayed as if it were the same of the date of creation, or "unknown" ([example](https://demo.ckan.org/dataset/metadata-last-updated-bug-hunter/resource/e42c5859-e5e6-4b4b-838a-a5e5953ff8ae)). Calling the CKAN API, the `revision_timestamp` attribute is set to `null` ([example](https://demo.ckan.org/api/3/action/resource_show?id=e42c5859-e5e6-4b4b-838a-a5e5953ff8ae)).

### What steps can be taken to reproduce the issue? 

1. Create a dataset.
2. Add a resource.
3. Update the resource.
4. Check the `revision_timestamp` attribute of the resource. Its value should be the timestamp of step 3 but, is `null`.

### Note

The implementation of #3028 has changed the UI, but not the API behaviour, so the bug should still be present in the master branch. I think that it had also not taken into consideration the fact that the `revision_timestamp` attribute is not being recorded when the resource is edited.

**Comment by tino097** [comment]
Hello @augusto-herrmann, thanks for pointing out about this issue and feel free to make a pull request with the fix

**Comment by Starl3n** [comment]
We have this scheduled for a fix during the next sprint at Link Digital
