### ISSUE TITLE
Unable to add new views and default views aren't working

### ISSUE THREAD

**Issue by gjackson12** [ckan/ckan#3913]
### CKAN Version if known (or site URL)
Version 2.7.2

### Please describe the expected behaviour
I have un-commented out the line in the configuration file in regards to views. I would expect when looking at say an excel resource and going to the manage screen and clicking views that either a default view would already be available and/or I could create a new one. 

### Please describe the actual behaviour
When I go to an Excel file resource I don't see a default view. Additionally, when I go to create a new view, I  don't see any options available when I click the new view button. 

### What steps can be taken to reproduce the issue? 
I'm not sure to be honest. I can provide an image if that would be helpful.

**Comment by amercader** [comment]
Hi @gjackson12 just to confirm, you are not seeing "Data Explorer" on this dropdown?

![screenshot 4](https://user-images.githubusercontent.com/200230/32610281-3645238a-c55a-11e7-9943-e02f33cf118b.png)

Things to check:

* Apart from uncommenting the `ckan.views.default_views` setting in your ini file, you must also enable the relevant plugins on `ckan.plugins`. The default data viewer plugin is `recline_view`. Is that present on your `ckan.plugins` setting?
* Does the resource has a format defined? (XLS or XLSX)

**Comment by gjackson12** [comment]
Problem solved! I had not added the relevant plugins to the `ckan.plugins` configuration. The documentation never mentioned that step.
