### ISSUE TITLE
Search contents of resources

### ISSUE THREAD

**Issue by gjackson12** [ckan/ckan#3917]
### CKAN Version if known (or site URL)
2.7,2

This is a question and not an issue. Is it possible using CKAN to index the contents of resource files and be able to keyword search incorporating that data. Say a csv file contains the word Apple, I would expect to see that file in my search results.

**Comment by TkTech** [comment]
You're looking for one of the Tika integration plugins like https://github.com/transparenzportalhamburg/ckanext-fulltext.

In the future please use the mailing list or stackoverflow for questions.
