### ISSUE TITLE
Clean up template rendering code

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#3923]
[`ckan.lib.base.render()`](https://github.com/ckan/ckan/blob/a923e00e636ad8b83bc0a689c9c7e8833aa63219/ckan/lib/base.py#L97) is a mess of old code that is probably no longer used. Now that we are starting to port Pylons controllers to Flask in earnest is the perfect time to do a long overdue cleanup.

The Canadian open data portal has been running for a while in a [extremely simplified](https://github.com/open-data/ckan/blob/canada-v2.6/ckan/lib/base.py#L88) version of it. @wardi and @TkTech provided context in this [IRC conversation](https://botbot.me/freenode/ckan/2017-11-10/?msg=93378033&page=1).

Essentially:

* Remove all caching logic as it is not applied anyway
* Increase Jinja 2 cache size (https://github.com/open-data/ckan/commit/aa071b063)
* Check if the [`PageCacheMiddleware`](https://github.com/ckan/ckan/blob/a923e00e636ad8b83bc0a689c9c7e8833aa63219/ckan/config/middleware/common_middleware.py#L31) is being used at all, and if not nuke it.

I'm happy to keep all current stuff in a `_render_template_pylons()` function and have the cleaned up version just apply to Flask

**Comment by smotornyuk** [comment]
For simplicity, all existing caching logic from `render` will be moved to separate function called only for pylons' routes, thus it can be safely dropped after finishing flask migrations. 

In addition: 
- enable Jinja2's bytecode cache
- leave cache size with default value(it already increased inside Jinja2 itself)
- completely remove PageCacheMiddleware. First reason for this - it wasn't used for rendering snippets and extended templates, so profit of using it is quite small. In addition, it seems that most of CKAN users configure different variations of caching using separate tools(ex. serving over nginx)

**Comment by amercader** [comment]
Fixed in #3979
