### ISSUE TITLE
Upload file to a package at the command line

### ISSUE THREAD

**Issue by ply112** [ckan/ckan#3928]
### CKAN Version if known (or site URL)
v2.60
### Please describe the expected behaviour
I was trying to upload a file from my home directory on Linux using the following command at the command line in Linux. 

curl http://myckan.org/api/action/resource_create -H "Authorization:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -F upload=@/home/dummyuser/test_json.json -d '{"package_id":"xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}'

### Please describe the actual behaviour
A warning message was returned: "Warning: You can only select one HTTP request!"

My understanding is that "package_id" is the long code CKAN creates for your package, not the package name you enter.  My question is whether the path for the file to be uploaded is specified correctly.  What is the '@' preceding the file path?

**Comment by TkTech** [comment]
This is not how you use curl. The warning is because you're doing `-F` and `-d` at the same time. `-F` tells curl to send a `multipart/form-data` POST. `-d` tells curl to send an `application/x-www-form-urlencoded` POST. Pick one.

`@` is again curl-specific and just means the following is a file.

**Comment by ply112** [comment]
I actually copied the wrong command.  Anyway, I was able to get it to work.  Thanks.
