### ISSUE TITLE
Request for clarification: Unable to update resource package_id

### ISSUE THREAD

**Issue by gerbyzation** [ckan/ckan#3931]
### CKAN Version if known (or site URL)
2.7

### Please describe the expected behaviour
In the documentation it's described that `ckan.logic.action.update.resource_update` updates the resource with the given parameters. For the list of parameters it refers to `resource_create`, where `package_id` is one of the listed parameters.

Based on that I would expect that 
```
resource_update(data_dict={
    'id': resource_id,
    'package_id': destination_package_id,
})
```
update the resource with the new package id. 

### Please describe the actual behaviour
The `package_id` of the resource is not updated. Other parameters passed in the data_dict will update fine. 

The `resource_update` function internally makes use of the `package_update` function, overriding the newly given `package_id`. I'm not sure why it needs to update through the package it belongs to, as far as I can see in the database the relation is defined with a foreign key to the package in the resource schema. 

### What steps can be taken to reproduce the issue? 
```
def move_resources(resources, original_dataset, destination_dataset):
    """
    Move resources from original_dataset to dataset destination_dataset.
    """
    resource_update = get_action('resource_update')
    resource_show = get_action('resource_show')

    for resource in resources:
        data_dict = resource
        data_dict['package_id'] = destination_dataset['id']
        result = resource_update(data_dict=data_dict)
```
```
def test_move_resources_does_update_package_id(self):
    first_dataset = factories.Dataset()
    second_dataset = factories.Dataset()
    user = factories.User()
    resource = factories.Resource(package_id=first_dataset['id'])

    resource_show = get_action('resource_show')
    resource_update = get_action('resource_update')

    data_dict = resource
    data_dict['package_id'] = second_dataset['id']

    resource_update(data_dict=data_dict)

    assert_equal(resource_show(data_dict={'id': resource['id']})['package_id'], second_dataset['id'])
```
The testcase given above fails.

Is this current behaviour intended? 

My objective for using this is to be able to move a resource to a different dataset than originally created in. If I should be doing this through another approach please let me know

**Comment by gerbyzation** [comment]
@wardi any chance you could spare some time for this?

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
