### ISSUE TITLE
CKAN 2.8 version release as a package ? http://packaging.ckan.org/

### ISSUE THREAD

**Issue by asifamingov** [ckan/ckan#3934]
We are planning to integrate our templates which are written in Bootstrap3 with the CKAN templates.

From the documentation I came to know that version 2.8 is using Bootstrap3 . Would like to know when CKAN 2.8 will be available as a release package on this url  http://packaging.ckan.org/ ?

**Comment by wardi** [comment]
This isn't the place to ask about release schedules, but if you'd like to help test master that would help us get there sooner!
