### ISSUE TITLE
CKAN detects wrong game version

### ISSUE THREAD

**Issue by Hunter-The-Gamer** [ckan/ckan#3935]
### CKAN Version if known (or site URL)
1.22.6

### Please describe the expected behaviour
I would update KSP in Steam from 1.2.2 to 1.3.1, CKAN would detect the update, and would allow me to install mods for the new version

### Please describe the actual behaviour
CKAN didn't detect the update, and still only suggests mods for the old version

### What steps can be taken to reproduce the issue? 
I don't know really, it just doesn't work

### Additional information
I'm using a fresh install of KSP (no mods), the default Steam install directory, and my PC is running Windows 10

**Comment by tino097** [comment]
Wrong CKAN
