### ISSUE TITLE
CKAN 2.6.4 user login removing non-root directory

### ISSUE THREAD

**Issue by joelwigley** [ckan/ckan#3942]
### CKAN Version if known (or site URL)
2.6.4

### Please describe the expected behaviour
When logging into CKAN, the user should be redirected to the URL and root directory specified by ckan.site_url and ckan.root_path

i.e if CKAN is running at http://site_url.com.au/data/ then logging in should not remove the "/data/" directory from the URL when logging in.

### Please describe the actual behaviour
CKAN was running with the following settings (site_url.com.au is just an example domain):

ckan.site_url = http://site_url.com.au
ckan.root_path = /data/{{LANG}}/

When logging in at http://site_url.com.au/data/user/login the user is redirected to http://site_url.com.au/user/login which fails with a 404 error.

The login form POSTs to http://site_url.com.au/data/login_generic?came_from=/data/user/logged_in which generates the following HTTP headers:

HTTP/1.1 302 Found
Server: nginx
Date: Mon, 27 Nov 2017 02:15:18 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 375
Connection: keep-alive
Location: http://site_url.com.au/user/logged_in?__logins=0&came_from=%2Fdata%2Fuser%2Flogged_in

### What steps can be taken to reproduce the issue? 
Install CKAN 2.6.4 with no extensions and have it running at /data/ on the site_url domain. Set the site_url and root_path values in production.ini as mentioned higher up. Create a new user and then try to login via the web interface.

### What I did to solve the problem...

After a bit of digging I discovered that adding "/data/" to the front of the following variables in who.ini solved the problem:

login_form_url= /data/user/login
login_handler_path = /data/login_generic
logout_handler_path = /data/user/logout
post_login_url = /data/user/logged_in
post_logout_url = /data/user/logged_out

Once I restarted the Apache process serving CKAN and tried to login again, I was redirected correctly to http://site_url.com.au/data/dashboard as expected.

Instead of needing to manually update these variables to include the root directory where CKAN is being served from, they should (in my opinion) use the existing ckan.root_path value which is already set in production.ini.

**Comment by tino097** [comment]
Yes, this is not well documented, especially the part with repoze. Feel free to create PR with your changes to fix this issue @joelwigley

**Comment by Engerrs** [comment]
Hi @tino097 , @joelwigley.
I've checked this one, it's already working on CKAN 2.7 correctly. Fix is already exist, but not backported for some reasons to CKAN 2.6.
Can [this fix](https://github.com/ckan/ckan/commit/7102445911d88b850b9449860eb920c1387b3b4e) be backported to CKAN 2.6 in next release, as it's already in CKAN 2.7! Thanks

**Comment by vjain641** [comment]
Hi @joelwigley , @tino097 , @Engerrs 

I'm facing the same issue with CKAN 2.7.2 and Nginx 1.13.3 even after applying the above workaround.

CKAN is running with the following settings :
_ckan.site_url = http://CKAN_URL/
ckan.root_path = /ckan/{{LANG}}/

login_form_url= /ckan/user/login
login_handler_path = /ckan/login_generic
post_login_url = /ckan/user/logged_in_

and following is the Nginx configuration:
        _location /ckan/ {
                 proxy_pass   http://CKAN_URL/ ;
                 proxy_set_header    Host    $host;
                 proxy_set_header    X-Real-IP    $remote_addr;
                 proxy_set_header   X-Forwarded-Host    $host;
                 proxy_set_header    X-Forwarded-Server    $host;
                 proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
                 rewrite ^/ckan/ckan/(.*) /ckan/$1 permanent;
                  }_

While logging in [https://<Nginx URL>/ckan/user/login](), the user is redirected to [ https://<Nginx URL>/ckan/login_generic?came_from=/ckan/user/logged_in]() but it fails with a 404 error.

POST [https://<Nginx URL>/ckan/ckan/login_generic?came_from=/ckan/user/logged_in]() response headers:
_HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Wed, 29 Aug 2018 05:03:54 GMT
Content-Type: text/html
Content-Length: 178
Location: https://<Nginx URL>/ckan/login_generic?came_from=/ckan/user/logged_in
Connection: keep-alive
X-Frame-Options: SAMEORIGIN_

GET [https://<Nginx URL>/ckan/login_generic?came_from=/ckan/user/logged_in]() response headers:
_HTTP/1.1 404 Not Found
Server: nginx
Date: Wed, 29 Aug 2018 05:03:54 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 12771
Connection: keep-alive
Cache-Control: public, max-age=0, must-revalidate_

Could you please help here?

**Comment by fostermh** [comment]
Not working in 2.8.1 using the docker image either.
ckan.site_url = http://CKAN_URL/
ckan.root_path = /ckan
```
login_form_url= /ckan/user/login
login_handler_path = /ckan/login_generic
logout_handler_path = /ckan/user/logout
post_login_url = /ckan/user/logged_in
post_logout_url = /ckan/user/logged_out
```
yields 
```
Request URL: https://CKAN_URL/ckan%2Fckan%2Fuser%2Flogged_in
Request Method: GET
Status Code: 404 Not Found
```

While
```
login_form_url= /user/login
login_handler_path = /login_generic
logout_handler_path = /user/logout
post_login_url = /user/logged_in
post_logout_url = /user/logged_out
```
gives
```
Request URL: https://CKAN_URL/user/logged_in?__logins=0&came_from=%252Fckan%252Fuser%252Flogged_in
Request Method: GET
Status Code: 404 Not Found
```

Any suggestions?

**Comment by vjain641** [comment]
Hi @fostermh ,

Could you try below changes in your files:

Change login/logout end points as below(don't put /ckan string in handler paths)-
```
login_form_url= /ckan/user/login
login_handler_path = /login_generic
logout_handler_path = /user/logout
post_login_url = /ckan/user/logged_in
post_logout_url = /ckan/user/logged_out
```
If still issue persists, try minimal conf for nginx like below:
```
_location /ckan/ {
                 proxy_pass   http://CKAN_URL/ ;
                 proxy_set_header X-Url-Scheme $scheme;
                 proxy_set_header Host $host;
                 rewrite ^/ckan/ckan/(.*) /ckan/$1 permanent;
         }_
```
Please comment if you still have trouble in accessing ckan.

**Comment by fostermh** [comment]
@vjain641, thanks for the quick response!

I think I have my issue sorted. I will outline my solution in case it helps others.

This was a two faceted problem. The first was a mis-configuration in the who.ini file (adding /ckan/ to the handler paths), thanks again for that. The second was a redirect from http to https on the host machine. I have apache on the host handling requests and passing to the docker instance. Due to my rewrite rules this meant that:
```
https://CKAN_URL/ckan/login_generic?came_from=/ckan/user/logged_in
```
called
```
http://CKAN_URL/ckan/user/logged_in?__logins=0&came_from=%2Fckan%2Fuser%2Flogged_in
```
which redirected to 
```
https://CKAN_URL/ckan/user/logged_in?__logins=0&came_from=%252Fckan%252Fuser%252Flogged_in
```
Then, because  came_from decodes to "%2Fckan%2Fuser%2Flogged_in", which is seen as a relative path, apache prepended with ```https://CKAN_URL/ckan``` which blew up. 
```
Request URL: https://CKAN_URL/ckan%2Fckan%2Fuser%2Flogged_in
Request Method: GET
Status Code: 404 Not Found
```
### Solution
Change apache config to redirect without escaping the url. 
for example:
```
RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [NC,R,L,**NE**]
```

came_from is still escaped but only once which works. I'm not sure if its ckan or nginx doing the initial escape of came_from. I'm wondering if came_from should be left decoded?
