### ISSUE TITLE
Deleted resource is not deleted

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#395]
If I upload a file as a resource, and then delete it, the file should be deleted from wherever CKAN stored it in the cloud. It is not enough simply to no longer show it in the dataset. This could lead to bad security breaches.

E.g. this file:

http://beta.ckan.org/storage/f/2013-02-07T13%3A52%3A18.792Z/.secure

was created by preview.ckan.org when I uploaded it to a datset called http://preview.ckan.org/dataset/top-secret-personal-data, and is still there even though I deleted the resource (and indeed, even though the dataset no longer exists).

We should also ensure this also happens if the dataset is purged.

**Comment by ansh1221** [comment]
Hi @kindly @amercader was the above issue really fixed, as after Purging the dataset, the resource still remains in filestore at location /var/lib/ckan/resources/...

**Comment by paulmueller** [comment]
@kindly This issue might have to be reopened. I am having the same issue. CKAN 2.8 package install on Ubuntu 16.04.6 LTS (dedicated virtual machine).
