### ISSUE TITLE
Replace MD5 with a more secure algorithm (e.g. SHA2)

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#3950]
### CKAN Version if known (or site URL)
CKAN 2.8+

### Please describe the expected behaviour
Use a secure hash algorithm that is not broken (e.g. SHA2)

### Please describe the actual behaviour
Currently throughout the code base MD5 is used as a secure hash for different purposes. Since MD5 is broken since ~10yrs it might be time to move to a more recent algorithm like SHA2. This is not a security issue per se, but we don't want to risk collisions.

Disclaimer: this is a finding of a recent security audit/code review performed on one of our client installations.

### What steps can be taken to reproduce the issue? 
Search for hashlib.md5 in the code base.

**Comment by TkTech** [comment]
It is not used as a secure hash anywhere. It is used in several places purely as a fast hashing function.

Sha512 with a strong salt is used where strong hashes are required.
