### ISSUE TITLE
CKAN Extension NGSI view can't communicate with Orion in same domain.

### ISSUE THREAD

**Issue by saurabhjangir** [ckan/ckan#3957]
[issue]
If the hostname of CKAN site is same as querycontext API's hostname,
error [Enable resource_proxy] occurred in accessing API from CKAN.
  
 [Root Cuase]
 API is published to Orion from CKAN but it's via NGSI view.
 However NGSI view is coded for blocking communication which is among CKAN and subscriber which is in same domain in 'setup_template_variables' function.

[workaround]
Thus, Workaround of this issue is that it is necessary to name separately each host.

**Comment by saurabhjangir** [comment]
@smotornyuk Hello, Could you please provide me your views on this issue ?

**Comment by wardi** [comment]
Please open this issue in the appropriate extension unless there's part of the fix that must be done in core.
