### ISSUE TITLE
Editor role is able to submit a dataset as private (Missing Role to make workflow make sense)

### ISSUE THREAD

**Issue by gjackson12** [ckan/ckan#3959]
### CKAN Version if known (or site URL)
2.8.0

### Please describe the expected behaviour
One would think there is a user role that can submit a dataset but not also make it public. I'm confused why an editor can submit a dataset and make it public. What is the point of the admin approval workflow? 

### Please describe the actual behaviour
User with editor role is able to submit a dataset and make it public at the same time. This is quite counter intuitive.

**Comment by wardi** [comment]
Thank you, but this seems like a workflow-related feature request not an issue. The mailing list or the ideas repository would be better places to discuss new approval workflows.

A problem with restricting editing public datasets as you describe is that once datasets are published the original editor wouldn't be able to make changes without marking the datasets private again (un-publishing)

One site I work on implements a similar publishing behaviour with two separate ckan instances (one for the editors and one for the general public) There are certainly other ways to accomplish this too.

The roles in CKAN out of the box are:
- member: can view private datasets
- editor: can create and edit datasets
- admin: can add members, editors to orgs
- sysadmin users: all powerful

If the docs don't describe this properly, a update to the docs would be very welcome!

**Comment by gjackson12** [comment]
Fair enough.  I will take a look at the documentation again. 

I just fail to see the purpose of the approval workflow as is. I don't understand the use case that it supports.
