### ISSUE TITLE
Ckan 2.5 and 2.6 missing DB migrations

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3963]
### CKAN Version
2.5.0 < 2.5.8, 2.6.0 < 2.6.4

### Expected behaviour
All migrations that been added at CKAN 2.7 are backported to earlier versions like 2.5 and 2.6.

### Please describe the actual behaviour
CKAN 2.5 and 2.6 missing some migrations that been added at CKAN 2.7.

Backport please the missing migrations for CKAN 2.6 and 2.5, because they adding some fixes to DB.

**Comment by wardi** [comment]
We can't backport migrations because then they won't apply after an upgrade. If there is a specific issue you're having with the DB in 2.5 or 2.6 would you point to that instead?
