### ISSUE TITLE
Missing Display time PR for CKAN 2.5 and 2.6

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3964]
### CKAN Version
2.5, 2.6

### Expected behaviour
PR https://github.com/ckan/ckan/issues/2970 is backported to CKAN 2.5 and 2.6

### Actual behaviour
CKAN 2.5 and 2.6 is missing display time PR, which leads to incorrect time display (-1 day)

Backport please https://github.com/ckan/ckan/issues/2970 to CKAN 2.5 and 2.6
There two commits that related to this one: https://github.com/ckan/ckan/pull/3240/commits/b9b1bd66c0deb0288c752af28eb4e164f3adb656, https://github.com/ckan/ckan/pull/3240/commits/596f5fdb1696fbc4e1714db7bd574a702b9d4998

**Comment by wardi** [comment]
@Engerrs #2970 is an issue, what is the PR you would like backported?

**Comment by amercader** [comment]
PR was https://github.com/ckan/ckan/pull/3240, backported
