### ISSUE TITLE
Can I embed private dataset's data explorer in other site?

### ISSUE THREAD

**Issue by owl17** [ckan/ckan#3974]
### CKAN Version if known (or site URL)
CKAN 2.7

### Please describe the expected behaviour
Due to some reasons, I want to embed data explorer which belong to a private dataset to other website.
I am authorized to access to the private dataset, the embed data explorer work fine in external website if I logged in in my CKAN website, otherwise the embed data explorer show Error 404 in external website. 

Is there have anyway to pass authorization in order to view my private dataset's data explorer from external website?

Thanks.

**Comment by tino097** [comment]
Hi @owl17 , thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!
