### ISSUE TITLE
500 Internal Server Error in Docker Container APP when image created with drone 

### ISSUE THREAD

**Issue by Priyanka12345678910** [ckan/ckan#3977]
I am trying to run a python-Django app within container. When I manually build the image and push that to artifactory, pull the image from there , build the container then app works fine. But If everything happens through proper process (git push, .drone.yaml create the image and push that image to the artifactory), If I pull that image and build the container from that. Then app running in that container throws "Internal Server Error".

I logged into the container and checked nginx and supervisord services are running fine. All the pip packages are installed. Tried with --upgrade also.

**Comment by amercader** [comment]
@Priyanka12345678910 I'm not sure this relates to CKAN (the data portal) If so please provide more details.
