### ISSUE TITLE
CKAN installation on Linux - required dos2unix on file

### ISSUE THREAD

**Issue by carlsonp** [ckan/ckan#3990]
### CKAN Version if known (or site URL)
3921dd9d7c094c50dc666708f11d6f340af9044c

### Please describe the expected behaviour
I expected the installation via Docker on Linux Ubuntu to run without needing changes.

### Please describe the actual behaviour
All docker containers started except the main one "docker_ckan".

### What steps can be taken to reproduce the issue? 
Clone the code and try a clean install

### What can be done to fix the issue?
I ended up running `dos2unix contrib/docker/ckan-entrypoint.sh`.  This resolved the problem.  Maybe someone running on Windows could try this?  If it's OK we could commit this small change.

**Comment by thekaveman** [comment]
I am running Docker for Windows and I was not seeing the "docker_ckan" container start (while the other 4 started just fine) at the latest commit 44aea3b

Running `dos2unix contrib/docker/ckan-entrypoint.sh` fixed the issue for me.

**Comment by thekaveman** [comment]
Continuing along with the Docker installation instructions, I ran into another (potential) instance of this issue.

At [Step 3](http://docs.ckan.org/en/latest/maintaining/installing/install-from-docker-compose.html#datastore-and-datapusher), and after reading the discussion on #3991 (which led me to modify the command according to @ghislainp's suggestion), I received the following error:

> /docker-entrypoint-initdb.d/00_create_datastore.sh: 2: set: Illegal option -

After tearing everything down, running 

    dos2unix contrib/docker/postgresql/docker-entrypoint-initdb.d/00_create_datastore.sh

rebuilding, and getting to this point again - I get the error reported by @ghislainp in #3991:

> ERROR:  role "datastore_ro" already exists

**Comment by frafra** [comment]
I do not have such problem running CKAN from Docker on Linux. I fetched it using git. I guess this issue has been solved.

@thekaveman Can you close this issue if it has been fixed?

**Comment by thekaveman** [comment]
Hi @frafra - I didn't open the issue; and I haven't worked with CKAN in some time, so I'm not really following it anymore. Fine by me to close it.

@carlsonp was the OP for this issue, maybe they would like to chime in?

**Comment by carlsonp** [comment]
It's likely a result of what OS (Linux or Windows) the git checkout is performed on.  If you're on Linux and you checkout the code and build it you're likely using the appropriate line endings.  In my case, I had to use `dos2unix` to switch them on Windows.  It likely could have also been fixed on the Git side by setting `core.autocrlf`.  I'll close it out.
