### ISSUE TITLE
Docker install documentation for datastore should reference .sh file

### ISSUE THREAD

**Issue by carlsonp** [ckan/ckan#3991]
### CKAN Version if known (or site URL)
3921dd9d7c094c50dc666708f11d6f340af9044c
On Docker installed on Ubuntu Linux

### Please describe the behaviour

https://github.com/ckan/ckan/blob/6951bf69b34a43b9b798640c2353394d711b99da/doc/maintaining/installing/install-from-docker-compose.rst#3-datastore-and-datapusher

This documentation section references `00_create_datastore.sql`, however, this file does not exist.  I'm guessing it should reference this:

https://github.com/ckan/ckan/blob/master/contrib/docker/postgresql/docker-entrypoint-initdb.d/00_create_datastore.sh

### Referenced commits

https://github.com/ckan/ckan/commit/65139aa3d045ee6e07072e61d79128ead5ad69b6#diff-27c8c3b5d7593e7e1c8e9ee90599401f

**Comment by ghislainp** [comment]
It seems the full command is:
docker exec -it db  /bin/sh /docker-entrypoint-initdb.d/00_create_datastore.sh

but I got an error saying the ro user was already created. I guess this means this operation has been done automatically before. It is correct ? This part of the documentation definitely needs some cleaning

**Comment by fvanderbiest** [comment]
There is no `00_create_datastore.sh` file indeed.

The [doc](https://github.com/ckan/ckan/blob/2.8/doc/maintaining/installing/install-from-docker-compose.rst#3-datastore-and-datapusher) requires an update. Can someone have a look ? Thanks

**Comment by tino097** [comment]
Fixed in #4274
