### ISSUE TITLE
Does CKAN track who has accessed what resources on CKAN?

### ISSUE THREAD

**Issue by ply112** [ckan/ckan#3998]
### CKAN Version if known (or site URL)
Version 2.6.1

### Please describe the expected behaviour
We plan to upload PHI data to our CKAN instance. Although we have already set these datasets as PRIVATE, it would be important and it is a corporate requirement to track who has accessed what datasets/resources and the type of access (download / view etc. ). 

### Please describe the actual behaviour
I am digging deep into CKAN's database tables, including tracking_summary, tracking_raw, resource_view, activity, activity_detail etc., but haven't been able to pinpoint the exact table that contains the right information.

So far, the tracking_raw table seems to have the information I need. However, the user_key column does not match the user id column in the ****ldap_user**** or user table. Additionally, the same user_key is linked to activities by different users within a short time window.  In essence, CKAN doesn't appear to be tracking "who has accessed what".

Are there user access logs on the server side?  Any inputs would be greatly appreciated. Thanks.

### What steps can be taken to reproduce the issue? 
I have done some testing and confirmed that CKAN does not link user activities to individual users in the Tracking_Raw table.

**Comment by amercader** [comment]
@ply112 you are right. As far as I'm aware there is no functionality in CKAN core that tracks which individual users access particular resources. You'll need to implement something like this yourself.

IIRC ckanext-googleanalytics has support for API events that track resource downloads, maybe you can extend that code. Also ckanext-cloudstorage generates temporary URLs for private resources that you might be able to track depending on your needs (I might have got that wrong, @TkTech is the ckanext-cloudstorage expert).

Hope this helps. Please write to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) if you need further help.

**Comment by ply112** [comment]
Thank you so much for your response.

**Comment by TkTech** [comment]
You could use the same hooks ckanext-cloudstorage does to check auth, which provides you with a user object. Then maybe insert an activity event "X downloaded X"? Secure urls let you auditlog the IP but not much else.

**Comment by ply112** [comment]
Thank you, TkTech.  I'll look into ckanext-cloudstorage.
