### ISSUE TITLE
Data explorer failed to load

### ISSUE THREAD

**Issue by owl17** [ckan/ckan#3999]
### CKAN Version if known (or site URL)
CKAN 2.7.0

### Please describe the actual behaviour
Sometime (frequently), data explorer failed to display. It keep loading. What I found is that it go to jsonpdataproxy.appspot.com and jsonpdataproxy malfunction sometime. Is there any alternative solution to replace the services provided by jsonpdataproxy ?  

Thanks a lot.

**Comment by mattfullerton** [comment]
Please see this answer: #3177

**Comment by owl17** [comment]
@mattfullerton I did setup Datastore and the data is pushed successfully by Datapusher, but it still use jsonpdataproxy. Did I missed some configuration?

**Comment by owl17** [comment]
@mattfullerton Thanks for your solution. Just found that I did setup Datastore and Datapusher but Datapusher failed to push data from CSV due to my configuration on .htaccess blocked Datapusher to download the CSV file.

Once again, thanks for your help.
