### ISSUE TITLE
Please confirm the situation of vulnerability problem of the CSRF in CKAN.

### ISSUE THREAD

**Issue by saurabhjangir** [ckan/ckan#4009]
I would like to know what is the situation of vulnerabilty problem of the CSRF in CKAN.
What methods are implemented to protect CKAN against CSRF issue ?

**Comment by wardi** [comment]
Your best bet right now is to use the middleware provided by https://github.com/data-govt-nz/ckanext-security . Let us know if you're interested in helping migrate this feature into core.

**Comment by saurabhjangir** [comment]
What I can guess from this is that CSRF protection is not implemented in core CKAN code.
For using protection against CSRF we need to install this extension with CKAN?
Am I thinking right @wardi

**Comment by saurabhjangir** [comment]
@wardi  I am interested in migrating this feature in core CKAN.

**Comment by ThrawnCA** [comment]
@wardi Does the CSRF protection in `ckanext-security` actually work? I've looked at the code, and I can't see how it would block an attack. It sets a token cookie and then checks for it, but it never compares that token to the request contents, so how can it tell whether the request was genuine or forged? Browsers attach cookies to cross-site requests, that's the whole basis of CSRF, so the token cookie would appear even on a forged request.

**Comment by ThrawnCA** [comment]
@wardi @saurabhjangir I [have tested](https://github.com/data-govt-nz/ckanext-security/issues/23) the CSRF protection in ckanext-security, and I do NOT recommend relying on it. It's actually just a Referer check. All the setting and reading of cookies is entirely ineffective to stop a CSRF attack.

**Comment by camfindlay** [comment]
Big thanks to @ThrawnCA for raising the issue. We're going to look into getting a patch in ckanext-security shortly. Would also be good to pick up the conversation about building in CSRF to CKAN core.

**Comment by wardi** [comment]
@ThrawnCA you're right about the referer check, but that's all we've got for now.

IIUC a proper CSRF fix would require hidden input fields in all our forms and logic on the view side to validate them. That's a fair bit of work but certainly worthwhile if you've got some time.

**Comment by ThrawnCA** [comment]
The trouble with inserting hidden fields everywhere is that the templates can be overridden, and usually are. That would potentially place a significant burden on pretty much every CKAN installation. To make it manageable requires dynamic insertion of the hidden fields.

`ckanext-security` is in the process of adding such a filter: https://github.com/data-govt-nz/ckanext-security/pull/24

However, that filter is basically the same one that was [already rejected for CKAN core](https://github.com/ckan/ckan/pull/2359#issuecomment-132502500), except that it's now fully self-contained, no JavaScript patching necessary. It's not clear whether or not that is sufficient to make it compatible with CKAN's future direction?
