### ISSUE TITLE
Datapusher extension: Custom url instead of ckan site url

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan#4013]
### CKAN Version if known (or site URL)

2.7

### Please describe the expected behaviour

I want datapusher to use internal URL (local network bound), so that it doesn't go through the internet.

### Please describe the actual behaviour

It looks like datapusher uses public CKAN url. So datapusher goes through public interface while it's faster to just use 127.0.0.1:5000.

### Suggestions

Either make custom ckan url setting for datapusher:

`ckan.datapusher.ckan_url = http://127.0.0.1:5000/`

Or make a general purpose internal ckan url setting:

```
ckan.site_url = 'https://data.mycity.com'
ckan.private_site_url = 'http://127.0.0.1:5000'
```

**Comment by Vanuan** [comment]
Ok, the issue is much deeper than that. It looks like the url of the resource file is stored in the database. So it depends on what the `ckan_url` was at the time it was uploaded. That's not very flexible :(

It means that whenever you migrate to another domain you have to run some script which replaces ckan url all over the database.

**Comment by Vanuan** [comment]
Yet another consequence is that datapusher can only store published datasets.

**Comment by Vanuan** [comment]
The last sentence is not true, as it looks like CKAN passes on some auth token to datapusher

**Comment by mattfullerton** [comment]
This got discussed before and @amercader proposed a solution:
https://github.com/ckan/datapusher/issues/83#issuecomment-151121100

**Comment by terchris** [comment]
Workaround is to put ckan host name in the hosts file.

**Comment by spikeheap** [comment]
Hi @terchris, using the hosts file isn't a great workaround, because it means each host machine needs to be customised to allow the service to be run, rather than encapsulating the configuration within the Docker configuration. 

Adding `ckan.datapusher.ckan_url` and falling back to `ckan.site_url` feels like it silos the additional changes to the datapusher plugin (CKAN-side), but adds a significant amount of flexibility.

**Comment by amercader** [comment]
The real solution to this is implement the DataPusher as a simple internal background job using @torfsen's [new library](http://docs.ckan.org/en/latest/maintaining/background-tasks.html) and drop the standalone HTTP service that so many issues causes. All interactions would be then made via internal action calls.

In the meantime, if anyone has time to work on a PR that adds that introduced a config option for an alternative internal URL I'd be happy to review.
