### ISSUE TITLE
PluginNotFoundException: my_theme

### ISSUE THREAD

**Issue by gallexme** [ckan/ckan#4028]
### CKAN Version if known (or site URL)

2.7.2
### Please describe the expected behaviour
Plugin Should be Installed after
python setup.py develop

### Please describe the actual behaviour
it says its installs but ckan cant find it

### What steps can be taken to reproduce the issue? 
 . /usr/lib/ckan/default/bin/activate
python setup.py develop

###LOG INSTALL:

 /usr/lib/ckan/default/bin/python2.7 setup.py  develop
running develop
running egg_info
writing ckanext-my-theme.egg-info/PKG-INFO
writing namespace_packages to ckanext-my-theme.egg-info/namespace_packages.txt
writing top-level names to ckanext-my-theme.egg-info/top_level.txt
writing dependency_links to ckanext-my-theme.egg-info/dependency_links.txt
writing entry points to ckanext-my-theme.egg-info/entry_points.txt
reading manifest file 'ckanext-my-theme.egg-info/SOURCES.txt'
writing manifest file 'ckanext-my-theme.egg-info/SOURCES.txt'
running build_ext
Installing /usr/lib/ckan/default/lib/python2.7/site-packages/ckanext-my-theme-nspkg.pth
Creating /usr/lib/ckan/default/lib/python2.7/site-packages/ckanext-my-theme.egg-link (link to .)
ckanext-my-theme 0.0 is already the active version in easy-install.pth

###Apache Log:
[Fri Feb 16 17:23:59.722577 2018] [:error] [pid 2030] [remote 127.0.0.1:192] mod_wsgi (pid=2030): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Fri Feb 16 17:23:59.722606 2018] [:error] [pid 2030] [remote 127.0.0.1:192] Traceback (most recent call last):
[Fri Feb 16 17:23:59.722629 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/etc/ckan/default/apache.wsgi", line 9, in <module>
[Fri Feb 16 17:23:59.722685 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     application = loadapp('config:%s' % config_filepath)
[Fri Feb 16 17:23:59.722699 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Fri Feb 16 17:23:59.722729 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     return loadobj(APP, uri, name=name, **kw)
[Fri Feb 16 17:23:59.722741 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Fri Feb 16 17:23:59.722761 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     return context.create()
[Fri Feb 16 17:23:59.722772 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Fri Feb 16 17:23:59.722791 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     return self.object_type.invoke(self)
[Fri Feb 16 17:23:59.722802 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Fri Feb 16 17:23:59.722821 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Fri Feb 16 17:23:59.722833 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
[Fri Feb 16 17:23:59.722854 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     val = callable(*args, **kw)
[Fri Feb 16 17:23:59.722865 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 46, in make_app
[Fri Feb 16 17:23:59.722888 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     load_environment(conf, app_conf)
[Fri Feb 16 17:23:59.722899 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 99, in load_environment
[Fri Feb 16 17:23:59.722920 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     p.load_all()
[Fri Feb 16 17:23:59.722930 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
[Fri Feb 16 17:23:59.722951 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     load(*plugins)
[Fri Feb 16 17:23:59.722961 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in load
[Fri Feb 16 17:23:59.722980 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     service = _get_service(plugin)
[Fri Feb 16 17:23:59.722990 2018] [:error] [pid 2030] [remote 127.0.0.1:192]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 256, in _get_service
[Fri Feb 16 17:23:59.723024 2018] [:error] [pid 2030] [remote 127.0.0.1:192]     raise PluginNotFoundException(plugin_name)
[Fri Feb 16 17:23:59.723047 2018] [:error] [pid 2030] [remote 127.0.0.1:192] PluginNotFoundException: my_theme

**Comment by wardi** [comment]
try again without a "-" in your plugin name

**Comment by gallexme** [comment]
tried it with _ did also not work

**Comment by wardi** [comment]
you'll need to provide a link to your extension for us to help any further

**Comment by gallexme** [comment]
the extension works on a different ckan 2.7.2 server (also same centos, same python)
so i dont think its because of the extension itself
just that i missed some step/did one step wrong which broke everything
sadly the plugin is private :/

**Comment by gallexme** [comment]
https://stackoverflow.com/questions/22038591/ckan-plugins-core-pluginnotfoundexception-pages 
this person had the same problem, but he didnt got an working solutin too :/

**Comment by wardi** [comment]
If you can't share your code, please create and share a small example extension that also fails and describe all the steps that lead to the failure.

**Comment by gallexme** [comment]
the theme is stored here:
/usr/lib/ckan/default/src/ckanext-my_theme
setup.py
[ckan.plugins]
        my_theme=ckanext.my_theme.plugin:MyThemePlugin
    ''',

**Comment by gallexme** [comment]
@wardi 
Removed all Private Data etc..
https://github.com/gallexme/ckanffm_theme
cloned that into /usr/lib/ckan/default/src/

 cd ckanext-ffm_theme/
    python setup.py develop
    sudo service httpd restart

ckan production.ini contains: ffm_theme as plugin

**Comment by wardi** [comment]
I can load your example plugin fine, after fixing the setup.py syntax error. Did you try it yourself?

in your virtualenv from a python prompt can you run
```python
from ckanext.my_theme.plugin import MyThemePlugin
```

**Comment by gallexme** [comment]
from ckanext.ffm_theme.plugin import FFMThemePlugin
>>> FFMThemePlugin
<class 'ckanext.ffm_theme.plugin.FFMThemePlugin'>
YES

**Comment by wardi** [comment]
Can you load the example you provided? That's working for me.

**Comment by gallexme** [comment]
i get the same problem with my example

**Comment by wardi** [comment]
if it works from `paster serve` in your virtualenv then there's something different about your apache configuration or permissions that you'll need to investigate

**Comment by gallexme** [comment]
i found the problem \*_____\*
ckan didnt had execute access to that folder
/var/lib/ckan/default/resources & storage

but why didnt i got the real error message?

**Comment by gallexme** [comment]
EDIT:
no it did not fix the problem 
only my example theme suddenly worked
not the real theme im confused

**Comment by wardi** [comment]
`pkg_resources` is hiding the original error as we loop over the available entry points, so all we can do is raise PluginNotFound. We could add some text to that exception suggesting that the user check that the user has permission to import the module, but that's just one of many things that would cause the same error.

**Comment by gallexme** [comment]
@wardi 
so i just tried it as apache2 user
bash-4.2$ source /usr/lib/ckan/default/bin/activate
(default)bash-4.2$ 
(default)bash-4.2$ 
(default)bash-4.2$ python
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> FFMThemePlugin
<class 'ckanext.ffm_theme.plugin.FFMThemePlugin'>

i also checked if has full write/read accessto the datastorage :(

**Comment by Prashantguptanz** [comment]
@gallexme  Did you finally figured out what the issue was? I am having a similar situation where I have tried everything and it's just not working. Any help would be appreciated

**Comment by gallexme** [comment]
It was either that I didn't have write access to some directory, or because
selinux

Prashant Gupta <notifications@github.com> schrieb am Mo., 30. Juli 2018,
03:08:
