### ISSUE TITLE
psycopg2 install error

### ISSUE THREAD

**Issue by effdrums** [ckan/ckan#4043]
### CKAN Version if known (or site URL)
CKAN 2.7.2

Hi I'm following the installation process and I'm having trubles with psycopg2 when running 
`pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt`

with the error: 

```
 Error: could not determine PostgreSQL version from '10.2'
    Complete output from command python setup.py egg_info:
    running egg_info
```
I've tryied to install with version 10 of postgresql and with version 9.5 but in both cases the error appears.. 

I've seen some other posts and it's said that can be a psycopg2 bug, does someone had the same issue? 

Thanks!

**Comment by torfsen** [comment]
AFAIK this has been fixed in #3978.

**Comment by amercader** [comment]
@effdrums the fix for this is upgrading psycopg2:

```
pip install --upgrade psycopg2==2.7.3.2
```

That's the version currently in master (upcoming 2.8) but it should work just as fine in 2.7.

Please reopen if you have any further issues

**Comment by amercader** [comment]
We are not actally backporting the requirements change but adding it to the changelog si users affected can fix the issue.

**Comment by torfsen** [comment]
@amercader: Note that #3978 needed to do more than simply upgrading `psycopg2`, there were some issues w.r.t. DataStore. So simply upgrading `psyopg2` might not be a good idea.

**Comment by effdrums** [comment]
hey I've solved via https://stackoverflow.com/questions/48989301/error-could-not-determine-postgresql-version-from-10-2

I just changed the version of psycopg2 to older one
