### ISSUE TITLE
recaptcha v1 will stop working 2018-3-31

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4061]
### CKAN Version if known (or site URL)
All since 2.0ish

### The problem
Users will not be able to register, due to the re-captcha being switched off by Google on 2018-3-31.

Google's deprecation info: https://developers.google.com/recaptcha/docs/versions#v1

This affects those sites that:
* have setup recaptcha (i.e. registered with Google and [added their keys to the CKAN config](http://docs.ckan.org/en/latest/maintaining/configuration.html?highlight=captcha#ckan-recaptcha-publickey)). This is not part of the default CKAN install. Most installs only use the 'user' functionality for admins, so the impact should be limited.
* AND they use v1 of recaptcha. This is the default in the CKAN config, but Google deprecated v1 May 2016 and prevented new sites using it (I imagine it was the same time), so the issue only affects sites set-up before then.

### How to check if you have this problem
Show the relevant bits of your CKAN config:
```
grep recaptcha /etc/ckan/default/production.ini
```
IF `ckan.recaptcha.publickey` has a value (i.e. not blank or unset)
AND (`ckan.recaptcha.version = 1` OR `ckan.recaptcha.version` is blank or unset)
THEN you need to upgrade to recaptcha 2 before 2018-03-31.

### Action
I think we should change the default to v2 and warn the community.

**Comment by amercader** [comment]
@davidread sounds good, do you want a submit a PR chaging the default? This we can backport. And then we can remove support completely for v1 in a separate PR.
