### ISSUE TITLE
error setup in window 8.1

### ISSUE THREAD

**Issue by vietlv** [ckan/ckan#4067]
###  When i run command line "pip install -r requirements.txt" error
![image](https://user-images.githubusercontent.com/6602895/36969612-960ed3da-2098-11e8-8f3b-d015945bdf56.png)[image]

### And error where run command paster
![image](https://user-images.githubusercontent.com/6602895/36969763-052398fa-2099-11e8-97e4-498888e10009.png)[image]

**Comment by smotornyuk** [comment]
1. You are using python3.*, which is not supported yet
2. Windows os is not supported officially, so you'll definitely run into a bunch of additional problems even after switching to python2. I would suggest you to try Linux or MacOS(Official docs are written for UbuntuLinux, so you  can start from it)

**Comment by vietlv** [comment]
Thanks, I using python version 3.6.1
