### ISSUE TITLE
datastore: test_configure.py is currently broken and disabled

### ISSUE THREAD

**Issue by cclauss** [ckan/ckan#4076]
Just recording this here for completeness:
* https://github.com/ckan/ckan/blob/master/ckanext/datastore/tests/test_configure.py#L10-L17

**Comment by iamarnavgarg** [comment]
Hello @amercader  can you guide on how to proceed further for this ?

**Comment by amercader** [comment]
@iamarnavgarg I think the best way forward is to remove this test class completely as it has never been used and it doesn't follow the rest of tests conventions
