### ISSUE TITLE
Tests fail when run locally

### ISSUE THREAD

**Issue by klikstermkd** [ckan/ckan#4087]
### CKAN Version if known (or site URL)
2.8 (master)

### Please describe the expected behaviour
When tests are run locally they should all pass.

### Please describe the actual behaviour
When tests are run locally some of them fail (16 in total). This is weird because on CircleCI currently they all pass on master. Tests were run on two different virtual envs in case one of those was somehow malformed. I ran the tests on `ckan` and `ckanext`. 

I also ran the failed tests individually and 13 of those passed and 3 still failed.

### What steps can be taken to reproduce the issue? 
Run the command:
```
nosetests --ckan --reset-db --nologcapture --with-pylons=test-core.ini ckan ckanext
```

List of failed tests:
- `ckan.tests.test_common.TestCommonG.test_flask_g_is_used_on_a_flask_request`
- `ckan.tests.test_common.TestCommonG.test_can_also_use_c_on_a_flask_request`
- `ckan.tests.test_common.TestCommonG.test_accessing_missing_key_raises_error_on_flask_request`
- `ckan.tests.legacy.logic.test_action.TestAction.test_26_resource_show`
- `ckan.tests.legacy.functional.test_activity.TestActivity.test_user_activity`
- `ckanext.webpageview.tests.test_view.TestWebPageView.test_view_shown_on_resource_page`
- `ckanext.textview.tests.test_view.TestTextView.test_title_description_iframe_shown`
- `ckanext.textview.tests.test_view.TestTextView.test_js_included`
- `ckanext.reclineview.tests.test_view.TestReclineView.test_title_description_iframe_shown`
- `ckanext.reclineview.tests.test_view.TestReclineMapView.test_title_description_iframe_shown`
- `ckanext.reclineview.tests.test_view.TestReclineGridView.test_title_description_iframe_shown`
- `ckanext.reclineview.tests.test_view.TestReclineGraphView.test_title_description_iframe_shown`
- `ckan.tests.test_common.TestCommonRequest.test_params_also_works_on_flask_request`
- `ckan.tests.legacy.functional.api.test_activity.TestActivity.test_delete_extras`
- `ckan.tests.legacy.functional.api.test_activity.TestActivity.test_add_tag`
- `ckanext.reclineview.tests.test_view.TestReclineViewDatastoreOnly.test_create_datastore_only_view`

If all of these failed tests are executed individually, 13 of those pass:
- `ckan.tests.test_common.TestCommonG.test_flask_g_is_used_on_a_flask_request`
- `ckan.tests.test_common.TestCommonG.test_can_also_use_c_on_a_flask_request`
- `ckan.tests.test_common.TestCommonG.test_accessing_missing_key_raises_error_on_flask_request`
- `ckan.tests.legacy.logic.test_action.TestAction.test_26_resource_show`
- `ckan.tests.legacy.functional.test_activity.TestActivity.test_user_activity`
- `ckanext.webpageview.tests.test_view.TestWebPageView.test_view_shown_on_resource_page`
- `ckanext.textview.tests.test_view.TestTextView.test_title_description_iframe_shown`
- `ckanext.textview.tests.test_view.TestTextView.test_js_included`
- `ckanext.reclineview.tests.test_view.TestReclineView.test_title_description_iframe_shown`
- `ckanext.reclineview.tests.test_view.TestReclineMapView.test_title_description_iframe_shown`
- `ckanext.reclineview.tests.test_view.TestReclineGridView.test_title_description_iframe_shown`
- `ckanext.reclineview.tests.test_view.TestReclineGraphView.test_title_description_iframe_shown`
- `ckan.tests.test_common.TestCommonRequest.test_params_also_works_on_flask_request`

But these 3 still fail:
- `ckan.tests.legacy.functional.api.test_activity.TestActivity.test_delete_extras`
- `ckan.tests.legacy.functional.api.test_activity.TestActivity.test_add_tag`
- `ckanext.reclineview.tests.test_view.TestReclineViewDatastoreOnly.test_create_datastore_only_view`

I guess somehow the execution of tests affects the rest of the tests, that's why most of them pass when run individually.

Any insight on what could be the reason for this?

**Comment by kmbn** [comment]
I'm closing this in favor of #4088, where most of the discussion about failing local tests has taken place.
