### ISSUE TITLE
Test failures in master in a fresh CKAN install

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4088]
Brand new virtualenv, fresh CKAN source install:

```
nosetests --nologcapture --with-pylons=test-core.ini -v ckan ckanext
```

gives:

```
----------------------------------------------------------------------
Ran 2511 tests in 1069.050s

FAILED (SKIP=10, errors=11, failures=14)


CKAN_SQLALCHEMY_URL in the env takes precedence over CKAN_DB ... ERROR
Setting an env var from the whitelist will set the appropriate option ... ERROR
ckan.tests.test_common.TestCommonRequest.test_params_also_works_on_flask_request ... ERROR
ckanext.reclineview.tests.test_view.TestReclineGraphView.test_title_description_iframe_shown ... ERROR
ckanext.reclineview.tests.test_view.TestReclineGridView.test_title_description_iframe_shown ... ERROR
ckanext.reclineview.tests.test_view.TestReclineMapView.test_title_description_iframe_shown ... ERROR
ckanext.reclineview.tests.test_view.TestReclineView.test_title_description_iframe_shown ... ERROR
ckanext.reclineview.tests.test_view.TestReclineViewDatastoreOnly.test_create_datastore_only_view ... ERROR
ckanext.textview.tests.test_view.TestTextView.test_js_included ... ERROR
ckanext.textview.tests.test_view.TestTextView.test_title_description_iframe_shown ... ERROR
ckanext.webpageview.tests.test_view.TestWebPageView.test_view_shown_on_resource_page ... ERROR
Test add tag activities. ... FAIL
Test deleted package extra activity stream. ... FAIL
ckan.tests.legacy.functional.api.test_package_search.TestPackageSearchApi1.test_05_uri_json_tags ... FAIL
ckan.tests.legacy.functional.api.test_package_search.TestPackageSearchApi1.test_06_uri_q_tags ... FAIL
ckan.tests.legacy.functional.api.test_package_search.TestPackageSearchApi2.test_05_uri_json_tags ... FAIL
ckan.tests.legacy.functional.api.test_package_search.TestPackageSearchApi2.test_06_uri_q_tags ... FAIL
ckan.tests.legacy.functional.api.test_package_search.TestPackageSearchApi3.test_05_uri_json_tags ... FAIL
ckan.tests.legacy.functional.api.test_package_search.TestPackageSearchApi3.test_06_uri_q_tags ... FAIL
Test user activity streams HTML rendering. ... FAIL
ckan.tests.legacy.lib.test_solr_search_index.TestSolrSearch.test_1_basic ... FAIL
ckan.tests.legacy.logic.test_action.TestAction.test_26_resource_show ... FAIL
ckan.tests.test_common.TestCommonG.test_accessing_missing_key_raises_error_on_flask_request ... FAIL
ckan.tests.test_common.TestCommonG.test_can_also_use_c_on_a_flask_request ... FAIL
ckan.tests.test_common.TestCommonG.test_flask_g_is_used_on_a_flask_request ... FAIL
```
@klikstermkd @tino097 @gocemitevski are these the same failures you are getting when running the tests in master? Is someone else getting the same failures (or others , or none) in master?

Full output [here](https://gist.github.com/amercader/556be90fd7d0430fac8f0bfb936cb6c2).

As usual we know where to look for the culprit:

```
nosetests --nologcapture --with-pylons=test-core.ini -v ckan ckanext --exclude-dir=ckan/tests/legacy
```

This gives:

```
----------------------------------------------------------------------
Ran 1480 tests in 752.088s

FAILED (errors=1)
```

Full output [here](https://gist.github.com/amercader/6f09981eb2f3109f45f2c9e0e2ac2c99). There is still a failure, a max recursion level that might still be an issue, but probably a separate one (related to streaming?)
The thing that makes these failures so frustrating to fixis that the tests work on CircleCI and when you try to run the individual tests that are failing they pass!

Why this is happening? Some of the legacy tests are badly written and they rely on results of other tests or modify the state (config, global objects, DB...) without cleaning after themselves on teardown. So the actual order in which tests are run matters. In CircleCI we are splitting the whole test suite in 4 containers so we are not hitting these issues.

Some change in master (we don't know how recently) triggered a change in the output / state of the bad legacy tests which then affects the other.

Things we can try:
* See how far we need to go to find tests passing in master
* Try excluding different combinations of legacy tests until the failing tests pass
* Remove / replace as many as possible of the legacy tests that so much trouble have caused us

**Comment by klikstermkd** [comment]
@amercader I created an issue where I explain basically the same issue #4087 

As you said, it might have to do with running the tests in multiple containers on CircleCI.

**Comment by tino097** [comment]
My results:

```
----------------------------------------------------------------------
Ran 2428 tests in 866.249s

FAILED (SKIP=10, errors=61, failures=6)

```
Full error output [here](https://gist.github.com/tino097/f56cb264687bf1de9fd7d991320097e9)

**Comment by tino097** [comment]
These three tests are failures with full test run and started separately

```
ckan.tests.legacy.functional.api.test_activity.TestActivity.test_delete_extras
ckan.tests.legacy.functional.api.test_activity.TestActivity.test_add_tag
ckanext.reclineview.tests.test_view.TestReclineViewDatastoreOnly.test_create_datastore_only_view
```
First two are legacy test and could be moved or replaced with similar in the `test_api.py` controller tests

**Comment by tino097** [comment]
After fresh install 
FAILED (SKIP=5, errors=13, failures=3)

https://gist.github.com/tino097/bc2deb2f45ff2e59db5daeffe4a02e37

**Comment by tino097** [comment]
@amercader @wardi 
https://gist.github.com/tino097/997229b880a173109189a96a4a9ef4b8

this is the new run, same issues

**Comment by ThrawnCA** [comment]
> As you said, it might have to do with running the tests in multiple containers on CircleCI.

I've recently tried to create a GitHub Actions workflow for our fork, and I was able to still split the tests into four containers, but still encountered some of these errors.
