### ISSUE TITLE
CKAN flask errors after updating to 2.8.0a for security issues to do with jquery. CKAN will not load any pages or read jinja tags.

### ISSUE THREAD

**Issue by Invis1988** [ckan/ckan#4101]
### CKAN Version if known (or site URL)
2.8.0a

### Please describe the expected behaviour
I did the following commands on a CKAN 2.7.2 residing on CentOS using PGSQL 9.6 and SOLR with an APACHE backend running wsgi which was fully functioning:
`git fetch`
`git checkout master`
`git pull`
I then ran the following commands:
`pip install --upgrade -r requirements.txt`
`python setup.py develop`
`pip search-index rebuild -c development.ini`
`systemctl restart httpd`
Everything continued with no errors and CKAN was updated on my source installation.
Expected site to be running.
### Please describe the actual behaviour
Site is giving 500 Error when loading.
Server is now giving a 500 error and has many errors in the log to do with app.py, does not load templating and so the site fails to load all pages.
Logs:
See attached
[ckan log.txt](https://github.com/ckan/ckan/files/1798294/ckan.log.txt)

### What steps can be taken to reproduce the issue? 
Upgrade CKAN

**Comment by Engerrs** [comment]
Hi @Invis1988 From what I can see in your attached file, is that complain about {% endblock %} on 123 line, but from what I can see in [template](https://github.com/ckan/ckan/blob/master/ckan/templates/header.html) there only 103 lines... Also I've tried to reproduce this by following steps you are described and had no problems.
Check your header.html template in this directory, maybe you've got some custom code in it.

**Comment by amercader** [comment]
@Invis1988 as @Engerrs suggests this is syntax error on your template.
