### ISSUE TITLE
Login over HTTPS redirects to HTTP

### ISSUE THREAD

**Issue by Nimphal** [ckan/ckan#4129]
### CKAN Version if known (or site URL)
CKAN 2.7.2 (but present on master) running with Docker

### Please describe the expected behaviour
When running CKAN over HTTPS with a correctly specified CKAN_SITE_URL, users can login/logout without issue.

### Please describe the actual behaviour
When running over HTTPS and attempting to login/logout, the service hangs and then bails out. After investigation, it seems the current usage of repoze.who used for the user login does not support https. Closest I got to understanding the problem is this discussion https://groups.google.com/forum/#!topic/pylons-discuss/u_YCE-6rgkw 

I suspect most people who run CKAN over HTTPS don't run it through Docker and as a result have an nginx configuration that masks this problem. We are running it with Docker on an AWS stack and had not set up nginx. 

As a workaround we added a small nginx service that listens on a port and redirects all requests to the https equivalent. Then we made the Load Balancer redirect HTTP port 80 to this service. 

### What steps can be taken to reproduce the issue? 
Run CKAN with docker-compose over HTTPS

**Comment by nykc** [comment]
I am also experiencing this issue.

**Comment by myksymz** [comment]
Same here with ckan 2.8.2

**Comment by akariv** [comment]
Same here... @amercader where in the code should I start looking for the cause?

**Comment by amercader** [comment]
@akariv I'm afraid that this is handled at the repoze.who level. We are using and old plugin, repoze.who-friendlyform that might be a good place to fix this. We need to rewrite it or remove it anyway as part of the py3 migration (#4796). If everything else fails I suppose we could add the middleware shown on the mailing list discussion mentioned in the description.

**Comment by vmireles-swc** [comment]
Still experiencing this on 2.9. Is there any update on this issue?

**Comment by syats** [comment]
Still experiencing this in 2.9. Any updates? workarounds?

**Comment by frafra** [comment]
I run CKAN behind an HTTPS reverse proxy and I do not have such issue.
@syats Have you tried with the latest CKAN 2.9.5 with Python 3?

**Comment by Sheile** [comment]
We faced same problem in 2.9.5( [master at yesterday](https://github.com/ckan/ckan/commits/71a82c4b0) ) and Python 3.
I've created above PR to redirect to HTTPS after login with who-friendlyform.

Is there anyone who can check this fix for your environment?

**Comment by nykc** [comment]
Unfortunately, we have all moved on to different projects. Hoping this fix will help others who may need it however.
