### ISSUE TITLE
API Documentation update

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#4136]
### CKAN Version
2.5, 2.6, 2.7, 2.8

### Expected behaviour
**organization_show** and **group_show** got all param types set according to others API infromation.

### Actual behaviour
**organization_show** and **group_show** showing wrong **id** type and other params missing types.

### What steps can be taken to reproduce the issue? 
Go to CKAN API Documentation and check **organization_show** or **group_show** actions.

**Comment by Engerrs** [comment]
I also updated params for other API actions that had same problem or were missing types.

**Comment by amercader** [comment]
Fixed in #4137
