### ISSUE TITLE
Webservice instead of standard frontend

### ISSUE THREAD

**Issue by AppWerft** [ckan/ckan#4138]
### CKAN Version if known (or site URL)
python-ckan_2.7-xenial_amd64.deb

### Please describe the expected behaviour

After successful installation I see standard frontend.

### Please describe the actual behaviour
I see webservice page with link to help, /status shows me what I have aspected (the status)

### What steps can be taken to reproduce the issue? 
Standard installation following the receipt for package installation

**Comment by tino097** [comment]
@AppWerft is there anything in the ` /var/log/apache2/ckan_default.error.log ` 

or maybe you should check if the database is initialized 

` sudo ckan db init `

**Comment by AppWerft** [comment]
I have successful initialized the db. After this I have added password to solr and then I have added this creds to configuration. How can I use `sudo ckan db init` with password?
The error.log is empty. ;-(

**Comment by tino097** [comment]
maybe you should try to start and stop apache and ngnix again:
  ```
 sudo service apache2 restart 
 sudo service nginx restart 
```

**Comment by AppWerft** [comment]
Tanks, this was my first thought. ;-)
If I start `sudo ckan db init` then I see an auth error althought in `/etc/ckan/default/*.ini` I have an entry for it:
```
[app:main]
solr_user=solr
solr_password=Dam*******iss42838
```
`sudo -u postgres psql -l` gives me:
```
     Name     |    Owner     | Encoding |   Collate   |    Ctype    |   Access privileges   
--------------+--------------+----------+-------------+-------------+-----------------------
 ckan_default | ckan_default | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres     | postgres     | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0    | postgres     | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
              |              |          |             |             | postgres=CTc/postgres
 template1    | postgres     | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
              |              |          |             |             | postgres=CTc/postgres
```

**Comment by amercader** [comment]
Hi @AppWerft, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

I suggest attaching a screenshot of the page you are getting and an excerpt of the error log

Thanks!
