### ISSUE TITLE
 Ckan resource edit via interface does not work

### ISSUE THREAD

**Issue by brunoqs** [ckan/ckan#4139]
### CKAN Version 2.7.2
I need to send a new .csv file to a resource that is already created. 
When I send the file it is not updated in the data explorer, I upload the new file but the datapusher does not update it in the datastore..

**Comment by brunoqs** [comment]
I solved the error by changing the update time of the datapusher in prodution.ini:

**Comment by amercader** [comment]
Closing as it seems the issue was fixed, please reopen if otherwise.
