### ISSUE TITLE
Adding filter at resoruce preview doesn't work while site is setup with ckan.root_path param

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#4140]
### CKAN Version
2.6, 2.7, 2.8

### Expected behaviour
Filter at resources preview work fine.

### Actual behaviour
It doesn't return any data when choosing a field for filter.

### What steps can be taken to reproduce the issue? 
1.Setup you CKAN site using extra **ckan.root_path** param
2. Add datastore and datapusher to plugins list
3. Create a new resource with CSV format (should have data)
4. Go to resource page and try to add filter at the preview block

**Comment by Engerrs** [comment]
I added PR with fix to that issue.
Can this fix be backported also to earlier versions? 2.6, 2.7

**Comment by amercader** [comment]
Fixed in #4141
