### ISSUE TITLE
Plugin Extras

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#4147]
Extending #3072 to implement `plugin_extras` fields on:
* Users
* Groups and Organizations (same underlying model)
* Datasets
* Resources

`plugin_extras` is a JSON field that is not exposed through the user interface or API (by default.) It's intended as a generic way for plugins to attach data to Users, Groups, Organizations, Datasets and Resources. 

By convention each plugin will store its own data in a separate JSON object, e.g. `my_user.plugin_extras['funky_auth']` would be the place a `ckanext.funky_auth` extension could store its data related to `my_user`.

For API-level migration of data from one CKAN instance to another, sysadmin users may request `plugin_extras` data by passing `include_plugin_extras=true` to the appropriate `*_show` API, and `plugin_extras` values passed to `*_update` and `*_create` APIs will be accepted when called by a sysadmin user. By default (and for all other users) this key is ignored and not returned.

Plugin extras are **not** revisioned and **not** copied into activity records. Values stored are private and hidden to normal users.

Plugins may choose to expose values they store in `plugin_extras` and/or allow them to be updated from the API and front end by chaining actions or customizing validation rules, **not** through any new interface introduced by this change.

This PR only creates the `plugin_extras` fields to enable future plugins to do something actually useful, e.g. https://github.com/ckan/ideas-and-roadmap/issues/211

**Comment by torfsen** [comment]
I'd love to see the `plugin_extras` field on as many CKAN entities as possible. For example, I currently need a way to attach plugin-related extras to resource views (see also #2655).

Aside from the entities already mentioned by @wardi, universal support could include:

* Views
* Tags
* Relationships (but see #4212)
* Vocabularies
* Activities

Perhaps there is a way to implement this mechanism in some kind of "base  class" so that all current and future entities (in CKAN core and in extensions) are automatically supported?

**Comment by rufuspollock** [comment]
Repeating comment from https://github.com/ckan/ideas/issues/211 (naturally we have ended up with roughly same item in both ideas and here):

Would it not be better to store workflow related information in a table dedicated to workflow rather than adding stuff to the dataset object (or other core objects)? This creates a cleaner setup where the direction of dependency is better: the workflow system depends on dataset not the other way round (you aren't changing the dataset object because of the workflow system).

I note that where this started which was with User Extras it makes more sense #16  - though even there i would be concerned to limit the use of this (it should really be specific stuff added to the user and other extensions can create their own tables).

Overall I feel this is could be something of an anti-pattern - rather than extensions creating data in their own clean namespace they add directly or indirectly to the core objects.

**Comment by wardi** [comment]
there are a few problems with every extension adding tables to the ckan database:

- there's no clear place to create/remove the tables so it's up to the extension to add a cli for this
- the tables have FK to core ckan models causing trouble when we want to purge our models without being aware of all extensions
- tables and sql are harder to work with for developers used to json as part of the API
- more code is required in extensions to access and update custom sql data, making it more fragile
- separate sql tables can't be automatically tracked as changes in activities the way a simple json field can
- separate sql table can't be automatically exposed or updated with sysadmin-only API calls, preventing mirroring custom data across sites at the logic level (except for complete db cloning)

Also, it seems common that extensions need a very small amount of extra data added to the core models so retrieving that data as part of the same query will perform better than N extra queries to N tables for N extensions on every action.

**Comment by rufuspollock** [comment]
> - there's no clear place to create/remove the tables so it's up to the extension to add a cli for this

Can you clarify - and surely this issue shows up for adding extras (you have to add and remove them systematically right ...). This seems like a bit of analogy with schemaless debates https://martinfowler.com/articles/schemaless/

> - the tables have FK to core ckan models causing trouble when we want to purge our models without being aware of all extensions

But why would you want to purge core models (like actually delete the table)? Surely if you are doing that you can remove *all* tables ... And again, this seems like good hygiene.

> - tables and sql are harder to work with for developers used to json as part of the API

Which developers? Users of this info still read/write it via an API right? It's just a separate clean API.

> - more code is required in extensions to access and update custom sql data, making it more fragile

I'm a bit unclear - you mean to create the table in the first place? Isn't a good thing to make the developers be explicit about their schema and its behaviour and give them full power.

> - separate sql tables can't be automatically tracked as changes in activities the way a simple json field can

You mean you want a way to add to add to audit log on events ... One can (and maybe should) have a simple core API for event logging and not rely on it being implicit.

> - separate sql table can't be automatically exposed or updated with sysadmin-only API calls, preventing mirroring custom data across sites at the logic level (except for complete db cloning)

You have the table and a wrapper logic function to expose via API (no?).

To be clear I'm proposing extensions if they have custom data have their own table and their own *API*.

**Comment by Zharktas** [comment]
Purging in this context is referring to API calls like purge_dataset which removes single dataset from database. If there are foreign keys referring the dataset in tables created by extensions, it deletion would fail. 

There already are quite significant performance issues with models that are not in solr like groups and organizations, for example calling organization_list with extras for a 1000 organizations, actually call organization_show 1000 times and it does sql queries some tens of thousands of times with lazy loading things with SqlAlchemy. I wouldn't want to add an interface or api which would add more queries to core models and slow thing down even more.

Your example of having own tables for extension and api would not solve this as the developer would still need to fetch all organizations and then add extensions things from database to it.

**Comment by rufuspollock** [comment]
> Purging in this context is referring to API calls like purge_dataset which removes single dataset from database. If there are foreign keys referring the dataset in tables created by extensions, it deletion would fail.

OK, so there are two parts here:

* EITHER that is desired (i.e. there is a dependency that needs clearing out ...)
* OR deleting the dataset should delete associated dependencies ... in which case you probably just want to cascade the delete - see e.g. https://docs.sqlalchemy.org/en/13/orm/cascades.html

> There already are quite significant performance issues with models that are not in solr like groups and organizations, for example calling organization_list with extras for a 1000 organizations, actually call organization_show 1000 times and it does sql queries some tens of thousands of times with lazy loading things with SqlAlchemy. I wouldn't want to add an interface or api which would add more queries to core models and slow thing down even more.

This sounds like an optimization concern leaking into a separation of concerns issue (and i'm not clear anyway that *this* particular item would make a difference performance wise one way or the other - it's a single join).

PS: when is one calling organization show for a 1000 items at one time as part of now functionality? (Is this scraping?)

> Your example of having own tables for extension and api would not solve this as the developer would still need to fetch all organizations and then add extensions things from database to it.

*Which* developer? A developer who is a client of the API or a developer writing an extension?

**Comment by Zharktas** [comment]
> This sounds like an optimization concern leaking into a separation of concerns issue (and i'm not clear anyway that _this_ particular item would make a difference performance wise one way or the other - it's a single join).

It's a single join when you write the sql yourself, but the currently recommended way is to use the api and get the added benefit of authorization and validation through it. It would require some query building interface for extensions to add joins to ckan queries themselves.

> PS: when is one calling organization show for a 1000 items at one time as part of now functionality? (Is this scraping?)

It's actually just really poorly implemented performance wise
https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L337..L347, we had issues with this when we need all our organizations and their translations which reside in extras. Usually we solve it by writing the sql ourselves and bypass the whole api.

> _Which_ developer? A developer who is a client of the API or a developer writing an extension?

I mean the developer who writes the extension. If there would be an interface which would allow adding things to core models from other tables, it would need interfaces to write high performance sql, Currently it's not supported.

**Comment by rufuspollock** [comment]
> It's a single join when you write the sql yourself, but the currently recommended way is to use the api and get the added benefit of authorization and validation through it. It would require some query building interface for extensions to add joins to ckan queries themselves.

I'm confused by whether we are talking about *clients* of the system or the developer building an extension? I'm certainly not suggesting that clients write SQL (they can't!?). For a developer of an extension surely they can use sqlalchemy and then expose their plugin data via an API ...

> It's actually just really poorly implemented performance wise
https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L337..L347, we had issues with this when we need all our organizations and their translations which reside in extras. Usually we solve it by writing the sql ourselves and bypass the whole api.

OK ... and it sounds like we want to solve that head on rather than allow that imperfection to deform other parts of the code (like this stuff).

> I mean the developer who writes the extension. If there would be an interface which would allow adding things to core models from other tables, it would need interfaces to write high performance sql, Currently it's not supported.

" If there would be an interface which would allow adding things to core models from other tables,"

This does not quite make sense to me - why do i need to add things from core models to other tables? Don't i use FKs?

**Comment by wardi** [comment]
@amercader as mentioned at the dev meeting today this might be the right place to continue discussion on this feature.

Names are really important for clear communication so here are some names we could use to disambiguate the types of additional data that are added to ckan datasets/resources/groups/orgs and the way they are stored:
1. "free-form extras" are the default interface for adding any key/string value to a dataset. no validation rules apply
2. "custom fields" are new fields added to a schema with IDatasetForm or ckanext-scheming. custom validation may apply
3. "package extras" are the current separate-table model-level implementation for storage of free-form extras *and* package-level custom fields (not resources)
4. "resource extras" is a free-form JSON field to store all resource values passed that are not part of a schema, no interface or validation is provided *and* this is used to store resource-level custom fields

Package extras and resource extras have a name conflict when both free-form extras and custom fields are used at the same time. This can lead to errors or silent overwriting of data stored.

## rename plugin extras to "plugin data"?

The "Plugin Extras" name of the feature described in this ticket is possibly something we should change. We have so many flavours of "extras" now that it's easy to get confused. I like @amercader 's suggestion to use the name "Plugin Data" instead, because this feature is really intended to allow storing arbitrary private-by-default json data on an object.

"Plugin Data" could be used as a place to store data from custom fields to solve the name conflict present with package extras and resource extras. Or as @tino097 said we could add an entirely separate json field for this purpose to avoid mixing private and public data in the same column.

I suggested using plugin data for custom field storage because I envisioned potentially allowing multiple plugins to add custom fields to objects in the future (like how ckanext-validation requires a few new fields at the resource level) and plugin data would be a way to keep each plugins' field data separated. This is especially applicable to user extras (which don't entirely exist yet).

Treating custom field storage as private also lets plugins store custom field data in a format that makes sense for them, not necessarily 1:1 with the public API version of the same fields. 

## plugin data in the API

Having private plugin data available from the API (for sysadmins) will make it easy to synchronize objects from one ckan instance to another, even when many plugins are being used. When extensions add their own database tables that link to ckan objects, tools to export data must be customized for each extension.
