### ISSUE TITLE
Datastore dump results are not the same as data in database

### ISSUE THREAD

**Issue by asarchami** [ckan/ckan#4150]
### CKAN Version if known (or site URL)
2.7.2

### Please describe the expected behaviour
Downloaded dataset is not consistent with the actual data! 

### Please describe the actual behaviour
We've upserted data using datastore api. The data is shown correctly in data explorer, Table view, API call or even querying postgres, But the data in downloaded csv file is different! Total number of records are the same but in csv we have random number of duplicates and missing data.

### What steps can be taken to reproduce the issue? 
Upsert data using API. Download the CSV file using URL. Filter and compare downloaded data and data shown in data explorer or table view.

**Comment by wardi** [comment]
Are you updating the data while dumping it by any chance? Dump is using row offsets which can change while data is being inserted.

**Comment by asarchami** [comment]
It's highly unlikely. update is done once a week. I can provide a link if you want to check.

**Comment by wardi** [comment]
a link to the resource and examples of the duplicate+missing rows would help for sure.

**Comment by asarchami** [comment]
Link to resource: https://data.illinois.gov/dataset/725state_employee_pay_hired_after_112011/resource/f86e27e4-67e4-4d50-9c52-a56c1159ace0
If you download the resource and filter the data using for example Agency = Human Rights you can see we have 145 records in CSV and we have 106 records in Data Explorer.

**Comment by wardi** [comment]
This does seem to be a pagination issue. We're requesting 25000 records at a time from the database and e.g. record `7301,...,2013,CORRECTIONS,SOUTHWESTERN IL..` appears at line 63899 and 88902 (25003 lines apart). We can force an ordering on `_id` here https://github.com/ckan/ckan/blob/master/ckanext/datastore/controller.py#L136

```python
    def result_page(offs, lim):
        return get_action('datastore_search')(None, {
            'resource_id': resource_id,
            'limit':
                PAGINATE_BY if limit is None
                else min(PAGINATE_BY, lim),
            'offset': offs,
            'sort': '_id',    # add this line
            'records_format': records_format,
            'include_total': 'false',  # XXX: default() is broken
        })
```
and we should stop seeing duplicates in the dump output

**Comment by asarchami** [comment]
Thanks, 
I'll test it out and let you know.

**Comment by asarchami** [comment]
I closed it for now since I cannot test it right now

**Comment by wardi** [comment]
Reopened because this one is serious. We need to fix & backport it even if you can't reproduce right now

**Comment by asarchami** [comment]
I updated to 2.7.4 and I still see the issue. Problem is not resolved

**Comment by wardi** [comment]
@asarchami so you're testing on a local copy (data.illinois is still running 2.7.2)? Are you still seeing repeated and missing rows in the dumped output?

**Comment by asarchami** [comment]
The link I provided above is on our production and its updated to 2.7.4. That specific resource I can't touch but if you download and filter it you can still see duplicates. I am also testing it in our QA and still having same issue.

**Comment by wardi** [comment]
https://data.illinois.gov/api/action/status_show is still showing 2.7.2, are you sure it's been updated?

**Comment by asarchami** [comment]
Problem is fixed. It was my update process! Thanks. It wasn't fully updated to 2.7.4

**Comment by wardi** [comment]
Huzzah!
