### ISSUE TITLE
Documentation for version 2.5 is unavailable on Read The Docs

### ISSUE THREAD

**Issue by Toshakins** [ckan/ckan#4151]
**Steps to reproduce**

1. Open CKAN documentation home page: http://docs.ckan.org/
1. Switch version to the 2.5 version(2.5.8 at the moment).

**Actual behaviour**
The server cannot find the page, and the browser shows 404 error.

**Expected behaviour**
Documentation for 2.5.x version is available, and the client receives status code 200.

**Comment by jqnatividad** [comment]
This also happens for 2.7.2
docs.ckan.org/en/ckan-2.7.2/api/

**Comment by Zharktas** [comment]
Missing 2.7.2 is by design as far as I know since 2.7.3 has been released, there was a long discussion about in #2946

**Comment by jqnatividad** [comment]
Thanks @Zharktas for the heads-up
cc @jguo144

**Comment by amercader** [comment]
Yes, the current way we have of linking to the docs using the tags is terrible as we break links and it's confusing. Also Read the Docs won't allow you to rebuild a tag if you change it, so we can not fix whatever issue is causing the build to fail in 2.5.8.
We decided that we would have a dedicated branch per minor version (`2.6`, `2.7`, `2.8`...) and that's what we will use to build the docs:

http://docs.ckan.org/en/2.6/
http://docs.ckan.org/en/2.7/

etc
