### ISSUE TITLE
There is no space between the drop-down box and the "Add to Group" button

### ISSUE THREAD

**Issue by JasminaPN** [ckan/ckan#4154]
### CKAN Version if known (or site URL)
https://beta.ckan.org/
ckan_version: "2.8.0b",

### Please describe the expected behaviour
There should be space between the drop-down box for adding group to dataset and the button "Add to group"

### Please describe the actual behaviour
The drop-down box for adding group to dataset and the button "Add to group" are merged. (please check the attached image)
![merged](https://user-images.githubusercontent.com/23238850/38029413-15a80cec-3296-11e8-8c7a-aa008cff86cf.PNG)

**Comment by gocemitevski** [comment]
@tino097 there is a regression after this PR. Because of the too generic CSS selector, other buttons of type `submit` are affected across CKAN. I will create another PR to fix the regression. Please reopen the issue if possible.

**Comment by gocemitevski** [comment]
The regression is visible on the Update Profile button.

![screenshot from 2018-04-03 15-27-41](https://user-images.githubusercontent.com/359855/38252098-92240c78-3753-11e8-9b54-4433cba37504.png)
