### ISSUE TITLE
500 Internal Server Error on Datastore

### ISSUE THREAD

**Issue by JasminaPN** [ckan/ckan#4155]
### CKAN Version if known (or site URL)
https://beta.ckan.org
ckan_version: "2.8.0b",
### Please describe the expected behaviour
After uploading a resource for dataset and on DataStore tab , by clicking on "Upload to DataStore" button there should be status: Complete.

### Please describe the actual behaviour
Steps to reproduce the issue:

1. Go to "Dataset" tab of the portal and click on the following dataset: "Test Dataset 28.03.2018" (https://beta.ckan.org/dataset/test-dataset-28-03-2018)
2. On the "Test Dataset 28.03.2018" page, click on "roads.csv" resource
3. On ''roads.csv" page - (https://beta.ckan.org/dataset/test-dataset-28-03-2018/resource/e76c5b42-5c81-4e41-8d49-610c9b77902c), click on "Manage" button
4. On "Manage roads.csv" page click "DataStore" tab and click on "Upload to DataStore" button.

**Result**: Error: CKAN DataStore bad response. Status code: 500 Internal Server Error. At: https://beta.ckan.org/api/3/action/datastore_create. 
HTTP status code: 500 
Response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete y... 
Requested URL: https://beta.ckan.org/api/3/action/datastore_create

**Comment by amercader** [comment]
Thanks @JasminaPN 

The log says:

```
   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
     context)
   File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
     cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) function populate_full_text_trigger() does not exist

```

This means that we need to run the [`datastore set-permissions`](http://docs.ckan.org/en/latest/maintaining/datastore.html#set-permissions) command on the datastore database to create these new functions (as mentioned in the [changelog](https://github.com/ckan/ckan/blob/master/CHANGELOG.rst#id1). 

@tino097 can you forward this to the relevant person on your side that can do this?

**Comment by tino097** [comment]
@amercader its on the way

**Comment by tino097** [comment]
this is fixed
