### ISSUE TITLE
Purging datasets from the trash re-activated some of them

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#4175]
### CKAN Version if known (or site URL)
2.6.4, but possibly applies to all versions including master since the [code in admin.py didn't change in the last ~6 years](https://github.com/ckan/ckan/blob/f711f5be380ae29aa9e64471412dc371d6a5b078/ckan/controllers/admin.py#L128).

### Please describe the expected behaviour
Purging datasets from the CKAN trash using the "Delete" button should be possible as described [in the Sysadmin guide](http://docs.ckan.org/en/ckan-2.6.5/sysadmin-guide.html#permanently-deleting-datasets).

### Please describe the actual behaviour
We had around 1000 datasets (with lots of revisions, several thousands each) in the trash and the page timed out after pressing the "Delete" button (at least we couldn't really tell what's going on). After some time, our client reported that previously deleted datasets are suddenly reappearing on the portal. This is really strange and currently our only explanation is the [code in the `trash()` method of the admin controller](https://github.com/ckan/ckan/blob/f711f5be380ae29aa9e64471412dc371d6a5b078/ckan/controllers/admin.py#L128). Since the purging is not running in a transaction, I think it's possible that, when something went wrong a previously deleted package is then active again.

### What steps can be taken to reproduce the issue?
1. Purge datasets from the trash using the "Delete" button
2. Provoke an error or a timeout during the purge
3. Check the database if any deleted packages are now active again

I think at least the documentation should be updated to not use the UI for large amounts of datasets and/or rewrite the purging using the `dataset_purge` Action API.

**Comment by tino097** [comment]
didnt managed to reproduce, as i was trying to kill the paster process. I can agree that this should be taken into reconsideration for improvement
