### ISSUE TITLE
Ckan License (Question)

### ISSUE THREAD

**Issue by tahaipek** [ckan/ckan#4176]
Hello,
There are points that i can't understand when examining CKAN's licenses.

[http://licenses.opendefinition.org/licenses/groups/ckan.json](http://licenses.opendefinition.org/licenses/groups/ckan.json)
[https://github.com/geosolutions-it/ckanext-ogdat/blob/master/ckan.json](https://github.com/geosolutions-it/ckanext-ogdat/blob/master/ckan.json)
[https://github.com/ckan/ckan/blob/d73326ad4beb3743cb4a347b15c04dace8c8654b/ckan/tests/model/licenses.v2](https://github.com/ckan/ckan/blob/d73326ad4beb3743cb4a347b15c04dace8c8654b/ckan/tests/model/licenses.v2)

What does "domain_content" mean? Where and how is it used?
What does "domain_data" mean? Where and how is it used?
What does "domain_software" mean? Where and how is it used?
What does "od_conformance" mean? Where and how is it used?
What does "osd_conformance" mean? Where and how is it used?

Sample Node:

```
{
    "domain_content": false, 
    "domain_data": true, 
    "domain_software": false, 
    "family": "", 
    "id": "ODC-BY-1.0", 
    "maintainer": "Open Data Commons", 
    "od_conformance": "approved", 
    "osd_conformance": "not reviewed", 
    "status": "active", 
    "title": "Open Data Commons Attribution License 1.0", 
    "url": "http://www.opendefinition.org/licenses/odc-by"
  }, 
```

**Comment by amercader** [comment]
For historical reasons, the licenses used in CKAN use the models stored in http://licenses.opendefinition.org/ I don't think CKAN actually uses any of these properties except the title and the URL.

If you are curious what the properties actually mean, I think `domain_*` tells you if this license is generally applied to content, data or software, `od_conformance` if the license conforms to the [Open Definition](https://opendefinition.org/), `osi_conformant` if the license is approved by the [Open Source Initiative](https://opensource.org/licenses).

Hope this helps and feel free to reopen if you find another issue with this.
