### ISSUE TITLE
API link in footer can lead to an error page if version is not latest

### ISSUE THREAD

**Issue by xellos866** [ckan/ckan#4185]
### CKAN Version if known (or site URL)

Error occoured and tested in:
* `2.7.1`
* `2.7.2`
* every version which is not explicitly available in the documentation

### Please describe the behaviour

At the Front-End in the Footer is an Link "CKAN-API" to the API-Documentation of Ckan. The Link is generated based on the version. If the version is not available (anymore) in the documentation there is noch fallback and an error page is shown:

`
Permission Denied
You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.
`

affected file: `ckan/templates/footer.html`

### Please describe the expected behaviour

The correct API documentation should be linked or there should be an fallback (i.e. the startpage of the documentation).

### What steps can be taken to reproduce the issue? 

In an installation of Ckan with an version which is no longer available in the documentation (i.e. `2.7.1`) klick on the Link "CKAN-API" in the footer.

greetings

**Comment by amercader** [comment]
@xellos866 you are right, the way doc links work is a mess. We are going to fix it in #4209 
cheers
