### ISSUE TITLE
After upgrading 2.6 to 2.7.3, data explorer view of csv resource fails.

### ISSUE THREAD

**Issue by tedstrauss** [ckan/ckan#4186]
### CKAN Version if known (or site URL)

`"ckan_version": "2.7.3"`
Just upgraded from 2.6

### Please describe the expected behaviour

Data explorer view of CSV resources should display a data table interface. 

### Please describe the actual behaviour

Clicking CSV resource link opens a: **Server Error - An internal server error occurred**

Apache error log:

`[Fri Apr 13 14:53:45.226977 2018] [:error] [pid 32479] [remote 127.0.0.1:35490] Error - <class 'ckan.logic.ValidationError'>: {'info': {'params': [()], 'statement': ['\\n            SELECT array_to_json(array_agg(j))::text FROM (\\n                SELECT  "_id" as "_id", "x" as "x", "y" as "y", "z" as "z"\\n                FROM "50fb5102-db98-45ce-ae6d-a5ddc5f636c5" \\n                  LIMIT 0 OFFSET 0\\n            ) AS j'], 'orig': ['function array_to_json(record[]) does not exist\\nLINE 2:             SELECT array_to_json(array_agg(j))::text FROM (\\n                           ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\\n']}, 'query': ['Invalid query']}`

### What steps can be taken to reproduce the issue? 

Upgrade CKAN 2.6 to 2.7.3, open a resource link to a csv type.

**Comment by tedstrauss** [comment]
```
> psql --version                                                                                                         
psql (PostgreSQL) 9.3.22  
```

**Comment by tedstrauss** [comment]
I ran `ckan db upgrade` at the end of the upgrade.
Are there other commands needed to run on the DB?

**Comment by wardi** [comment]
what does `select version();` return?

**Comment by tedstrauss** [comment]
And... the bug is fixed.
Postgresql server cluser upgraded from 9.1 to 9.3. 

```
# select version();
                                                   version                                 
-------------------------------------------------------------------------------------------
 PostgreSQL 9.3.22 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.0
(1 row)

```

References:
https://nixmash.com/post/upgrading-postgresql-9-1-to-9-3-in-ubuntu
https://gist.github.com/tamoyal/10303138
