### ISSUE TITLE
lib/mailer: The header "From" with UTF-8 name and ASCII address

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#4194]
### CKAN Version if known (or site URL)

2.6.5

### Please describe the expected behaviour

The "From" field (with UTF-8 name) in the header of emails sent by CKAN should be decoded and displayed by recipient's email client like:

From: "跨領域區域研究資料集" \<no-reply@data.depositar.io\>

### Please describe the actual behaviour

The "From" field shows:

From: "跨領域區域研究資料集 \<no-reply@d"ata.depositar.io\>

Note that the latter double quote is in the wrong place, which ruins the field and brakes some email authentication methods, such as DKIM.

### What steps can be taken to reproduce the issue? 

1. Set a site title with UTF-8 characters in SITE_URL/ckan-admin/config.
2. Let CKAN send a mail (invite someone via email, for example).

P.S. According the discussion in [this thread](https://stackoverflow.com/questions/41908883/how-to-add-an-utf-8-from-address-to-a-mail-mesage), we should assign the encoding to the name part and the address part respectively. I will submit a workable PR later.

**Comment by smotornyuk** [comment]
Original issue was caused by the mail client. At present, I'm getting this data passed to the mail client:
```
# Headers:
Content-Type :  text/plain; charset="utf-8"
MIME-Version :  1.0
Content-Transfer-Encoding :  base64
Subject :  =?utf-8?b?SW52aXRlIGZvciDot6jpoJjln5/ljYDln5/noJTnqbbos4fmlpnpm4Y=?=
From :  =?utf-8?b?6Leo6aCY5Z+f5Y2A5Z+f56CU56m26LOH5paZ6ZuGIDxoZXlAeW91Pg==?=
```

And it's decoded to:
```
# Headers:
Content-Type :  text/plain; charset="utf-8"
MIME-Version :  1.0
Content-Transfer-Encoding :  base64
Subject :  Invite for 跨領域區域研究資料集
From :  跨領域區域研究資料集 <hey@you>
```
