### ISSUE TITLE
ckanapi is deleting all resources under a dataset package when resource_update action is called

### ISSUE THREAD

**Issue by rp-21** [ckan/ckan#4214]
### CKAN Version if known (or site URL)
2.6

### Please describe the expected behaviour
ckanapi should update all resources under a dataset package when resource_update action is called

### Please describe the actual behaviour
ckanapi is deleting all resources under a dataset package when resource_update action is called

### What steps can be taken to reproduce the issue? 
python script using remoteCkan in ckanapi.
creating the resources if it is missing.
but when comes to updating using resource_update action 
it gives error "resource not found %s after all".
tried adding log statements in ckan no error there and it is working as expected using web-interface.
for both resource create and update actions.

**Comment by wardi** [comment]
This certainly doesn't sound like normal behaviour, I'm wondering if it's related to any extensions installed or other services connected to that instanced.

@rp-21 can you link to the script you're using and the site you're running this against? If you can't, then we'll need some way to reproduce the issue you describe (a minimal example would be perfect).

**Comment by rp-21** [comment]
Hi @wardi thanks for responding.

I Figured it out. it's all because of a small flag "**_ckan_phase**" sent in request_data. controller/package.py -> **_save_edit** method will actually add a flag **allow_partial_update : True** in context to preserve existing resources under the package to be updated based on **_ckan_phase** in data_dict. this flag in context then is used by the action accordingly.

since ckanapi is directly tapping into actions which is missing out the above flag logic. So i added the above flag logic also into action from the controller/package.py --> _save_edit method

**Comment by rp-21** [comment]
Hi @wardi thanks for responding.

I Figured it out. it's all because of a small flag "**_ckan_phase**" sent in request_data. controller/package.py -> **_save_edit** method will actually add a flag **allow_partial_update : True** in context to preserve existing resources under the package to be updated based on **_ckan_phase** in data_dict. this flag in context then is used by the action accordingly.

since ckanapi is directly tapping into actions bypassing controllers from it's flow which is missing out the above flag logic. So i added the above flag logic also into action from the controller/package.py --> _save_edit method
