### ISSUE TITLE
Link to API docs for any version other than current patch sends user to 404 version docs

### ISSUE THREAD

**Issue by camfindlay** [ckan/ckan#4226]
This line at
https://github.com/ckan/ckan/blob/fa3462e374f80fece9df702bc63d9b645b430173/ckan/templates/package/search.html#L53

Adds the particular version of CKAN into the URL, problem is for example if you're running ckan-2.6.4 following this link will send the user to a 404 page as the documention system doesn't retain past version paths. For example http://docs.ckan.org/en/ckan-2.6.4/api/ 

Suggestion that the link send the use to the minor point version of the docs rather than the patch level. 

This will maintain the link for 2.6.5, 2.6.6, 2.7.3, 2.7.4 and so on.

Happy to raise a PR if we can agree on an approach.

**Comment by tino097** [comment]
Please check #4209
you are welcome to contribute with PR

**Comment by amercader** [comment]
Thanks for flagging this @camfindlay, I added the changes as part of #4231
