### ISSUE TITLE
Reorder Resource View" button is mising on beta.ckan.org - bootstrap 2

### ISSUE THREAD

**Issue by JasminaPN** [ckan/ckan#4233]
### CKAN Version if known (or site URL)
beta.ckan.org - bootstrap 2

### Please describe the expected behaviour
"Reorder Resource View" button should be on Views page for the resource.

### Please describe the actual behaviour
Go to Dataset page of the portal
Create Dataset (metadata +add resource (data)
Click "edit" on the newly created resource
Go to "Views" tab from edit/resource
There should be a button "+Reorder Resources View", which is missing.

**Comment by tino097** [comment]
same as #3765
fix was introduced to #3604 but probably missed porting to bs-2
