### ISSUE TITLE
On resource view page, clicking the features: "fullscreen" and 'embed" is displayed like tabs

### ISSUE THREAD

**Issue by JasminaPN** [ckan/ckan#4239]
### CKAN Version if known (or site URL)

https://beta.ckan.org
### Please describe the expected behaviour
Clicking on "fullscreen" and "embed" should not be displayed as tabs.

### Please describe the actual behaviour

On resource view page, by clicking the "fullscreen" and 'embed" is displayed like tabs

**Comment by gocemitevski** [comment]
@JasminaPN the problem here is that the Fullscreen and Embed buttons are missing the `.btn-default` CSS class.
