### ISSUE TITLE
Search on datastore returns nothing

### ISSUE THREAD

**Issue by asarchami** [ckan/ckan#4244]
### CKAN Version if known (or site URL)
2.7.2

### Please describe the expected behaviour
I have a fairly large dataset ~75GB. We need to have a persistent URL to this resource and for that we cannot delete and recreate the resource. Right now we are using sql queries to write directly to database. We cannot use upsert because this dataset doesn't have a unique ID.  Every morning all records are deleted and ID is reseted and new data is inserted to database. Everything works except the search dialogue in "Data Explorer" or "Table" view returns nothing. If I use datastore API It works just fine but this way I loose persistent URL. We are definitely doing something wrong.  

### Please describe the actual behaviour
Search return nothing

### What steps can be taken to reproduce the issue? 
delete all records from datastore database and insert new data into it.

**Comment by wardi** [comment]
You need your `_full_text` column populated with data for the datastore search to work. In CKAN 2.7 its data is created from within `datastore_upsert`, so you'll need to use the API for loading your data (`method=insert`) or populate `_full_text` from your SQL.

CKAN 2.8 comes with a trigger for loading `_full_text` data that does this job instead. If you can upgrade to 2.8 then you should be able to load your data with the SQL you already have and let the trigger create the `_full_text` data.

**Comment by asarchami** [comment]
Thanks. I think we can move to 2.8.

**Comment by asarchami** [comment]
How do you use `_full_text`. How can I update my data to use postgres full text search?

**Comment by wardi** [comment]
no, if the datasets already exist you can just run the datastore set-permissions command (as it says in the upgrade docs)

If your tables are currently missing values in their _full_text columns you'll need to call the `datastore_run_triggers` action to force an update.

**Comment by asarchami** [comment]
Thanks
