### ISSUE TITLE
User login no longer times out after installation of CKAN LDAP plugin

### ISSUE THREAD

**Issue by ply112** [ckan/ckan#4246]
### CKAN Version if known (or site URL)
2.6.1

### Please describe the expected behaviour
User logins on CKAN should time out in accordance to the time-out parameter set in the configuration file.  After the installation of the CKAN LDAP plugin, we expect the user login to time-out accordingly.

### What steps can be taken to reproduce the issue? 
User logs in and the account is never timed out.

### Please describe the actual behaviour
After the installation of the CKAN LDAP plugin, user logins no longer time out even though the time-out parameter in the configuration file remained unchanged.

**Comment by amercader** [comment]
@ply112 Do you mean the [`who.timeout`](http://docs.ckan.org/en/2.8/maintaining/configuration.html#who-timeout) setting? If this is working in a plain CKAN install but not with the LDAP extension enabled please open an issue in the [ckanext-ldap](https://github.com/NaturalHistoryMuseum/ckanext-ldap) repo. Thanks!
