### ISSUE TITLE
Installation instructions for 2.7.4 actually install 2.7.3

### ISSUE THREAD

**Issue by WterBerg** [ckan/ckan#4255]
### CKAN Version if known (or site URL)
2.7.4

### Please describe the expected behaviour
The installation instructions for CKAN version 2.7.4 mentions and installs CKAN version 2.7.4

### Please describe the actual behaviour
Following the 'Install CKAN from source' instructions the documentation still states that 2.7.3 is the latest stable version and the terminal command downloads CKAN 2.7.3 (http://docs.ckan.org/en/2.7/maintaining/installing/install-from-source.html#install-ckan-into-a-python-virtual-environment Step C).

The chapter 'Installing CKAN from package' correctly reference the 2.7.4 release.

### What steps can be taken to reproduce the issue? 

Follow the installation instructions via http://docs.ckan.org/en/2.7/maintaining/installing/install-from-source.html#install-ckan-into-a-python-virtual-environment

**Comment by amercader** [comment]
Ups, thanks for flagging @WterBerg , we'll fix this asap

**Comment by WterBerg** [comment]
Something changed and all versions of the installation instructions now point to the latest stable ( 2.8.0 ). Is this intentional? I would expect the instructions for CKAN 2.6.6 to install CKAN 2.6.6.

**Comment by amercader** [comment]
No, @WterBerg this is not working as expected, there is a problem with the variables being used in the docs. As you say they should display the latest patch release for that minor version (ie 2.6.6). We need to fix this.

**Comment by amercader** [comment]
@tino097 can you add this to your list? one of the variables set in `doc/conf.py` probably needs to be cahnged to use the branch that the docs are on rather than the latest one.
