### ISSUE TITLE
after restart of docker package_list and package_search give different result

### ISSUE THREAD

**Issue by vicding-mi** [ckan/ckan#4259]
http://ckan:5000/api/3/action/package_list gives different result than http://ckan:5000/api/3/action/package_search?q=organization:org_test
When the search on all the organisations returning nothing, the package_list should return nothing as well. But it is not the case. 

### CKAN Version if known (or site URL)
2.9.0a

### Please describe the expected behaviour
After restart of the docker images, datasets persist. Expecting to see them in organization . 

### Please describe the actual behaviour
Either datasets totally removed or not removed at all (should see them in the organization they belong to)

### What steps can be taken to reproduce the issue? 
start docker images, create datasets within organization and restart docker.

**Comment by wardi** [comment]
Sounds like the solr image is being wiped when you restart. @vicding-mi would you try adding a volume for solr to https://github.com/ckan/ckan/blob/master/contrib/docker/docker-compose.yml and see if that helps for your configuration?

**Comment by vicding-mi** [comment]
I added a volume, but the problem was still there. And there is another issue, not sure if I can mention it here or better start another thread. I will briefly mention anyway. 

When I try to click on one of the organizations (like organization_test_1) I get 500 error. Please see the screenshot below
<img width="303" alt="screen shot 2018-05-23 at 18 49 46" src="https://user-images.githubusercontent.com/31689867/40439065-239df9ec-5eba-11e8-96e8-b71093c27299.png">

The message in the error log is 
`File '/usr/lib/ckan/venv/src/ckan/ckan/controllers/organization.py', line 29 in _update_facet_titles
  facets = plugin.organization_facets(
AttributeError: 'FacetPlugin' object has no attribute 'organization_facets'`

**Comment by wardi** [comment]
I think this is a problem with your particular set-up. reindexing your datasets with `paster search-index rebuild` might help.

To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.
