### ISSUE TITLE
"New view" button does not work

### ISSUE THREAD

**Issue by klikstermkd** [ckan/ckan#4260]
### CKAN Version if known (or site URL)
2.8

### Please describe the expected behaviour
If the portal is in Bootstrap 2 mode, the "New view" button located in the "Views" tab for a resource, when clicked it should give a list of possible views to create.

### Please describe the actual behaviour
If the portal is in Bootstrap 2 mode, the "New view" button located in the "Views" tab for a resource, when clicked it does not give a list of possible views to create. Instead in the browser console it shows the following error when clicked:

```js
jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #
    at Function.ga.error (jquery.min.js:2)
    at ga.tokenize (jquery.min.js:2)
    at ga.select (jquery.min.js:2)
    at Function.ga [as find] (jquery.min.js:2)
    at r.fn.init.find (jquery.min.js:2)
    at new r.fn.init (jquery.min.js:2)
    at r (jquery.min.js:2)
    at i (jquery.fileupload.min.js:6)
    at HTMLAnchorElement.toggle (jquery.fileupload.min.js:6)
    at HTMLDocument.dispatch (jquery.min.js:3)
```

### What steps can be taken to reproduce the issue? 
In a CKAN 2.8 portal, make it to use Bootstrap 2 by setting `ckan.base_templates_folder` to `templates-bs2` and `ckan.base_public_folder` to `public-bs2` in the config file. Then create a resource. Go to the "Manage" page for the created resource and then "Views" tab. Try to click the "New view" button.

**Comment by amercader** [comment]
@klikstermkd can you have a look and see if it's an easy fix?

**Comment by klikstermkd** [comment]
@amercader Yes I will.
