### ISSUE TITLE
Dataset license links from www.opendefinition.org are broken

### ISSUE THREAD

**Issue by jguo144** [ckan/ckan#4263]
### CKAN Version if known (or site URL)
2.7+

### Please describe the expected behaviour
When on a dataset page, clicking on the license link on the left should direct users to a page with an overview of the license.

### Please describe the actual behaviour
The urls for licenses from www.opendefinition.org are broken. For example the link for Creative Commons Attribution is http://www.opendefinition.org/licenses/cc-by.

### What steps can be taken to reproduce the issue? 
Click on a license link from www.opendefinition.org

**Comment by amercader** [comment]
Thanks @jguo144, that was a misconfiguration in the opendefinition.org domain, it is now fixed.
