### ISSUE TITLE
Broken links in CKAN footer

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#4264]
### CKAN Version if known (or site URL)
CKAN 2.7.2, https://datastore.landcareresearch.co.nz/

### Please describe the expected behaviour
At the foot of the page we have the standard About, CKAN API, and CKAN Association links, as we have always had.  Clicking on the CKAN API link should take you to documentation about the API, and the CKAN Association link to the CKAN website.

### Please describe the actual behaviour
The CKAN API link points to http://docs.ckan.org/en/ckan-2.7.2/api/, and this returns a message 
"Permission Denied
You don't have the proper permissions to view this page. Please contact the owner of this project to request permission."

The CKAN Association link points to http://www.ckan.org/, whcih retunrs a DNS error 502 Bad Gateway.
The page has moved to https://ckan.org/

### What steps can be taken to reproduce the issue? 
Correct the links to point to the updated locations/fix permission issues relating to documentation.

**Comment by amercader** [comment]
Hi @Aaron-M we have changed the documentation URLs to be stable across releases (ie http://docs.ckan.org/en/ckan-2.7.2/api/ -> http://docs.ckan.org/en/2.7/api/). If you upgrade to the latest patch release (2.7.3) the API link should be fixed.

http://www.ckan.org/ should now work as well

Feel free to reopen if there is still an issue.
