### ISSUE TITLE
Search - input- border color is overly specific in CSS (CKAN 2.8)

### ISSUE THREAD

**Issue by JasminaPN** [ckan/ckan#4273]
### CKAN Version if known (or site URL)
beta.ckan.org (CKAN 2.8)

### Please describe the expected behaviour
search - input- border color is overly specific in CSS. It should not have been overridden from .form-control
### Please describe the actual behaviour
Please check the following image:
![screenshot from 2018-06-05 14-17-53](https://user-images.githubusercontent.com/23238850/40976960-e8f0578e-68cf-11e8-91d9-b3c70bb854ca.png)

### What steps can be taken to reproduce the issue? 
Cc @gocemitevski

**Comment by rossjones** [comment]
@JasminaPN Is this something you're intending to submit a PR for?   If not do you have a way of describing what the fix is so that someone looking for a first contribution could take a look.

**Comment by gocemitevski** [comment]
@rossjones I will submit a PR. @JasminaPN is just reporting the issue.
