### ISSUE TITLE
Jinja2 Autoescape Default-Setting

### ISSUE THREAD

**Issue by stefina** [ckan/ckan#4279]
### CKAN Version if known (or site URL)
CKAN 2.8 and earlier

### Please describe the expected behaviour
Set autoescape explicitly to True.

### Please describe the actual behaviour
In a recent security audit/code review performed on one of our client installations the following findings are considered harmful due to potential Cross-Site-Scripting-Vulnerabilities.

Jinja2 sets autoescape to False by default. Consider setting the autoescape-setting to True to prevent potential Cross-Site-Scripting.
https://github.com/ckan/ckan/blob/3c7ad610cba7e9db8ea9a8467af516826773542d/ckan/pastertemplates/__init__.py#L28-L30

### What steps can be taken to reproduce the issue? 
See the referenced code-snippet above.

**Comment by TkTech** [comment]
The code segment you have linked is not at all involved with user-facing input or output and is used to generate on-disk template files from paster. The exclusion of safe strings is intentional.

**Comment by amercader** [comment]
@stefina To give more context, this template renderer is used when bootstrapping a CKAN extension with the command:

```
paster --plugin=ckan create -t ckanext ckanext-myext
```

The extension files are generated from static templates located in [this folder](https://github.com/ckan/ckan/tree/master/ckan/pastertemplates/template) and the autoescaping is needed to properly render them.

**Comment by stefina** [comment]
That makes sense to me! Thank you for clarifying that :)
