### ISSUE TITLE
Bug in resource description field

### ISSUE THREAD

**Issue by datagovlvlv** [ckan/ckan#4294]
"ckan_version": "2.6.0"

In catalog typing text in the data resource description box, for example "2017. data", the text is not displayed correctly - it appears as "annual data" in the data view, but in the file view as "Year 1 data"
_(You can see the pictures below)_

![2_data view](https://user-images.githubusercontent.com/39514280/41591798-6e64a674-73c3-11e8-901a-0ed2c72e0293.gif)
![3_file_view](https://user-images.githubusercontent.com/39514280/41591801-6e854802-73c3-11e8-9304-6d7b59fb178e.gif)
![1_description box](https://user-images.githubusercontent.com/39514280/41591811-72983008-73c3-11e8-9c4d-dde266785058.gif)

_At the suggestion of our IT consultants, we are asking you for solution for the CKAN "bug"_

**Comment by amercader** [comment]
@datagovlvlv The description field supports Markdown syntax. Markdown will interpret any number followed by a period (`.`) as an ordered list and create a list item starting with 1. Try removing or changing the period for another character.

Let me know if this makes sense.

**Comment by TkTech** [comment]
You can also escape the period. `1\.` will not create a list. Not terribly intuitive but it works.
