### ISSUE TITLE
BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery

### ISSUE THREAD

**Issue by rp-21** [ckan/ckan#4300]
### CKAN Version if known (or site URL)
2.6.*

### Please describe the expected behaviour
Any Page accessed must not have any error

### Please describe the actual behaviour
getting 500 internal server error occasionally.
on checking the logs below error is captured.
DBRunRecoveryError: (-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery')

### What steps can be taken to reproduce the issue? 
not sure what steps...

**Comment by TkTech** [comment]
Doesn't really have anything to do with CKAN, you're just noticing it on CKAN. Other programs on your system are likely failing. One of the many, many, many tools on your system that use the Berkley DB are failing. Could be IMAP, LDAP, yum, rpm, etc...

**Comment by rp-21** [comment]
i think so
using saml mode for ldap
below is the complete log 

[Thu Jun 21 11:49:13.932445 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406] 2018-06-21 11:49:13,931 ERROR [saml2.s2repoze.plugins.sp] Exception: (-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery')
[Thu Jun 21 11:49:13.932470 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406] Traceback (most recent call last):
[Thu Jun 21 11:49:13.932475 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/home/svc_datacatalog/data-catalog-src/data-catalog/ckan/default/src/pysaml2/src/saml2/s2repoze/plugins/sp.py", line 407, in _eval_authn_response
[Thu Jun 21 11:49:13.932478 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     self.outstanding_certs)
[Thu Jun 21 11:49:13.932481 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/home/svc_datacatalog/data-catalog-src/data-catalog/ckan/default/src/pysaml2/src/saml2/client_base.py", line 598, in parse_authn_request_response
[Thu Jun 21 11:49:13.932484 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     self.users.add_information_about_person(resp.session_info())
[Thu Jun 21 11:49:13.932487 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/home/svc_datacatalog/data-catalog-src/data-catalog/ckan/default/src/pysaml2/src/saml2/population.py", line 26, in add_information_about_person
[Thu Jun 21 11:49:13.932490 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     session_info["not_on_or_after"])
[Thu Jun 21 11:49:13.932493 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/home/svc_datacatalog/data-catalog-src/data-catalog/ckan/default/src/pysaml2/src/saml2/cache.py", line 114, in set
[Thu Jun 21 11:49:13.932496 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     if cni not in self._db:
[Thu Jun 21 11:49:13.932499 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/usr/lib64/python2.7/shelve.py", line 110, in __contains__
[Thu Jun 21 11:49:13.932502 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     return key in self.dict
[Thu Jun 21 11:49:13.932506 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/usr/lib64/python2.7/_abcoll.py", line 369, in __contains__
[Thu Jun 21 11:49:13.932509 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     self[key]
[Thu Jun 21 11:49:13.932512 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in __getitem__
[Thu Jun 21 11:49:13.932515 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
[Thu Jun 21 11:49:13.932518 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
[Thu Jun 21 11:49:13.932520 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     return function(*_args, **_kwargs)
[Thu Jun 21 11:49:13.932523 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]   File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in <lambda>
[Thu Jun 21 11:49:13.932526 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406]     return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
[Thu Jun 21 11:49:13.932529 2018] [wsgi:error] [pid 12134] [client 10.164.136.100:32406] DBRunRecoveryError: (-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery')
