### ISSUE TITLE
I am Unable to authenticate CKAN 2.7.2 using oauth2 on http

### ISSUE THREAD

**Issue by iamarnavgarg** [ckan/ckan#4301]
### CKAN Version if known (or site URL)
2.7.2

### Please describe the expected behaviour

I am using CKAN 2.7.2 .

I have added the following configurations in my development.ini file of ckan

ckan.oauth2.authorization_endpoint = https://account.lab.fiware.org/oauth2/authorize
ckan.oauth2.token_endpoint = https://account.lab.fiware.org/oauth2/token
ckan.oauth2.profile_api_url = https://account.lab.fiware.org/user
ckan.oauth2.client_id = xyz
ckan.oauth2.client_secret = xyz 
ckan.oauth2.profile_api_user_field = abc
ckan.oauth2.profile_api_mail_field =  abc@gmail.com 

Also, have exported the following while running ckan using paster serve :

export OAUTHLIB_INSECURE_TRANSPORT=True

Also, I have added an application (ckan provider) in fiware.lab also with callback URL = where the CKAN instance is running (i.e a private IP of 172.30.66.XX type running on port 5000)

### Please describe the actual behaviour
And when I click on Login,i get redirect to fiware lab login page and after logging in i get the following error

{"state": "eyJjYW1lX2Zyb20iOiAiL2Rhc2hib2FyZCJ9", "error": "mismatching_redirect_uri"} (HTTP 400)

NOTE : I get the same error while authenticating using WSO2 identity Server.
### What steps can be taken to reproduce the issue? 
install ckanext-oauth2
add it in plugins of ckan - development.ini
run ckan using paster serve /etc/ckan/default/development.ini

**Comment by amercader** [comment]
Hi @iamarnavgarg, this tracker is for issues with CKAN core itself. Please open an issue in the ckanext-oauth2 extension that you are using or in the Fiware software involved.
