### ISSUE TITLE
Is it possible to log in to CKAN from javascript ?

### ISSUE THREAD

**Issue by terchris** [ckan/ckan#4302]
### CKAN Version if known (or site URL)
any

### Please describe the expected behaviour
I'm making a javascript client that reads data from ckan using the ckan.js api. This works just fine when accessing data that does not need authentication.

In order to read private data and to update data I need to provide  the API key. But how to get the API key from my javascript client. I cant find a login API, is there one ?
 
 
### Please describe the actual behaviour
In the documentation it says that I find the API key by looking on the profile page. But the user of my javascript client will never log in to ckan.
> When calling an API function that requires authorization, you must authenticate yourself by providing your API key with your HTTP request. To find your API key, login to the CKAN site using its web interface and visit your user profile page." http://docs.ckan.org/en/latest/api/#authentication-and-api-keys

**Comment by torfsen** [comment]
You need to actively pass the appropriate API key to your JavaScript client (via a configuration file, a function parameter, etc.). There is no way to obtain it automatically. This is similar to other APIs (Twitter, etc.).

Your JS can then pass the API key along its requests using the `Authorization` HTTP header. How you set that header in your requests depends on which JS library you use for making the requests.

**Comment by torfsen** [comment]
Ah, I've missed that your using the [`ckan.js` client](https://github.com/okfn/ckan.js). Take a look at the example provided with that library:

```
// You can also provide an API key (for operations that require one)
var client = new CKAN.Client('http://my-ckan-site.com', 'my-api-key');
```
