### ISSUE TITLE
Hide everything unless logged in.

### ISSUE THREAD

**Issue by mystycs** [ckan/ckan#4306]
How would I go about only allowing domain/login to be visible and hiding everything else unless the user is logged in?

Basically unless use is logged in, redirect to the login page

**Comment by rossjones** [comment]
I'm sure someone will correct me if I'm wrong, but I don't recall an option to require a login to access the site that ships with CKAN.

You've probably got two options:

1. Write a http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IMiddleware plugin that checks if the user is logged in and does the right thing.

2. Implement http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IAuthFunctions in your plugin to overwrite https://github.com/ckan/ckan/blob/master/ckan/logic/auth/get.py#L17

Bonus points for option 2 as it finally shows a good use of the site_read auth check :) Unfortunately the site_read auth check is done in each controller, so I'm not sure if option 1 would actually be the better option here. That way we could remove the site_read auth check from lots of places (or rather not reimplement in the newer flask controllers).

Don't forget you may also want to allow users to access password reset functionality as well ;)

**Comment by amercader** [comment]
To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

I went for option 2 in [this extension](https://github.com/okfn/ckanext-unhcr) and I have to warn you it's not straight-forward, as there are many edge cases that are not covered, and some actions are not prepared for this case. But it works so you can have a look. The main bits are:

* Overriding the auth on all get functions: https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/auth.py (ignore `organization_create`)
* Page template override to show a login message if not logged in (there is a [helper](https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/helpers.py#L42) to whitelist pages like the login, pwd reset, error pages etc): https://github.com/okfn/ckanext-unhcr/blob/master/ckanext/unhcr/templates/page.html 

You can handle the second differently, with a redirect or however suits you. It's a bit hacky but hope it helps.

**Comment by mystycs** [comment]
That looks good, but its not working with 2.8 unfortunately.

**Comment by amercader** [comment]
The relevant bits should work fine in 2.7 so you can cherry-pick what you need.
