### ISSUE TITLE
Q: Dashboard functions in user controller?

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#4308]
### CKAN Version if known (or site URL)

2.8

### Please describe the expected behaviour

The user controller (ckan/controllers/user.py) still contains methods for rendering dashboard pages.  
Can these now safely be removed?

**Comment by amercader** [comment]
That's the place where they lived in the old controller. When moving it to a Flask blueprint @smotornyuk split the methods in two blueprints, `admin` and `user`. We'll keep the old controllers around for a version in case someone is extending them from their extensions but the whole file will eventually go, so no need to remove them for now.
