### ISSUE TITLE
Get error when running db init (internal server error)

### ISSUE THREAD

**Issue by mystycs** [ckan/ckan#4313]
I installed 2.7.3 from source and every time i run the paster db init production.in script i get the following error below:

This also causes an internal server error on my site.

Whats happening?

> 
> ./usr/lib/ckan/default/src/ckan$ paster db init -c /etc/ckan/default/production.ini
> Traceback (most recent call last):
>   File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
>     sys.exit(run())
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
>     invoke(command, command_name, options, args[1:])
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
>     exit_code = runner.run(args)
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
>     result = self.command()
>   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 333, in command
>     self._load_config(cmd!='upgrade')
>   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 306, in _load_config
>     self.site_user = load_config(self.options.config, load_site_user)
>   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 221, in load_config
>     load_environment(conf.global_conf, conf.local_conf)
>   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 99, in load_environment
>     p.load_all()
>   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
>     load(*plugins)
>   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 167, in load
>     plugins_update()
>   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
>     environment.update_config()
>   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 271, in update_config
>     plugin.configure(config)
>   File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 80, in configure
>     self.backend.configure(config)
>   File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1696, in configure
>     self._check_urls_and_permissions()
>   File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1583, in _check_urls_and_permissions
>     if not self._read_connection_has_correct_privileges():
>   File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1630, in _read_connection_has_correct_privileges
>     (read_connection_user, privilege)
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
>     return self._execute_text(object, multiparams, params)
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
>     statement, parameters
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
>     context)
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
>     exc_info
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb)
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
>     context)
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (ProgrammingError) role "datastore_ro@ckanpostgres" does not exist
>  "SELECT has_table_privilege(%s, '_foo', %s)" ('datastore_ro@ckanpostgres', 'INSERT')
>

**Comment by davidread** [comment]
Looks like you have the datastore plugin enabled in your .ini file, but you've not followed the datastore set-up instructions, well at least have not the createdb step or it doesn't match the ckan.datastore.read_url. See http://docs.ckan.org/en/latest/maintaining/datastore.html#create-users-and-databases

Closing, as this more likely user error than an issue with ckan.
