### ISSUE TITLE
Not able to upload xls dataset

### ISSUE THREAD

**Issue by ranjith-murugasamy** [ckan/ckan#4322]
Version: 2.8

### Please describe the expected behaviour
Dataset should be successfully uploaded through datastore

### Please describe the actual behaviour
Error: CKAN DataStore bad response. Status code: 409 CONFLICT. At: http://***********/api/3/action/datastore_create. 
HTTP status code: 409 
Response: {"help": "http://**********/api/3/action/help_show?name=datastore_create", "success": false, "error": {"field": ["Duplicate column names are not supported"], "__type": "Validation Error"}... 
Requested URL: http://***********/api/3/action/datastore_create

**Comment by rossjones** [comment]
"Duplicate column names are not supported"

If you have the option to resolve this with your source data, then that would be the quickest (but not best) fix.

See https://github.com/ckan/ckan/issues/2574 and https://github.com/ckan/ckan/pull/2576

**Comment by ranjith-murugasamy** [comment]
Thank you @rossjones . i removed the duplicate columns, but now i got a different error
Error: CKAN DataStore bad response. Status code: 409 CONFLICT. At: http://************/api/3/action/datastore_create. 
HTTP status code: 409 
Response: {"help": "http://************/api/3/action/help_show?name=datastore_create", "success": false, "error": {"records": ["function json_each_text(json) does not exist"], "__type": "Validation E... 
Requested URL: http://ckan-qa.intellectyx.com/api/3/action/datastore_create

**Comment by rossjones** [comment]
This might be a casting issue, can you confirm the output of this command (run in psql)

```
SELECT version();
SELECT * FROM json_each_text('{}');
```

**Comment by ranjith-murugasamy** [comment]
function json_each_text(unknown) does not exist. It looks like this is not supported in postgresql 9.2.*.
We are upgrading postgresql to 9.3. Will confirm the results. Thank you very much

**Comment by ranjith-murugasamy** [comment]
Thank you very much!
