### ISSUE TITLE
Datastore upload, json_each_text(json) does not exists

### ISSUE THREAD

**Issue by ranjith-murugasamy** [ckan/ckan#4323]
### CKAN Version if known (or site URL)
CKAN Version: 2.8
PostgreSQL: 9.2

### Please describe the expected behaviour
Dataset should be uploaded successfully

### Please describe the actual behaviour
Error: CKAN DataStore bad response. Status code: 409 CONFLICT. At: http://***********/api/3/action/datastore_create. 
HTTP status code: 409 
Response: {"help": "http://***********/api/3/action/help_show?name=datastore_create", "success": false, "error": {"records": ["function json_each_text(json) does not exist"], "__type": "Validation E... 
Requested URL: http://***********/api/3/action/datastore_create 

--
Ckan datapusher Logs
---
[Fri Jul 06 09:10:23.664532 2018] [:error] [pid 881] Determined headers and types: [{'type': u'text', 'id': u'test'}, {'type': u'numeric', 'id': u'date'}, {'type': u'numeric', 'id': u'completed'}, {'type': u'text', 'id': u'country'}, {'type': u'text', 'id': u'state'}]
[Fri Jul 06 09:10:23.668658 2018] [:error] [pid 881] Saving chunk 0
[Fri Jul 06 09:10:23.717149 2018] [:error] [pid 881] Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
[Fri Jul 06 09:10:23.717171 2018] [:error] [pid 881] Traceback (most recent call last):
[Fri Jul 06 09:10:23.717175 2018] [:error] [pid 881]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
[Fri Jul 06 09:10:23.717178 2018] [:error] [pid 881]     retval = job.func(*job.args, **job.kwargs)
[Fri Jul 06 09:10:23.717181 2018] [:error] [pid 881]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 411, in push_to_datastore
[Fri Jul 06 09:10:23.717184 2018] [:error] [pid 881]     records, api_key, ckan_url)
[Fri Jul 06 09:10:23.717202 2018] [:error] [pid 881]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 222, in send_resource_to_datastore
[Fri Jul 06 09:10:23.717205 2018] [:error] [pid 881]     check_response(r, url, 'CKAN DataStore')
[Fri Jul 06 09:10:23.717208 2018] [:error] [pid 881]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 137, in check_response
[Fri Jul 06 09:10:23.717211 2018] [:error] [pid 881]     request_url=request_url, response=response.text)
[Fri Jul 06 09:10:23.717222 2018] [:error] [pid 881] HTTPError

**Comment by rossjones** [comment]
This might be a casting issue, can you confirm the output of this command (run in psql)

```
SELECT version();
SELECT * FROM json_each_text('{}');
```

**Comment by rossjones** [comment]
@ranjith-murugasamy if this does turn out to be a Postgres version issue, could you close this issue after noting that it is ... thanks.

**Comment by rossjones** [comment]
@ranjith-murugasamy Assuming that this was indeed your problem, will close the ticket for you.
