### ISSUE TITLE
Returning incorrect number of records with datastore_search

### ISSUE THREAD

**Issue by asarchami** [ckan/ckan#4327]
### CKAN Version if known (or site URL)
2.7.4

### Please describe the expected behaviour
when using limit and offset in search using url number of records is always 10.

### Please describe the actual behaviour
Instead of showing requested number of records API only returns 10 records

### What steps can be taken to reproduce the issue? 
go to this url: https://data.illinois.gov/api/3/action/datastore_search?resource_id=1efec2db-59e0-4a8e-931b-46202936b0b3&offset=0&limit=100&q="License%20Type":"MEDICAL%20BOARD"

**Comment by kushagrasrivastva-NEC** [comment]
Try given below query as it is giving number of records in the table.
Below query will return all the number of fields included in the table and number of records present in the table.

_curl -X GET "http://'URL':5000/api/3/action/datastore_search?limit=1500&resource_id={RESOURCE_ID}"_

**Comment by wardi** [comment]
This seems to be working now, maybe it was an intermittent issue with the site? Please reopen if you can reproduce.

**Comment by wardi** [comment]
You need to format your `q` parameter as JSON if you're using a GET request. e.g:

https://data.illinois.gov/api/3/action/datastore_search?offset=1&resource_id=7f21c6b1-4401-4df4-a764-28e7ef3f9c90&q={%22License%20Type%22:%22MEDICAL%20BOARD%22}

**Comment by asarchami** [comment]
Thank you.
