### ISSUE TITLE
/groups on local machine creates infinite redirect

### ISSUE THREAD

**Issue by LukeTully** [ckan/ckan#4331]
### CKAN Version if known (or site URL)
2.6.3 - 2.*

### Please describe the expected behaviour
Visiting /group on my local machine allows me to view the list of groups in CKAN

### Please describe the actual behaviour
I described it [in this StackOverflow post](https://stackoverflow.com/questions/51237804/what-would-cause-an-infinite-redirect-on-the-group-route?noredirect=1#comment89497912_51237804) but will re-post the relevant bits here.

I'm running CKAN 2.6.3 locally on my mac. I've tried replicating this instance from a database dump on the remote instance. The rest of the site seems to work just fine, but hitting /group leads to an infinite redirect.

If I try and visit a specific group, I can view that just fine. Adding a group gives me the following stack trace.

`IntegrityError: (IntegrityError) duplicate key value violates unique constraint "group_name_key" DETAIL: Key (name)=() already exists. 'INSERT INTO "group" (id, name, title, type, description, image_url, created, is_organization, approval_status, state, revision_id) VALUES (%(id)s, %(name)s, %(title)s, %(type)s, %(description)s, %(image_url)s, %(created)s, %(is_organization)s, %(approval_status)s, %(state)s, %(revision_id)s)' {'description': u'', 'created': datetime.datetime(2018, 7, 8, 19, 57, 57, 297647), 'title': u'', 'approval_status': u'approved', 'is_organization': False, 'state': u'active', 'image_url': u'', 'revision_id': u'339d9b92-cfc3-4a0b-9bb7-cd8e53f15f62', 'type': u'group', 'id': 'a827e08b-9afd-4e3a-98c3-a78e4247b377', 'name': u''}`

Having followed a few troubleshooting paths, I've come up dry, except discovering that the initial request to /group serves a 301 redirect back to /group.

Other tidbits:
1. The remote instance does not have the same issue running under the paster httpserver
2. Locally served with the standard paster httpserver with paster serve /etc/ckan/development.ini

### What steps can be taken to reproduce the issue?
This might be pretty tricky, but installing CKAN locally on a mac, with solr6, redis, and running in dev mode with the paster server running on port 5000 should do it.

**Comment by amercader** [comment]
Hi @LukeTully, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [#ckan IRC channel](http://webchat.freenode.net/?channels=ckan) on freenode, where other developers may be able to help you.

Thanks!
