### ISSUE TITLE
2.8.1 release

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4342]
Scheduled 25th July 2018

### Starting up

- [x] Send email to CKAN announce / dev a week before
- [x] Update version on `dev-v2.8` branch to `2.8.1b`
- [x] Cherry-pick all issues marked as ["Backport 2.8.1" and "Backport Pending"](https://github.com/ckan/ckan/issues?utf8=%E2%9C%93&q=label%3A%22Backport+pending%22+label%3A%22Backport+2.8.1%22) to `dev-v2.8`

### Next few days

- [x] Pull translations on `dev-v2.8` branch
  - [x] `tx pull --all --minimum-perc=5 --force`
  - [x] Commit `*.po` files
  - [x] Compile `*.mo` files (`python setup.py compile_catalog`)
  - [x] Commit `*.mo` files
- [x] Build frontend (`paster front-end-build`), if there any changes commit them (there probably won't be)
- [x]  Update changelog in `dev-v2.8`
- [x] Test fixes for cherry-picked issues locally and on beta.ckan.org
- [x] Test that Debian package builds fine

### When the release is frozen

- [x] Update version on `dev-v2.8.1b` branch to `2.8.1`
- [x] Create tag `ckan-2.8.1`
- [x] Build final deb package

### Release day

- [x] Upload to https://packaging.ckan.org/
  - [x] Rename package to override existing 2.8 one
  - [x] Update md5sum
- [x] Upload to pypi (`pyhton setup.py sdist upload`)
- [x]  Announce
  - [x] ckan-announce and ckan-dev ([model](https://lists.okfn.org/pipermail/ckan-announce/2018-March/000035.html))
  - [x] Twitter
  - [x] ckan.org blog post (can be the same as the email announcement, changing the formatting)

### After release 

- [x] Cherry pick two i18n commit above to master
- [x] Update changelog in master with the 2.8.1 one
- [x] Merge `dev-2.8` into `2.8`
- [x] :beers:

**Comment by tino097** [comment]
@amercader please tweet , i didnt have access to the twitter account :)

**Comment by tino097** [comment]
@amercader there is a error in the tests on master when i cherry-picked the i18n commits. Whenever you have chance to reply please check it and suggest a fix for it
