### ISSUE TITLE
Site name may include characters that are invalid RFC822 email address

### ISSUE THREAD

**Issue by saper** [ckan/ckan#4343]
### CKAN Version if known (or site URL)

2.8.0

### Please describe the expected behaviour

Email from header should be displayed without issues in the mailer.

    From: Justice Reform in Ukraine <site@betterjustice.in.ua>

### Please describe the actual behaviour

An artificial semicolon is added by the mailer, probably because ":" should not appear in the email address.

    From: Council of Europe:  Justice Reform in Ukraine <site@betterjustice.in.ua> ;

Raw header looks deceptively okay:

    From: Council of Europe:  Justice Reform in Ukraine <site@betterjustice.in.ua> ;

### What steps can be taken to reproduce the issue? 

Set the site name to something containing colon.

Either the site name should be prohibited to contain certain characters
or email address should be quoted properly or another attribute should be created to describe email address.

Maybe the same UI widget could be used as for organisation/dataset names and their URLs
I find it pretty cool - it generates the address by itself in JavaScript but I can change it by hand
if I want (for example to keep it stable).

For this, `smtp.mail_from` config parameter should be moved to the ckan-admin UI.

**Comment by saper** [comment]
Nope, no PR from me at the moment

**Comment by boykoc** [comment]
As per PR#4549 I've tested this again in ckan-2.8.0 and am not able to replicate this issue.  I did the same steps as mentioned in my PR comment but using 2.8.0 instead of master. I recommend closing this issue for now an re-opening if the error comes up again for others. cc'ing @kmbn

**Comment by kmbn** [comment]
Thanks for following up on this, @boykoc. I'm closing the issue—if it comes up again for anyone, please re-open it.
