### ISSUE TITLE
Additional step in installation from source would be useful for beginners

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckan#4344]
### CKAN Version if known (or site URL)

2.9.0a

### Please describe the expected behaviour

According to the docs (http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html#install-and-configure-postgresql) PostgreSQL should list the existing databases after being installed

<pre>
    <strong>orphan:</strong>
    Check that PostgreSQL was installed correctly by listing the existing databases:
    
        sudo -u postgres psql -l
</pre>

(is **orphan:** an error message in this instance?)

### Please describe the actual behaviour

Running the commands in the docs gives:

    chris@u1:~$ sudo -u postgres psql -l
    psql: could not connect to server: No such file or directory
            Is the server running locally and accepting
            connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

It seems that PostgreSQL needs to be started after being installed with ``sudo service postgresql start`` before the above command can work. Can this be added to the docs?

(I tried to find it in the source, but 2.9.0a doesn't seem to be listed as a tag or a branch in the github repo, and the relevant rst file in the main branch also doesn't seem to correlate with 2.0.9a docs - what branch is it under?)

**Comment by wood-chris** [comment]
Equally, as a non expert postgreSQL user, it's just taken me a while to find out how to set the encoding of databases (running ``sudo -u postgres psql -l`` showed that the 3  default databases were in ``SQL_ASCII``) - it might be useful to include that this is all that is needed:

    sudo -u postgres psql
    psql (9.5.13)
    Type "help" for help.

    postgres=# initdb -E UTF8

**Comment by wood-chris** [comment]
```
postgres=# select version();
                                                     version
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.5.13 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609, 64-bit
(1 row)
```

**Comment by wood-chris** [comment]
As a (very late) comment, I should have probably said I was trying this on a Windows Subsystem. I've since tried on a standard linux ubuntu and it worked straight away!

**Comment by amercader** [comment]
Thanks @wood-chris, it looks like we need to make clear the instructions are tested on Ubuntu
