### ISSUE TITLE
Test error running locally

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4354]
Tests pass on CircleCI, but I get this test error on master locally:
```
$ nosetests --ckan --with-pylons=test-core.ini ckan/tests/logic/action/test_get.py -x
No handlers could be found for logger "ckan.lib.uploader"
.../usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2181: SAWarning: Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
  % method)
........................................................................................................................E
======================================================================
ERROR: ckan.tests.logic.action.test_get.TestTagShow.test_tag_show_for_vocab_tag
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/vagrant/src/ckan/ckan/tests/logic/action/test_get.py", line 1857, in test_tag_show_for_vocab_tag
    tag_in_dataset = dataset['tags'][0]
KeyError: 'tags'

----------------------------------------------------------------------
Ran 124 tests in 66.301s

FAILED (errors=1)
```
I can recreate it more quickly by just running these two tests:
```
nosetests --ckan --with-pylons=test-core.ini ckan/tests/logic/action/test_get.py:TestPackageAutocompleteWithDatasetForm.test_custom_schema_returned ckan/tests/logic/action/test_get.py:TestTagShow.test_tag_show_for_vocab_tag
```

Does anyone else have this problem or is it just me? Has any one got any ideas how to fix it?

@smotornyuk you were changing this test only recently: https://github.com/ckan/ckan/pull/4062/files#diff-c92cdbf4ff7391d90f31341452b90303 - maybe you can shed some light?

**Comment by davidread** [comment]
Probably better asked on SO: https://stackoverflow.com/questions/51444790/ckan-tests-error-keyerror-tags

**Comment by smotornyuk** [comment]
No, i have no similar issues. But giving a quick look,  noticed two things:
# https://github.com/ckan/ckan/blob/master/ckan/logic/action/create.py#L235  - at this point records in tag table and package_tag table already created, but package.get_tags() returns empty list - maybe we need to reset sql.session cache here
# https://github.com/ckan/ckan/blob/master/ckan/tests/logic/action/test_get.py#L1856 - if you update dataset creation here to something like `dataset = factories.Dataset(tags=[{'name': 'acid-rain'}])`(note absense of vocabulary_id key), tag appears in pkg_dict, but it will be another tag, so tag.id check few lines bellow will fail.

Unfortunately, i don't have time to investigate it deeper, at leat, during next week

**Comment by davidread** [comment]
Thanks for checking @smotornyuk.

I found the issue now! The test was missing a call to teardown_class() in the parent class, which only became a problem when it was recently changed it from teardown->teardown_class.

Opening until the PR is merged.
