### ISSUE TITLE
How to install/add a plugin in CKAN dockerfile

### ISSUE THREAD

**Issue by iamarnavgarg** [ckan/ckan#4373]
### CKAN Version if known (or site URL)
2.7.2

### Please describe the expected behaviour
I am unable to install this plugin https://github.com/conwetlab/ckanext-right_time_context
using dockerfile.

### Please describe the actual behaviour
So, if anyone can help me on how can i write these additional commands in dockerfile of ckan
 
git clone https://github.com/conwetlab/ckanext-right_time_context.git
cd ckanext-right_time_context
python setup.py develop

so that I use this plugin in ckan using docker

**Comment by amercader** [comment]
This is more of a Docker question, but you can install Python packages like CKAN extensions like this in your Dockerfile:

```
RUN pip install -e git+https://github.com/conwetlab/ckanext-right_time_context#egg=ckanext-right_time_context
```

Hope this helps
