### ISSUE TITLE
Datastore_upsert not allowing primary_key definition

### ISSUE THREAD

**Issue by shah-ronak** [ckan/ckan#4374]
Running CKAN 2.7.3 with Datstore - 

Using the CKAN API, I am running the datastore_create() function with the primary_key option specified. It tells me that the datastore resource is create successfully, and teh response includes the primary_key that has been created. 

Response from creating the dataset: 
`{
    "help": "http://site/api/3/action/help_show?name=datastore_create",
    "success": true,
    "result": {
        "resource": {
            "url": "_datastore_only_resource",
            "mimetype": null,
            "package_id": "package_test_name"
        },
        "primary_key": [
            "column"
        ],`

However, when I attempt to do a datastore_upsert later, it tells me that the _id field is needed. Is this intended behavior?

This is the response I am getting:

`{
    "help": "http://site/api/3/action/help_show?name=datastore_upsert",
    "success": false,
    "error": {
        "__type": "Validation Error",
        "key": [
            "fields \"_id\" are missing\n                        but needed as key"
        ]
    }
}`

**Comment by wardi** [comment]
I'm having trouble reproducing this. I'm able to create a datastore table with primary key and add records to it, e.g.
```sh
ckanapi action package_create name=pktest owner_org=testorg
ckanapi action datastore_create resource:'{"package_id":"pktest"}' primary_key="foo,bar" fields:'[{"id":"foo","type":"text"},{"id":"bar","type":"text"}]'
ckanapi datastore_upsert resource_id=<id-from-resource-create> records:'[{"foo":"aaa", "bar":"bbb"}]'
```
Please send the exact commands you're using when you see the failure.
