### ISSUE TITLE
Docker-compose: Datastore creation not working

### ISSUE THREAD

**Issue by solars** [ckan/ckan#4378]
Hi there, running into a problem with the docker-compose setup:

### CKAN Version if known (or site URL)

2.8.1

### Please describe the expected behaviour

I'm following: http://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html
where:
docker exec -it db psql -U ckan -f 00_create_datastore.sh
should setup the database

### Please describe the actual behaviour

docker exec -it db psql -U ckan -f 00_create_datastore.sh
returns:
./00_create_datastore.sh: No such file or directory

The Dockerfile seems to add the postgresql/docker-entrypoint-initdb.d directory
So I tried:
sudo docker exec -it db psql -U ckan -f docker-entrypoint-initdb.d/00_create_datastore.sh

However, this also cannot work because the command above already is a call to psql but the
file is a shellscript including a call to psql itself, resulting in:

psql:docker-entrypoint-initdb.d/00_create_datastore.sh:5: ERROR:  syntax error at or near "#!/"
LINE 1: #!/bin/bash

Is this a bug? I'm confused

### What steps can be taken to reproduce the issue? 

Just follow: http://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html
until:

3. a) docker exec -it db psql -U ckan -f 00_create_datastore.sh

Thanks for your help,
Christoph

**Comment by spikeheap** [comment]
Hi, and sorry for the slow response to this. This looks like a bug in the docs – the datastore DB is created automatically as part of the container initialisation. From a clean checkout of `master`:

```bash
> docker-compose up db
... (output truncated for brevity)
db            | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/00_create_datastore.sh
db            | CREATE ROLE
db            | CREATE DATABASE
db            | GRANT
... (output truncated for brevity)
```

I've filed #4488 to remove this instruction from the docs.
