### ISSUE TITLE
ie7-ie8 have many issues to display

### ISSUE THREAD

**Issue by flazx** [ckan/ckan#4381]
I have just installed the CKAN2.8 and it has many issues which ie7-ie8 not support quite well. And the recline view couldn't display under ie7-ie8 as well.

**What is the CKAN support plan for ie7 or ie8?**

**Comment by smotornyuk** [comment]
Hi, @flazx . We are using Bootstrap3 in >=2.8 and it doesn't provide support of ie<9 out of the box. If it critical for you, you portal can be customized(probably, via plugin) - you need to include some additional libraries for ie8 support - https://getbootstrap.com/docs/3.3/getting-started/#support-ie8-ie9 . As for ie7, i suppose, it would be quite a challenge, to fix all issues in it.

We are not supporting ie<11 anymore, as Microsoft has officially announced the end of support for these browsers a long time ago. We would appreciate if you provide some pull request for backward compatibility, but our main goal is evolving CKAN and we are trying not to couple to legacy unsupported software.

**Comment by flazx** [comment]
@smotornyuk thanks for your response. I got the CKAN IE support plan now.

And I have to use the Bs2 template and there are still some issues, but not big issues, I think I can resolve it by myself.
Thanks again for your great help!
