### ISSUE TITLE
Full URL of the resource stored in the DB

### ISSUE THREAD

**Issue by tino097** [ckan/ckan#4382]
### CKAN Version if known (or site URL)
2.6+
Reported in #4070 

### Please describe the expected behaviour
When editing resource metadata, we should store the filename in the database, at `resource` table `URL` column. 

### Please describe the actual behaviour
When editing resource metadata, full URL is saved in the database

### What steps can be taken to reproduce the issue? 
1.Go to edit resource page
2.Save the changes

I've tested of this occurs on edit dataset and the issue is not reproducible.It occurs only on edit resource.

This occurs because we are generating the full url on [reading](https://github.com/ckan/ckan/blob/master/ckan/lib/dictization/model_dictize.py#L110) the resource and it is stored as it in the DB on save

**Comment by amercader** [comment]
Here what's happening:

* When creating the resource, the uploader stores just the file name in the `url` field
* This is what gets stored in the database, by `ckan.lib.dictization.model_save.resource_dict_save()`

So far so good.

Now, when we add a new resource to the same dataset, or edit the existing resource:

* `resource_create` and `resource_update` call `package_show` internally to update the whole dataset dict with the new/updated resource and pass it to `package_update`.
* `package_show` (correctly) translates the single file name in `url` to a fully qualified URL so it can be displayed in the frontend or the API
* But we are passing the dict with fully qualified URLs to `package_update`, which will store them on the database

We need to strip the full URL and store just the file name again when storing resources (only for resources where `url_type=upload` of course!). We can do that:

1. At the [`model_save.resource_dict_save`](https://github.com/ckan/ckan/blob/master/ckan/lib/dictization/model_save.py#L16) level
2. At the  [`default_update_resource_schema`](https://github.com/ckan/ckan/blob/master/ckan/logic/schema.py#L61) level (validation)

Note that the creation of the fully qualified URL is done at the same level of 1 in [`model_dictize.resource_dictize`](https://github.com/ckan/ckan/blob/master/ckan/lib/dictization/model_dictize.py#L100) so perhaps it make sense to be consistent and do it there as well.
