### ISSUE TITLE
What is the tracking logic?

### ISSUE THREAD

**Issue by LingboTang** [ckan/ckan#4383]
### CKAN Version if known (or site URL)
I've been using it in both 2.6.6 and 2.8.1

### Please describe the expected behaviour
My expected behaviour is every time a user visited a particular package or resource, it will update the tracking summary.

### Please describe the actual behaviour
If a user kept himself/herself in one session, no matter how many times he/she views the package or resource, it only updates the tracking summary once. Also no matter how many times I download one resource, it only updates the tracking summary once. This tracking logic is also valid, but I can't find this design logic in the documentation here: http://docs.ckan.org/en/2.8/maintaining/tracking.html . Can someone help me verify that my understanding is correct?

*Update:*
I've tried to logout the user, clear browser cookie and session. When I login and updated the tracking with paster command, it didn't update the number of views for that package. So it feels like the tracking is per person wise?

### What steps can be taken to reproduce the issue? 
Enable the tracking in your *.ini config files and view a particular test package.
Use the `package_show()` API with `include_tracking=True` to check the tracking summary.

**Comment by smotornyuk** [comment]
There is a note in [docs](http://docs.ckan.org/en/2.8/maintaining/tracking.html#retrieving-tracking-data):

> Repeatedly visiting the same page will not increase the page’s view count! Page view counting is limited to one view per user per page per day.

And don't forget, that you also need to configure rebuilding of search index(but it's not related to the problem)

**Comment by LingboTang** [comment]
I see that, I'll close this issue now.

**Comment by LingboTang** [comment]
@smotornyuk Is tracking function able to tracking how many times has one data (actual resource under a package) been downloaded?

**Comment by jqnatividad** [comment]
@LingboTang, you may want to check https://github.com/ckan/ckanext-googleanalytics for that.

You may also want to check out http://tools.wprdc.org/analytics/wprdc-dashboard/ and https://github.com/WPRDC/WPRDC-dashboard cc @drw

**Comment by Gauravp-NEC** [comment]
@LingboTang , I have followed the doc: https://docs.ckan.org/en/2.7/maintaining/tracking.html#enabling-page-view-tracking and enabled page view tracking in CKAN v2.7.12. I am trying to get the tracking summary of dataset using package_show() API i.e., curl http://localhost:5000/api/3/action/package_show?id=[ ]&include_tracking=true , but tracking_summary is not included in the API response. How can I get the tracking_summary?
