### ISSUE TITLE
how to upload only excel and csv files to the upload folder

### ISSUE THREAD

**Issue by lilisasa** [ckan/ckan#4386]
I use ckan 2.8
i just need to grant access only to upload .csv and .xlsx files to my uploading folder. so what modifications should i do in the ckan directory?

**Comment by iamarnavgarg** [comment]
Can you please elaborate more about your concern ?

**Comment by amercader** [comment]
You can't limit the upload formats by default in CKAN. You could implement it customizing the file upload control to use the [`accept`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept) parameter or you probably can write a custom Uploader (but that would be more tricky probably)
