### ISSUE TITLE
Can groups and organizations have tags?

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#4388]
*This ticket is inspired by [a question on StackOverflow](https://stackoverflow.com/q/49638498/857390)*.

The documentation for several API functions related to groups and organizations list a `include_tags` option (e.g. [`organization_list`](http://docs.ckan.org/en/latest/api/#ckan.logic.action.get.organization_list)), but the [`organization_create`](http://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.create.organization_create) and [`group_create`](http://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.create.group_create) do not mention a corresponding `tags` option (in contrast to [`package_create`](http://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.create.package_create)). The output of, for example, `organization_show` does include a `tags` key, but in my experiment that is always empty. I also don't see a way to edit group or organization tags in the web UI. The web UI does show a list of tags for each organization, but as far as I can tell those are the tags of the datasets belonging to the organization. The [ORM model for groups](https://github.com/ckan/ckan/blob/05685a3aeda49d27213c5727e78068ffad248efd/ckan/model/group.py) (and organizations) also doesn't include a columns for tags.

My impression is that groups and organizations can't have tags. If that is the case, then the `include_tags` options should either be removed, or (if they are intended to return the tags of the datasets belonging to the group/organization) their documentation and implementation needs to be fixed (since I'm always getting empty tag lists).

If groups and organizations *can* have tags, then they should be configurable using the UI and the `_create`, `_patch` and `_update` API functions.

**Comment by DomDomHaas** [comment]
@smotornyuk Could at least the documentation be changed so to everyone as to figure it out by oneself?

**Comment by smotornyuk** [comment]
We've discussed it on the weekly meeting and decided to erase this feature completely in favor of custom fields. They can be provided by the group's schema modification

**Comment by DomDomHaas** [comment]
Okay. Am I correct to assume, that when I want all the datasets from an organization, I have to get the organization frist and then do a package_search with the organization id / name?

**Comment by smotornyuk** [comment]
Yes. You'll probably use `package_search?fq=owner_org:ORG_ID` or `package_search?fq=organization:ORG_NAME`
