### ISSUE TITLE
DataStore API does not find the resource to be deleted

### ISSUE THREAD

**Issue by s3lvatico** [ckan/ckan#4391]
I'm trying with filing a bug since I am at a loss about correctly using the DataStore API.

Using CKAN v 2.7

### Please describe the expected behaviour
The resource associated with a dataset is deleted

### Please describe the actual behaviour
The DataStore API call fails with the following response:
`{"help": "http://<le_hostname>/api/3/action/help_show?name=datastore_delete", "success": false, "error": {"message": "Not found: Resource \"04ae6ca6-cbe8-4696-98c7-09485e95b280\" was not found.", "__type": "Not Found Error"}}`

### What steps can be taken to reproduce the issue? 
- Create a new dataset and a new resource inside it
- Write down the UUID of the resource by opening the dataset, exploring the resource and looking at the resource UUID inside the resource URL, as in http://<le_hostname>/dataset/f17be53f-fe4f-4676-adc5-516a61ddb842/resource/**04ae6ca6-cbe8-4696-98c7-09485e95b280**/download/t-18810-1045_data_0.csv
- cross-check the correctness of the resource UUID by issuing an API call to `GET /api/3/action/package_show?id=f17be53f-fe4f-4676-adc5-516a61ddb842` 

```json
{
   "help": "http://<le_host>/api/3/action/help_show?name=package_show",
   "success": true,
   "result": {
      "license_title": "Creative Commons Attribution",
      ...
      "id": "f17be53f-fe4f-4676-adc5-516a61ddb842",
      ...    ^ I imagine this is the dataset's UUID
      "type": "dataset",
      "resources": [
         {
            "mimetype": "text/csv",
            "cache_url": null,
            "hash": "",
            "description": "",
            "name": "t-18810-1045_data_0",
            "format": "CSV",
            "url": "http://<le_host>/dataset/f17be53f-fe4f-4676-adc5-516a61ddb842/resource/04ae6ca6-cbe8-4696-98c7-09485e95b280/download/t-18810-1045_data_0.csv",
            ... ^ the aforementioned URL containing the resource's UUID
            "datastore_active": false,
            "cache_last_updated": null,
            "package_id": "f17be53f-fe4f-4676-adc5-516a61ddb842",
            "created": "2018-08-10T08:50:08.512313",
            "state": "active",
            "mimetype_inner": null,
            "last_modified": "2018-08-10T08:50:08.483044",
            "position": 0,
            "revision_id": "7d62d44a-98b3-49a0-89b3-ca10fc654a91",
            "url_type": "upload",
            "id": "04ae6ca6-cbe8-4696-98c7-09485e95b280",
            .......^ the resource's UUID?
            "resource_type": null,
            "size": 25
         }
      ],
      "num_resources": 1,
      "tags": [
         {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "test",
            "id": "cc82c587-decd-45b4-816c-adb87e151645",
            "name": "test"
         }
      ],
      "groups": [],
      "license_id": "cc-by",
      "relationships_as_subject": [],
      "organization": {
         "description": "the description",
         ...
         "approval_status": "approved"
      },
      "name": "t-18810-1045",
      "isopen": true,
      "url": "",
      "notes": "ST",
      "owner_org": "440692a8-c7ef-444e-9ad7-a0782c712470",
      "extras": [],
      "license_url": "http://www.opendefinition.org/licenses/cc-by",
      "title": "t-18810-1045",
      "revision_id": "7d62d44a-98b3-49a0-89b3-ca10fc654a91"
   }
}
```

- Issue an API call to delete the resource

`POST /api/3/action/datastore_delete HTTP/1.1`

(Authorization header is correctly set)

Request body: `{"resource_id":"04ae6ca6-cbe8-4696-98c7-09485e95b280","force":"True"}`

The response body is as follows

`{"help": "http://<le_host>/api/3/action/help_show?name=datastore_delete", "success": false, "error": {"message": "Not found: Resource \"04ae6ca6-cbe8-4696-98c7-09485e95b280\" was not found.", "__type": "Not Found Error"}}`

The call has been made either with an automation tool (an ETL developing environment) and via a simple call with curl for win32.

The calls made with curl were an "explorative" one

`curl -X POST http://<le_host>/api/3/action/datastore_delete -H "Authorization: 44d6d704-fd92-4078-8323-d0657ad434b9" -d "{\"resource_id\" : \"04ae6ca6-cbe8-4696-98c7-09485e95b280\"}"`

whose failure was expected due to the absence of the "force" attribute: `{"help": "http://<le_host>/api/3/action/help_show?name=datastore_delete", "success": false, "error": {"__type": "Validation Error", "read-only": ["Cannot edit read-only resource. Either pass\"force=True\" or change url-type to \"datastore\""]}}`

and another one with the "force" attribute explicitly set

`curl -X POST http://<le_host>/api/3/action/datastore_delete -H "Authorization: 44d6d704-fd92-4078-8323-d0657ad434b9" -d "{\"resource_id\" : \"04ae6ca6-cbe8-4696-98c7-09485e95b280\", \"force\" : true}"`

which gave the same "not found" error

`{"help": "http://<le_host>/api/3/action/help_show?name=datastore_delete", "success": false, "error": {"message": "Not found: Resource \"04ae6ca6-cbe8-4696-98c7-09485e95b280\" was not found.", "__type": "Not Found Error"}}`

... so why can't the system find what seems to be there?

**Comment by amercader** [comment]
According to the dataset dict that you posted, your resource is not on the DataStore (`"datastore_active": false`), so the Not Found error is the expected response.

Are you using the DataPusher to get the data automatically in the DataStore after uploading a file? If not you need to [enable it](http://docs.ckan.org/en/latest/maintaining/datastore.html#datapusher-automatically-add-data-to-the-datastore).

If you are using it, maybe there was an error during the upload. Go to the resource page > Manage > DataPusher to see if there are any details in the log.

**Comment by s3lvatico** [comment]
Thank you @amercader , I actually had the datapusher not explicitly enabled, as you correctly pointed out.

**Comment by amercader** [comment]
Glad you got it working

**Comment by s3lvatico** [comment]
As a follow up, is it normal that I can still see the resource inside the dataset although it appears to be correctly deleted? (and I assume it to be actually deleted since the DataExplorer plugin reports an error and I get a "not found" error if I try to download the resource).
Should I also manually delete it from the web interface or is there some other API call I am missing?
