### ISSUE TITLE
pbr version conflicts with dev-requirements.txt

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4392]
```
ckan's requirements.txt:
    pbr==1.10.0               # via sqlalchemy-migrate

ckan's dev-requirements.txt:
    pyfakefs==2.9

pyfakefs's [setup.py](https://github.com/jmcgeheeiv/pyfakefs/blob/version-2.9/setup.py#L26)
    setup_requires=mox3

mox's setup.py:
    setup_requires=['pbr>=2.0.0']
```

### CKAN Version if known (or site URL)
master

### What steps can be taken to reproduce the issue? 
* `pip install requirements.txt`
* `pip install dev-requirements.txt` gives error:
```
mox3 0.26.0 has requirement pbr!=2.1.0,>=2.0.0, but you'll have pbr 1.10.0 which is incompatible.
```

**Comment by amercader** [comment]
@davidread want to submit a PR with this requirements change? I think it should not affect tests but we'll find out.

**Comment by davidread** [comment]
Cool, I've done a PR and the tests pass.

**Comment by TkTech** [comment]
Posted an alternative PR which just removes pyfakefs.
