### ISSUE TITLE
Is there support for CKAN-Globus integration?

### ISSUE THREAD

**Issue by ghltshubh** [ckan/ckan#4404]
Does CKAN provide integration with Globus?

**Comment by rossjones** [comment]
Globus? https://www.globus.co.uk/ ?

**Comment by amercader** [comment]
@ghltshubh Maybe you mean this [Globus](https://www.globus.org/globus-connect-personal)? 
There is no support for this AFAIA but feel free to reach the mailing list or the [ideas](https://github.com/ckan/ideas-and-roadmap) repo if you would like guidance of how to implement it.
