### ISSUE TITLE
Flask-Babel does not translate zh_TW and zh_CN

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#4413]
### CKAN Version if known (or site URL)

≧ 2.8.0

### Please describe the expected behaviour

When switching to ``zh_TW`` or ``zh_CN`` languages on the pages written in Flask (ex. ``/`` and ``/user``), the pages should be shown in corresponding languages.

### Please describe the actual behaviour

It shows English instead of ``zh_TW`` or ``zh_CN``.

### What steps can be taken to reproduce the issue? 

Switch language to Chinese on the above-mentioned pages.

**Comment by u10313335** [comment]
The problem is caused by the ``Flask-Babel`` module which is used to translate pages written in Flask.

Pylons uses Python's ``gettext`` module which is [directory-based](https://github.com/python/cpython/blob/2.7/Lib/gettext.py#L524). However, ``Flask-Babel`` tries to find the directory containing translated strings through Babel's ``Locale.parse()`` function ([ref1](https://github.com/python-babel/flask-babel/blob/v0.11.2/flask_babel/__init__.py#L227), [ref2](https://github.com/python-babel/flask-babel/blob/v0.11.2/flask_babel/__init__.py#L243)), which "normalizes" the ``zh_TW`` and ``zh_CN`` to ``zh_Hant_TW`` and ``zh_Hans_CN`` respectively. Since there is no dirs named ``zh_Hant_TW`` and ``zh_Hans_CN``, those pages will not shown in desired languages.

A [similar situation](https://github.com/flask-admin/flask-admin/issues/403) happened on ``flask-admin`` and they decided to rename the dirs. But I think renaming dirs will break backwards compatibility in CKAN if people bookmarks urls with old ``/zh_TW`` or ``/zh_CN`` path. Any ideas or suggestions are welcomed.

**Comment by tino097** [comment]
@u10313335 Please check #4402. I think its fixing this issue

**Comment by u10313335** [comment]
@tino097 thanks. But #4402 is about the "label" shown on the language switcher. The problem I have described in this issue is the language of a CKAN site.

**Comment by tino097** [comment]
Sorry, i didnt read your comment, just went through the issue description  :/

**Comment by TkTech** [comment]
flask-babel needs to allow passing through args to babel.parse, specifically `resolve_likely_subtags=False` would fix this problem.

**Comment by amercader** [comment]
@TkTech any pointers on how to progress with this?

**Comment by ltf9651** [comment]
> flask-babel needs to allow passing through args to babel.parse, specifically `resolve_likely_subtags=False` would fix this problem.

how to edit resolve_likely_subtags=False? Can you give me the dir and filename where the code exists please? Thanks

**Comment by ltf9651** [comment]
> @TkTech thanks.
> 
> But I got the `babel.core.UnknownLocaleError: unknown locale 'zh_TW'` exception after setting `resolve_likely_subtags=False`.

I edit resolve_likely_subtags=False and restart apache, nothing changes

**Comment by ltf9651** [comment]
I didn't change resolve_likely_subtags=False
I just cp zh_CN(or zh_TW) zh_Hans_CN(zh_Hant_TW)
And it works!

**Comment by u10313335** [comment]
@ltf9651 You should set the ``resolve_likely_subtags`` argument to babel.parse in flask-babel just like @TkTech said. However, I have tried that but no luck.

And, renaming dirs resolve this issue but it will break backwards compatibility in CKAN if people bookmark urls with old /zh_TW or /zh_CN path.

Please refer to my previous comment here: https://github.com/ckan/ckan/issues/4413#issuecomment-414532805

**Comment by ltf9651** [comment]
@u10313335 
cd /ckan/i18n
copy zh_CN zh_Hans_CN
My problem fixed, you should have a try

**Comment by u10313335** [comment]
@ltf9651 I know that renaming dirs will resolve this issue. But it will break the links with /zh_TW or /zh_CN in the older versions of CKAN.

**Comment by wuweihust** [comment]
> 
> 
> @u10313335
> cd /ckan/i18n
> copy zh_CN zh_Hans_CN
> My problem fixed, you should have a try

It does work properly, thanks

**Comment by linforestzhang** [comment]
> 
> 
> @u10313335
> cd /ckan/i18n
> copy zh_CN zh_Hans_CN
> My problem fixed, you should have a try

Thanks. It is working.

**Comment by linforestzhang** [comment]
> 
> 
> @ltf9651 I know that renaming dirs will resolve this issue. But it will break the links with /zh_TW or /zh_CN in the older versions of CKAN.

The links remain zh_CN or zh_TW when using the workaround above provided by @u10313335.
For example, the URL is http://127.0.0.1:5000/zh_CN/dataset/example_xxx_dataset
rather than http://127.0.0.1:5000/zh_Hans_CN/dataset/example_xxx_dataset

**Comment by linforestzhang** [comment]
When switch the language to zh_CN, an error occurs with the details page of an organization:
...
File "/usr/local/lib64/python3.6/site-packages/markupsafe/init.py", line 249, in getitem
return self._kwargs[key]
KeyError: 'organization'

The details page of an organization is okay when switch the language to other language such as ja or zh_TW.
And ckan/i18n uses the folder named 'zh_Hans_CN' and 'zh_Hans_TW'.
But the po and mo files remain intact as the original files released by the CKAN GitHub project.

The error is still there even after the database has been cleared and initialized.
It's okay with other languages such as en, ja or zh_TW.

**Comment by linforestzhang** [comment]
> I didn't change resolve_likely_subtags=False
> I just cp zh_CN(or zh_TW) zh_Hans_CN(zh_Hant_TW)
> And it works!

Did you encounter the internal server error about showing the details page of an organization?

**Comment by linforestzhang** [comment]
> The problem is caused by the `Flask-Babel` module which is used to translate pages written in Flask.
> 
> Pylons uses Python's `gettext` module which is [directory-based](https://github.com/python/cpython/blob/2.7/Lib/gettext.py#L524). However, `Flask-Babel` tries to find the directory containing translated strings through Babel's `Locale.parse()` function ([ref1](https://github.com/python-babel/flask-babel/blob/v0.11.2/flask_babel/__init__.py#L227), [ref2](https://github.com/python-babel/flask-babel/blob/v0.11.2/flask_babel/__init__.py#L243)), which "normalizes" the `zh_TW` and `zh_CN` to `zh_Hant_TW` and `zh_Hans_CN` respectively. Since there is no dirs named `zh_Hant_TW` and `zh_Hans_CN`, those pages will not shown in desired languages.
> 
> A [similar situation](https://github.com/flask-admin/flask-admin/issues/403) happened on `flask-admin` and they decided to rename the dirs. But I think renaming dirs will break backwards compatibility in CKAN if people bookmark urls with old `/zh_TW` or `/zh_CN` path. Any ideas or suggestions are welcomed.

Is there any solution or workaround for this issue?  Thanks.

**Comment by linforestzhang** [comment]
> 
> 
> flask-babel needs to allow passing through args to babel.parse, specifically `resolve_likely_subtags=False` would fix this problem.
@u10313335
How to set resolve_likely_subtags=False?  Thanks

**Comment by linforestzhang** [comment]
Workaround to be fully evaluated:
Temporarily get the line for calling the feeds snippet in the read-base of "organization".  That's all.  Any idea or suggestion?  THX.

**Comment by linforestzhang** [comment]
The formal solution seems  within the snippet feeds.html

**Comment by amercader** [comment]
@u10313335 @linforestzhang @TkTech could you please check https://github.com/ckan/ckan/pull/6008? I think that is a good compromise between doing things as Babel expects them and supporting old URLs.

**Comment by u10313335** [comment]
LGTM, thanks @amercader!
