### ISSUE TITLE
Dataset counts incorrect on Groups listing

### ISSUE THREAD

**Issue by inghamn** [ckan/ckan#4420]
After upgrading to CKAN 2.8.1, the dataset counts are incorrect on the group listing screen.

On the group listing screen (/group), the dataset count for each group is the full dataset count for the whole site.  The correct count is shown on the screen for each individual group (/group/somegroup)

CKAN 2.8.1
/group
/group/somegroup

**Comment by iamarnavgarg** [comment]
Hello @inghamn I was able to reproduce the issue as per the details given by you. However, I find that when the "visibility" option of the data set is "private", then only it doesn't show the correct count.
Also, if you change the visibility status of the data set to "public", you will be able to see the correct count on `/group`.

**Comment by inghamn** [comment]
All of our datasets are Public.

The problem is not that each group count is zero.  Rather each group count is the full count of all datasets on the server.  The query does not seem to actually be filtering by group.

https://data.bloomington.in.gov/group

**Comment by smotornyuk** [comment]
I've tried to reproduce this issue a number of times during these months but was unable to get reported behavior even once, on different CKAN versions. Could you try to disable all custom extensions (harvest, datajson, cob), rebuild Solr index and check, whether the problem still exists? 
PS and could you also check solr logs when performing re-index?

**Comment by inghamn** [comment]
I've disabled harvest, datasjon, and cob (our custom theme).  I've also re-indexed the solr index, and attached the solr log.  The result is the same, though.  There are no errors in the solr logs.

I didn't realize the groups page is info coming from Solr.  It must be an error in the solr queries for each of the groups.
[solr.log](https://github.com/ckan/ckan/files/2901411/solr.log)

**Comment by inghamn** [comment]
With the knowledge that this is a Solr query error, I reviewed the logs and manually queried our Solr core.  I think this an error in the code generating the solr queries for this screen.  What's getting generated is:
```
fq=%2Bcapacity:public+groups:"operations"
```
and what should be generated is:
```
fq=capacity:public&groups:"operations"
```

**Comment by inghamn** [comment]
I suspect it is caused by the code in /ckan/logic/action/get.py at line 1883.
```python
        data_dict.setdefault('fq', '')
        if not include_private:
            data_dict['fq'] = '+capacity:public ' + data_dict['fq']
```
However, someone more familiary with ckan's building of Solr queries would know better than I.  It looks like attempting to build up the filter queries as a single fq parameter string, rather than multiple fq parameters.
