### ISSUE TITLE
resource_proxy not working

### ISSUE THREAD

**Issue by mystycs** [ckan/ckan#4432]
I am running ckan 2.7.3 and i enabled resource_proxy in my plugins production.ini.

But i still get the error in my HTML view for webpage_view.

Refused to display 'https://www.newegg.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'. 

Any idea why it might not be working?

**Comment by derwas** [comment]
Any updates on this?
I am having the same issue with ckan 2.7.2

**Comment by mystycs** [comment]
So it seems that mine was working, just many sites dont allow external linking so they will give that error.

I tried this page (https://en.wikipedia.org/wiki/Turtle) and it worked and then tried smaller websites not like google, yahoo etc and saw it works.

Allot of sites set it to sameorigin or deny because they dont allow external linking for security. Was not on my end in the end

**Comment by amercader** [comment]
Yes, the original site can define its preferences regarding embedding via the `X-Frame-Options` header. If it disallows embedding, the browser will honor this and refuse to display the page.
