### ISSUE TITLE
Package URL is not stored

### ISSUE THREAD

**Issue by LingboTang** [ckan/ckan#4434]
### CKAN Version if known (or site URL)
2.7.3

### Please describe the expected behaviour
When I query a package with `package_search` or `package_show`, it should show me the url in `url` field. For example if I want to get the metadata on demo: https://demo.ckan.org/api/3/action/package_show?id=ict-administracja-2015. It should show me:
`{"help": "https://demo.ckan.org/api/3/action/help_show?name=package_show", "success": true, "result": {"license_title": "Creative Commons Attribution", "maintainer": "", "relationships_as_object": [], "private": false, "maintainer_email": "", "num_tags": 0, "id": "928187e8-3fd1-475a-91ab-8f62aa9bd91b", "metadata_created": "2018-07-03T20:17:07.803888", "metadata_modified": "2018-07-03T20:28:10.687937", "author": "", "author_email": "", "state": "active", "version": "", "creator_user_id": "109ca79d-768c-4d05-ab18-592537ca2b69", "type": "dataset", "resources": [{"mimetype": null, "cache_url": null, "hash": "", "description": "", "name": "", "format": ".xlsx", "url": "https://demo.ckan.org/dataset/928187e8-3fd1-475a-91ab-8f62aa9bd91b/resource/cc8f8bab-1b2e-420e-9450-b878a96ed734/download/cccc.xlsx", "datastore_active": false, "cache_last_updated": null, "package_id": "928187e8-3fd1-475a-91ab-8f62aa9bd91b", "created": "2018-07-03T20:17:37.004470", "state": "active", "mimetype_inner": null, "last_modified": null, "position": 0, "revision_id": "495f3722-6f09-4ea9-a38c-ef2b378f7071", "url_type": "upload", "id": "cc8f8bab-1b2e-420e-9450-b878a96ed734", "resource_type": null, "size": null}], "num_resources": 1, "tags": [], "groups": [], "license_id": "cc-by", "relationships_as_subject": [], "organization": null, "name": "ict-administracja-2015", "isopen": true, "url": "https://demo.ckan.org/dataset/ict-administracja-2015", "notes": "test", "owner_org": null, "extras": [], "license_url": "http://www.opendefinition.org/licenses/cc-by", "title": "test", "revision_id": "a939efe9-7ef3-4a4f-9d24-ea5fd7347675"}}`

### Please describe the actual behaviour
The actual results is that I got an empty string for the `url` field.  I did similar thing in my local development environment and checked the package table. The `url` column is also an empty string.

### What steps can be taken to reproduce the issue? 
1. Create a package
2. Search this package with api or find this package in package table.

**Comment by metaodi** [comment]
This is a misunderstanding. The "url" field on the package is not supposed to contain the URL of the dataset on the portal, it's a metadata field to describe the source of this dataset. If you have a look at the demo instance of CKAN, I created a dataset: https://demo.ckan.org/dataset/this-is-a-test-metaodi

There the field "Source" is filled, and if you query this dataset with the API, you'll see that the the "Source" is called "url" in the API (https://demo.ckan.org/api/3/action/package_show?id=this-is-a-test-metaodi).

The package URL must not be saved by CKAN, as it can easily be generated. It could however be useful to add this as an extra field to the API output.

**Comment by LingboTang** [comment]
@metaodi Thanks for your explanation, I think I can close this issue now.
