### ISSUE TITLE
Feature request: "add another" button when editing datasets

### ISSUE THREAD

**Issue by VikingScientist** [ckan/ckan#4442]
### CKAN Version if known (or site URL)
http://portal.mso4sc.eu/

### Please describe the expected behaviour
I expect the interface on editing existing datasets to mirror that of creating new datasets. In short I expect that the two screenshots given below ("new dataset" and "edit dataset") should have identical form.

### Please describe the actual behaviour
What happens is that editing datasets has a different set of buttons. In particular it is missing the "save & add another" button which I greatly miss. A current workaround is to navigate all the way back to this page for every new dataset to be uploaded which is somewhat cumbersome.

### What steps can be taken to reproduce the issue? 

* Data catalogue
* Datasets
* Add dataset

gives the following screen 

<img width="692" alt="screenshot 2018-08-29 09 41 52" src="https://user-images.githubusercontent.com/3500376/44773192-3ba29e00-ab70-11e8-9a64-1f4002b7883d.png">

Notice in particular the button "save & add another" at the bottom.

If you try and **edit** an existing dataset by

* Data catalogue
* Datasets
* (click existing dataset)
* Manage
* Resources
* Add new resource

we get the following screen which is missing the "save & add another"-button. After clicking "add" you basically have to navigate all the way back to this screen again to keep editing.

<img width="692" alt="screenshot 2018-08-29 09 39 53" src="https://user-images.githubusercontent.com/3500376/44773347-a94eca00-ab70-11e8-8b87-9f1375f2cbac.png">

**Comment by amercader** [comment]
What you describe makes sense. There is some logic in the templates that hides the "Save & add another" button when not in the create dataset form (`stage == True`):

https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/resource_form.html#L71

Changing this would be easier but I'm not sure if further changes are needed at the blueprint level to handle redirects (I'd imagine they are not)

Feel free to have a go at it, happy to help.

**Comment by ashmeet-kandhari** [comment]
Hi @amercader ,
I have raised a PR for the above changes. Please let me know if anything else is needed to be done.

**Comment by VikingScientist** [comment]
Proposed fix can be found in #4490

**Comment by boykoc** [comment]
@amercader I think this can get closed. #4490 seems to have addressed it and has been merged, looks like issue number was missed.

**Comment by tino097** [comment]
Thanks @VikingScientist and @boykoc
