### ISSUE TITLE
Following organization fails

### ISSUE THREAD

**Issue by exlibris** [ckan/ckan#4445]
Running CKAN 2.8.0.  A fresh install with no localization via extension.  When clicking "Follow" on an organization, I am getting the error:
```
404 Not Found
The resource could not be found.

Incorrect group type
```
It works fine for datasets and groups.  Also, I see it is working in demo.ckan.org, but that appears to be back at version 2.6.0.  Is CKAN 2.8.0 considered a stable release or should I roll back to 2.6.0?

**Comment by smotornyuk** [comment]
Could you try to upgrade to 2.8.1 - it works fine there. There were some bugs related to routing that are fixed in 2.8.1 and you probably just find one of them
