### ISSUE TITLE
In datastore_search, parameter include_total=False doesn't work

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4446]
### CKAN Version if known (or site URL)
master

### Please describe the expected behaviour
When calling action function `datastore_search` you can set parameter include_total=False when you don't need the count. This should prevent an SQL query e.g. `SELECT  count(*) FROM "47e77d3c-6c77-44f2-bbf4-740b1b28bf5f"  ;` Counting rows is notoriously expensive, so we should avoid this when possible.

### Please describe the actual behaviour
The parameter didn't change behaviour. The `SELECT count(*)...` occurred anyway. This causes the resource page to display slowly.

This is not normally a problem, but when the datastore db is being taxed (e.g. by ckan-xloader loading in data) the resource page for large datasets [can become unresponsive](https://github.com/ckan/ckanext-xloader/issues/41). So it is important to save on these expensive requests where we can.

### What steps can be taken to reproduce the issue?
You can see the `SELECT count(*) ...` occurring by turning on sqlalchemy logging, viewing a resource page (e.g. `/dataset/abc/resource/xyz` for a CSV that has been xloaded/datapushed.

If you put a pdb breakpoint in `ckan/ckanext/datastore/helpers.py:datastore_dictionary()` you see it calls datastore_search with include_total=False, however in datastore_search you see that gets changed to True when stepping past this line:
```
    data_dict, errors = _validate(data_dict, schema, context)
```

**Comment by wardi** [comment]
oh, I see the bug. The `default` validator replaces any falsey values with its parameter. That seems really broken. Will have to check for code relying on that behaviour, but I'll submit a fix.

**Comment by wardi** [comment]
I didn't notice this because I was testing with the API using the string `"false"` instead of the json value False
