### ISSUE TITLE
CKAN Limitations?

### ISSUE THREAD

**Issue by wendyliao2018** [ckan/ckan#4455]
Is CKAN able to be programmed so that instead of uploading data onto a website, clients could actually just write straight onto the website and save?

**Comment by tino097** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!

**Comment by wendyliao2018** [comment]
Hi, Thanks for letting me know! Still trying to figure the site out I've posted it over on StackOverflow and I'll wait for an answer there.
