### ISSUE TITLE
Active Directory implementation

### ISSUE THREAD

**Issue by Abhishek-Dutta** [ckan/ckan#4465]
### Please describe the expected behaviour

I am checking on if we can do Active Directory implementation for users with ckan and not create users on ckan separately. Not sure if I am missing any component. If present can anyone please point to the right documentation or api.

**Comment by jqnatividad** [comment]
You may want to check https://github.com/nhsengland/ckanext-adfs.  We've used it in several installations successfully.

**Comment by wardi** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!
