### ISSUE TITLE
Is packaging.ckan.org down?

### ISSUE THREAD

**Issue by maurizi** [ckan/ckan#4466]
Our Ansible scripts have been failing due to being unable to download the `.deb` from packaging.ckan.org.

Going to the website shows a CloudFlare error page:
![packaging ckan org-python-ckan_2 8-trusty_amd64 deb](https://user-images.githubusercontent.com/4432106/45769829-bfe7be80-bc0e-11e8-8aa1-768fb9fc1880.png)

**Comment by Abhishek-Dutta** [comment]
Any Update on this. I am also facing the same issue

**Comment by amercader** [comment]
Sorry, this is being looked at now. It must be a problem with the DNS but in the meantime you can access the S£ bucket directly: http://packaging.ckan.org.s3-website-eu-west-1.amazonaws.com/

**Comment by wardi** [comment]
Looks fixed now

**Comment by amercader** [comment]
Note that https is not working, but http should work for now
