### ISSUE TITLE
How to make datatables url open new tab

### ISSUE THREAD

**Issue by mystycs** [ckan/ckan#4469]
Where is the code that allows URLs to be rendered in datatables? I looked through all the js files but cant narrow down where the URLs are generated in datablesview: I want to make the below URL Giftcards open in a new tab

![image](https://user-images.githubusercontent.com/3004566/45833008-7d3aea80-bcd1-11e8-84ee-2a27eb2093a6.png)

**Comment by amercader** [comment]
@wardi do you know? That's probably handled by datatables itself right?

**Comment by klikstermkd** [comment]
@mystycs This is something that is handled by the Datatables library itself. It automatically creates the links.

Not sure if Datatables has that option, but you can do it by yourself by selecting all links in the table and set the `target` attribute to `_blank`. Example:

`$('#myTable a').attr('target', '_blank');`

Hope this helps.

**Comment by wardi** [comment]
The code that creates the datatable is in https://github.com/ckan/ckan/blob/master/ckanext/datatablesview/public/datatablesview.js and https://github.com/ckan/ckan/blob/master/ckanext/datatablesview/templates/datatables/datatables_view.html so you could extend the template with JS like @klikstermkd suggests in your own theme plugin
