### ISSUE TITLE
NAVL __junk Error - Package Create with groups

### ISSUE THREAD

**Issue by HilariousGil** [ckan/ckan#4470]
I'm using ckanext-scheming and my dataset schema as a field "groups" so I can select the group to which the dataset is connected to. 
As the package_create documentation says I give it a list of dictionaries with the key 'id' (e.g. pkg_dict['groups'] = [{'id':'1234567'}] ).
I recieve a Validation Error "__junk: The input field ('groups', 0, 'id') was not expected."
I can see that the dictization_function tries to check not only if the field "('groups',)" but also the field "('groups', 0, 'id')" and this is what causes the validation error.

I do not have a ckanext-scheming schema definition for groups, is that needed?
Is there something I'm missing about adding a simple field to chose select a group for a dataset?

### CKAN Version if known (or site URL)
2.8.1

### Please describe the expected behaviour
Package Creation would be sucessfull

### Please describe the actual behaviour
Get a Validation Error on the ('groups', 0, 'id') field

**EDIT**
I changed my approach to the problem and worked around this no longer have this issue.
This Issue can be closed.

**Comment by Baehn** [comment]
I have a similar problem: I added a form element inserting elements from "h.available_groups" to data.groups in the package form and after trying to create a new package I get an error 

"__junk: The input field  [(u'groups', 0, u'image_display_url'), (u'groups', 0, u'description'), (u'groups', 0, u'id'), (u'groups', 0, u'name'), (u'groups', 0, u'title'), (u'groups', 0, u'display_name')]  was not expected."

However, editing groups on an existing dataset works
