### ISSUE TITLE
Remove legacy Search API

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4483]
### CKAN Version if known (or site URL)

Can we officially deprecate the legacy [Search API and Utils APIs](https://docs.ckan.org/en/latest/api/legacy-api.html)?

These was described as "legacy API"s since CKAN 2.3 (here)[https://github.com/ckan/ckan/commit/254fca2d43ccacbe674df2da42aba83897dcdb96#diff-b4e5718590c95267775a87dafc922c76). However they have not been marked as deprecated in the changelog.

These are the APIs:
* `/api/search/dataset` / `/api/search/package` (replaced by `package_search`)
* `/api/search/resource` (replaced by `resource_search`)
* `/api/search/revision` (revisions are deprecated)
* `/api/tag_counts` (can be done with `package_search facet.field='tags'`)
* `/api/util/dataset/autocomplete` (replaced by `package_autocomplete`)
* `/api/util/tag/autocomplete` (replaced by `tag_autocomplete`)
* `/api/util/resource/format_autocomplete` (replaced by `format_autocomplete`)
* `/api/util/dataset/munge_name`
* `/api/util/dataset/munge_title_to_name`
* `/api/util/tag/munge`

I can't see any replacements for the munge functions and I suspect they are still useful to anyone replacing the CKAN front-end. Should we turn these into action funcs?

(We [got rid of the REST API `/api/rest/*` in 2.8](https://github.com/ckan/ckan/pull/4069), having been marked as deprecated in the 2.7 changelog)

**Comment by amercader** [comment]
That sounds very sensible.

I think that that the munge functions can be easily turned into actions as you suggest, and the rest we should just remove.

**Comment by davidread** [comment]
Nice one @ZoranPandovski !

**Comment by howff** [comment]
scheming is still using tag/autocomplete isn't it?

**Comment by davidread** [comment]
@wardi would know
