### ISSUE TITLE
Process completed but unable to post to result_url

### ISSUE THREAD

**Issue by jorarmarfin** [ckan/ckan#4515]
### CKAN Version if known (or site URL)
version 2.8.1

### Please describe the expected behaviour
I install ckan with docker, and everything works fine but when I add a resource in datastore it does not work I get this error Process completed but unable to post to result_url

**Comment by linforestzhang** [comment]
> 
> 
> This error means that the DataPusher finished its job (ie the data is on the DataStore) but it could not ping back to CKAN via HTTP to update the status. This generally happens because the CKAN host (as defined in `ckan.site_url` is not accessible, in this case from the DataPusher container.
> 
> One workaround is to add an entry to your /etc/hosts file (something like `127.0.0.1 ckan-dev` and use that in your `ckan.site_url` setting.

This workaround is not working for me (CKAN v2.9.1 installed from docker compose)

**Comment by edsmcosta** [comment]
For me too, i wonder what am i missing between the datastore. I cant get access to write even with the introdutory test :
![image](https://user-images.githubusercontent.com/22220849/119218289-04aa0e80-bab6-11eb-8936-71afe463e0b4.png)
![image](https://user-images.githubusercontent.com/22220849/119218312-17244800-bab6-11eb-8f96-2ed428c68e1f.png)
![image](https://user-images.githubusercontent.com/22220849/119218360-33c08000-bab6-11eb-869b-ef76c7c4682f.png)
