### ISSUE TITLE
How to uninstall CKAN or change it into development mode?

### ISSUE THREAD

**Issue by ltf9651** [ckan/ckan#4520]
CKAN document says that If you’re not using Ubuntu 16.04 64-bit or Ubuntu 14.04 64-bit, or if you’re installing CKAN for development, you should follow Installing CKAN from source instead.

Now I installed from the package and it's production mode, I am a developer and I wanna change it into development mode.

It's running on Ubuntu 16 now

**Comment by amercader** [comment]
I'm not sure I follow. You can probably turn a package install into a source one as essentially what the package one does is creating a virtualenv in `/usr/lib/ckan/default` and installing CKAN and its requirements. You could use the ckan source in `src/` for development using the paster development server but it's probably best if you just reinstall CKAN using a source install. You can use the same database and Solr server than the current site.

To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [Gitter channel](https://gitter.im/ckan/chat) on freenode, where other developers may be able to help you.

Thanks!
