### ISSUE TITLE
ImportError: LazyView ||   ckan/views/dataset.py Missing

### ISSUE THREAD

**Issue by HilariousGil** [ckan/ckan#4527]
### CKAN Version if known (or site URL)
Branch 2.8

### Please describe the expected behaviour
Server should load sucessfully

### Please describe the actual behaviour
The server crashes with a Import Error.
"ImportError: cannot import name LazyView"

### Note

I see that the file "/ckan/ckan/views/dataset.py" is not present in the branch 2.8

**Comment by tino097** [comment]
If you had started `master` branch before, cleaning the `*.pyc` files should help for this issue

**Comment by HilariousGil** [comment]
Thanks a lot @tino097  for the very very fast answer.
that solved the issue!
