### ISSUE TITLE
package_autocomplete not working as expected

### ISSUE THREAD

**Issue by klikstermkd** [ckan/ckan#4529]
### CKAN Version if known (or site URL)
2.8.1 (but probably not working on older versions as well)

### Please describe the expected behaviour
When I use the `package_autocomplete` API action, if there is a dataset with title "Dataset title", and I set `q` param to be "title", the dataset with title "Dataset title" should be returned.

### Please describe the actual behaviour
When I use the `package_autocomplete` API action, if there is a dataset with title "Dataset title", and I set `q` param to be "title", the dataset with title "Dataset title" is not returned. In the CKAN API documentation for the action https://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.get.package_autocomplete it says that "Datasets with names or titles that **contain** the query string will be returned.". So I expect that it will do a fuzzy search match. Looking at the code https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L1512 it's obvious that it will only search for names and titles that **start** with the query. In order to work as per the documentation instead of `%s%%` it should be `%%%s%%`.

### What steps can be taken to reproduce the issue? 
1. Create a dataset with title "Dataset title" and make it public.
2. Call the API action `package_autocomplete` and set the value for `q` param to be `title`. This will not return the above dataset.
3. Call the API action `package_autocomplete` and set the value for `q` param to be `dataset`. This will return the above dataset.

**Comment by wardi** [comment]
fixed by #4191 need to review and merge
