### ISSUE TITLE
HTTPS not working on dataset and resource page

### ISSUE THREAD

**Issue by solars** [ckan/ckan#4533]
Hi there,

I'm using a dockerized CKAN (2.8.1) installation that has SSL enabled.

I always get a mixed content/insecure content warning and have to enable the request manually.
This happens on the datasets details page (/datasets/xy) with the following error:

```
jquery.min.js:4 Mixed Content: The page at 'https://ckan.myckan.com/dataset/naechtigungen-gesamt' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ckan.myckan.com/api/i18n/en'. This request has been blocked; the content must be served over HTTPS.
send @ jquery.min.js:4
```

If I then click on the resources page, the data is not displayed (e.g. CSV). I instead get:
```
Mixed Content: The page at 'https://ckan.myckan.com/dataset/naechtigungen-gesamt/resource/af10138d-b73b-45d2-bca9-179eda1fc7b6' was loaded over HTTPS, but requested an insecure resource 'http://ckan.myckan.com/dataset/naechtigungen-gesamt/resource/af10138d-b73b-45d2-bca9-179eda1fc7b6/view/a6d82a4f-7a05-42fe-99e3-db5c3003a95e'. This request has been blocked; the content must be served over HTTPS.
jquery.min.js:4 Mixed Content: The page at 'https://ckan.myckan.com/dataset/naechtigungen-gesamt/resource/af10138d-b73b-45d2-bca9-179eda1fc7b6' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ckan.myckan.com/api/i18n/en'. This request has been blocked; the content must be served over HTTPS.
```
The page source includes:
`<body data-site-root="http://ckan.myckan.com/" data-locale-root="http://ckan.myckan.com/" >
` I'm not sure if this is correct and whether it's used for the javascript calls.

I've read through https://github.com/ckan/ckan/wiki/SSL the settings are present.

This is my nginx config:
https://gist.github.com/solars/748af63dbde53db659aa03967d68ba1c

I verified the headers are forwarded with tcpdump:
https://gist.github.com/solars/c03c740cad3f488b498a37d02a6d5b7c

Can anyone please help?

**Comment by frafra** [comment]
Is the variable `CKAN_SITE_URL` set properly? Are you connecting to the very same URL? I just wanted to be sure, because I had a similar issue (`http://` instead of `https://`).

**Comment by tino097** [comment]
Hi @solars , thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!

**Comment by solars** [comment]
@tino097 I already did this, which led me to conclude that this a bug, not a support issue. All the suggested settings and options are in place as specified.

**Comment by solars** [comment]
> Is the variable `CKAN_SITE_URL` set properly? Are you connecting to the very same URL? I just wanted to be sure, because I had a similar issue (`http://` instead of `https://`).

Yes, this is what I have set.

**Comment by tino097** [comment]
@solars im sorry, but your nginx settings are looking good to me, so the problem could be somewhere else. That's why we are proceeding this type of issues to Gitter or StackOverflow.
