### ISSUE TITLE
nosetests fail locally

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4540]
### CKAN Version if known (or site URL)
2.8.1

### Please describe the expected behaviour
Tests should be reproducible: users should get the same result when they run them locally or on a CircleCI pipeline triggered by a pull request.

### Please describe the actual behaviour
Many tests fail on current master, because CKAN tests looks for "http://test.ckan.net/". This value is hard-coded in many tests.

Changing `ckan.site_url` manually in `test-core.ini` does not fix the issue (this value should be set automatically on Docker images in my opinion and the default should be `http://localhost`, not `http://test.ckan.net`).

### What steps can be taken to reproduce the issue? 
```
$ cd contrib/docker
$ docker-compose up -d
$ docker exec -it ckan /bin/bash
$ cd /usr/lib/ckan/venv/src/ckan && source ../../bin/activate
$ pip install -r dev-requirements.txt
$ nosetests --ckan --with-pylons=test-core.ini ckan ckanext
```

Using `--reset-db` gives even worse results.

**Comment by kmbn** [comment]
I'm closing this in favor of #4088, where most of the discussion about failing local tests has taken place. Whether the tests are run on 2.8 or master, users still report unexpected errors and failures.
