### ISSUE TITLE
Popular flame icon is not displayed for popular resources.

### ISSUE THREAD

**Issue by LingboTang** [ckan/ckan#4542]
### CKAN Version if known (or site URL)
2.6.6, 2.7.3, 2.8.1

### Please describe the expected behaviour
As what has been mentioned in the official docs: [highlighting-popular-datasets-and-resources](https://docs.ckan.org/en/2.8/maintaining/tracking.html?highlight=tracking#highlighting-popular-datasets-and-resources), there should be a flame icon displayed for popular datasets/resources (more than 10 views) by default.

### Please describe the actual behaviour
It only displayed 'Popular' text, it is not displaying the flame icon.

### What steps can be taken to reproduce the issue? 
1. Create a package/resource.
2. Set view numbers more than 10 for this package/resource.
3. View it on the webpage list.

**Comment by wardi** [comment]
I think you need to rebuild the search index e.g. with a `paster search-index rebuild -r` in a nightly cron job for the popular flag to appear

**Comment by LingboTang** [comment]
@wardi I've tried to rebuild it already, but I still can't display the icon.

**Comment by smotornyuk** [comment]
I believe, that this icon is disabled by default - take a look at https://github.com/ckan/ckan/blob/master/ckan/templates/snippets/package_item.html#L7

So you'll probably need to update template inside your theming extension for displaying banner...

**Comment by LingboTang** [comment]
The developers who worked on my current project previously had overwritten the default css files and that's why I can't display them. I thought they just added their style definition in the default one but I shouldn't take it for granted. I will close it now.
