### ISSUE TITLE
Role function issue

### ISSUE THREAD

**Issue by ltf9651** [ckan/ckan#4546]
I developed a platform based on CKAN and there is a function that can custom different roles's permissions(create,delete,read an so on) 
When I add an new role , I can't see the new role in the select list in /member_new/ page but the new role can shows in the left side , under the " What are roles?" 
I can see the new role until I restart the CKAN server(shut down CKAN and restart)
How should I do to see the new role in select list once I create or update it

**Comment by smotornyuk** [comment]
Maybe i miss something, but there is no official way of registering new roles, so you may need to either hack into CKAN core, or reimplement roles from scratch in your extension. If you are brave enough - you may try to monkey-patch `ROLE_PERMISSIONS` dictonary from `ckan.authz` - this collection used by core ckan functionality when generating list of available roles. But, as i said before, there is no 'official' way of doing this, so you'll probably face some issues. For example, as i see from code, if you add new role, let's call it 'owner' - you need to add translation function for this role. For this you may need to replace `ckan.authz.trans_role` function or create `ckan.authz._trans_role_owner` function... 

So, quick outline - there are no good solution and you need to patch `ckan.authz` module.
