### ISSUE TITLE
SSL SYSCALL error

### ISSUE THREAD

**Issue by mystycs** [ckan/ckan#4547]
I am running my ckan app on Azure. The ckan side runs on a VM Ubuntu 16.04 and the Postgres database is running on Azure Database for PostgreSQL server.

Every few weeks i get these errors below and I cant resolve it unless i start apache2. Does anyone know of a fix or solution around this? I assume its due to a connection break but Im not sure why it breaks and im looking for a solution to resolve these issues right away if it happens.

Is there a way to resolve these connection issues or does ckan always just stay connected?

`Module ckan.controllers.home:22 in __before__
>>  base.BaseController.__before__(self, action, **env)
Module ckan.lib.base:199 in __before__
>>  app_globals.app_globals._check_uptodate()
Module ckan.lib.app_globals:203 in _check_uptodate
>>  value = model.get_system_info('ckan.config_update')
Module ckan.model.system_info:58 in get_system_info
>>  obj = meta.Session.query(SystemInfo).filter_by(key=key).first()
Module sqlalchemy.orm.query:2334 in first
>>  ret = list(self[0:1])
Module sqlalchemy.orm.query:2201 in __getitem__
>>  return list(res)
Module sqlalchemy.orm.query:2405 in __iter__
>>  return self._execute_and_instances(context)
Module sqlalchemy.orm.query:2420 in _execute_and_instances
>>  result = conn.execute(querycontext.statement, self._params)
Module sqlalchemy.engine.base:727 in execute
>>  return meth(self, multiparams, params)
Module sqlalchemy.sql.elements:322 in _execute_on_connection
>>  return connection._execute_clauseelement(self, multiparams, params)
Module sqlalchemy.engine.base:824 in _execute_clauseelement
>>  compiled_sql, distilled_params
Module sqlalchemy.engine.base:954 in _execute_context
>>  context)
Module sqlalchemy.engine.base:1116 in _handle_dbapi_exception
>>  exc_info
Module sqlalchemy.util.compat:189 in raise_from_cause
>>  reraise(type(exception), exception, tb=exc_tb)
Module sqlalchemy.engine.base:947 in _execute_context
>>  context)
Module sqlalchemy.engine.default:435 in do_execute
>>  cursor.execute(statement, parameters)
OperationalError: (OperationalError) SSL SYSCALL error: EOF detected 'SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id \nFROM system_info \nWHERE system_info.key = %(key_1)s \n LIMIT %(param_1)s' {'key_1': 'ckan.config_update', 'param_1': 1}
`

**Comment by amercader** [comment]
@mystycs This error just suggests that the connection to Postgres was dropped which points to network or connectivity issues. Perhaps your provider has scheduled downtimes? In any case it doesn't seem to be related to CKAN itself.

**Comment by mystycs** [comment]
Are there any suggestions or methods to reconnecting when the provider has downtime?

How have other people approached this?

**Comment by LinuxChristian** [comment]
Hi,

Sorry for opening a old isssue but I have exactly the same problem and have been debugging this for a copule of month. I have an managed Azure Postgresql database and a Redhat Enterprise 7.0 VM running CKAN v2.8.3.

Everything works fine initially but after a couple of months CKAN fails with HTTP500 Internal Server Error. Then the server may keep this error for a couple of days or a week and then everything works again. It is very strange.

In the CKAN logs I get,
```
[Tue Jul 30 08:16:03.908026 2019] [:error] [pid 102384] [remote 10.68.4.36:52] OperationalError: (OperationalError) SSL SYSCALL error: EOF detected
[Tue Jul 30 08:16:03.908032 2019] [:error] [pid 102384] [remote 10.68.4.36:52]  'SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id \\nFROM system_info \\nWHERE system_info.key = %(key_1)s \\n LIMIT %(param_1)s' {'param_1': 1, 'key_1': 'ckan.config_update'}
```

I also initially expected this to be a firewall issue but I can see the same request hit the database with the following error,

```
2019-07-30 09:21:30 UTC-5d400bd3.76d8-ERROR:  syntax error at or near "%" at character 251
2019-07-30 09:21:30 UTC-5d400bd3.76d8-STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id 
	FROM system_info
	WHERE system_info.key = %(key_1)s 
	LIMIT '%(param_1)s' {'key_1': 'ckan.config_update', 'param_1': 1}
2019-07-30 09:22:02 UTC-5d400bd3.76d8-ERROR:  syntax error at or near "%" at character 251
2019-07-30 09:22:02 UTC-5d400bd3.76d8-STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id 
	FROM system_info
	WHERE system_info.key = %(key_1)s 
	LIMIT %(param_1)s {'key_1': 'ckan.config_update', 'param_1': 1}
2019-07-30 09:22:41 UTC-5d400c61.7750-LOG:  connection received: host=127.0.0.1 port=41525 pid=30544
```
So the database claims this is a syntax error. The syntax also does not look correct.

Any suggestions?

**Comment by LinuxChristian** [comment]
I had a look in the CKAN code and could the problem be in this function

https://github.com/ckan/ckan/blob/ebe9d8390e52458bc388fbaf15a9ab7bee2ae2d7/ckan/model/system_info.py#L55-L64

From the SQL I would expect the 

```sql
SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id 
FROM system_info
WHERE system_info.key = ckan.config_update 
LIMIT 1;
```

But the statement on the server is,

```sql
SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id 
FROM system_info
WHERE system_info.key = %(key_1)s 
LIMIT %(param_1)s {'key_1': 'ckan.config_update', 'param_1': 1}
```

So the string interpolation never happens. I had a look at the [filter_by ](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.filter_by) function but that expects keyvars and that is also what it gets.

So still stumped and does not explain why this error only surfaces after 1+ month and not when CKAN starts.

**Comment by LinuxChristian** [comment]
From the CKAN error logs I can see that it is exactly in the system_info.py file the problem happens,

```
[Thu Aug 01 08:15:42.818026 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 199, in __before__
[Thu Aug 01 08:15:42.818042 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     app_globals.app_globals._check_uptodate()
[Thu Aug 01 08:15:42.818049 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/src/ckan/ckan/lib/app_globals.py", line 203, in _check_uptodate
[Thu Aug 01 08:15:42.818065 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     value = model.get_system_info('ckan.config_update')
[Thu Aug 01 08:15:42.818072 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/src/ckan/ckan/model/system_info.py", line 58, in get_system_info
[Thu Aug 01 08:15:42.818238 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     try:
```

From there the problem moves into the sqlalchemy package,

```
[Thu Aug 01 08:15:42.818253 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2334, in first
[Thu Aug 01 08:15:42.818283 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     ret = list(self[0:1])
[Thu Aug 01 08:15:42.818293 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2201, in __getitem__
[Thu Aug 01 08:15:42.818312 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     return list(res)
[Thu Aug 01 08:15:42.818321 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2405, in __iter__
[Thu Aug 01 08:15:42.818339 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     return self._execute_and_instances(context)
[Thu Aug 01 08:15:42.818349 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2420, in _execute_and_instances
[Thu Aug 01 08:15:42.818368 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     result = conn.execute(querycontext.statement, self._params)
[Thu Aug 01 08:15:42.818377 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 727, in execute
[Thu Aug 01 08:15:42.818397 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     return meth(self, multiparams, params)
[Thu Aug 01 08:15:42.818406 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
[Thu Aug 01 08:15:42.818428 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     return connection._execute_clauseelement(self, multiparams, params)
[Thu Aug 01 08:15:42.818437 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 824, in _execute_clauseelement
[Thu Aug 01 08:15:42.818456 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     compiled_sql, distilled_params
[Thu Aug 01 08:15:42.818464 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
[Thu Aug 01 08:15:42.818483 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     context)
[Thu Aug 01 08:15:42.818492 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
[Thu Aug 01 08:15:42.818510 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     exc_info
[Thu Aug 01 08:15:42.818519 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
[Thu Aug 01 08:15:42.818555 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     reraise(type(exception), exception, tb=exc_tb)
[Thu Aug 01 08:15:42.818564 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
[Thu Aug 01 08:15:42.818600 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     context)
[Thu Aug 01 08:15:42.818607 2019] [:error] [pid 102384] [remote 10.32.14.166:52]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
[Thu Aug 01 08:15:42.818624 2019] [:error] [pid 102384] [remote 10.32.14.166:52]     cursor.execute(statement, parameters)
```

**Comment by malthe** [comment]
This seems like a bug in the database driver. That statement is very strange-looking because the "bind parameters" are not actually being sent to PostgreSQL as such. This is just some string representation of the query as SQLAlchemy understands it, being sent as a statement without the processing (i.e. as you say, parameter interpolation) that should be done by the database driver.

Perhaps something wonky is going on with two threads operating on the same connection object?
