### ISSUE TITLE
[Errno 13] Permission denied: '/var/lib/ckan/ (no solution works)

### ISSUE THREAD

**Issue by mystycs** [ckan/ckan#4548]
I set my storage folder as /var/lib/ckan.

Everytime i try to upload a file through resource create i get this error

[Thu Nov 08 23:59:50.286522 2018] [:error] [pid 23021] [remote 10.172.24.4:76] Error - <type 'exceptions.OSError'>: [Errno 13] Permission denied: '/var/lib/ckan/resources/ecf'

Now i tried everything.

I ran all of these commands and nothing has helped.

My httpd runs on the user apache.
sudo chown -R apache /var/lib/ckan 
sudo chmod -R u+rwx /var/lib/ckan
sudo chmod 777 -R /var/lib/ckan

But nothing works. Do I have some funky permissions issue going on here??

[user@ckanserverckan]$ ls -l
drwxr-xr-x. 2 apache apache  4096 Nov  8 23:45 resources
drwxr-xr-x. 2 apache apache  4096 Nov  8 23:57 storage

**Comment by mystycs** [comment]
I ever tried to set permissions as root and still no success.

**Comment by mystycs** [comment]
As you can see my httpd is running as the user apache

```
root      23020  0.0  0.0 239820  5992 ?        Ss   Nov08   0:00 /usr/sbin/httpd -DFOREGROUND
apache    23021  0.8  0.6 820676 113512 ?       Sl   Nov08   0:03 ckan_default    -DFOREGROUND
apache    23022  0.6  0.6 814476 107620 ?       Sl   Nov08   0:03 ckan_default    -DFOREGROUND
apache    23023  0.0  0.0 514548  8872 ?        Sl   Nov08   0:00 demo            -DFOREGROUND
apache    23024  0.0  0.0 244104  7724 ?        S    Nov08   0:00 /usr/sbin/httpd -DFOREGROUND
apache    23025  0.0  0.0 244104  7464 ?        S    Nov08   0:00 /usr/sbin/httpd -DFOREGROUND
apache    23026  0.0  0.0 244104  6960 ?        S    Nov08   0:00 /usr/sbin/httpd -DFOREGROUND
apache    23027  0.0  0.0 244104  6960 ?        S    Nov08   0:00 /usr/sbin/httpd -DFOREGROUND
apache    23028  0.0  0.0 244104  6960 ?        S    Nov08   0:00 /usr/sbin/httpd -DFOREGROUND
apache    23091  0.0  0.0 244104  6960 ?        S    Nov08   0:00 /usr/sbin/httpd -DFOREGROUND

```

**Comment by TkTech** [comment]
To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [Gitter channel](https://gitter.im/ckan/chat) on freenode, where other developers may be able to help you.

Thanks!

**Comment by mystycs** [comment]
I just solved it!

SELinux may be enabled on CentOS. That blocks apache from writing to non-default folders. Use 'sestatus' to see if it's enabled.
More info here https://wiki.centos.org/HowTos/SELinux

**Comment by tino097** [comment]
@mystycs Great to hear that, you can always add the solution as [wiki](https://github.com/ckan/ckan/wiki) page to the repo
