### ISSUE TITLE
Resource "/download" URL returns Internal Server Error

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#4596]
### CKAN Version
CKAN from version 2.7

### Expected behaviour
When User goes to **domain_name/dataset/id/resource/res_id/download**, it shouldn't return "Internal Server Error". On CKAN 2.5 and 2.6 this URL was used as an alternative to **domain_name/dataset/id/resource/res_id/download/filename**.

### Actual behaviour
If User goes to **domain_name/dataset/id/resource/res_id/download**, it returns "Internal Server Error"

### Steps to reproduce the issue
1. Have clean CKAN 2.7
2. Storage enabled
3. Upload file and go to URL described above.

**Comment by smotornyuk** [comment]
I've tested it on all versions starting from 2.6 till current master state and issue is not reproducible. In addition, the code states that `.../download` link's behavior was not changed - it still serves the file. @Engerrs 
 probably, there are some changes/extensions in your setup

**Comment by Engerrs** [comment]
Hi @smotornyuk, it seems that it works on clean setup, but on our projects where we have our own extensions, it brakes.
Nevertheless, thank you for checking this one.
