### ISSUE TITLE
Error when uploading to Datastore, probably SSL related

### ISSUE THREAD

**Issue by plasmy** [ckan/ckan#4606]
I'm trying to upload a csv to a Datastore but I'm getting the following error:

Error: File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job retval = job.func(*job.args, **job.kwargs) File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 348, in push_to_datastore response = requests.get( resource.get('url'),verify=SSL_VERIFY ) File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/api.py", line 70, in get return request('get', url, params=params, **kwargs) File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/api.py", line 56, in request return session.request(method=method, url=url, **kwargs) File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 488, in request resp = self.send(prep, **send_kwargs) File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 609, in send r = adapter.send(request, **kwargs) File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/adapters.py", line 497, in send raise SSLError(e, request=request) SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),),)

The certificates in the server are up to date and haven't been changed recently. (https://indicadores.pr)

I did once change the variable SSL_VERIFY to None. I changed it back to False but I am still getting the error. Up until this moment it was all working just fine. Any help on this will be appreciated.

**Comment by amercader** [comment]
Can you have a look on Datapusher's issues? there are some open and closed related to the SSL and you might find the fix there: https://github.com/ckan/datapusher/issues

Thanks
