### ISSUE TITLE
IE local path: should we ignore it?

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4608]
Internet Explorer writes the full path when uploading a file if "Include local directory path when uploading files to a server" is enabled. We could strip the path to avoid long names and strange effects.

CKAN 2.8.1

Links:
 - http://commons.apache.org/proper/commons-fileupload/faq.html#whole-path-from-IE
 - https://stackoverflow.com/questions/2200100/input-type-file-for-ie-gives-full-path-need-file-name-only
 - https://stackoverflow.com/a/1130801

**Comment by wardi** [comment]
Great idea, we'd have to catch those paths somewhere around here:
https://github.com/ckan/ckan/blob/a11a03806ea4185ae0165254ad2c196b9e9ad6bb/ckan/lib/uploader.py#L164

Do you have time to submit a PR?

**Comment by frafra** [comment]
> Do you have time to submit a PR?

Yes I have.

What about patching the web interface?

https://github.com/ckan/ckan/blob/b9e45e2723d4abd70fa72b16ec4a0bebc795c56b/ckan/public/base/javascript/modules/resource-upload-field.js#L188

**Comment by wardi** [comment]
Sure that should work (we don't support using ckan with js disabled, right?)

**Comment by iamarnavgarg** [comment]
Hi @frafra are you still working on this issue??
