### ISSUE TITLE
Error emails are not sent in flask routes

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#4611]
### CKAN Version if known (or site URL)
2.8, master

### Please describe the expected behaviour
When some route generates an error and error emails are configured, stacktrace and other info are expected to be mailed in specified email address.

### Please describe the actual behaviour
If the route is migrated to flask, the error email is never sent. Most likely due to the that mailing is based on pylons error middleware https://docs.pylonsproject.org/projects/pylons-webframework/en/latest/modules/middleware.html#pylons.middleware.ErrorHandler

### What steps can be taken to reproduce the issue? 
Configure error emails.
Insert syntax error to route migrated to flask. For example view/user.py.
Error page is generated, email is not sent.

**Comment by amercader** [comment]
Yes, this was an internal Pylons feature so we lost it during the migration. It seems pretty easy to add an [email log handler](http://flask.pocoo.org/docs/1.0/logging/#email-errors-to-admins) that would replace this functionality. And perhaps there is an already existing Flask plugin that wraps this.

Marking as Good for Contribution in case @Zharktas or someone else wants to work on it.
