### ISSUE TITLE
A license more user-friendly than AGPL?

### ISSUE THREAD

**Issue by mrkafk** [ckan/ckan#4613]
Where I work Affero GPL-ed software is totally banned as this license poses substantial legal risks...

Would you pretty please consider changing license to almost anything else? GPL is OK in legal sense (mostly), if you can't accept Apache or MIT, etc..

**Comment by wardi** [comment]
We try to use the issues on this repo to track discussion around the code. For license discussion please use the mailing list or our channel on gitter https://gitter.im/ckan/chat

Thanks!
