### ISSUE TITLE
PostgreSQL Linux Centos best configurations for a CKAN production centos 7

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ckan/ckan#4634]
Hi,

This is a question only.

I'm planning to use CKAN 2.7.4 in centos 7.6 in a production environment.
I have postgreSQL 9.6 in a separate host. Then, what postgreSQL configuration is the best for a CKAN production?

In runtime execution and for a backup and restore postgreSQL.

I write this question because I am new in postgreSQL and because I saw that in the runtime it goes a little slow, and when a restore is done it goes very slowly.

Regards,
Cesar Jorge

**Comment by amercader** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [Gitter channel](https://gitter.im/ckan/chat) on freenode, where other developers may be able to help you.

Thanks!
