### ISSUE TITLE
Replace Paste with Click

### ISSUE THREAD

**Issue by kmbn** [ckan/ckan#4639]
Replace all Paste/paster with Click if they're CLI commands or with another approach if they're used internally.

This is required for migrating from Pylons to Flask and for enabling Python 3 compatibility.

## Approach

User-wise we are going from this:

    paster search-index rebuild

To this:

    ckan search-index rebuild

The goal is to move all commands in `ckan/lib/cli.py` to the new `ckan/cli` folder. The already migrated commads in the `cli` folder should be self-explanatory but overall the process is:

* Pick a pending command from the list below and create a new file for it in `ckan/cli`
* Add a entrypoint using `@click.group`, eg:
    ```
    @click.group(name=u'db', short_help=u'Database commands')
    def db():
        pass
    ```
* Add individual subcommands. In most cases the actual code used in the current cli will remain unchanged, but of course feel free to add any improvements that you consider worth doing.
    ```
    @db.command(u'upgrade', short_help=u'Upgrade the database')
    @click.option(u'-v', u'--version', help=u'Migration version')
    def updatedb(version=None):
        # ...
    ```
* Add the command to the end of the `ckan/cli/cli.py` file

### Current status

 paster command | descritpion | status | ckan command 
  -------------------- | ----------------- | -------- | ---------------------
  check-po-files  |  Check po files for common mistakes |  migrated | `ckan translation`
  color             | Create or remove a color scheme.| drop it|
  config-tool      | Tool for editing options in a CKAN config file | migrated
  create-test-data |  Create test data in the database. | migrated | renamed to `seed`|
  datapusher      |  Perform commands in the datapusher | migrated |
  dataset         |  Manage datasets | migrated |
  datastore      |   Perform commands to set up the datastore | migrated|
  db          |      Perform various tasks on the database. | migrated | `ckan -c ckan.ini db` |
  front-end-build |  Creates and minifies css and JavaScript files | migrated
  jobs           |   Manage background jobs | migrated
  less         |     Compile all root less documents into their CSS counterparts | migrated
  minify       |     Create minified versions of the given Javascript and CSS files.| migrated
  notify        |    Send out modification notifications. | migrated
  plugin-info   |    Provide info on installed plugins. | migrated
  profile       |    Code speed profiler | migrated
  ratings       |    Manage the ratings stored in the db | drop it|
  rdf-export    |    Export active datasets as RDF | drop it, if useful will be ported to ckanext-dcat |
  search-index  |     Creates a search index for all datasets | migrated | `ckan -c ckan.ini search-index `|
  sysadmin     |     Gives sysadmin rights to a named user | migrated |
  tracking      |    Update tracking statistics | migrated
  trans       |      Translation helper functions | migrated | `ckan translation`
  user        |      Manage users | migrated | 
  views      |       Manage resource views. | migrated

In this table is not included the `paster serve` command which is already migrated as `ckan run` as part of the #4412, including migration of `paster db` and `paster search index` commands

**Comment by kmbn** [comment]
If anyone is interested in helping out on this issue—I've assigned it to myself, and I'll be working on it, but I'd be glad to have help.

**Comment by tino097** [comment]
Just for reference https://github.com/ckan/ckan/issues/4291

**Comment by iamarnavgarg** [comment]
> If anyone is interested in helping out on this issue—I've assigned it to myself, and I'll be working on it, but I'd be glad to have help.

Hi @kmbn do we need to change the paster commands in all ckan files(logic,controller,lib etc) ?

**Comment by tino097** [comment]
paster command | descritpion | status | ckan command 
  -------------------- | ----------------- | -------- | ---------------------
  check-po-files  |  Check po files for common mistakes |  
  color             | Create or remove a color scheme.|
  config-tool      | Tool for editing options in a CKAN config file |
  create-test-data |  Create test data in the database. |
  datapusher      |  Perform commands in the datapusher |
  dataset         |  Manage datasets |
  datastore      |   Perform commands to set up the datastore |
  db          |      Perform various tasks on the database. | migrated | `ckan -c ckan.ini db` |
  front-end-build |  Creates and minifies css and JavaScript files |
  jobs           |   Manage background jobs |
  less         |     Compile all root less documents into their CSS counterparts |
  minify       |     Create minified versions of the given Javascript and CSS files.|
  notify        |    Send out modification notifications. |
  plugin-info   |    Provide info on installed plugins. |
  profile       |    Code speed profiler |
  ratings       |    Manage the ratings stored in the db |
  rdf-export    |    Export active datasets as RDF |
  search-index  |     Creates a search index for all datasets | migrated | `ckan -c ckan.ini search-index `|
  sysadmin     |     Gives sysadmin rights to a named user |
  tracking      |    Update tracking statistics |
  trans       |      Translation helper functions |
  user        |      Manage users |
  views      |       Manage resource views. |

In this table is not included the `paster serve` command which is already migrated as `ckan run` as part of the #4412, including migration of `paster db` and `paster search index` commands

**Comment by iamarnavgarg** [comment]
> If anyone is interested in helping out on this issue—I've assigned it to myself, and I'll be working on it, but I'd be glad to have help.

Hi @kmbn I am interested in this issue.

**Comment by davidread** [comment]
@iamarnavgarg Thanks for offering to help with this! The paster commands are listed in the table above and the code is all in ckan/lib/cli.py, so I'm not clear what you're saying about paster commands in logic etc. Maybe you can point to the bit in the code you're talking about?

**Comment by pdelboca** [comment]
I have submitted a PR to implement `plugin-info` command and I can work on the following commands in the next days/weeks! Feel free to assign it to me :)

**Comment by vesnikos** [comment]
Hi, I thought I could contribute a bit in this migration task from parser to click as a potentil new contributor.  I did _locally_ in my machine the `jobs` command + subcommands, but I couldn't find a test suite for click cli's, so I don't know what's the best way to test the changes

**Comment by davidread** [comment]
@vesnikos That's great, do you want to submit a PR? There are no tests for cli at the moment (sad), so no worse than before - just test manually.

**Comment by amercader** [comment]
All commands done now. Thanks to everyone who contributed. New tickets for the remaining tasks:

* Commands from extensions: #5108 
* Documentation: #5109 
* Cleanup: #5110
