### ISSUE TITLE
CSS word wrap broken on Firefox

### ISSUE THREAD

**Issue by howff** [ckan/ckan#4642]
Words are wrapped by breaking them in the middle.

See Chrome on left (correct) Firefox on right (broken)

[https://pasteboard.co/HYGUgnx.png](https://pasteboard.co/HYGUgnx.png)

### CKAN Version if known (or site URL)

2.8

### Please describe the expected behaviour

Words are wrapped at whitespace (unless a word really is is very long)

### Please describe the actual behaviour

Words are wrapped in the middle of the word (Firefox only, it's ok in Chrome)

### What steps can be taken to reproduce the issue? 

Look at the list of organisations

**Comment by smotornyuk** [comment]
I checked possible solution and it seems, that there is no perfect way to make long titles looks similar in chrome and FF. You may get rid of this word breaking by setting `word-break: break-word`, but then long lines won't be split in FF. Instead, if you are using `white-space: pre-wrap` with auto hyphens - FF still breaks words wherever it possible(pic below), the only difference - it's adding hyphens after breaks, but I don't think that it's valuable enough to add this into stylesheets
![screenshot from 2019-02-25 17-38-02](https://user-images.githubusercontent.com/11091199/53349521-f7793600-3925-11e9-8047-84bb21310713.png)

Any suggestions, @howff ?

**Comment by howff** [comment]
overflow-wrap: break-word; ?

(exactly where are you changing the CSS so that I can test this?)

**Comment by smotornyuk** [comment]
Issue fixed in CKAN v2.8.3
Closing the issue.
