### ISSUE TITLE
Docker install fails to start ckan container: exit code 127 can't find /ckan-entrypoint.sh

### ISSUE THREAD

**Issue by DerekW24** [ckan/ckan#4652]
### CKAN Version if known (or site URL)
git 2.8.2 version. 

### Please describe the expected behaviour
Following instructions https://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html to install on a RHEL7 system with Docker-CE 18.09.1 installs complete. But CKAN fails to start.
Customizations:
CKAN_MAX_UPLOAD_SIZE_MB=5000 
Needed to add CKAN_MAX_UPLOAD_SIZE_MB to keep from getting an error during the ckan build process, Variable not mentioned in .env.template

docker-compose logs -f ckan shows
ckan  | /bin/sh: 0: Can't open /ckan-entrypoint.sh
ckan exited with code 127

### Please describe the actual behaviour

docker-compose restart ckan produces the same error.
Since the container doesn't start I am not sure how to connect to it and see what is really wrong.

### What steps can be taken to reproduce the issue? 
removed the docker containers and reinstalled with the same results.  Also tried the latest git master.

**Comment by DerekWerthmuller** [comment]
I think this maybe related to this Docker issue.  Docker tries to set extended attribute.  
https://github.com/moby/moby/issues/38155

Going to try and downgrade to Docker v17

**Comment by DerekWerthmuller** [comment]
Update again: tried Docker v17 and have the same error.
I'm wondering if this is a ckan-entrypoint.sh permission error.  The ckan user can't execute the ckan-entrypoint.sh .  Here is what I've done.
> docker run -ti --entrypoint /bin/sh docker_ckan
> whoami
ckan
>ls -l /ckan-entrypoint.sh
rwxr-x--x      root root   /ckan-entrypoint.sh

Would I be able to run CKAN with part of the installation (redis, datapusher, db) via docker and ckan its self via source.  like a combined install.  Would that work?

**Comment by DerekWerthmuller** [comment]
Here is the solution to the problem:
Primary docker file: https://github.com/ckan/ckan/blob/master/Dockerfile
   Line # 53 chmod +x /ckan-entrypoint.sh && \
Change to:
chmod 755 /ckan-entrypoint.sh && \

Container builds and starts once this change has been made.  Its a minor but important change.

**Comment by mroutis** [comment]
@DerekWerthmuller , I couldn't replicate your issue with `ckan-2.8.2` :disappointed: 

The whole Docker thingy is working good for me:
```
Storage Driver: overlay2
Runtimes: runc
OSType: linux
Docker version: 18.09.1-ce
```

Also, `chmod +x` and `chmod 755` does kindof the same thing, at least, it allows any user to execute the file (755 is more specific, as it explicitly sets all the permissions), usually when you create a new file, the default permission mask is `644` so modifying it with `+x` will set it to `755`.

**Comment by DerekWerthmuller** [comment]
The chmod +x works well when you can predict the default system umask as 0022.  But on some systems the default umask is different for various reasons.  We needed to be specific when setting the permissions to because our system umask is not 0022.

The CKAN_MAX_UPLOAD_SIZE_MB was an error that we caught when looking at errors during the Docker build process,  its not critical but an error we found in the process.

**Comment by blavoie** [comment]
I can confirm that chmod 0755 does the trick...

**Comment by Metuphysics** [comment]
Alpine uses a different package manager(apk) than debian based 
So, I recommend u use alpine base like  `FROM node:17-alpine` or etc...
