### ISSUE TITLE
datastore_search returns most relevant records last 

### ISSUE THREAD

**Issue by Br3nda** [ckan/ckan#4660]
### CKAN Version if known (or site URL)
data.govt.nz

### Please describe the expected behaviour
When querying the `datastore_search` API method,  we expected the most relevant results to be listed first. basically `ORDER BY rank DESC`

(relevant means that they closely march the search query)

When querying for "age concern" we expected results with this exact phrase to be first.

### Please describe the actual behaviour

the most relevant results are listed last. `ORDER BY rank `
results containing only "age" or only "concern" are in the first pages of results, and "age concern" is in the last pages.

### What steps can be taken to reproduce the issue? 

http GET `{server}/datastore_search?distinct=true&plain=false&resource_id={resource}&q={keyword}&limit=10`;

e..g 
https://catalogue.data.govt.nz/api/3/action/datastore_search?resource_id=35de6bf8-b254-4025-89f5-da9eb6adf9a0&q=age+concern&limit=10

results for "age" or "concern" are in the first pages.
results for "age concern" are in the last pages

**Comment by wardi** [comment]
Wow, that's not good. Care to submit a PR? I think we just need a "DESC" after each value here https://github.com/ckan/ckan/blob/master/ckanext/datastore/backend/postgres.py#L474 and a quick test to prevent regressions

**Comment by Br3nda** [comment]
i've given it a go on #4661
