### ISSUE TITLE
Dataset notes markdown h1 headings same size as h2

### ISSUE THREAD

**Issue by shevron** [ckan/ckan#4665]
### CKAN Version if known (or site URL)
2.8.2

### Please describe the expected behaviour
All rendered markdown headings to be of different size where top level headings are always strictly greater than lower level headings. 

### Please describe the actual behaviour
Some of the rendered markdown blocks (e.g. dataset "notes") have 1st level headings at the same size as 2nd level headings which is confusing

### What steps can be taken to reproduce the issue? 
1. Create a new dataset with the following markdown content in notes:

    # 1st level heading
    some text
    
    ## 2nd level heading
    more text

2. Look at the dataset overview, and notice that "1st level heading" and "2nd level heading" are the same size.

**Comment by shevron** [comment]
In general it looks like `.embedded-content h1` and `.embedded-content h2` are the same size.

**Comment by amercader** [comment]
@shevron sounds good, do you want to submit a PR? :)
