### ISSUE TITLE
Install CKAN in a Cloud VM with Private IP

### ISSUE THREAD

**Issue by BlueRoy** [ckan/ckan#4667]
I installed CKAN 2.8.2 in a cloud server with private ip `a.b.c.d`. To access the web site from outside, I configured a port forwarding rule from public ip `e.f.g.h:10100` to `a.b.c.d:80`. Moreover, I deployed CKAN with Apache and Nginx following the [Deploying a source install](https://docs.ckan.org/en/2.8/maintaining/installing/deployment.html) instruction.

Now I can access CKAN home page with `http://e.f.g.h:10100`, however the login process will redirect the page to `http://e.f.g.h/user/login...` which is not accessible because of the missing port in the url.

In production.ini file, I have configured `ckan.site_url = http://e.f.g.h:10100`. However, it seems the port will be ignored after page redirection.

What do I miss in the configurations (e.g., apache, nginx or ckan production.ini)?

**Comment by tino097** [comment]
Hi @BlueRoy , thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the Gitter [#ckan](https://gitter.im/ckan/chat) channel, where other developers may be able to help you.

Thanks!
