### ISSUE TITLE
Help neded on configuring CKAN data explorer

### ISSUE THREAD

**Issue by vinga2805** [ckan/ckan#4668]
Hi All,

Can anyone help me on configuring data explorer on CKAN?
Any document?

Thanks and Regards,
Vishal Ingale

**Comment by vinga2805** [comment]
We have also configured below plugins in our config file.
stats text_view 
image_view 
recline_view 
datapusher 
datastore resource_proxy 
geo_view 
pages 
harvest 
ckan_harvester 
ldap

**Comment by tino097** [comment]
Hi @vinga2805 , thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the Gitter [#ckan](https://gitter.im/ckan/chat) channel, where other developers may be able to help you.

Thanks!
