### ISSUE TITLE
Remove references from paste for using asbool, aslist and asint

### ISSUE THREAD

**Issue by dportoles** [ckan/ckan#4670]
As @kmbn  mentioned in https://github.com/ckan/ckan/pull/4638#issuecomment-458063189 we need to stop using paste. Also is related to https://github.com/ckan/ckan/issues/4639

It's a fact that there're too many imports of paste related to the use of asbool function (also asint & aslist but it's hardly ever used).

As a first step I propose to unify the use of asbool in plugins.toolkit in order to remove paste import to only one file.

In future there should be changed also this unique import (plugins.toolkit) but... what do you think is the best approach? IMHO we could rewrite a function similar to current asbool implementation. Should we copy directly from paste?

**Comment by amercader** [comment]
That sounds really reasonable @dportoles. It can be a two stage process:

1. Rewrite all imports in the code to point to the plugins.toolkit `asbool` (and others if necessary)
2. Refactor the `asbool` function in toolkit to not rely on the paster implementation.

Do you want to have a go at it?

**Comment by dportoles** [comment]
ok @amercader!
I can try to develop a PR for this issue,  so I will assign it to me

**Comment by chandradeep03** [comment]
@dportoles , @amercader  Is someone working on this issue?

**Comment by amercader** [comment]
No @chandradeep03 , would you like to work on this if @dportoles does not have time? More details here: https://github.com/ckan/ckan/issues/4797

I'll close this issue in favour of the above

**Comment by Chandradeep-NEC** [comment]
@amercader 
Thanks. 
We are working on this issue
