### ISSUE TITLE
Indexes lost

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4676]
### CKAN Version if known (or site URL)
2.8.2

### Please describe the expected behaviour
Indexes should not be lost.

### Please describe the actual behaviour
Indexes are lost.

### What steps can be taken to reproduce the issue? 
This happens from time to time. I think that it could happen when the disk is full.

**Comment by amercader** [comment]
We need more details here @frafra . Is that in Docker? The solr index volumes are not persisted?

**Comment by frafra** [comment]
Docker, persistent volumes, recreating indexes works. Files return 404 at the moment, even if they are available. I will investigate in the following days and come back with more details.

**Comment by frafra** [comment]
Fixed, solr volume was missing from the Docker compose file.
