### ISSUE TITLE
recaptcha is broken on 2.8

### ISSUE THREAD

**Issue by krupalip** [ckan/ckan#4680]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8

### Please describe the expected behaviour
user registration page should show recaptcha checkbox

### Please describe the actual behaviour
recaptcha checkbox is not showing up

### What steps can be taken to reproduce the issue? 
install ckan 2.8 and click on register to get user registration page.
set captcha public and private key in ckan.ini file

**Comment by krupalip** [comment]
solution:
change recaptcha.html - remove captcha version
and captcha.py - change request.params to request.form

**Comment by sivang** [comment]
Wasn't this fixed 2 weeks ago? If so can be closed?

**Comment by amercader** [comment]
Fixed in https://github.com/ckan/ckan/pull/4732
