### ISSUE TITLE
Old DataPusher version included in latest packages

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4682]
This was flagged in this message to the list:

https://lists.okfn.org/pipermail/ckan-dev/2019-March/023079.html

I downloaded python-ckan_2.8-trusty_amd64.deb and python-ckan_2.8-xenial_amd64.deb from http://packaging.ckan.org/ and while the CKAN versions are correct, the DataPusher version included is 0.0.12. The one used in the latest packaging script is [0.0.14](https://github.com/ckan/ckan-packaging/blob/master/package.yml#L102) and there's a new one that could be used (0.0.15).

I'm not sure what happened here, probably packaging using and outdated version of the Ansible scripts but can you look at this @tino097?

* Check if the latest packages for 2.7 and 2.6 from the previous release also need updating. (download them, run `dpkg -x package.deb folder` and check `usr/lib/ckan/datapusher/src/datapusher/__init__.py`)
* Update the packages to use latest DataPusher version
* Rebuild the packages and reupload

**Comment by tino097** [comment]
Done

**Comment by amercader** [comment]
Thanks @tino097!
