### ISSUE TITLE
Add `extras_require` to include test dependencies for better extensions testing

### ISSUE THREAD

**Issue by adborden** [ckan/ckan#4689]
As an extension developer, I want `pip install ckan[test]` to install ckan as well as any test dependencies so that I don't have to worry about what ckan depends on when writing unit tests for my ckan extensions.

Setuptools allows you to specify `extras_require` so that consumers can [install dependencies for additional features](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), like testing utilities.

### CKAN Version if known (or site URL)
N/A

### Please describe the expected behaviour
`pip install ckan` doesn't bring in all the test dependencies.

### Please describe the actual behaviour
The code below fails with import errors.

I have to install ckan, and then look at ckan's requirements.txt to install test dependencies one by one and have no way to keep that updated in my extension.

### What steps can be taken to reproduce the issue? 
```python
# ckanext/myextension/tests/test_example.py
import ckan.tests
import paste.fixture
import pylons.test

class TestMyExtension(object):
    def setup(self):
        self.app = paste.fixture.TestApp(pylons.test.pylonsapp)

    def test_show_package_hook(self):
         ckan.tests.call_action_api(self.app, 'package_show', id='non-exist')
```

**Comment by smotornyuk** [comment]
You've probably missed [this section in the docs](https://docs.ckan.org/en/2.8/contributing/test.html#install-additional-dependencies). Generally, every dev has a source installation of CKAN, where you can find dev-requirements.txt that already contains all necessary libs. As for listing requirements in setup.py - we are trying to use requirements files instead(there are few closed issues and some articles on the web, that explains our point of view in details)

**Comment by adborden** [comment]
That makes sense for general CKAN development, but it makes "drive-by" contributions to extensions very difficult. In this model, a potential contributor needs to setup a full-blown CKAN dev install just to fix a bug in an extension and write/run a test case. Most extensions also don't link to the CKAN docs for development setup, so if you're unfamiliar with CKAN, there's a steep learning curve and barrier to entry.

If you could link to those resources, that would be helpful, since IMHO this is contrary to best practice. I don't mean to harp on this, but as an example, I opened this issue previously and the conversation has stalled https://github.com/ckan/ckan/issues/4590

**Comment by smotornyuk** [comment]
From this point of view, it has a lot of sense. I've created [PR](https://github.com/ckan/ckan/pull/4731) for documentation. This note will be displayed at the top of `Writing extension tutorial` and, hopefully, will make the life of contributors a little bit easier. @adborden , what do you think about such solution?
