### ISSUE TITLE
form.checkbox breaks down when is_required=True

### ISSUE THREAD

**Issue by filipporemonato** [ckan/ckan#4693]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### Please describe the expected behaviour
Wanted to extend the "new user" registration form with a checkbox for "I have read and agree to the user's licence". For this, I made a plugin that modifies the `user/new_user_form.html` template, and added the chekbox using the macro `form.checkbox` command, following the style of the form that is already in place. The checkbox must be flagged as required, so I set `is_required=True`. This last thing makes the code crash when loading the page.

### Please describe the actual behaviour
The code breaks down and crashes on page load. This is because `macros/form.html` calls a function `input_required()` when `is_required=True`, with
`{% if is_required %} {{ input_required() }} {% endif %}`
but such function is not defined anywhere. It seems like someone had an idea and forgot to implement it.

### What steps can be taken to reproduce the issue? 
Make a form with a checkbox with the parameter `is_required=True`

**Comment by amercader** [comment]
Yes, this line is a leftover and should be removed. The `is_required` param is used on this line of [another macro](https://github.com/ckan/ckan/blob/9dd6b2c6b3c79781509a447af534cc0ae540d644/ckan/templates/macros/form.html#L277) not called on the checkbox one, so I guess the checkbox macro markup needs to be updated to include the `{% if is_required %}<span title="{{ _("This field is required") }}" class="control-required">*</span> {% endif %}` bit.

Do you want to submit a PR?

**Comment by sivang** [comment]
I'll submit a PR @amercader  , I just hit that as well when implementing a checkbox preset. I dropped the line altogether and it works nicely, is the change you mention in the prev note mandatory?

**Comment by sivang** [comment]
discussion with @amercader :
Disable all extension, remain only with CKAN core, and test to see if error message when field was not supplied remains-> then add the suggested code.

**Comment by amercader** [comment]
Fixed in b60caf7
