### ISSUE TITLE
CKAN from web panel not create a datastore when create a dataset and upload data

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ckan/ckan#4698]
### CKAN Version if known (or site URL)
CKAN 2.7.5 (https://github.com/ckan/ckan/blob/ckan-2.7.5)

### Please describe the expected behaviour
CKAN from web panel not create a datastore when create a dataset and upload data.
From web:
Click in Datasets->Add Dataset
Title: datasetexample
Click in Next: Add Data
Then click Upload and select a CSV file (as example)
Click in Finish
Then click in Explore->Preview
Then show visualize the data

### Please describe the actual behaviour
CKAN from web panel not create a datastore when create a dataset and upload data.
From web:
Click in Datasets->Add Dataset
Title: datasetexample
Click in Next: Add Data
Then click Upload and select a CSV file (as example)
Click in Finish
Then click in Explore->Preview
Then show error (and not visualize nothing):  This resource view is not available at the moment

How to fix in code (or an ini parameter) this behaviour for CKAN 2.7.5, without force execute an API call to change anything?
Investigating a bit, the associate resource is created as "datastore_active" to False.
Then, in the recline views, show that try to access to an external URL called "jsonpdataproxy.appspot.com".

### What steps can be taken to reproduce the issue? 
CKAN from web panel not create a datastore when create a dataset and upload data.
From web:
Click in Datasets->Add Dataset
Title: datasetexample
Click in Next: Add Data
Then click Upload and select a CSV file (as example)
Click in Finish
Then click in Explore->Preview

**Comment by tino097** [comment]
Please check the docs, it looks like datastore permissions issue 

https://docs.ckan.org/en/2.8/maintaining/datastore.html#set-permissions

**Comment by cesarjorgemartinez** [comment]
The datastore permissions are created correctly as shows in the docs.
Is from web panel when not create the datastore (from API works).

**Comment by cesarjorgemartinez** [comment]
I need to install the Datapusher to work with this uploads from UI?

**Comment by tino097** [comment]
If this is related to [stackoverflow](https://stackoverflow.com/questions/55205900/ckan-datastore-bad-request-action-name-not-known-datastore-search) it looks its already solved
