### ISSUE TITLE
Paster always return 0 error code

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ckan/ckan#4704]
### CKAN Version if known (or site URL)
CKAN 2.7.5

### Please describe the expected behaviour
Paster error codes returned to the shell.

### Please describe the actual behaviour
Always returns 0

### What steps can be taken to reproduce the issue? 
With myuser already exists:

paster --plugin=ckan user add myuser password="mypassword" email="email@test.com" --config=/etc/ckan/default/development.ini
  echo $?

Then return code 0:

Traceback (most recent call last):
  File "/usr/local/ckan/venv_valencia/src/ckan/ckan/lib/cli.py", line 132, in user_add
    user_dict = logic.get_action('user_create')(context, data_dict)
  File "/usr/local/ckan/venv_valencia/src/ckan/ckan/logic/__init__.py", line 457, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/local/ckan/venv_valencia/src/ckan/ckan/logic/action/create.py", line 961, in user_create
    raise ValidationError(errors)
ValidationError: {'name': ['That login name is not available.']}
0

**Comment by smotornyuk** [comment]
That happens because this username already used. Try different name

**Comment by amercader** [comment]
@cesarjorgemartinez You are right that paster is handling this incorrectly. We are migrating away from the paster CLI to a new click based one (https://github.com/ckan/ckan/issues/4639), which hopefully handles error codes better.
