### ISSUE TITLE
Command paster not found with Windows Environement

### ISSUE THREAD

**Issue by developper-ing** [ckan/ckan#4714]
Hi,
I'm working to install CKAN platform within windows Environement And I follow the guides mentioned via this link https://github.com/ckan/ckan/wiki/How-to-Install-CKAN-2.5.2-on-Windows-7
But arriving to instruction 10 ((ckan) C:\src\ckan>paster make-config ckan development.ini), the paster command is mentioned as not recongized as an internal or external command.
How can I resolve this issue noting that I used an other script to install paster (virtualenv paster) but it does not working.

**Comment by amercader** [comment]
@developper-ing We don't support CKAN in Windows. The wiki page you link to was created by some community member and is probably out of date. You might have some luck in the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) but you are probably better off deploying CKAN in a supported OS like Ubuntu.
