### ISSUE TITLE
API response help link is nonsense when root_path is set

### ISSUE THREAD

**Issue by cdn** [ckan/ckan#4722]
### CKAN Version if known (or site URL)

2.8.2/master(2.9.0a0)

### Please describe the expected behaviour

help URL in API returns has root_path inside URL
http://domain.tld/data/api/3/help_show?name=package_list

### Please describe the actual behaviour

help URL has root_path prepended
/datahttp://domain.tld/api/3/help_show?name=package_list

### What steps can be taken to reproduce the issue? 

Install either 2.8.2 or master
configure with root_path = /{{LANG}}/data

$ paster serve /etc/ckan/default/development.ini &
$ curl http://localhost:5000/api/action/package_list

**Comment by iamarnavgarg** [comment]
Hi @cdn, can you please provide more detailed step to reproduce the issue?

**Comment by cdn** [comment]
> Hi @cdn, can you please provide more detailed step to reproduce the issue?

Where would you like more detail?
