### ISSUE TITLE
Could not load view: DataProxy returned an error

### ISSUE THREAD

**Issue by dpadron** [ckan/ckan#4738]
Hello,
I installed Ckan using Dockers
On ubuntu 16.04
using the ckan repo master
The following error is generated when you try to display a view of the .xlsx data.

Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)

Has anyone managed to fix it, any clue?

![error_ckan](https://user-images.githubusercontent.com/7094961/56390254-e8c74500-622b-11e9-931a-7c0421a3fe83.jpg)

**Comment by wardi** [comment]
Hello @dpadron, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the Gitter #ckan channel, where other developers may be able to help you.

Thanks!
