### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'transaction'

### ISSUE THREAD

**Issue by jfni** [ckan/ckan#4751]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.9.0a Docker installation

### Please describe the actual behaviour

I do the following:
When a new package is added with an Excel in it, I convert the individual worksheets to .csv and add them to the draft package. I do this with a plugin, using the notify function. I end up at a CKAN page, saying "An internal server error occurred". In the logs I find the attached error:

[error_report.txt](https://github.com/ckan/ckan/files/3121705/error_report.txt)

**Comment by amercader** [comment]
Hi @jfni. This seems related to a problem with how you manage the session on your extension code. Perhaps if you share it someone can help. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Feel free to reopen if you think this is actually an issue with CKAN core.
Also we don't recommend using the master branch, and rather the latest stable version (2.8.x)
