### ISSUE TITLE
Database clean error with the new cli command

### ISSUE THREAD

**Issue by tino097** [ckan/ckan#4764]
With the migrated commands for database, im getting an error when executing database clean command

       ```
       ckan db clean 
      ```
results with
```
    (psycopg2.InternalError) cannot drop table spatial_ref_sys because extension postgis requires it
    HINT:  You can drop extension postgis instead.
    [SQL: '\nDROP TABLE spatial_ref_sys CASCADE']
```

additional info my database is set with docker

**Comment by jonathansberry** [comment]
I'm hitting this problem and struggling to find any info on it.  Was it ever resolved?

**Comment by ghn** [comment]
Same problem here with `paster`

`paster db clean -c /etc/ckan/production.ini`

> cannot drop table spatial_ref_sys because extension postgis requires it
> HINT:  You can drop extension postgis instead.

with CKAN 2.8.3

**Comment by ghn** [comment]
@tino097 any reason you closed this issue? Is there a work around?

**Comment by ghn** [comment]
Hi, thanks for your response.
Yes that's what I did in psql `drop extension PostGIS cascade`. Still it's weird that paster command fails with fresh ckan install. Looks like a bug to me

**Comment by nickumia-reisys** [comment]
I did `drop extension IF EXISTS postgis cascade;` and the `db clean` command still fails with the same error, 

```
sqlalchemy.exc.InternalError: (psycopg2.InternalError) cannot drop table spatial_ref_sys because extension postgis requires it
HINT:  You can drop extension postgis instead.
 [SQL: '\nDROP TABLE spatial_ref_sys CASCADE']
```

**Comment by nickumia-reisys** [comment]
For anyone else who had the same issue, my problem was making sure I was referencing the right database and dropping the extension at the right time.  It had to be after the databases were initialized and the call to `[SQL: 'SELECT postgis_lib_version()']`, but before the first call of `db clean` or `reset_db`
