### ISSUE TITLE
Remove vdm

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4783]
Now that the revisioning has been removed and activities expanded (#3972) removing VDM is the single major blocker to the Python 3 migration. We can't start working on running CKAN in Python 3 until it is removed, as it is used at a very low level and very early in the initialization code.

Current PR: https://github.com/ckan/ckan/pull/4784 (and @davidread previously did some exploratory work on https://github.com/ckan/ckan/pull/4664/, and @TkTech showed [interest](https://github.com/ckan/ckan/pull/3972#issuecomment-465523145).

The following issues have been flagged:

Observations:

* `user_dict.number_of_edits` is removed, as calculating that relied on revisions
* `stats` extension loses all the stats time-line, as calculating those relied on revisions. could be resurrected with activitie stream data.
* trash page removed (no revisions to trash)
* `migrate_filestore` won't work any more

The items above all seem fine to lose for me, including the stats extension which hasn't had any development in ages.

Not working:
* fix up activities - they are not being created for some reason
* migration

These need to be fixed as part of the work.

#### Approach

@davidread covered all the things involved in the actual removal of VDM and the revisioning: low level stuff when initializing the database, revision based columns and methods on the models, removing explicit revision creation calls, etc.

The second part of the work will be of course to make everything work as expected, fixing the activities problems, migration etc.

#### Story points

13

**Comment by amercader** [comment]
@davidread I added some more detail to include this issue in the Py 3 roadmap. Feel free to rewrite anything
