### ISSUE TITLE
Flask and Python 3 support on selected extensions

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4793]
At least for the most used extensions on the ckan organization we should make sure they are ready for a Python 3 / Flask only version of CKAN. @davidread compiled a list of candidates and potential coordinators in #4681. It unlikely that the persons listed will be able to do all of them but if we do a couple of the critical ones first and document all the steps in the documentation (see #XXXX) that is a task where the wider community can definitely help us. I'd suggest focusing on ckanext-scheming and ckanext-dcat first, one because it's pretty critical and widely used and the other because I've already made some work on it.

- [x] [ckanext-scheming](https://github.com/ckan/ckanext-scheming) - 3 - @smotornyuk
- [x] [ckanext-dcat](https://github.com/ckan/ckanext-dcat) - 5 - @smotornyuk
- [x] [ckanext-xloader](https://github.com/ckan/ckanext-xloader) - 2
- [x] [ckanext-harvest](https://github.com/ckan/ckanext-harvest) - 5 - @smotornyuk
- [x] [ckanext-spatial](https://github.com/ckan/ckanext-spatial) - 5 - @smotornyuk
- [x] [ckanext-pages](https://github.com/ckan/ckanext-pages) - 3
- [x] [ckanext-geoview](https://github.com/ckan/ckanext-geoview) - 2 - @smotornyuk
- [x] [ckanext-googleanalytics](https://github.com/ckan/ckanext-googleanalytics) - 3 - @smotornyuk
- [ ] [ckanext-qa](https://github.com/ckan/ckanext-qa) - 5 - @shubham-mahajan
- [x] [ckanext-showcase](https://github.com/ckan/ckanext-showcase) - 5 - @smotornyuk
- [x] [ckanext-pdfview](https://github.com/ckan/ckanext-pdfview) - 2 - @smotornyuk
- [x] [ckanext-archiver](https://github.com/ckan/ckanext-archiver) - 5 - @Zharktas 
- [x] [ckanext-fluent](https://github.com/ckan/ckanext-fluent) - 2
- [x] [ckanext-hierarchy](https://github.com/ckan/ckanext-hierarchy) - 2 - @smotornyuk
- [x] [ckanext-report](https://github.com/davidread/ckanext-report) - 2 - @Zharktas 

TODO
add syndication - @smotornyuk
add cloudstorage - @smotornyuk

#### Approach

For each extension:

* Check if any extension requirement is Python 2 only, replace if so
* Enable the Flake 8 tests that will flag any Python 3 compatibility issues (there are several PRs by @Zharktas enabling this)
* All imports through the toolkit. Use [ckantoolkit](https://github.com/ckan/ckantoolkit) if necessary.
* Migrate `IMapper` + `BaseController` instances to `IBlueprint` + Blueprints

The main challenge with this task will be extensions that need to support different CKAN versions (so pretty much all of the ones in the ckan organizastion). There are variuos things that work differently pre and post Flask migration, eg:

* Templates don't use `c` variables in newer versions
* `IMapper` vs `IBlueprint`
* ...

In some cases you can use selectively one feature or the other depending on the CKAN version, eg:

```python
class MyPlugin(p.SingletonPlugin):
    """My plugin."""

    if p.toolkit.check_ckan_version(min_version='2.8.0'):
        p.implements(p.IBlueprint)
    else:
        p.implements(p.IRoutes, inherit=True)    

    # Ignored on CKAN >= 2.8
    def before_map(self, map):
        # ...

    # Ignored on CKAN < 2.8
    def get_blueprint(self):
        # ...
    
```

On others like templates using `c` it might be a bit more tricky and we might end up with two sets of templates or different branches for different versions.

It is worth remembering that `IBlueprint` has been around since 2.7 so depending on the extension we might just decide to support from that version onwards and remove support for the Pylons based controllers.

#### Story points

3-5 per extension, depending on complexity (now added to the list above)

Total: 47 points

**Comment by davidread** [comment]
Analysis of the extensions is here: https://docs.google.com/spreadsheets/d/1oEAp68C8aGQj08vU9pVSAoDDICYR-y9EUl4Aunz45Lc/edit#gid=346652840
I've recently extended it to include the number of lines of python code, to enable estimation of story points. I've added these above.

**Comment by TkTech** [comment]
What py3 are we aiming for? 3.6+? (fstrings woo)

**Comment by wardi** [comment]
or 3.7+ for context variables and dataclasses

**Comment by wardi** [comment]
Maybe add https://github.com/ckan/ckantoolkit and https://github.com/ckan/ckanapi to this list

**Comment by shubham-mahajan** [comment]
@amercader Shall I take https://github.com/ckan/ckanext-qa?

**Comment by kowh-ai** [comment]
@shubham-mahajan I don't think anyone is assigned to this yet @smotornyuk: what do you think?

**Comment by davidread** [comment]
@shubham-mahajan ckanext-qa is maintained by @Zharktas. I assume there is no issue with creating PRs on any extension that get us closer to python3 compatibility.

Note to all: our guide for doing the conversion is here: https://github.com/ckan/ckan/wiki/Migration-guide-for-extensions

**Comment by smotornyuk** [comment]
Yep, everyone is on holiday, so there no current work on listed extensions. It would be really cool to have your help with ckanext-qa

**Comment by shubham-mahajan** [comment]
@davidread Then I am taking up this one.

**Comment by amercader** [comment]
Most commonly used extensions support CKAN .9 / Python 3
