### ISSUE TITLE
Replace webhelpers with a modern alternative

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4794]
Webhelpers is not maintained and Python 2 only, so it needs to be replaced. We use webhelpers for:

- [x] Generating the Atom feeds in the feeds blueprint
- [x] Building pagination for search results (pager objects)
- [x] Utilities around HTML like `literal`

#### Approach

* The pagination module has been moved to separate library ([paginate](https://github.com/Pylons/paginate)) which supports Python 3, so that might be the easiest replacement
* For generating feeds this seems reasonably well maintained and supports Python 3 (https://github.com/lkiesow/python-feedgen).
* For the HTML investigate options or roll our own

For all these, choose a replacement, rewrite the imports and refactor any code involved to accommodate changes in syntax.

#### Story points

5

**Comment by frafra** [comment]
```bash
shopt -s globstar && egrep -l '(from|import) webhelpers' **/*.py)
ckan/controllers/error.py
ckan/controllers/feed.py
ckan/controllers/group.py
ckan/controllers/package.py
ckan/lib/base.py
ckan/lib/helpers.py
ckan/plugins/toolkit.py
ckan/tests/controllers/test_feed.py
ckan/tests/legacy/functional/api/base.py
ckan/tests/legacy/functional/api/test_package_search.py
ckan/views/feed.py
```

I can try to help with that.

**Comment by wardi** [comment]
@boykoc you mentioned that scheming is related to this one?

**Comment by boykoc** [comment]
@wardi I thought so. During the call it was the discussion on this issue in the sheets tracker that I thought went to scheming compatibility with WTforms? for HTML utilities.

**Comment by wardi** [comment]
WTForms aren't a good fit for us because we have more flexibility with what we can do by overriding templates and validation in plugins, e.g. ckanext-scheming allows defining snippets and validation rules for form fields and API from a yaml/json data format. The eventual plan for scheming is to make these schemas configurable through a web interface. WTForms would require writing Python classes and a major change across the code base.

**Comment by amercader** [comment]
@boykoc @wardi I think this relates to https://github.com/ckan/ckan/issues/4800 rather than this issue
