### ISSUE TITLE
Don't use paste.deploy appconfig to parse the ini file

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4798]
Right now we are using paste.deploy's `appconfig` to parse the INI file and get the `config` object that CKAN uses. It offers some functionality that we don't use (like the ability to parse an INI file hosted elsewhere via HTTP), but basically it's a wrapper around `ConfigParser`. The one feature that we need to keep for backwards compatibility is interpolation (eg things like `cache_dir = /tmp/%(ckan.site_id)s/`), which is also supported in the [standard library](https://docs.python.org/3/library/configparser.html#interpolation-of-values).

#### Approach

Write our own simpler version of the configuration file parser and replace the `appconfig` calls in the CLI code.

#### Story points

5

**Comment by sivang** [comment]
@amercader can you please add some notes of where to check existing code, who is the user of this code (to test that the "contract" is kept) etc? I have a good understanding of what needs to be done, as I've written some config parsers. Looking for where exactly to start.

**Comment by amercader** [comment]
We use the config parser whenever we start the application to parse the ini file and pass the config object to `load_environment()`, which will set everything up.

This can be done more explicitly or hidden as part of a higher level execution. The only place we are doing this directly right now is in the CLI, and the only ones that should be updated are:

* [Old paster CLI](https://github.com/ckan/ckan/blob/master/ckan/lib/cli.py#L205)
* [New click CLI](https://github.com/ckan/ckan/blob/master/ckan/cli/__init__.py#L25). This one covers the new development server (`ckan run`) 

In here you need to replace usage of `appconfig` with our own parser. Check the paste source to see what is special about `appconfig` but as I said in the description I think we only need to keep the interpolation support.

Other places where the config is parsed include the tests. Currently the parsing is done via a Pylons plugin (`nose --with-pylons`) but the new pytest based tests use [our own](https://github.com/ckan/ckan/pull/4996/files#diff-023eefdbe76a226e831eebffefa86b9eR15) parser.

Another place where this will be used will be the wsgi entrypoint for production servers, like the current [Apache one](https://github.com/ckan/ckan-packaging/blob/master/common/etc/ckan/default/apache.wsgi) (which will be replaced by uswgi or gunicorn).

But for now as I said the goal is to parse the ini file and get a config object, and refactor the cli methods to use our own parser.

Let me know if this makes sense.

**Comment by amercader** [comment]
One important functionality that we need to keep is support for the interpolated variables eg (`%(ckan.site_id)s`). So this ini file:

```
# This is /etc/ckan/production.ini

cache_dir = /tmp/%(ckan.site_id)s/ 
ckan.site_id = default
who.config_file = %(here)s/who.ini
who.log_file = %(cache_dir)s/who_log.ini
```

Should become this config object

```python
config = {
  'cache_dir': '/tmp/default',
  'ckan.site_id': 'default
  'who.config_file': '/etc/ckan/who.ini
  'who.log_file': '/tmp/default/who_log.ini
}
```

[This module](https://github.com/Pylons/pastedeploy/blob/9cbc584a86bd1ae425bd0c0c3c00617d7e59475d/paste/deploy/loadwsgi.py) contains the source code of paster's paster in case you want to check the implementation (but that one is way more complex than what we need)

**Comment by pdelboca** [comment]
After talking with @sivang I started doing some work on this issue. So far so good, although I would probably require some assistance. I will create a PR soon to get some feedback!
