### ISSUE TITLE
Remove or replace formencode support

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4800]
Although it's not explicitly listed as a requirement in `requirements.in` (because it's a Pylons requirement), formencode is used in two places:

* Its `OneOf` validator is added to the standard CKAN ones [here](https://github.com/ckan/ckan/blob/f43d6a572838c792193f3239827d04f9ffea9206/ckan/logic/__init__.py#L677).
* There is support for defining formencode validators in the CKAN schema ([docs](https://docs.ckan.org/en/2.8/extensions/adding-custom-fields.html?highlight=formencode#custom-validators), [code](https://github.com/ckan/ckan/blob/b9e45e2723d4abd70fa72b16ec4a0bebc795c56b/ckan/lib/navl/dictization_functions.py#L219:L233))

We need to remove the requirement, because it hasn't been updated in 3 years and its setup.py only lists support up until Python 3.5.

We use `OneOf` in core and someone might be using it in an extension so we need to implement it, but I doubt that anyone is using the second feature, and that we should drop it.

In the future we can add similar support for a better maintained validation library like [WTForms](https://wtforms.readthedocs.io/).

#### Approach

* Write our own implementation of `OneOf` in `validators.py` (and rename it to `one_of` for consistency, but keeping the old name for backwards compatibility).
* Remove all formencode bits from the code base.

#### Story points

2

**Comment by batitaye** [comment]
should I write it from scratch or just plug in WTForms in place of OneOf
and which branch should I implement this on

**Comment by amercader** [comment]
@batitaye sorry I missed your comment. You should use the current `master` branch as a base for this.
I'd prefer if you re-implemented `OneOf` on our code base to avoid the WTForms requirement for now. You can add it to [this module](https://github.com/ckan/ckan/blob/f43d6a572838c792193f3239827d04f9ffea9206/ckan/logic/validators.py) with the rest of the core ones.
Let me know if you need any more pointers and thanks for your help!

**Comment by iamarnavgarg** [comment]
Hi @amercader , is there anyone working on this issue?

**Comment by amercader** [comment]
@iamarnavgarg No AFAICT. Unless @batitaye is working on it feel free to submit a PR. As I mentioned, OneOf should be re-implemented in our own [validators module](https://github.com/ckan/ckan/blob/f43d6a572838c792193f3239827d04f9ffea9206/ckan/logic/validators.py), and references to it updated.

**Comment by Nehimyeah** [comment]
@amercader in formencode OneOf is a class and so CKAN expects the implementation of OneOf to be an object but in [validators module](https://github.com/ckan/ckan/blob/f43d6a572838c792193f3239827d04f9ffea9206/ckan/logic/validators.py "validator.py") every validation implementations are functions so is there a reason why the new implementation of OneOf can't be a class?

**Comment by iamarnavgarg** [comment]
Hi @amercader , I would like to inform you that, I have started working on this issue.

**Comment by iamarnavgarg** [comment]
Hi @amercader , As per my analysis -`one_of(value,context)` should be defined at this location `/src/ckan/ckan/logic/validators.py` . In this defined function, it will take `value` as a parameter and a context parameter that contains a list or a tuple.

Then, using an iterator it will check whether the list(available in context parameter) contains the value. if it exists in the list/tuple, it will return the same value, otherwise raise an exception if not found. 

Could you please confirm with my understanding ?

**Comment by iamarnavgarg** [comment]
Hi @amercader could you please guide me and confirm with my understanding?

> Hi @amercader , As per my analysis -`one_of(value,context)` should be defined at this location `/src/ckan/ckan/logic/validators.py` . In this defined function, it will take `value` as a parameter and a context parameter that contains a list or a tuple.
> 
> Then, using an iterator it will check whether the list(available in context parameter) contains the value. if it exists in the list/tuple, it will return the same value, otherwise raise an exception if not found.
> 
> Could you please confirm with my understanding ?

Hi @amercader could you please guide me and confirm with my understanding?

**Comment by amercader** [comment]
Sorry @iamarnavgarg , I added comments on the pull request
