### ISSUE TITLE
Implement changes to allow running CKAN in both Python 2 and 3

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4801]
During our transition period the same code base needs to be able to run in both Python 2 and 3. Pylons will still be there to allow people to completely migrate their extensions, which means that there will be two different sets of requirements:

* `requirements.py2.in`: Including Pylons and whatever Pylons 2 only stuff that still needs to be there
* `requirements.in`: Python 3 only requirements, which will be the ones installed by default in the documentation for new instances

Once we have installed the Python 3 requirements in a py3 virtualenv then it's just a matter of running `ckan run` and keep fixing things until CKAN works :sweat_smile:. And then do the same until all tests pass.

We will find two main issues:

1. Python 3 incompatible code. Despite all the great work done so far there are still things that we have missed (eg relative imports, `map()` function returning an iterator rather than a list, etc). These should be easy to pick up and fix.
2. Conditional imports and execution.  There will be some imports and code that only need to be run on Python 2. We can decide the best way to define this conditional loading (the `if six.PY2` bit) but essentially it boils down to things like:

    ```python
    # ckan/common.py
    
    import six

    import flask

    if six.PY2:
        import pylons
        from pylons.i18n import (ugettext as pylons_ugettext,
                                 ungettext as pylons_ungettext)
        from pylons import response
    
    # ...
 
    def is_flask_request():
        '''
        A centralized way to determine whether we are in the context of a
        request being served by Flask or Pylons
        '''
        if six.PY3:
            return True
        
        # ...
    
    ```

Luckily as part of the Flask migration work a lot of imports for the most used objects were centralized in a few modules, so hopefully these hacks will be limited in scope (and remember that they should be removed in the next version).

I had a quick go a this and I quickly bumped into VDM, as it is used very early on the initialization, so VDM is definitely the major blocker on getting this important work started.

#### Approach

* Create two different sets of requirements for Python 2 / 3 envs - see #5063
* Load Python 2 requirements conditionally
* Fix Python 3 compatibility issues
* Get CKAN starting up when running `ckan run` (and to serve some pages) in Python 3
* Get all tests passing in Python 3

#### Story points

13

**Comment by davidread** [comment]
Nice work @amercader and @smotornyuk!

Can this issue be closed then?

**Comment by amercader** [comment]
Yes! Any new py3 compatibility issues can be created separately
