### ISSUE TITLE
Update the WSGI entrypoint to not use paste.deploy

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4802]
TODO

paste.deploy loadapp

#### Story points

**Comment by davidread** [comment]
We want to get rid of PasteDeploy's `loadapp` and instead use Werkzeug.

It looks like @JGulic has done this for the Profile command - https://github.com/ckan/ckan/pull/5244.

The heart of this ticket is to change the .wsgi file we use to deploy CKAN into production: https://github.com/ckan/ckan/blob/master/doc/maintaining/installing/deployment.rst#4-create-the-wsgi-script-file 

A basic Werkzeug .wsgi is documented here: https://werkzeug.palletsprojects.com/en/1.0.x/deployment/mod_wsgi/#creating-a-wsgi-file

Our [make_app()](https://github.com/ckan/ckan/blob/master/ckan/config/middleware/__init__.py#L50) also needs a config parameter. So I guess we need to do: CKANConfigLoader(filename).get_config()
(whereas loadapp we just passed in the filename)

The existing apache.wsgi also configures logging:
```
from paste.script.util.logging_config import fileConfig
    fileConfig(config_filepath)
```
We want to get rid of PasteScript in py3 requirements. Logging is not configured from the ini when running tests or the click cli, so this is a new thing to ckan. It looks the built-in python3 logging module has what we want: [logging.config.fileConfig](https://docs.python.org/3.5/library/logging.config.html#logging.config.fileConfig)

**Comment by davidread** [comment]
☝️ I wrote this with a bit of research - I'd appreciate @amercader or @smotornyuk checking this is right. And if it is then it should be easier for whoever gets there first to contribute a PR and test it out with Apache.

**Comment by kowh-ai** [comment]
I will also be able to test the new (Werkzeug)  .wsgi file with the new uWSGI and gunicorn "servers/entrypoints" as I have now finished these new configurations. They both work with the PasteDeploy loadapp file.  I'm guessing Apache will still be around for CKAN 2.9 however I could add these 2 new configs to the CKAN 2.9 documentation. I guess we will be phasing out Apache completely by CKAN 3.0...

**Comment by davidread** [comment]
@kowh-ai I'm very happy to see https://github.com/ckan/ckan/issues/4991 progressing 👍 

When we have a PR for this issue, it doesn't really matter which server it is tested against - I just said Apache as it was the current default - so I'm also very happy to see your offer of testing it 🙏
