### ISSUE TITLE
Replace paster make-config

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4803]
From @davidread input, plus some extra detail:

This is the command used to create new ini files (eg `development.ini` or `production.ini`). This is done as part of [installation](https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#create-a-ckan-config-file):

    paster make-config ckan /etc/ckan/default/development.ini

It generates it from a template: https://github.com/ckan/ckan/blob/master/ckan/config/deployment.ini_tmpl

I think it also has a feature that allows you to update your .ini file when you upgrade CKAN and the template has changed. However I'm not sure anyone uses that - we make sure additions are defaulted so that .ini files are forwards compatible.

#### Approach

Add a new CLI function that renders the template and saves it as a file. Now that we have the `ckan generate` command we can add a `ckan generate config` option (in addition to the existing `ckan generate extension`). This should accept one argument, the path to the new ini file.

Rendering in this case just means substituting variables like `${app_instance_secret}` which we might change to Jinja style and use the Jinja renderer. Or even python `.format()` - I don't think escaping is needed.

Variables like `%(ckan.site_id)s`  should be kept in the resulting ini file, as these are evaluated when reading the ini file, not when writing it.

#### Story points

3

**Comment by davidread** [comment]
# Requirements

i.e. a way to create development.ini. This is done as part of [installation](https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#create-a-ckan-config-file):

    paster make-config ckan /etc/ckan/default/development.ini

It generates it from a template: https://github.com/ckan/ckan/blob/master/ckan/config/deployment.ini_tmpl

I think it also has a feature that allows you to update your .ini file when you upgrade CKAN and the template has changed. However I'm not sure anyone uses that - we make sure additions are defaulted so that .ini files are forwards compatible.

# How

A cli function that renders the template and saves it as a file. Rendering in this case just means substituting variables like `%(ckan.site_id)s` and `${app_instance_secret}` which we might change to Jinja style and use the Jinja renderer. Or even python `.format()` - I don't think escaping is needed.

**Comment by mpolidori** [comment]
I'd like to take this one

**Comment by amercader** [comment]
Great @mpolidori, thanks a lot! Ping us here if you need help. If you see you won't be able to work on it after all let us know so I we can assign it to someone else.

**Comment by mpolidori** [comment]
@amercader Will do. Thanks!

**Comment by mpolidori** [comment]
@amercader I've made a little progress, but if I start taking too long, please let me know! I'm still getting the hang of things.

**Comment by mpolidori** [comment]
@amercader 

As David mentioned, `.format()` or Jinja would obviously work, but I started with [Template strings](https://docs.python.org/3/library/string.html#template-strings), which I think also works well. The format is identical to the current variable setup. `$identifier_name` variables in `deployment.ini_tmpl`, and you pass a dictionary with the identifiers like `identifier_name: identifier_value` to `.substitute(identifier_dict)`, which returns the new modified template string. I can change this to `.format()` or Jinja if needed. Also, you mentioned leaving the `%(ckan.site_id)s` style variables, as they're used when the file is read , whereas David mentions substituting those as well.

A few other things I'm kind of stuck on...

It seems that `ckan` commands require the `development.ini` to already exist:
```
ERROR: You need to specify the CKAN config (.ini) file path.
Use the --config parameter or set environment variable CKAN_INI or have development.ini
in the current directory.
```
I've been looking into somehow overriding this for only the `ckan generate config` command I have implemented, but I haven't had any luck yet (maybe I'm missing something obvious, or approaching it from the wrong angle - still looking into this). For development and testing, I have been using the default `.ini` file I created with my working environment, but this is obviously a problem.

Another thing I'm curious about is whether we're worried about setting things like `ckan.site_url` here? By default, it isn't set in `deployment.ini_tmpl`, which results in an error on running a `ckan` command after creating the new `.ini` file. Currently, I prompt the user to set the URL or default to `http://ckan:5000`.

**Comment by mpolidori** [comment]
Also, I saw #4798, and it seems to be what's reading the `.ini` file. Maybe the new implementation can bypass reading the `.ini` if the command is `ckan generate config`? Let me know if any of these questions or points aren't clear.

**Comment by davidread** [comment]
All sounds very promising! Can you make a draft PR please?

'Template strings' looks good to me - simple.

> leaving the %(ckan.site_id)s style variables

@amercader is quite right on this :)

> ckan commands require the development.ini to already exist

I would have thought it is possible to avoid the load_config method, but I've not looked closely.

> Another thing I'm curious about is whether we're worried about setting things like ckan.site_url here?

No. The [instructions](https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) guide you through these sorts of things. We might choose to improve this, but that would be for a separate effort at a more suitable time.

To test, just check you get the same output as from `paster make-config ckan something.ini`.

**Comment by mpolidori** [comment]
@davidread Thanks for clearing those up! I made a pull request. I believe the only thing left is to find a way to get around the required `development.ini`. Let me know what you think.
