### ISSUE TITLE
Remove AppDispatcher and Pylons middleware

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4805]
TODO

#### Story points

**Comment by davidread** [comment]
While I think of it, `paste.urlparser.StaticURLParser` is one of the middlewares that needs replacing in [pylons_app.py](https://github.com/ckan/ckan/blob/master/ckan/config/middleware/pylons_app.py). Probably this: http://flask.pocoo.org/docs/1.0/api/#flask.send_from_directory (which we already use for webassets)
