### ISSUE TITLE
Remove vars in templates context set in views

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4806]
TODO

#### Story points

**Comment by Gauravp-NEC** [comment]
@amercader , I am interested to work in this issue. Please let me know what needs to be done in this issue.

**Comment by amercader** [comment]
@Gauravp-NEC hold on this one. I think last time we discussed this we decided to wait a few more versions

**Comment by amercader** [comment]
Closed in favour of https://github.com/ckan/ckan/issues/6769
