### ISSUE TITLE
Can I set premission to dataset download?

### ISSUE THREAD

**Issue by wuweihust** [ckan/ckan#4808]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
CKAN 2.8

### Please describe the expected behaviour
I‘d like to set premission to dataset download in order to protect the visitors from downloading some datasets?
firstly, can I set premission to dataset download?
secondly, can I add more user types？

Thank you for reply.

**Comment by davidread** [comment]
Issues are for bugs and enhancements. Please ask questions elsewhere - see the README.
