### ISSUE TITLE
Orphaned pyc files

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#4809]
Compiled '*.pyc' files are not removed when checking out a different Git revision, even if their source files no longer exist. This is not always a problem, but sometimes can be.

### CKAN Version if known (or site URL)

2.7.3 and 2.8.2

### Please describe the expected behaviour

Rolling back from CKAN 2.8.2 to 2.7.3 should be possible by checking out the 2.7.3 Git tag, installing the Python dependencies, and providing a blank database.

### Please describe the actual behaviour

`paster db init` fails because the 086 database update script still exists in compiled form.

### What steps can be taken to reproduce the issue? 

Install CKAN 2.8.2, including dependencies and database.
Check out the 2.7.3 branch and rerun dependency installation.
Provide a blank database and initialise it with paster.

**Comment by davidread** [comment]
Yep, this trips up developers switching branches with different migration scripts on them, particularly downgrading CKAN versions.

I wonder if Django / Alembic have any solutions we can use?

There are a number of things you have to do when downgrading, such as reinstall requirements, wipe db. Deleting .pyc files is just another thing to remember. I have a script for doing all this: https://gist.github.com/davidread/3ed0d962b05cb87678b389f34186fa3f

**Comment by amercader** [comment]
Unfortunately this is something that would be difficult or incorrect to handle at the CKAN level. We can add a note in the relevant docs if that helps.

You can configure a [git post-checkout hook](https://stackoverflow.com/a/1810193/235993) to remove the pyc files for you.

**Comment by ThrawnCA** [comment]
What about handling it within the `paster` task?

**Comment by davidread** [comment]
I'm with @amercader in being apprehensive about mucking about deleting pyc files from within python. Feels wrong. Unintended consequences.

**Comment by ThrawnCA** [comment]
Could it at least be documented at https://docs.ckan.org/en/latest/maintaining/upgrading/index.html ?

**Comment by TkTech** [comment]
IMO, this isn't really a CKAN thing, it's part of Python's internal operations. Every Python project (and a lot of other interpreted languages) deal with problems like this. We should deal with this for you if you're using the ready-to-go packages, but if you're working with the source we should expect you to know Python and its quirks. We can't really document *everything*.

This problem should disappear with the switch to py3 which introduces the separate caches directory.

**Comment by amercader** [comment]
@ThrawnCA sure, it makes sense to add a `..note::` in the docs reminding people to clear pyc files if they are switching branches. A pull request would be welcome.
