### ISSUE TITLE
After removing the tag the redirect web url is wrong and it causes an error

### ISSUE THREAD

**Issue by 0wenwu** [ckan/ckan#4823]
Hi, thanks for the wonderful CKAN. It makes me set up a open data portal very fast. 
When I search the data by tags, it works very quickly.
![图片](https://user-images.githubusercontent.com/6868237/58615187-05f03880-82ed-11e9-8420-e8b83fe59766.png)

But I am trying to remove the tags like the picture below
![图片](https://user-images.githubusercontent.com/6868237/58615334-641d1b80-82ed-11e9-965e-12e8b968807f.png)

 the redirect web url became` http://10.102.30.154:5000/en/dataset/dataset?tags=%E6%B5%8B%E8%AF%95`. The url has an extra `dataset`, which causes an error in the UI.

![图片](https://user-images.githubusercontent.com/6868237/58615220-1acccc00-82ed-11e9-9d7e-024d229480fc.png)

![图片](https://user-images.githubusercontent.com/6868237/58615241-28825180-82ed-11e9-949e-9ee848366ddd.png)

**Comment by usingsky** [comment]
It seems to be an issue related to the following.
I have requested PR, but if you have any other solution, I would appreciate your comments.
[https://github.com/ckan/ckan/pull/4790](https://github.com/ckan/ckan/pull/4790)
