### ISSUE TITLE
Error while integrating oauth2

### ISSUE THREAD

**Issue by Madhu-NEC** [ckan/ckan#4832]
I want to authenticate Ckan(2.7.2) with WSO2IS(5.3.0) and WSO2APIM(2.1.0).
I have created an application on wso2apim store with callback URL : https://ckan-instance-url/oauth2/callback

Following are the /etc/ckan/default/development.ini configurations:

ckan.oauth2.logout_url = /user/logged_out
ckan.oauth2.register_url = /
ckan.oauth2.reset_url = /
ckan.oauth2.edit_url = /
ckan.oauth2.authorization_endpoint = https://wso2-instance-url/oauth2/authorize?prompt=login
ckan.oauth2.token_endpoint = https://wso2-instance-url/oauth2/token
ckan.oauth2.profile_api_url = https://wso2-instance-url/oauth2/userinfo?schema=openid
ckan.oauth2.client_id = # Client ID
ckan.oauth2.client_secret = # Client Secret
ckan.oauth2.scope = openid
ckan.oauth2.rememberer_name = auth_tkt
ckan.oauth2.profile_api_user_field = sub
ckan.oauth2.profile_api_fullname_field = sub
ckan.oauth2.profile_api_mail_field = sub
ckan.oauth2.authorization_header = OAUTH2_HEADER
ckan.oauth2.profile_api_groupmembership_field = sub
ckan.oauth2.sysadmin_group_name = admin

While logging in CKAN, it successfully redirects to wso2 page and accepts login credentials but when it redirects it to its callback(i.e. ckan login page) I got **[Errno 2] No such file or directory**. Please find attached screenshot.
**Note:** Ckan , wso2 IS and APIM are being served on nginx.
![error_ckan](https://user-images.githubusercontent.com/47887616/59078440-be753800-88fc-11e9-96ff-c941f343846a.png)

**Comment by tino097** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the Gitter [#ckan](https://gitter.im/ckan/chat) channel, where other developers may be able to help you.

Thanks!

**Comment by wardi** [comment]
also this looks like it might be related to the extension you're using, have you tried reporting it on the extension repo?
