### ISSUE TITLE
How to add website to "Ckan is used by" list in Ckan website.

### ISSUE THREAD

**Issue by vugar005** [ckan/ckan#4833]
Hello
We have built open data website for governement.
Now we want it to be on the list of  "Ckan is used by" list in Ckan website.
What is required to do that ?

Website: [http://opendata.neuron.az](http://opendata.neuron.az)
Technology Stack: Angular 6 + Java Spring Boot

Thanks in advance

**Comment by rossjones** [comment]
The site at https://ckan.org/about/instances/ suggests you should fill in the form at https://ckan.org/census/ and then someone will probably check it and add to the list.  

As well as looking _very_ pretty, your site is a bit more than just CKAN (1), are you just using it as an API?  

(1) I was unable to access the CKAN api at /api/3/action/package_list and got a Tomcat error.

**Comment by vugar005** [comment]
@rossjones 
Thank u  for quick response.
1. We are inspired by CKAN but have our custom api , unfortunately it is not CKAN api. But it has most features that CKAN offers.
Can it prevent from being on the list of 'Used by'.

**Comment by rossjones** [comment]
@vugar005 not really up to me, I suggest filling in the form and seeing what the reviewer thinks, but I suspect as a list of CKAN instances, it's probably better if it is just actual CKAN instances rather than things that look similar.
