### ISSUE TITLE
Resource schema alterations in extensions show incorrect data

### ISSUE THREAD

**Issue by hardingalexh** [ckan/ckan#4836]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
Latest

### Please describe the actual behaviour
When an extension adds a custom field the resource metadata, something strange is going on.

No matter how many resources are uploaded to the dataset, the custom field on the first resource will display the info from the last resource in the list.

For example, I upload three resources with the following values, where "custom" is being added by the extension:

Name: First
Custom: First

Name: Second
Custom: Second

Name: Third
Custom: Third

When viewing the resource named "First", the custom value will show "Third". If I then add a fourth, First will show Fourth.

### What steps can be taken to reproduce the issue? 

I've created an extension to demonstrate this. The extension adds a custom field to the resource schema, adds a template to the form to set it, and adds the value to the dataset front page so you don't have to click in as much to see the problem. Try installing this extension and adding a dataset with more than one resource and you should be able to replicate. This extension was built with the tutorial from the extending guide.

https://github.com/hardingalexh/ckanext-testingresourceschema

**Comment by wardi** [comment]
This is a problem with documentation. The `convert_from_extras` and `convert_to_extras` validators are only for extras at the package level, not at the resource level.

**Comment by boykoc** [comment]
You can kind of see in [the documentation](https://docs.ckan.org/en/latest/extensions/adding-custom-fields.html#adding-custom-fields-to-resources) the highlighted code changes to add a custom field to the resource. But it's a bit hard to see the differences (highlighting yellow on green isn't great).
