### ISSUE TITLE
form.input does not allow custom markup in labels

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#4840]
### CKAN Version if known (or site URL)

CKAN 2.8.2

### Please describe the expected behaviour

We want to include hint text in our form labels. Our CKAN 2.7 markup looks like:

      <div class="control-group control-medium">
        <label for="field-password" class="control-label">
          <span class="label">New password</span>
          <small class="hint">Passwords should be a minimum of 8 characters in length and contain (at least) one capital letter, one lower case letter, a numeral and a symbol such as: @#$%^& etc.</small>
        </label>
        <div class="controls ">
          <input type="password" autocomplete="off" placeholder="" value="" name="password1" id="field-password" class="">
        </div>
      </div>

When upgrading to CKAN 2.8, we want to use the form macros to do this, as per the core templates.

### Please describe the actual behaviour

The `form.input` macro does not allow anything more than simple text inside the label tag. Extra HTML is possible, but it appears after the input field.

**Comment by smotornyuk** [comment]
Hi, @ThrawnCA .
There are two options of providing markdown into labels. 

You can use safe strings for small pieces of content:
```jinja2
  {{ form.markdown('notes', id='field-notes', label='hello <em>world</em>'|safe, placeholder=_('eg. Some useful notes about the data'), value=data.notes, error=errors.notes) }}
```

And when you need more control, editor highlight, multiline, etc, you can use block-variables:
```jinja2
  {% set label %}
      Hello <mark>world</mark>
  {% endset  %}
  {{ form.markdown('notes', id='field-notes', label=label, placeholder=_('eg. Some useful notes about the data'), value=data.notes, error=errors.notes) }}

```
