### ISSUE TITLE
404s for minor recline assets

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4844]
### CKAN Version if known (or site URL)
latest master

### Bug
When I preview a CSV on the resource page e.g. `/dataset/test/resource/0d534c55-879c-41c3-9e8f-26386b574158`
then it basically works, but there are some 404 errors fetching a few assets:

* /webassets/img/ajaxload-circle.gif
* /webassets/fonts/glyphicons-halflings-regular.woff
* /webassets/fonts/glyphicons-halflings-regular.ttf

There is a mismatch because there is an asset here: /img/ajaxload-circle.gif

I guess this is a side-effect from: https://github.com/ckan/ckan/pull/4614

**Comment by davidread** [comment]
@smotornyuk I don't suppose you have a moment to look at this?

**Comment by smotornyuk** [comment]
Hi. Thanks for report - i've created PR for this issue. Even though i slightly restricted in terms of workload, I have to fix problems created by my former PRs as soon as possible :)
