### ISSUE TITLE
Docker container dd container name hardcoded in startup.

### ISSUE THREAD

**Issue by ErroneousBosch** [ckan/ckan#4845]
### CKAN Version if known (or site URL)
master branch

### Please describe the expected behaviour
Initializing CKAN container should connect to the database container regardless of the database container name. Also should be able to connect to an external DB server. 

### Please describe the actual behaviour
CKAN container tries to see if a server named "db" is live, simply returning "no attempt". This is is because this server name is hardcoded in `ckan-entrypoint.sh` @ line 44, rather than taking an environment variable. This also prevents using an external or existing DB.

### What steps can be taken to reproduce the issue? 
Spin up your docker compose with a different container name, or with external server name in connection URLS.

**Comment by ErroneousBosch** [comment]
Note that this hardcoding also appears on line 71 for ckan-paster (which is missing from the container)

**Comment by rdenadai** [comment]
Not the ideal solution, but... maybe it could help someone else...

if using **docker** run command add a:
```bash
   --add-host=db:127.0.0.1
```

In case of **docker-compose**:
```yml
extra_hosts:
  - "db:127.0.0.1"
```

It will add to internals /etc/hosts a mapping so the container can find **db** hostname.

**Comment by Gauravp-NEC** [comment]
@ErroneousBosch @wardi , Please refer to PR https://github.com/ckan/ckan/pull/5596 it may close this issue.

**Comment by Gauravp-NEC** [comment]
@wardi , I am interested to work on this issue. Now is it required to remove the hardcoded db container name? As this issue was opened 2 years back. Please let me know your opinion. Thanks :)

**Comment by Gauravp-NEC** [comment]
@wardi, In this issue I understand that the hardcoded reference to db host and users should be removed. Please confirm my understanding.

**Comment by ErroneousBosch** [comment]
Yes. in the pg_isready check, it hardcodes in the db name as "db", rather than using something like an environment variable with a default value, which would be a better practice.

**Comment by Gauravp-NEC** [comment]
@ErroneousBosch , Can you help me to understand how in the pg_isready check, it hardcodes in the db name as "db"?

**Comment by Gauravp-NEC** [comment]
@rdenadai , Thankyou. If the env var like ${CKAN_POSTGRESQL_HOST} is placed then how I can verify that the hard-coded db is removed?
