### ISSUE TITLE
Recline.js jsonpdataproxy solution?

### ISSUE THREAD

**Issue by Quackpower** [ckan/ckan#4848]
Hello!

i'm completly new with ckan, is it installed already and it work well but the server that the recline.js library uses "jsonpdataproxy" , is down most of the time, what is a work around to this, as i unstderstand, the proxy is used to load the file form an external source, but all of my files are locally stored, anyone has ha this issue before??? thanks!

**Comment by wardi** [comment]
Hi, thanks for submitting your issue.

To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the gitter channel https://gitter.im/ckan/chat, where other developers may be able to help you.

Thanks!
