### ISSUE TITLE
Preview for multimedia files

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4850]
CKAN provides previews for images and tables, but not for audio and videos.

It should be pretty easy to add it:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by frafra** [comment]
I started to work on it.

**Comment by mutantsan** [comment]
Hi, I've created a PR #5103 , since it's still not implemented

**Comment by frafra** [comment]
Hi @mutantsan; have you figured out why the previous draft PR was not working as expected?

**Comment by frafra** [comment]
Any news?
