### ISSUE TITLE
Python 2/3 migration guide

### ISSUE THREAD

**Issue by pwalsh** [ckan/ckan#4855]
# User story

As a {developer} working on Py2/3 migration for CKAN, I want a clear migration guide, so I can provide Py2/3 compatibility in a consistent way using a common set of tools.

# Use cases

- Contributing Py2/3 compatible code in CKAN Core
- Contributing Py2/3 compatible code in a CKAN Extension
- Starting a new CKAN Extension with Py2/3 compatibility

**Comment by amercader** [comment]
Done in https://github.com/ckan/ckan/issues/4792
