### ISSUE TITLE
CKAN 2.7 migrations on postgres 10 not working

### ISSUE THREAD

**Issue by kadimka** [ckan/ckan#4868]
### CKAN Version
CKAN 2.7

### Expected behaviour
while initializing database "paster db init -c /etc/ckan/ckan2.7/development.ini", database should be initialized.

### Actual behaviour
while running "paster db init" we got migrations errors

### To reproduce the issue
1. setup clear CKAN 2.7
2. install postgres 10 
3. run "paster db init"

**Comment by kadimka** [comment]
Hi guys, it seems that migration updates that were added here https://github.com/ckan/ckan/commit/3a6015a60644fb7ae18644b0537604f4552fae4d haven't been backported to CKAN2.7.
Checked with this commit, it started to work properly.

**Comment by amercader** [comment]
The changes to support Postgres 10 were included on this PR: https://github.com/ckan/ckan/pull/3978/files (which is not part of 2.7, but you can port to it). The changes in the commit that you link to are related to an upgrade to SQLAlchemy, but they are tied to CKAN 2.8. CKAN 2.7 should have its own SA requirement.

Perhaps there's an issue with your requirements (sqlalchemy or psycopg2)

Closing for now, feel free to reopen if there's a problem with CKAN core
