### ISSUE TITLE
"Debug" flag warning in INI file has inadequate wording

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#4871]
The INI file template has a warning on the `debug` flag, but that warning doesn't properly match the documentation. Specifically, the warning says that the flag must be false in a *production* environment, but the real rule, as described at https://docs.ckan.org/en/latest/maintaining/configuration.html, is that it must be false for a *public* site. These are very different criteria; it's not uncommon to have publicly facing, but not advertised, non-production environments.

### CKAN Version if known (or site URL)
CKAN 2.8.2

### Please describe the expected behaviour
The warning on `debug` should state that it must be false for publicly visible sites.

### Please describe the actual behaviour
The warning on `debug` states that it must be false for production sites.

**Comment by amercader** [comment]
This sounds reasonable @ThrawnCA, do you want to submit a quick PR with the change?

**Comment by ThrawnCA** [comment]
What branch(es) should I use?

**Comment by ThrawnCA** [comment]
Opened #4880
