### ISSUE TITLE
Allow custom CKAN callback URL for the DataPusher

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4878]
The DataPusher pings back CKAN when performing or finishing a job (the `datapusher_hook` action), and it does so via an HTTP request to the host defined in `ckan.site_url`.

There are a number of scenarios where this does not work, eg:

* CKAN and DataPusher sitting behind a Firewall that doesn't allow external requests
* Standard Docker compose setup for development where the `ckan.site_url` is `http://localhost:5000` or similar (as the DataPusher container won't be able to ping that)

This has been flagged in numerous occasions: 

https://github.com/ckan/ckan/issues/3987
https://github.com/ckan/ckan/issues/4013
https://github.com/ckan/datapusher/issues/83
https://github.com/ckan/ckan/issues/4515

**Comment by anibalpacheco** [comment]
Just some info when using apache-wsgi in 8080 behind nginx, this patch worked excellent for me using the new setting with `http://localhost/` pointing to the nginx, (using http://localhost:8080 pointing the apache didn't work, it seems that a twisted-zope error was thrown trying to load the apache.wsgi script)
