### ISSUE TITLE
Data Explorer not loading data

### ISSUE THREAD

**Issue by Prithvi48** [ckan/ckan#4887]
I'm using a website that uses the ckan API, I'm uploading the data through AWS and when I upload the data and try to view it in the data explorer, I get the following

" This resource view is not available at the moment. Click here for more information. "

and when I click I get the following

" Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds) "

Does anyone have any suggestions?

PS: I am also missing the data dictionary, which I believe it's related to this, but not sure.

**Comment by wxg0103** [comment]
你解决了吗?

**Comment by amercader** [comment]
The DataProxy is a deprecated external service that CKAN uses when data is not on the DataStore. To enable the data visualizations install and configure the DataStore plus DataPusher or XLoader as described here:

https://docs.ckan.org/en/latest/maintaining/datastore.html
