### ISSUE TITLE
Server Error on '/dataset' page after installing ckanext-ddi and harvester

### ISSUE THREAD

**Issue by Pardhu448** [ckan/ckan#4890]
![dataset_server_error_ckan](https://user-images.githubusercontent.com/10006246/60584904-0b3d1900-9dac-11e9-9c53-a8130ed021be.png)
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.
### CKAN Version 
2.8.2 (Running locally through Docker)

### Please describe the expected behaviour

'/dataset' page should show the datasets available. 

### Please describe the actual behaviour

But throws 'An internal server error occurred' Server error. Also I am able to access datasets through Organizations. So sample dataset resource page like 'http://ckan-dev:5000/dataset/imt-data/resource/dd0b92ec-2105-468a-b29f-4655b01339c3'' is being fetched properly. Things were fine before installing ckanext-harvester and ckanext-ddi extensions. DDI and Harvester are installed properly. 

### What steps can be taken to reproduce the issue? 
- Run locally CKAN using Docker Image
- Install ckanext-ddi and ckanext-harvest
- Try accessing '/dataset' page
### Following is the detailed log generated from docker-compose logs ckan:
[ckan_logs_new.txt](https://github.com/ckan/ckan/files/3354559/ckan_logs_new.txt)

Thanks in Advance!

**Comment by smotornyuk** [comment]
```
 File '/usr/lib/ckan/venv/src/ckanext-ddi/ckanext/ddi/templates/package/search.html', line 9 in block "page_primary_action"
   {% link_for _('Import Dataset from DDI/XML'), controller='ckanext.ddi.controllers:ImportFromXml', action='import_form', class_='btn btn-primary', icon='plus-sign-alt' %}
...
 CkanUrlException: There is a broken url being created {'action': 'import_form', 'controller': 'ckanext.ddi.controllers:ImportFromXml'}
```
Here's a problem and, as you can see, it came from ckanext-ddi. You should address this issue to extension maintainer because, afaik it not mainteined by CKAN tech team so we cannot resolve this issue.

**Comment by Pardhu448** [comment]
Thanks for the quick response. Will try it in DDI extension issues.

**Comment by yjaques** [comment]
@Pardhu448 were you ever able to resolve this issue? I raised it in ckanext-ddi github but no reply.
