### ISSUE TITLE
Docker setup for production

### ISSUE THREAD

**Issue by olivierdalang** [ckan/ckan#4893]
Hi !

The Docker setup seems to work fine for testing purposes but doesn't seem suited to production at all (using `paster serve`, which as far as I understood is a deprecated dev server, doesn't provide HTTPS nor instruction on how to set it up, etc.).

Thanks,

Olivier

**Comment by tino097** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the Gitter [#ckan](https://gitter.im/ckan/chat) channel, where other developers may be able to help you.

Thanks!
