### ISSUE TITLE
[Docker] better management of production.ini

### ISSUE THREAD

**Issue by olivierdalang** [ckan/ckan#4894]
Currently, the Docker setup for CKAN uses a volume for `production.ini`. The file is generated the first time in the entrypoint, and the volume is not mounted on the host.

That's not really optimal :
- there's a duplication of settings between `production.ini` and `.env` (e.g.  `CKAN_SMTP_*` env vars from `.env` must be defined again in `production.ini`)
- config can only be edited live
- config is hard to find (hidden in docker's internal volume files) and thus also hard to manage/version

I think a template `production.ini` should be shipped with the source rather than generated on the fly. It could either :
a/ contain variables that would be replaced with envsubst in the docker entrypoint
b/ be mounted directly in the source directory

Variant a/ would be nicer to use in a typical docker workflow, as config would exclusively happen as env vars (everything in `.env`), but would be less flexible. Variant b/ would be more flexible, as you could manually change the `production.ini` file to whatever you need.

What do you think ?

**Comment by tino097** [comment]
@olivierdalang can you please use dev mailing list or Gitter for this discussion as we dont want to spam issues on the repo.
