### ISSUE TITLE
Dataset search page shows all types instead of only "dataset"

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#4898]
### CKAN Version
2.8, master

### Expected behaviour
When User goes to "/dataset" page, the page shows only Datasets list items.
 

### Actual behaviour
When User goes to "/dataset" page, page shows all Dataset types (e.g. dataset, showcase....)

### To reproduce the issue

1.  Have CKAN pure installation
2. Add ckanext-showcase
3. Create a few showcases
4. On Dataset search page showcases appear as well.

**Comment by Engerrs** [comment]
Hi @wardi , I found a reason for that bug in #3807 issue. The code that supposed to show all types or specific types is not working as expected.
https://github.com/ckan/ckan/pull/3807/files#diff-d61fa02346248a2c5eed362244515307R231 breaks the logic, as in case if this config is not added, the "asbool" function returns an error and search_all sets to True, as a result, it shows all types. Even if "ckan.search.show_all_types" is set for example to "showcase", it still won't work and show all types.
This is a critical issue I suppose and this logic should be reviewed/refactored.

**Comment by Engerrs** [comment]
Hi @smotornyuk , I added a fix to this issue.
Separated it into 3 commits, so "Fix Dataset search show all types for Controller" and "Update configuration.rst for ckan.search.show_all_types" can be backported to CKAN 2.8

It seems that commits were duplicated when I pushed them into my repo, but the all same. You can check the last 3 ones.

**Comment by frafra** [comment]
This would be very nice indeed. I can try to make a PR.

**Comment by smotornyuk** [comment]
Closing this one, because original behavior now works as expected:

`ckan.search.show_all_types = false` - don't show all dataset types on any search page
`ckan.search.show_all_types = true` - show all dataset types only on `/dataset` page
`ckan.search.show_all_types = custom_type` - show all dataset types only on `/custom_type` pate
