### ISSUE TITLE
 URL ‘/hello’ rule in public site

### ISSUE THREAD

**Issue by usingsky** [ckan/ckan#4911]
I suggest providing the /hello path only in debug mode.

### CKAN Version if known (or site URL)
2.8

### Please describe the expected behaviour
Ckan extension can determine whether to use /hello routing.

### Please describe the actual behaviour
Currently ckan core provides the "/hello" path by default.
In a production build, I think this is unnecessary information for users.
There is no way to remove "/hello" routing from an extension without modifying the core, and it must be redefined.

### What steps can be taken to reproduce the issue? 
It is being routed on some sites based on ckan
eg)
https://demo.ckan.org/hello
https://data.stadt-zuerich.ch/hello
https://data.gov.ie/hello
https://ckan0.cf.opendata.inter.sandbox-toronto.ca/hello

**Comment by amercader** [comment]
Thanks @usingsky . That's a leftover from the initial stages of the Flask migration. I've removed in #4913
