### ISSUE TITLE
Datasets on homepage shows wrong

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#4919]
### CKAN Version if known (or site URL)
CKAN 2.8, master

It seems that when **home** controller was migrated to blueprint there was a mistype in **data_ditct**. The **start** option should be [0](https://github.com/ckan/ckan/blob/master/ckan/controllers/home.py#L50) rather than [4
](https://github.com/ckan/ckan/blob/master/ckan/views/home.py#L37)

**Comment by amercader** [comment]
Fixed in #4920
