### ISSUE TITLE
Norwegian language is not working with Flask blueprints

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#4933]
### CKAN Version
2.8, master

### Expected behaviour
When changing language to Norwegian, it should translate the pages. (Implementation from views, not controllers)

### Actual behaviour
When changing language to Norwegian nothing happens

### Steps to reproduce
1. Setup pure CKAN 2.8 or master.
2. Change language to Norwegian or homepage or about page.

**Comment by Engerrs** [comment]
Hi @amercader , I added a link to 'no' folder translations in order to add new Norwegian option 'nb_NO'. As far as I understand 'no' is an old format, but pylons support both 'no' and 'nb_NO' while Flask babel doesn't.
In order to fix this for 100% we need to update the transifex code from 'no' to 'nb_NO' on https://www.transifex.com/okfn/ckan/. But not sure if it is critical right now.
There might be other languages that has same issue.

As a second option, if I understand correctly, we can modify the '.tx/config' file by adding "trans.no = ckan/i18n/nb_NO/LC_MESSAGES/ckan.po" and pull the languages again, as a result it will save translations from transifex for 'no' to 'nb_NO' folder. Not sure if it works that way.

Another issue for CKAN 2.8 that https://github.com/ckan/ckan/commit/56fb0b19db735c4583309fe1e9fdc8eb06364189#diff-d89c6cc9bc6f95acbc9906e48b946eb0 is not backported, as a result some laguages still not shown as an active.

**Comment by tsmaavik** [comment]
Hi. I've installed CKAN 2.9, and Norwegian is still not working. It would be nice if the issue got fixed. 
However, I got around it by using this hack: Renaming some files, folders and config options.

```
cd /usr/lib/ckan/default/src/ckan/ckan/i18n/
sudo mv no/ nb_NO
```

```
cd /usr/lib/ckan/default/src/ckan/ckan/public/base/i18n
sudo mv no.js nb_NO.js
```

In /etc/ckan/default/ckan.ini
```
## Internationalisation Settings
ckan.locale_default = nb_NO
ckan.locale_order = nb_NO sv en pt_BR ja it cs_CZ ca es fr el sr sr@latin sk fi ru de pl nl bg ko_KR hu sa sl lv
ckan.locales_offered = nb_NO sv en
ckan.locales_filtered_out = en_GB
```
