### ISSUE TITLE
New Datasets with DOI - DOI Failed - error code 404

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [ckan/ckan#4940]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
Ckan 2.8. WIth DataCite (DOI), datastore, datapusher

### Please describe the expected behaviour
I can add new resources to public of an organisation. One time it works but second time etc. i got an error.

### Please describe the actual behaviour
I have an organisation and i add first time a ressource. It works, but after i try to add a new dataset with a new resource i got a error: Creating DOI Failed - error code 404

### What steps can be taken to reproduce the issue? 
Install Ckan 2.8 with the plugins DOI, datastore, datapusher and a  test-account by datacite.
Create a organisation and add new datasets.

**Comment by MichaelHarmsTIB** [comment]
[Tue Aug 20 10:43:04.014626 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] 2019-08-20 10:43:04,014 ERROR [ckanext.doi.api] Creating DOI Failed - 404 Client Error: Not Found for url: https://mds.datacite.org/metadata
[Tue Aug 20 10:43:04.014716 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] 2019-08-20 10:43:04,014 ERROR [ckanext.doi.api] Creating DOI Failed - error code 404
[Tue Aug 20 10:43:04.014771 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] 2019-08-20 10:43:04,014 ERROR [ckanext.doi.api] Creating DOI Failed - error Not found
[Tue Aug 20 10:43:04.016048 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] Error - <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://mds.datacite.org/metadata

**Comment by MichaelHarmsTIB** [comment]
[Tue Aug 20 10:43:04.017466 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__
[Tue Aug 20 10:43:04.017470 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   app_iter = self.application(environ, sr_checker)
[Tue Aug 20 10:43:04.017472 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Tue Aug 20 10:43:04.017475 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   resp = self.call_func(req, *args, **self.kwargs)
[Tue Aug 20 10:43:04.017477 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Tue Aug 20 10:43:04.017480 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return self.func(req, *args, **kwargs)
[Tue Aug 20 10:43:04.017482 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
[Tue Aug 20 10:43:04.017484 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return request.get_response(self.app)
[Tue Aug 20 10:43:04.017487 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Tue Aug 20 10:43:04.017489 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   application, catch_exc_info=False)
[Tue Aug 20 10:43:04.017491 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Tue Aug 20 10:43:04.017494 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   app_iter = application(self.environ, start_response)
[Tue Aug 20 10:43:04.017496 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Tue Aug 20 10:43:04.017498 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   resp = self.call_func(req, *args, **self.kwargs)
[Tue Aug 20 10:43:04.018031 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Tue Aug 20 10:43:04.018036 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return self.func(req, *args, **kwargs)
[Tue Aug 20 10:43:04.018038 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
[Tue Aug 20 10:43:04.018040 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   response = request.get_response(self.app)
[Tue Aug 20 10:43:04.018043 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Tue Aug 20 10:43:04.018045 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   application, catch_exc_info=False)
[Tue Aug 20 10:43:04.018047 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Tue Aug 20 10:43:04.018050 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   app_iter = application(self.environ, start_response)
[Tue Aug 20 10:43:04.018052 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware/pylons_app.py', line 265 in inner
[Tue Aug 20 10:43:04.018055 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   result = application(environ, start_response)
[Tue Aug 20 10:43:04.018057 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
[Tue Aug 20 10:43:04.018059 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return self.app(environ, start_response)
[Tue Aug 20 10:43:04.018061 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py', line 156 in __call__
[Tue Aug 20 10:43:04.018064 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return self.wrap_app(environ, session_start_response)
[Tue Aug 20 10:43:04.018066 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
[Tue Aug 20 10:43:04.018068 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   response = self.app(environ, start_response)
[Tue Aug 20 10:43:04.018071 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py', line 30 in __call__
[Tue Aug 20 10:43:04.018073 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return self.app(environ, start_response)
[Tue Aug 20 10:43:04.018075 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py', line 56 in __call__
[Tue Aug 20 10:43:04.018078 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return self.app(environ, start_response)
[Tue Aug 20 10:43:04.018080 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
[Tue Aug 20 10:43:04.018082 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   response = self.dispatch(controller, environ, start_response)
[Tue Aug 20 10:43:04.018085 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
[Tue Aug 20 10:43:04.018092 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return controller(environ, start_response)
[Tue Aug 20 10:43:04.018094 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 240 in __call__
[Tue Aug 20 10:43:04.018096 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   res = WSGIController.__call__(self, environ, start_response)
[Tue Aug 20 10:43:04.018099 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
[Tue Aug 20 10:43:04.018101 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   response = self._dispatch_call()
[Tue Aug 20 10:43:04.018103 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
[Tue Aug 20 10:43:04.018106 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   response = self._inspect_call(func)
[Tue Aug 20 10:43:04.018108 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
[Tue Aug 20 10:43:04.018110 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   result = self._perform_call(func, args)
[Tue Aug 20 10:43:04.018113 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
[Tue Aug 20 10:43:04.018115 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   return func(**args)
[Tue Aug 20 10:43:04.018117 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckan/controllers/package.py', line 712 in new_resource
[Tue Aug 20 10:43:04.018120 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   dict(data_dict, state='active'))
[Tue Aug 20 10:43:04.018122 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 464 in wrapped
[Tue Aug 20 10:43:04.018124 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   result = _action(context, data_dict, **kw)
[Tue Aug 20 10:43:04.018127 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/update.py', line 334 in package_update
[Tue Aug 20 10:43:04.018129 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   item.after_update(context, data)
[Tue Aug 20 10:43:04.018131 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckanext/datacite/ckanext/doi/plugin.py', line 108 in after_update
[Tue Aug 20 10:43:04.018134 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   publish_doi(package_id, **metadata_dict)
[Tue Aug 20 10:43:04.018136 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckanext/datacite/ckanext/doi/lib.py', line 80 in publish_doi
[Tue Aug 20 10:43:04.018138 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   metadata.upsert(**kwargs)
[Tue Aug 20 10:43:04.018140 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckanext/datacite/ckanext/doi/api.py', line 207 in upsert
[Tue Aug 20 10:43:04.018143 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   r = self._call(method='post', data=xml, headers={'Content-Type': 'application/xml'})
[Tue Aug 20 10:43:04.018145 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/src/ckan/ckanext/datacite/ckanext/doi/api.py', line 55 in _call
[Tue Aug 20 10:43:04.018150 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   r.raise_for_status()
[Tue Aug 20 10:43:04.018153 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] File '/usr/lib/ckan/default/lib/python2.7/site-packages/requests/models.py', line 862 in raise_for_status
[Tue Aug 20 10:43:04.018155 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]   raise HTTPError(http_error_msg, response=self)
[Tue Aug 20 10:43:04.018157 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802] HTTPError: 404 Client Error: Not Found for url: https://mds.datacite.org/metadata
[Tue Aug 20 10:43:04.018160 2019] [wsgi:error] [pid 29605:tid 139755694876416] [remote 127.0.0.1:57802]

**Comment by MichaelHarmsTIB** [comment]
Always happened this if I set the ressource on public

**Comment by tino097** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the Gitter [#ckan](https://gitter.im/ckan/chat) channel, where other developers may be able to help you.

Thanks!
