### ISSUE TITLE
API guide incoherent about API or API-s

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#4943]
[The API guide](https://docs.ckan.org/en/latest/api/index.html) starts with:

> This section documents CKAN’s API, for developers who want to write code that interacts with CKAN sites and their data.

This implies CKAN has a single API. Yet, section API versions starts with:

> The CKAN APIs are versioned.

This page is generally inconsistent about the number of API-s which CKAN has. It would help to stick to singular, or to list all CKAN API-s.

By the way, I suppose that in "We recommend that you specify the API number in your requests", "API number" should read "API version number".

**Comment by wardi** [comment]
@Chealer these are good suggestions, mind submitting a PR?

**Comment by Chealer** [comment]
Thank you wardi, but I am just starting to learn CKAN. I know that some things are wrong, but I don't really know the reality yet nor the best way to present it.
Also, in this specific case there may be a terminological issue. Perhaps the guide uses the term "API" in 2 different senses, and it may be that for one of these senses, it should be replaced by a different term (say, "sub-API"). Such renaming would require discussion among contributors sufficiently knowledgeable about CKAN to evaluate the impacts.

**Comment by Gauravp-NEC** [comment]
@wardi , I have raise the PR https://github.com/ckan/ckan/pull/5740 to close this issue.

**Comment by Chealer** [comment]
Thank you @Gauravp-NEC 
This probably goes in the right direction, but if the solution is to consider that CKAN has several API-s, references to "the CKAN API" should be removed. I suppose they should be replaced by references to "CKAN's Action API". Or simply "the Action API".

By the way, the guide contains "Version 3 is currently the only version of the Action API."

**Comment by Chealer** [comment]
Can this ticket be reopened?

**Comment by Gauravp-NEC** [comment]
@Chealer ,This ticket is closed by PR #5740 . I will suggest you to raise a new ticket if you want more changes for API guide.
