### ISSUE TITLE
Please provide an official Postman collection

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#4948]
It would be helpful to provide (or refer to) a [Postman](https://www.getpostman.com/) collection so that CKAN's API can be used/tested easily. The Postman software is proprietary, but the format of its collections looks like straightforward JSON, if it isn't documented.

I found [a Postman API for CKAN](https://github.com/EMN-Data/ckan-api-postman), but it isn't clear if that's supposed to be specific to EMN or generic, and the repository is not in great shape in any case.

**Comment by amercader** [comment]
Sounds useful but not something that the technical team can work on. If you or someone from the community wants to give it a go the repo linked seems like a good start.

**Comment by Chealer** [comment]
@amercader , is the team missing something?
And do you have any indication that the ckan-api-postman repository intends to target generic CKAN?
