### ISSUE TITLE
ERROR:  role "datastore_ro" already exists

### ISSUE THREAD

**Issue by thsohn17** [ckan/ckan#4960]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

No.
### CKAN Version if known (or site URL)
2.8.2

### Please describe the expected behaviour
i am trying to run the docker command below in order to create readonly user from db container. 

ERROR:  role "datastore_ro" already exists

i am expecting something like create complete message after running this command. 

### Please describe the actual behaviour
but i got the error message "ERROR:  role "datastore_ro" already exists" . 

### What steps can be taken to reproduce the issue? 

Create and configure datastore database . 

could anybody help me with this issue? 
thanks ~

**Comment by amercader** [comment]
The `datastore_ro` user should have been created for you when building the postgres image. The error is just telling you that the user already exists.

Closing, please reopen if you find an actual issue, for support head to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 
Thanks!
