### ISSUE TITLE
Automatic Upload

### ISSUE THREAD

**Issue by ziusware** [ckan/ckan#4963]
### CKAN Version if known (or site URL)
2.9.0

### Please describe the expected behaviour
I have a ckan website.I upload data manually to the datastore, its working perfectly. However my actual requirement is to automate the process.I want a job scheduler which automatically upload data like geojson,excel,csv,txt,pdf, etc in the ckan application. Please provide inputs

Thanks

**Comment by amercader** [comment]
What you need is the either the [Express Loader](https://github.com/ckan/ckanext-xloader) or the [DataPusher](https://docs.ckan.org/en/latest/maintaining/datastore.html#datapusher-automatically-add-data-to-the-datastore).

In the future please submit support requests like this one to the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 


Thanks!
