### ISSUE TITLE
Database [performance] for group_extras and resource

### ISSUE THREAD

**Issue by bzar** [ckan/ckan#4974]
Related to #3511

### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
Fetching from `group_extra` by `group_id` or from `resource` by `package_id` is fast.

### Please describe the actual behaviour
With enough data, both become slow. The former is especially visible when fetching `organization_list`.

### What steps can be taken to reproduce the issue? 
Insert a lot of organizations with a translated `ckanext-fluent` `title_translated` field, then attempt to get a list of organizations with translated names.

### Proposed fix
Add database indices for `group_extra (group_id)` and `resource (package_id)`. These speed up the operations considerably.

**Comment by bzar** [comment]
I would've included a PR, but master has transitioned to alembic and I haven't had the time yet to look into it.

**Comment by amercader** [comment]
The additions that you propose sound great to have on master (2.9) so a PR is most welcome. On previous releases we can suggest the change in the CHANGELOG so people can run it manually if needed.
