### ISSUE TITLE
Facet + search not working within organization page

### ISSUE THREAD

**Issue by mgaitan** [ckan/ckan#4990]
### CKAN Version if known (or site URL)

2.8

### Please describe the expected behaviour

I should be able to facet a search result list whitin an organization page

### Please describe the actual behaviour

Faceted search whitin organization returns empty results, when some results are expected

### What steps can be taken to reproduce the issue? 

Using official docker image (https://github.com/okfn/docker-ckan) create an organization with name `my-org` and 4 datasets with `keyword1` in 2 of them and diferent kind of resources for each ne. 

- Go to `/dataset` and do a search for `keyword1` and facet results by organization and format. Result should be filtered correctly. 
- Go to `/organization/my-org` and repeat the same search. Results without facets are correct, but when you try to filter by format or other criterium, you'll get no results. 

Demo @ youtube https://www.youtube.com/watch?v=1OckOI0j3ss

[![](https://img.youtube.com/vi/1OckOI0j3ss/0.jpg)](https://www.youtube.com/watch?v=1OckOI0j3ss)

**Comment by mgaitan** [comment]
@wardi  @smotornyuk I have a one-line patch for this. Opening the PR in a moment.

**Comment by sivang** [comment]
@wardi @smotornyuk any idea if this got merged / fixed in any form?

**Comment by smotornyuk** [comment]
Yes, the fix is available in v2.9
Original code from the group controller replaced by a call to [function](https://github.com/ckan/ckan/blob/1fb0d785657de6d2a01be0c412e40c843b4efd72/ckan/views/dataset.py#L247) which contains [suggested fix](https://github.com/ckan/ckan/blob/1fb0d785657de6d2a01be0c412e40c843b4efd72/ckan/views/dataset.py#L184)
