### ISSUE TITLE
Help strings for paster commands

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckan#5002]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
The CKAN Getting Started (https://docs.ckan.org/en/2.8/maintaining/getting-started.html) docs say to run `paster sysadmin add seanh email=seanh@localhost name=seanh -c /etc/ckan/default/production.ini`, but `paster sysadmin --help` only says:

```
sysadmin add USERNAME [FIELD1=VALUE1 FIELD2=VALUE2 ...]
                              - creates a new user that is a sysadmin
                                (prompts for password and email if not
                                supplied).
                                 Field can be: apikey                                          
                                               password
                                               email
```

### Please describe the actual behaviour
Name is missing from the field list help string (or, name isn't a valid field name at all, and the Getting Started page is wrong) 

### What steps can be taken to reproduce the issue? 
n/a

**Comment by wardi** [comment]
Yes it looks like the documentation is wrong here. Would you care to submit a PR?

**Comment by wood-chris** [comment]
Submitted!

I haven't gone through a lot of the other code in much detail, but I see that the help strings say that apikey is a valid field - I can't see where this is parsed in `user_add` tho?
