### ISSUE TITLE
Datastore Create does not work

### ISSUE THREAD

**Issue by ziusware** [ckan/ckan#5009]
### CKAN Version if known (or site URL)
2.82.1

### Please describe the expected behaviour
When I request the "http://MY_CKAN_URL//api/3/action/datastore_create" from API it would have to create a new dataset on my ckan;

### Please describe the actual behaviour
When I request the "http://MY_CKAN_URL//api/3/action/datastore_create" from API it returnes this error.

> {
    "help": "http://MY_CKAN_URL/api/3/action/help_show?name=datastore_create",
    "success": false,
    "error": {
        "message": "Internal Server Error",
        "__type": "Internal Server Error"
    }
}

Do someone know how to solve this issue?

**Comment by wardi** [comment]
When you get an internal server error there should be a traceback in the server log files that will help tell us what went wrong. Please attach that traceback to this issue. It's possible your datastore is not set up or misconfigured but we can't tell without more information.

**Comment by anmobor** [comment]
Hello @wardi I have installed CKAN in Docker and I have the same error and that is what I have inside ckan_default.error.log:

[wsgi:error] [pid 20:tid 140290595436288] [remote 127.0.0.1:50840]  [SQL: 'CREATETRIGGER zfulltext\\n        BEFORE INSERT OR UPDATE ON "c8ad5ab0-da25-4935-8619-167ea686a1cf"\\n        FOR EACH ROW EXECUTE PROCEDURE populate_full_text_trigger()']

And this inside error.log:  [core:notice] [pid 18:tid 140290744224704] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

furthermore I have all the time this: 
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.4.222. Set the 'ServerName' directive globally to suppress this message

**Comment by Suryakandukuri** [comment]
@wardi Can you please help with a solution on this? I have already tried datastore set-permissions. Maybe I missed something, but this issue persists.

Thanks, Surya
