### ISSUE TITLE
Inconsistency between resource URLs and site_url

### ISSUE THREAD

**Issue by dottyz** [ckan/ckan#5010]
**CKAN 2.8.2 - https://ckan0.cf.opendata.inter.prod-toronto.ca**

We have 2 CKAN instances set up with a master-slave replication for PostgreSQL (with one behind a firewall and the other open to the public). Both CKAN instances share the same SOLR instance and have different URLs.

**Part 1 of the issue:** The resource URLs always uses the host where the SOLR index was built from instead of the site_url in production.ini. Although this make sense given that they share the same SOLR but not sure if this is the intended behaviour. 

To work around this, we update our extension to modify the resource URL to use the same host as the site_url on resource before_show (similar to how the datastore extension modifies the URL to the datastore dump URL). 

**Part 2 of the issue:** The extension resolve the issue for most situations except for when making calls to the package_search endpoints. It seems like the before_show is not called for package_search and all resources reverts back to the host where the SOLR index was generated from. 

**To replicate:** This can difference can be seen by comparing the response from https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/package_search?q=name:city-wards vs. https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/package_show?id=city-wards

Seems related to #5000 as well

**Comment by wardi** [comment]
Running two ckan sites from one DB image is an interesting idea, but I can see it causing problems.

ckan stores the complete dataset metadata in solr (including full URLs to resources) so it can be returned efficiently. Parsing and replace every url in package_search results is possible but you'll have to override the `package_search` action to do it, there's no plugin because of the performance impact.

**Comment by dottyz** [comment]
I see, so I guess the best solution would be to have 2 instances of SOLR as well then?

**Comment by wardi** [comment]
That could work. You'll just have to make sure changes to datasets get reindexed in both cores (with the right host names)

**Comment by dottyz** [comment]
Great thanks for the help!

**Comment by dottyz** [comment]
We have managed to set up separate SOLR instances for both of our internal and public CKAN instances, but having a bit of issues with updating the index for both cores. 

Would you suggest ideas for reindexing and keep the URLs different between the two instances? 

Thanks in advance for the help!
