### ISSUE TITLE
facet search uses the free text search `q`, breaking free text within organization

### ISSUE THREAD

**Issue by sivang** [ckan/ckan#5017]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
When faceting upon a filter field, results should be returned accordinglt to the amount of available times.

### Please describe the actual behaviour
Search returns nothing

### What steps can be taken to reproduce the issue? 
- Go to an organization page dataset list display
- enter a search term in the text field
- Choose another facet to filter , ie 'CSV'.
- See no results are returned

When inspecting this is what's getting on the search strings:
```
'q': u'test res_format: "CSV"'
```

Clicking on the facet should add this criteria to the `fq` rather than to `q`

**Comment by mutantsan** [comment]
Hi! I've create a PR #5053
