### ISSUE TITLE
popular tags breaks when overriden in PackageController::`before_search`

### ISSUE THREAD

**Issue by sivang** [ckan/ckan#5018]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
Popular Tags continues working no matter changes done in `before_search`

### Please describe the actual behaviour
Popular Tags stops working

### What steps can be taken to reproduce the issue? 
- Use `before_search` , add a filter query to `search_params['q']` 
- See popular tags stops working on home page

**Comment by wardi** [comment]
@sivang (as mentioned on the call): please add a link to the code you're using that causes this problem

**Comment by sivang** [comment]
After more investigation, I realized the code I was using was dropping a `:` out of the wildcard search query which was wrong so I special cased it so this is not a bug in CKAN but in a workaround, that tries to make sure a colon (:) does not break search, gone wrong.

Closing as this is INVALID.
