### ISSUE TITLE
Search extra fields

### ISSUE THREAD

**Issue by MandanaMoshref** [ckan/ckan#5021]
### CKAN Version if known (or site URL)
Ckan: 2.8
Solr: 7.7.2

### Please describe the expected behaviour
To be able to run a temporal search based on an additional/extra field for collection date of a datase and not only based on modified or created date.

### Please describe the actual behaviour
I have some datasets which have the collection dates (range: [startDate - endDate])
At the moment I do not want to add this field (in fact two fields for start and end date) into the metadata but manually to add it for few datasets. It means [this option](https://docs.ckan.org/en/latest/extensions/adding-custom-fields.html) "Adding custom fields" is not my aim.

Meantime I have found an extension which only provides the user interface for temporal search and it is based on ckan "metadata_modified" and/or "metadata_created".
https://github.com/geosolutions-it/ckanext-datesearch

However, it only takes the created or last modified date from CKAN. I would like to add the same interface and temoral search functionality to my CKAN instance but to search for those datasets which have the startDate and enDate as extra fields.

In the same extension in another [branch](https://github.com/geosolutions-it/ckanext-datesearch/tree/c007/indexing), it is suggested to be able to index temporal fields into Solr the XML schema must be modified. However, it doesn't return any datasets.

Is there any extension which provides temporal search for extra field? and if not what should be the steps to implement it?

This is especially necessary for the Harvested CSW datasets where the created date is not the same as the one in the ckan and it is most of the time added as extra fields (based on my configuration).

Best regards
Mani  

### What steps can be taken to reproduce the issue? 
Either to add this extension:
https://github.com/EUDAT-B2FIND/ckanext-timeline
with including the solr indexing from:
https://github.com/geosolutions-it/ckanext-datesearch/tree/c007/indexing
https://github.com/geosolutions-it/ckanext-datesearch/blob/c007/ckanext/datesearch/plugin.py#L37

**Comment by amercader** [comment]
@MandanaMoshref 

The steps to add a date range filter are basically:

* Index the relevant fields as `date` in Solr. If you index the fields with a name ended in `*_date` (in the `before_index` plugin method) CKAN will do that for you automatically, so no need to change the Solr schema.
* Construct a date range query that Solr understands when a query is sent. This is done in the `before_search`  plugin method)
* Provide a UI widget to allow users to either enter or select dates, and send these values in the format expected.

The extensions you linked do some of these point. Additionally this one also implements a working date range search on custom date fields: https://github.com/okfn/ckanext-tsbsatellites

Look on the [plugins.py](https://github.com/okfn/ckanext-tsbsatellites/blob/master/ckanext/tsbsatellites/plugin.py#L73) file for the `before_index` and `before_search` methods, and on [search.html](https://github.com/okfn/ckanext-tsbsatellites/blob/master/ckanext/tsbsatellites/theme/templates/package/search.html#L6) for the UI side of it.

This will be really useful to extract on a reusable plugin.

Closing as this is not an issue with CKAN core. Try the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [Gitter channel](https://gitter.im/ckan/chat) if you need more help

Thanks!

**Comment by MandanaMoshref** [comment]
I know this is closed and roughly old issue, just for those who have the same requirements as me, here is my extention with a greate help provided by @amercader 
[ckanext-datesearch](https://github.com/MandanaMoshref/ckanext-datesearch/)

**Comment by amercader** [comment]
Thanks for sharing @MandanaMoshref!
