### ISSUE TITLE
Cannot register user at demo.ckan.org

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#5022]
When you try and register on https://demo.ckan.org/, when you click create account, it returns "Bad Captcha. Please try again."

The registration form contains no Captcha form for users to complete, hence it is impossible to register.

**Comment by Aaron-M** [comment]
The inability for **anyone** to register on demo.ckan.org is hindering the ability to address other issues (e.g. by testing/demonstrating issues using the demo install).

**Comment by bazayod** [comment]
also I have this problem "no Captcha" when register on https://demo.ckan.org/

**Comment by imran1122** [comment]
bazayod I am facing the same issue if you solve the Captcha problem can you please share.

**Comment by howff** [comment]
demo.ckan.org has been completely broken for ages.
Maybe if everyone contacts  stewards@ckan.org  it will get fixed :-)

Recent thread:
"the demo site is hosted by Datopian right now. But yes, if you email stewards@ckan.org then that email will go to both xxx and myself :)
If anyone is skilled up with WordPress and would like to help update the website while it is also migrated to a new home with WP Engine then please PM me :)
If anyone is keen to contribute design skills then that is also welcome.
No stress if folks are too busy but feel pressure to help :) I have folks both at Link Digital and at Datopian that can help but it would be more fun to work with some others and share the work more (and, the rewards of knowing you helped with a fun bit of work)"

**Comment by amercader** [comment]
@sivang can you reach at the relevant person in Datopian to address this?

@howff @Aaron-M @bazayod If you need to test some functionality in the meantime you can use https://beta.ckan.org, which is running CKAN 2.8

**Comment by Aaron-M** [comment]
@amercader  I tred the beta site - the exact same problem exists there:
![image](https://user-images.githubusercontent.com/4842751/69371953-b15ed080-0d05-11ea-942a-86bca101b48b.png)

**Comment by Chealer** [comment]
I reported the issue with beta.ckan.org in ticket #5220.
