### ISSUE TITLE
Updating/Adding a Resource sets obj.url_changed = True to all other uploaded resources of the package

### ISSUE THREAD

**Issue by pdelboca** [ckan/ckan#5027]
### CKAN Version if known (or site URL)
2.8.3 but as far as  tested it also happens in master

### Please describe the expected behaviour
Updating or adding a new resource to the package shouldn't set `obj.url_changed=True` in other resources with uploaded files of the same package.

### Please describe the actual behaviour
* Each time a resource is created if a file is uploaded, the `__init__` method of ResourceUpload sets the `resource['last_modified']` field.
* Later, each time a new resource is added to the Package (or an existing resource of that package edited) when executing `resource_dict_save` the `obj.url_changed` is set to true due to this condition: https://github.com/ckan/ckan/blob/f717999a1a4e63ecc192cb4dfe5a7506b7c8cff0/ckan/lib/dictization/model_save.py#L51

This causes the `IResourceURLChanged` interface to be notified even when nothing changed, but regardless that, it is confusing of why it is set to `True` if nothing changed on the resource.

### What steps can be taken to reproduce the issue? 
- Create a new CKAN instance
- Add a Package
- Add `resource_1` to it. *This resource should be a file to be uploaded*.
- Add a `resource_2` to the same package

This last action will call `resource_dict_save` for each resource of the package and when executing it for `resource_1`it will set `obj.url_changed` in the mentioned condition.

**Comment by amercader** [comment]
@pdelboca This is obviously a bug, and the problem is right above the line you linked:
https://github.com/ckan/ckan/blob/f717999a1a4e63ecc192cb4dfe5a7506b7c8cff0/ckan/lib/dictization/model_save.py#L48:L50

This assumes that `value` (ie the value of `resource['last_modified']`) is a string, but [that is not the case](https://github.com/ckan/ckan/blob/f717999a1a4e63ecc192cb4dfe5a7506b7c8cff0/ckan/lib/uploader.py#L222).

We need something like:

```diff
diff --git a/ckan/lib/dictization/model_save.py b/ckan/lib/dictization/model_save.py
index a9514e648..27f2f5542 100644
--- a/ckan/lib/dictization/model_save.py
+++ b/ckan/lib/dictization/model_save.py
@@ -46,7 +46,11 @@ def resource_dict_save(res_dict, context):
             continue
         if key in fields:
             if isinstance(getattr(obj, key), datetime.datetime):
-                if getattr(obj, key).isoformat() == value:
+                if isinstance(value, string_types):
+                    db_value = getattr(obj, key).isoformat()
+                else:
+                    db_value = getattr(obj, key)
+                if  db_value == value:
                     continue
                 if key == 'last_modified' and not new:
                     obj.url_changed = True
```

Can you submit a PR? This should be backported.

**Comment by pdelboca** [comment]
Great! I will submit the PR thanks!

**Comment by ThrawnCA** [comment]
Can this be backported to CKAN 2.8? We're seeing serious performance problems when updating a dataset containing many resources (over 180), with hundreds of unnecessary XLoader tasks being created and suspected database lock contention.

**Comment by ThrawnCA** [comment]
Just in case anyone's curious, we've backported this patch on data.qld.gov.au, and it worked very well. Within 8 hours of deploying the change, we went from an XLoader processing backlog of over 12 hours, to no backlog at all.

**Comment by ThrawnCA** [comment]
Update: We're still seeing the `resource_update` API trigger XLoader jobs for every other resource in the package.

Sample log:

    [Sun Mar 01 05:05:39.837770 2020] [:error] [pid 31205] 05:05:39,837 INFO  [ckan.lib.base]  /api/3/action/xloader_hook render time 0.050 seconds
    [Sun Mar 01 05:05:41.938961 2020] [:error] [pid 31205] 05:05:41,938 DEBUG [ckanext.xloader.plugin] Submitting resource 77ca1d7a-2b2a-40b4-95f2-45373f8795b3 to be xloadered
    [Sun Mar 01 05:05:42.058169 2020] [:error] [pid 31205] 05:05:42,058 INFO  [ckanext.xloader.action] Added background job baeaa8e4-a928-491c-a79c-63b52ae1e682 to queue "default"
    [Sun Mar 01 05:05:42.058301 2020] [:error] [pid 31205] 05:05:42,058 DEBUG [ckanext.xloader.action] Enqueued xloader job=baeaa8e4-a928-491c-a79c-63b52ae1e682 res_id=77ca1d7a-2b2a-40b4-95f2-45373f8795b3
    [Sun Mar 01 05:05:42.849137 2020] [:error] [pid 31205] 05:05:42,849 INFO  [ckan.lib.jobs] Added background job 6e2ff392-47d4-4e07-b5da-2cf31944c368 to queue "default"
    [Sun Mar 01 05:05:43.002557 2020] [:error] [pid 31205] 05:05:43,002 INFO  [ckan.lib.jobs] Added background job 24f73ef6-7c17-4ad5-adc0-2335a31e9ed1 to queue "default"
    [Sun Mar 01 05:05:43.158924 2020] [:error] [pid 31205] 05:05:43,158 INFO  [ckan.lib.jobs] Added background job 50bdcd8f-5d2e-44fb-ba30-8dc14e15b05b to queue "default"
    [Sun Mar 01 05:05:43.310997 2020] [:error] [pid 31205] 05:05:43,310 INFO  [ckan.lib.jobs] Added background job bdb825fa-fbf5-48a1-ab22-d4321b0946d7 to queue "default"
    [Sun Mar 01 05:05:43.465801 2020] [:error] [pid 31205] 05:05:43,465 INFO  [ckan.lib.jobs] Added background job 24f28a97-8c94-4820-b56b-e9faf773a429 to queue "default"
    [Sun Mar 01 05:05:43.616758 2020] [:error] [pid 31205] 05:05:43,616 INFO  [ckan.lib.jobs] Added background job 88f23a78-aa65-454b-800e-a2b1d86974ac to queue "default"
    [Sun Mar 01 05:05:43.774292 2020] [:error] [pid 31205] 05:05:43,774 INFO  [ckan.lib.jobs] Added background job 1793cd68-fc40-4d59-a439-c9845e157b75 to queue "default"
    [Sun Mar 01 05:05:43.932183 2020] [:error] [pid 31205] 05:05:43,932 INFO  [ckan.lib.jobs] Added background job 6b5eaf8b-db55-4df5-abb9-bf4a05f783ab to queue "default"
    [Sun Mar 01 05:05:44.084553 2020] [:error] [pid 31205] 05:05:44,084 INFO  [ckan.lib.jobs] Added background job 8447127c-7ea6-4eea-98da-cd75af58bf4d to queue "default"
    [Sun Mar 01 05:05:44.236180 2020] [:error] [pid 31205] 05:05:44,236 INFO  [ckan.lib.jobs] Added background job 148a8925-7e22-4bfe-a6fd-df94d4974535 to queue "default"
    [Sun Mar 01 05:05:44.388622 2020] [:error] [pid 31205] 05:05:44,388 INFO  [ckan.lib.jobs] Added background job 22ef4f73-a7ea-41eb-8e1b-bf278a8cc50c to queue "default"
    [Sun Mar 01 05:05:44.538217 2020] [:error] [pid 31205] 05:05:44,538 INFO  [ckan.lib.jobs] Added background job c01ca1ce-7ca4-4fec-bbd8-3e76d40d27b9 to queue "default"
    [Sun Mar 01 05:05:44.690299 2020] [:error] [pid 31205] 05:05:44,690 INFO  [ckan.lib.jobs] Added background job 35c9e79b-a867-49e0-ba23-1e497b406fc3 to queue "default"
    [Sun Mar 01 05:05:44.839884 2020] [:error] [pid 31205] 05:05:44,839 INFO  [ckan.lib.jobs] Added background job 42c7e501-66cd-4d26-a572-520993535c9a to queue "default"
    [Sun Mar 01 05:05:45.008009 2020] [:error] [pid 31205] 05:05:45,007 INFO  [ckan.lib.jobs] Added background job 963f5efa-60c1-4ead-bf59-0c9f33bf3f82 to queue "default"
    [Sun Mar 01 05:05:45.167537 2020] [:error] [pid 31205] 05:05:45,167 INFO  [ckan.lib.jobs] Added background job e66d654e-a1c1-4ebe-a5f1-1d2b94343cd2 to queue "default"
    [Sun Mar 01 05:05:45.326267 2020] [:error] [pid 31205] 05:05:45,326 INFO  [ckan.lib.jobs] Added background job b5ab7d8b-bb50-49c8-95f1-1a13d3182e23 to queue "default"
