### ISSUE TITLE
usage of special /__after/ field in schema breaks dataset validation

### ISSUE THREAD

**Issue by sivang** [ckan/ckan#5029]
## CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
Expected behavior is that I can finish creating a new dataset including adding a resource.

### Please describe the actual behaviour
When trying to add the resource and finish dataset creation (as followed from `dataset/new`) a **Dataset id already exists** error occurs (no traceback) and the dataset remains in draft state.

### What steps can be taken to reproduce the issue? 
Following the documentation @ https://docs.ckan.org/en/2.8/extensions/adding-custom-fields.html#custom-validators
I have created an example extension that when installed onto a fresh vainalla CKAN instance will reproduce the error reliably via the UI, as described above but in general:
- Make sure the extension https://github.com/sivang/ckanext-brokenafter is installed.
- Try to create a new dataset and finish the creation by adding a resource.

**Comment by amercader** [comment]
I'm afraid there's not much shared knowledge about the  `__after` validators. I'll see if I can install the extension and learn more but you might have to investigate deeper into how CKAN uses them to see how (and if) they work.

**Comment by sivang** [comment]
@amercader there seemed to have an error in my code due to copy pasting from the docs, so it seems fixed but I'll test further and update if the issue persists.
