### ISSUE TITLE
Intermittent very high render times

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#5030]
### CKAN Version if known (or site URL)

2.7.3, 2.8.3

### Please describe the expected behaviour

Pages should normally load in under 10 seconds.

### Please describe the actual behaviour

Page loads are normally fast (around 1 second) but sometimes take over 30 seconds, causing proxies to time out. This is particularly problematic when it occurs during dataset creation, because it leaves the dataset in 'draft' state and cannot be resolved by resubmitting the request; the dataset must be located via the My Datasets page and edited to fix its state.

### What steps can be taken to reproduce the issue? 

No consistent cause has been found.

**Comment by amercader** [comment]
There's definitely more information needed here. There have been recent improvements in render times but the issues that they fixed would have consistent slow times, not spikes.
Spikes like these generally suggest a problem in the underlying infrastructure (db connections, memory issues etc).
If you can pinpoint some steps and conditions to consistently reproduce it feel free to reopen.

**Comment by ThrawnCA** [comment]
Just saw this happen in a development environment, so not under any special load, taking *85.044 seconds* to render `/dataset/new`. Tried it again and took 10.849 seconds.

**Comment by ThrawnCA** [comment]
Update: This has started happening consistently on new datasets in our production environment. Adding debugging statements indicates that the time is being spent in attempting to load tracking summary data (`ckan/model/tracking.py`, TrackingSummary.get_for_package), although in the end no tracking data exists since they're new datasets.

**Comment by ThrawnCA** [comment]
This appears to be related to the combination of ORDER BY and LIMIT 1; see https://stackoverflow.com/questions/21385555/postgresql-query-very-slow-with-limit-1 and https://stackoverflow.com/questions/6037843/extremely-slow-postgresql-query-with-order-and-limit-clauses for discussion.

There is a simple workaround of adding a second unnecessary ordering clause, which causes PostgreSQL to make better query plan choices.
