### ISSUE TITLE
GEOJson data in map viewer

### ISSUE THREAD

**Issue by theokcu** [ckan/ckan#5050]
I have installed on my computer with the references from 
[Ckan 2.8.1](https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html)
and [Issue 4916](https://github.com/ckan/ckan/issues/4916#issuecomment-515564751) with ubuntu 18.04.
The ckan web site is up and working. Now i am trying to explore new features of ckan and add some data and visualize them. 
I tried creating data set and giving a reference to an external GEOJSON file from malaga data. And installed some plugins. In map viewer i get just a map not pin points.  And after clicking some where else i get 'Could not proxy resource because a connection error occurred. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)' error on web site. I couldn't find a solution neither in here nor in google. Does anyone have a clue about what should i do?

Also the data link i use for my data set is [Malaga Parking Spot Data](https://datosabiertos.malaga.eu/recursos/urbanismoEInfraestructura/equipamientos/da_aparcamientosResidente-4326.geojson)

**Comment by amercader** [comment]
@theokcu When trying to render an external GeoJSON file (or any other external file) the view will use the `resource_proxy` plugin to get the external data to get around the same origin policy. In your case it looks like there is an SSL (https) error when trying to get that data. Are the logs showing more information? Are you using the `geojson_view` plugin?

**Comment by theokcu** [comment]
@amercader I have added geo_view as my pluin and geo_view and geojson_view as my default views. I have also added ssl_verify = false to my development.ini file. I don't think logs are showing more information or if they do i am not aware of those.

**Comment by theokcu** [comment]
@amercader I have also installed geojson_view plugin. Should i also install ressource_proxy to overcome this problem?

**Comment by theokcu** [comment]
@amercader I have installed resource_proxy plugin, and as afore mentioned i have add ssl_verify = false to my config file. After some digging i have also added ckan.cors.origin_allow_all = true into my config file. I haven't found anything else in ckan configuration options. But none of them worked for me. I still get 
Could not proxy resource because a connection error occurred. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727) 

error when i try to acces data in my ckan website. Do you have any other suggestion? Thank you in advance.
