### ISSUE TITLE
Data Store GeoJSON

### ISSUE THREAD

**Issue by theokcu** [ckan/ckan#5077]
Hey there,

I am new in CKAN and i have installed 18.04 ubuntu with ckan 2.8.2. CKAN is runnig now. I have also installed datastore and imported some csv files into my database. Now i want to try to import some geojson data in my database and visualize them on my from my local source. I have tried some methods but no success. Is theree any one who has any idea how to do that? Thanks in advance.

**Comment by amercader** [comment]
The DataStore can only hold tabular data, not JSON based one. If you want to preview GeoJSON files have a look at the `geojson_view` plugin of the [ckanext-geoview](https://github.com/ckan/ckanext-geoview) extension.
