### ISSUE TITLE
ckan rest api package update without removing existing resources

### ISSUE THREAD

**Issue by Akshay-Hegde** [ckan/ckan#5078]
I tried `/api/action/package_update` method, in which I noticed existing resources removed, I am on latest ckan 2.8.3

- Is there any possibilities to retain existing resources ?
- I had gone through https://docs.ckan.org/en/2.8/api/#ckan.logic.action.update.package_update
- I had gone through https://github.com/ckan/ckan/blob/master/ckan/logic/action/update.py#L602

How do I updated without removing existing resources, I see `allow_partial_update = true` in `context`, but unable to find docs on how to set context in rest api docs.

**Comment by amercader** [comment]
`package_update` will update the whole dataset dict with the data provided, so if you pass an empty resources list, it will delete them. From the docs:

> It is recommended to call ckan.logic.action.get.package_show(), make the desired changes to the result, and then call package_update() with it.

You can do as above and resubmit the whole dataset dict, or use [`package_patch`](https://docs.ckan.org/en/2.8/api/#ckan.logic.action.patch.package_patch), which will only update the keys that you provide and leave the rest of the dataset dict as is.
