### ISSUE TITLE
Allow extensions to define Click commands

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5108]
The core ones are migrated but currently there is no way for extensions to add commands to the main `ckan` one (eg `ckan harvester`, `ckan saml2 initdb` etc).

This is the place where it should happen: [ckan/cli/cli.py](https://github.com/ckan/ckan/blob/master/ckan/cli/cli.py). In the same way that the core ones are added with the `ckan.add_command()` call, we should iterate all extensions and register any commands provided by them.

Extension paster commands use entrypoints defined in the extensions `setup.py` file (`[paste.paster_command]`). Perhaps for the `ckan` one we could follow the existing pattern of providing an interface (eg `ICLICommand`) with a `get_commands()` method that plugins can implement. This will return a reference to the click command defined in the extension (like the different modules on `ckan/cli/`).

Then on `ckan/cli/cli.py` we iterate over all plugins and load the provided commands (check how we get [extensions blueprints](https://github.com/ckan/ckan/blob/master/ckan/config/middleware/flask_app.py#L188) for an example).

If there are methods from the core cli module that would be helpful to extensions we can add them to the toolkit (eg `error_shout`)

**Comment by mutantsan** [comment]
Hi, I've tried to implement this feature in this PR #5112 . It works, but probably needs some improvements.
