### ISSUE TITLE
Update documentation with the new CLI commands

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5109]
Now that the all commands are available in the new `ckan` command we need to update the docs to replace usage of the paster based ones.

- [ ] The main CLI doc page is [this one](https://github.com/ckan/ckan/blob/master/doc/maintaining/paster.rst)
- [ ] Besides, we need to replace all `paster xxx` commands listed in the docs with its `ckan xxx` counterparts
- [ ] Include info on how to add commands from extensions after #5108 is done

**Comment by kowh-ai** [comment]
I’m in the process of updating all “pre CKAN 2.9 paster command” CKAN documentation and I see the new “ckan” command replacement requires the CKAN config (.ini) file. The “paster” command did not require this. 

(default) [brett@ckan-training ~]# ckan  user --help
ERROR: You need to specify the CKAN config (.ini) file path.
Use the --config parameter or set environment variable CKAN_INI or have development.ini
in the current directory.

Shall I go ahead and remove the references to paster that DOES not include the .ini file in the new CKAN 2.9 documentation?

**Comment by kowh-ai** [comment]
@smotornyuk and @amercader have anwsered these questions
