### ISSUE TITLE
Remove old paster CLI commands

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5110]
Once #5108 and #5109 are done we can remove the old paster commands in `ckan/lib/cli.py`.

At least for CKAN 2.9 let's remove the actual commands only and keep the `CkanCommand` class as this is present in the toolkit and needed by extensions to implement paster-based commands. Also utilities like `load_config` as they might be imported from extensions.

There's is some click-based stuff in there which I don't know if it's still relevant (`click_config_option`, `paster_click_group`...). If no longer needed it can be removed.

**Comment by EvgeniiaVak** [comment]
I would like to take this one.

**Comment by amercader** [comment]
@EvgeniiaVak great! Let us know if you need any pointers

**Comment by EvgeniiaVak** [comment]
@amercader  
Yes, some pointers would be helpful. Although I don't know what exactly to ask for. As I understand, there was paster, that was used for everything, now flask is used for creating the server, click - for cli commands.

I can also wait for https://github.com/ckan/ckan/issues/5109 and continue to lean how ckan in general works in the mean time.

I hope this feature is not very urgent, because I don't think I can complete it very soon.

**Comment by amercader** [comment]
@EvgeniiaVak not a problem and sorry for not coming back to you sooner.

The old paster commands are defined in `ckan/lib/cli.py`. Their new equivalents are written in Click and located in `ckan/cli/cli.py`.

The next version of CKAN will only use the new Click based CLI so we want to remove as much as possible from the old paster ones to avoid confusion. But we can't delete the whole ckan/lib/cli.py module because extensions rely on some classes and methods from that module to write their own commands, and we want to give them time to migrate.

So here's how we could approach it:

- [ ] Remove all `XYZCommand` classes from ckan/lib/cli.py, except the main `CkanCommand` one.
- [ ] Keep the `load_config` and `query_yes_no` methods as these are used by extensions, all the rest of methods and unused imports can be removed
- [ ] Check that the new CLI works fine (`ckan -h`) and that the old CLI still works on a command provided by an extension, eg from ckanext-harvest `paster --plugin=ckanext-harvest harvester sources -c /path/to/ini` (it can be any command from any extension)

Let me know if this helps

**Comment by EvgeniiaVak** [comment]
@amercader 
Yes, this clarifies things very much, thank you!

**Comment by EvgeniiaVak** [comment]
### From gchat with @pdelboca 

@EvgeniiaVak:
> I was looking for the tests for the new cli commands and didn't find any. I guess I could update the ckan/tests/lib/test_cli.py to use the new commands. And probably move test_cli.py to ckan/tests/ (out of lib dir). Or maybe I miss something here?
> Also I was launching the tests with nosetests --with-pylons=test-core.ini ckan/tests/lib/test_cli.py command and I've seen somewhere among other issues we are moving away from pylons. Should I use something else?

@pdelboca:
> Those are good questions, initially yes, it will be good to have the new CLI commands tested
so migrating the old paster tests to the new ckan command would be nice
> But... indeed, we are moving from nosetests to pytest in this whole Py3 project
> So there are two tasks there: Migrate old tests from paster to ckan AND from nosetest to pytest
