### ISSUE TITLE
French: "alphanumeric characters" translated to "lettres minuscules, des chiffres"

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5115]
The English string

> Tag \"%s\" must be alphanumeric characters or symbols: -_.

...which is used in ckan/logic/validators.py:428 to validate tags, has an inaccurate translation in French:

> Le mot-clé \"%s\" ne peut contenir que des lettres minuscules, des chiffres ou les symboles : -_.

An alphanumeric character can be a digit or any letter, whether lowercase or not, so the French description is overly restrictive. An accurate translation could therefore be:
"Le mot-clé \"%s\" ne peut contenir que des lettres, des chiffres ou les symboles : -_."

This affects CKAN 2.4.1, and persists in the master branch as of a3a6b582fcd758727c98b628d13d198b4317787c.

Note that it is unclear which (special) symbols these strings refer to.

**Comment by amercader** [comment]
@Chealer that sounds good. Translations are managed on Transifex (https://www.transifex.com/okfn/ckan/). If you register for an account you can update the strings for the 2.6, 2.7 and 2.8 resources, and next time we do a patch release we will pull the latest translations with the fixes:

![Screenshot_2019-12-10 CKAN Languages](https://user-images.githubusercontent.com/200230/70528781-49a2e500-1b4f-11ea-919d-5def961b8bd4.png)

**Comment by Chealer** [comment]
Thank you @amercader but I'm afraid an efficient solution for this string would start with a clarification of the English version.

**Comment by amercader** [comment]
@Chealer sorry, I don't follow. What needs clarification on the English string?

**Comment by Chealer** [comment]
@amercader the "symbols" (special characters) which are allowed (if I understand correctly, dashes and underscores).

**Comment by amercader** [comment]
> Tag "%s" must be alphanumeric characters or symbols: -_.

The only [allowed](https://github.com/ckan/ckan/blob/master/ckan/logic/validators.py#L432) punctuation symbols are hyphen (`-`), underscore (`_`) and full stop (`.`). That's what it says on the message. Perhaps is the colon what is confusing?

If you can think of a better message please do send a PR and then we can create a new French translation.

**Comment by Chealer** [comment]
> > Tag "%s" must be alphanumeric characters or symbols: -_.
> 
> The only [allowed](https://github.com/ckan/ckan/blob/master/ckan/logic/validators.py#L432) punctuation symbols are hyphen (`-`), underscore (`_`) and full stop (`.`).

Is that something you know for sure, or is that merely your understanding of the message?

> That's what it says on the message. Perhaps is the colon what is confusing?

Well, besides the potential for confusion, there is the issue of not being syntactically valid (English does not allow to just throw characters in a sentence). But yes, this sentence is not only invalid but unclear because:

1. Most importantly, the period's role is ambiguous. Considering that some characters are unquoted, one wonders if it's an unquoted literal period of just the sentence's mandatory ending full stop.
1. Considering that the sentence is not properly written, one cannot exclude that the color and space have a literal value.
 
> If you can think of a better message please do send a PR and then we can create a new French translation.

I'm not sure what the message should be, but there are certainly better ways to write it. Anything with the characters quoted and/or named would be better.

**Comment by Gauravp-NEC** [comment]
@amercader , I have raise the PR https://github.com/ckan/ckan/pull/5760 to fix this issue.

**Comment by Chealer** [comment]
I'm sorry if this is repetition, but the right way to fix this would be to start with the English string. The newly proposed change is also unclear, and I would even say also incorrect.

**Comment by Gauravp-NEC** [comment]
@amercader @Chealer , I have purposed a better message and its French translation in the PR https://github.com/ckan/ckan/pull/5760

**Comment by Chealer** [comment]
@Gauravp-NEC the proposal contradicts @amercader 's 2019-12-16 claim about spaces. Are you sure spaces are supported? In general, management systems do not support spaces in tag names.
