### ISSUE TITLE
FileStore with Cloud Storage

### ISSUE THREAD

**Issue by datphamict** [ckan/ckan#5125]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

Dear all,

I have just readed document in FileStore and File Uploads features.

Document as below:
_"Changed in version 2.2: Previous versions of CKAN used to allow uploads to remote cloud hosting but we have simplified this to only allow local file uploads (see Migration from 2.1 to 2.2 for details on how to migrate). This is to give CKAN more control over the files and make access control possible."_

i have some questions:

Why do we remove this feature? And how can i upload file to remote cloud hosting ?

Thanks.

**Comment by smotornyuk** [comment]
Now cloud uploads are handled by https://github.com/TkTech/ckanext-cloudstorage . It supports quite a long list of providers, so there is no need in duplicated logic inside CKAN core
