### ISSUE TITLE
2.8.3 works but 2.8.2 returns "Bad request - JSON Error: Invalid request. Please use POST method for your request"

### ISSUE THREAD

**Issue by jspinella** [ckan/ckan#5149]
### CKAN Version if known (or site URL)
2.8.2 (from source)

### Please describe the expected behaviour
Organization/Package/etc. is created.

### Please describe the actual behaviour
CKAN API returns error message: "Bad request - JSON Error: Invalid request. Please use POST method for your request"

### What steps can be taken to reproduce the issue? 
Attempt to POST to `...api/3/action/organization_create`  or `package_create` with required param(s).

I haven't really seen this issue out in the wild, but I do **not** have this issue on a CKAN 2.8.3 install deployed from package. Tested both CKAN instances with the same Postman requests (using POST of course) and a program I wrote that hits the CKAN API. Both can successfully POST in 2.8.3 but not 2.8.2.

Is this a known issue that is fixed in 2.8.3? Changelog docs do not appear to be up to date.

**Comment by amercader** [comment]
I can't recall a fix along those lines. Can you share the exact commands, URLs, and objects that you are using? Can you reproduce it using another tool like curl or httpie?

**Comment by smotornyuk** [comment]
I think that you're somehow making GET request. http://demo.ckan.org is running on 2.8.2 
```
$ curl https://demo.ckan.org/api/action/package_create

"Bad request - JSON Error: Invalid request. Please use POST method for your request"

$ curl -X POST https://demo.ckan.org/api/action/package_create

{"help": "https://demo.ckan.org/api/3/action/help_show?name=package_create", "success": false, "error": {"message": "Access denied: User  not authorized to create packages", "__type": "Authorization Error"}}
```

**Comment by jspinella** [comment]
It does seem like CKAN API is receiving a GET, but it's curious that the issue doesn't happen on 2.8.3.

When I do a CURL (Postman provided the CURL code below), it does not give me this error. Instead it says I haven't provided a name for the package in this case:

`curl --location --request POST 'http://data.smartnorthfloridadata.com/api/3/action/package_create' \
--header 'Content-Type: application/json' \
--header 'Authorization: {API Key here}' \
--data-raw '{
	"name":"bfedreservetreasuryrate",
	"url":"https://fred.stlouisfed.org/series/DGS10/",
	"as":"table",
    "title": "BConsumer Price Index: All Items in U.S. City Average, All Urban Consumers",
	"author": "St. Louis FED",
	"notes": "hey whats up",
	"groups":[{"name":"agriculture"}, {"name":"florida"}]
}'`

`"Validation Error", "name" ["Missing value"]`

**Comment by jspinella** [comment]
> curl -X POST https://demo.ckan.org/api/action/package_create

@smotornyuk If I run this against http://data.smartnorthfloridadata.com I get HTML back with text "301 Moved Permanently". 

Something seems up with this CKAN install. Again, it was a from-source install. I'm not sure what else was done or which guide floating around the Internet was followed... Theoretically I can upgrade pretty easily, and that might fix the issue.

**Comment by smotornyuk** [comment]
That's because http://data.smartnorthfloridadata.com switches you to HTTPS. Either add `-L` flag to curl, or use correct schema - `curl -X POST httpS://data.smartnorthfloridadata.com/api/action/package_create `

**Comment by jspinella** [comment]
AH. Didn't realize the website is only using HTTPS. 

THANK YOU.
