### ISSUE TITLE
In dashboard - My Organizations only public datasets are counted and displayed

### ISSUE THREAD

**Issue by mdlux** [ckan/ckan#5156]
### CKAN Version
2.8.3

### Please describe the expected behaviour
The dataset counter under each organization box in My Organizations TAB of the dashboard should behave exactly as in case of organizations displayed in the main organization TAB, counting not only public datasets but also private ones (which user can access). 

### Please describe the actual behaviour
Only public datasets are counted and displayed in My Organizations TAB of the dashboard.

### What steps can be taken to reproduce the issue? 
Create a dataset in an organization, and keep it private. see the difference between dataset count in main organization TAB and My Organizations in the dashboard

Possible source of error:
query in "ckan.lib.dictization.model_dictize.get_group_dataset_counts()" defaults to '+capacity:public'

**Comment by mdlux** [comment]
Relates to #3579

**Comment by mdlux** [comment]
Could #3580 be reopened? I think it solves the issue...

**Comment by amercader** [comment]
@mdlux #3580 is now merged and will be backported to the next patch release

**Comment by mdlux** [comment]
Thank you!
