### ISSUE TITLE
Run latest master with Python 3 on master.ckan.org

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5168]
Now that master is starting to get fully Ptyhon 3 ready we want as many people as possible to test it.

https://master.ckan.org/ is running an old version and it would great to update it to the current one and update the image used to run on Python 3

Priorities:

* Update site to run on Python 3 (the current Circle CI config will help but it should be basically the same steps but using the correct `requirements.txt` file and `ckan` commands instead of paster
* Update to current master

Nice to have:

* Automate the deployment eg nightly
* Show the commit the site is running on (I wrote [this](https://github.com/ckan/ckanext-repo) ages ago, it probably still works)

**Comment by amercader** [comment]
@JGulic given that master.ckan.org is currently hosted by Datopian can I leave this with you to coordinate on your end? Thanks

**Comment by amercader** [comment]
ping @JGulic , just checking if this in your radar

**Comment by wardi** [comment]
@amercader we should show the python version alongside the ckan commit id :-)

**Comment by marikanti** [comment]
What would be the release date for 2.9 with Python3?

**Comment by JGulic** [comment]
@amercader sorry for missing this. I am starting to work on it now, and I will post updates here

**Comment by amercader** [comment]
@JGulic no worries, thanks a lot!

**Comment by amercader** [comment]
@JGulic no worries, thanks a lot!

**Comment by pdelboca** [comment]
@amercader FYI latest CKAN 2.9 is now running on [master.ckan.org](https://master.ckan.org/).

**Comment by marikanti** [comment]
> @amercader FYI latest CKAN 2.9 is now running on [master.ckan.org](https://master.ckan.org/).

When is the release date for 2.9?

**Comment by amercader** [comment]
@pdelboca great news! Is that running py3 or still on py2?

@marikanti no date yet but you can track what is missing on this milestone: https://github.com/ckan/ckan/milestone/13

**Comment by pdelboca** [comment]
@amercader it's running on Python 3 :)

**Comment by amercader** [comment]
Fantastic, thanks
