### ISSUE TITLE
Ckan fails in docker compose with error 'ImportError: No module named html'

### ISSUE THREAD

**Issue by mmartain** [ckan/ckan#5184]
### CKAN Version if known (or site URL)
master (2.9.0)

### Please describe the expected behaviour
Building CKAN with instructions from:
https://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html

### Please describe the actual behaviour
ckan container crashes upon start

```
ckan          | db:5432 - no response
ckan          | db:5432 - accepting connections
ckan          | Distribution already installed:
ckan          |   ckan 2.9.0a0 from /usr/lib/ckan/venv/src/ckan
ckan          | Creating /etc/ckan/production.ini
ckan          | Now you should edit the config files
ckan          |   /etc/ckan/production.ini
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 8, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan          |     invoke(command, command_name, options, args[1:])
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan          |     exit_code = runner.run(args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan          |     result = self.command()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 338, in command
ckan          |     self._load_config(cmd != 'upgrade')
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 315, in _load_config
ckan          |     self.site_user = load_config(self.options.config, load_site_user)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 228, in load_config
ckan          |     app = make_app(conf.global_conf, **conf.local_conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app
ckan          |     flask_app = make_flask_stack(conf, **app_conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 211, in make_flask_stack
ckan          |     _register_core_blueprints(app)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/flask_app.py", line 477, in _register_core_blueprints
ckan          |     module = loader.find_module(name).load_module(name)
ckan          |   File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
ckan          |     mod = imp.load_module(fullname, self.file, self.filename, self.etc)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/views/api.py", line 5, in <module>
ckan          |     import html
ckan          | ImportError: No module named html
```

### What steps can be taken to reproduce the issue? 
follow instructions on https://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html

My install was on Ubuntu 16.04 LTS

**Comment by mmartain** [comment]
Actually added html as a dependency in requirements-py2.txt does not seem to be the solution as i have the module installed but still get the same error

**Comment by smotornyuk** [comment]
Are you sure, that you've this module installed inside docker container under CKAN's virtual environment? Because, in that case, it's Python's but - it's unable to import installed module. As it's unlikely the case, you're either modifying `sys.path` or using custom python interpreter.

**Comment by mmartain** [comment]
Well, i see the html module being installed and no errors as the ckan is being build via compose. I would assume that this means its installed under the virtual environment. I even tried with adding the html module to both py2 and the normal requirements txt file.

**Comment by mmartain** [comment]
Well, the PR does not fix it, so it should not be closed just yet?

**Comment by usingsky** [comment]
@mmartain 
There seems to be a problem with the py3 migration from the latest version. 
I think If you want to use docker based on py2, you can revert the following patch (ckan/views/api.py).
https://github.com/ckan/ckan/commit/b719e631984a61907cd737571513b009607c8343#diff-ae791a48f22c79a269e100b5fe3de5ce

html->cgi

I hope it helps

**Comment by mmartain** [comment]
@usingsky Thanks! I will give this a go and report back!

**Comment by smotornyuk** [comment]
@usingsky , i don't think that reverting is acceptable, because you can just use CKAN 2.8 in that case. Option with external `html` 

@mmartain , just give it a try after disabling all the running containers(make sure, you are not using old setup, have PostgreSQL service running on host machine and don't skip/change any of the steps, unless you are using windows - in that case, you should change **only** `cd /tmp` and `sed ...`, which just sets correct DB password in my case). Here the script that works perfectly on my local machine:
```
cd /tmp 
git clone https://github.com/ckan/ckan.git dock
cd dock/contrib/docker  

sed 's/POSTGRES_PASSWORD=ckan/POSTGRES_PASSWORD=root/' .env.template > .env
docker rmi -f docker_ckan docker_db    
docker rmi $(docker images -f dangling=true -q) 
docker-compose up --build
```
Now just open http://0.0.0.0:5000/api/action/status_show in your browser

**Comment by usingsky** [comment]
@smotornyuk 
I wrote a comment on #5186

**Comment by smotornyuk** [comment]
Thanks, i see the point - i'll update fix to one, that should work for everyone
