### ISSUE TITLE
Last modified dates not updated for resources

### ISSUE THREAD

**Issue by starsinmypockets** [ckan/ckan#5190]
### Please describe the expected behaviour

Updating metadata fields (title, description, etc) for resources should update the _metadata last updated_ attribute of the resource.

### Please describe the actual behaviour

_Metadata last updated_ value remains the same after edit

### What steps can be taken to reproduce the issue? 

* Update `package/resource_read.html` to show full localized datetime for the "Metadata last updated" field
```
              <tr>                
                <th scope="row">{{ _('Data last updated') }}</th>
                <td>{{ h.render_datetime(res.last_modified, "%c", False) or h.render_datetime(res.created, "%c", False) or _('unknown') }}</td>
              </tr>
              <tr>                            
                <th scope="row">{{ _('Metadata last updated') }}</th>
                <td>{{ h.render_datetime(res.revision_timestamp, "%c", False) or h.render_datetime(res.created, "%c", False) or _('unknown') }}</td>                     
              </tr>    
```
* Create resource
* Update metadata field
* Check to see if `last_modified` field is updated to current time

On create:
> ![Screenshot from 2020-02-08 09-35-59](https://user-images.githubusercontent.com/949175/74087039-bf93d180-4a56-11ea-8ee4-b718e9cbe1a5.png)

On update:
> ![Screenshot from 2020-02-08 09-36-27](https://user-images.githubusercontent.com/949175/74087032-b276e280-4a56-11ea-8c46-1bcadb6f72b5.png)

### Proposed solutions

I've explored two potential solutions:

#### 1. Controller-level

In package controller https://github.com/ckan/ckan/blob/master/ckan/controllers/package.py#L586
```python
            try:
                if resource_id:
                    data['id'] = resource_id
                    if resource_updated(context, data): # FIXME implement
                      data['last_modified'] = datetime.datetime.now()
                   get_action('resource_update')(context, data)
                else:
                    get_action('resource_create')(context, data)
```

#### 2. Dictization-level

Another approach might be when preparing to write the new data dictionary to the database, check if there are changes, and add the field here.

For example (in `resource_dict_save` https://github.com/ckan/ckan/blob/master/ckan/lib/dictization/model_save.py#L17):

```python
    for key, value in res_dict.iteritems():
        if isinstance(value, list):
            continue
        if key in ('extras', 'revision_timestamp', 'tracking_summary'):
            continue
        if key in fields:
            if isinstance(getattr(obj, key), datetime.datetime):
                if isinstance(value, string_types):
                    db_value = getattr(obj, key).isoformat()
                else:
                    db_value = getattr(obj, key)
                if  db_value == value:
                    continue
                if key == 'last_modified' and not new:
                    obj.url_changed = True
            if key == 'url' and not new and obj.url != value:
                obj.url_changed = True

            # keep track of fields we are updating
            if getattr(obj, key) != value:
                updated_fields_count += 1 
            setattr(obj, key, value)
        else:
            # resources save extras directly onto the object, instead
            # of in a separate extras field like packages and groups
            new_extras[key] = value
    
    if updated_fields_count > 0:
        obj.last_modified = datetime.datetime.now()
    obj.state = u'active'
    obj.extras = new_extras

    session.add(obj)
    return obj
```

**Comment by starsinmypockets** [comment]
@amercader Here is the issue we discussed

**Comment by wardi** [comment]
`last_modified` on resources refers to the linked/uploaded resource itself. `metadata_modified` on the package refers to the last time the package or resource metadata was modified

**Comment by starsinmypockets** [comment]
@wardi I updated the ticket to use the correct nomenclature

**Comment by starsinmypockets** [comment]
Added some better steps to reproduce the issue as well.

I would propose that rather than relying on the revision timestamp, that we include a metadata_updated field, and update it appropriately, either via the dictization function (compare on write) or via the controller, where we add the value explicitly on save (again, if metadata compare is not ==)

**Comment by starsinmypockets** [comment]
I'm happy to put together a PR -- I'd like to validate the approach first.

**Comment by Zharktas** [comment]
https://github.com/ckan/ckan/issues/3028 there is also discussion about "data last modified" and "metadata last updated" and relating issue https://github.com/ckan/ckan/issues/3907 that the revision_timestamp is never updated.

**Comment by pdelboca** [comment]
I have been looking at this issue since I need to fix it for my current project. Even when we track metadata last update for package there is not such thing for resources, they don't have neither `metadata_modified` nor `revision_timestamp` fields.

Here is what `table_dictize()` returns for a package:
```
{'author': '',
 'author_email': '',
 'creator_user_id': '5c863e35-0560-4622-ad04-02d4acbadb4f',
 'id': '83761632-068f-4e12-9e0d-05aeaf6443ad',
 'license_id': 'cc-by',
 'maintainer': '',
 'maintainer_email': '',
 'metadata_created': '2020-02-21T17:12:20.034554',
 'metadata_modified': '2020-02-21T17:38:39.627429',
 'name': 'testing',
 'notes': 'Test',
 'owner_org': 'e322cb2c-04a1-4ff7-8d56-774b8b848059',
 'private': True,
 'state': 'active',
 'title': 'Testing',
 'type': 'dataset',
 'url': '',
 'version': ''}
```

And here is what it returns for a resource:
```
{'cache_last_updated': None,
 'cache_url': None,
 'created': '2020-02-21T17:12:25.004894',
 'description': 'Test 6',
 'extras': {'datastore_active': False},
 'format': 'CSV',
 'hash': '',
 'id': '973af36b-4fae-442f-baf6-12d3cc944480',
 'last_modified': '2020-02-21T14:18:23.113350',
 'mimetype': 'text/csv',
 'mimetype_inner': None,
 'name': 'mini-csv.csv',
 'package_id': '83761632-068f-4e12-9e0d-05aeaf6443ad',
 'position': 0,
 'resource_type': None,
 'size': 40,
 'state': 'active',
 'url': 'mini-csv.csv',
 'url_type': 'upload'}
```

So in order to be able to track this we should create a new field in the `resource` model to keep track of this and then apply a logic like @starsinmypockets suggested. For what I have been reviewing this may require some migration on the database so the field can be created properly? Or what approach should we take to tackle this issue?
