### ISSUE TITLE
Markdown do not populate href attributes if link is not http

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#5206]
### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
`[name](protocol://resource)` should be rendered `<a href="protocol://resource">name</a>`.

### Please describe the actual behaviour
`href` is missing if the protocol is not recognized, like `file://`

### What steps can be taken to reproduce the issue? 
Create a dataset using `[name](file://resource)` as description.

**Comment by amercader** [comment]
Thanks @frafra, this sounds like a sensible default security-wise to be honest. You can always override the `render_markdown()` helper to change the options passed to the render library, or use a different library all together.

**Comment by frafra** [comment]
I do not agree actually, because it is totally legit to have a link to a non-http resource, such as ftp (or even webdav o torrent). It is up to the browser to decide which protocol should handle or not.
Thanks for your suggestion.
