### ISSUE TITLE
Docker-Compose: Python error:  ImportError: No module named configparser

### ISSUE THREAD

**Issue by yjaques** [ckan/ckan#5212]
### CKAN Version if known (or site URL)
2.8.2 (latest)

### Please describe the expected behaviour
ckan service starts

### Please describe the actual behaviour
ckan service exits with code 1:

```
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 8, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
ckan          |     command = commands[command_name].load()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
ckan          |     return self.resolve()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
ckan          |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 32, in <module>
ckan          |     from ckan.cli import load_config as _get_config
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/__init__.py", line 7, in <module>
ckan          |     from configparser import ConfigParser
ckan          | ImportError: No module named configparser
ckan exited with code 1
```

### What steps can be taken to reproduce the issue? 
Using instructionas at [https://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html](https://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html)
1. clone repo: `git clone https://github.com/ckan/ckan.git`
2. Modify .env file as instructed.
3. build and deploy as instructed
4. all services will launch (volumes get created, containers are running) except for ckan that bombs out. You can verify it's not running using `docker ps`, and view the log error by using  `docker-compose logs -f ckan`

**Comment by lgc0313** [comment]
I encountered the same problem today.

**Comment by pdelboca** [comment]
Thanks! You are using the latest version of `master` branch for the docker compose that may not be stable.

Did you execute the following step in the installation process for checking out a stable branch? After cloning the repository you can execute: `git checkout tags/ckan-2.8.3` to get the latest stable branch for your Docker Compose.

**Comment by lgc0313** [comment]
I change to use 2.8.2 tag to build docker image, and everything is ok.

**Comment by yjaques** [comment]
Yes that worked for me too. Sorry, although I had switched from master to 2.8.2, I had to actually prune my volumes to get it to rebuild off of 2.8.2. It wasn't enough to follow the rebuild instruction in .env template

**Comment by joshkant** [comment]
i have configparser error even on 2.8.0 2.8.2.. any suggestions?

**Comment by yjaques** [comment]
Did you follow all the instructions in the yaml for rebuilding when you have already pulled a non working version? And also be sure you prune your docker volumes as well.

**Comment by scampion** [comment]
Same issue for me.
I cleaned the docker stack, test with 2.8, 2.8.2 and 2.8.3

```
ckan          | Command 'db' not known (you may need to run setup.py egg_info)
ckan          | Known commands:
ckan          |   create       Create the file layout for a Python distribution
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 8, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan          |     invoke(command, command_name, options, args[1:])
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan          |     exit_code = runner.run(args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 806, in run
ckan          |     command.load().summary))
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
ckan          |     return self.resolve()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
ckan          |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckanext/datapusher/cli.py", line 7, in <module>
ckan          |     import ckan.lib.cli as cli
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 17, in <module>
ckan          |     from ckan.cli import load_config as _get_config
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/__init__.py", line 8, in <module>
ckan          |     from configparser import ConfigParser
ckan          | ImportError: No module named configparser
```

**Comment by yjaques** [comment]
@scampion as I noted before, just following the cleaning instructions is not enough. You also need to prune your volumes before rebuilding, making sure you have killed all the ckan volumes by using `docker prune` command, after which you should NOT see the following volumes when using `docker volume ls`:

local               docker_ckan_config
local               docker_ckan_home
local               docker_ckan_storage
local               docker_pg_data 

at that point you should be able to pull another version and build as before.
