### ISSUE TITLE
stats extension: Title/breadcrumb ("Statistics") not translatable

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5221]
The statistics extension defines in [templates/ckanext/stats/index.html](https://github.com/ckan/ckan/blob/master/ckanext/stats/templates/ckanext/stats/index.html) the following as breadcrumb:
`<li class="active">{{ 'Statistics' }}</li>`
The content of the list item is strange. It is not clear to me why a Jinja string is used. It looks like this is an incomplete attempt to make the content translatable, but unfortunately for this to work the underscore function needs to be called, as follows:
`<li class="active">{{ _('Statistics') }}</li>`

### CKAN Version if known (or site URL)
2.8.3

**Comment by amercader** [comment]
@Chealer sounds good, do you want to submit  a PR?

**Comment by Chealer** [comment]
Thanks @amercader but submit a _what_?

**Comment by Gauravp-NEC** [comment]
@amercader @Chealer ,I have raise the PR https://github.com/ckan/ckan/pull/5603 to close this issue. The incomplete attempt to make the content translatable is still present in ckan version 2.9 release.
