### ISSUE TITLE
Prepare new patch releases

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5251]
Scheduled March/April 2020

We are targeting 2.6.9, 2.7.7 and 2.8.4

**Note**: The steps below need to be replicated for 2.7.7 and 2.6.9 (using the relevant branches `dev-v2.7` and `dev-v2.6`. 

### Starting up

- [x] Update version on `dev-v2.8` branch to `2.8.4b`
- [x] Cherry-pick all issues marked as ["Backport Pending"](https://github.com/ckan/ckan/issues?q=label%3A%22Backport+pending%22) to `dev-v2.8`

### Next few days

- [x] Pull translations on `dev-v2.8` branch
  - [x] `tx pull --all --minimum-perc=5 --force`
  - [x] Commit `*.po` files
  - [x] Compile `*.mo` files (`python setup.py compile_catalog`)
  - [x] Commit `*.mo` files
- [x] Build frontend (`paster front-end-build`), if there any changes commit them (there probably won't be)
- [x]  Update changelog in `dev-v2.8`
- [x] Test fixes for cherry-picked issues locally and on beta.ckan.org
- [x] Test that Debian package builds fine

### When the release is frozen

- [x] Update version on `dev-v2.8.4b` branch to `2.8.4`
- [x] Create tag `ckan-2.8.4`
- [x] Build final deb package
- [x] Send email to CKAN announce / dev a week before the planned release day

### Release day

- [x] Upload to https://packaging.ckan.org/
  - [x] Rename package to override existing 2.8 one
  - [x] Update md5sum
- [x] Upload to pypi (`pyhton setup.py sdist upload`)
- [ ]  Announce
  - [x] ckan-announce and ckan-dev ([model](https://lists.okfn.org/pipermail/ckan-announce/2018-March/000035.html))
  - [ ] Twitter
  - [x] ckan.org blog post (can be the same as the email announcement, changing the formatting)

### After release 

- [x] Cherry pick two i18n commit above to master
- [x] Update changelog in master with the 2.8.4 one
- [x] Merge `dev-2.8` into `2.8`
- [ ] :beers:

**Comment by ThrawnCA** [comment]
Any chance of including the patches in https://github.com/ckan/ckan/compare/dev-v2.8...qld-gov-au:qgov-master ?

**Comment by amercader** [comment]
@ThrawnCA All patches backported to the patch releases should be already in master. Are the commits linked already submitted as Pull requests? If so are they labelled "Backport pending"?

**Comment by ThrawnCA** [comment]
Hmm... #5185 has been fixed in master as part of a larger change, though I don't think it was marked for backport.

#5027 was merged into master, and the issue says it should be marked for backport, but I don't think it was, because it doesn't seem to be on the 2.8 branch.

#5030 was merged into master and the pull request was marked for backport, but it isn't on the 2.8 branch.

**Comment by smotornyuk** [comment]
All marked PRs were cherry-picked into `dev-v2.*.*` branches. The only exception - #5167 - @wardi will you be able to check it during week or two? Nevertheless, it doesn't have any frontent\translation changes, so I've finished all other preparation steps.
Now I need someone to update beta.ckan.org and build debian packages(i never was able to do it :cry: )

**Comment by kowh-ai** [comment]
@smotornyuk - I'll revisit the work I did with building debian packages last year. I had problems with building on Ubuntu too. I resorted to using Mac OS X. I'll see what I can achieve by the end of this weekend :-)

**Comment by Zharktas** [comment]
https://github.com/ckan/ckan/pull/5255 wasn't marked for backporting but it probably should be.

**Comment by amercader** [comment]
@ThrawnCA can you help me out here and link to any *pull request* (not issue) that you think should be backported and it isn't yet. Many thanks!

**Comment by amercader** [comment]
Agreed plan:

* Week 30th March: finish backports
* Week 6th April: Announce release and iron out last issues
* 15th April: Release

**Comment by ThrawnCA** [comment]
@amercader The following are labelled for backport but don't seem to be in dev-v2.8:

https://github.com/ckan/ckan/pull/5033
https://github.com/ckan/ckan/pull/5139

https://github.com/ckan/ckan/pull/4636 is also labelled for backport, but there was a suggestion that it should be split up as it includes other work besides the direct bugfix. 01bbb53 and 0fbe25e implement that in our fork, if you want to cherry-pick them.

https://github.com/ckan/ckan/pull/4918 has a note on it requesting backport, but it hasn't been actioned at all.

**Comment by boykoc** [comment]
I second #4918 too if possible.

**Comment by ThrawnCA** [comment]
@boykoc Just so you know, if any patches in our fork don't make it into 2.8.4, we'll definitely merge them and cut a new release based on 2.8.4. Feel free to use `ckan-2.8.4-qgov.3` in the meantime.

**Comment by smotornyuk** [comment]
Update to @ThrawnCA  comment(make sure you are using latest **dev-2.8**  - not the same as **2.8** - I've pushed few commits there about a week ago):
#5033 already in dev-2.8 - [link](https://github.com/ckan/ckan/blob/dev-v2.8/ckan/lib/dictization/model_save.py#L49-L53)
#5139 already in dev-2.8 - [link](https://github.com/ckan/ckan/blob/dev-v2.8/ckan/model/tracking.py#L34-L35)
#4636 already in dev-2.8 - [link](https://github.com/ckan/ckan/blob/dev-v2.8/ckan/views/user.py#L551-L571). But I missed discussion about splitting, so we still need to cherry-pick two mentioned commits

#4918 - not backported, +1 for backporting it into all branches

CircleCI fix [already there](https://github.com/ckan/ckan/blob/dev-v2.8/.circleci/config.yml#L5)

**Comment by ThrawnCA** [comment]
Ah, I think I misread Github's comparison of the two branches; it was only showing the changes included in our branch's commits, not showing a full diff.

Doing a proper diff, it looks good as far as I can tell (can't read the updated translations myself), except for 4918 as you say.

**Comment by amercader** [comment]
#4918 is backported now

**Comment by amercader** [comment]
Patch releases went out on 2020-04-15
