### ISSUE TITLE
While uploading resource files sequentially, some of them get deleted randomly.

### ISSUE THREAD

**Issue by ArqamFarooqui110719** [ckan/ckan#5256]
I am  using CKAN v2.7.2.

While I upload resource files sequentially, files get disappeared randomly (I am uploading xlsx files and the size of each file varies from 10-20KB and there are total ~250 files).
I have created multiple datasets. While uploading files in 1st dataset (total ~225 files uploaded), some files gets disappeared randomly after uploading the next resource file. And in another dataset (uploading same files), some other resource files gets disappeared randomly. 
The files which are disappeared, initially appears on CKAN GUI, But when I upload the next resource file in same dataset, the previous resource file disappears from the GUI.  
There is no `creation log`  is present in `ckan_http.error.log`, `ckan_http.custom.log` and `datapusher.error.log` log files for the files that have been disappeared. 
But there is an` error log` is present corresponding to the resource file which disappeared from GUI. See the screenshot of `ckan_http.error.log` (I have highlighted the error):

![ckan_http error log](https://user-images.githubusercontent.com/55977298/75884373-b4ac4100-5e4a-11ea-8039-270838425c41.png)

Also, the deletion history is present in PostgreSQL database(in `state` column) for the same resource files that disappeared. See the screenshot `Psql DB screenshot` (I have highlighted the error): 

![pSQL DB screenshot](https://user-images.githubusercontent.com/55977298/75884394-bc6be580-5e4a-11ea-8d9b-82e7c06b45d7.png)

Here. "05-05_h30.xlsx" file was added, but it disappeared from GUI while uploading next resource file and there is no entry corresponding to its `uploading` in any other log files. But the state of this resource file in PostgreSQL database is "deleted". Although, there is no entry for its successful upload in database.

Can anyone confirm if there is any such issue in CKAN where resource files gets disappeared randomly while uploading multiple resource files in dataset. Also, why the logs are not created on uploading some of the resource files.

**Comment by amercader** [comment]
Currently `resource_create` and `resource_update` are not safe to use concurrently as they both call `package_update` under the hood. That might be causing the issues you see. Check https://github.com/ckan/ckan/issues/5225 for more context.


BTW, if you are creating datasets with 250 resources you might want to check https://github.com/okfn/ckanext-resourcesfilter

**Comment by ArqumFarooqui-NEC** [comment]
Hi @amercader,  
we are uploading files sequentially and the issue #5225 is related to parallel uploading. And we are uploading nearly 30 files per hours avg.
And also we are just uploading the files not updating the same.

> BTW, if you are creating datasets with 250 resources you might want to check https://github.com/okfn/ckanext-resourcesfilter

As I have mentioned in issue, I am creating multiple datasets so I'm also uploading 60-70 resource files in another dataset and facing the same problem i.e. `previously uploaded file gets disappeared sometime (randomly) when uploaded the new resource file.`

**Comment by wardi** [comment]
Opened a new ticket for this #6420
