### ISSUE TITLE
CKAN - Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)

### ISSUE THREAD

**Issue by scoutinhoGit** [ckan/ckan#5268]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

Hi,

I would like to  inactive dataproxy visualization on CKAN, cause i am having this message error on a local scan installation:

`Could not load view: DataProxy returned an error 
`

So i am following instructions to activate  dataset preview using DATASTORE funcionality 
(https://docs.ckan.org/en/latest/maintaining/datastore.html) without success.

What am i doing wrong? 

Regards,

Sergio

### CKAN Version if known (or site URL)
Lastest version - 2.9. This is a SOURCE INSTALL.
Python 3.x version

### Please describe the expected behaviour
Trying to see a CSV file by DATASET browser

### Please describe the actual behaviour
After some seconds trying to show CSV itens, appeared the message error:

> Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)

### What steps can be taken to reproduce the issue? 
1) On MENU, select DATASETS
2) Select the DATASET with CSV file
3) Select button EXPLORE on dataset window and PREVIEW in menu options of EXPLORE
4) After some seconds, appeared the message:
   This resource view is not available at the moment. Click here for more information.
5) Following message error:
`   Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)`
 
### Additional Details:

A) Can download and upload CVS files on CKAN

B) My ckan.ini file has this plug-in configuration:
`ckan.plugins = datastore stats text_view image_view recline_view recline_grid_view recline_graph_view recline_map_view`

C) Tried to set permissions on POSTEGREE database with this command:

_paster3 --plugin=ckan datastore set-permissions -c /etc/ckan/default/ckan.ini | sudo -u postgres psql --set ON_ERROR_STOP=1_
```
     There is a message error here:
(default) ckan@ubuntu:/usr/lib/ckan/default$ paster3 --plugin=ckan datastore set-permissions -c /etc/ckan/default/ckan.ini | sudo -u postgres psql --set ON_ERROR_STOP=1
Traceback (most recent call last):
  File "/usr/bin/paster3", line 11, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/python3/dist-packages/paste/script/command.py", line 91, in run
    commands = get_commands()
  File "/usr/lib/python3/dist-packages/paste/script/command.py", line 133, in get_commands
    plugins = pluginlib.resolve_plugins(plugins)
  File "/usr/lib/python3/dist-packages/paste/script/pluginlib.py", line 83, in resolve_plugins
    pkg_resources.require(plugin)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: <exception str() failed>
```

**Comment by amercader** [comment]
@scoutinhoGit please see comment on #5269 , thanks
