### ISSUE TITLE
Error: "**ModuleNotFoundError: No module named 'pyutilib'"

### ISSUE THREAD

**Issue by scoutinhoGit** [ckan/ckan#5269]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

Hi ,

I'm trying to implement DATASTORE in CKAN to be able to view TXT or XLS files. I'm running a script to assign permissions on POSTGREE,

`paster3 --plugin=ckan datastore set-permissions -c /etc/ckan/default/ckan.ini
`

but every time i run it i saw this error message:

`ModuleNotFoundError: No module named 'pyutilib'`

I am new to the study of CKAN and I would like to know if anyone could guide me on how to solve this problem, because the library that presents this  error is already installed in the environment.

Thank you very much for any help you can provide to me.

Regards,

Sergio

### CKAN Version if known (or site URL)
CKAN latest version (source installation)
Python 3.x
Ubuntu 18.0.4 LTS

### Please describe the expected behaviour
Apply  datastore permissions on CKAN running command:

`(default) ckan@ubuntu:/usr/lib/ckan/default/src/ckan$ paster3 --plugin=ckan datastore set-permissions -c /etc/ckan/default/ckan.ini
`

### Please describe the actual behaviour
```
There is an error when i run this command:
(default) ckan@ubuntu:/usr/lib/ckan/default/src/ckan$ paster3 --plugin=ckan datastore set-permissions -c /etc/ckan/default/ckan.ini
Traceback (most recent call last):
  File "/usr/bin/paster3", line 11, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/python3/dist-packages/paste/script/command.py", line 101, in run
    command = commands[command_name].load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ckan/ckan/lib/default/src/ckan/ckanext/datastore/commands.py", line 5, in <module>
    from ckan.lib.cli import (
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/lib/cli.py", line 34, in <module>
    from ckan.config.middleware import make_app
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/config/middleware/__init__.py", line 10, in <module>
    from ckan.lib.i18n import get_locales_from_config
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/lib/i18n.py", line 55, in <module>
    from ckan.plugins import PluginImplementations
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/plugins/__init__.py", line 3, in <module>
    from ckan.plugins.core import *
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/plugins/core.py", line 10, in <module>
    from pyutilib.component.core import PluginGlobals, implements
**ModuleNotFoundError: No module named 'pyutilib'**

```

### What steps can be taken to reproduce the issue? 
Activate python virtual env for CKAN
Apply command described before.

### Python3 libraries installed:
```
(default) ckan@ubuntu:/usr/lib/ckan/default/src/ckan$ pip3 freeze
alabaster==0.7.12
alembic==1.0.0
arrow==0.15.5
atomicwrites==1.3.0
attrs==19.3.0
Babel==2.3.4
Beaker==1.11.0
beautifulsoup4==4.5.1
binaryornot==0.4.4
bleach==3.0.2
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
-e git+https://github.com/ckan/ckan.git@d6906b038305a07eae94f8d500f1f0b90c854908#egg=ckan
click==6.7
cookiecutter==1.6.0
coverage==5.0.3
coveralls==1.11.1
decorator==4.4.1
docopt==0.6.2
docutils==0.12
dominate==2.4.0
factory-boy==2.1.1
fanstatic==1.1
feedgen==0.9.0
first==2.0.2
Flask==1.1.1
Flask-Babel==0.11.2
Flask-DebugToolbar==0.10.1
flask-multistatic==1.0
funcsigs==1.0.2
future==0.18.2
idna==2.8
imagesize==1.2.0
importlib-metadata==1.5.0
itsdangerous==1.1.0
Jinja2==2.10.1
jinja2-time==0.2.0
lxml==4.4.2
Mako==1.1.0
Markdown==2.6.7
MarkupSafe==1.1.1
mock==2.0.0
more-itertools==8.2.0
nose==1.3.7
packaging==20.1
passlib==1.6.5
PasteDeploy==2.0.1
pathtools==0.1.2
pbr==5.4.4
pip-tools==2.0.2
pkg-resources==0.0.0
pluggy==0.13.1
polib==1.0.7
poyo==0.5.0
psycopg2==2.8.2
py==1.8.1
pycodestyle==2.5.0
pyfakefs==3.2
Pygments==2.5.2
pyparsing==2.4.6
pysolr==3.6.0
pytest==4.6.5
pytest-cov==2.7.1
pytest-rerunfailures==8.0
pytest-split-tests==1.0.9
python-dateutil==2.8.1
python-editor==1.0.4
python-magic==0.4.15
pytz==2016.7
PyUtilib==5.7.1
PyYAML==5.2
redis==3.3.11
repoze.lru==0.7
repoze.who==2.3
requests==2.22.0
responses==0.10.6
Routes==1.13
rq==1.0
shutilwhich==1.1.0
simplejson==3.10.0
six==1.13.0
snowballstemmer==2.0.0
Sphinx==1.8.5
sphinx-rtd-theme==0.3.1
sphinxcontrib-websupport==1.2.0
SQLAlchemy==1.3.5
sqlalchemy-migrate==0.12.0
sqlparse==0.2.2
Tempita==0.5.2
tzlocal==1.3
unicodecsv==0.14.1
urllib3==1.25.7
watchdog==0.10.2
wcwidth==0.1.8
webassets==0.12.1
webencodings==0.5.1
WebOb==1.8.5
Werkzeug==0.15.5
whichcraft==0.6.1
zipp==3.0.0
zope.interface==4.3.2

```

**Comment by amercader** [comment]
@scoutinhoGit There is something wrong with your installation as you should not be using `paster` in the latest (master) version but the `ckan` command.
If you really want to use the latest unreleased code use the `latest` version of the docs:
https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html

If you want to use the latest stable one use, the `2.8` one:

https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html

If you find any problems there please consider using the [ckan-dev mailing list](https://groups.google.com/a/ckan.org/forum/#!forum/ckan-dev) or  the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Thanks!
