### ISSUE TITLE
Problem with relationships packages

### ISSUE THREAD

**Issue by emiliomoran** [ckan/ckan#5274]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
Version 2.7.3

I created a relationship between two datasets, and when call the package_relationships_list, return the expect value in results, but when I update a package from relationship, the relationship lose.

**Comment by amercader** [comment]
@emiliomoran the relationship feature is currently unmaintained. Check the discussion on #5273 for potential ways forward. Thanks.
