### ISSUE TITLE
DataStore: "Further information in the main CKAN Data API and DataStore documentation" poorly translatable

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5276]
### Please describe the expected behaviour
The first paragraph in the dialog brought up by clicking the green "Data API" button from a resource which uses the DataStore (such as [this one](https://demo.ckan.org/fr/dataset/test-this-now/resource/66029d0b-2a3c-4365-bed4-cbe9a6a6685c)) ends with the following sentence:

> Further information in the main CKAN Data API and DataStore documentation.

This sentence should be found in the ckan.po translation file.

### Please describe the actual behaviour
Rather than just that sentence, ckan.po contains:
```
#: ckanext/datastore/templates/ajax_snippets/api_info.html:26
msgid ""
" Further information in the <a             "
"href=\"http://docs.ckan.org/en/latest/maintaining/datastore.html\" "
"target=\"_blank\">main CKAN Data API and DataStore documentation</a>.</p> "
```
That is, there are superfluous spaces before and after the sentence, and there are superfluous spaces and newlines inside the opening A tag.

### What steps can be taken to reproduce the issue? 
1. Enable the DataStore
1. Add a tabular resource, such as a CSV file, in the DataStore
1. Access the resource
1. Press the button to show the Data API modal

---

The sentence starts at [line 26 of api_info.html](https://github.com/ckan/ckan/blob/master/ckanext/datastore/templates/ajax_snippets/api_info.html#L26). This sentence was previously translated to French, but it was lost (except when using the Bootstrap 2 template) after the file was reindented in [revision 369db2d0e5a3205f6fc1c97ead666ee1ae1740ef](https://github.com/ckan/ckan/commit/369db2d0e5a3205f6fc1c97ead666ee1ae1740ef) (the sentence is duplicated in the French ckan.po starting from revision 97544fa417baf0dbdca653c58b0767518ea79e9c).

To ease translation and ensure that translations are not frequently lost, the template could use _trans_'s _trimmed_ to that superfluous whitespace does not pollute translation templates and cause unnecessary duplication.

### While we're at it
1. This may be a good occasion to change the problematic "sentence" into an actual sentence (one with a verb).
1. It also looks like what used to be called "the Data API" is now called "the DataStore API".
1. I suppose it would be best to link to the version of the documentation for the linking CKAN instance rather than to "latest" all the time. For example, for 2.4.1, link to https://docs.ckan.org/en/ckan-2.4.9/maintaining/datastore.html. So replace "latest" with a variable which keeps the string constant.

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I am interested to work on this issue. Please confirm that "the Data API" is now called "the DataStore API".

**Comment by kowh-ai** [comment]
That would be great if you could work on this - thank you...and yes Datastore: https://docs.ckan.org/en/latest/maintaining/datastore.html

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Please confirm that the green "Data API" button will also get rename to "DataStore API"

![image](https://user-images.githubusercontent.com/66116382/102324849-65ce3300-3fa8-11eb-9f92-19b2a5de91ae.png)

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have raise the PR https://github.com/ckan/ckan/pull/5803 to close this issue.

**Comment by amercader** [comment]
@Gauravp-NEC Sorry I forgot to update this issue. After discussion with the team we felt that it was better to implement the other way around, ie update the references in the docs to "Data API" so they match the frontend: https://docs.ckan.org/en/latest/maintaining/datastore.html

Does this makes sense?

**Comment by Gauravp-NEC** [comment]
@amercader , @kowh-ai  have confirmed that "the Data API" is now called "the DataStore API" in comment https://github.com/ckan/ckan/issues/5276#issuecomment-745261173. However if you want to update the references in the docs to "Data API" so they match the frontend I will do it.  Please confirm.

**Comment by Gauravp-NEC** [comment]
@amercader , Based on your comment https://github.com/ckan/ckan/issues/5276#issuecomment-760952133. I have raise the PR https://github.com/ckan/ckan/pull/5850 to match the frontend. Thankyou :)

**Comment by Chealer** [comment]
Thanks @Gauravp-NEC 
Regarding the bogus whitespace, I do not know how, but it was removed (it's not in current master).
