### ISSUE TITLE
ckan.max_resource_size configuration option is not validated (uploads crash when wrong)

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5277]
### Please describe the expected behaviour
When [the ckan.max_resource_size configuration option](https://docs.ckan.org/en/ckan-2.7.3/maintaining/configuration.html#ckan-max-resource-size) has an invalid value, the effective value should fallback to the default value and a warning should be raised.

### Please describe the actual behaviour
Resource uploads fail with an HTTP 500 status code:

> ValueError: invalid literal for int() with base 10: "[...]"

### What steps can be taken to reproduce the issue? 
1. Set ckan.max_resource_size to a non-integer value (such as "500 10")
1. Attempt to create a resource in a dataset

**Comment by wardi** [comment]
-1 to suggested change. Silently ignoring invalid configuration values is a bad idea.

**Comment by Zharktas** [comment]
Most of the configuration could be validated at the start though, crashing immediately would make invalid configurations apparent earlier.

**Comment by Chealer** [comment]
> -1 to suggested change. Silently ignoring invalid configuration values is a bad idea.

Reporting a warning is part of the expected behavior I described.

**Comment by wardi** [comment]
We discussed in today's dev meetings the suggested approach is to validate this field on start-up from the enabled IUploader plugin or in core if no plugin is enabled.

**Comment by Chealer** [comment]
Just to clarify my stance:
I wrote an expected behavior because the ticket template asked for one. I do not have a strong opinion on the best behavior and would appreciate any change which does not result in a failure which looks cryptic (to the uninitiated).

**Comment by wardi** [comment]
validation is now applied to (almost) all config options
