### ISSUE TITLE
tag_create Documentation needs update

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan#5280]
### CKAN Version if known (or site URL)
2.8.3

### The Issue
The tag_create API documentation has 2 issues:
1. For the tag name space is an allowed character but is not currently listed

2. The example of using the vocabulary name ('Genre') is incorrect the actual id is what is required. Issue #2362 sought a fix the software to match the documentation but was not completed. Unless it is doing to get fixed the documentation should be updated.

**Comment by Gauravp-NEC** [comment]
@pdekraker-epa @Zharktas , I am working on this issue. In tag name "space" is an allowed character but it is not listed in the document. I think vocabulary_id (string) – the id of the vocabulary that the new tag should be added to, e.g. the id of vocabulary 'Genre' is correct as it clearly states that in the end " e.g. the id of vocabulary 'Genre' ", Where  'Genre' is just an example. It can be id of any other vocabulary as well which has been created.

**Comment by Gauravp-NEC** [comment]
@wardi @Zharktas  I have raise PR https://github.com/ckan/ckan/pull/5721 to close this issue.
