### ISSUE TITLE
Is it possible to install CKAN 2.8  using Python 3.x ?

### ISSUE THREAD

**Issue by scoutinhoGit** [ckan/ckan#5283]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

Hi,

We would like to know if it´s possible to install CKAN 2.8 (stable version)  **using Python 3.x.**

We are reading instructions of install from source:

`https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html
`

But we have checked  that these  instructions install python 2.x, This version is obsolet now and we do not think it worth to develop customizations using this old language version.  

If it´s possible to install CKAN 2.8 using Python 3.x, which changes did we need to do following instructions  of 2.8?

Or did we need to install _**lastest version**_ if we would like to work with **Python 3.x**?

Thanks for the help !

Sergio

**Comment by pdekraker-epa** [comment]
CKAN 2.8 is Python 2.x only. 
CKAN 2.9 is planned to be compatible with both Python 2 and Python 3.
CKAN 3.0 released afterward would be Python 3 only.

You can track the process of the conversion which is mostly complete [here](https://github.com/ckan/ckan/projects/3). 
For developing customization extensions developing off 2.8 or the latest master are both plausible options. 2.8 being an official release is more stable, and if you avoid the functionalities that are being dropped in the conversion (mostly Pylons) much should transfer fine. This is particularly true if the customization you mention is more focused towards updating html templates and such. The latest master is capable of most functionality and could be used for extension development.

**Comment by scoutinhoGit** [comment]
Hi pdekraker-epa,

Thank you very much for your explanation!  

Based on it, we are planning to install the **_latest_** version of CKAN **_from source_**.

But we must confess that - perhaps because it is not a stable version - we are facing some problems or limitations on this kind of installation. For example,  SOLR-JETTY, which version 9 has problems to work in UBUNTU 18 (in this case we are planning to  downgrade it to version 6.5). 

One last question: for DATASTORE to work automatically - allowing us to view the datasets without need of download - is the installation script for the latest version of CKAN sufficient or did we need to perform any DATASTORE / DATAPUSHER installation in a virtual python environment? 

Sorry if this last question was not clear, but we had problems in the past, trying to activate CSV dataset visualization on CKAN 2.9 local web site version (in every attenpt, the CKAN continued trying to acces DATAPROXY, ignoring DATASTORE/DATAPUSH configurations).

Best regards,

Sergio

**Comment by pdekraker-epa** [comment]
There are additional steps to configure the database for datastore [here](https://docs.ckan.org/en/latest/maintaining/datastore.html). I use xloader instead of datapusher, which is not yet updated for 2.9. If CKAN is loading from dataproxy it is because the data has not been loaded into the datastore or it is not configured. If datastore is installed the log about generating the datastore entry for each resource can be found on the DataStore tab of the resource edit page.

**Comment by amercader** [comment]
@scoutinhoGit as @pdekraker-epa mentioned, CKAN 2.8 is Python 2 only. Please don't rely on master for production code as it is not stable. If you find issues with the set up of the datasore / datapusher please raise them separately, thanks!
