### ISSUE TITLE
Error installing CKAN 2.8.3 from github -  TypeError: '<' not supported between instances of 'map' and 'map'

### ISSUE THREAD

**Issue by scoutinhoGit** [ckan/ckan#5284]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

Hi,

I'm trying to install CKAN from SOURCE using stable version.

I´m following CKAN manual on "https://buildmedia.readthedocs.org/media/pdf/ckan/latest/ckan.pdf"

I got an error when tunning command **" pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.8.3#egg=ckan' "**

What could i do to fix this problem? Cause i am following the instructions of manual.

Best regards,

Sergio

### CKAN Version if known (or site URL)
CKAN 2.8.3 - Source Installation
Ubuntu 18
Python 3.x

### Please describe the expected behaviour
Expected that could download and install CKAN 2.8.3 without error from GITHUB

### Please describe the actual behaviour
```
(default) ckan@ubuntu:~$ pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.8.3#egg=ckan' 
Obtaining ckan from git+https://github.com/ckan/ckan.git@ckan-2.8.3#egg=ckan
  Cloning https://github.com/ckan/ckan.git (to revision ckan-2.8.3) to /usr/lib/ckan/default/src/ckan
  Running command git clone -q https://github.com/ckan/ckan.git /usr/lib/ckan/default/src/ckan
  Running command git checkout -q 8e1cc60b2fa11da6843051678b7ee2cc08c2a7a9
    ERROR: Command errored out with exit status 1:
     command: /usr/lib/ckan/default/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/usr/lib/ckan/default/src/ckan/setup.py'"'"'; __file__='"'"'/usr/lib/ckan/default/src/ckan/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /usr/lib/ckan/default/src/ckan/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/ckan/default/src/ckan/setup.py", line 34, in <module>
        if parse_version(setuptools_version) < min_setuptools_version:
    TypeError: '<' not supported between instances of 'map' and 'map'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

### What steps can be taken to reproduce the issue? 

```
    1  sudo apt update
    2  sudo apt-get install python3-dev postgresql libpq-dev python3-pip python3-venv git-core solr-jetty openjdk-8-jdk redis-server
    3  mkdir -p ~/ckan/lib
    4  sudo ln -s ~/ckan/lib /usr/lib/ckan 
    5  mkdir -p ~/ckan/etc 
    6  sudo ln -s ~/ckan/etc /etc/ckan
    7  sudo mkdir -p /usr/lib/ckan/default 
    8  sudo chown `whoami` /usr/lib/ckan/default 
    9  python3 -m venv /usr/lib/ckan/default 
   10  . /usr/lib/ckan/default/bin/activate
   11  pip install setuptools==36.1 
   12  pip install --upgrade pip 
   13  pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.8.3#egg=ckan' 

```

**Comment by scoutinhoGit** [comment]
Hi,

Closing this issue cause CKAN 2.8.3 does not works with Python 3.x.

> We do not know why CKAN manual (https://buildmedia.readthedocs.org/media/pdf/ckan/latest/ckan.pdf) say it´s possible to install this CKAN version with python 3.x, but we suggest it´s very important to fix this manual, to avoid anothers users trying to install CKAN 2.8.3  with Python 3.x.  (as we have done)

**Comment by ccancellieri** [comment]
after that failure i've tryied with this:
pip install -e 'git+https://github.com/ckan/ckan.git#egg=ckan[requirements]'

(using master branch)
and it is working with python 3.7!
thanks
