### ISSUE TITLE
 Contributing guide: "the Pylons book" link in Translating CKAN links to ad portal

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5309]
### Please describe the expected behaviour
[The _Do the translation_ section of the _Translating CKAN_ page from the _Contributing guide_](https://docs.ckan.org/en/2.8/contributing/i18n.html#do-the-translation) contains:

> For more information on how to do this, see the Pylons book.

"the Pylons book" has a link which points to http://pylonsbook.com/en/1.1/internationalization-and-localization.html  
Clicking that link should bring to the Pylons book.

### Please describe the actual behaviour
Clicking the link brings to a hijacked domain which displays advertisements.

### What steps can be taken to reproduce the issue? 
This is not a behavioral bug.

---

The Pylons book is currently hosted on docs.pylonsproject.org. I believe the page corresponding to the one which used to be linked is [the _Internationalization and Localization_ page](https://docs.pylonsproject.org/projects/pylons-webframework/en/latest/i18n.html). [Its _Back To Work_ section](https://docs.pylonsproject.org/projects/pylons-webframework/en/latest/i18n.html#back-to-work) discusses modifying a po file, but very briefly.

**Comment by daminichopra** [comment]
Hi @amercader , If you are not working on this issue can u please assign this issue to me. Thank you :)

**Comment by amercader** [comment]
@daminichopra thanks a lot! I can't assign you without being a repo collaborator but please go ahead and submit a pull request if you can.
