### ISSUE TITLE
Update travis build templates to use newer build image

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#5310]
Current generated build templates use deprecated image from 2017 because it include older libpq https://github.com/travis-ci/travis-ci/issues/8897.

New extensions which are added to travis default to validate the config which changes the image from deprecated-2017Q4 to deprecated-2017q4. Travis is being travis and even though the images are built from the same cookbook, image with lowercase name has updated libpq and the build fails on older ckan versions.

Options for this are either document steps to turn off config validation and clear the caches for builds to work again or update to newer image and upgrade psycopg during travis build for it work with the newer libpq.

Either way the templates should be updated to run on python2 and python3 with nosetest and pytest, like migration guide tells to do. Unless we want that the templates target ckan 2.9 and later only.

**Comment by Zharktas** [comment]
It was agreed that base image should be updated, maybe to something that we have ourselves built.

The template will still target current ckan version and later and link to the some good extension for multiversion setups.

**Comment by duttonw** [comment]
Just raised a support ticket to TravisCI Request #19631, and they have come back and stated that they now don't lowercase group anymore.

Also on using bionic image to build ckan, i've managed to get it working on the qa extension you can see most of the changes here  https://github.com/qld-gov-au/ckanext-qa/pull/7/files 

```
Hello William,

Thanks for your patience regarding this issue.

I have reviewed it with Senior Engineers on our team and a fix has been pushed in this regard. You should be able to retain the "case" used for your group names as desired. I hope this helps.

Please let us know if there's anything else we can assist with on our platform.

Thanks and happy building!

--
MK

Travis CI Test and Deploy with Confidence.
www.travis-ci.com
```

**Comment by Zharktas** [comment]
Mostly superseded by #5569
