### ISSUE TITLE
Contributing guide: Internationalizing strings in JavaScript code section misleading about _() and ngettext()

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5317]
### CKAN 2.8

The first sentence of [section _Internationalizing strings in JavaScript code_ of the Contributing guide](https://docs.ckan.org/en/2.8/contributing/string-i18n.html#internationalizing-strings-in-javascript-code) is:
> Each CKAN JavaScript module offers the methods _ and ngettext for translating singular and plural strings, respectively: [...]

It is correct that ngettext() can be used for plural strings, but the implication that ngettext() cannot translate singular strings and the implication that \_() can only translate singular strings are wrong. The sentence should presumably distinguish between invariant strings (_()) and number-inflected strings (ngettext()).

**Comment by Gauravp-NEC** [comment]
@Chealer @kowh-ai ,I am working on this issue. I have investigate both the ngettext() and _() function. The ngettext() can be used for translating strings in both singular and plural form. Where as _( ) is the simplest function which returns the translated string. Please confirm my understanding.

**Comment by Chealer** [comment]
Thank you @Gauravp-NEC 
Your understanding seems correct, but it needs to be written carefully as the difference is subtle. ngettext() can be used to translate a single "string" which has both a singular and a plural form.

**Comment by Gauravp-NEC** [comment]
@Chealer , Thankyou for your response.
Please confirm my understanding that _( ) is the simplest function which returns the single translated string only.

**Comment by Chealer** [comment]
I confirm @Gauravp-NEC
