### ISSUE TITLE
Rendering error template fails for non-ascii error messages

### ISSUE THREAD

**Issue by bellisk** [ckan/ckan#5320]
### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
When an error page is returned, it should include the text of the error, e.g. "Unauthorized to edit a user."

### Please describe the actual behaviour
When the error text includes non-ascii characters, an "Internal server error" page with response code 500 is returned instead.

### What steps can be taken to reproduce the issue? 
As a non-logged-in user, with language set to German, try to edit a user page: https://demo.ckan.org/de/user/edit/covenant. The error text that should be returned is, "Keine Berechtigung, Benutzer zu ändern," and it fails because of the ä. In English it works: https://demo.ckan.org/en/user/edit/covenant.

In `ckan.lib.base.abort`, the detail is utf8-encoded with a comment saying that this is to prevent an exception from WebOb 0.9.7.1, but this encoding now seems to create an exception instead. (It works if the detail is not encoded.) Is there anything speaking against just removing this line?

**Comment by bellisk** [comment]
I meant to link to the line in question, sorry: https://github.com/ckan/ckan/blob/master/ckan/lib/base.py#L67

The commit comment refers to problems with versions of WebOb before 1.0, which has been required since 2013, so I _think_ removing the encoding shouldn't cause a problem.

**Comment by Zharktas** [comment]
I think this was already fixed in master https://github.com/ckan/ckan/pull/4829. At least I've been using it for a while, its not in 2.8.3 but would you mind testing if it fixes it for you too?

**Comment by bellisk** [comment]
Thanks @Zharktas, I tested it and that fix also works for me.
