### ISSUE TITLE
Updating resource doesn't show validation error

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#5334]
### CKAN Version
CKAN 2.9 and lower versions like 2.8, 2.7...

### Expected behavior
Updating required field without a value in a resource that for example is the second is list from 3 resources, should display validation error for this Resource.

### Actual behavior
Updating Resource doesn't show validation error if it's not the last in the list.

### Steps can be taken to reproduce the issue? 
1. Set up pure CKAN
2. Added ckanext-scheming and modify the default schema of resources by adding required field.
3. Create 3 resources
4. The last resource should have the required value.
5. Update the second Resource without the required value, as a result no value will be disaplyed.

**Comment by Engerrs** [comment]
Hi guys,
As mentioned above, there is an issue with error display while updating Resource without the required field. I'm using ckanext-schema, so been able to reproduce this issue, while default schema doesn't have required fields.
Fix is pretty straightforward. The [line](https://github.com/ckan/ckan/blob/master/ckan/logic/action/update.py#L119) raise `ValidationError(e.error_dict['resources'][-1])` was copied form Resource create action, which is right, but it shouldn't be like this on update.
If you look a bit above this [line](https://github.com/ckan/ckan/blob/master/ckan/logic/action/update.py#L110) in the update action, there is `pkg_dict['resources'][n] = data_dict` line in which n is the actual resource, so this n should be applied to the validation line as well as it makes sense to do so.

**Comment by Engerrs** [comment]
I also suggest that this fix should be backported to lower versions.

**Comment by amercader** [comment]
Fixed in https://github.com/ckan/ckan/pull/5335
