### ISSUE TITLE
Incompatible setuptools versions when setting up dev environment

### ISSUE THREAD

**Issue by chris48s** [ckan/ckan#5343]
### CKAN Version if known (or site URL)

2.9/dev

### Please describe the actual behaviour

I think its a docs issue really, not a bug.

I was recently setting up a copy of CKAN for local development. The instructions at https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html tell me to specifically `pip install setuptools==36.1` so I downgraded to 36.1, but then when I `pip install -r dev-requirements.txt` it throws

`ERROR: pytest-rerunfailures 8.0 has requirement setuptools>=40.0, but you'll have setuptools 36.1.0 which is incompatible.`.

Is there actually a hard dependency on setuptools 36.1 or should that really be `pip install setuptools>=36.1` in the docs?
Alternatively, should `pytest-rerunfailures` be pinned to a compatible version with the required `setuptools`?

### What steps can be taken to reproduce the issue? 

`pip install setuptools==36.1`
`pip install -r dev-requirements.txt`

**Comment by amercader** [comment]
@chris48s sounds like the best option is to bump the setuptools requirement to 40.0, can you do a quick PR?
