### ISSUE TITLE
packaging.ckan.org: .deb packages for Ubuntu contain .git/ directory

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5362]
### Please describe the expected behaviour
The Debian-format packages found on http://packaging.ckan.org/ should contain all CKAN files once only.

### Please describe the actual behaviour
The files in the /usr/lib/ckan/default/src/ckan/ of the python-ckan package are included both at their normal location and in a Git packfile in /usr/lib/ckan/default/src/ckan/.git/objects/pack/. This nearly doubles the size of .deb packages.

### What steps can be taken to reproduce the issue? 
This is not a behavioral issue.

---

I only verified this with http://packaging.ckan.org.s3-eu-west-1.amazonaws.com/python-ckan_2.8-bionic_amd64.deb, but according to the size displayed, this must affect all packages.

I did not check how these packages are built, but presumably, Git is used to create the contents of the packages, but the process fails to clean the .git/ once the checkout is complete. The $ git archive; command might help to clean up Git internals, but I am not sure how it should be used.

**Comment by kowh-ai** [comment]
@amercader @smotornyuk @wardi - probably don't need to include .git/* in packages right?...if so I can begin a PR on the https://github.com/ckan/ckan-packaging repo

**Comment by kowh-ai** [comment]
Created PR for this: https://github.com/ckan/ckan-packaging/pull/16

**Comment by kowh-ai** [comment]
This has been merged
