### ISSUE TITLE
master.ckan.org: HTTP Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5363]
### Please describe the expected behaviour
https://master.ckan.org/ should show the homepage of a CKAN instance using the master (development) version.

### Please describe the actual behaviour
An error is displayed:

> Error 503 Backend fetch failed
> Backend fetch failed
> 
> Guru Meditation:
> XID: 631116
> 
> Varnish cache server

### What steps can be taken to reproduce the issue? 
1. Access https://master.ckan.org/ in a browser

---

This has been happening for at least 8 hours.

**Comment by amercader** [comment]
master.ckan.org is currently being upgraded so we can expect some downtime there.

**Comment by pdelboca** [comment]
As mentioned, this instance is currently being upgraded. We will start doing updates about this in the following ticket: https://github.com/ckan/ckan/issues/5168

I'm closing this one.

**Comment by Chealer** [comment]
Thank you @amercader and @pdelboca 
If this issue is expected to persist for significant time, I recommend to either:

1. Change the master.ckan.org homepage to point to the other ticket
2. Keep this ticket open
3. Retitle the other ticket so it conveys the message that master.ckan.org is currently unavailable
