### ISSUE TITLE
demo.ckan.org: "unknown" as dates when viewing resources

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5369]
### Please describe the expected behaviour
The 3 first fields ("Data last updated", "Metadata last updated" and "Created") of the "Additional Information" table should display dates.

### Please describe the actual behaviour
The fields display "unknown", at least for many resources (possibly all).

### What steps can be taken to reproduce the issue? 
1. Load a resource from demo.ckan.org, such as [this one](https://demo.ckan.org/dataset/the-iris-dataset/resource/f8f8ca48-32a0-4e78-9904-522bd4ff56d5)

---

I checked that this also happens with a newly created resource.

**Comment by amercader** [comment]
@pdelboca not a priority, but maybe it's easy to find what's wrong on demo.ckan.org resources.

**Comment by daminichopra** [comment]
Hi @Chealer , I have been trying to reproduce this issue and in my case "Additional Information" table able to display dates.
Please find below screenshot for same.
![Capture](https://user-images.githubusercontent.com/35693908/86323571-b0f2c480-bc5a-11ea-8977-568b2e088919.PNG)

Please confirm if i am missing something. Thank you

**Comment by Chealer** [comment]
@daminichopra are you trying to reproduce on demo.ckan.org, or on another CKAN instance?

**Comment by daminichopra** [comment]
@Chealer , I am trying to reproduce it on demo.ckan.org

**Comment by Chealer** [comment]
@daminichopra what is the URL of your test?

**Comment by daminichopra** [comment]
@Chealer , This is the [URL](https://demo.ckan.org/dataset/demo22) of uploaded test.

**Comment by Chealer** [comment]
@daminichopra I am talking about the Additional Information table in resource pages, not about the Additional Info table in dataset pages.

**Comment by daminichopra** [comment]
@Chealer , Right i got it now, i will look into it. Thanks for the correction

**Comment by daminichopra** [comment]
Hi @Chealer , I was trying to debug the code by checking logs in my local ckan instance version 2.8.3 so that i can fix the issue and in my local instance "Additional Information" table is  displaying dates at  [URL](http://180.179.214.171:5000/dataset/damini/resource/2fecb563-638c-4eb6-857d-5a3ba3454a20).
Also , i have attached image for reference:
![local ckan](https://user-images.githubusercontent.com/35693908/87117800-1831f980-c297-11ea-91c4-69a1ed0389a9.PNG)

kindly, let me know if the problem is only related to demo.ckan.org and if i am missing something on this. Thanks

**Comment by Chealer** [comment]
To my knowledge, this issue is indeed specific to demo.ckan.org @daminichopra

**Comment by daminichopra** [comment]
Hi @Chealer @pdelboca  , I have been investigating further this issue with respect to `demo.ckan.org`. Please find below some investigation points.

1. I checked the version demo.ckan.org using is 2.8.2 
![Capture](https://user-images.githubusercontent.com/35693908/87414728-d0d6a080-c5e9-11ea-8dd6-09301f999f14.PNG)
2. After this i further investigated that how to update its version to 2.8.3 or 2.8.4 in which this issue has already fixed and i found these files [base.html](https://github.com/ckan/ckan/blob/687afafd54631a52801b3f00c9b50a7532390202/ckan/templates/base.html#L27)  [install.py](https://github.com/ckan/ckan/blob/f43d6a572838c792193f3239827d04f9ffea9206/ckan/config/install.py#L13)  [init.py](https://github.com/ckan/ckan/blob/c85561189b1bb88d9c8cf80809aa8bcd08912a5f/ckan/__init__.py#L3)
in which init.py `__version__ = '2.10.0a'` is used.

3. Also, Date which is not displaying in ckan version 2.8.2 has been resolved in ckan version 2.8.3 and updated versions , Please refer [api_token.py](https://github.com/ckan/ckan/blob/c7f0023a231391e756d1eeac01dc2ac4c413363e/ckan/model/api_token.py#L29)  [action.py](https://github.com/ckan/ckan/blob/32c1e6f3b1051773a556f794200e61e6bec987f1/ckanext/datapusher/logic/action.py#L88).

So, please confirm my understanding and kindly guide me that if there is separate code written for demo.ckan.org where i could update demo.ckan.org version.

**Comment by Chealer** [comment]
Thank you @daminichopra 
Let me first say I do not understand your last comment entirely. It is plausible that the outdated CKAN version could explain this issue, thanks for pointing that out. Unfortunately I cannot find any evidence to that effect either by reading the changelog of by reading commit messages. But changelogs are rarely complete and commit messages often do not tell much on the benefits, so you could still be right.

Unfortunately, I also cannot advise about how demo.ckan.org can be updated.

**Comment by Chealer** [comment]
What I can say is that dates show properly on beta.ckan.org (running CKAN ~2.9), according to [this example](https://beta.ckan.org/dataset/teststestset/resource/2d2cc96f-f2b8-46a4-8a48-40edcb54bed7).

**Comment by daminichopra** [comment]
@Chealer , yes its working fine on beta.ckan.org & I think updating demo.ckan.org version will resolve the problem. Also, If fixing is not required then please close this issue. Please let me know your opinion. Thank you

**Comment by Chealer** [comment]
I do not know for sure what is required to solve this, but if updating suffices, then by all means the ticket can be closed then. This ticket could be retitled something like "demo.ckan.org: on outdated 2.8.2, "unknown" as dates when viewing resources" if you are positive the version is the culprit.

**Comment by frafra** [comment]
Still happens in CKAN dev-v2.9.

**Comment by frafra** [comment]
It seems to work on demo.ckan.org.

**Comment by Chealer** [comment]
It does seem to work. Thank you @frafra , I will assume that this was resolved.

**Comment by frafra** [comment]
I think so. I still have it, but I think it could be related to ckanext-scheming.
