### ISSUE TITLE
stats extension: Wrong Statistics Menu icon (fa-medium)

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5371]
### Please describe the expected behaviour
The statistics extension offers a statistics page at /stats which contains a menu at the left. That menu is presented under a "Statistics Menu". If that heading has an icon, it should represent statistics.

### Please describe the actual behaviour
The heading has an "M" icon (representing the medium.com website).

### What steps can be taken to reproduce the issue? 
1. Enable the stats extension
1. Access http://root/stats

---

The regression must come from commit 7cae1c84fd4cdbe0e4bd48a8bdacb2012567d889, which added class _fa-medium_ instead of the previous _icon-medium_ class. I do not know what icon-medium did in Bootstrap 3, but I suppose it either did nothing, or affected the icon's size, which is not what it does in Bootstrap 4.

Removing that class changes the displayed icon to bar-chart, which is sensical.

**Comment by wardi** [comment]
sound like an easy fix @Chealer would you mind submitting a pull request?

**Comment by Chealer** [comment]
> sound like an easy fix @Chealer would you mind submitting a pull request?

It does sound easy but I didn't have a branch ready, so I'm happy to see I was beaten to it. Thanks @Zharktas and Mark Stuart, your solutions look good.
