### ISSUE TITLE
Dashboard: Unclear/misleading label "Edit settings" for link to profile

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5379]
### CKAN 2.8.4
The dashboard contains a link to /user/edit/username for the user's profile information. This link is labelled "Edit settings", which is at minimum unclear, and arguably misleading, as pieces of information like a user's _About_ field are not settings (at least in my book).

That phrase is also used as the title attribute (tooltip) for the cog wheel link at the top of all pages.

This can be experienced on [the dashboard on demo.ckan.org](https://demo.ckan.org/dashboard/groups).

---

"**Edit profile**" would better describe the link's function. I would add that "**Profile**" may be even better, since that page also allows consulting your profile. The "Username" field cannot even be changed. The page itself also uses the term "**Account Info**".

**Comment by amercader** [comment]
Fixed in #5410
