### ISSUE TITLE
Upgraded vendor js libraries broke the UI in CKAN 2.7.7 

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#5384]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.7.7

### Please describe the expected behaviour
According to the discussion: https://github.com/ckan/ckan/pull/3547#issuecomment-302437127 and the [changelog of CKAN 2.8.0](https://docs.ckan.org/en/latest/changelog.html#v-2-8-0-2018-05-09), only CKAN 2.8 and later come with newer vendor js libraries (e.g., Font Awesome 4.7.0). Templates are also updated to align with upgraded libraries.

### Please describe the actual behaviour
This commit: https://github.com/ckan/ckan/commit/973a6e28f25f3661de34d5a658ada2fa64c56783 updated vendor js libraries. However, the templates remained unchanged, which broke the UI. For example, the heading of a search facet shows an "M" icon because the [fa-medium](https://github.com/ckan/ckan/blob/ckan-2.7.7/ckan/templates/snippets/facet_list.html#L53) class specifies the icon of medium.com in Font Awesome 4.7.0. The fa-medium class had been removed in the CKAN 2.8.x but CKAN 2.7.x hadn't.

### What steps can be taken to reproduce the issue? 
Install the CKAN 2.7.7, then access http://SITE_URL/dataset.

**Comment by Zharktas** [comment]
fa-medium and the [previous icon-medium class](https://github.com/ckan/ckan/commit/7cae1c84fd4cdbe0e4bd48a8bdacb2012567d889#diff-6a3b893a7654633c7adb9bd072320f10L53) actually didn't do anything as far as I can tell from git history. It might have been an attempt to explicitly say something about icon size as font-awesome 3 has icon-large class, but it doesn't have icon-medium at all. fa-medium class should just be removed from everywhere as it actually has a meaning in newer font awesome as they added the medium logo, there is a related issue #5371 as stats extension still has the fa-medium in there.

**Comment by markstuart** [comment]
I'd really like to upgrade the CKAN version for catalogue.data.govt.nz to 2.7.7, and this is a bit of a blocker. I'm happy to raise a PR to fix this... should I do that against the 2.7 branch?

**Comment by u10313335** [comment]
Thanks @Zharktas and @markstuart.

But I think the changes of templates are far more than just the fa-medium class. More specifically, there are lots of modifications in the [bs3 migration](https://github.com/ckan/ckan/pull/3547/files). I would suggest a rollback to the old vendor js libraries since bs3 has not yet been (and should not be) included in the CKAN 2.7.x.

**Comment by Zharktas** [comment]
Ah, right. I didn't remember that bootstrap was upgraded at ckan 2.8, it needs to be downgraded again for older ckans. That fa-medium just confused me as it is not related to bootstap.

**Comment by amercader** [comment]
Thanks @u10313335 , we will release new patch releases to address this

**Comment by u10313335** [comment]
Thank you all! I appreciate it.

**Comment by Zharktas** [comment]
Closed via new patch releases.
