### ISSUE TITLE
Datapusher requests failing in 2.7.7 when using uwsgi sockets

### ISSUE THREAD

**Issue by markstuart** [ckan/ckan#5385]
### CKAN Version if known (or site URL)
2.7.7

### Please describe the expected behaviour
Datapusher requests to ckan should succeed when using nginx proxy and uwsgi sockets on the ckan server

### Please describe the actual behaviour
Datapusher fails with an error in the UI, and uswgi error in the ckan container logs: 
```
invalid request block size: 21327 (max 4096)...skip
```

### What steps can be taken to reproduce the issue? 
Run ckan with datapusher, ckan running uwsgi with flags:
```
--protocol uwsgi  --socket 0.0.0.0:5000
```

So this appears to have been introduced in https://github.com/ckan/ckan/commit/9a41f5a791bbc551959d3608103340ce545785c0

@amercader I'm confused as to why this url would be hardcoded like this? In our particular setup it almost works since we have our ckan container as a named route in the docker-compose file and we're running on port 5000, but since it bypasses the nginx proxy it is trying to talk http to uwsgi socket. Looking at the master branch it seems to be still in the same format as prior to your commit, `h.url_for('/', qualified=True)`.

**Comment by amercader** [comment]
This is obviously a bug @markstuart , thanks for flagging it and submtting the PR

**Comment by pazepaze** [comment]
> Datapusher fails with an error in the UI, and uswgi error in the ckan container logs:
> 
> ```
> invalid request block size: 21327 (max 4096)...skip
> ```

This error message is similar to https://github.com/okfn/docker-ckan/issues/50 and I fixed it like this https://github.com/okfn/docker-ckan/pull/51

**Comment by markstuart** [comment]
Cleaning up, not sure why this stayed open after the PR was merged.
