### ISSUE TITLE
 Utilizing object store access control

### ISSUE THREAD

**Issue by espenfl** [ckan/ckan#5407]
First, thanks for all the effort everyone has been putting into CKAN. It is nice to see its progress and increased adoption.

With an object store system, one typically have access control already in place at the object level. Can this be utilized in CKAN? E.g. say that a user makes an API request to fetch a dataset. The user is allowed if the right credentials from the object store system is in place, otherwise some sensible messages are returned etc. Same goes for data entry and search etc. In practice the authentication system of CKAN is then somewhat bypassed (except possibly when one also want to limit the use of the frontend).

**Comment by amercader** [comment]
@espenfl For general discussion like this we use the ideas [repo](https://github.com/ckan/ideas) where we can flesh out proposals or ideas until they are concrete actions or fixes to be done in core.
It'd be useful if you could expand on your use case, what tools you need to integrate with, etc.
These existing resources might help you in what you are trying to do:
* [Extending core authorization functions](https://docs.ckan.org/en/latest/extensions/tutorial.html#implementing-the-iauthfunctions-plugin-interface)
* Extension for Token based authorization: https://github.com/datopian/ckanext-authz-service

Thanks!
