### ISSUE TITLE
Problem with repoze.who-friendlyform install

### ISSUE THREAD

**Issue by DorimenUkraine** [ckan/ckan#5411]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
last version from Github

### Please describe the expected behaviour
I can't install repoze.who-friendlyform from requirements-py2.txt on Ubuntu 16.04 LTS server

Collecting repoze.who-friendlyform
  Using cached repoze.who-friendlyform-1.0.8.tar.gz (25 kB)

    ERROR: Command errored out with exit status 1:
     command: 'E:\DjangoEnv\agrilands.in.ua\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\vandr\\AppData\\Local\\Temp\\pycharm-packaging\\repoze.who-friendlyform\\setup.py'"'"'; __file__='"'"'C:\\Users\\vandr\\AppData\\Local\\Temp\\pycharm-packaging\\repoze.who-friendlyform\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\vandr\AppData\Local\Temp\pip-pip-egg-info-w24lshza'
         cwd: C:\Users\vandr\AppData\Local\Temp\pycharm-packaging\repoze.who-friendlyform\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\vandr\AppData\Local\Temp\pycharm-packaging\repoze.who-friendlyform\setup.py", line 18, in <module>
        from ez_setup import use_setuptools
      File "C:\Users\vandr\AppData\Local\Temp\pycharm-packaging\repoze.who-friendlyform\ez_setup.py", line 94
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

http://joxi.ru/bmo1Ekds91gEqA

**Comment by smotornyuk** [comment]
`except Type, e` is valid only for Python2. And that's meat that you are using python3's pip while installing packages. You have two options:
* use python2 (probably, you need to recreate venv)
* install `requirements.txt` instead - this file contains dependencies for python3.

**Comment by DorimenUkraine** [comment]
> `except Type, e` is valid only for Python2. And that's meat that you are using python3's pip while installing packages. You have two options:
> 
> * use python2 (probably, you need to recreate venv)
> * install `requirements.txt` instead - this file contains dependencies for python3.

Thnx a lot!
