### ISSUE TITLE
Upload to Datastore doesn't work

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [ckan/ckan#5441]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
datastore_default und ckan_default postgres user exist und works fine.
I install Datastore, test it with 
`curl -X POST http://127.0.0.1:5000/api/3/action/datastore_create -H "Authorization: 2dc79e57-20e0-4cd6-984a-ce0381fb93c1" -d '{"resource": {"package_id": "cb49140a-09c2-4dea-930c-184a873d051a"}, "fields": [ {"id": "a"}, {"id": "b"} ], "records": [ { "a": 1, "b": "xyz"}, {"a": 2, "b": "zzz"} ]}'
`

### Please describe the actual behaviour
But the I got an error, 404.
On ckan-site i got no message, still loading and loading.
![grafik](https://user-images.githubusercontent.com/49939451/84658859-cfe11f00-af16-11ea-86d4-99ccdee88319.png)

**Comment by LukeTully** [comment]
I was just working through a similar issue last night, and to help you, we'll need more information. 

Have you set up DataPusher as well as DataStore? [Datapusher is a separate service](https://docs.ckan.org/projects/datapusher/en/latest/index.html) that interacts with the DataStore through apis in the respective [Datapusher plugin](https://github.com/ckan/ckan/tree/master/ckanext/datapusher). The DataPusher plugin needs to be enabled and configured with the URL of DataPusher in your config file (ckan.datapusher.url).

Based on the chain of methods that are called to get data into the DataStore, my guess is that you have enabled both the DataStore and the DataPusher plugin in your config, but you've either not installed the DataPusher service, or something else is misconfigured in your hosting of that service.

There are instructions on the [DataPusher installation page ](https://docs.ckan.org/projects/datapusher/en/latest/index.html) for testing DataPusher on it's own. If you get an unexpected response from DataPusher, then DataStore won't work. At this point, you can provide stack traces from the datapusher or ckan log files (with sensitive information obscured, like your API key), as well as any config files associated with datapusher or apache, and I'll try and help further.

**Comment by MichaelHarmsTIB** [comment]
I installed xloader instead as datapusher.

**Comment by MichaelHarmsTIB** [comment]
Upload of data/files working, solr works, another error message is from postgresql db: datastore_default@datastore_default LOG: could not recieve data from client: Connection reset by peer
But password/login is set and works for ckan.

**Comment by amercader** [comment]
@MichaelHarmsTIB When are you getting the 404 error? is it when calling the `datastore_create` action? If so can you double check you have loaded the `datastore` plugin.

Another thing to check is that xloader requires a worker job to carry on the uploads, are you running this? Check the Xloader documentation for more details on this.

For support requests like this one please use the [ckan-dev mailing list](https://groups.google.com/a/ckan.org/forum/#!forum/ckan-dev) or the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Thanks!

**Comment by MichaelHarmsTIB** [comment]
Thx, I found the reason, you have to start one worker, or it doesn't work. And one issue, if you start a upload before starting the worker, ckan has already add a dataset, und you got an error of double columns.
