### ISSUE TITLE
Page view tracking of datasets is not working if ckan is running at a subpath

### ISSUE THREAD

**Issue by wrinklenose** [ckan/ckan#5468]
### CKAN Version if known (or site URL)
2.8.4

### Please describe the expected behaviour
Page view tracking works as describend in https://docs.ckan.org/en/2.8/maintaining/tracking.html as well if ckan is operated at subpath.

### Please describe the actual behaviour

Page view tracking works as expected if ckan runs at standard root path "/".
But we're running ckan on a subpath ('/ckan') using the ckan.root_path property in the production.ini.
In this case the page view tacking of datasets **always shows zero hits**.

After some investigation into the db, I figured out that the hits are successfully reflected in table 'tracking_raw', but not updated during a 'paster --plugin=ckan tracking update' in table 'tracking_summary'.

I further noticed, that tracking_summary.package_id keeps the value '\~\~not\~found\~\~' for all datasets at this system. (Unlike to a system running on '/' where correct package-ids are set).

When I compared the stored urls of both systems, i also noticed that the leading url path is reflected in the stored url. So you'll get:
' /ckan/dataset/test' or ' /ckan/de/dataset/test'(both not working) im comparision to ' /dataset/test' or ' /de/dataset/test' (both working).

I've tried to track the problem in the code. For my understanding the problem could be located in **/cli/tracking.py** - function **update_tracking**.
Below the comment "get ids for dataset urls" happens the construction of a sql, using a regex.

```
# get ids for dataset urls
sql = u'''UPDATE tracking_summary t
            SET package_id = COALESCE(
                (SELECT id FROM package p
                WHERE p.name = regexp_replace
                  (' ' || t.url, '^[ ]{1}(/\\w{2}){0,1}' || %s, ''))
                ,'~~not~found~~')
            WHERE t.package_id IS NULL
            AND tracking_type = 'page';'''
engine.execute(sql, PACKAGE_URL)
```

This regex does not reflect a leading path part ('/ckan' in our example), which leads to an failing UPDATE statement.

### What steps can be taken to reproduce the issue? 
- configure ckan under a sub path like mentioned in the docs https://docs.ckan.org/en/2.8/maintaining/configuration.html#ckan-root-path
- enable page view tracking like mentioned in the docs https://docs.ckan.org/en/2.8/maintaining/tracking.html
- create a dateset and visit it
- update the page view tracking statistic like mentioned in the docs https://docs.ckan.org/en/2.8/maintaining/tracking.html (I did it manually running the paster command)
- Retrieve the tracking data by API or paster command like mentioned in https://docs.ckan.org/en/2.8/maintaining/tracking.html
- alternatively confirm my findings by inspecting the database tables 'tracking_raw' and 'tracking_summary'

**Comment by wardi** [comment]
The simplest approach would be to strip the root path before storing in the tracking summary table. Good for contribution.

**Comment by quinoescobar** [comment]
This still happens in current versions of CKAN running under a root_path

**Comment by Gauravp-NEC** [comment]
Hi, I am trying to get the tracking summary of dataset using package_show() API i.e., curl http://localhost:5000/api/3/action/package_show?id-[] & include_tracking=true . Can anyone confirm me that I calling the correct API?

**Comment by wardi** [comment]
In #5483 I asked for a change and there hasn't been any activity since. @nisha-nec if you would like to submit a new PR please go ahead.

**Comment by nisha-nec** [comment]
@wardi I have raised the PR #7649 . kindly review the PR .

**Comment by Nisha1293** [comment]
Hi, I have checked the tracking extension under the root_path, and the issue still exists in CKAN v2.11.
Could you please let me know that is there any plan to fix this issue? or may I proceed with raising a new PR to address it?
