### ISSUE TITLE
ckan docker container does not start under macOS

### ISSUE THREAD

**Issue by TBoonX** [ckan/ckan#5469]
### CKAN Version if known (or site URL)
git branch master and tags: ckan-2.8.0, ckan-2.8.3, ckan-2.8.4
Before a new checkout I executed `docker-compose down && docker rmi -f docker_ckan docker_db`

### Please describe the expected behaviour
After `docker-compose up -d --build` all containers should be running or, with a few retries, stopped containers should be runnable.

### Please describe the actual behaviour
All containers except `ckan` are running and `ckan` restarting results in it being stopped.
The `ckan` container stopps with the following log message:
```
ckan          | Command 'db' not known (you may need to run setup.py egg_info)
ckan          | Known commands:
ckan          |   create       Create the file layout for a Python distribution
ckan          |   exe          Run #! executable files
ckan          |   help         Display help
ckan          |   make-config  Install a package and create a fresh config file/directory
ckan          |   points       Show information about entry points
ckan          |   post         Run a request for the described application
ckan          |   request      Run a request for the described application
ckan          |   serve        Serve the described application
ckan          |   setup-app    Setup an application, given a config file
```

### What steps can be taken to reproduce the issue? 
Follow the steps under https://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html#build-docker-images
The `.env` file was just copied from the template, no changes

My environment:
Docker version 19.03.8
docker-compose version 1.25.5
macOS Catalina 10.15.5

On Stackoverflow seems to be the same issue: https://stackoverflow.com/questions/61937083/ckan-docker-install-seems-perfect-except-ckan-container-exits-immediately-after

**Comment by kowh-ai** [comment]
Is your stack trace the same as (or similar to) the Stackoverflow link? Does it include this file: ``/usr/lib/ckan/venv/src/ckan/ckan/cli/init.py`` if so, this file and directory does not exist in CKAN 2.8.x and somehow you have some CKAN 2.9 in there. I'd suggest running: ``docker system prune -a --volumes`` if that is the case

**Comment by TBoonX** [comment]
It is not in my stack trace. I still executed `docker volume prune` after I deleted all ckan containers and now all container are running! Thanks.

**Comment by kowh-ai** [comment]
Excellent news!
