### ISSUE TITLE
Could not connect to DataPusher

### ISSUE THREAD

**Issue by debbielee1996** [ckan/ckan#5481]
**CKAN version**

**Describe the bug**
Could not connect to DataPusher

**Steps to reproduce**

**1. Installed CKAN from source https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html**
**2. Installed DataStore extension (https://docs.ckan.org/en/2.8/maintaining/datastore.html), tested till step 3 curl -X GET "http://127.0.0.1:5000/api/3/action/datastore_search?resource_id=_table_metadata"**

Output:
_{"help": "http://localhost:5000/api/3/action/help_show?name=datastore_search", "success": true, "result": {"include_total": true, "resource_id": "_table_metadata", "fields": [{"type": "int", "id": "_id"}, {"type": "name", "id": "name"}, {"type": "oid", "id": "oid"}, {"type": "name", "id": "alias_of"}], "records_format": "objects", "records": [], "_links": {"start": "/api/3/action/datastore_search?resource_id=_table_metadata", "next": "/api/3/action/datastore_search?offset=100&resource_id=_table_metadata"}, "total": 0}}(default)_

**3. Installed DataPusher according to https://docs.ckan.org/projects/datapusher/en/latest/deployment.html**
All steps work except sudo a2ensite datapusher

**4. Some of my development.ini settings**

##Define which views should be created by default
##(plugins must be loaded in ckan.plugins)
ckan.views.default_views = image_view text_view recline_view

##Customize which text formats the text_view plugin will show
##ckan.preview.json_formats = json
##ckan.preview.xml_formats = xml rdf rdf+xml owl+xml atom rss
##ckan.preview.text_formats = text plain text/plain

##Customize which image formats the image_view plugin will show
##ckan.preview.image_formats = png jpeg jpg gif

###Datapusher settings

##Make sure you have set up the DataStore

ckan.datapusher.formats = csv xls xlsx tsv application/csv application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
ckan.datapusher.url = http://0.0.0.0:8800/
ckan.datapusher.assume_task_stale_after = 3600

**Additional details**
- deployed everything locally, only development setup (ie. only development.ini file available)
**- strangely with my setup I am not seeing any log files for datapusher/apache (/var/log/apache2) like what other users have reported** --> how do I get the log files set up?
- when I run curl http://0.0.0.0:8000 I get the connection refused error
![datapusher](https://user-images.githubusercontent.com/62943444/86335758-810ae780-bc81-11ea-9f2c-ce8d0e2096e0.png)

**Comment by debbielee1996** [comment]
Is there possibly a guide on how to set up DataStore properly? I could go up to the point where I set up ckan (2.8.4), sysadmin and fileupload properly. But afterwards when I start to work on DataStore/DataPusher the entire project just spins out of control... Would appreciate any help I can get :(

**Comment by debbielee1996** [comment]
A little update as I have been trying out a few other debugging methods - I created the log file manually following the setup of DataPusher via https://docs.ckan.org/projects/datapusher/en/latest/development.html

On running the step: python datapusher/main.py deployment/datapusher_settings.py
There is apparently an error **ImportError: No module named ckanserviceprovider.web**

Maybe that was the root cause, but how do I resolve the issue? Thanks! :)

**Comment by debbielee1996** [comment]
I installed Datapusher via the development and production way... And with this **https://docs.ckan.org/projects/datapusher/en/latest/development.html**
when I tried running _python datapusher/main.py deployment/datapusher_settings.py_ in the python virtual environment
I get the error **ImportError: No module named ckanserviceprovider.web**

localhost:8800 gave me a success page too
![image](https://user-images.githubusercontent.com/62943444/86421600-3a62cf00-bd0d-11ea-8e6c-b2ee00c2098d.png)

Hoping this helps

**Comment by debbielee1996** [comment]
I attempted to redo everything and managed to setup DataPusher successfully. For anyone out there who might have issues setting up in development, here are the series of steps to follow:

**1. Setup CKAN from source**
https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html
Follow this tutorial https://www.youtube.com/watch?v=rPiI2J32rpw&t=924s to fill in the missing steps, as the documentations from the link above will lead to some issues in the setup process.

**2. Set up DataStore**
https://docs.ckan.org/en/2.8/maintaining/datastore.html

**3. Set up FileStore to upload files**
https://docs.ckan.org/en/2.8/maintaining/filestore.html

**4. Set up sysadmin and upload a csv file of your choice**
https://docs.ckan.org/en/2.8/sysadmin-guide.html

**5. Setup DataPusher**
https://docs.ckan.org/projects/datapusher/en/latest/development.html
Slight bug here when you run _python datapusher/main.py deployment/datapusher_settings.py_
It will lead to an error in the file _main.py_
Simply change the line _from . import jobs_ to _import jobs_ and rerun the line above. You need to start up datapusher manually everytime you want to use it

**6. Simply reload ckan project. And both DataPusher and DataStore should be running**
![image](https://user-images.githubusercontent.com/62943444/86453117-dad9e300-bd4f-11ea-9547-564b1d96874c.png)


Hopefully I'm doing it right. But one question for @amercader - why is there no log files for DataPusher/DataStore? Or where do I find it? I'm not seeing it anywhere... many thanks!

**Comment by debbielee1996** [comment]
another question I'm wondering is if there's different versions of SQLAlchemy required for CKAN/DataStore/DataPusher? Because when I reran the entire project, I was forced to downgrade my SQLAlchemy to version 0.4-0.9. And when I did it broke the project, I couldn't view the datasets anymore and certain sites on the browser were broken (internal server error).

**Comment by kowh-ai** [comment]
@debbielee1996 - Did you ever find where your logging ended up?...if you are running DataPusher in "Development mode" you should see logging in the window you started the python process PLUS in `/tmp/ckan_service.log`. If you set up DataPusher with apache, the logs will be in the standard `/var/log/apache2/` directory. Please note that CKAN 2.9 was released today and if you install this version using the "CKAN package" format, DataPusher will be installed by default and will include a uWSGI server component, the logs of which will be located in `/var/log/ckan/`

**Comment by debbielee1996** [comment]
awesome, thanks kowh-ai! In addition, I would like to ask on some rendering issues. Will be setting up a new thread for that - would appreciate any help given :)
