### ISSUE TITLE
CKAN 2.9 Release

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5485]
WIP

This is an issue to track the work needed for the release of CKAN 2.9.
The target is to release it before the end of July (ie week of 27th July). We are also aiming to do patch releases for 2.8 and 2.7, which are tracked in a separate issue: TODO

### Starting up
- [x] Create a new `dev-v2.9` branch from master.
- [x] Change version number on this branch to `2.9.0b`
- [x] Update version on `master` to `2.10.0b` (we can always change it to `3.0.0a`later)
- [x] Update beta.ckan.org to run from the `dev-v2.9` branch (py3)
- [x] Create new 2.9 translations on Transifex. Full instructions on point 5 [here](https://docs.ckan.org/en/2.8/contributing/release-process.html#doing-the-beta-release) but the summary is:
  * Create new `ckan.pot` file and new Transifex resource (in `.tx/config`)
  * Pull latest translations from last release
  * Update po files
  * Push new po files
- [x] Announce on the mailing list the start of the release process. From this moment on, anything that needs to go into 2.9 needs to be first merged to master and then cherry-picked to 2.9 (use the [Backport 2.9.0](https://github.com/ckan/ckan/labels/Backport%202.9.0) label to mark the relevant PRs)
- [x] Update packaging scripts to be able to build 2.9 (https://github.com/ckan/ckan-packaging/issues/17)

### Next few days
The following steps will likely be need to be repeated as we put more changes on the release branch. The idea is to keep it as usable and up to date as possible for testers:
- [x] Create the documentation branch from the release branch (`dev-v2.9`). This branch should be named `2.9`
- [x] Build frontend (`ckan front-end-build`)
- [x]  Update changelog in `dev-v2.9`. Run towncrier command plus manually add anything missing.
- [x] Test fixes for cherry-picked issues locally and on beta.ckan.org
- [x] Test that Debian package builds fine
- [x] Merge `dev-2.9` into `2.9`

### When the release is frozen

- [x] Update version on `dev-v2.9` branch to `2.9.0`
- [x] Create tag `ckan-2.9.0`
- [x] Build final deb package
- [x] Merge `dev-2.9` into `2.9`
- [x] Send email to CKAN announce / dev a week before the planned release day

### Release day

- [x] Upload to https://packaging.ckan.org/
  - [x] Rename package to override existing 2.8 one
  - [x] Update md5sum
- [x] Upload to pypi (`python setup.py sdist && twine upload dist/*`)
- [ ]  Announce
  - [x] ckan-announce and ckan-dev ([model](https://lists.okfn.org/pipermail/ckan-announce/2018-March/000035.html))
  - [x] Twitter
  - [x] ckan.org blog post (For 2.9 I think a more detailed walk through the new features would be great apart from the usual annoucement)

### After release 

- [x] Cherry pick two i18n commit above to master
- [x] Update changelog in master with the 2.9.0 one
- [x] :beers:

**Comment by pdelboca** [comment]
@shubham-mahajan completed the deploy and [beta.ckan.org](https://beta.ckan.org/) is running on CKAN 2.9. So we can check that item from the list @amercader!

[https://beta.ckan.org/api/3/action/status_show](https://beta.ckan.org/api/3/action/status_show)

**Comment by amercader** [comment]
Thanks @shubham-mahajan @pdelboca I just noticed that things look off because the frontend wasn't built, can you redeploy now? I pushed a new commit to dev-v2.9

**Comment by shubham-mahajan** [comment]
@amercader @pdelboca Redeployed with the latest commit.

**Comment by amercader** [comment]
2.9 was released on 2020-08-05

Leaving the drinks item :beers: to everyone's own convenience
