### ISSUE TITLE
Requirements Upgrade

### ISSUE THREAD

**Issue by slacker007** [ckan/ckan#5491]
Hi, 

Would it be possible to upgrade the requirements listed below due to vulnerabilities with the current versions of the dependencies? 

requests==2.11.1 to 2.24.0
Jinja==2.8 to 2.11.2
nose==1.3.7 to nose2 0.9.2 (successor to nose & actively maintained)
SQLAlchemy==1.2.19 to 1.3.18
bleach==2.1.3 to 3.1.5
mako==1.0.7 to 1.1.3
flask-babel==0.11.2 to 1.0.0
jquery==3.2.1 to latest
jquery==1.7.1 to latest
moment==2.0.0 to latest
moment==2.14.1 to latest
werkzeug==0.14.1 to 1.0.1
flask==0.12.4 to 1.1.2
html5lib==1.0.1 to 1.1

**Comment by smotornyuk** [comment]
Yes, these libraries are updated in CKAN v2.9 that should be released in the end of the month: 
https://github.com/ckan/ckan/blob/master/requirements.txt
https://github.com/ckan/ckan/blob/master/package.json#L14-L16

**Comment by slacker007** [comment]
Awesome.  Thanks!
