### ISSUE TITLE
CKAN - Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds) 

### ISSUE THREAD

**Issue by gallexme** [ckan/ckan#5492]
**CKAN version**
2.8
**Describe the bug**
Previewing Excel File Above 2.xMB Results in 
> Ansicht konnte nicht geladen werden: DataProxy gab einen Fehler zurück (Request Error: Backend did not respond after 10 seconds)

DataProxy Backend tells me:
> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.`

**Steps to reproduce**
Preview Excel file of about 3MB Size, 
**Expected behavior**
Preview to Successfully work

**Additional details**
![image](https://user-images.githubusercontent.com/1122989/86936762-bc545d00-c13e-11ea-82ef-57175ebcb47b.png)

![image](https://user-images.githubusercontent.com/1122989/86936748-b78fa900-c13e-11ea-86bd-ba4aad09f023.png)

**Comment by wardi** [comment]
The dataproxy is a shared resource and has resource limits and occasional outages. Try to make sure all your data is being loaded into your own datastore with xloader or datapusher then recline will access the data directly instead.
