### ISSUE TITLE
Couldn't create a Transifex account, say, to update an existing language

### ISSUE THREAD

**Issue by linforestzhang** [ckan/ckan#5498]
**CKAN version**
Not relevant.  This not an issue for CKAN per se.

**Describe the bug**
A Transifex account couldn't be created  , say, to update an existing language.

**Steps to reproduce**
-- Steps to reproduce the behavior:
Visit from a country with something blocking:
https://www.transifex.com/signup/?join_project=ckan

**Expected behavior**
-- A clear and concise description of what you expected to happen.
There are no input controls (e.g., fields for entering text such as user name) on the page.

**Additional details**
-- If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.
For further details, please see the snapshot attached.
![An issue for creating a Transifex account](https://user-images.githubusercontent.com/8653853/87307534-61f73a00-c54c-11ea-9689-b09f46dda345.PNG)

**Comment by linforestzhang** [comment]
This issue would prevent people's engagement in the CKAN's Transifex translation project.

**Comment by amercader** [comment]
@linforestzhang I get the same result if I turn off javascript. Is that the case with you? Try enabling javascript to see if the login form appears. Alternatively you might be using an adblocker that affects the form display?
If that doesn't help please reach out to Transifex https://www.transifex.com/contact/ as this is not something we can help with

**Comment by linforestzhang** [comment]
@amercader Wierd.  The login form shows up even when I didn't do anything now and My account was created successfully.  Thank you so much!

**Comment by amercader** [comment]
Glad you got it working, thanks for contributing!
