### ISSUE TITLE
Ckan 2.8.5 Login Logout page redirection issue

### ISSUE THREAD

**Issue by hussnainwithss** [ckan/ckan#5525]
**CKAN version**

**Describe the bug**
Im running a development version of stable release of ckan 2.8.5 (branch 2.8 previously ckan-2.8.5) on an amazon ec2 instance and whenever i try to login or logout any user it redirects me to http://0.0.0.0:5000/user/logged_in?__logins=0&came_from=%2Fuser%2Flogged_in which im not sure why is it doing this. Redirection works completely fine on Registration page. but does not work on login or logout page.
**Steps to reproduce**
- Install ckan 2.8.5 on AWS EC2 ubuntu 16.04 Instance 
- Run locally on the ec2 instance with ckan site address pointing to public IP of the instance in the development.ini file
- Go to login page and try to login (either with correct or incorrect credentials) 
- Unable to connect error given by the browser

**Expected behavior**
For login the user should be logged in and redirected to the dashboard page and for logout the user should be logged out of the session.

**Additional details**
Exception happened during processing of request from ('39.35.227.12', 52519)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by amercader** [comment]
@hussnainwithss Thanks for the report. The issue you describe should be fixed in 011405f77. This was on the `dev-v2.8` branch but not the `2.8` one. I've now updated it to contain the latest changes. Can you pull and restart to try again?

**Comment by hussnainwithss** [comment]
The issue has been resolved  @amercader  thank you
