### ISSUE TITLE
Documentation missing for webassets config option

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5526]
While reviewing the changelog I could not find any documentation about these two new config options on CKAN 2.0:

     ckan.webassets.use_x_sendfile = false
    ckan.webassets.path = /var/lib/ckan/webassets

@smotornyuk would you mind adding a short description in `configuration.rst` and maybe some paragraph in the webassets docs about how to set up X-Sendfile?

**Comment by smotornyuk** [comment]
Done. I've created branch inside this repo, so you can change it if I've chosen phrases that are not clear enough
