### ISSUE TITLE
Login Issue - Login always fails on first attempt

### ISSUE THREAD

**Issue by debbielee1996** [ckan/ckan#5529]
**CKAN version**
2.8 on Ubuntu LTS 18.04

**Describe the bug**
Unable to login successfully on first attempt (tried with admin and regular user account).

**Steps to reproduce**
1. 127.0.0.1:5000/user/login to have first login attempt with correct credentials
![image](https://user-images.githubusercontent.com/62943444/89602184-c5009600-d898-11ea-964b-81f41a6f0b74.png)

2. upon 'failed' attempt to login, will be redirected to 127.0.0.1:5000/user/logged_in where I can login successfully with the exact same credentials. When I wrote a selenium script to help automate the uploading of datasets, I always have to login via 127.0.0.1:5000/user/logged_in instead
![image](https://user-images.githubusercontent.com/62943444/89602301-fed19c80-d898-11ea-965d-a377937ee56b.png)

**Expected behavior**
Logging in via 127.0.0.1:5000/user/login should always succeed on first attempt with correct credentials.

**Comment by guibos** [comment]
I think that is a expected behavior if your ckan.site_url = http://127.0.0.1 (in your production.ini). Please try to logging directly: 127.0.0.1:5000/user/logged_in

**Comment by debbielee1996** [comment]
Hi guibos, thank you for the response. Is there an explanation why the site is behavinv like this? I am using 127.0.0.1 as the ckan website.

**Comment by debbielee1996** [comment]
Some updates - I realized that the issue occurs only after the installation of DataPusher. Strange though, because I set up DataPusher in a separate virtualenv as there were conflicting versions of packages with CKAN itself. Would like to seek your advice on this

**Comment by shubham-mahajan** [comment]
@debbielee1996 `127.0.0.1` and `localhost` are considered as two different hosts for the cookie when generating the cookie with the domain and so if your `ckan.site_url` is having value as `127.0.0.1`, then ckan will generate the cookie for domain `127.0.0.1` which cannot be shared with `localhost`.

e.g if my `ckan.site_url=ckan`, then the cookie with the `domain as ckan` can only validate login.

<img width="1242" alt="Screenshot 2020-09-03 at 12 55 34 PM" src="https://user-images.githubusercontent.com/25545982/92084275-c87a3500-ede4-11ea-8dc1-8db4256aaa49.png">

**Comment by debbielee1996** [comment]
Thanks a lot @shubham-mahajan for the explanation! I think it's clearer now 👍
