### ISSUE TITLE
Docker-compose and CKAN 2.9

### ISSUE THREAD

**Issue by guibos** [ckan/ckan#5530]
**CKAN version 2.9**

**Describe the bug**
When docker-compose is up ckan container raise this exception. This only happen in CKAN version 2.9. I think that previous versions of CKAN used to use Jetty version and now is using tomcat version.
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 8, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan          |     invoke(command, command_name, options, args[1:])
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan          |     exit_code = runner.run(args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan          |     result = self.command()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 357, in command
ckan          |     self._load_config(cmd!='upgrade')
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 330, in _load_config
ckan          |     self.site_user = load_config(self.options.config, load_site_user)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 237, in load_config
ckan          |     load_environment(conf.global_conf, conf.local_conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 116, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 130, in load_all
ckan          |     unload_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 183, in unload_all
ckan          |     unload(*reversed(_PLUGINS))
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 211, in unload
ckan          |     plugins_update()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
ckan          |     environment.update_config()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 227, in update_config
ckan          |     search.check_solr_schema_version()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/search/__init__.py", line 291, in check_solr_schema_version
ckan          |     res = urllib2.urlopen(req)
ckan          |   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
ckan          |     return opener.open(url, data, timeout)
ckan          |   File "/usr/lib/python2.7/urllib2.py", line 435, in open
ckan          |     response = meth(req, response)
ckan          |   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
ckan          |     'http', request, response, code, msg, hdrs)
ckan          |   File "/usr/lib/python2.7/urllib2.py", line 473, in error
ckan          |     return self._call_chain(*args)
ckan          |   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
ckan          |     result = func(*args)
ckan          |   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
ckan          |     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
ckan          | urllib2.HTTPError: HTTP Error 404: Not Found

**Steps to reproduce**
docker-compose up

**Additional details**
When I have a while I'll try to fix it.

**Comment by kowh-ai** [comment]
@guibos - I presume you are using the CKAN Docker install without any modifications. The solr image (and container config) hasn't changed, it's still **solr:6.6.5**. 

Iv'e just installed a Docker CKAN 2.9 and run `wget http://solr:8983/solr` on the CKAN container to get a 200 status code. There are a couple of modifications required to get this to work (https://github.com/ckan/ckan/pull/5381) but your error will probably not get resolved by them

**Comment by guibos** [comment]
Thank you @kowh-ai ! This issue is duplicate so, I will close this issue.
