### ISSUE TITLE
"Upgrading Postgres for the CKAN 2.6 release" creates non-SQL ".sql" files

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5545]
**CKAN version**
2.9

**Describe the bug**
[The Upgrading section of the Postgres for the CKAN 2.6 release page of the Maintainer's guide](https://docs.ckan.org/en/2.9/maintaining/upgrading/upgrade-postgres.html#upgrading) is misleading. The first variant of step 12 instructs to create dump files named _backup_ckan.sql_ and _backup_datastore.sql_. Yet these are not SQL files, due to usage of format "c" instructed by `-Fc`.

**Steps to reproduce**
This is not a behavioral bug.

**Expected behavior**
The commands should probably call the files _*.dmp_.

**Additional details**
Note that despite the last paragraph about -Fc, the second variant does not use it.

**Comment by Gauravp-NEC** [comment]
@Chealer @wardi , I have investigate on this issue. In step 12 of "The Upgrading section of the Postgres for the CKAN 2.6 release page of the Maintainer's guide" -Fc option is used to produce backup file in custom dump format i.e., *.dmp . Also I think we need to update the upgrading section of the Postgres for the CKAN 2.9 release in Maintainer's guide.  I am interested to work in this issue. Please assign this issue to me.

**Comment by Gauravp-NEC** [comment]
@wardi @Chealer , I have started working on this issue. At step no. 13 of Maintainer's guide (https://docs.ckan.org/en/latest/maintaining/upgrading/upgrade-postgres.html) I did not find the file "postgis_restore.pl" at the location: /usr/share/postgresql/9.4/contrib/postgis-2.1/postgis.sql and also at step no. 16, I did not find the file "postgis.sql" and "spatial_ref_sys.sql" at same location. Both the steps 13 & 16 are optional.

**Comment by Gauravp-NEC** [comment]
@wardi @Chealer , I have raise the PR #5567 for this issue. I have not updated optional step no 13 & 16. I did not find the found "postgis_restore.pl" for step no. 13 and "postgis.sql" & "spatial_ref_sys.sql" for step no. 16 at location: /usr/share/postgresql/9.4/contrib/postgis-2.1

**Comment by Chealer** [comment]
Thank you @Gauravp-NEC 
The paths to those files depends on the system. Which PostGIS version do you use?

**Comment by Gauravp-NEC** [comment]
@Chealer @wardi , I have updated the optional step no 13 and 16 in PR https://github.com/ckan/ckan/pull/5567

**Comment by Chealer** [comment]
Thank you @Gauravp-NEC 
I did not test the new procedure, but I assume it will fail for those trying step 13, since it works on a file named _backup_ckan.sql_, while step 12 now creates a _backup_ckan.**dmp**_.

Also, it is beyond this ticket's scope, but it is a good idea to rename the page (from the current "Upgrading Postgres for the CKAN 2.6 release"). But I think renaming changing "2.6" with "2.9" can be misleading. I recommend changing it to "2.6 or above", or just "2.6+" ("Upgrading PostgreSQL for CKAN versions 2.6 and above").
