### ISSUE TITLE
Minified Font Awesome CSS file not upgraded in CKAN 2.7.x

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#5557]
**CKAN version**
2.7.8

**Describe the bug**
It seems that the minified font-awesome css (font-awesome.min.css) has not been upgraded during the update: https://github.com/ckan/ckan/commit/973a6e28f25f3661de34d5a658ada2fa64c56783.

**Steps to reproduce**
Install the CKAN 2.7.8, then add any new icons introduced in font-awesome 4.7.0 to any pages. Those new icons will not be shown since the minified font-awesome css is still in [v4.0.3](https://github.com/ckan/ckan/tree/2.7/ckan/public/base/vendor/font-awesome/css).

**Expected behavior**
We need to upgrade the font-awesome.min.css to v4.7.0.

**Additional details**
I also found that there is a font-awesome.css.map file in ckan/ckan/public/base/vendor/font-awesome/css/ for [CKAN >= 2.8](https://github.com/ckan/ckan/tree/2.8/ckan/public/base/vendor/font-awesome/css). Do we need to include that file in CKAN 2.7.x too?

**Comment by Zharktas** [comment]
Fixed for 2.7 in eb402df and 2.8 in 91cafaf.

**Comment by u10313335** [comment]
Thank you all!
