### ISSUE TITLE
Remove rating_create

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5558]
**CKAN version**
2.9

**Describe the bug**
As per #2660, `rating_create` was supposed to be removed and interested users directed to https://github.com/6aika/ckanext-rating.

**Steps to reproduce**
`rating_create` is still available in the API and API Docs - https://docs.ckan.org/en/2.9/api/#ckan.logic.action.create.rating_create

**Expected behavior**
`rating_create` is removed and API Docs updated accordingly with a note mentioning ckanext-rating

**Comment by daminichopra** [comment]
Hi @jqnatividad , I would like to work on this. Please assign this issue to me.

**Comment by amercader** [comment]
@daminichopra you can not be assigned to issues but please go ahead and work on this, thanks a lot!
