### ISSUE TITLE
Ckan2.8.3 production build debug=true Internal server error

### ISSUE THREAD

**Issue by hussnainwithss** [ckan/ckan#5559]
**CKAN version**

**Describe the bug**
Im using LinkDigital's image on aws to deploy Ckan 2.8.3. it uses apache/wsgi(mod_wsgi) to serve ckan in production build. when i set debug = true in the production.ini file the server gives internal error. the error log show blinker is not installed but it is actually installed 

**Steps to reproduce**
- setup Link Digitals AMI on aws ec2 
- do debug = true in /etc/ckan/default/production.ini
- pip install flask_debugtoolbar (if not already installed)
- open the site in browser
- internal server error is given

**Expected behavior**
Site should load completely fine along with the debug toolbar

**Additional details**

**WSGI log**

mod_wsgi (pid=9502): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
    return self.apps[app_name](environ, start_response)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 151, in process_request
    DebugToolbar(real_request, self.jinja_env))
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask_debugtoolbar/toolbar.py", line 23, in __init__
    self.create_panels()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask_debugtoolbar/toolbar.py", line 34, in create_panels
    context=self.template_context)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask_debugtoolbar/panels/template.py", line 37, in __init__
    template_rendered.connect(self._store_template_info)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/signals.py", line 32, in _fail
    raise RuntimeError('signalling support is unavailable '
RuntimeError: signalling support is unavailable because the blinker library is not installed.

**Comment by kowh-ai** [comment]
Hussnain - did you install the packages via dev-requirements.txt? `pip install -r /usr/lib/ckan/default/src/ckan/dev-requirements.txt`

**Comment by hussnainwithss** [comment]
> 
> 
> Hussnain - did you install the packages via dev-requirements.txt? `pip install -r /usr/lib/ckan/default/src/ckan/dev-requirements.txt`

i did and now the site loads but the styles are all messed up. 
this is the httpd log 

[Wed Aug 26 11:32:26.230627 2020] [:error] [pid 27496] [remote 127.0.0.1:296] mod_wsgi (pid=27496): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Wed Aug 26 11:32:26.230669 2020] [:error] [pid 27496] [remote 127.0.0.1:296] Traceback (most recent call last):
[Wed Aug 26 11:32:26.230682 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 409, in streaming_iter
[Wed Aug 26 11:32:26.230703 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     for item in self.application(environ, start_response):
[Wed Aug 26 11:32:26.230708 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Wed Aug 26 11:32:26.230718 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     app_iter = app(environ, wrapper.wrap_start_response)
[Wed Aug 26 11:32:26.230723 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/middleware.py", line 201, in __call__
[Wed Aug 26 11:32:26.230739 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     self.app, environ, catch_exc_info=True)
[Wed Aug 26 11:32:26.230744 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
[Wed Aug 26 11:32:26.230752 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     app_iter = application(environ, start_response)
[Wed Aug 26 11:32:26.230756 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/weberror/evalexception.py", line 251, in __call__
[Wed Aug 26 11:32:26.230764 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     "The EvalException middleware is not usable in a "
[Wed Aug 26 11:32:26.230775 2020] [:error] [pid 27496] [remote 127.0.0.1:296] AssertionError: The EvalException middleware is not usable in a multi-process environment
[Wed Aug 26 11:32:26.384768 2020] [:error] [pid 27497] [remote 127.0.0.1:60] mod_wsgi (pid=27497): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Wed Aug 26 11:32:26.384802 2020] [:error] [pid 27497] [remote 127.0.0.1:60] Traceback (most recent call last):
[Wed Aug 26 11:32:26.384816 2020] [:error] [pid 27497] [remote 127.0.0.1:60]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 409, in streaming_iter
[Wed Aug 26 11:32:26.384836 2020] [:error] [pid 27497] [remote 127.0.0.1:60]     for item in self.application(environ, start_response):
[Wed Aug 26 11:32:26.384841 2020] [:error] [pid 27497] [remote 127.0.0.1:60]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Wed Aug 26 11:32:26.384851 2020] [:error] [pid 27497] [remote 127.0.0.1:60]     app_iter = app(environ, wrapper.wrap_start_response)
[Wed Aug 26 11:32:26.384856 2020] [:error] [pid 27497] [remote 127.0.0.1:60]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/middleware.py", line 201, in __call__
[Wed Aug 26 11:32:26.384864 2020] [:error] [pid 27497] [remote 127.0.0.1:60]     self.app, environ, catch_exc_info=True)
[Wed Aug 26 11:32:26.384869 2020] [:error] [pid 27497] [remote 127.0.0.1:60]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
[Wed Aug 26 11:32:26.384877 2020] [:error] [pid 27497] [remote 127.0.0.1:60]     app_iter = application(environ, start_response)
[Wed Aug 26 11:32:26.384881 2020] [:error] [pid 27497] [remote 127.0.0.1:60]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/weberror/evalexception.py", line 251, in __call__
[Wed Aug 26 11:32:26.384890 2020] [:error] [pid 27497] [remote 127.0.0.1:60]     "The EvalException middleware is not usable in a "
[Wed Aug 26 11:32:26.384901 2020] [:error] [pid 27497] [remote 127.0.0.1:60] AssertionError: The EvalException middleware is not usable in a multi-process environment
[Wed Aug 26 11:32:26.533357 2020] [:error] [pid 27496] [remote 127.0.0.1:296] mod_wsgi (pid=27496): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Wed Aug 26 11:32:26.533394 2020] [:error] [pid 27496] [remote 127.0.0.1:296] Traceback (most recent call last):
[Wed Aug 26 11:32:26.533408 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 409, in streaming_iter
[Wed Aug 26 11:32:26.533429 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     for item in self.application(environ, start_response):
[Wed Aug 26 11:32:26.533435 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Wed Aug 26 11:32:26.533444 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     app_iter = app(environ, wrapper.wrap_start_response)
[Wed Aug 26 11:32:26.533449 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/middleware.py", line 201, in __call__
[Wed Aug 26 11:32:26.533466 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     self.app, environ, catch_exc_info=True)
[Wed Aug 26 11:32:26.533471 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
[Wed Aug 26 11:32:26.533479 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     app_iter = application(environ, start_response)
[Wed Aug 26 11:32:26.533483 2020] [:error] [pid 27496] [remote 127.0.0.1:296]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/weberror/evalexception.py", line 251, in __call__
[Wed Aug 26 11:32:26.533491 2020] [:error] [pid 27496] [remote 127.0.0.1:296]     "The EvalException middleware is not usable in a "
[Wed Aug 26 11:32:26.533502 2020] [:error] [pid 27496] [remote 127.0.0.1:296] AssertionError: The EvalException middleware is not usable in a multi-process environment

**Comment by hussnainwithss** [comment]
> 
> 
> Hussnain - did you install the packages via dev-requirements.txt? `pip install -r /usr/lib/ckan/default/src/ckan/dev-requirements.txt`

https://github.com/ckan/ckan/issues/3771  #3771 this issue explains it that apache does not support debug mode in production environment.

**Comment by Zharktas** [comment]
Documentation was updated a while back that you need single process environment when running in debug mode. https://docs.ckan.org/en/2.9/maintaining/configuration.html#debug

**Comment by hussnainwithss** [comment]
> 
> 
> Documentation was updated a while back that you need single process environment when running in debug mode. https://docs.ckan.org/en/2.9/maintaining/configuration.html#debug

Thank you for the help. i didnt get a look at the new documentation for 2.9

**Comment by kowh-ai** [comment]
You could also shut down Apache altogether and just serve the application without it...let me know if you want help in doing this...

**Comment by hussnainwithss** [comment]
> 
> 
> You could also shut down Apache altogether and just serve the application without it...let me know if you want help in doing this...

i fixed it according to the documentation and its working fine thank you <3
