### ISSUE TITLE
Error running tests: unrecognized arguments: --ckan-ini

### ISSUE THREAD

**Issue by EricSoroos** [ckan/ckan#5570]
**CKAN version**

Ckan 2.9/python 2.7

**Describe the bug**
Followed the directions in the docs to run tests, and got the following error:

```
pytest --ckan-ini=test-core.ini ckan/ ckanext/ 
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --ckan-ini=test-core.ini
  inifile: None
  rootdir: /usr/lib/ckan/default/src/ckan
```

**Steps to reproduce**

* Install ckan into docker container, including requirements-py2.txt and dev-requirements.txt
* Shell in and run `pytest --ckan-ini=test-core.ini ckan/ ckanext/`

**Expected behavior**

Tests to run. 

**Additional details**
The following pytest related packages are installed:
```
pytest --version
This is pytest version 4.6.5, imported from /usr/lib/ckan/default/local/lib/python2.7/site-packages/pytest.pyc
setuptools registered plugins:
  pytest-rerunfailures-8.0 at /usr/lib/ckan/default/local/lib/python2.7/site-packages/pytest_rerunfailures.py
  pytest-cov-2.7.1 at /usr/lib/ckan/default/local/lib/python2.7/site-packages/pytest_cov/plugin.py
  pytest-split-tests-1.0.9 at /usr/lib/ckan/default/local/lib/python2.7/site-packages/pytest_split_tests/__init__.pyc
  pytest-freezegun-0.4.1 at /usr/lib/ckan/default/local/lib/python2.7/site-packages/pytest_freezegun.py
  pyfakefs-3.2 at /usr/lib/ckan/default/local/lib/python2.7/site-packages/pyfakefs/pytest_plugin.py
```

**Comment by EricSoroos** [comment]
Is this perhaps a missing dependency on pytest-ckan?

**Comment by shasan-marsdd** [comment]
having the same issue, cannot set up tests for 2.9.

**Comment by paulmueller** [comment]
I can confirm that ``pytest-ckan`` needs to be installed for this to work. It is missing in https://github.com/ckan/ckan/blob/master/dev-requirements.txt. I get some other strange error when I run it with the ``--ckan-ini=test-core.ini`` option:
```
(default) root@dcor-test:/dcor-repos/ckanext-dcor_schemas# pytest --ckan-ini=test.ini ckanext/dcor_schemas/tests/
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/_pytest/main.py", line 204, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/tests/pytest_ckan/ckan_setup.py", line 22, in pytest_sessionstart
INTERNALERROR>     conf = load_config(session.config.option.ckan_ini)
INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/cli/__init__.py", line 102, in load_config
INTERNALERROR>     loggingFileConfig(filename)
INTERNALERROR>   File "/usr/lib/python3.8/logging/config.py", line 71, in fileConfig
INTERNALERROR>     formatters = _create_formatters(cp)
INTERNALERROR>   File "/usr/lib/python3.8/logging/config.py", line 104, in _create_formatters
INTERNALERROR>     flist = cp["formatters"]["keys"]
INTERNALERROR>   File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
INTERNALERROR>     raise KeyError(key)
INTERNALERROR> KeyError: 'formatters'
```
...but removing it seems to work for me at least for now (``ckan.tests.factories`` can be used and I just started to get going with tests).

**Comment by Sayaka91** [comment]
> I can confirm that `pytest-ckan` needs to be installed for this to work. It is missing in https://github.com/ckan/ckan/blob/master/dev-requirements.txt. I get some other strange error when I run it with the `--ckan-ini=test-core.ini` option:
> 
> ```
> (default) root@dcor-test:/dcor-repos/ckanext-dcor_schemas# pytest --ckan-ini=test.ini ckanext/dcor_schemas/tests/
> INTERNALERROR> Traceback (most recent call last):
> INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/_pytest/main.py", line 204, in wrap_session
> INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
> INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
> INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
> INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
> INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
> INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
> INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
> INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
> INTERNALERROR>     return outcome.get_result()
> INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
> INTERNALERROR>     raise ex[1].with_traceback(ex[2])
> INTERNALERROR>   File "/usr/lib/ckan/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
> INTERNALERROR>     res = hook_impl.function(*args)
> INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/tests/pytest_ckan/ckan_setup.py", line 22, in pytest_sessionstart
> INTERNALERROR>     conf = load_config(session.config.option.ckan_ini)
> INTERNALERROR>   File "/usr/lib/ckan/default/src/ckan/ckan/cli/__init__.py", line 102, in load_config
> INTERNALERROR>     loggingFileConfig(filename)
> INTERNALERROR>   File "/usr/lib/python3.8/logging/config.py", line 71, in fileConfig
> INTERNALERROR>     formatters = _create_formatters(cp)
> INTERNALERROR>   File "/usr/lib/python3.8/logging/config.py", line 104, in _create_formatters
> INTERNALERROR>     flist = cp["formatters"]["keys"]
> INTERNALERROR>   File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
> INTERNALERROR>     raise KeyError(key)
> INTERNALERROR> KeyError: 'formatters'
> ```
> 
> ...but removing it seems to work for me at least for now (`ckan.tests.factories` can be used and I just started to get going with testing my CKAN extensions).

Hi, i get the same error. Did u fix the last error: KeyError: "formatters"? what did happen with logging/config of python 3.8?

**Comment by paulmueller** [comment]
@Sayaka91 I think I just removed the ``--ckan-ini=test-core.ini`` keyword argument and did an ``export CKAN_INI=/etc/ckan/default/test-core.ini`` beforehand.

I am using a vagrant image for testing, references:

- https://github.com/DCOR-dev/ckanext-dcor_schemas/blob/master/vagrant-run-tests.sh
- https://github.com/DCOR-dev/dcor-vagrant

**Comment by frafra** [comment]
What I did to make it work:
- Installed `pytest-ckan`
- Set `CKAN_INI` variable instead of using `--ckan-ini`

If you hit the `KeyError: 'formatters'` issue, it means that the path of your conf file is wrong, or some sections are missing from your conf file (loggers, formatters, ...).

**Comment by nielsaka** [comment]
The [test instructions ](https://docs.ckan.org/en/2.10/contributing/test.html) in the official documentation does not currently reflect this: The need to either install `pytest-ckan` manually or set `CKAN_INI`.
