### ISSUE TITLE
Download options in Datatables_view do not work

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5578]
**CKAN version**
2.9

**Describe the bug**
Using datatables_view as a default resource view, which works well.  Apart from the nicer UI and pagination, one benefit of the view is that you can download a filtered version of the resource (https://github.com/ckan/ckan/pull/4497).  However, none of the datatables_view download buttons work to download the filtered data.

**Steps to reproduce**

1. Add a CSV resource to a dataset
2. Create a datatables resource view (labeled 'Table' in the resource view picklist)
3. Go to resource view and try to use the Download button for any format type
4. A 404 error page replaces the datatables control

**Comment by wardi** [comment]
This sounds like a regression related to the URL generation for these endpoints since the move to flask. https://github.com/ckan/ckan/blob/878dbf6bf2a058de4efa0d8fce9b66e2ef5b7fa3/ckanext/datatablesview/templates/datatables/datatables_view.html#L48 would be the place I would start looking.
