### ISSUE TITLE
jQuery error "Cannot convert object to primitive value"

### ISSUE THREAD

**Issue by clauded** [ckan/ckan#5583]
**CKAN version**
2.8.5

**Describe the bug**
We use some jQuery functions to expand/collapse fields in our CKAN extensions. Since upgrading CKAN from 2.8.4 to 2.8.5 we get an error when clicking on the expand/collapse button ("Cannot convert object to primitive value"). This seems to be related to the update to jQuery 3.5.0 that breaks bootstrap (see https://github.com/jquery/jquery/issues/4665). jQuery 3.5.1 have a fix for this.

**Expected behavior**
Was working in 2.8.4; broken in 2.8.5.

**Additional details**
Workaround : replace jquery.js (and min version as well) with [v3.5.1](https://code.jquery.com/jquery-3.5.1.js) and errors are gone

**Comment by Zharktas** [comment]
JQuery was updated in master and 2.9 to 3.5.1 in #5448, I marked it as backport pending a while back so it will be upgraded in the next 2.7 and 2.8 release.

**Comment by Zharktas** [comment]
Fixed in new patch releases.
