### ISSUE TITLE
CKAN 2.9 Datastore file dump doesnt return file extension

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#5593]
**CKAN version**
2.9

**Describe the bug**
When Datastore is enabled and Resouce is uploaded to Datastore, on Resource page Go to resource/Download button become select box, when User clicks on it, file is being downloaded in an appropriate format, but without the file extension (for example "e854b0dc-fc44-4720-a852-e983351304f8", while should be "e854b0dc-fc44-4720-a852-e983351304f8.csv").

**Expected behavior**
File returned with an appropriate selected format.

**Comment by amercader** [comment]
@Engerrs did you mean to submit a PR for this?

**Comment by jqnatividad** [comment]
Is this the PR?
https://github.com/ckan/ckan/pull/5594

**Comment by shubham-mahajan** [comment]
@amercader PR is already merged against this issue. (https://github.com/ckan/ckan/pull/5604)

**Comment by jqnatividad** [comment]
@shubham-mahajan, just wanted to confirm that #5604 does not fix the file extension problem. It only fixes the url generation coz of the move to flask - the downloaded files still do not have the right file extension and still requires #5594.

**Comment by Engerrs** [comment]
Hi @amercader , I already done a PR (https://github.com/Engerrs/ckan/commit/ac989564a6de366903979fb76c9eddf908506853), it is highlighted under the issue description.

**Comment by shubham-mahajan** [comment]
@Engerrs I have added the comment on the PR. (https://github.com/ckan/ckan/pull/5594#issuecomment-722917754)

**Comment by Engerrs** [comment]
Hi @shubham-mahajan , sorry for the delay. I updated the code.

**Comment by Zharktas** [comment]
Fixed in #5594
