### ISSUE TITLE
how to merge Flask to CKAN

### ISSUE THREAD

**Issue by microshadow** [ckan/ckan#5601]
I have a very simple Flask app, I wanted to add some functionality of this app to our CKAN project. How to do that?
Is that like just copy and paste some existing code from me to somewhere in CKAN project?
Thanks a lot!

**Comment by smotornyuk** [comment]
Yes, this can be done in two steps:
1. Move all the application logic into Flask's Blueprints
2. Return those blueprints as a list from your CKAN extension that implements IBlueprint interface: 
```python
import ckan.plugins as p
from ckanext.my_extension.flask_blueprints import blueprint_a, blueprint_b

class MyExtensionPlugin(p.SingletonPlugin):
    p.implements(p.IBlueprint)
    def get_blueprint(self):
         return [blueprint_a, blueprint_b]
```
