### ISSUE TITLE
Data Dictionary Update Bug

### ISSUE THREAD

**Issue by debbielee1996** [ckan/ckan#5602]
**CKAN version**
2.8

**Describe the bug**
Data dictionary not updating properly.

**Steps to reproduce**
Example of inputting labels and descriptions:
![image](https://user-images.githubusercontent.com/62943444/93161993-58ee3900-f746-11ea-982a-e3935d81d86a.png)

Output:
![image](https://user-images.githubusercontent.com/62943444/93162031-70c5bd00-f746-11ea-95b6-8236a70926a2.png)

The description from the first field is being inputted into the description in the second field.

Which code is the logic of the editing of the field inputs? The front end code seems fine...

In addition, where in the postgresql database are the label and description being stored? I can't seem to find them.

**Comment by debbielee1996** [comment]
I found that its got to do with the way the data_dict is being stored. In /ckan/lib/default/src/ckan/ckanext/datastore/dictionary.html, under the dictionary method, I printed out the info, fields and data variables and found that the structure is slightly off.

![image](https://user-images.githubusercontent.com/62943444/93166047-3bbe6800-f750-11ea-9c35-f414164c51d9.png)
![image](https://user-images.githubusercontent.com/62943444/93166072-47aa2a00-f750-11ea-9078-7a3e83c243c7.png)
![image](https://user-images.githubusercontent.com/62943444/93165995-15003180-f750-11ea-8de7-65233db56abf.png)

As you can see, for the first 2 elements in the tuple, it will always have 1 missing label/notes sub element. Where can I change the structure of this tuple?

**Comment by debbielee1996** [comment]
I think I am nearing... I found out its due to the extra variable _id that always appear in a data table. How do I remove it?
![image](https://user-images.githubusercontent.com/62943444/93183806-09236800-f76e-11ea-89c8-9822fe6a6d14.png)

**Comment by debbielee1996** [comment]
Resolved it. Added the following code lines to /ckan/lib/default/src/ckan/ckanext/datastore/controller.py

![image](https://user-images.githubusercontent.com/62943444/93191816-8bfcf080-f777-11ea-9867-2662dd127d04.png)

**Comment by wardi** [comment]
@debbielee1996 thank you for this, are you using 2.8.5? There was a change to unflatten in this release that might have caused this to break. we have a patch that works around the issue for extras https://github.com/ckan/ckan/pull/5546/files but this sounds like we should fix unflatten instead of chasing the bugs created in other parts of the code.

**Comment by debbielee1996** [comment]
Hi wardi, I installed CKAN 2.8.5. Will the patch you mentioned resolve the unflatten issue? Additionally, do you know where I can view the stored data dictionary in the postgresql database? I can't seem to find it.

**Comment by jqnatividad** [comment]
This also seems to break how type override in data dictionary works, with the override not being applied properly after reuploading to the datastore.

**Comment by wardi** [comment]
yes, #5611 is an important fix, we need to get it out in a release soon
