### ISSUE TITLE
Built-in resource view plugins need to be documented

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5605]
**CKAN version**
2.9

**Describe the bug**
There are additional built-in resource views (i.e. datatables, audio, video) that are not properly documented.

https://docs.ckan.org/en/2.9/maintaining/data-viewer.html?highlight=resource%20view#available-view-plugins

**Expected behavior**
Expanded resource view documentation.

**Comment by amercader** [comment]
Done in master (future 2.10): http://docs.ckan.org/en/latest/maintaining/data-viewer.html
