### ISSUE TITLE
Unable to update a ckan logic method via an extension

### ISSUE THREAD

**Issue by debbielee1996** [ckan/ckan#5606]
**CKAN version**
2.8.5

**Describe the bug**
Tried building an extension following https://docs.ckan.org/en/2.8/extensions/tutorial.html 

My use case is I am trying to call package_show and filter out the results. However, in plugin.py file, if I try to do the following:

def package_show(context, data_dict=None):
    initial_results = package_show(context, data_dict)
    # do some filtering on initial_results
    return final_results

I will get an error maximum recursion error. How do I get over this? Or do I edit package_show method directly in the ckan/logic/action/get.py file?

**Comment by Zharktas** [comment]
You are calling the function which you just defined so it will recurse itself indefinitely until it fails on maximum recursion error. In python terms you should have different names for them, but ckan with its extensions offer interfaces to modify results. You could plug into https://docs.ckan.org/en/2.9/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IPackageController.after_show which is called as the last thing in package_show https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L1049

Alternatively if you just want to modify the api, you could use chained actions https://docs.ckan.org/en/2.9/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IActions.get_actions, example of this can be found in this test https://github.com/ckan/ckan/blob/8f271bfe3eccaa83a419ee55e3e35042d1196c5a/ckanext/datastore/tests/test_chained_action.py#L18..L28

**Comment by debbielee1996** [comment]
Alright, thank you. Can I check, let's say I want to add another layer of authentication to package_search, how do I go about doing it? I think I shouldn't place the logic in the package_search action, but rather in the IAuth side of package_search. My use case is that I want to query another table I created on whether a particular user has the rights to view a particular dataset or not. I could only find a documentation that overrides the original IAuth function of a get action, but not add on to it.

**Comment by debbielee1996** [comment]
I found that it has got to do with this method highlighted below, is there any way that I can add more dataset labels in order for me to filter by the package_id and resource_id going forward?

![image](https://user-images.githubusercontent.com/62943444/93552221-7fa8ab80-f9a2-11ea-9c66-43c8412b5dd4.png)

**Comment by Zharktas** [comment]
You can extend them via [IPermissionLabels](https://docs.ckan.org/en/2.9/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IPermissionLabels).

**Comment by debbielee1996** [comment]
I have added new labels to the dataset_labels, however, where do I change the code that searches for datasets in solr that has a specific package_id? I can't find the code for that...

**Comment by debbielee1996** [comment]
Question - how do I load the new extension?
![image](https://user-images.githubusercontent.com/62943444/93565953-c73d3080-f9be-11ea-8c53-98ce42f287ea.png)

Slightly down the code I see this:
![image](https://user-images.githubusercontent.com/62943444/93565991-d7551000-f9be-11ea-8a81-f936e41a924b.png)

But it doesn't help with my own IPermissionLabels plugin...

**Comment by Zharktas** [comment]
Permissions are added to solr during indexing https://github.com/ckan/ckan/blob/6d3453396359c9fc401e4f60383ee1b7f9e05885/ckan/lib/search/index.py#L294 But since this issue is now more of an support request than fault in ckan codebase, i'm closing this and guiding you to either [gitter chat](https://gitter.im/ckan/chat) or [mailing list](https://groups.google.com/a/ckan.org/forum/#!forum/ckan-dev)

**Comment by debbielee1996** [comment]
alright thanks, I shall seek help there then :)
