### ISSUE TITLE
CKAN 2.9.0 can't create a sysadmin user – Command 'sysadmin' not known

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckan#5621]
**CKAN version**: 2.9.0 + patch for Docker install (PR #5381)

**Describe the bug**
When first installing CKAN and trying to create the first sysadmin user, I get a message "Command 'sysadmin' not known (you may need to run setup.py egg_info)" instead.

**Steps to reproduce**
I'm following the instructions in the documentation for [installing with Docker Compose](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html). I initially came across bug #5572, as the CKAN container wouldn't work, then applied the patch [as suggested by mabah-mst](https://github.com/ckan/ckan/issues/5572#issuecomment-693263908) to fix it:

```
git checkout tags/ckan-2.9.0
#Apply fix to get CKAN to start at all in the docker-compose: https://github.com/ckan/ckan/pull/5381
git diff 9abeaa1b7d2f6539ade946cc3f407878f49950eb^ 9abeaa1b7d2f6539ade946cc3f407878f49950eb | git apply
```

Then, skip step 3, as we don't need to set up and enable the data store and data pusher.

We get to step 4, [create CKAN admin user](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html#create-ckan-admin-user).

However, when running the suggested command, we get the error message saying "Command 'sysadmin' not known".

```
$ docker exec -it ckan /usr/local/bin/ckan-paster --plugin=ckan sysadmin -c /etc/ckan/production.ini add johndoe
Command 'sysadmin' not known (you may need to run setup.py egg_info)
Known commands:
  create       Create the file layout for a Python distribution
  exe          Run #! executable files
  help         Display help
  make-config  Install a package and create a fresh config file/directory
  points       Show information about entry points
  post         Run a request for the described application
  request      Run a request for the described application
  serve        Serve the described application
  setup-app    Setup an application, given a config file
```

**Expected behavior**
A new sysadmin user is expected to be created, instead of displaying this error.

**Additional information***
I also tried entering the container and enabling the Python environment first, but the result is the same.

```
docker exec -it ckan bash
cd /usr/lib/ckan/
source venv/bin/activate
/usr/local/bin/ckan-paster --plugin=ckan sysadmin -c /etc/ckan/production.ini add johndoe
```

**Comment by tino097** [comment]
@augusto-herrmann Have you tried to use the new CLI commands ? https://docs.ckan.org/en/2.9/changelog.html#migration-notes

**Comment by kowh-ai** [comment]
@augusto-herrmann - Try this:

`docker exec -it ckan bash`
`cd /usr/lib/ckan/`
`source venv/bin/activate`
**`ckan -c /etc/ckan/production.ini sysadmin add johndoe email=johndoe@localhost name=johndoe`**

The CKAN Docker install is getting re-written which will include this documentation

**Comment by augusto-herrmann** [comment]
That worked! Thank you, @kowh-ai ! :partying_face:
