### ISSUE TITLE
Dataset changes list fails for datasets without tags

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan#5627]
**CKAN version**
2.9

**Describe the bug**
Dataset changes listing in activity stream fails when dataset has no tags

**Steps to reproduce**
Create a dataset then update it making a few changes to create multiple versions, but do not add any tags
Browse to the activity stream and click on the changes link

**Expected behavior**
The details on the changes should be listed, but instead a KeyError is generated. 

**Additional details**
End of stack trace showing relevant files / lines

```
  File "/usr/lib/ckan/default/src/ckan/ckan/templates/package/snippets/change_item.html", line 3, in top-level template code
    {% set changes = h.compare_pkg_dicts(activity_diff.activities[0].data.package, activity_diff.activities[1].data.package, activity_diff.activities[0].id) %}
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 2849, in compare_pkg_dicts
    check_metadata_changes(change_list, old, new)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/changes.py", line 340, in check_metadata_changes
    old_tags = {tag['name'] for tag in old['tags']}
```

I observed this on a system with multiple dataset schemas, some of which use custom vocabularies. Although this behavior is present on a generic schema that matches the default CKAN format.

**Comment by amercader** [comment]
Fixed in #5573
