### ISSUE TITLE
jQuery JavaScript Library version missmatch between full and minified variant

### ISSUE THREAD

**Issue by xellos866** [ckan/ckan#5631]
**CKAN version**

i have checked the following versions:
* Ckan 2.9.0 (e7e2d49)
* Ckan 2.8.5 (797c698)

**Describe the bug**

The following jQuery JavaScript Library versions are missmatching:

* path: `ckan/ckan/public/base/vendor/`

* Ckan 2.9.0 (e7e2d49)
  * `jquery.js` (full): `3.5.1`
  * `jquery.min.js` (minified): `3.4.1`

* Ckan 2.8.5 (797c698)
  * `jquery.js` (full): `3.5.0`
  * `jquery.min.js` (minified): `3.2.1`

**Steps to reproduce**

Check your served jQuery file (i.e. via Chrome Inspect Tool) and check the version (minified version is served in production) or just view the files in the project.

**Expected behavior**

The versions of the full and minified version are the same: `3.5.1`

**Comment by Zharktas** [comment]
Fixed for 2.7 in eb402dfa79d5c757e7553c3fe22a7ac93bddd543, 2.8 in 91cafafac086a1866404a2901cb66cb9095723d4 and for 2.9/master there's related pull request.

**Comment by xellos866** [comment]
Hello Zharktas,

thank you for your fast reply. 

I checked your linked commit and the current branch `dev-v2.8` (6be3b95) and the noted issue/ mismatch is still given:

* `ckan/ckan/public/base/vendor/jquery.js` -> `v3.5.1`
* `ckan/ckan/public/base/vendor/jquery.min.js` -> `v3.2.1`

The minified library is also not in your PR. Was the behaviour changed which library is served?

greetings

**Comment by Zharktas** [comment]
@xellos866 you are correct, the files in vendor root folder weren't minified, only the files in subdirectories. Thanks for actually verifying it. I'll fix it soonish.

**Comment by Zharktas** [comment]
Updated now in https://github.com/ckan/ckan/commit/c5bb5fc0a81f7a229ed0cb0a733440197e0d979c for 2.7 and in https://github.com/ckan/ckan/commit/f6c0013e6ea6064e80137e548accd82913159c9d for 2.8

**Comment by xellos866** [comment]
Hello Zharktas,

thanks again for the fast reply and the libraries look good - have a nice week.
