### ISSUE TITLE
FileStore API documentation: what is file() ?

### ISSUE THREAD

**Issue by maxclac** [ckan/ckan#5652]
Hi!
I am trying to test the FileStore API as presented there:
[https://docs.ckan.org/en/latest/maintaining/filestore.html]

While trying to create a new resource with the piece of code on the webpage:
```
import requests
requests.post('http://0.0.0.0:5000/api/action/resource_create',
              data={"package_id":"my_dataset"},
              headers={"X-CKAN-API-Key": "21a47217-6d7b-49c5-88f9-72ebd5a4d4bb"},
              files=[('upload', file('/path/to/file/to/upload.csv'))])
```
I noticed that 'file' is actually not defined and I get an error message:
```
Traceback (most recent call last):
  File "requests_test.py", line 5, in <module>
    files=[('upload', file('test.csv'))])
NameError: name 'file' is not defined
```

What is then this 'file' function?

Thanks!

**Comment by textninja** [comment]
I wonder if it would be clearer if the docs said <code>open('<strong>/path/to/file/to/upload.css</strong>', 'rb')</code> instead.

**Comment by maxclac** [comment]
Thanks!
