### ISSUE TITLE
Datastore/datapusher Authorization Error (Ckan 2.9 package install on Ubuntu 20.04)

### ISSUE THREAD

**Issue by abedkhooli** [ckan/ckan#5657]
I made a fresh package install on Ubuntu 20.04.1 LTS, set up filestore, datastore and datapusher (installed with Ckan, just config in ckan.ini). Everything on the same server. 
If I add a new resource, the dataproxy tries to display it (if not overloaded). The status under the DataStore tab shows "pending" and after timeout (1800 sec), the log shows:
```Error: Access denied HTTP status code: 403 Requested URL: http://www.opendata.ps/api/3/action/resource_show Response: {"help": "http://www.opendata.ps/api/3/action/help_show?name=resource_show", "error": {"__type": "Authorization Error", "message": "Access denied"}, "success": false}```
If I trigger manual submit (Upload to DataStore button), I get:
```Error: File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/apscheduler/scheduler.py", line 512, in _run_job retval = job.func(*job.args, **job.kwargs) File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 336, in push_to_datastore resource = get_resource(resource_id, ckan_url, api_key) File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 282, in get_resource r = requests.post(url, File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/api.py", line 119, in post return request('post', url, data=data, json=json, **kwargs) File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/sessions.py", line 530, in request resp = self.send(prep, **send_kwargs) File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/sessions.py", line 643, in send r = adapter.send(request, **kwargs) File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) ConnectionError(MaxRetryError("HTTPConnectionPool(host='www.opendata.ps', port=80): Max retries exceeded with url: /api/3/action/resource_show (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a794cb3a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"))```
If I resubmit from command line: `sudo ckan -c /etc/ckan/default/ckan.ini datapusher resubmit` I get
Submitting 1 datastore resources Submitting 414d7bd7-f0ae-4b44-9abc-71bb0cf3cd2b...Traceback (most recent call last): File ```"/usr/lib/ckan/default/bin/ckan", line 11, in <module> .... File "/usr/lib/ckan/default/src/ckan/ckanext/datapusher/logic/action.py", line 53, in datapusher_submit p.toolkit.check_access('datapusher_submit', context, data_dict) File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 313, in check_access raise NotAuthorized(msg) ckan.logic.NotAuthorized```
Another error after uploading a new resource under a new dataset and waiting too long:
`Error: Process completed but unable to post to result_url`  
Here are relevant parts from config file (ckan.ini). I should mention that pass in 
ckan.datastore.read_url = postgresql://datastore_default:pass@localhost/datastore_default 
has '@' sign in the middle - just in cases it could confuse where server name (host) starts.
```
[server:main]
use = egg:Paste#http
host = 0.0.0.0
port = 5000
...
ckan.site_url = http://www.opendata.ps
...
ckan.site_id = default
solr_url = http://127.0.0.1:8983/solr
...
ckan.plugins = stats text_view image_view recline_view datastore datapusher
...
ckan.storage_path = /var/lib/ckan/default
ckan.max_resource_size = 10
ckan.max_image_size = 2
...
ckan.datapusher.formats = csv xls xlsx tsv application/csv application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
ckan.datapusher.url = http://127.0.0.1:8800/
ckan.datapusher.assume_task_stale_after = 1800
...
ckan.jobs.timeout = 180```

** I changed the datastore password and removed the at sign, so that was not the issue.

**Comment by kowh-ai** [comment]
@abedkhooli - Iv'e been looking at your issue (plus the extra info you have provided on the ckan gitter chat)and it looks to me like some sort of internal (application layer) networking issue...Can you ping/access all systems on the internal VM? If you run an `nslookup opendata.ps` and `nslookup www.opendata.ps` do they both resolve to `213.244.123.83` ?

**Comment by abedkhooli** [comment]
Thanks @kowh-ai for looking into the issue. Yes, both nslookups resolve to 213.244.123.83 
I also tried to resubmit from terminal:
`(default) open-data@opendata:~$ ckan -c /etc/ckan/default/ckan.ini datapusher resubmit`
and got this:
```
Submitting 1 datastore resources
Submitting 414d7bd7-f0ae-4b44-9abc-71bb0cf3cd2b...Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datapusher/cli.py", line 46, in resubmit
    _submit(resource_ids)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datapusher/cli.py", line 98, in _submit
    if datapusher_submit({u'user': user[u'name']}, data_dict):
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datapusher/logic/action.py", line 53, in datapusher_submit
    p.toolkit.check_access('datapusher_submit', context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 313, in check_access
    raise NotAuthorized(msg)
ckan.logic.NotAuthorized
```

**Comment by abedkhooli** [comment]
Update: upgraded to 2.9.1 but did not resolve the issue. 
after update (/var/log/ckan/ckan-datapusher.stderr.log - restarted uwgsi and ngnx):
`detected binary path: /usr/lib/ckan/default/bin/uwsgi`
`!!! no internal routing support, rebuild with pcre support !!!`
...
`*** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers
 *** `
Uploaded a new resource as org admin:
```
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x56450850ff30 pid: 947 (default app)
spawned uWSGI master process (pid: 947)
spawned uWSGI worker 1 (pid: 1063, cores: 1)
spawned uWSGI http 1 (pid: 1064)
[pid: 1063|app: 0|req: 1/1] 127.0.0.1 () {36 vars in 427 bytes} [Thu Oct 22 07:28:06 2020] POST /job => generated 717 bytes in 31 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 1063|app: 0|req: 2/2] 127.0.0.1 () {36 vars in 537 bytes} [Thu Oct 22 07:30:05 2020] GET /job/8d792656-716a-4965-9557-6abc60f1f764 => generated 666 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 1063|app: 0|req: 3/3] 127.0.0.1 () {36 vars in 537 bytes} [Thu Oct 22 07:31:55 2020] GET /job/8d792656-716a-4965-9557-6abc60f1f764 => generated 666 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 1063|app: 0|req: 4/4] 127.0.0.1 () {36 vars in 537 bytes} [Thu Oct 22 07:44:29 2020] GET /job/8d792656-716a-4965-9557-6abc60f1f764 => generated 666 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 1063|app: 0|req: 5/5] 127.0.0.1 () {36 vars in 537 bytes} [Thu Oct 22 07:51:04 2020] GET /job/8d792656-716a-4965-9557-6abc60f1f764 => generated 1005 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)
```
in UI:
```Error: Access denied
HTTP status code: 403
Requested URL: http://www.opendata.ps/api/3/action/resource_show
Response: {"help": "http://www.opendata.ps/api/3/action/help_show?name=resource_show", "error": {"__type": "Authorization Error", "message": "Access denied"}, "success": false}```
After a while, manual trigger from UI:
```
[pid: 1063|app: 0|req: 6/6] 127.0.0.1 () {36 vars in 427 bytes} [Thu Oct 22 08:46:31 2020] POST /job => generated 717 bytes in 20 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 336, in push_to_datastore
    resource = get_resource(resource_id, ckan_url, api_key)
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 288, in get_resource
    check_response(r, url, 'CKAN')
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 152, in check_response
    raise HTTPError(
datapusher.jobs.HTTPError: <unprintable HTTPError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 340, in push_to_datastore
    resource = get_resource(resource_id, ckan_url, api_key)
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 288, in get_resource
    check_response(r, url, 'CKAN')
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 152, in check_response
    raise HTTPError(
datapusher.jobs.HTTPError: <unprintable HTTPError object>
[pid: 1063|app: 0|req: 7/7] 127.0.0.1 () {36 vars in 536 bytes} [Thu Oct 22 08:46:31 2020] GET /job/1aabf8ce-b8a0-45b6-a095-3bb29a0c196c => generated 666 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 1063|app: 0|req: 8/8] 127.0.0.1 () {36 vars in 537 bytes} [Thu Oct 22 08:49:36 2020] GET /job/1aabf8ce-b8a0-45b6-a095-3bb29a0c196c => generated 666 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
```
After 20 min in UI: `Error: Access denied` as above.

**Comment by abedkhooli** [comment]
Closing: I deleted the 'default' user not knowing it is used for jobs/extensions. Used an update query (sysadmin add won't work) from terminal to set the status to 'active'.

**Comment by evaleries** [comment]
I think CKAN must add this problem to the documentation. No one know what's the effect from deleting "default" user.
