### ISSUE TITLE
Unflatten changes in navl break data dictionaries, harvest etc.

### ISSUE THREAD

**Issue by mbocevski** [ckan/ckan#5669]
**CKAN version**
all

**Describe the bug**
Due to changes introduced in #5444 caused by issue #5443, editing data dictionaries in datastore, as well as editing datasets when using harvest is broken. It's a bit unclear why this change was introduced, can we revert back the change so that this gets in the next patch release?

**Steps to reproduce**
Upload a resource to datastore, edit the data dictionary.

**Expected behavior**
Data dictionary should be properly edited with the values from the user.

**Additional details**
n/a

**Comment by amercader** [comment]
The unflatten functions were patched in https://github.com/ckan/ckan/pull/5611, which will included in next week's patch releases

**Comment by mbocevski** [comment]
Thanks @amercader. I tried #5611 and it works fine, I'll close this issue as resolved in upcoming releases.
