### ISSUE TITLE
Is there any way to replace  "ckan_storage_path =/var/lib/ckan/default" with db?

### ISSUE THREAD

**Issue by Ajaysamdyan** [ckan/ckan#5680]
**CKAN Version 2.7.2**

Is it possible to share filestore data between clusters using a method other than file sharing (NAS). (DB etc.)
Moreover, Is there any way to replace the file store path "ckan.storage_path = /var/lib/ckan/default" with db etc. (any other file storing method).

Please let me know , if there is any query.

**Comment by wardi** [comment]
The best extension for storing files is https://github.com/TkTech/ckanext-cloudstorage
