### ISSUE TITLE
2.9.1 requirements files still uses click v6.7

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5681]
**CKAN version**
2.9.1

**Describe the bug**
2.9.1 requirements files still refer to click v6.7 and not v7.1.2 and causes a dependency error. 

**Steps to reproduce**
Upgrade a source install per https://docs.ckan.org/en/2.9/maintaining/upgrading/upgrade-source.html

**Expected behavior**
The proper version of click is installed.

**Comment by smotornyuk** [comment]
I've added backport labels to #5539 so this issue will be solved by v2.9.2
