### ISSUE TITLE
Recreate removed stats functionality using Activity Streams

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5684]
**CKAN version**
2.9.1

**Describe the bug**
When Revisions were deprecated, some dependent code in stats needed to be removed (#5215).  However, these stats are necessary for the effective maintenance of CKAN installations by sysadmins/org admins - specifically:
 - most_edited
 - new_packages_by_week
 - deleted_packages_by_week
 - num_packages_by_week
 - most_edited_by_week

**Steps to reproduce**
Go to `/stats` page.

**Expected behavior**
The detailed stats are restored by using activity streams.

**Comment by Gauravp-NEC** [comment]
@jqnatividad @smotornyuk , I am interested to work on this issue. In this issue I understand that stats functionality needs to be recreated and rendered to activity stream. Please confirm my understanding. Thankyou : )

**Comment by smotornyuk** [comment]
No. Stats functionality just needs to be recreated. Just forget about activity streams. 

### stats functionality needs to be recreated SOMEHOW and rendered exactly as before(as much as possible)

**Comment by Gauravp-NEC** [comment]
@smotornyuk @jqnatividad , I have investigated the source code of stats (2.8 and 2.9). I am stuck at what to use in place of revisions. I am keeping this on hold from my end.

**Comment by smotornyuk** [comment]
Use activities instead of revisions

**Comment by Gauravp-NEC** [comment]
@smotornyuk, Do I need to develop stats functionality here https://github.com/ckan/ckan/blob/master/ckan/views/dataset.py#L1127-L1166 and render it to  https://github.com/ckan/ckan/blob/master/ckanext/stats/templates/ckanext/stats/index.html? Please confirm my understanding. Thanks :)

**Comment by smotornyuk** [comment]
> Do I need to develop stats functionality here [link to dataset blueprint]

No, `stats` has dedicated [blueprint](https://github.com/ckan/ckan/blob/master/ckanext/stats/blueprint.py)


> render it to [link to stats template]

yes
