### ISSUE TITLE
Configuring CKAN FileStore for CKAN Docker installation.

### ISSUE THREAD

**Issue by Souradeep2304** [ckan/ckan#5688]
I have successfully installed ckan docker and now I am trying to setup filestore using the following link: https://docs.ckan.org/en/latest/maintaining/filestore.html#setup-file-uploads

I am stuck on the part of giving permission. Is there is something specific we need to do for the docker installation process or we can ignore this?

I wanted to know because I am trying to install ckanext-cloudstorage extension which needs the Ckan filestore to be setup.

**Comment by amercader** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://groups.google.com/a/ckan.org/forum/#!forum/ckan-dev) or the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Thanks!
