### ISSUE TITLE
Update jquery-fileupload

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5692]
**CKAN version**
2.9.1

**Describe the bug**
jquery-fileupload was added Jul 2012, ~version 6.9.  It is now at version 10.31.  Since it was bundled, several vulnerabilities have been reported:

https://github.com/blueimp/jQuery-File-Upload/blob/master/VULNERABILITIES.md
https://blogs.akamai.com/sitr/2018/10/an-update-on-the-jquery-file-upload-vulnerability.html

**Expected behavior**
bundled jquery-fileupload is updated to the latest release.  

Great opportunity to add resumable, chunked uploads with progress bars, along with large file uploads as well.  Right now, even if you configure `ckan.max_resource_size`  and nginx for large file uploads, large file uploads are still not reliable for various reasons (timeouts, no UI/UX feedback indicating file is being uploaded, etc.)

#2368
#5119 
#4011

**Comment by Zharktas** [comment]
JQuery-fileupload is actually updated in 2.9 https://github.com/ckan/ckan/blob/2.9/package.json#L6 to at least 10.8.0

**Comment by jqnatividad** [comment]
Thanks @Zharktas! Sorry to have missed that one...

Will close this and just reopen #2368 now that jquery-fileupload has been updated.
