### ISSUE TITLE
Ckan Azure Blobs Storage

### ISSUE THREAD

**Issue by Souradeep2304** [ckan/ckan#5694]
I have installed CKAN using docker on my vm. Now I wanted to use the Azure Blob Storage driver in my Ckan inorder to put resources directly in my storage account container. How do I install this driver with the script being given in https://libcloud.readthedocs.io/en/latest/storage/drivers/azure_blobs.html. I am not sure what steps are to be followed for running this script("where and how")

**Comment by jqnatividad** [comment]
@Souradeep2304 check out https://github.com/TkTech/ckanext-cloudstorage.

Also, we primarily use GH issues for bug reports.  If you need further assistance, use https://gitter.im/ckan/chat or the mailing list.

**Comment by pdelboca** [comment]
@Souradeep2304 there is also some new extensions to cover this requirement:

- https://github.com/datopian/ckanext-blob-storage for resources
- https://github.com/datopian/ckanext-asset-storage for static assets

This extensions provide some extra features like direct to cloud upload which may be handy for some scenarios.
