### ISSUE TITLE
Very high render times on resource addition and updates

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#5713]
**CKAN version**

CKAN 2.8.4

**Describe the bug**

Updating resources, or adding resources, for a dataset that already has a large number of resources, is unmanageably slow.

**Steps to reproduce**

- Create a dataset with the resources from https://www.data.qld.gov.au/dataset/ambient-estuarine-water-quality-monitoring-data-near-real-time-sites-2012-to-present-day
- Edit and save a resource

**Expected behavior**

Resources should update within a few seconds.

**Additional details**

We recently installed the ckanext-archiver, ckanext-report, and ckanext-qa extensions; it is possible that there is an interaction with these extensions that is causing or exacerbating the problem.

Debugging suggests that the slowness is occurring in `ckan/logic/action/update.py`, within `package_update`, when generating a new revision. This may be indicative of a database deadlock.

**Comment by ThrawnCA** [comment]
I think the fundamental issue here is that updating a resource triggers an update at the package level, which means that any package with multiple resources has the potential for database lock contention. As the number of resources increases, and/or the number of clients increases (eg ckanext-archiver, ckanext-xloader, ckanext-qa), the contention gets worse.

**Comment by Zharktas** [comment]
Package_update has known scaling issues as it validates all the resources even though the user is modifying only one of them, but usually the performance becomes an issue after hundreds of resources in a single dataset. In my opinion if the those extensions are downloading all the resources every time, that should be fixed in the extensions, at least archiver and qa hasn't received lot of interest lately as I haven't had the need to respond to issues as maintainer of those extensions.

**Comment by ThrawnCA** [comment]
@Zharktas I think it's not exactly a bug in one extension, more like the straw that broke the camel's back.

> usually the performance becomes an issue after hundreds of resources in a single dataset.

With extensions that download the file, like XLoader and Archiver, the file size might make a difference to how many resources you can have before you run into problems. Eg the linked dataset that's having trouble has about two dozen resources, but each one is several megabytes of CSV.

It might also be affected by having multiple clients consuming from the job queue; that increases the scope for lock contention. We're running four clients (looking at reducing that, actually, but that's how it is for now).
