### ISSUE TITLE
Datapusher being triggered before file is uploaded (update)

### ISSUE THREAD

**Issue by shubham-mahajan** [ckan/ckan#5727]
**CKAN version**
v2.9, 2.8, 2.7

**Describe the bug**
The Datapusher is triggered before the file is uploaded and causing the file to use the old URL and the new data is not uploaded to filestore until clicked manually

**Steps to reproduce**
1. Create a resource
2. Check the preview
3. Update the resource with a new file.
4. The preview is same.
5. Click `Upload to Datapusher`. The resource will be updated

**Expected behavior**
The data from the new file should be updated to the datastore

**Additional details**

We can fix this by removing the `notify` method and using the `after_update` hook of the resource.

`notify` is triggered as soon the URL is changed and updated in DB and not committed to SOLR yet and the `resource_show` method use the SOLR to fetch the data so the datapusher is fetching from the old URL instead of new URL or a new resource

**Comment by duttonw** [comment]
would this also affect xloader?

**Comment by shubham-mahajan** [comment]
@duttonw I am not sure

**Comment by Gauravp-NEC** [comment]
@shubham-mahajan , I am interested to work on this issue. I have tried to reproduce this issue on CKAN 2.9.2 , but this issue is not reproduced in my environment. It is working as per expected behavior.

**Comment by shubham-mahajan** [comment]
@Gauravp-NEC Create a resource and upload a CSV, check the preview.

Now upload a completely different CSV and check the resource preview, it will not be updated until you manually click the `Upload the Datapusher`

**Comment by Gauravp-NEC** [comment]
@shubham-mahajan , I tried the same, but again this issue is not reproduced in my environment.
