### ISSUE TITLE
Update Theming for new resource in Ckan

### ISSUE THREAD

**Issue by Souradeep2304** [ckan/ckan#5728]
I have followed the steps from the documentation for creating new custom fields in ckan for create resource form, now what I want to do is add some instruction regarding the same field in the left nav:
![image](https://user-images.githubusercontent.com/36326807/98510323-e488cf80-2288-11eb-8360-570420059ab4.png)
Or somewhere below the field like it has for Format field:
![image](https://user-images.githubusercontent.com/36326807/98510372-ff5b4400-2288-11eb-939c-c7773d926de0.png)

Is there any way way to do so ?

**Comment by amercader** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://groups.google.com/a/ckan.org/forum/#!forum/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Thanks!
