### ISSUE TITLE
Update the 420x220 image in Home Page - Dockerized CKAN

### ISSUE THREAD

**Issue by Souradeep2304** [ckan/ckan#5730]
I am able to change featured organizations and groups in CKAN but I am not able to change this image that pops up in the home screen, it says 420x220. How can I change this in case of the Dockerized version of Ckan? I cant find the relevant content in the CKAN Documentation, any help would be appreciated. Also I don't see any option in the admin config.

**Comment by amercader** [comment]
Hi, thanks for submitting your issue. To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://groups.google.com/a/ckan.org/forum/#!forum/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Thanks!
