### ISSUE TITLE
Translation missing for "Data explorer" in reclineview

### ISSUE THREAD

**Issue by J-bytes** [ckan/ckan#5732]
**CKAN version=2.8.6**

**Describe the bug**
When switching to the french language, the tab name "data explorer on a resource preview page is not translated

**Steps to reproduce**
1. Installing ckan from source
2. Set up a dataset with a previewable format (e.g csv)
3. preview the data 
4. Select the french language by changing the url t0 http://XXX.X.X.X:XXXXfr/XXXXXXX

**Expected behavior**
The tab name shoud be translated to something like "Explorateur de données"

**Comment by amercader** [comment]
You are right, the "Data Explorer" string [here](https://github.com/ckan/ckan/blob/f6ebeb5a581e7550bc8f2c5b3bf59343b1692602/ckanext/reclineview/plugin.py#L109) and all the the `title` properties of the other plugins should be wrapped in the underscore function to make them translatable, eg `'title': _('Data Explorer')`

Do you want to submit a pull request for this?

**Comment by Gauravp-NEC** [comment]
@amercader , I have wrapped the title property of recline_view and other plugins in the underscore function to make them translatable but getting the below NameError.
 ![Capture](https://user-images.githubusercontent.com/66116382/98807733-19d81d80-2441-11eb-8c17-0fbcc15c42ad.JPG)

**Comment by J-bytes** [comment]
I agree it would be good to wrap those with the underscore function. However, even with the titles wrapped, the tab name doesn't seems to get translated (for "data explorer" that is )

**Comment by Gauravp-NEC** [comment]
@amercader , I have check and found that "Data Explorer" is not translated in other languages as well.

**Comment by amercader** [comment]
@Gauravp-NEC thanks for your help. It's better to import `_` from the toolkit when in an extension like this one.

For "Data Explorer" to be translatable, the string needs to be extracted first and included in the `.po` files that we use for translation. But we do this separately before a release, so just wrapping the string with `_()` at this point should be enough

**Comment by J-bytes** [comment]
@amercader I've checked deeper and it seems many translations displayed inside the iframe do not get translated too. They are all wrapped with the underscore function and the traductions were already available in the .po file. I've tried recompiling the .mo file with and without fuzzy with no success... Do you have any idea what could stop babel from translating these? Thank you for your help.
![image](https://user-images.githubusercontent.com/60334318/99886822-9622eb80-2c0d-11eb-8b84-7bc25644ce0d.png)

![image](https://user-images.githubusercontent.com/60334318/99886824-9ae79f80-2c0d-11eb-9695-1e98bec33d3c.png)

**Comment by Gauravp-NEC** [comment]
@amercader , based on the above discussion I have raise the PR https://github.com/ckan/ckan/pull/5754 to close this issue.

**Comment by amercader** [comment]
@J-bytes Besides the "Data Explorer" string which is in CKAN, all the other ones are rendered by the Recline JS library, which doesn't support i18n yet.
Original issue is https://github.com/datopian/recline/issues/459
In case you can help, there is an old PR (https://github.com/datopian/recline/pull/508) that might be easy to bring up to speed with Recline's master, and perhaps the folks at datopian can merge it and release a new recline version. I'd be happy to upgrade the one shipped with CKAN at that point

Alternatively, just for table views there's another view plugin shipped with CKAN, `datatables_view` that might have better i18n support.
