### ISSUE TITLE
File Name uses resource ID when using DataStore

### ISSUE THREAD

**Issue by sethug** [ckan/ckan#5742]
**CKAN version 2.9.1**

**Describe the bug**
when we download the dataset, it uses the resource id and it does not append the extension(like .csv, .json, .xml)

**Expected behavior**
we would like to download hte dataset with a proper filename and extension as opposed just a filename using resourceid and no extension. At the moment, it just downloads the file like this "fe05b025-a4e7-47a0-b24e-86c75558307d" and not even extension.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by Zharktas** [comment]
This duplicates https://github.com/ckan/ckan/issues/5593
