### ISSUE TITLE
Chained auth functions lose anonymous access

### ISSUE THREAD

**Issue by hardingalexh** [ckan/ckan#5751]
**CKAN version**
All
**Describe the bug**
If an auth function is marked as chained, it is transformed into a functools partial. In doing so, no function attributes are persisted to the new function - leaving `auth_allow_anonymous_access` flags out. This means that there is no way for developers to specify that an auth function is both chained and allowed to be accessed anonymously.

**Steps to reproduce**
Create a plugin implementing `IAuthFunctions`, and use both the `@toolkit.auth_allow_anonymous_access` and `@toolkit.chained_auth_function` decorators. The function will be chained, but will return `403` before ever running your function.

**Expected behavior**
The function doesn't automatically get 403'd.

**Additional details**
The error is in the `_build` function for the `AuthFunctions` class in `ckan/ckan/authz.py`. Specifically the `auth_allow_anonymous_access` attributes are managed [here](https://github.com/ckan/ckan/blob/612e0f9ab01b61516399e39a803d8cb66cd3c9cf/ckan/authz.py#L79), but then the chained auth functions are transformed into partials [here](https://github.com/ckan/ckan/blob/612e0f9ab01b61516399e39a803d8cb66cd3c9cf/ckan/authz.py#L118). I don't have my dev environment set up for contributing back at the moment (it's in a private fork) but have this fixed in my local 2.8 version and will get this into master this weekend.

**Comment by Zharktas** [comment]
There is a related issue with partial solutions in https://github.com/ckan/ckan/issues/4597

**Comment by hardingalexh** [comment]
> +1 to this issue. We're running into this with Data.gov.

I have a fix in here: https://github.com/ckan/ckan/pull/5756 but need to add tests so that it will get accepted. I'll try and get on that this week!
