### ISSUE TITLE
Wrong Exception in package_collaborator_create

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan#5759]
**CKAN version**
2.9.1

**Describe the bug**
When attempting to add a non-existent user as a dataset collaborator a NotAuthorized exception is raised, which should probably be a validation or not found exception. The message 'Not allowed to add collaborators' also does not make sense for the underlying cause. When using this functionality via the web interface (at least in my implementation) the NotAuthorized exception logs the user out, which is not desired behavior.

https://github.com/ckan/ckan/blob/254b18cd274dc23f2895d9de7b7eb3022b49a534/ckan/logic/action/create.py#L671

**Comment by amercader** [comment]
Thanks @pdekraker-epa, I've created a PR for this https://github.com/ckan/ckan/pull/5763
