### ISSUE TITLE
Dashboard template nav links should be in content_primary_nav

### ISSUE THREAD

**Issue by EricSoroos** [ckan/ckan#5768]
**CKAN version**
2.9/Master
**Describe the bug**
Dashboard template nav links should be wrapped in {% block content_primary_nav %} like all of the other nav tabs. 

(here https://github.com/ckan/ckan/blob/master/ckan/templates/user/dashboard.html#L20)

**Steps to reproduce**

* Write an extension that adds to the dashboard. 
* Have to patch core ckan or duplicate the existing nav items in the extension. 

**Expected behavior**

Be able to do something like:
```
{% block content_primary_nav %}
  {{ super()}}
  {{ h.build_nav_icon("route', _('Title'),  icon='info-circle') }}
{% endblock %}
```

**Comment by amercader** [comment]
That makes a lot of sense. Do you want to submit a Pull Request @EricSoroos ?

**Comment by Sunny-NEC** [comment]
i like to work on this @amercader
