### ISSUE TITLE
Organization changes do not have detailed Activity Stream UI

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5771]
**CKAN version**
2.9.1

**Describe the bug**
One of the major features in 2.9 is the detailed Dataset Activity Stream.  Even though Organization changes are also stored in the `activity` table, it only logs that the Organization has been updated.

**Steps to reproduce**
Make changes to an Organization and check the Activity Stream.

**Expected behavior**
The Activity Stream should at least show the diff, similar to how its done with Datasets, as the Organization metadata is stored in `activity.data` column.

**Comment by Gauravp-NEC** [comment]
@amercader @jqnatividad , I am interested to work on this issue. I have started the investigation.

**Comment by Gauravp-NEC** [comment]
@amercader, Can you please share the reference of PR in which the work of detailed activity stream of Dataset is done?

**Comment by Gauravp-NEC** [comment]
@amercader @jqnatividad , I have raise the PR https://github.com/ckan/ckan/pull/5912 to fix this issue.

**Comment by Gauravp-NEC** [comment]
@amercader @jqnatividad , I have raise the PR https://github.com/ckan/ckan/pull/5985 to fix this issue.
