### ISSUE TITLE
Can't Import Mod List in Terminal Version

### ISSUE THREAD

**Issue by lobf** [ckan/ckan#5776]
**CKAN version**
1.29.0

**Describe the bug**
I an export my mod list, but when I navigate to it's directory, it doesn't show up as a selectable file 

**Steps to reproduce**
Use CKAN 1.29 on MacOS Catalina, export a mod list and then attempt to find it 

**Expected behavior**
The mod list will not appear in CKAN

**Additional details**
I can provide more specific details upon request

**Comment by lobf** [comment]
I'm using the terminal version for MacOS versions which have stopped supporting 32 bit applications. Either I'm missing something, or some of the functionality in regards to exporting / importing mod lists seems to be broken.

**Comment by Zharktas** [comment]
You are filing the issue in wrong CKAN repo, you are probably looking for https://github.com/KSP-CKAN/CKAN
