### ISSUE TITLE
Deleted a harvest source but gives error that resource already exists

### ISSUE THREAD

**Issue by hussnainwithss** [ckan/ckan#5781]
**CKAN version**
2.8

**Describe the bug**
I created a harvest resource first which was wrong, hence i deleted it and try to recreate the same one but i get the error that 
URL: There already is a Harvest Source for this URL (& config): url=https://data-atgis.opendata.arcgis.com/data.json config=
when there is not
**Steps to reproduce**
- create a harvest resource
- delete it and remove all its contents
- recreate the same harvest source 
- it will give error

**Expected behavior**
it should have created it as the previous one is deleted.

**Additional details**
![image](https://user-images.githubusercontent.com/47157583/101451274-afd26b80-394d-11eb-9f2b-e4c4f0e16412.png)

**Comment by amercader** [comment]
Yes, this is confusing behaviour from the harvest extension. Can you create an issue in https://github.com/ckan/ckanext-harvest/issues?
As a workaround you can add a `#` character on the URL or add a config object different from the deleted one (any JSON will do, eg `{"a": "b"}`)
