### ISSUE TITLE
Patch releases February 2021

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5783]
This is an issue to track progress on the patch releases scheduled for XXX (2.7.10, 2.8.7 and 2.9.2)

[Full docs](http://docs.ckan.org/en/latest/contributing/release-process.html)

* [x] Backports
* [x] Translations
* [x] Rebuild Frontend
* [x] Changelog
* [x] Change version and tag 
* [x] Build packages
* [x] Update docs (RTD)
* [x] PyPI
* [x] Announce

**Comment by amercader** [comment]
Patch releases 2.7.10, 2.8.7 and 2.9.2 were released 2021-02-10

**Comment by tino097** [comment]
docs seems are not updated to 2.9.2
