### ISSUE TITLE
travis-ci.org end of live 31 dec 2020: need to enable travis-ci.com cicd (and migrate project over)

### ISSUE THREAD

**Issue by duttonw** [ckan/ckan#5792]
Travis-ci.org is going away, this repo needs to have travis-ci.com added to continue using their services.

Here's the link to migrate from travis-ci.org to .com, i've had to do this for our org qld-gov-au.
https://travis-ci.com/organizations/ckan/migrate

travis-ci.org “will be officially closed down completely on December 31st, 2020”

see:
https://www.theregister.com/2020/11/02/travis_ci_pricng/
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

It might be a good time to embrace (cross-pollinate) `github actions` while they have free unlimited minutes on builds that are on public repos tho that could be done in another ticket etc.
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-circleci-to-github-actions

**Comment by duttonw** [comment]
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#what-will-happen-to-my-travis-ciorg-repository

**Comment by Zharktas** [comment]
Travis is pretty much unusable now for open source with their new pricing model, @amercader has done some work to move ckanext-harvest to github actions, so that it probably which way extension testing is going and we will probably drop travis all together.

**Comment by duttonw** [comment]
yep, seems to get more credits you need to open a support ticket. 

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
> Your account name and VCS provider (like travis-ci.com/github/[your account name] )
> How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)
> Usage will be tracked under your account information so that you can better understand how many credits/minutes are being used
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by amercader** [comment]
CKAN core no longer uses Travis. Extensions will gradually migrate away from it.

From anyone looking for alternatives, the extension template contains an example GitHub Actions workflow to run the tests:

https://github.com/ckan/ckan/blob/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/.github/workflows/test.yml

For a multi-CKAN version setup, check ckanext-scheming or ckanext-harvest ones.
