### ISSUE TITLE
Data from two instances of CKAN in one

### ISSUE THREAD

**Issue by piodii** [ckan/ckan#5793]
I would like to ask you if there is possibility to show data from two instances of CKAN in only one of them? I have two instances of CKAN in diffrent locations and networks. I would like to show the data from both instances in the first location.

**Comment by amercader** [comment]
You can check [ckanext-harvest](https://github.com/ckan/ckanext-harvest) that will allow you to regularly import metadata from one instance into another. 

To minimize the number of issues on this repo we encourage you to submit support requests like this one to the [ckan-dev mailing list](https://groups.google.com/a/ckan.org/forum/#!forum/ckan-dev). You can also try on the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Thanks!
