### ISSUE TITLE
[wrong repository] Auto-updater removes ckan.exe after "updating"

### ISSUE THREAD

**Issue by Krzeszny** [ckan/ckan#5802]
[wrong repository]

**Comment by HebaruSan** [comment]
@Krzeszny Thanks, but this is the wrong repo; these kind folks do something sophisticated with databases. Please try again at:

- https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Comment by jqnatividad** [comment]
@Krzeszny please close this issue.
