### ISSUE TITLE
User nor pre-selected when editing organization member role

### ISSUE THREAD

**Issue by espona** [ckan/ckan#5806]
**CKAN version**
2.9
**Describe the bug**
When you press the edit (wrench tool icon) to edit the role of a member of an organization the user is not pre-selected in the "organization/member_new/<id>" page. 
The extra_vars passed to that template do not contain the 'user_dict' as expected.

**Steps to reproduce**
1. Edit an existing organization
2. Go to Members and press the edit role button (wrench tool icon)
3. See how in next page the user is not pre-selected

**Expected behavior**
The username of the member whose role you are editing, should be pre-selected

**Additional details**
This issue occurs because the user_dict is not added to the extra_vars in ckan/views/group.py, https://github.com/ckan/ckan/blob/ba1a3b831c79f2c0bec1322dc5508bc845f92319/ckan/views/group.py#L1109-L1143

I did quick fix in our own fork and it works as expected: https://github.com/EnviDat/ckan-forked/commit/e93fb70eca5061f0b7dc2d06997bae9ea5818015

**Comment by Gauravp-NEC** [comment]
@espona @amercader , I have investigate this issue. User role is not getting modified when editing the organization member role. With the approach in https://github.com/EnviDat/ckan-forked/commit/e93fb70eca5061f0b7dc2d06997bae9ea5818015 user roles are getting modified i.e., "Member" role user can change his role to "Admin/Editor" and likewise "Editor" role user can change his role to "Admin/Member"  but "Admin" user  cannot change his role to "Member" or "Editor". @amercader  Please confirm that Admin user can change his role to Member/Editor in ckan or not?

**Comment by Zharktas** [comment]
There was an [issue](https://github.com/ckan/ckan/issues/4560) where admin of the organization could lose his access to the organization by changing his own role in the organization, it was fixed in https://github.com/ckan/ckan/pull/4821. Might be related.

**Comment by Gauravp-NEC** [comment]
@amercader , Shall I submit the PR?

**Comment by Gauravp-NEC** [comment]
@amercader , Its being so long that this issue is open. Shall I submit the PR to close this issue ? I have already shared my investigation https://github.com/ckan/ckan/issues/5806#issuecomment-756539790

**Comment by Gauravp-NEC** [comment]
@amercader ,  Its being so long that this issue is open. I am interested to submit the PR for this issue. Please assign this issue to me. I have already shared my investigation in comment https://github.com/ckan/ckan/issues/5806#issuecomment-756539790.

**Comment by amercader** [comment]
@espona this was fixed in https://github.com/ckan/ckan/pull/5767, which will be part of the next patch release

@Gauravp-NEC Admins not being able to change their roles if they are Admins is expected behaviour, it was introduced in #4821 as @Zharktas mentioned
