### ISSUE TITLE
Email notifications documentation not working on CKAN 2.9.x

### ISSUE THREAD

**Issue by mbocevski** [ckan/ckan#5807]
**CKAN version: 2.9.x**

**Describe the bug**
The documentation regarding email notifications https://docs.ckan.org/en/2.9/maintaining/email-notifications.html#email-notifications is not working on 2.9.x due to nothing replacing `paster post`

**Steps to reproduce**
Try running `ckan post`, command post not available.

**Expected behavior**
An authenticated API request to the send_email_notifications action is made.

**Comment by ammarfmg** [comment]
@amercader also struggling with the same issue. I think the 'ckan post' command has been replaced with the 'ckan notify' but unable to find any info on usage. 
Could you assist with this issue?

Cheers,
Ammar

**Comment by ammarfmg** [comment]
@mbocevski have you been able to sort this issue yet? I am also trying to work this one out. I think the 'ckan post' command has been replaced with the 'ckan notify' but unable to find any info on usage.

**Comment by Zharktas** [comment]
Notify is a different thing. Post was internal functionality of paster, which needs to implemented in ckan cli as paster was removed.

**Comment by ammarfmg** [comment]
> Notify is a different thing. Post was internal functionality of paster, which needs to implemented in ckan cli as paster was removed.

@Zharktas thanks for the quick response. Any work around for sending email notifications until this is implemented by the ckan team?

**Comment by Zharktas** [comment]
There is no workaround, someone needs to implement it.

**Comment by mbocevski** [comment]
>have you been able to sort this issue yet?

>There is no workaround

@ammarfmg yes there is a workaround. What `ckan post` does is basically sends a sysadmin authenticated request to the `/api/action/send_email_notifications` endpoint. So you can implement it simply by registering an sysadmin account, generating an API token and then using that token you can call something like:
 `curl -s -H "Authorization: SYSADMIN_API_TOKEN" -d {} http://<ckan_url>/api/action/send_email_notifications`

You can see how we've implemented it temporarily on our ckan helm package here: https://github.com/keitaroinc/ckan-helm/blob/master/templates/cronjob.yaml#L19-L26

**Comment by ammarfmg** [comment]
> > have you been able to sort this issue yet?
> 
> > There is no workaround
> 
> @ammarfmg yes there is a workaround. What `ckan post` does is basically sends a sysadmin authenticated request to the `/api/action/send_email_notifications` endpoint. So you can implement it simply by registering a sysadmin account, generating an API token and then using that token you can call something like:
> `curl -s -H "Authorization: SYSADMIN_API_TOKEN" -d {} http://<ckan_url>/api/action/send_email_notifications`
> 
> You can see how we've implemented it temporarily on our ckan helm package here: https://github.com/keitaroinc/ckan-helm/blob/master/templates/cronjob.yaml#L19-L26

@mbocevski thanks a lot for this. I will give it a try.

**Comment by ammarfmg** [comment]
@mbocevski after generating an API key, can I add the curl command to my crontab file with an @hourly keyword?

@hourly curl -s -H "Authorization: SYSADMIN_API_TOKEN" -d {} http://<ckan_url>/api/action/send_email_notifications

**Comment by mbocevski** [comment]
>can I add the curl command to my crontab file

Of course.

**Comment by ammarfmg** [comment]
Thanks again. It is running but giving this message:

"Bad request - JSON Error: Invalid request. Please use POST method for your request"

I will try to solve it.

**Comment by mbocevski** [comment]
>"Bad request - JSON Error: Invalid request. Please use POST method for your request"

Did you include the `-d {}` that means to send empty data with the request which will automatically send a POST request. You can always add `-X POST` if you want to explicitly set the request method.

**Comment by ammarfmg** [comment]
> > "Bad request - JSON Error: Invalid request. Please use POST method for your request"
> 
> Did you include the `-d {}` that means to send empty data with the request which will automatically send a POST request. You can always add `-X POST` if you want to explicitly set the request method.

Thanks again. I am doing something like this in my crontab.

@hourly sudo curl -s -H "Authorization: xxxxxxxxxxxxxxxxxx" -d {}  -X POST http://10.217.84.24//api/action/send_email_notifications

**Comment by mbocevski** [comment]
Try running the curl command from the shell to see that all works fine. You don't need to use `sudo`. It shouldn't matter but you have double forward-slashes `//api`. If it works fine from the shell, and doesn't work from cron then check whether you need to quote the command or something depends on your systems cron.

**Comment by ammarfmg** [comment]
Ok sure. I am getting the following output in shell:

{"help": "http://x.x.x.x/api/3/action/help_show?name=send_email_notifications", "success": true, "result": null}

Is this the expected behavior?

**Comment by mbocevski** [comment]
>{"help": "http://x.x.x.x/api/3/action/help_show?name=send_email_notifications", "success": true, "result": null}
>Is this the expected behavior?

Yes! Great.

**Comment by ammarfmg** [comment]
> > {"help": "http://x.x.x.x/api/3/action/help_show?name=send_email_notifications", "success": true, "result": null}
> > Is this the expected behavior?
> 
> Yes! Great.

Thank you and have a good day.

**Comment by shubham-mahajan** [comment]
> There is no workaround, someone needs to implement it.

@Zharktas What do you think to implement it in the [notify CLI](https://github.com/ckan/ckan/blob/master/ckan/cli/notify.py) itself with the new click command as `send_email_notifications` which will trigger the notifications

Something like this

```python
@notify.command(
    name=u'send_email_notifications',
    short_help=u'Send out Email notifications.'
)
def send_email_notifications():
    if not converters.asbool(
            config.get('ckan.activity_streams_email_notifications')):
        raise ValidationError('ckan.activity_streams_email_notifications'
                              ' is not enabled in config')
    email_notifications.get_and_send_notifications_for_all_users()

```


WDYT about the above approach?

**Comment by ThrawnCA** [comment]
> WDYT about the above approach?

I mostly like it, but if it's already getting filed under 'notify', maybe it can have a shorter name?
