### ISSUE TITLE
How do I change, add, delete anything on the home page?

### ISSUE THREAD

**Issue by infracritical** [ckan/ckan#5817]
I've looked throughout the documentation, and have found very little.  Thoughts/

-rad

**Comment by jqnatividad** [comment]
You may want to check Customizing CKAN's templates in the Theming Guide.

https://docs.ckan.org/en/2.9/theming/templates.html

Once you generate an extension, I suggest you choose a **Homepage layout** which you wish to extend in http://yourckansite/ckan-admin/config and override the corresponding jinja2 templates in your extensions' template directory.

See https://docs.ckan.org/en/2.9/theming/templates.html#replacing-a-default-template-file

The homepage templates can be found in the ckan/templates/home directory.

**Comment by infracritical** [comment]
And what do I do if I want to change an existing template?

For example, my 'home' directory outside of the Dockerized environment is '/usr/local/ckan', so the templates are located under '/usr/local/ckan/ckan/templates'. Now say I want to change the default "Welcome to CKAN" with the 420 x 220 image placeholder; the template file is located here: /usr/local/ckan/ckan/templates/snippet/promoted.html.  I've saved off the default version as '_orig_promoted.html' and changed the entries within the file.

I went to the directory '/usr/local/ckan/contrib/docker', entered 'docker-compose down', then entered 'docker-compose up -d --build'. Upon refreshing the web site, it DOES NOT show the changes to my template entry.

As this is a Docker Compose'd container, it utilizes its 'source'; the 'source' is '/usr/local/ckan'.

I *should* be able to perform the change(s) directly to the template files within the '/usr/local/ckan/ckan/templates/...' directory, yes?

-rad

**Comment by infracritical** [comment]
So...translation - my changes to ANY *existing* template file under '/usr/local/ckan/ckan/templates/...blahblahblah...' DO NOT show up upon rebuilding the containers through the Docker Compose'r utility.

**Comment by infracritical** [comment]
BTW, I've done the following commands for the Dockerized container:

1. docker-compose down
2. docker rmi -f docker_ckan docker_db
3. docker rmi $(docker images -f dangling=true -q)
4. docker-compose up -d --build

The answer is still NO.  Not changes that were applied to any of the existing templates *outside* of the Dockerized container were applied.

-rad

**Comment by kowh-ai** [comment]
@infracritical -  The ckan container is built from ckan master with line 51 in the ckan Dockerfile. How are you overriding the template files when you build the container?

**Comment by infracritical** [comment]
THAT'S IT!!!  I was looking at the wrong location!!!

I thought that it was located at "/usr/lib/ckan" (or my version, "/usr/local/ckan"; it wasn't.

The real master is located at "/var/lib/docker/volumes/docker_ckan_home/_data/venv/src/ckan".

I made a test change in there, shutdown the containers, then rebuilt them.  IT WORKS!!!  THANK YOU!!!!
