### ISSUE TITLE
Outdated 'sqlparse' causes errors when viewing resources with newlines and semicolons in headers

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#5822]
**CKAN version**

2.8.4

**Describe the bug**

Upon adding a resource that can be parsed into the datastore, with a header containing a newline and a semicolon, the resource page fails to load, logging a "Query is not a single statement" error. This occurs because CKAN is using an old version (0.2.2) of the `sqlparse` library. The behaviour is resolved in sqlparse version 0.3.0.

**Steps to reproduce**

Create a resource from a CSV file with a header containing newlines and semicolons, eg:

        Heading1,"Head
        ing;2"
        Value1,Value2

Load the resource into the datastore.

View the resource page.

**Expected behavior**

Semicolons in CSV headers should be treated like regular characters.

**Additional details**

sqlparse changelog is at https://sqlparse.readthedocs.io/en/latest/changes/#release-0-3-0-mar-11-2019

**Comment by ThrawnCA** [comment]
It may be worth updating to 0.3.1 instead of 0.3.0; it contains several more bug fixes and remains backwards compatible.

**Comment by ThrawnCA** [comment]
This should be backported to CKAN 2.9 under Python 2.

**Comment by wardi** [comment]
@ThrawnCA I've added the backport label to the PR.

Also.. newlines and semicolons in headers?? you monster.

**Comment by ThrawnCA** [comment]
> @ThrawnCA I've added the backport label to the PR.

Thanks for the fast response!

> Also.. newlines and semicolons in headers?? you monster.

Heh. I don't own the data, I just help maintain the portal.

**Comment by ThrawnCA** [comment]
Incidentally, the semicolons+newlines make more sense when the data is an Excel spreadsheet. I've seen *bulleted lists* in header rows before...
