### ISSUE TITLE
Resource Additional Information metadata is incomplete/incorrect

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5829]
**CKAN version**
2.9.1

**Describe the bug**
Several resource-level metadata is stored but not displayed on the Resource page:

* size - in bytes
* hash - currently used by datapusher to detect if a file has changed. Can be used by users as well to do the same.
* resource_type - doc, listing, service, api, etc.
* format - TXT, CSV, PDF, etc.

and resource mimetype is incorrectly displayed as format.

**Expected behavior**
All "standard" resource level metadata should be displayed on the Additional Information section of the resource page.

**Comment by amercader** [comment]
I'm pretty sure that the standard template shows all resource fields (hidden under "Show more"), eg see https://beta.ckan.org/dataset/this-is-a-test-dataset/resource/ba807bd0-061a-4b25-ae97-a21b0c9669f8

It might be ckanext-scheming that doesn't implement this in its resource read template.
