### ISSUE TITLE
CKAN 2.9.x install instructions: command line to install "solr-jetty", instructions to configure with tomcat9?

### ISSUE THREAD

**Issue by ryangermann-gov-on-ca** [ckan/ckan#5835]
could I suggest that this line:

sudo apt-get install python3-dev postgresql libpq-dev python3-pip python3-venv git-core **solr-jetty** openjdk-8-jdk redis-server

of the CKAN 2.9x install from source instructions at:

https://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html

be changed to:

sudo apt-get install python3-dev postgresql libpq-dev python3-pip python3-venv git-core **solr-tomcat** openjdk-8-jdk redis-server

in the installation instructions for CKAN 2.9.x: the install instructions suggest using tomcat not jetty (a change from 2.8x instructions) which is fine: the command lines in the instructions make it easy for someone not really adept with linux to get CKAN up and running, but having to figure out how to set up all the components takes a lot of time... perhaps that time would not need to be spent if the instructions were updated as I suggest? I am not confident to make the change myself so just a suggestion to those who might know better.

**Comment by Gauravp-NEC** [comment]
@kowh-ai , What is your opinion?

**Comment by Sunny-NEC** [comment]
As per my understanding by below files also need to be changed:
        
        doc/maintaining/installing/install-from-source.rst
	ckan/pastertemplates/template/bin/travis-build.bash_tmpl
	doc/maintaining/upgrading/upgrade-source.rst
	doc/maintaining/upgrading/upgrade-package-to-minor-release.rst
	.circleci/config.yml
	doc/contributing/test.rst
	doc/maintaining/installing/solr.rst
	doc/maintaining/installing/install-from-package.rst
	ckan/lib/search/query.py

Please confirm.
