### ISSUE TITLE
Unable to read large csv files 

### ISSUE THREAD

**Issue by albastakihalima** [ckan/ckan#5866]
version 2.9

When trying to preview the uploaded file, message appear as following:
Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)

**Steps to reproduce**
- We Tried to alter several parameters but no results
Those Parameters were applied for CKAN 
- CKAN_MAX_UPLOAD_SIZE_MB=40000
- CKAN_MAX_RESOURCE_SIZE=500000
- CKAN_DATASTORE_SEARCH_ROW_MAX=1000000
 - CKAN_SEARCH_ROW_MAX= 5000000
 
Those Parameters were applied for Data Pusher
- DATAPUSHER_MAX_CONTENT_LENGTH=10485760000
- DATAPUSHER_CHUNK_SIZE=163840000
- DATAPUSHER_CHUNK_INSERT_ROWS=250000
- DATAPUSHER_DOWNLOAD_TIMEOUT=3000

**Expected behavior**
 This resource view is not available at the moment. Click here for more information.
Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)

**Comment by amercader** [comment]
The DataProxy is used when the resource data can not be retrieved from the DataStore. Check the DataPusher logs on Resource > Manage > DataStore to see if the data was actually uploaded and see if there is an error during the upload.
Alternatively you can use https://github.com/ckan/ckanext-xloader, which allows you to import just a subset of the data for visualization purposes.
