### ISSUE TITLE
ERROR: 'humanize_entity_type' has not been defined.

### ISSUE THREAD

**Issue by pauldcollins** [ckan/ckan#5877]
I am using **CKAN 2.8.5**

I am trying to create a custom template for the Organizations home page. 

I have copied the code from this page:
https://github.com/ckan/ckan/blob/cc000d3acf7401957d8321be53e8cabc2d9ebf3a/ckan/templates/organization/index.html

And I have created an `index.html` file under the same path:
`my_theme\ckannext\project_theme\templates\organization\index.html`

But, I the page is broken and I am getting the following error: 
**WebError Traceback:
⇝ HelperError: Helper 'humanize_entity_type' has not been defined.**

I'm a little confused about where this `humanize_entity_type` function lives and how I can fix this error. Thanks for any help.

**Comment by Zharktas** [comment]
You need to customize templates from 2.8 branch https://github.com/ckan/ckan/blob/2.8/ckan/templates/organization/index.html
`humanize_entity_type` is helper function which is implemented only in master and therefore is released in the next major ckan release, thats why it's failing for you.
