### ISSUE TITLE
Wrong docstring for  of ckan.tests.helpers.call_auth

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#5884]
**CKAN version** 2.9.1

**Describe the bug**
The docstring in ``ckan.tests.helpers.call_auth`` is wrong:
https://github.com/ckan/ckan/blob/master/ckan/tests/helpers.py#L153-L155

This function actually just returns a boolean value (return value of `logic.check_access`):
https://github.com/ckan/ckan/blob/master/ckan/logic/__init__.py#L248-L320

**Expected behavior**
The docstring should read s.th. like
```
    :returns: the 'success' value of the authorization check
    :rtype: bool
```

**Additional details**
It might actually be helpful for testing to return the dict that the auth function returns (via an additional keyword argument?)

**Comment by Gauravp-NEC** [comment]
I am interest to work on this issue.

**Comment by Gauravp-NEC** [comment]
@paulmueller, I am interest to work on this issue. What is the purpose of the Additional details that " It might actually be helpful for testing to return the dict that the auth function returns (via an additional keyword argument?)" ?

**Comment by paulmueller** [comment]
The original docstring says that it returns the "dict that the auth function returns". For writing test functions with pytest, it might be interesting to actually get the error message ``{'success': False, msg: 'important error message'}`` and check whether it is the right one.

Since returning the dictionary is not an option (would break all current tests), I thought it would be helpful to get this via an additional keyword argument (such as `ret_dict=False` by default).

**Comment by Gauravp-NEC** [comment]
@paulmueller , as discussed above I have raise the PR https://github.com/ckan/ckan/pull/5893 to fix this issue. Thankyou :)

**Comment by paulmueller** [comment]
@Gauravp-NEC I believe you misunderstood me. ``:ret_dict: False`` does not make any sense in the docstring. Also,

```
, e.g.
``{'success': True}`` or ``{'success': False, msg: 'important error message'}``
or just ``{'success': False}``
```

should not be there, since the function does not return a dict, it returns a bool.

**Comment by Gauravp-NEC** [comment]
@paulmueller , Thankyou for your quick response. I have update the PR.
