### ISSUE TITLE
Installing via pip does not install requirements

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#5885]
**CKAN version**
2.7, 2.8

**Describe the bug**
Installing ckan via pip `pip install ckan==2.8.6` or `pip install ckan==2.7.9` does not install its requirements and the requirements file does not exist with the installed version.

**Steps to reproduce**
Run `pip install ckan==2.8.6` or `pip-compile requirements.in` where `ckan==2.8.6` is listed as requirement.

**Expected behavior**
Requirements should be installed with ckan itself.

**Additional details**
This probably got fixed for 2.9 in https://github.com/ckan/ckan/pull/5408 and https://github.com/ckan/ckan/pull/5738

**Comment by Zharktas** [comment]
Tested this against 2.9.2 and requirements are parsed nicely with pip-compile, so backporting should be enough.

**Comment by amercader** [comment]
Backported to 2.8.8
