### ISSUE TITLE
Bug: package_revise returns a list not str in the message value on error

### ISSUE THREAD

**Issue by mcarans** [ckan/ckan#5888]
**CKAN version**
2.9

**Describe the bug**
package_revise returns a list in the message value eg.
```
{'message': [{'resources__1__upload': ['Unmatched key resources__1']}], '__type': 'Validation Error'}
```

**Steps to reproduce**
Specify a resource that doesn't exist when uploading eg. `update__resources__1__upload`

**Expected behavior**
Error is returned with a string message (judging by how ckanapi Python library handles the returned error message by attempting to "split" it)

**Additional details**
I had raised an error against the ckanapi Python library (https://github.com/ckan/ckanapi/issues/186), but it seems the error is in package _revise. @wardi said "interesting, this might be a bug in package_revise, none of the other actions return a list in the message value AFAIK"

Traceback:
```
Traceback (most recent call last):
  File "/home/mcarans/Programming/hdx-python-api/src/hdx/data/hdxobject.py", line 331, in _write_to_hdx
    return self.configuration.call_remoteckan(self.actions()[action], data, files=files_to_upload)
  File "/home/mcarans/Programming/hdx-python-api/src/hdx/hdx_configuration.py", line 307, in call_remoteckan
    return self.remoteckan().call_action(*args, **kwargs)
  File "/home/mcarans/Programming/VirtualEnvs/hdx-python-api/lib/python3.8/site-packages/ckanapi/remoteckan.py", line 88, in call_action
    return reverse_apicontroller_action(url, status, response)
  File "/home/mcarans/Programming/VirtualEnvs/hdx-python-api/lib/python3.8/site-packages/ckanapi/common.py", line 114, in reverse_apicontroller_action
    emessage = err.get('message', '').split(': ', 1)[-1]
AttributeError: 'list' object has no attribute 'split'
```

**Comment by Sunny-NEC** [comment]
@mcarans I would like to work in this issue but I am unable to reproduce this issue. Can you provide me more information on how to reproduce it.

**Comment by robin-NEC** [comment]
Hi @mcarans , I'm trying to reproduce the issue but am unable to do so.  Could you please confirm where you're getting the error, is it coming from the `ckanapi` or `package_revise`?
Can you please provide the API endpoint that you're using to get this error response? 
Thanks.

**Comment by mcarans** [comment]
@robin-NEC I was using `ckanapi` and a fix was released in that library for the problem. See [this issue](https://github.com/ckan/ckanapi/issues/186). @wardi said "interesting, this might be a bug in package_revise, none of the other actions return a list in the message value AFAIK"

Looking at the source code, I think it was fixed in a large update. If you load the diff for [ckan/logic/action/update.py](https://github.com/ckan/ckan/commit/b2a03aa66b50fde7a68e0b2921104475117e7093#diff-dd88e6f8dd6bc2534492239093b9b1480233b670287fe4bc275a8ba32ed99c67) and search for `[{'match':` you can see that on line 488, it has changed from `raise ValidationError([{'match': [` to `raise ValidationError({'message': [{'match': [` and similarly for otehr ValidationError lines.

**Comment by mcarans** [comment]
@robin-NEC I have tried a call like this in postman
url: SERVER_URL/api/3/action/package_revise
body: 
    match__id=ANY DATASET ID TO MATCH
    update__resources__20__upload@testfile1

(20 is any number higher than teh number of resources in the dataset)

I got:
`{"help": "https://stage.data-humdata-org.ahconu.org/api/3/action/help_show?name=package_revise", "error": {"message": [{"resources__20__upload": ["Unmatched key resources__20"]}], "__type": "Validation Error"}, "success": false}`

I think this means that the problem persists since I wrote before that the message part looked like this:
`{'message': [{'resources__1__upload': ['Unmatched key resources__1']}], '__type': 'Validation Error'}`

**Comment by wardi** [comment]
note that latest ckanapi no longer fails this way when a list is returned in the message key
