### ISSUE TITLE
Detail in change logs

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckan#5897]
**CKAN version**
2.8 -> 2.9

**Additional details**

It would be useful to know if all changes needed to reflected in extensions. For example, `templates/organization/new.html` changed from 2.8 ([code](https://github.com/ckan/ckan/blob/2.8/ckan/templates/organization/new.html)) to 2.9 ([code](https://github.com/ckan/ckan/blob/2.9/ckan/templates/organization/new.html)).

For people who write extensions that override this file, it would be good to know the impact of either incorporating these changes, or of not doing so.

**Comment by amercader** [comment]
We do try to list all breaking changes in the CHANGELOG so that one slipped through the cracks. Perhaps it was part of the big refactor to support Flask on 2.9 and this particular case was missed.
