### ISSUE TITLE
Uploaded files and activity stream history

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan#5904]
**CKAN version**
2.9.1

**Describe the bug**
When viewing an uploaded resource via the activity stream history, the url and downloaded filename match the prior version, but the file contents is the most recently uploaded file.  There is a red message a the top that could lead the user to believe that they would be getting the older version of the resource.

**Steps to reproduce**
Create a dataset with an uploaded file resource
Manage the resource and upload a new file in its place
Using the activity stream browse back to the old version of the dataset
Try to download the resource from the old dataset
The contents of the file will be the newer file

**Expected behavior**
I don't know, maybe if the file has been replaced the URL listing should removed and a message put in its place

An option to retain old versions would be awesome, but that is a bigger ask

**Comment by wardi** [comment]
Let's update the red message to include "resource files may not match the old version of the data" or similar and make sure it's shown on dataset and resource pages.

**Comment by Gauravp-NEC** [comment]
@wardi , I am interested to work on this issue.

**Comment by wardi** [comment]
@Gauravp-NEC this should be a simple message text change. Go for it.

**Comment by Gauravp-NEC** [comment]
@wardi @pdekraker-epa , I have raise the PR https://github.com/ckan/ckan/pull/6041 to fix this issue.
