### ISSUE TITLE
User email wrongly stored when there is a failed email invite

### ISSUE THREAD

**Issue by ldv1452** [ckan/ckan#5908]
**CKAN version**
2.9.2

**Describe the bug**
If the email server is not setup when inviting a user to register via email an error message is returned and no invite is sent out. However, the email used in the previous is stored internally so that when the user tries to register a message "Email already in use" is given. 

**Steps to reproduce**
Steps to reproduce the behavior: as a organization administrator try to send out an email invite for registration without having the email server setup. This will return an error. Then try to register using the same email given within the invite. A message "Email already in use" will be issued.

**Expected behavior**
When the email server is not setup and an organization administrator tries to send out a failed invite the given email should not be internally stored.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by amercader** [comment]
There's an existing pull request to purge users if the invite failed that should address this issue: https://github.com/ckan/ckan/pull/5879

**Comment by sfirke** [comment]
This should be re-opened as the PR https://github.com/ckan/ckan/pull/5879 was never merged and the problem persists.
