### ISSUE TITLE
Scheming & Fluent extensions don't work in new CKAN 2.9

### ISSUE THREAD

**Issue by microshadow** [ckan/ckan#5913]
**CKAN version**
2.9
**Describe the bug**
upgrading ckan from 2.8 to 2.9 gets an error called "permission error". 

**Steps to reproduce**
N/A

**Expected behavior**
if do not add scheming & fluent extension, it works fine, but once those extensions were added, it causes the error.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by wardi** [comment]
scheming definitely works with Python 3 but fluent needed https://github.com/ckan/ckanext-fluent/pull/32 , now merged. Would you try again and if you get an error please post the full traceback or screenshot with url where you see the error.
