### ISSUE TITLE
Groups Activity Stream do not have detailed "changes" in UI

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#5915]
**CKAN version**
   2.9

**Describe the bug**
If there is any change in Groups, it only logs that the Groups has been updated.

**Steps to reproduce**
   Make changes to a Group and check the Activity Stream.

**Expected behavior**
   The  Groups Activity Stream should show the differences.

**Additional details**
  This is similar to Dataset detailed Activity Stream.

**Comment by Zharktas** [comment]
Only datasets currently have detailed changes view and this needs an implementation similarly as in #5771.

**Comment by Gauravp-NEC** [comment]
@Zharktas, I am interested to work on this issue.

**Comment by Gauravp-NEC** [comment]
@Zharktas , I have raised the PR https://github.com/ckan/ckan/pull/6002 to fix this issue.

**Comment by Gauravp-NEC** [comment]
@Zharktas ,  I have raise the PR https://github.com/ckan/ckan/pull/6040 to fix this issue.
