### ISSUE TITLE
Is there a way to call helper function in a javascript?

### ISSUE THREAD

**Issue by YukunYangNPF** [ckan/ckan#5920]
Hi, I'm trying to visualize the dataset summary statistics and put it on the home page. For example, a heatmap showing the number of docs in that category in a specific year.

I know I can generate some site stats by calling helper functions or template functions, but that data will be accessible to jinja, right? How can I make it accessible to a custom javascript script so it can load the data and create viz?

**Comment by smotornyuk** [comment]
You can encode your data into JSON and print it on the right side of an assignment operator inside `script` tag:

```
# inside helpers.py
def encoded_helper(): return json.dumps({'a': 1})
def plain_helper(): return {'a': 1}


# inside any jinja2 template 
<script>
 var data = {{ h.encoded_helper() }}
 {# or #}
 var data = {{ h.plain_helper() | tojson }}
</script>
```

**Comment by YukunYangNPF** [comment]
It worked. Thanks a lot.
