### ISSUE TITLE
Suggest updating postgis image to official postgis docker images

### ISSUE THREAD

**Issue by checkbook-org** [ckan/ckan#5922]
https://github.com/ckan/ckan/blob/40f127af93fd09b89c1a86206563986417dd1214/contrib/docker/postgresql/Dockerfile#L2

Postgis now provides their own docker images, which are updated with latest postgres db versions:

https://hub.docker.com/r/postgis/postgis

Suggestion updating the source docker image.

**Comment by Gauravp-NEC** [comment]
I am interested to work on this issue.

**Comment by amercader** [comment]
Thanks @Gauravp-NEC  that would be great

**Comment by checkbook-org** [comment]
Great!  I edited contrib/postgresql/Dockerfile to use
FROM postgis/postgis

docker-compose up –build
succeeds, but I haven’t gotten the whole installation running yet (I’m new to CKAN).

Let me know if there’s anything I can do to help.

Eric

**Comment by Gauravp-NEC** [comment]
@amercader , I have raise the PR https://github.com/ckan/ckan/pull/5957 to fix this issue.
