### ISSUE TITLE
"New view" button does not work in CKAN 2.7.9 and 2.7.10

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#5931]
**CKAN version**

2.7.9 and 2.7.10

**Describe the bug**
Exactly the same error as #4260. In the browser console it shows the `Uncaught Error: Syntax error, unrecognized expression: #` error.

**Steps to reproduce**
Install the CKAN 2.7.9 or 2.7.10. Under the "Manage" page for the created resource, click the "Views" tab. Then try to click the "New view" button.

**Expected behavior**
There should be a list of possible views to create.

**Additional details**
Since we have updated the minified jQuery to 3.5.0 in https://github.com/ckan/ckan/commit/c5bb5fc0a81f7a229ed0cb0a733440197e0d979c, maybe we need the same fix (#4350) for "New view" button like the one for Bootstrap 2 mode in CKAN ≥ 2.8?
It should be an easy fix and I can make a PR if needed.

**Comment by Zharktas** [comment]
Apparently the fix just needs to be backported, thanks for flagging this.

**Comment by shubhamsharma10** [comment]
Please review the patch and if it is OK then please merge it to master branch. @amercader @Zharktas

**Comment by u10313335** [comment]
I found another PR related this issue and needed to be backported: #3720.

**Comment by amercader** [comment]
Both #3720 and #4350 will be in 2.7.11
