### ISSUE TITLE
sqlalchemy setting "pool_pre_ping"

### ISSUE THREAD

**Issue by etj** [ckan/ckan#5932]
**CKAN version**

Introduced in commit https://github.com/ckan/ckan/commit/ae9eb1360028a77b35506716eed2768349827806 which is related at least to 2.9.0, 2.9.1, 2.9.2. 

**Describe the bug**

This is the ckan code:
```python
    # Enable pessimistic disconnect handling (added in SQLAlchemy 1.2)
    # to eliminate database errors due to stale pooled connections
    config.setdefault('pool_pre_ping', True)

    # Initialize SQLAlchemy
    engine = sqlalchemy.engine_from_config(config)
```

This is the sqlalchemy function:
```python
    def engine_from_config(configuration, prefix="sqlalchemy.", **kwargs):
```

I guess the `pool_pre_ping` config is not taken into account by sqlalchemy since it's missing the prefix.

**Comment by amercader** [comment]
Sounds good, want to submit a PR @etj
