### ISSUE TITLE
No way to reliably serve large files through uWSGI + nginx

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#5933]
**CKAN version** 2.9.2
(I am using the default setup with Ubuntu 20.04 and nginx+uWSGI as described in the docs)

**Describe the bug**
There is no reliable and efficient way of serving large files from CKAN via nginx+uWSGI.

**Steps to reproduce**
- Initially I ran into this bug where I could not download files larger than 1.08GB. This was solved
  1. with the nginx configuration option (in `location` block): `proxy_max_temp_file_size 0;`, which is set to `1024m` by default and
  2.  by setting `harakiri` to a large number in the uWSGI configuration file.
- But then, the CKAN instance will only process one "request" at a time (With that I mean, while the file was downloading, I could not browse the CKAN web frontend): "504 Gateway Time-out".
- I then started to work myself through the [uWSGI options](https://uwsgi-docs.readthedocs.io/en/latest/Options.html) and realized that
  - I cannot use [async](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#async), because apparently CKAN would have to be [written with that in mind](https://uwsgi-docs.readthedocs.io/en/latest/Async.html).
  - I cannot use [workers](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#workers), because then I run into https://github.com/ckan/ckan/issues/4576
- This left me with no other choice than to set the nginx config `proxy_max_temp_file_size 10000m;` (~10GB). Now nginx is storing everything it gets from uWSGI in a temporary directory, filling up valuable disk space every time someone downloads a file. The CKAN instance is blocked until nginx is finished copying the file to that temporary directory. This workaround is not suitable for production.

**Expected behavior**
There should be a simple and efficient solution for serving large files via uWSGI+nginx. After all, this is the recommended production setup (according to the docs).

**Additional information**
- Note that it is not an option for me to just let nginx serve the large files as static files, because they belong to private CKAN datasets (authorization via CKAN required).
- I have the feeling that I am missing a configuration option. I would gladly update the CKAN docs if there was a simple fix.

**Comment by paulmueller** [comment]
If it helps, I only run into https://github.com/ckan/ckan/issues/4576, if I have previously started a resource download of a private dataset:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 400, in ckan_after_request
    r_time = time.time() - g.__timer
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 444, in __getattr__
    return getattr(app_globals.app_globals, name)
AttributeError: '_Globals' object has no attribute '__timer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 400, in ckan_after_request
    r_time = time.time() - g.__timer
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 444, in __getattr__
    return getattr(app_globals.app_globals, name)
AttributeError: '_Globals' object has no attribute '__timer'
```

**Comment by paulmueller** [comment]
And I also get this:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 369, in ckan_before_request
    app_globals.app_globals._check_uptodate()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/app_globals.py", line 199, in _check_uptodate
    value = model.get_system_info('ckan.config_update')
  File "/usr/lib/ckan/default/src/ckan/ckan/model/system_info.py", line 47, in get_system_info
    obj = meta.Session.query(SystemInfo).filter_by(key=key).first()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3222, in first
    ret = list(self[0:1])
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3012, in __getitem__
    return list(res)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3324, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3349, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected

[SQL: SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state 
FROM system_info 
WHERE system_info.key = %(key_1)s 
 LIMIT %(param_1)s]
[parameters: {'key_1': 'ckan.config_update', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by paulmueller** [comment]
@smotornyuk Since you were assigned, could this be related to the fact that I am getting this message in my logs:

`Python threads support is disabled. You can enable it with --enable-threads`?

**Comment by paulmueller** [comment]
I just had another look at this issue and I found that I could set `proxy_temp_path` in the nginx `location` config to keep free space on my root partition:
```
proxy_max_temp_file_size 100000m;
proxy_temp_path /data/tmp/nginx/proxy 1 2;
proxy_store off;
proxy_cache off;
```
which uses the network share mounted on `/data` (where the large files are stored) as a temporary path for downloaded files.


Interestingly, on a machine that has a block storage mounted on `/data` (instead of an NFS share) with the same settings, the directory `/data/tmp/nginx/proxy` remains empty. Downloads are working. After a brief period (the system must be copying the original file somewhere), CKAN is responsive again. But I don't know where nginx copied the file to. Nginx should get the file from uwsgi, so this cannot be a copy-on-write feature of the file system. Is uwsgi telling nginx that it wants to send a file and where it is on the file system? I don't get it - is this some kind of undocumented feature? `df -h` and `du -sh /data/tmp/nginx/proxy` remain unchanged when I download a 2GB file from CKAN. The root partition has a total of 20GB storage. `htop` tells me that 1GB of RAM is used.

I would really appreciate someone with more in-depth knowledge to explain what is happening.

**Comment by smotornyuk** [comment]
Hi, @paulmueller 

As for NFS / local fs issue, I have no clue what's going on.  But i'm sure you can solve `__Global` error when you increasing the number of workers inside uwsgi config, by adding `lazy-apps = true` to that config file. This option will postpone application initialization and all the child threads will have their own set of global variables(they are missing in your case and it causes the error)

**Comment by paulmueller** [comment]
I can confirm that the `__Global` goes away when using `workers` in combination with `lazy-apps = true`.

**Comment by paulmueller** [comment]
I believe I have figured out how to solve this issue and it now makes a lot more sense to me that CKAN is running on uWSGI behind nginx. Below I pasted my current `ckan-uwsgi.ini` file. I enabled caching of downloads in nginx via `proxy_max_temp_file_size` and `proxy_temp_path`. I believe there is no way around this because if I had to deal with 100 clients at the same time, then I would need 100 uWSGI workers, which is not practical (or even possible) - nginx handles clients much better.

```
[uwsgi]

; Since we are behind a webserver (proxy), we use the socket variant.
; We use HTTP1.1 (keep-alives)
http11-socket   =  127.0.0.1:8080
uid             =  www-data
gid             =  www-data
wsgi-file       =  /etc/ckan/default/wsgi.py
virtualenv      =  /usr/lib/ckan/default
module          =  wsgi:application
master          =  true
pidfile         =  /tmp/%n.pid
harakiri        =  7200
max-requests    =  5000
vacuum          =  true
callable        =  application
buffer-size     =  32768

; Make sure all options in this file exist.
strict          =  true

; Enable post-buffering - not sure exactly how it works, but it avoids
; unexpected closing of the connection by nginx during upload.
post-buffering  =  1

; Set the number of workers to something > 1, otherwise
; only one client can connect via nginx to uWSGI at a time.
; See https://github.com/ckan/ckan/issues/5933
workers         =  4
; Use lazy apps to avoid the `__Global` error.
; See https://github.com/ckan/ckan/issues/5933#issuecomment-809114593
lazy-apps       =  true
; If we don't want to cache the files that users want to download
; (i.e. set `proxy_max_temp_file_size 0;` in nginx), then we have to set
; socket-timeout = 7200
; (Note that we are serving CKAN via http11-socket behind nginx).
; Otherwise, downloads will fail with `uwsgi_response_sendfile_do() TIMEOUT !!!`,
; because the client cannot download the file from nginx as fast as
; uWSGI can send the file to nginx. But in this case, we can really only
; have as many connections as we have workers.
; On the other hand, if we, set `proxy_max_temp_file_size 100000m;`
; in nginx, then all downloads will be cached by nginx. And nginx will
; handle all users. The purpose of setting `workers` to `4` in uWSGI
; is now only so that CKAN does not block for as long as it takes the
; system to copy the download from uwsgi to nginx's `proxy_temp_path`.
; In other words, CKAN will only be unresponsive if 4 downloads are
; started at the same time for as long as it takes the smallest download
; to be copied over the http socket from uWSGI to nginx.
; Good to know: nginx also caches uploads, so no uWSGI worker is
; blocked *during* an upload.
```

@smotornyuk Does this make sense to you or is there a better solution? Do you know how/if https://demo.ckan.org solves this issue? If this is acceptable from your expert point of view, then I would consider this issue closed. Thanks!

**Comment by smotornyuk** [comment]
Your solution really looks like the best option in current conditions. Unfortunately, there is no recommended\better option and it has been a problem for quite a long time. When it's possible we are trying to use [ckanext-cloudstorage](https://github.com/TkTech/ckanext-cloudstorage) or some sort of similar extension that moves all the files to the cloud and reduces the load of CKAN web-nodes. In the future it would be nice to try using Nginx's [XSendfile](https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/) feature - it may handle such cases more seamlessly. But right now there is a bunch of other problems that have higher priority so there are no any estimations as to when to expect this problem to be solved :(

**Comment by paulmueller** [comment]
Thank you for the quick reply. Yes, I can see how XSendfile would be good (nginx would not have to cache downloads anymore). With your blessing, I am closing this one.

**Comment by paulmueller** [comment]
FYI Regarding the  NFS / local fs issue, I found out that nginx is still using disk space in the local fs case. Nginx apparently creates the cached file and immediately deletes it while writing to it. Therefore, `du -sh` did not show any file system usage. `df -h` on the other hand should show usage (in this case, the block storage on `/data` was too large to see the difference).

For the NFS case, nginx probably tries something similar, but there are `.nfsxxxyyyzzz` files in the directories (you probably cannot delete files on an NFS mount while keeping the file object?). That's why `du -sh` showed file system usage here.

**Comment by cdrojasm** [comment]
I'm sorry. I know that the issue was marked as completed, but I would like to know if was the proposed feature (a way to serve large files to multiple clients simultaneously) added to the current versions of CKAN ?

**Comment by paulmueller** [comment]
I believe not. I personally solved the issue by hosting the large files on S3 object storage and giving out presigned download URLs to users.

**Comment by cdrojasm** [comment]
Hi @paulmueller 

Thanks a lot for your response,

I only have a little doubt. It's possible for you to share a summary of your CKAN setup? Or give me any advice about what is the best approach to deal with this integration issue with S3? I see that they exist several extensions to integrate CKAN and S3, but I'm not sure about which is the best approach. Should I develop a custom implementation or integrate the existent extensions of CKAN? I found two extensions https://github.com/datagovsg/ckanext-s3-resources and https://github.com/ckan/ckanext-s3archive however seems that both have not been maintained recurrently. 

Best regards !!

**Comment by paulmueller** [comment]
AFAIK these extensions do not support presigned URLs. I have rolled my own implementation. You would want to do something like this: https://github.com/DCOR-dev/dcor_shared/blob/master/dcor_shared/s3.py#L50

**Comment by cdrojasm** [comment]
Thanks, I will check it
