### ISSUE TITLE
Unable to add/update groups using API. Validation Error

### ISSUE THREAD

**Issue by YukunYangNPF** [ckan/ckan#5935]
**CKAN version**
master

**Describe the bug**
I was trying to add groups when creating packages and updating packages, both failed.

`{'help': 'http://ec2-100-25-34-117.compute-1.amazonaws.com/api/3/action/help_show?name=package_update',
 'error': {'__junk': ["The input field [('group', 0, 'name')] was not expected."],
  '__type': 'Validation Error'},
 'success': False}`

**Steps to reproduce**
`groups=[{'name': 'fioa_awardee'}]`
`  res = requests.post(base+update_package,
                        data=json.dumps({
                            'name': dataset_name,
                            'group': groups,
    }),
                        headers={"X-CKAN-API-Key": api_key,
                                 'content-type': 'application/json'}
                        )`

**Expected behavior**
200

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by aleks-iv** [comment]
@YukunYangNPF It looks like you used wrong parameter name in data argument of POST request: "group" instead "groups".
Correct request:
`res = requests.post(base+update_package, data=json.dumps({ 'name': dataset_name, 'groups': groups, }), headers={"X-CKAN-API-Key": api_key, 'content-type': 'application/json'} )`
