### ISSUE TITLE
render_datetime helper does not respect ckan.display_timezone configuration

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5946]
**CKAN version**
N/A

**Describe the bug**
[`ckan.display_timezone`](https://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-display-timezone) sets the timezone to use when displaying dates on the frontend.  

The `render_date` template helper however,  still uses UTC even if `ckan.display_timezone` is set to a non-UTC timezone.

**Expected behavior**
`render_datetime` should respect the display_timezone setting.

**Comment by Zharktas** [comment]
`render_datetime` should respect display_timezone setting as it calls https://github.com/ckan/ckan/blob/5aad00921d68721decc0b31b7007d31e0b8b5c15/ckan/lib/helpers.py#L1709 which calls 
https://github.com/ckan/ckan/blob/5aad00921d68721decc0b31b7007d31e0b8b5c15/ckan/lib/helpers.py#L180 But of course there might be a bug in there.

**Comment by jqnatividad** [comment]
Yes. I thought so myself.

However, an earlier check on line 174 if a datetime has timezone info short-circuits it and never reaches line 180.

https://github.com/ckan/ckan/blob/5aad00921d68721decc0b31b7007d31e0b8b5c15/ckan/lib/helpers.py#L174-L182

**Comment by Sunny-NEC** [comment]
@Zharktas @jqnatividad   I would like to work in this issue But I have following queries :
                          -  Is this issue is specific to a version of CKAN ?
                          -  Where time is displayed in CKAN UI?

**Comment by TomeCirun** [comment]
Hi, @jqnatividad @Zharktas 

Im doing some research around this issue and i noticed few things:

I've changed `ckan.display_timezone` to different timezone than my local (e.g Canada/Saskatchewan) and commented out the javascript snippet (.automatic-local-datetime) 
![image](https://user-images.githubusercontent.com/72216462/124925913-3f7feb80-dffd-11eb-9e87-e52b072b898b.png)

As we can see the UI doesnt respect `ckan.display_timezone` and shows the UTC time.

I noticed that flask-babel [`format_datetime`](https://flask-babel.tkte.ch/#flask_babel.format_datetime) looks like converts the object to users timezone by default, if we pass `rebase=False` at line https://github.com/ckan/ckan/blob/master/ckan/lib/formatters.py#L55
it shows correct value.
![image](https://user-images.githubusercontent.com/72216462/124926717-2461ab80-dffe-11eb-9236-ce70999aa589.png)

What's your opinion over this?
