### ISSUE TITLE
Alternatives for adding duplicated keys for the extra?

### ISSUE THREAD

**Issue by YukunYangNPF** [ckan/ckan#5954]
**CKAN version**
master 
**Describe the bug**
Hello, I'm trying to add a field in the extra, called it "related chapter", however, one dataset could have multiple chapters related, but I cannot set multiple keys with the same name in the extra. Is there a way to circumvent this issue? Or I can only use groups or tags to do this. But I do want to group them into one category so I can search with facets.

**Steps to reproduce**
key: related chapter value: 1, 4 works

key:'realted chapter' value:1
key:'realted chapeter' value: 4 failed

**Comment by wardi** [comment]
[github just ate my comment, that's frustrating]

Free-form extras don't support repeating the same key multiple times.

Consider using ckanext-scheming instead. We just added support for `multiple_text` fields https://excess.org/scheming-subfields/#multiple-text and if your values are from a controlled list of choices you can also use `multiple_select` or `multiple_checkbox` presets with a choices list https://github.com/ckan/ckanext-scheming#preset

You can use these fields as facets by configuring the field as `multiValued="true"` in your solr schema.xml, e.g.
```xml
<field name="related_chapter" type="string" indexed="true" stored="true" multiValued="true"/>
```
