### ISSUE TITLE
Datastore doesn't support excel files

### ISSUE THREAD

**Issue by YukunYangNPF** [ckan/ckan#5962]
**CKAN version**
master

**Describe the bug**
I was trying to upload some xlsx files and have their previews. I've xloader installed to push them to the data store. However, it failed and return the error:
Error: Can't read Excel file: XLRDError('Excel xlsx file; not supported

**Comment by Zharktas** [comment]
[Messytables](https://github.com/okfn/messytables) which is used both in datapusher and xloader use [xlrd](https://pypi.org/project/xlrd/) to parse excel files, doesn't support xlsx files at all. CKAN itself does not parse csv or excel files, so the issue needs to be raised in messytables to support xlsx files.
