### ISSUE TITLE
Email validators block email addressees with space at  the end

### ISSUE THREAD

**Issue by VladimirZD** [ckan/ckan#5973]
**CKAN version**
2.9.2
**Describe the bug**
If you enter email address with space at the end, validators don't allow it. 
IT isn't major problem, but it would be nice if address can be trimmed before validating and saving..

**Steps to reproduce**
When creating new dataset in author email enter address with space at the end (or start) " test@example.com "

**Expected behavior**
Trim data before validation and saving

**Additional details**
For me this is big issue because i am harvesting data from older portals which don't have email validation, and some of resources are failing because they have spaces in email addresses..
IT can be fixed in harvester but i think this is better place..

**Comment by amercader** [comment]
@VladimirZD that makes sense. Actually a generic `trim_value` validator that is applied in most text fields would be a really good addition.
In the meantime you can implement a [custom schema](https://github.com/ckan/ckanext-scheming) for your extension and add the trim validator to the email field.

**Comment by Gauravp-NEC** [comment]
@amercader @VladimirZD , I am interested to work on this issue.

**Comment by amercader** [comment]
@Gauravp-NEC here's what I would suggest:

* Create a new `strip_value` validator in `validators.py` that trims whitespace at either end of the provided value. Something simple like:
    ```python
    def strip_value(value):
        return value.strip()
    ```
* Add it to the relevant (all?) text fields in the [dataset schema](https://github.com/ckan/ckan/blob/3ec23fec9f904019a246372e60ea228de258b6c3/ckan/logic/schema.py#L102) (and you can also add them to other schemas like the group, user, etc)
* Add a couple of tests in [test_validators.py](https://github.com/ckan/ckan/blob/master/ckan/tests/logic/test_validators.py)

**Comment by Gauravp-NEC** [comment]
@amercader @VladimirZD , I have raise the PR https://github.com/ckan/ckan/pull/6042 to fix this issue.
