### ISSUE TITLE
Following extensions tutorial for package-installed CKAN throws permission errors

### ISSUE THREAD

**Issue by reedv** [ckan/ckan#5986]
**CKAN version**
2.9.1

**Describe the bug**
Trying to follow the extensions tutorial (https://docs.ckan.org/en/2.9/extensions/tutorial.html ), but have the problem where I installed CKAN via package (https://docs.ckan.org/en/2.9/maintaining/installing/install-from-package.html ) which has you do things via `sudo` (actually the source install has you do this too), so when trying to use `ckan generate extension` I get errors whether I use `sudo` or not, eg...
```
(default) uadmin@myserver:/usr/lib/ckan/default/src$ sudo ckan generate extension
/usr/lib/ckan/default/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
...

Extension's name [must begin 'ckanext-']: ckanext-publicdatarestrictions
Author's name []: me
Author's email []:
Your Github user or organization name []: reedv
Brief description of the project []:
List of keywords (separated by spaces) [CKAN]:
/usr/lib/ckan/default/lib/python2.7/site-packages/arrow/arrow.py:28: DeprecationWarning: Arrow will drop support for Python 2.7 and 3.5 in the upcoming v1.0.0 release. Please upgrade to Python 3.6+ to continue receiving updates for Arrow.
  DeprecationWarning,
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  ...
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/generate.py", line 102, in extension
    output_dir=output_dir)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/cookiecutter/main.py", line 87, in cookiecutter
    dump(config_dict['replay_dir'], template_name, context)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/cookiecutter/replay.py", line 27, in dump
    raise IOError('Unable to create replay dir at {}'.format(replay_dir))
IOError: Unable to create replay dir at /home/uadmin/.cookiecutter_replay/



(default) uadmin@myserver:/usr/lib/ckan/default/src$ ckan generate extension
...
/usr/lib/ckan/default/lib/python2.7/site-packages/arrow/arrow.py:28: DeprecationWarning: Arrow will drop support for Python 2.7 and 3.5 in the upcoming v1.0.0 release. Please upgrade to Python 3.6+ to continue receiving updates for Arrow.
  DeprecationWarning,
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
...
  File "/usr/lib/python2.7/shutil.py", line 262, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/cookiecutter/utils.py", line 25, in force_delete
    os.chmod(path, stat.S_IWRITE)
OSError: [Errno 2] No such file or directory: '/usr/lib/ckan/default/src/ckanext-publicdatarestrictions'
```
(Note: tried deleting /home/uadmin/.cookiecutter_replay/ and retrying w/ sudo but still no progress).

Am I doing something wrong here? Misunderstanding something? I installed via package just based on the docs which had me use `sudo` to install into dirs natively owned by root, but it seems like that's now an issue here.

**Steps to reproduce**
1. Install CKAN 2.9.1 via package, while singed in as a non-root user, w/ docs: https://docs.ckan.org/en/2.9/maintaining/installing/install-from-package.html 
2. Attempt to run `sudo ckan generate extension` or `sudo ckan generate extension` (per the docs https://docs.ckan.org/en/2.9/extensions/tutorial.html )

**Expected behavior**
Generate extension template folder in location from which the `generate extension` command is being called.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by reedv** [comment]
Fixed the issue by using the command...
```bash
sudo /usr/lib/ckan/default/bin/ckan generate extension
```
...(after recalling a similar experience I had (https://github.com/NaturalHistoryMuseum/ckanext-ldap/issues/65#issuecomment-781277591 )).

Is this a bug of something? Are the docs not right?

**Basically, even though the virtualenv is active (as can be seen by the (default) at the start of the bash command lines I entered), when you use `sudo` the system python is used not the virtualenv**.

I would think this would be a problem everyone would run into if they tried following the docs as they are. Is there some obvious underlying issue implied by my problem that I'm missing here?

**Comment by amercader** [comment]
@reedv I think the main issue here is that the expectation is that users will use the [source install](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html) when developing extensions. In fact this is one of the scenarios listed in the main install page:

> You should install CKAN from source if:
> [...]
> * You want to install CKAN for development

A development setup using a package install, although possible doing some workaround (as you've found out), is not recommended and we don't support it.
I'm going to close this issue, but feel free to suggest any changes to make this clearer. Cheers.
