### ISSUE TITLE
UI Shows in English When Traditional Chinese or Simplified Chinese Is Selected

### ISSUE THREAD

**Issue by spectatorcharlie** [ckan/ckan#6010]
**CKAN version**
CKAN 2.9.2

**Describe the bug**
UI shows in English even though Traditional Chinese or Simplified Chinese is selected under Language.

**Steps to reproduce**
1. Open localhost:5000
2. Select Traditional Chinese or Simplified Chinese under Language
3. UI still shows in English

**Expected behavior**
UI should be displayed in Traditional Chinese or Simplified Chinese

**Additional details**
![1](https://user-images.githubusercontent.com/81850880/114396278-f839b880-9bcf-11eb-8ae3-d2a5555aaa70.png)

**Comment by amercader** [comment]
@spectatorcharlie This was reported in #4413 and I pushed a potential fix here: https://github.com/ckan/ckan/pull/6008
Would be great if you could try it out and provide feedback in the pull request, thanks!
