### ISSUE TITLE
Bootstrap 5 Upgrade

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#6012]
The release of Bootstrap 5 is fast approaching and at the time of this writing beta3 is already released. There is old unfinished PR #5423 and it's probably smarter to upgrade straight to Bootstrap 5 instead of finishing the upgrade to 4 and then upgrade again in the near future.

This requires migrating from less to sass which has been used by bootstrap since bootstrap 4.
* Convert all less files to sass, some tool probably can be used to do this.
* Replace build tool from [Less](https://www.npmjs.com/package/less) to [Sass](https://www.npmjs.com/package/sass) 
* Update [Gulpfile](https://github.com/ckan/ckan/blob/master/gulpfile.js) to compile sass instead of less.
* Update documentation related to less.

We want to keep compatibility with Bootstrap 3 at least for one ckan version, so upgrading templates should have a flag in ckan configuration which version to use, similar to [Bootstrap3 upgrade](https://docs.ckan.org/en/2.8/maintaining/configuration.html#ckan-base-public-folder) had.
* Copy current templates to templates-bs3.
* Copy current public libraries to public-bs3.
* Add configuration flag for choosing which templates to use.
* Upgrade templates in templates folder.
* Update Gulpfile to copy bootstrap files to both public-bs3 and public.
* Update documentation to reflect upgrade of bootstrap and the new configuration flag.

**Comment by amercader** [comment]
@Zharktas Could point 1 (less -> sass) be done independently with the current Boostrap 3 templates? Maybe using something like https://github.com/twbs/bootstrap-sass in the interim until we don't move to 5. Or is it not worth it and makes sense to do it all in one go?

**Comment by Zharktas** [comment]
@amercader yes, sass conversion can be done with bootstrap3. There is a official port of bs3 for sass https://github.com/twbs/bootstrap-sass

**Comment by Zharktas** [comment]
And I think it would make sense to make it as separate PR, so it would merged faster to master.

**Comment by sagargg** [comment]
@Zharktas  I'm interested in this,  are we planning to migrate bootstrap 3 less ==> sass independently and then upgrade bootstrap 5 in a separate PR? Why we shouldn't do direct upgrading?

**Comment by anuveyatsu** [comment]
@sagargg I believe this is to make reviewing and merging PRs easier.

**Comment by Zharktas** [comment]
Bootstrap upgrade in itself is already a major effort, migrating to sass can be separated and as such should be so that something is eventually finished.

**Comment by Zharktas** [comment]
Only sass migration was done.

**Comment by Zharktas** [comment]
Done in #6307
