### ISSUE TITLE
Centos Ckan: can open http://localhost:5000, but not http://myIP:5000，and also failed to log in ckan

### ISSUE THREAD

**Issue by chenxj2020** [ckan/ckan#6032]
CKAN 2.9.2 on Centos 7

When I run ckan test, I can open http://localhost:5000, but can not open http://myIP:5000，it shows that: unable to connect.
In addition, when I log in ckan with the default username and password, it shows the same result as opening http://myIP:5000.

Appreciated for any reply.

**Comment by kowh-ai** [comment]
Are you running the **Dev server** `ckan -c /etc/ckan/default/ckan.ini run`? 

If so are you passing the `--host` and `--port` args in too?

**Comment by chenxj2020** [comment]
Thank you.

 Yes, I run ckan test by commands:
 ckan -c /etc/ckan/default/ckan.ini db init  (it shows Initialising DB: SUCCESS),
 ckan -c /etc/ckan/default/ckan.ini run

But I didn't see any information about "passing the --host and --port args".
Do I need to set some parameters? Where to set?

Thank you very much.

**Comment by kowh-ai** [comment]
Check out https://docs.ckan.org/en/2.9/maintaining/cli.html

**Comment by chenxj2020** [comment]
Thanks for all the answers
