### ISSUE TITLE
 h.url_for not working in some templates

### ISSUE THREAD

**Issue by pauldcollins** [ckan/ckan#6043]
**CKAN version**
2.8

**Describe the bug**
I'm having trouble using `h.url_for` in the `resource_read.html` template. I can't see what I need to import to be able to use it, so I'm not sure if it's an error.

Basically, I'm trying to copy the link from the `resource_view.html` page and use it in the `resource_read.html` template. But for some reason it breaks when I use `h.url_for`

`href="{{ h.url_for('resource_view', id=package['name'], resource_id=resource['id'], view_id=resource_view['id'], qualified=True) }}"`

**Steps to reproduce**
Copy above line into the `resource_read.html` file
https://github.com/ckan/ckan/blob/2.8/ckan/templates/package/resource_read.html

**Expected behavior**
It should go to the URL, as it does in the `resource_view.html` page.
https://github.com/ckan/ckan/blob/2.8/ckan/templates/package/snippets/resource_view.html

**Comment by Zharktas** [comment]
I doubt url_for is the issue here. When you copy and paste helper calls between templates and it fails, you probably are missing some variable from the new template. It should tell you why it fails in the logs or in the UI itself if you turn on the debug mode.

**Comment by pauldcollins** [comment]
Thanks @Zharktas for your email, you were correct - it's not the `url_for` that's the issue. I've managed to get it working, more or less - at least the page is no longer breaking but I have one last problem. 

The `view_id` is not being passed correctly, which means the **Resource View** page is producing a 404 when I click to it. The original code from the  `resource_view.html` file uses `view_id=resource_view['id']`, but **resource_view** is not available to me in this template. 

I've logged out all the available variables, but I can't see any option. To sum it up, I just want to be able to access the value of `resource_view['id']` inside the `resource_view.html` template. 

Thanks for any help.

**Comment by Zharktas** [comment]
@pauldcollins in `resource_read.html` the resource view is parsed here https://github.com/ckan/ckan/blob/1e10689a4e9936069cb1c0b2fc8bf630c530c246/ckan/templates/package/resource_read.html#L114...L122 as there can be multiple resource_views.

**Comment by Zharktas** [comment]
But as this is not a bug in CKAN and is more of support request, I'll convert this to discussion.
