### ISSUE TITLE
Small error in Macedonian translation

### ISSUE THREAD

**Issue by ElenaKusevska** [ckan/ckan#6071]
**CKAN version**
2.8.2-2.9.2

**Describe the bug** 
There is a minor error in the Macedonian ("mk") translation of CKAN. The string "upload resource" is incorrectly translated. 

---------------------

I would like to correct this. Is it possible to include the correction in older ckan versions as well? We have some older projects that are still running on ckan 2.8.7.

**Comment by tino097** [comment]
@ElenaKusevska please check the translations to [transifex](https://www.transifex.com/okfn/ckan/language/mk/)

**Comment by ElenaKusevska** [comment]
@tino097 I just sent a request to join the team for Macedonian translations. I can't view the link otherwise. By the way, sorry, I'm a new to CKAN, how often do you update the translations in CKAN from transifex?

**Comment by tino097** [comment]
@amercader can you please add @ElenaKusevska  to [Macedonian translation](https://www.transifex.com/okfn/teams/11162/mk/) team on transifex

@ElenaKusevska we have few efforts to translate a bit more but at the end we end translating only with 2.8 and 2.9 releases.

**Comment by ElenaKusevska** [comment]
@tino097 Thanks for the reply. 2.8 and 2.9 is what we need at the moment. By the way, if we make the correction on transifex, when does it get included in the translations on the ckan repo?

**Comment by tino097** [comment]
@ElenaKusevska it will be in the next patch releases

**Comment by ElenaKusevska** [comment]
@tino097 Thank you. I'll look into the translations when I have access.

**Comment by amercader** [comment]
@ElenaKusevska you should have access now!

**Comment by amercader** [comment]
@ElenaKusevska to your question, yes, if you update the translation on Transifex it will be included in the next patch release.

**Comment by ElenaKusevska** [comment]
@amercader Thank you :)

**Comment by ElenaKusevska** [comment]
@amercader Will that be for older versions of ckan (2.8.7), or only the latest one (2.9.2)?

**Comment by ElenaKusevska** [comment]
@amercader Sorry for asking before checking. I just saw that you have translations for each version of ckan.

**Comment by amercader** [comment]
@ElenaKusevska whichever you update on Transifex! If you update both the ckan-2.8 and ckan-2.9 resources it will be available to both.

No worries, ask as much as you need.

**Comment by ElenaKusevska** [comment]
@amercader Thank you :)

**Comment by ElenaKusevska** [comment]
@tino097 The same typo is present in both the ckan-2.8 and the ckan-2.9 version of the translation on transifex. "update resource" is translated as "ажурирајње на ресурс". There's an extra j. I submitted the suggestion for both versions.

**Comment by tino097** [comment]
@ElenaKusevska i think you can do the translations too

**Comment by ElenaKusevska** [comment]
@tino097 Thank you :)
