### ISSUE TITLE
"AttributeError: 'CKANTestApp' object has no attribute 'reset'" when using FunctionalTestBase

### ISSUE THREAD

**Issue by adborden** [ckan/ckan#6074]
**CKAN version**
2.9.2

**Describe the bug**
Updating my extension for CKAN 2.9 and getting this error when extending with FunctionalTestBase during the `setup()`
> AttributeError: 'CKANTestApp' object has no attribute 'reset'

**Steps to reproduce**
1. Create a test that extends FunctionalTestBase

```
from ckantoolkit.tests.helpers import FunctionalTestBase
import ckanext


class TestPlugin(FunctionalTestBase):

    def test_plugin(self):
        pass
```

2. Run your test, e.g. `pytest --ckan-ini=test.ini --disable-warnings ckanext/datagovtheme/tests/test_datagovtheme.py`

**Expected behavior**
Test passes, maybe with a deprecation warning

**Additional details**
```
bash-5.1# pytest --ckan-ini=test.ini --disable-warnings ckanext/datagovtheme/tests/test_datagovtheme.py                                                                           
2021-05-06 13:46:20,806 INFO  [ckan.cli] Using configuration file /app/test.ini
2021-05-06 13:46:20,807 INFO  [ckan.config.environment] Loading static files from public
2021-05-06 13:46:20,876 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2021-05-06 13:46:21,473 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
================================== test session starts ===================================
platform linux -- Python 3.8.7, pytest-4.6.5, py-1.10.0, pluggy-0.13.1
rootdir: /app
plugins: ckan-0.0.12, rerunfailures-8.0, split-tests-1.0.9, Faker-6.5.0, cov-2.7.1, pyfakefs-3.2, freezegun-0.4.1
collected 1 item

ckanext/datagovtheme/tests/test_datagovtheme.py E                                  [100%]

========================================= ERRORS =========================================
________________________ ERROR at setup of TestPlugin.test_plugin ________________________

self = <ckanext.datagovtheme.tests.test_datagovtheme.TestPlugin object at 0x7f54aa0d6460>

    def setup(self):
        """Reset the database and clear the search indexes."""
        reset_db()
        if hasattr(self, "_test_app"):
>           self._test_app.reset()
E           AttributeError: 'CKANTestApp' object has no attribute 'reset'

/srv/app/src/ckan/ckan/tests/helpers.py:361: AttributeError
--------------------------------- Captured stdout setup ----------------------------------
2021-05-06 13:46:21,970 INFO  [ckan.config.environment] Loading static files from public
2021-05-06 13:46:22,030 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2021-05-06 13:46:22,143 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2021-05-06 13:46:23,032 INFO  [ckan.model] Database tables dropped
2021-05-06 13:46:24,817 INFO  [ckan.model] CKAN database version upgraded: base -> ccd38ad5fced (head)
2021-05-06 13:46:24,817 INFO  [ckan.model] Database initialised
2021-05-06 13:46:24,817 INFO  [ckan.model] Database rebuilt
----------------------------------- Captured log setup -----------------------------------
INFO     ckan.config.environment:environment.py:94 Loading static files from public
INFO     ckan.config.environment:environment.py:273 Loading templates from /srv/app/src/ckan/ckan/templates
INFO     ckan.config.environment:environment.py:273 Loading templates from /srv/app/src/ckan/ckan/templates
INFO     ckan.model:__init__.py:215 Database tables dropped
INFO     ckan.model:__init__.py:319 CKAN database version upgraded: base -> ccd38ad5fced (head)
INFO     ckan.model:__init__.py:204 Database initialised
INFO     ckan.model:__init__.py:236 Database rebuilt
========================== 74 warnings, 1 error in 3.05 seconds ==========================
```

I think `reset()` used to be defined from CKANTestApp extending `webtest.TestApp`, but it no longer does in 2.9. webtest is included in requirements-py2.txt, but I'm not seeing it used anywhere in the code.

Also, the deprecation of FunctionalTestBase wasn't called out in the [2.9 changelog](https://docs.ckan.org/en/2.9/changelog.html) nor is it mentioned in the [Python 3 extension upgrade guide](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions) (thank you for providing these resources), so I was pretty confused to run into this error.

I'm trying to write the extension tests so that they are compatible for both 2.8 and 2.9 (py3), so looking for the simplest change to get that working.

**Comment by adborden** [comment]
FYI, to work around, we moved to pytest, dropped FunctionalTestBase, and using the pytest app auto fixture.

**Comment by amercader** [comment]
@adborden yes, as you found out [`FunctionalTestBase`](https://docs.ckan.org/en/2.9/contributing/testing.html?highlight=functionaltestbase#ckan.tests.helpers.FunctionalTestBase) is deprecated and replaced by pytest fixtures. We should have added this in the CHANGELOG, but I added a note on the Py3 migration guide for extensions now.

Most major extension are migrated now to support CKAN 2.9 / py3 so you can have a look at their test suites for common test patterns (eg [ckanext-scheming](https://github.com/ckan/ckanext-scheming), [ckanext-harvest](https://github.com/ckan/ckanext-harvest), [ckanext-dcat](https://github.com/ckan/ckanext-dcat)). Also note that if you need to run the tests on both pre 2.9 and above you can use the [pytest-ckan](https://github.com/datopian/pytest-ckan) external package.
