### ISSUE TITLE
Allow `*_activity_list` actions to filter by `activity_type`

### ISSUE THREAD

**Issue by chris48s** [ckan/ckan#6106]
**CKAN version**: 2.9

It would be helpful if the `*_activity_list` actions had the ability to optionally accept a list of `activity_type`s to filter by.

e.g:

```py
get_action('package_activity_list')(context, {
    'id': 'my-dataset',
    'activity_types': ['changed package'],
})
```

- The default would be that all activities associated with `id` are returned (as it is now).
- Passing `activity_types` would filter to only the specified activity types.

This would be particularly useful for plugin authors leveraging custom activity types.

**Comment by amercader** [comment]
I think this will make life for extension developers much easier.
Perhaps it would make sense to have two different parameters:
* `include_activity_types`: only return activities of these types
* `exclude_activity_types`: ignore activities of these types

The implementation would not be much more complex and I can see both being useful in situations I've encountered working with custom activities.

**Comment by avdata99** [comment]
FYI @amercader. I started this: https://github.com/ckan/ckan/pull/6123
