### ISSUE TITLE
Fix activity pagination in web UI

### ISSUE THREAD

**Issue by chris48s** [ckan/ckan#6108]
**CKAN version**: 2.9

**Describe the bug**

"Activity Stream" pages only show the first `activity_list_limit` activities.
In some previous version of CKAN there would be a "load more" button linking to the next page of activities, but the list just ends once there are more than `activity_list_limit` activities:

with less than  `activity_list_limit` activities:
![Screenshot at 2021-05-20 11-20-29](https://user-images.githubusercontent.com/6025893/118970354-06fd5300-b966-11eb-87a8-8467714bc25c.png)

with more than  `activity_list_limit` activities:
![Screenshot at 2021-05-20 11-21-46](https://user-images.githubusercontent.com/6025893/118970362-095fad00-b966-11eb-8f3c-57c075dd988c.png)

There is some code in https://github.com/ckan/ckan/blob/ckan-2.9.2/ckan/templates/activity_streams/activity_stream_items.html which does look like it should implement the 'Load more' pagination functionality, but I don't think it is currently used/working.

**Steps to reproduce**

Create more than `activity_list_limit` activities on a dataset/org/etc
Look at the "Activity Stream" page

**Expected behavior**

There should be a "Load More" button linking to the next page of activities.
The pagination should respect the value of `activity_list_limit`.

**Comment by avdata99** [comment]
I plan to tackle this @amercader

**Comment by Sunny-NEC** [comment]
@avdata99  Request you to please pickup another issue as currently I am working on this issue and it is in progress.

**Comment by Sunny-NEC** [comment]
@chris48s did the load more functionality was developed for some previous version of CKAN? i have checked CKAN version 2.8.2 , 2.8.4 , 2.8.8 but did not find any load more functionality.

**Comment by chris48s** [comment]
I think this was broken in 2.8 as well - at least the later versions. By the looks of it `activity_stream_items.html` was last touched in 2017. It might be necessary to go back to version 2.7.x for a version where that worked.
