### ISSUE TITLE
Activity Stream notification email does not include root_path

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#6116]
**CKAN version**
2.8, 2.9, master

**Describe the bug**
If email notifications are enabled for activity stream, the email includes a link to the users dashboard. These links are generated by using site_url which does not include root_path.

https://github.com/ckan/ckan/blob/0ab924d5ea331625bd61a805f23c68a17f028193/ckan/templates/activity_streams/activity_stream_email_notifications.text#L3-L7

**Steps to reproduce**
Enable activity stream emails, configure root_path, check email after updates.

**Expected behavior**
URLs should have root_path included.

**Additional details**
Related issue #5823, I've been thinking that we need a helper to generate site_url + root_path and document it for extensions.

**Comment by Zharktas** [comment]
url_for should be fixed so that it can be used for the cli and perhaps create a helper which would be intuitive for extension developers to generate URL to root.

**Comment by Gauravp-NEC** [comment]
@Zharktas , I am interested to work on this issue.  How can I configure root_path?

**Comment by Sunny-NEC** [comment]
@Zharktas Regarding this issue  could you please share the use case for the email extension.
