### ISSUE TITLE
Spec: Table Designer Feature

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#6118]
This is a description of a new "Table Designer" feature for CKAN. Table Designer provides custom enforced data schemas that supporting partial updates, suitable for reference data or data that is regularly updated. Users can build a data schema interactively then load data using auto-generated Excel templates, with a web form or via the API.

Table Designer relies on the datastore extension and its default postgresql back end, so this feature could be implemented as a core extension like datastore, an improvement to the datastore extension or as a core change (though it's a little odd to have a core feature depend on an extension)

This work is based on the well-loved and battle-tested data schemas from the [recombinant extension](https://github.com/open-data/ckanext-recombinant/), scheming-style data forms and datatables data view from the [canada extension](https://open-data/ckanext-canada/). Instead of [json/yaml schemas](https://github.com/open-data/ckanext-canada/tree/master/ckanext/canada/tables) and one-table-per organization, Table Designer allows user-designed data schemas at the individual resource level.

## A 3rd Way to Create CKAN Resources

Table Designer begins from the resource creation form. Instead of uploading a resource or providing a link, users select "Use Table Designer" to create a Table Designer resource. This creates a datastore-only resource with an empty datastore table with no columns defined, [*future:* or a set of columns copied from an existing resource].

Table Designer resources have a modified data dictionary form with no "Type Override" field (datapusher/xloader don't apply) but with a new "Type" drop-down, "Primary Key"/"Required" check boxes and a set of fields to control input validation. A new button at the bottom allows users to "Save and Add a new Column"

## Table Designer Schemas

Schemas will be saved like other data dictionary fields, but with enforced data dictionary validation [*to discuss:* we need a way to hook this up]. Schemas may also be created with `datastore_create` instead of using the data dictionary form.

[*future:* A new endpoint is available to partially export these schemas as JSON Schema where column validation rules map cleanly to JSON Schema rules].

Built-in validation rules include enforcing values are from a controlled list (single choice or multiple choice stored as a normalized text array), values within a range, and values conforming to a set of postgresql data types: int, numeric, date, etc.

[*future:* New validation rules can be added with plugins implementing a new ITableDesigner interface. Validation rules need to be defined in pl/pgsql for enforced validation as well as in Excel formulas for interactive validation within generated Excel templates. Validation can be conditional between fields in the same row; this is a frequent requirement for evolving data schemas, e.g. [the buyer name field in open.canada.ca's "contracts over $10K" data](https://github.com/open-data/ckanext-canada/blob/834a75a78d7bfca8552c3bdb6ba374b7759840e5/ckanext/canada/tables/contracts.yaml#L179)]

Validation is enforced with a trigger function created by Table Designer that reads the schema from the data dictionary and enforces them on a per-row basis. All errors in a row are returned together but only the errors for the first failing row is returned when more than one row is passed to `datastore_upsert`. This is sufficient to implement a web form with per-field error messages returned to the user, and is easy for API users to parse too.

## Excel Templates

![td-excel-errors](https://user-images.githubusercontent.com/153258/119753811-63340b80-be6d-11eb-83af-1537045e0f60.PNG)

Many data catalogue users love working in Excel. Excel templates, automatically generated from the schema, help meet these users in their preferred environment. Excel templates include immediate interactive feedback showing errors (red in screenshot above) and missing values (blue in screenshot above) as users type or paste data from other systems.

![td-reference](https://user-images.githubusercontent.com/153258/119753835-6f1fcd80-be6d-11eb-98ca-30347b8f5e0d.PNG)

Reference information is generated in a second tab. All controlled list codes and column descriptions are available by clicking on any column heading.

Excel templates allow users to create and update ("upsert" based on records with matching primary key values) many records at once. Data uploaded with these templates is processed immediately, never stored on the server in Excel format. These templates are suitable for manually uploading a few thousand records at a time; the `datastore_upsert` API is recommended for larger numbers of records.

![td-select](https://user-images.githubusercontent.com/153258/119753865-7f37ad00-be6d-11eb-9e2e-dc634f804995.PNG)

Existing records may be selected from a modified datatables view and downloaded in a pre-populated template by clicking "Edit in Excel". Users are encouraged to use this feature to update records instead of keeping copies of populated templates, in case they re-upload and accidentally revert someone else's changes. 

## Web Forms

![td-form](https://user-images.githubusercontent.com/153258/119753879-852d8e00-be6d-11eb-8202-3af648f903ee.PNG)

A web form is generated from the schema for creating and editing records. This makes entering or correcting a small number of records possible without leaving the website. Existing records may be edited by clicking "Edit" on a row in a modified datatables view and records can be created by clicking "Create a Single Record".

[future: Custom form fields can be added with plugins implementing a new ITableDesigner interface. Snippets are used for form fields similar to the ones used in ckanext-scheming.]

Form validation is implemented by parsing errors returned from the `datastore_upsert` call and used to mark errors any errors on the individual fields.

**Comment by wardi** [comment]
Some great feedback from dev call:
- ITableDesigner could have a better name. IDatastoreValidation?
- can we separate the excel and form ingestion interfaces from the core feature and make them plugable?
  - yes, but the required validation implementations and table designer schema forms depend on the ingestion interfaces, i.e. formulas+column widths for excel and snippets+js for the form, how do we manage this?

**Comment by wardi** [comment]
Would be amazing if we had a common way to specify validation rules that could generate all possible types of concrete validation (pl/pgsql, excel formula, javascript form, ...) but this would also prevent us from doing really cool things that are possible in each like pl/pgsql being able to look up values in another table or javascript calling out to a web service

**Comment by jqnatividad** [comment]
Awesome!
For the Table Designer schema, are you considering using [Table Schema](https://specs.frictionlessdata.io/table-schema/#language), and leveraging the [Frictionless Framework](https://github.com/frictionlessdata/frictionless-py)(
née goodtables)?

And for the Excel template, it'd be great if you can do as much validation on Excel as possible.  Having experimented with the recombinant extension  before, I know how powerful it is to use a familiar UI which folks use on an everyday basis to accelerate adoption.  Perhaps, with [xlwings](https://github.com/xlwings/xlwings), more validation can be done in Excel to enforce [constraints](https://specs.frictionlessdata.io/table-schema/#constraints)?

Having recently worked on the DataTables view, I'd be keen to leverage the Table Designer schema to automatically apply extended formatting for each column - e.g. applying the right date display format, displaying currency with the right currency symbol while still treating it as a numeric value, rendering data with alternate display elements (e.g. traffic light, star rating, etc.).

Maybe, even optionally support [semantic rich types](https://specs.frictionlessdata.io/table-schema/#rich-types) to go beyond simple data type/constraint validation - e.g. country codes, https://schema.org/Quantity, https://schema.org/MonetaryAmount, to not only inform validation, but to embed semantic metadata to make the data dictionary created by the Table Designer even more useful.

**Comment by wardi** [comment]
@amercader WDYT about implementing this feature two plugins:
- table designer schemas + modified datatable view + web form --> a core `tabledesigner` extension
- excel data templates and ingestion --> a core or external `exceltemplates` extension

In my mind separating out the web forms would leave us with half a feature - web UI for designing data validation but no UI for loading data.

**Comment by wardi** [comment]
New resource model field discussion and feedback:

- `datastore_active`
  - currently an optional resource extra value that is clumsy to update from `datastore_create`, datapusher or xloader
  - typically updated separate from any other resource metadata field, related to tables in separate db
  - let's migrate from resource extras to a normal boolean in the model and default resource schema to formalize this important feature and clean up code
  - general agreement in dev call that this is a good change

- `datastore_only`
  - informally indicated by "_datastore_only" string in url field when resource is created by `datastore_create`
  - we need a clear flag that indicates to datapusher or xloader that this resource is off-limits
  - could the `url_type` field be used instead?
    - currently a string field with no validation that is either blank or set to "upload" for uploaded files
    - may have been reused or extended by customized schemas, so a small chance of breaking existing sites
    - need to add a controlled list, something like ['' = normal url, 'upload' = uploaded file, 'datastore' = datastore only] ?
    - my preference is to add this as a new boolean field. `if resource['datastore_only']:` reads better to me than `if resource['url_type'] == 'datastore'`
  - discussion but no agreement in dev call

- `table_designer`
  - new boolean field to indicate that user clicked "Use Table Designer" to create a Table Designer resource
  - my preference is to add this as a new core boolean field.
    - like datastore I believe this will become a significant core feature of ckan that will be extended and relied on by most of our users
    - by adding `table_designer` to the core resource validation schema the field will be inherited by custom dataset schemas automatically so users can take advantage of table designer with no changes
    - downside: people not using table designer will have a `"table_designer": false` in all their resource metadata

There have been other cases where we've wanted to have custom behaviour for different types of resource, like resource views (datastore only again) that allowed users to input SQL to create a materialized view of data in other datastore resources. We might want a solution that keeps these sort of future uses in mind. At the same time, developing a feature in a simple way that works should win over getting stuck in design analysis paralysis.

**Comment by amercader** [comment]
@wardi here are some long overdue thoughts on this. 

Overall I think the proposed feature is a really powerful one that will add a lot of value to CKAN and enable a lot of interesting use cases.

Having said that I'm struggling a bit to wrap my head around the whole thing in terms of implementation so let's just focus first on the basic feature: creating a "Hosted resource" with a data table that only lives in the DataStore (as opposed to a link to a file or an uploaded file) and park the Excel side for now. For anyone reading, "datastore only resources" are now possible, but only via API calls [1].

Making this available to general users via the frontend would involve:

* Defining the structure of the table: fields, types
* (optional) Defining the validation rules for the fields
* Provide a web interface for data input

I think this is in alignment with the `tabledesigner` plugin that you suggest [here](https://github.com/ckan/ckan/issues/6118#issuecomment-850421612). The only thing I'm not clear why is needed at this level is the modified datatables view, can you give more details on why this is needed here?

On defining the table schema, I know I've raised it in the past but I still feel like there was an opportunity missed by not leveraging [Table Schema](https://specs.frictionlessdata.io/table-schema/#language) and the tooling around it, including [components](https://github.com/frictionlessdata/tableschema-ui) for rendering form UIs for it. It seems a bit awkward to store information like the field types in Postgres itself as column comments rather than at the resource metadata level. In fact there was an [old proposal](https://github.com/ckan/ideas/pull/160/files#diff-57142ead1472ad6ed1b45656bfb130822c896446981d13455c6ddc1c18d25fe7R124) that never materialized to add new resource model fields for `schema`, `schema_type` and `schema_version`  to allow other tools like [frictionless](https://github.com/frictionlessdata/frictionless-py) to use it for validation, export to other systems etc. I guess we can always add a compatibility layer and translate the info stored in postgres to a Table Schema and add it to `schema`.

Validation is the major thing I'm struggling to understand here. Is this only performed via pl/pgsql functions? ie when you say:

> Built-in validation rules include enforcing values are from a controlled list (single choice or multiple choice stored as a normalized text array), values within a range, and values conforming to a set of postgresql data types: int, numeric, date, etc.

Are these pl/pgsql functions that CKAN (or rather the `tabledesigner` plugin) creates when installing it? At some point you also mention javascript/form functions, does the form perform additional checks or you just submit the data, Postgres fails and an error response is shown to the user?

I guess some of my reticence here is to propose Pl/pgsql as the way for users to define their data validation logic. I never found any project where users had this expertise (I certainly don't have it) but that might be just my personal experience. So I wonder if it would be possible to provide a hook in the ingestion endpoint (the one the web form submits to) so plugins can validate the data before it hits Postgres (and I understand that this might be less performant). Something that allows to call frictionless, your own python scripts or whatever system they prefer.

Sorry, I know this was a bit rambling and it only covers half of your proposal. And to be clear, I'm not opposed to anything proposed, I just need a bit more clarity (or convincing) on some bits :)


---
[1] You need to call [`datastore_create`](https://docs.ckan.org/en/2.9/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_create) passing `resource={"package_id": <PACKAGE_ID>}` to create the table and `datastore_upsert` to add data afterwards

**Comment by wardi** [comment]
Thank you for this @amercader

A modified datatables view is required to preview the data that has been loaded and allow users a way to:
1. select records to delete
2. click to edit individual records in a form

datatables is great for this because it can be easily extended and has search, filtering and pagination built-in. See the 3rd screenshot above for an example of how this could look. 

Column types are already stored at the datastore level because our db needs to know them. Storing column types again at the resource level means we would need to sync changes in two directions somehow, and have a way to fix one or the other when they go out of sync (e.g. when restoring from a backup of your datastore db, or when an external tool like xloader or a postgresql integration creates the table). When users want to have a json-schema or similar in their resource metadata we're better off translating the table designer schema with a separate plugin at `package_show` time.

Thank you for pointing out table schema. I think table schema is a great target for the validation that could come by default with table designer. It's also important to be able to implement client's business rules that go beyond table schema rules[1]. For these cases sites could develop plugins to define new types of validation. I chose to implement rules like this in ckanext-recombinant with pl/pgsql for a few reasons:
1. flexibility only available with a real programming language
2. operations at the db level are fast[2] and strongly typed
3. data types exactly match what is stored in the db (critical for audit/tracking changes[3])
4. data that is side-loaded for performance reasons will be validated too

Users wouldn't be expected to provide pl/pgsql rules, they would be baked in to table designer and any plugins that add validation rules. The validation rules are implemented as a trigger function that collects and raises an error string in a specific format so that `datastore_upsert` can format the error messages as a row number and a json dict with column names and lists of errors for each column.

I agree it is important to provide a hook for plugins to validate data in python before it hits postgresql. In ckanext-recombinant we do this to handle some errors like passing invalid dates to date columns, because postgresql will reject the data before calling any trigger function. The same hook could be used to define validation in python if preferred.

---
[1]: we enforce validation for these real client business rules in our "contracts over 10K" dataset:
- field is limited to only 3 or 4 digits or "NA". if "NA", then [other field] must be equal "SOSA"
- mandatory if [other field] > 2019-01-01 unless [third field] is not blank
- select 1 or more values from [controlled list] and normalize the order of selections, but if "00" is selected no other values may be selected
- must be set to "N" if [other field] is "NS" or "VS"
- select from [controlled list] but some values are discontinued and not allowed if [other field] > [selection discontinued date]

[2]: Our users interactively upload and validate a few thousand rows of data at a time. No server side background job or async notification required

[3]: we chose to add columns that track the time any row was created and last modified, and another column automatically populated with the username that last modified the row. This feature reliably ignores rows re-uploaded with no changes by comparing the data in each row at the database level after validation.

**Comment by KatiRG** [comment]
What do you think about which field types to support? Postgres supports numeric array types such as e.g. integer array `integer[]`, but [frictionless](https://specs.frictionlessdata.io/table-schema/#types-and-formats) does not. So far in the `column_types.py` file you have the standard data types that frictionless supports. We haven't seen numeric arrays used in the datasets we intake, so it's an edge case for us, but surveying the larger community here...

**Comment by wardi** [comment]
@KatiRG in the precursor to this feature we make frequent use of `text[]` for multiple-select choice columns but have yet to need `int[]`. `IColumnTypes` should allow developers to add any types they need specific to their use case, including the postgres array types, so we have some cover and don't need to implement everything immediately.
