### ISSUE TITLE
Editor cannot add resource to a dataset

### ISSUE THREAD

**Issue by maxclac** [ckan/ckan#6127]
**CKAN version**
2.9.2

**Describe the bug**
A user with editor status cannot add a resource to a dataset, even though he is part of the organization where this dataset is located. When he tries to do so on the UI, he gets an "Internal server error" in the browser

**Steps to reproduce**
A sysadmin user adds this user with editor status to the organization where this dataset is located.

**Expected behavior**
The editor should be able to add a resource to the dataset.

**Additional details**
CKAN instance installed from source on Ubuntu 20.04

**Comment by tino097** [comment]
@maxclac are you using any other extensions that could override some of the core functionality ?
And if possible can you share the error trace log 

My testing doesnt reproduce the error
