### ISSUE TITLE
Erroneous command in documentation, in "Installing CKAN with Docker Compose" page

### ISSUE THREAD

**Issue by sdinot** [ckan/ckan#6128]
CKAN documentation, version 2.9.3 or latest

In the [3. Datastore and datapusher](https://docs.ckan.org/en/latest/maintaining/installing/install-from-docker-compose.html#datastore-and-datapusher) section of the [Installing CKAN with Docker Compose](https://docs.ckan.org/en/latest/maintaining/installing/install-from-docker-compose.html) page of CKAN documentation, it is indicated that the following command should be executed:

```bash
docker exec ckan /usr/local/bin/ckan-paster --plugin=ckan datastore set-permissions -c /etc/ckan/production.ini | docker exec -i db psql -U ckan
```
But the first part of this command fails with the following error message:
```
Command 'datastore' not known (you may need to run setup.py egg_info)
Known commands:
  create       Create the file layout for a Python distribution
  exe          Run #! executable files
  help         Display help
  make-config  Install a package and create a fresh config file/directory
  points       Show information about entry points
  post         Run a request for the described application
  request      Run a request for the described application
  serve        Serve the described application
  setup-app    Setup an application, given a config file
```
It seems that the command to be executed is actually the following:

```bash
docker exec ckan /usr/local/bin/ckan -c /etc/ckan/production.ini datastore set-permissions | docker exec -i db psql -U ckan
```

**Comment by ccancellieri** [comment]
probably it's sufficient/better to back-merge the #6131
