### ISSUE TITLE
Better accesibility for text rendered as `title` attributes

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#6150]
Across our templates we use the `title` attribute to provide additional information when hovering with the mouse, eg:

https://github.com/ckan/ckan/blob/0ceebd17bcbd435b156e776df20593ed41af3ffd/ckan/templates/header.html#L10

https://github.com/ckan/ckan/blob/0ceebd17bcbd435b156e776df20593ed41af3ffd/ckan/templates/user/read_base.html#L81

This [is strongly discouraged](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns) as it prevents a whole subset of users to access this information. We should incorporate more accessible ways of conveying this information. That might involve different approaches depending on the template and usage, including adding new markup elements for the extra information, use of `aria` attributes and elements, etc

This article provides a good starting point:

https://inclusive-components.design/tooltips-toggletips/

Any guidance and additional resources on this front would be greatly appreciated

**Comment by sagargg** [comment]
Hi @wardi, I would like to work on this issue.

**Comment by wardi** [comment]
@sagargg go for it!

**Comment by jqnatividad** [comment]
Just wanted to confirm that I will also modify DataTables view to aria-labels as it uses tooltips extensively.
