### ISSUE TITLE
How to find Maximum number of connections required by CKAN and its Extension for accessing PostgreSQL.

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#6153]
**CKAN version**
2.7.2 (Installed via Docker)

**Description** 
In our CKAN environment we have configure CKAN extensions DataStore and DataPusher.
We have created "ckan_default" and "datastore_default" databases in PostgreSQL.
We have configured Apache file with **_WSGIDaemonProcess ckan_default display-name=ckan_default processes=4 threads=15._**

Considering the SQLachemy, Queue size=5 and max overflow=10, we assume the below maximum number of connections required by CKAN and its extensions (DataStore and DataPusher) for accessing PostgreSQL:
![image](https://user-images.githubusercontent.com/66116382/121887421-5308a100-cd34-11eb-886f-455741f644cd.png)

Is the above information in the table is correct?  Is "datastore" is a process or a background job in CKAN?

How we can find Maximum number of connections required by CKAN and its Extension (DataStore and DataPusher) for accessing PostgreSQL?

**Comment by Gauravp-NEC** [comment]
@amercader , Is the above table is correct?

**Comment by amercader** [comment]
The Datastore does not run on a separate process, it will use the standard CKAN ones.The DataPusher does not interact directly with the Postgres database(s). It uses HTTP requests to call the Datastore API so any requests there will also run on the ckan process.
There is no number of connections required to access Postgres. Depending on your site load you might need to adjust the connections pool. This should get you started:

https://docs.ckan.org/en/2.9/maintaining/configuration.html#sqlalchemy
https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-datastore-sqlalchemy

**Comment by amercader** [comment]
Feel free to opena support discussion if you want to discuss this further:

https://github.com/ckan/ckan/discussions

**Comment by Gauravp-NEC** [comment]
@amercader ,
1)  I have check  the  psql's "pg_stat_activity` table and found the connections with "datastore_default" database and also some processes in postgres container with name "datastore_default" as shown in below image:

![Untitled](https://user-images.githubusercontent.com/66116382/122203824-0ea80d00-cebc-11eb-97d1-9f191b5562b3.jpg)




![image](https://user-images.githubusercontent.com/66116382/122202989-377bd280-cebb-11eb-8178-fd343ea8bfc8.png)



But when I disable the Datastore (by removing the plugin and commenting the datastore configs), these connections in psql's "pg_stat_activity" table and those processes that was appearing in the postgres container was not visible as shown below:

![Untitled](https://user-images.githubusercontent.com/66116382/122204834-33e94b00-cebd-11eb-891a-62f3453d6010.jpg)

 **What is your thought on this behavior? why these connections and processes were not shown after disabling the datastore?**

2) Currently in my psql, "max_connection" is set to default 100. When psql make all connections with CKAN (100 connections gets exhaust), then we are getting error as, "**Fatal error: too many clients**".

To resolving this error we should increase the value of "max_connection" parameter. How we can choose the value of this parameter for our CKAN setup to avoid this 'Fatal error: too many clients'?
