### ISSUE TITLE
Filters on dataset types different from "datasets" are not selective

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6168]
**CKAN version**
2.8.4

**Describe the bug**
Filters/facets available on the left column do not work as expected when a different dataset page is shown.
For example, `http://server/customdatasettype´ has organization facets linking to `http://server/dataset?organization=myorganization` instead of `http://server/dataset?organization=myorganization`

**Steps to reproduce**
Create datasets with a custom datasets type and apply a filter.

**Expected behavior**
Filters should be applied only to the custom datasets.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by frafra** [comment]
https://github.com/ckan/ckan/blob/891e6aa6542edc108bb6ee07a4f023199e9d5b36/ckan/templates/package/search.html#L75-L77

https://github.com/ckan/ckan/blob/891e6aa6542edc108bb6ee07a4f023199e9d5b36/ckan/templates/snippets/facet_list.html#L28-L30

It seems that `alternative_url` is not used by default.

**Comment by frafra** [comment]
Adding `alternative_url=dataset_type` as argument fixes the issue.

**Comment by Gauravp-NEC** [comment]
@smotornyuk @frafra , I am interested to work on this issue. Can you provide more details on how to create datasets with a custom datasets type? Thankyou :)

**Comment by frafra** [comment]
@Gauravp-NEC Hi :) You can define new datasets types using https://github.com/ckan/ckanext-scheming.

**Comment by Gauravp-NEC** [comment]
@frafra , Where I need to set the schemas as mentioned here : https://github.com/ckan/ckanext-scheming#configuration.  Do I need to configure it in CKAN config file? I have found that configurations are configured in "test_subclass.ini" file. Please confirm.

**Comment by frafra** [comment]
@Gauravp-NEC you set `scheming.dataset_schemas` in the CKAN config file to link to your schemas, like `myextension:myschema,json`.

**Comment by Gauravp-NEC** [comment]
@frafra , Can you make  me understand this statement "For example, http://server/customdatasettype´ has organization facets linking to http://server/dataset?organization=myorganization` instead of http://server/dataset?organization=myorganization" ?

**Comment by frafra** [comment]
@Gauravp-NEC sure: if you browse `http://myckanserver/customdatasettype` (where `customdatasettype` is the new dataset type defined by you in ckanext-scheming), you can see a search page, listing only datasets of that custom type. If you look at the left bar, where you can find tags and various filters, you can see that the links starts with `http://myckanserver/dataset` instead of `http://myckanserver/customdatasettype`, so if you click on a tag, you will not see all the datasets of type `customdatasettype` with that tag, but *all* the datasets. The same problem occurs if you filter by an organization, like my previous example stated.

**Comment by Gauravp-NEC** [comment]
@frafra , did this issue can reproduce only in 2.8.4 ? and not in 2.9+?

**Comment by frafra** [comment]
@Gauravp-NEC I didn't have the time to test, but the files linked to the issue, which I patched successfully, didn't change, so I am pretty confident that the problem is still there.

**Comment by Gauravp-NEC** [comment]
@frafra , Do I need to add "ckanext-scheming" in CKAN plugins apart from installing ckanext-scheming and setting the "scheming.dataset_schemas " in the CKAN config file?

**Comment by frafra** [comment]
@Gauravp-NEC I think so, otherwise you cannot add datasets with the new schema.

**Comment by Gauravp-NEC** [comment]
@frafra , Thankyou for giving quick response. How can I define new dataset type in ckanext-scheming?

**Comment by frafra** [comment]
@Gauravp-NEC you could try one of the example schemas actually https://github.com/ckan/ckanext-scheming#example-schemas---datasets
