### ISSUE TITLE
datastore_search full_text and fields parameters not processed properly

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#6172]
**CKAN version**
master

**Describe the bug**
When the new `full_text` parameter is used along with the `fields` parameter, `datastore_search` always returns the entire record, along with the "hidden" rank column (used for relevance in fts search)

**Steps to reproduce**
Use `datastore_search` `full_text` and `fields` in the same call.

**Expected behavior**
`datastore_search` will process `fields` properly when `full_text` is specified, and the hidden rank value should not be returned.

**Comment by robin-NEC** [comment]
Hi @jqnatividad , I would like to work on this issue.

**Comment by robin-NEC** [comment]
Hi @jqnatividad , I'm unable to reproduce the issue.
I also checked the API documentation for  [datastore_search](https://docs.ckan.org/en/2.9/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_search), but there is no reference for `full_text` in it. 
Can you provide any resource that has a reference  to `full_text` parameter.?

**Comment by robin-NEC** [comment]
Hi @jqnatividad , I'm able to reproduce the issue. Are we trying to remove the `rank` column from the records response when we hit the API, i.e. from `'records': [{'_id': 2, 'a': 2, 'b': 'zzz', 'rank': 0.057308756}],` and not from the field response . Please confirm my understanding.
