### ISSUE TITLE
Pre selecting organization field when adding metadata.

### ISSUE THREAD

**Issue by Patrick1Rhode** [ckan/ckan#6173]
CKAN version
**2.8.7**

**Describe the bug**
We wanted to suggest this [feature](https://github.com/ckan/ckan/discussions/6167) be added to CKAN, but after a close look at the [code](https://github.com/ckan/ckan/blob/0ab924d5ea331625bd61a805f23c68a17f028193/ckan/templates/package/snippets/package_basic_fields.html) we discovered the feature is already in place, but it does not work the way it is intended.

This [line](https://github.com/ckan/ckan/blob/756776201f36653440bf4f13db2df335300d3d86/ckan/templates/package/snippets/package_basic_fields.html#L74) throws an exception when a dot notation is used on the object, but if you change from the dot notation to square brackets, the code runs fine.

From the requirements file we can see that [Jinja 2.8](http://jinja.octoprint.org/) is the version used for CKAN 2.8.7.

To reproduce the issue follow these steps outlined [here](https://github.com/ckan/ckan/discussions/6167)

We expect jinja 2.8 to support the dot annotation on a python dictionary object but that's not the case. Is the issue coming from the CKAN core or it's from the template engine(Jinja) ?

I have attached my git diff file that has changes we made and **note** we manually added an item to the dictionary as highlighted in the file [ckan_change.txt](https://github.com/ckan/ckan/files/6673187/ckan_change.txt).

Thank you.

**Comment by Sunny-NEC** [comment]
I like to work in this issue

**Comment by Patrick1Rhode** [comment]
Hi everyone,

After running CKAN in vanilla mode, we discovered that the error was caused by one of our custom plugins; therefore, the issue can now be closed.
Thank you for all your responses.
