### ISSUE TITLE
Unable to install CKAN 2.8.4 in Ubuntu 16.04

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#6197]
**CKAN version**
2.8.4 

**Describe the bug**
I am trying to install CKAN 2.8.4 in Ubuntu 16.04.
I have refer the document: https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html for installation.

After executing the step no. 2(c) Install the CKAN source code into your virtualenv.
i.e., **pip install -e 'git+https://github.com/ckan/ckan.git@2.8.4#egg=ckan[requirements]'**
I am facing the below error:

error: pathspec '2.8.4' did not match any file(s) know to git.
ERROR: Command errored out with exist status 1: git checkout -q 2.8.4 check the logs for full command output.

![image](https://user-images.githubusercontent.com/66116382/123795995-407c9300-d902-11eb-999c-b6adba511f91.png)

**Expected behavior**
CKAN source code must be installed in Virtualenv after executing the step no. (c) as mentioned in document :https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html

**Additional details**
If I execute pip install -e 'git+https://github.com/ckan/ckan.git@COULD_NOT_DETECT_TAG_VERSION#egg=ckan[requirements]' it gives the same error.

**Comment by amercader** [comment]
Tags in CKAN have the form `ckan-2-8.4`. Also please use the latest patch release (2.8.8) or even better the latest version (2.9.3)

**Comment by Gauravp-NEC** [comment]
@amercader ,Thanks this solves my problem, but still I am unable to install CKAN. I am facing issue in creating a CKAN config file. This command "paster make-config ckan /etc/ckan/default/development.ini" gives the below error :

Must install ckan
Searching for ckan
Reading https://pypi.python.org/simple/ckan
Couldn't find index page for 'ckan' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for ckan error: Could not find suitable distribution for Requirement.parse('ckan')

![image](https://user-images.githubusercontent.com/66116382/123807811-cf42dd00-d90d-11eb-933b-fff9f50e93a6.png)

**Comment by Gauravp-NEC** [comment]
@amercader , Thanks this solves my problem, but still I am unable to install CKAN. I am facing issue in creating a CKAN config file. This command "paster make-config ckan /etc/ckan/default/development.ini" gives the below error :

Must install ckan
Searching for ckan
Reading https://pypi.python.org/simple/ckan
Couldn't find index page for 'ckan' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for ckan error: Could not find suitable distribution for Requirement.parse('ckan')

![image](https://user-images.githubusercontent.com/66116382/123807811-cf42dd00-d90d-11eb-933b-fff9f50e93a6.png)
