### ISSUE TITLE
Javascript is not included over webassets

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [ckan/ckan#6198]
**CKAN version**
2.9.2

**Describe the bug**
Custom Javascript doesn't included over webasset.

**Steps to reproduce**
My folder structure:
ckanext -> extension -> assets 
In this folder is the Javascript and the webasset.yml
My plugin.py -> toolkit.add_resource('assets', 'back_to_top')
In my back_to_top.js I wrote:
`"use strict";

/**
 * Back to top
 */
this.ckan.module('back_top_top', function ($) {
    return {
        initialize: function(jQuery) {
           .........
        }
    };
});
`
In my footer.html I wrote this: `{% asset 'back_to_top/back_to_top.js' %}`

**Expected behavior**
Custom javascript is included in the <head> as script.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by smotornyuk** [comment]
CKAN won't include assets automatically on the page, you have to include the given asset manually on a particular subset of pages.
[Documentation](https://docs.ckan.org/en/2.9/contributing/frontend/assets.html?highlight=webassets.yml)
Example:
```
# page.html
{% block scripts %}
  {{ super() }}
  {% asset "back_to_top/bundle_name" %}
{% endblock scripts %}
```
