### ISSUE TITLE
Use rel=noreferrer in external links

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#6204]
It is considered a [good practice](https://web.dev/external-anchors-use-rel-noopener/) from a security standpoint to include [`rel="noreferrer"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#attr-noreferrer) in external links that open in a new tab with `target="_blank"`

Here's an external links list from the core templates:

ckanext/datastore/templates/ajax_snippets/api_info.html#L84
ckanext/datastore/templates/ajax_snippets/api_info.html#L79
ckanext/datastore/templates/ajax_snippets/api_info.html#L74
ckan/templates/package/snippets/resource_view.html#L39 
ckan/templates/package/snippets/resource_view.html#L6
ckan/templates/package/snippets/resource_item.html#L55
ckan/templates/package/resource_read.html#L60
ckan/templates/package/resource_read.html#L58
ckan/templates/package/resource_read.html#L56
ckan/templates/package/resource_read.html#L54
ckan/templates/dataviewer/snippets/data_preview.html#L16
ckan/templates/admin/index.html#L78
ckan/templates/admin/config.html#L65

**Comment by Gauravp-NEC** [comment]
@amercader , I am interested to work in this issue.

**Comment by Gauravp-NEC** [comment]
@TomeCirun, You should read the above comment. I have already inform that I am interested to work on this issue and amercader have also reacted with thumbs up emoji. Today I was going to raise the PR to fix this issue. But you steal my work.

**Comment by TomeCirun** [comment]
@Gauravp-NEC, sorry that was not my intention, I was looking at the issues I saw #6204 has no Assignees ..so I did it very quickly... i didnt even look at the comment section... I am so sorry .. my bad.

**Comment by amercader** [comment]
@Gauravp-NEC I'm sure it was just an oversight. There's plenty of tasks available for contribution for everybody
