### ISSUE TITLE
CKAN config file not created in CKAN 2.8 source installation.

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#6210]
**CKAN version**
2.8.4

**Describe the bug**
I am trying to install CKAN 2.8.4 in Ubuntu 16.04.
I have refer the document: https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html for installation.

I am facing issue in creating a CKAN config file. This command "paster make-config ckan /etc/ckan/default/development.ini"  at https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html#create-a-ckan-config-file gives the below error :

Must install ckan
Searching for ckan
Reading https://pypi.python.org/simple/ckan
Couldn't find index page for 'ckan' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for ckan error: Could not find suitable distribution for Requirement.parse('ckan')

![image](https://user-images.githubusercontent.com/66116382/123807811-cf42dd00-d90d-11eb-933b-fff9f50e93a6.png)

**Steps to reproduce**
Follow the doc: https://docs.ckan.org/en/2.8/maintaining/installing/ after performing steps 1-3 at step 4 this command "paster make-config ckan /etc/ckan/default/development.ini" gives the error.

**Expected behavior**
CKAN config file must be created after executing the command "paster make-config ckan /etc/ckan/default/development.ini"

**Comment by scottlimmer** [comment]
Just ran into this myself on 2.8.8

You need to run the paster command from the directory `/usr/lib/ckan/default/src/ckan` to ensure it loads the package correctly.

**Comment by kowh-ai** [comment]
This looks like a PATH issue to me...I just tried the same command (on Ubuntu 18.04) and it worked fine. Please note that Ubuntu 16.04 reached EOL April 30th 2021

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have tried to install 2.8.4 in Ubuntu 18.04 but still development.ini file is not created. Please have a look on below images:


![Capture 1](https://user-images.githubusercontent.com/66116382/126137504-d81fd509-fc35-4b8e-a8e6-7c2b265f121a.JPG)

![Capture 2](https://user-images.githubusercontent.com/66116382/126138959-6ded5eae-fe7d-464a-a1c3-0a41da2617a7.JPG)

![Capture 3](https://user-images.githubusercontent.com/66116382/126139018-e5119845-3514-4dff-809a-4f580355fc7d.JPG)

**Comment by kowh-ai** [comment]
Looks like you need to use a newer version of setuptools - check the file: `requirement-setuptools.txt`
