### ISSUE TITLE
Ckan DataStore testing is not working properly

### ISSUE THREAD

**Issue by Lochanie** [ckan/ckan#6257]
I have installed ckan using package installation in ubuntu 20.4 LTS. I have followed the steps in https://docs.ckan.org/en/2.9/maintaining/datastore.html to install datastore. Once I typed curl -X GET "http://127.0.0.1:5000/api/3/action/datastore_search?resource_id=_table_metadata" command. It gives me the results. 

![image](https://user-images.githubusercontent.com/70228255/125739228-340aba7a-679c-476b-bd1a-eae6df761d81.png)
![results](https://user-images.githubusercontent.com/70228255/125739360-f856a2e1-2871-42e1-9e39-16eb8369a0b5.JPG)

How can I resolve this issue?? Please help me to resolve this

**Comment by smotornyuk** [comment]
It looks like your terminal emulator has some problems with newline characters - can you try removing it in the end of ApiToken (before `" -d ...`). Because payload itself cannot produce the given error

**Comment by Lochanie** [comment]
Hi , Thank you so much for your response. when I remove it, I am getting authorization error.  I put this commas" I am getting type not found error.
![image](https://user-images.githubusercontent.com/70228255/126308962-77b9d110-cf81-4ac9-abc0-12d27b127658.png)

**Comment by smotornyuk** [comment]
* AccessDenied : you are using invalid ApiToken
* NotFound: you are using invalid PackageID
