### ISSUE TITLE
Create "welcome username" after login on UI 

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#6328]
**CKAN version**
Master

**Steps to reproduce**
Login to CKAN and see the top right side as highlighted in below image:

![p1](https://user-images.githubusercontent.com/66116382/129704668-2cb18683-d8c9-4cd2-b4d9-750c13bb9aba.JPG)

**Expected behavior**
As highlighted in below image:

![Capture](https://user-images.githubusercontent.com/66116382/129705134-3eaf1a10-5828-4964-80fa-e94caa8d6a69.JPG)

**Comment by Gauravp-NEC** [comment]
If Dev-team agree to have PR on this issue. Please assign this issue to me. I will submit the PR. Thanks :)

**Comment by Gauravp-NEC** [comment]
@amercader , Please assign this issue to me.

**Comment by amercader** [comment]
Thanks @Gauravp-NEC . We don't believe this is a valuable feature for CKAN core, as it can be easily implemented in an extension if needed.
