### ISSUE TITLE
The tracking_summary table is no longer updated

### ISSUE THREAD

**Issue by hongjie123** [ckan/ckan#6334]
The tracking_summary table is no longer updated when a resource is downloaded.   However, if PostgreSQL data can be obtained normally, how do I solve the problem that the tracking_summary table is not updated? 
![image](https://user-images.githubusercontent.com/54384385/129992087-fdac35e0-8ec4-4c86-8068-59457da553b2.png)

**Comment by hongjie123** [comment]
Manual data insertion succeeded, eliminating the database problem.  How is the resource record written to the database?  
![image](https://user-images.githubusercontent.com/54384385/130002330-233a0bb7-2b47-4a5f-8eaa-32014ac4706e.png)

**Comment by amercader** [comment]
Page view tracking needs a command to be run regularly with a cron job to populate this table as described in the [docs](https://docs.ckan.org/en/2.9/maintaining/tracking.html#enabling-page-view-tracking). Are you doing this?

**Comment by hongjie123** [comment]
I have enabled page view tracking.
![image](https://user-images.githubusercontent.com/54384385/130161958-690b6567-4fe9-4313-a576-4535dd7e6ff8.png)

**Comment by jqnatividad** [comment]
@hongjie123 , apart from setting `ckan.tracking_enabled = true`, you also need to setup the cron job as @amercader mentioned. 

It's step 2 of [Enabling Page View Tracking](https://docs.ckan.org/en/2.9/maintaining/tracking.html#enabling-page-view-tracking).

**Comment by amercader** [comment]
@hongjie123 please start a Discussion if you need more support with this

**Comment by Gauravp-NEC** [comment]
@hongjie123 , I have followed the doc: https://docs.ckan.org/en/2.7/maintaining/tracking.html#enabling-page-view-tracking and enabled page view tracking in CKAN v2.7.12. I am trying to get the tracking summary of dataset using package_show() API i.e., curl http://localhost:5000/api/3/action/package_show?id=[ ]&include_tracking=true , but tracking_summary is not included in the API response. How can I get the tracking_summary?
