### ISSUE TITLE
% characters in config variables results in error.

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#6341]
**CKAN version**
2.9, master

**Describe the bug**
While upgrading from 2.8.8 to 2.9.3 and python3, CKAN refused to start and produced following error:
```
File "/usr/lib/python3.6/configparser.py", line 444, in _interpolate_some
        "found: %r" % (rest,))
    configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: somesecretvariablewith%characterinit
```

**Steps to reproduce**
Add % character to some config variable.

**Expected behavior**
CKAN should start as it did with 2.8.8

**Comment by amercader** [comment]
Add a note on the next patch release changelog about the escaping needed (`%%`)

**Comment by Sunny-NEC** [comment]
@amercader @Zharktas  I am interested to work on this issue.

**Comment by Sunny-NEC** [comment]
@Zharktas if we use %% sign with config variables instead of single % it will work fine. but if we have to use % then we can disable configparser.
