### ISSUE TITLE
Unexpected permissions issues when restarting `supervisor`

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckan#6347]
**CKAN version**
2.9.3

**Describe the bug**
Unexpected permissions issues when restarting `supervisor` by a different user to the one who installed CKAN 

**Steps to reproduce**

 - Follow CKAN installation instructions, including symlinking into the home directory of `user1`
 - a 2nd user on the same machine runs `sudo service supervisor restart`, but CKAN doesn't restart and returns a 502 error. The logs complain about (e.g.) `PermissionError: [Errno 13] Permission denied: '/home/user1/ckan/lib/default/src/ckan/ckan/public/base/i18n/cs_CZ.js'`

I've only noticed it after a patch upgrade, but don't know if it's a wider issue

**Expected behavior**
This may not be _unexpected_, but it took me a while to get round the issue. If it is a known limitation, then perhaps it could be briefly noted in the docs

**Additional details**

I've fixed it for now by making the `i18n` directory world-writeable, although this doesn't seem like a great solution!

I totally get that there will be some limitations with installing into a home directory - it's fairly obvious that user2 trying to install extensions, etc, is likely to cause issues, but this seems like a different problem, given it's python trying to write a file

The full section from uwsgi.ERR is

```
  Traceback (most recent call last):
  File "/etc/ckan/default/wsgi.py", line 12, in <module>
    application = make_app(config)
  File "/home/user1/ckan/lib/default/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/home/user1/ckan/lib/default/src/ckan/ckan/config/environment.py", line 138, in load_environment
    build_js_translations()
  File "/home/user1/ckan/lib/default/src/ckan/ckan/lib/i18n.py", line 412, in build_js_translations
    _build_js_translation(lang, po_files, js_entries, dest_file)
  File "/home/user1/ckan/lib/default/src/ckan/ckan/lib/i18n.py", line 354, in _build_js_translation
    with open(dest_filename, u'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/user1/ckan/lib/default/src/ckan/ckan/public/base/i18n/cs_CZ.js'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
```

(the most obvious longer term solution is to remove all the symlinks, move the directories back to where they _should_ be, and `chgroup` to a suitable group that contains users who need to write to it)

**Comment by amercader** [comment]
The underlying issue here is https://github.com/ckan/ckan/issues/6278. Until that is fixed perhaps the documentation changes you suggest make sense.
