### ISSUE TITLE
`ckan.lib.helpers.format_resource_items` discards `False` boolean values

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#6350]
**CKAN version**
2.9

**Describe the bug**
I have boolean resource metadata keys defined via schemas in my DCOR instance. These are not written to the resources HTML page, because [format_resource_items](https://github.com/ckan/ckan/blob/c5c529d10ebe63d8573515483fdd46e0839477f0/ckan/lib/helpers.py#L2294) discards `False` boolean values.

**Steps to reproduce**
Set a value of a resource key to `False`.

**Expected behavior**
Value should be displayed on HTML resource page.

**Additional details**
This can be fixed by changing the line linked above

```python
if not value or key in blacklist: 
    continue
```

 to

```python
if not isinstance(value, bool) and (not value or key in blacklist): 
    continue
```

**I can write a PR including a test for `format_resource_items` if you give me green light.**

**Comment by Zharktas** [comment]
I think the helper expects strings, even though there are some handling for special cases like dates and numbers. But the actual type given to the function is still a string.

**Comment by paulmueller** [comment]
I thought `items` (what `format_resource_items` accepts)  would be something like `dict.items()`, i.e. a list of `(key, value)` pairs.

And no, (while the keys are strings) the values are definitely not always strings. They can be floats, integers, and boolean. Otherwise it would not make sense to handle those cases in that function.

**Comment by amercader** [comment]
@paulmueller it makes sense to handle boolean as special case as well. A PR would be great!
