### ISSUE TITLE
Create the CKAN config file:Errors

### ISSUE THREAD

**Issue by hongjie123** [ckan/ckan#6358]
The use of "ckan generate config/etc/ckan/default/ckan ini" errors "ImportError: cannot import name 'token_urlsafe'".
![image](https://user-images.githubusercontent.com/54384385/131817696-93b19004-bb0c-497e-bb22-8acd9ffce2ee.png)

**Comment by hongjie123** [comment]
Version information of "secrets"
![image](https://user-images.githubusercontent.com/54384385/131818052-e11f89b8-0f6b-4b69-9139-c67600525da3.png)

**Comment by smotornyuk** [comment]
You are using python 3.5, while CKAN supports 3.6 and newer. Starting with v3.6, `secrets` was included in python's standard library. So you just need to update your python (CKAN v2.9 supports v3.6, v3.7, and v3.8)
