### ISSUE TITLE
ckan_default process is using more than allowed connections

### ISSUE THREAD

**Issue by ArqamFarooqui110719** [ckan/ckan#6362]
CKAN v2.7.2(Docker)

**Describe the bug**
In the CKAN I have configured, 
```
Sqlalchemy's queuepool
	pool_size = 5,  max_overflow = 10

PostgreSQL's
	max_connections = 180
	databases = ckandb(ckan_Default) database, ckan_datastore db(write) and ckan_datastore db(read)
	
ckan_default processes = 4
```	

As per the above configuration, maximum possible connections with 1 database(ckandb) should be 60, As: 
> 	  5 pool_size + 10 max_overflow == 15 * 4 ckan_default processes == 60 * 1 database = 60 connections.
	  
But when I look into pg_stat_activity table, it is showing, currently there are 75 connections with the `ckandb` (that is more than 60), out of which 64 connections are in `active` state and 2 connection are in `idle in transaction` and 9 connections are in `idle` state:

```
postgres=# select count(*) from pg_stat_activity where datname = 'ckandb';
 count
-------
    75
(1 row)

postgres=# select count(*) from pg_stat_activity where datname = 'ckan_datastore';
 count
-------
    22
(1 row)

```

As suggested by @smotornyuk on gitter query, to know the source of the connection I have killed ckan_default processes one by one and confirmed that all the connections made by only 4 ckan_default processes, and 5 connections (4 with ckandb + 1 with ckan_datastore db) are made by CKAN's parent process i.e. given below:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ckan-ap+     1  0.0  0.0  55472  12448 ?       Ss   01:35   0:02 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisor-ckan.conf
ckan-ap+   140  9.8  6.2 2746700 1019360 ?     Sl   01:35  22:02 ckan_default      -DFOREGROUND
ckan-ap+   141  7.1  5.7 2339084 939048 ?      Sl   01:35  15:58 ckan_default      -DFOREGROUND
ckan-ap+   142  9.4  5.6 2302216 912076 ?      Sl   01:35  21:06 ckan_default      -DFOREGROUND
ckan-ap+   143  9.7  5.3 2178556 866608 ?      Sl   01:35  21:51 ckan_default      -DFOREGROUND
```
When I killed 1st ckan_default process:
> ckan-ap+   140  9.8  6.2 2746700 1019360 ?     Sl   01:35  22:02 ckan_default      -DFOREGROUND 

**It releases 13 connections (7 ckandb connections + 6 ckan_datastore connections)**

When I killed 2nd ckan_default process:
> ckan-ap+   141  7.1  5.7 2339084 939048 ?      Sl   01:35  15:58 ckan_default      -DFOREGROUND

**It releases 11 connections (6 ckandb connections + 5 ckan_datastore connections)**

When I killed 3rd ckan_default process:
> ckan-ap+   142  9.4  5.6 2302216 912076 ?      Sl   01:35  21:06 ckan_default      -DFOREGROUND

**It releases 11 connections (6 ckandb connections + 5 ckan_datastore connections)**

When I killed 4th ckan_default process:
> ckan-ap+   143  9.7  5.3 2178556 866608 ?      Sl   01:35  21:51 ckan_default      -DFOREGROUND

**It releases 57 connections (52 ckandb connections + 5 ckan_datastore connections)**

I have confirmed it twice that 1 out of 4 ckan_default process contains more than 50 connections (in which ~50 connections are with ckandb database). How 1 ckan_default process can contain more than 50 connections? @amercader sir, @wardi sir, @smotornyuk sir, can you please look into it what is happening wrong?

**Steps to reproduce**
We are performing operations on CKAN by running multiple scripts of `resource_create` APIs, `resource_update` APIs, `datastore_search` APIs and `resource_show` APIs etc.

**Expected behavior**
ckandb database should have only `60 connections of ckan_default processes + 4 parent process connections == 64 connections` and 1 ckan_default process should create maximum `15 connections with ckandb + 30 connections with ckan_datastore(read and write) = 45 connections` as per sqlalchemy's queuepool configuration (5 pool_size + 10 max_overflow).

**Comment by smotornyuk** [comment]
Can you give more details as to your configuration and where you've found an example:

```Describe the bug
In the CKAN I have configured,

Sqlalchemy's queuepool
	pool_size = 5,  max_overflow = 10

PostgreSQL's
	max_connections = 180
	databases = ckandb(ckan_Default) database, ckan_datastore db(write) and ckan_datastore db(read)
	
ckan_default processes = 4
```

**Comment by ArqamFarooqui110719** [comment]
Yes sure...
first let me confirm your query, do you wanted to know source of the mentioned details for ex. where I have configure ckan_default processes == 4 or where I have found queuepool configuration)?

**Comment by smotornyuk** [comment]
The more details we have, the better - it allows us to reproduce your environment locally.
But the most important for now - how you've configured sqlalchemy pool and what part of CKAN documentation you've used for it?

**Comment by ArqamFarooqui110719** [comment]
Hi @smotornyuk sir, we are using CKAN v2.7.2(docker) and SQLAlchemy==0.9.6. 
and we have not modified sqlalchemy's queuepool configuration, it has default size as `pool_size = 5,  max_overflow = 10`. We have checked this in file `/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/pool.py`:

![sqlalchemy](https://user-images.githubusercontent.com/55977298/132189439-eee3c806-4c6a-475b-974e-6ea27bab627b.png)


However we have set ckan_default processe == 4 in `ckan/apache2/site-enabled/ckan_default.conf` file, as below:

![ckan_default](https://user-images.githubusercontent.com/55977298/132189655-d009f74a-a1fa-45ee-b839-f7d6b089c1fa.png)


And we have also modified postgresql's `max_connections == 180` in `var/lib/postgresql/data/postgresql.conf` file, as below:

![psql_conf](https://user-images.githubusercontent.com/55977298/132190078-54ad5340-a4e3-44da-b9a4-58618d322fa8.png)

Kindly let me know in case of other queries.

**Comment by smotornyuk** [comment]
Oh, I see. In that case, this has nothing to do with CKAN, report this issue to SQLAlchemy repo.

Little insight:
CKAN does not change any options of SQLAlchemy by default. It just uses an engine [created over your config file](https://github.com/ckan/ckan/blob/ckan-2.7.2/ckan/config/environment.py#L265). As mentioned in docs, [you can configure sqlalchemy's engine](https://docs.ckan.org/en/2.9/maintaining/configuration.html#sqlalchemy), but CKAN does not interfere into this process, so any unexpected behavior of engine/session has no relation to CKAN itself.
