### ISSUE TITLE
Missing resource_embedded_dataviewer.html or misnamed template file

### ISSUE THREAD

**Issue by kentsanggds** [ckan/ckan#6383]
**CKAN version**
2.9.3

**Describe the bug**
Missing or incorrectly named template file

**Steps to reproduce**

Create a dataset with a resource and then go to the resource url and append `/embed` at the end, it causes an internal server error - `TemplateNotFound: package/resource_embedded_dataviewer.html`

**Expected behavior**
The resource to be correctly returned from the request.

**Additional details**
This is the line with the template filename - 

https://github.com/ckan/ckan/blob/master/ckan/views/resource.py#L875

**Comment by amercader** [comment]
The `/embed` endpoint is a remnant of the old preview system. The route, blueprint endpoint and template should be removed cc @TomeCirun

**Comment by TomeCirun** [comment]
@amercader I am sorry... now i see that we have /viewer for this .. and additionally `fullscreen` is doing the same job.. please advise what else can i do  except removing the route,bluprint endpoint and template for /embed (i m not sure about the template as i can see   [view](https://github.com/ckan/ckan/blob/ad405b580332e5f73e933da8db6ed36a90adfcdf/ckan/views/resource.py#L611)  still using `"package/snippets/resource_view_embed.html"` as it calls [h.rendered_resource_view](https://github.com/ckan/ckan/blob/ad405b580332e5f73e933da8db6ed36a90adfcdf/ckan/lib/helpers.py#L2397)) if you have any suggestion i am glad to make it happen..

In addition please let me know what to do with this func: `def embedded_dataviewer`

Thanks
