### ISSUE TITLE
Patch releases September 2021

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#6386]
This is an issue to track progress on the patch releases scheduled for September 2021 (2.7.12, 2.8.9 and 2.9.4)

[Full docs](http://docs.ckan.org/en/latest/contributing/release-process.html)

* [x] Backports
* [x] Translations
* [x] Rebuild Frontend
* [x] Changelog
* [x] Change version and tag 
* [x] Build packages
* [x] Update docs (RTD)
* [x] PyPI
* [x] Announce

**Comment by amercader** [comment]
@smotornyuk This commit https://github.com/ckan/ckan/commit/b9e49519f79a50510644a4b30d21beefac86bddd#
removed and updated a bunch of entries from `requirements.txt`. I think you might have targeted the wrong `requirements.in` when running `pip-compile`. This was causing failures like [this one](https://app.circleci.com/pipelines/github/ckan/ckan/2324/workflows/e28086ac-8caf-46f1-b970-546aa7a30167/jobs/10072). I've rebuilt in d05f93686

**Comment by Gauravp-NEC** [comment]
@amercader , What is left in patch releases scheduled for September 2021? I think track progress should be closed now.

**Comment by Gauravp-NEC** [comment]
amercader , What is left in patch releases scheduled for September 2021? I think track progress should be closed now.
