### ISSUE TITLE
Remove tag template

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#6407]
**CKAN version**
Master

**Describe the bug**
Tag template is no longer used in CKAN.

**Expected behavior**
Tag template must be removed from CKAN code.

**Comment by Gauravp-NEC** [comment]
If Dev-team agree to have work on this issue. Please assign this issue to me. I will submit the PR. Thanks :)

**Comment by amercader** [comment]
Please go ahead @Gauravp-NEC

**Comment by Gauravp-NEC** [comment]
@amercader, Thanks. I will submit the PR.

**Comment by Gauravp-NEC** [comment]
@amercader  I have raised the PR https://github.com/ckan/ckan/pull/6416 to fix this issue.
