### ISSUE TITLE
Upgrade Jinja2 to v3.0.2 when it's released

### ISSUE THREAD

**Issue by smotornyuk** [ckan/ckan#6415]
In master, Jinja2 should be updated to v3.0.2 when it is released(currently uses v3.0.1).

I've just noticed a bug(which will be fixed in v3.0.2) that breaks ckanext-scheming on CKAN's master:)

It mentioned in Jinja's changelog:

> [Revert an unintended change that caused Undefined to act like StrictUndefined for the in operator.](https://jinja.palletsprojects.com/en/3.0.x/changes/#version-3-0-2)

**Comment by Gauravp-NEC** [comment]
@smotornyuk, v3.0.2 is released https://jinja.palletsprojects.com/en/3.0.x/changes/#version-3-0-2.

**Comment by smotornyuk** [comment]
Fixed by #6474
