### ISSUE TITLE
Pin redis to a specific version

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6418]
It would be safer to pin redis to the latest known compatible version.

https://github.com/ckan/ckan/blob/d20703f261c2f42fe034bbac7370943784b74e07/contrib/docker/docker-compose.yml#L79

**Comment by EricSoroos** [comment]
Propose pinning to either redis:6 or redis:6.2

**Comment by wardi** [comment]
I feel like Debian will be the better-tested environment, other than a slightly smaller image is there a reason to use Alpine?

**Comment by EricSoroos** [comment]
I don't really care that much for self contained services -- most of the big ones are reasonably stable with MUSL or they're not packaged that way. 

For python, I much prefer the debian based ones, as they're compatible with binary wheels.

**Comment by Gauravp-NEC** [comment]
I think it is better to keep the redis at latest version. If we change the redis to a specific version then in future we have change the version time to time.

**Comment by kowh-ai** [comment]
@Gauravp-NEC - The problem with that is there's a high chance a major version change will severely break things - We never really know when `:latest`  versions will change.
