### ISSUE TITLE
docker-compose.yml contains unneeded build args

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6419]
These arguments can be removed safely:
https://github.com/ckan/ckan/blob/d20703f261c2f42fe034bbac7370943784b74e07/contrib/docker/docker-compose.yml#L56-L58

These as well:
https://github.com/ckan/ckan/blob/d20703f261c2f42fe034bbac7370943784b74e07/contrib/docker/docker-compose.yml#L17-L18

It would be better to make images that are not deployment specific and just rely on environmental variables. This argument seems not very useful, as it is overwritten at run time:
https://github.com/ckan/ckan/blob/master/Dockerfile#L47-L48

https://github.com/ckan/ckan/blob/d20703f261c2f42fe034bbac7370943784b74e07/contrib/docker/ckan-entrypoint.sh#L23

**Comment by kowh-ai** [comment]
Yes agreed - always found Docker ARG and ENV a bit confusing especially when using Docker Compose
