### ISSUE TITLE
Custom fields , basic package fields keyError when using "Removed"

### ISSUE THREAD

**Issue by sim-pml** [ckan/ckan#6422]
**CKAN version**
2.8

**Describe the bug**
During the process of adding custom fields via https://docs.ckan.org/en/2.8/extensions/adding-custom-fields.html . 

Adding a` form.select` macro element into `package_basic_fields.html` causes a `keyError` in the logs (e.g. `error_log`)  if the id of the form.select element is called `Removed`. 

**Steps to reproduce**
Using the below line in `package_basic_fields.htm`  causes the error 

{{ form.select('Removed',  label=_('Has dataset been removed ?'), options=[{'name':yes, 'value': 'Yes'},{'name': No, 'value': 'No'}], ) }}

but we we change `Removed` to anything else then the code works as expected. Is "Removed" a keyword in jinja2 / python that might cause this ?

**Expected behavior**
The page should load without any errors

**Additional details**
```
[Wed Sep 22 11:14:20.609039 2021] [:error] [pid 24343] 2021-09-22 11:14:20,608 WARNI [ckan.lib.helpers] <type 'exceptions.KeyError'>
[Wed Sep 22 11:14:20.609103 2021] [:error] [pid 24343] 2021-09-22 11:14:20,609 WARNI [ckan.lib.helpers] 'key'
[Wed Sep 22 11:14:20.609167 2021] [:error] [pid 24343] 2021-09-22 11:14:20,609 WARNI [ckan.lib.helpers] <traceback object at 0x7f0ead658560>
[Wed Sep 22 11:14:20.609684 2021] [:error] [pid 24343] 2021-09-22 11:14:20,609 WARNI [ckan.lib.helpers] Traceback (most recent call last):
[Wed Sep 22 11:14:20.609694 2021] [:error] [pid 24343]   File "/opt/ckan/default/src/ckan/ckan/lib/helpers.py", line 1139, in sorted_extras
[Wed Sep 22 11:14:20.609698 2021] [:error] [pid 24343]     for extra in sorted(package_extras, key=lambda x: x['key']):
[Wed Sep 22 11:14:20.609701 2021] [:error] [pid 24343]   File "/opt/ckan/default/src/ckan/ckan/lib/helpers.py", line 1139, in <lambda>
[Wed Sep 22 11:14:20.609704 2021] [:error] [pid 24343]     for extra in sorted(package_extras, key=lambda x: x['key']):
[Wed Sep 22 11:14:20.609707 2021] [:error] [pid 24343] KeyError: 'key'
```

**Comment by sim-pml** [comment]
If this helps assist in the issue, I added a little extra logging to the helpers lib : 

```
[ckan.lib.helpers] listing extra [{u'key': u'Archive', u'value': u'Yes'}, {u'key': u'ArchiveDate', u'value': u'2021-09-02'}, {u'key': u'Removed'}, {u'value': u'Yes'}])
```
Not that the key and value for `Removed` are seperate elements in the list , whereas other extra fields I have added are one element . `Archive` is a good example as this is also using a dropdown list tp select values, but does not have this problem.

**Comment by smotornyuk** [comment]
Can you confirm that you are using one of the latest v2.8 tags( v2.8.8 or v2.8.9). There was a similar issue before, but I think it was fixed a few months ago (and, just in case, rebuild search index via CLI: `ckan -c <ckan-config.ini> search-index rebuild`)

**Comment by sim-pml** [comment]
I have managed to resolve  this issue now .  The `Removed` word was actually irrelevant . This was resolved by updating `plugin.py` for the extension . 

I noticed that `convert_from_extras` , `ignore_missing` were the wrong way around in the `show_package_schema` function, once switched around this resolved the issue.
