### ISSUE TITLE
resource_create API returns 500

### ISSUE THREAD

**Issue by jbrown-xentity** [ckan/ckan#6447]
**CKAN version: 2.9.4 (latest release)**

**Describe the bug**
When a resource is loaded via the API, a 500 error is given

**Steps to reproduce**
We use Cypress tests to validate key use cases for our users. See [GSA/data.gov PR](https://github.com/GSA/inventory-app/pull/373) showing this test case (tests pass on 2.8). See specific test case [here](https://github.com/GSA/inventory-app/blob/main/e2e/cypress/integration/dataset.spec.js#L33-L46).

**Expected behavior**
A successful 200 response when using `resource_create` route with valid access and file.

**Additional details**
Stack Trace:
```
ckan_1                  | 2021-09-30 14:32:14,286 ERROR [ckan.views.api] 'NoneType' object has no attribute 'transaction'
ckan_1                  | Traceback (most recent call last):
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/config/middleware/../../views/api.py", line 291, in action
ckan_1                  |     result = function(context, request_data)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/logic/__init__.py", line 504, in wrapped
ckan_1                  |     result = _action(context, data_dict, **kw)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/logic/action/create.py", line 332, in resource_create
ckan_1                  |     model.repo.commit()
ckan_1                  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
ckan_1                  |     return getattr(self.registry(), name)(*args, **kwargs)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
ckan_1                  |     self.transaction.commit()
ckan_1                  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 494, in commit
ckan_1                  |     self._prepare_impl()
ckan_1                  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 464, in _prepare_impl
ckan_1                  |     stx = self.session.transaction
ckan_1                  | AttributeError: 'NoneType' object has no attribute 'transaction'
ckan_1                  | 2021-09-30 14:32:14,325 INFO  [ckan.config.middleware.flask_app]  500 /api/action/resource_create render time 1.172 seconds
```

**Comment by jbrown-xentity** [comment]
@amercader, this is the bug I mentioned this morning on dev call.

**Comment by amercader** [comment]
@jbrown-xentity I could not verify this from your test setup but are you using the `xloader` plugin in the tests by any chance?

This issue was addressed in https://github.com/ckan/ckanext-xloader/pull/140, which was merged and included in the ckanext-xloader 0.9.0 release.

If this doesn't help can you share the list of plugins that are used in these tests? (I could not reproduce it in a vanilla CKAN instance)

**Comment by jbrown-xentity** [comment]
For future, we validate all our extensions are installed: https://github.com/GSA/inventory-app/blob/main/e2e/cypress/integration/ckan_extensions.spec.js#L14-L25

I bumped xloader which we are using, hopefully this solves the issue! https://github.com/GSA/inventory-app/pull/373#event-5394817572

**Comment by jbrown-xentity** [comment]
That did it, I'm closing this issue. Thanks for the quick response @amercader!
