### ISSUE TITLE
Upload.__init__ relies too much on makedirs

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#6521]
**CKAN version**

2.8, 2.9

**Describe the bug**

ckan.lib.uploader:Upload.__init__ relies on `os.makedirs` to create the storage directory. However, this is inadequate if, for example, the storage directory has been created by another process, with sufficient permissions for CKAN to use it, yet with insufficient permissions in the parent directory for CKAN to have created it.

It also adds extra OS calls on every creation of an Upload object.

**Comment by amercader** [comment]
This code is used to create subdirectories for each uploader type, eg `groups` for group and org images, `admin` for the 
admin UI logos, and others that extensions might want to create, which is really useful.

https://github.com/ckan/ckan/blob/master/ckan/lib/uploader.py#L123-L130

Perhaps it's not the most elegant one, what do you propose to improve it? Maybe checking if the directories exist before attempting `os.makedirs`?

**Comment by ThrawnCA** [comment]
> Maybe checking if the directories exist before attempting os.makedirs?

It would be a good check to add, yes.

Consider a CKAN system created by a configuration management tool like Chef. It might well have the storage directory created, with appropriate permissions for CKAN to use it, but without write access to the parent directory.
