### ISSUE TITLE
Syntax error on python 3.6 and on 3.8

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#6549]
**CKAN version**
master

**Describe the bug**
Running cli commands results in syntax error with python 3.6
```
SyntaxError: future feature annotations is not defined
```

We could either fix the error or bump our minimum python version to 3.7 as 3.6 end of life date is in a month anyway. 

On python 3.8, master produces different error:

```
from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by amercader** [comment]
We need to update the docs to reflect that master requires Python 3.7

**Comment by Sunny-NEC** [comment]
@Zharktas I am interested to work on this issue.

**Comment by frafra** [comment]
In addition to updating the documentation, a fix could be used for newer versions of Python, such as:

```
try:
    # Python 3.5+
    from typing import Literal
except ModuleNotFoundError:
    # Python <3.5
    from typing_extensions import Literal
```

If we are targeting Python 3.6 and if we exclude Python 2, then `from typing import Literal` can be used.

**Comment by frafra** [comment]
@Zharktas It looks like `typing_extensions` is available for Python 3.8+, so I guess there is something else going on with your CKAN setup. Did pip failed to install something?

**Comment by frafra** [comment]
@Zharktas then this issue can be closed, I guess :)
I am running ~CKAN 2.9.5 on Python 3.8, and it is working fine.

**Comment by Zharktas** [comment]
The docs aren't updated yet, i'm not closing an issue that still exists.

**Comment by frafra** [comment]
You are right. I was misled by the fact that more than one issue is mentioned in the first post, which seemed a code error more than a documentation issue.

**Comment by Gauravp-NEC** [comment]
> The docs aren't updated yet, i'm not closing an issue that still exists.

@Zharktas , I have raise the PR: https://github.com/ckan/ckan/pull/6740 for docs update.
