### ISSUE TITLE
Registering users don't get the confirmation email

### ISSUE THREAD

**Issue by maxclac** [ckan/ckan#6566]
**CKAN version**
2.9.4

**Describe the bug**

Hi!

I am using CKAN 2.9.4. I noticed that, when a user registers, everything is going fine except that no confirmation email is sent (not even in the spam folder). I don't think it is a postfix problem because commands like `echo "This is the body of the email" | mail -s "This is the subject line" user@example.com` work fine. 

**Steps to reproduce**
Register as a new user

**Expected behavior**
Confirmation email received

**Comment by Sunny-NEC** [comment]
@maxclac i am intrested in this issue.

**Comment by maxclac** [comment]
Thank you @smotornyuk for the information. Just a last question: is it the same for invitation emails (i.e. when I want to invite someone to a group who does not have an account)? Do I need to inform this person myself?

**Comment by Zharktas** [comment]
If you invite someone without an account to a group or organization, they will get an email about the invitation and resetting password. Template for that is here https://github.com/ckan/ckan/blob/master/ckan/templates/emails/invite_user.txt

**Comment by maxclac** [comment]
I see. So there is no confirmation email for users registering themselves, but there is an invitation email when someone wants to invite someone else to a group. Thank you for the clarification!
