### ISSUE TITLE
Let Docker services restart "always" to survive system reboot

### ISSUE THREAD

**Issue by florianm** [ckan/ckan#6568]
**CKAN version**
Current master [ace6850dd](https://github.com/ckan/ckan/commit/ace6850ddabb1bc533c6942cc434e806c62236e5)

**Describe the bug**
When installed via docker-compose, the services do not restart after a system reboot.

**Steps to reproduce**
Install CKAN following the [CKAN docker-compose docs](http://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html), run via `docker-compose up -d`, reboot system.

**Expected behavior**

CKAN services should reboot after a system reboot.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

A solution that works on my end:

* Noop: Configure Docker to restart on system boot, ref. [Docker docs on restart](https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot) - note: on Ubuntu this is already the default. I have tested this only on a Ubuntu 20.04 VM.
* New: Add `restart: always` policies to each service in docker-compose, ref. [docker-compose docs on restart policy](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart)
* Noop: Run CKAN as per docs as a daemonized process with `docker-compose up -d`.
* CKAN now reboots after the system reboots.

**Comment by kowh-ai** [comment]
PR tested - works great
