### ISSUE TITLE
Searching organization with trailing space failed

### ISSUE THREAD

**Issue by FuhuXia** [ckan/ckan#6579]
**CKAN version**
2.9

**Describe the bug**
When doing an organization search, the search terms are not trimmed. Searching with `GSA ` will not find organization **GSA**.

**Steps to reproduce**
https://demo.ckan.org/organization/?q=organization+
It gives no results.

**Expected behavior**
Show results including **Sample Organization**.

**Additional details**
Search terms need to be trimmed.

**Comment by Sunny-NEC** [comment]
@FuhuXia I am interested to work in this issue.
