### ISSUE TITLE
Cannot run reindex

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6599]
**CKAN version**
2.9-dev

**Describe the bug**
Cannot reindex the database.

**Steps to reproduce**
This happens on some of my setups, but not on all of them, so it can be hard to replicate. I just imported some dataset and run reindex.

**Expected behavior**
Reindex should work or give better errors.

**Additional details**
```
2021-12-15 10:55:24,640 ERROR [ckan.lib.search] Error while indexing dataset 7d31e7b0-506e-4fa0-94ec-9d73354805dc: TypeError('No object (name: tmpl_context or C) has been registered for this thread',)
No object (name: tmpl_context or C) has been registered for this thread
2021-12-15 10:55:24,658 INFO  [ckan.lib.search] Commited pending changes on the search index
The program exited via sys.exit(). Exit status:  0
```

I started to debug CKAN using `pdb` and I found that `package_show` is the function which is failing:
https://github.com/ckan/ckan/blob/2a9518e1c54f8283ffc586d8e456ce19c303f356/ckan/lib/search/__init__.py#L200-L201

Note that the exit status is wrong too, as CKAN overrides the exit code when fetching the errors. Related to https://github.com/ckan/ckan/issues/4514.

**Comment by frafra** [comment]
This issue is related to an extension which relies on `g.user` to create a new context.

**Comment by frafra** [comment]
This is how I fixed that:

```diff
 def new_context():
-    return {
+    context = {
         'model': model,
         'session': model.Session,
-        'user': g.user,
         'for_view': True,
-        'auth_user_obj': g.userobj,
     }
+    for attr in ('user', 'userobj'):
+        if hasattr(g, attr):
+            context[attr] = getattr(g, attr)
+    return context
```

Feedback is welcome.

I didn't have the same issue in CKAN 2.8.4 for some reason.

**Comment by amercader** [comment]
Flask raises an exception if you try to access an non-existing property of the `g` object. On CKAN 2.8 the `g` object implementation was provided by Pylons which doesn't fail. Your approach here seems correct.
