### ISSUE TITLE
db update Fail after migrating database from ckan 2.8.3 to ckan 2.9.3 instance

### ISSUE THREAD

**Issue by hussnainwithss** [ckan/ckan#6627]
**CKAN 2.9.3 by LinkDigital**

**Describe the bug**
Im following the guide on migrating database from 2.8 to 2.9.3 (both are from linkdigital). after taking dump and restoring it using pg_restore. i need to update the schema after migrating 2.8 version data. but db update command gives error. it also gives warning that harvester table creation deferred. 

**Steps to reproduce**
1- dump database from ckan 2.8 instance using `sudo -u postgres pg_dump --format=custom -d ckan_default > ckan.dump`
2- copy the dump file from 2.8 to 2.9 instance
3- run the following command to restore DB `ckan -c /etc/ckan/default/ckan.ini db clean
sudo -u postgres pg_restore --clean --if-exists -d ckan_default < ckan.dump`
4- it will give the error in the screenshot
![WhatsApp Image 2022-01-04 at 6 50 17 PM](https://user-images.githubusercontent.com/47157583/148070090-76bd6c6a-ab48-4ed5-b952-e16b2096f51a.jpeg)

**Expected behavior**
Database should upgrade and instance should work fine.

**Additional details**
```
(default) ec2-user@ip-172-31-1-179:~> ckan -c /etc/ckan/default/production.ini db upgrade
2022-01-05 01:01:51,811 INFO  [ckan.cli] Using configuration file /etc/ckan/default/production.ini
2022-01-05 01:01:51,811 INFO  [ckan.config.environment] Loading static files from public
2022-01-05 01:01:51,871 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-01-05 01:01:52,477 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
(psycopg2.errors.InvalidSchemaName) no schema has been selected to create in
LINE 2: CREATE TABLE alembic_version (
                     ^

[SQL:
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL,
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

]
(Background on this error at: http://sqlalche.me/e/f405)

```

**Comment by smotornyuk** [comment]
> no schema has been selected to create in

Something is wrong with your DB dump or DB server settings. Check [this StackOverflow post](https://stackoverflow.com/questions/41207259/no-schema-has-been-selected-to-create-in-error)

**Comment by hussnainwithss** [comment]
> > no schema has been selected to create in
> 
> Something is wrong with your DB dump or DB server settings(2.8 and 2.9 configured in a different way?). Check [this StackOverflow post](https://stackoverflow.com/questions/41207259/no-schema-has-been-selected-to-create-in-error)

so basically we are using the base instance provided by linkDigital. it is possible they are configured in different ways as i havent modified any of them.  The 2.8 dump does have other extensions installed that modify the schema and add new meta fields. where as the 2.9 one doesnt have those extensions installed. can that might be the issue?

**Comment by smotornyuk** [comment]
> it is possible they are configured in different ways as i havent modified any of them

Yes, it's possible. I've tested your examples of `pg_dump`/`pg_restore` on my local PostgreSQL server and it worked like a charm. 
This means, that commands are correct. You haven't modified the dump itself, so the only possible problem from my point of view is the differences between PostgreSQL services that you are using for your old and new CKAN application.


> The 2.8 dump does have other extensions installed ... whereas the 2.9 one doesn't have those extensions installed

Do you mean, that on CKAN 2.8 you have some CKAN extensions, that create tables? And you did not enable these extensions for CKAN 2.9, right? In that case, it shouldn't be a problem. CKAN extensions usually just create new tables and these tables are ignored if you don't have the corresponding extension enabled(except for ckanext-spatial, which requires PostGIS extension for PostgreSQL)

**Comment by hussnainwithss** [comment]
@smotornyuk it works locally for me as well. but when i take the dump to a remote ckan 2.9 server it work restore anything. and throws the error. ill try to recreate both servers again and then try and will also look at the configurations. since you work with LinkDigital would you be able to let me know if there are any configuration changes made in the new ckan 2.9 AWS AMI.

**Comment by smotornyuk** [comment]
Yep, i'll share this discussion with our team

**Comment by smotornyuk** [comment]
@hussnainwithss , I've discussed it with the team and they confirmed that there was nothing special about your instance's image. It was using exactly the same defaults as any other LinkDigital's images

**Comment by hussnainwithss** [comment]
> @hussnainwithss , I've discussed it with the team and they confirmed that there was nothing special about your instance's image. It was using exactly the same defaults as any other LinkDigital's images
okay so the issue is with the backup file it self i think.

**Comment by hussnainwithss** [comment]
@smotornyuk i redid the whole process using fresh instances, but used pgadmin to restore data and everything is working fine.  Was able to restore whole data along without any issues. Thank you for your help. 💯
