### ISSUE TITLE
organization_facets not working, instead replaced by group_facets but no description given about the change

### ISSUE THREAD

**Issue by mominimtiaz786** [ckan/ckan#6636]
**CKAN version**
2.9

**Describe the bug**
[organization_facets](https://docs.ckan.org/en/2.9/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IFacets.organization_facets) that were working in the 2.8 version of ckan are not working any more and there is no description in the documentation about changing of any thing. Instead group_facets function is being used to render facets on organization page, which was supposed to work on group page.

**Steps to reproduce**
I dig deep down into the framework code and got to know that upexpected and unnecessary changes have been made which are not even documented. I researching thoroughly I got to know that organization_facet is nowehere registering or updating our facets instead [group_facets](https://docs.ckan.org/en/2.9/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IFacets.group_facets), which is supposed to work on groups page is being used to render facets on organization page

**Expected behavior**
The organization_facets function supposed to work as it used to work in ckan 2.8 version i.e. render the facets on organization page but now it is not updating the facet_dict that needs to be rendered.

**Additional details**
links have been attached and the necessary detail is provided regarding the issue

**Comment by hussnainwithss** [comment]
@amercader any updates on this issue?

**Comment by tino097** [comment]
@amercader @hussnainwithss @mominimtiaz786 
The issue exists because the [function](https://github.com/ckan/ckan/blob/2.8/ckan/controllers/organization.py#L27) for organizations was not migrated from pylons to flask correctly.

@TomeCirun was working on this and he would provide a PR later this week
