### ISSUE TITLE
uwsgi in supervisor : spawn error

### ISSUE THREAD

**Issue by maxclac** [ckan/ckan#6670]
**CKAN version**
2.9.5

**Describe the bug**
I am using CKAN with Supervisor. I have the following error when I try to restart uwsgi in supervisor:
```
# supervisorctl restart ckan-uwsgi:ckan-uwsgi-00
ckan-uwsgi:ckan-uwsgi-00: ERROR (not running)
ckan-uwsgi:ckan-uwsgi-00: ERROR (spawn error)
```
The uwsgi logs tell me this:
```
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jan 24 11:17:41 2022] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 04 October 2021 08:17:00
os: Linux-3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022
nodename: zzz
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /tmp/ckan-uwsgi.pid
detected binary path: /usr/lib/ckan/default/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 31762
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8080).
bind(): Address already in use [core/socket.c line 769]
VACUUM: pidfile removed.
```
This happened after a reboot. Before it was working fine. What can I do?

**Comment by maxclac** [comment]
It turns out that CKAN on this machine runs both with supervisor and as a service with systemd. Both conflict with each other. If I turn off the systemd-deployed CKAN with `systemctl stop ckan`, I can restart supervisor normally without problem. Is it safe in that case to completely remove the ckan.service file, so that I don't have this problem again in the future?

**Comment by kowh-ai** [comment]
Yes @maxclac - you have a choice of either - looks like you already know what's going on

**Comment by Namwanza** [comment]
You need to reload apache2 and nginx:

1. sudo service apache2 reload
2. sudo service nginx reload

Then, restart CKAN Worker

1. sudo supervisorctl restart ckan-worker:*

your ckan-worker will be stopped and started again without errors:
_ckan-worker:ckan-worker-00: stopped
ckan-worker:ckan-worker-00: started_
