### ISSUE TITLE
API option doesn't show when the multiple resources are added to the new datasets. 

### ISSUE THREAD

**Issue by sagargg** [ckan/ckan#6672]
**CKAN version**
**2.9.5**

**Describe the bug**
Datastore won't get active when multiple resources are added to the newly created datasets. 

**Steps to reproduce**
1. Create Datasets 
2. Add New resource 
3.  Click `Save and add another` resource to add another resource. 
4.  Finally click `Save` to finish the dataset creation. You will see that only one dataset has an API option,  even all files pushed to the datastore. 

**Expected behavior**
datastore state should be active even when multiple resources are added. 

**Additional  details**
I think for some reason datastore state doesn't get updated for the draft dataset.

**Comment by TomeCirun** [comment]
Hey @smotornyuk, @sagargg,  I was doing a bit of research about this problem, seems everything's fine except this query from `solr` which returns an empty list after we submit the first resource:
https://github.com/ckan/ckan/blob/d61a533cc330b6050f4957573f58ec912695ed0a/ckanext/datastore/logic/action.py#L662-L668

So our first resource never reaches for the update in line 666 which contains the `{'datastore': True}`

Seems like `solr` cannot find the package with the given id when we are adding two resources in a row with `save & add another` `button`... (This is valid for the first resource only.)

Do you have any idea why this happens? 
Thanks

ps. One weird behavior I've noticed: accidentally forgot to remove breakpoints (which cause to stop the worker) and after submitting both resources in a row I noticed the worker stuck on the breakpoint after exiting it I can see now both resources are with Data API.

**Comment by smotornyuk** [comment]
By default CKAN [filters out all draft datasets(non-active)](https://github.com/ckan/ckan/blob/master/ckan/lib/search/query.py#L339-L340). When created dataset remains in the draft state till the user clicks on the **Finish** button.

**Comment by smotornyuk** [comment]
Generally, yes. Just don't forget to take into account the fact that `package_show` can throw NotAuthorized/NotFound exceptions if the context is misformed. Not sure if it's possible to get such an exception  in this particular case(there person, who uploads a resource probably has full access to the given package), but it's better to check if any worth-case scenario can happen

**Comment by TomeCirun** [comment]
@smotornyuk Thanks
