### ISSUE TITLE
/Organization package count incorrect, Collaborator private packages aren't included. 

### ISSUE THREAD

**Issue by n00dl3nate** [ckan/ckan#6694]
**CKAN 2.9**

Packages that you are a collaborator of are not included in the dataset count on the /organization view page but then are included on the organizations/<organistion_name> page.

I'm not sure whether this is the intended functionality? But it seems like packages you are a collaborator of should be included.

Thanks in advance.

**Comment by TomeCirun** [comment]
Hey, @n00dl3nate I've just tested this out, works fine for me, the only dataset that didn't count in the `/organization` page are those who are private...

**Comment by TomeCirun** [comment]
If the core team agreed to count the private datasets for collaborators on the `/organization` page I will make a PR

**Comment by n00dl3nate** [comment]
Hello, Thanks for your response, Apologies I left out that piece of information that it is private datasets that you are a collaborator of isn't being included in the dataset count on but private datasets that are owned by an organisation that you are a member of are included in the count. is there a reason why they shouldn't be included in the count?

**Comment by amercader** [comment]
@TomeCirun @n00dl3nate Yes, these two counts should have the same value. Also compare it to the Organization facet on the dataset search page to make sure they match
