### ISSUE TITLE
Api Token and `get_site_user` 

### ISSUE THREAD

**Issue by tino097** [ckan/ckan#6721]
After introducing the Api Token and merging  #6352 we are moving towards removing apikey from the [user](https://github.com/ckan/ckan/blob/master/ckan/model/user.py#L53) model. 

That will cause [`get_site_user`](https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L2402) action not to work anymore so we will need to create api token and return its value back in the response

**Comment by wardi** [comment]
Closing as discussed in #6722
