### ISSUE TITLE
Minor design fixes in latest theme

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#6782]
These should be easy to fix for a CSS wizard :stars: . They might be leftovers from the Bootstrap 5 migration or previous issues:

*Note:* Make sure to compile the SASS files if working from master, running `ckan sass`

- [ ] Misaligned "Remove" button on resource upload fields

![Screenshot 2022-03-22 at 12-56-56 Add data to the dataset - CKAN](https://user-images.githubusercontent.com/200230/160822278-2b250895-2371-43a3-9c17-a6a32727105d.png)

- [ ] Extra whitespace in primary section header (eg dataset or org page)

![Screenshot 2022-03-30 at 13-11-17 Test datasets 222222 - CKAN](https://user-images.githubusercontent.com/200230/160822783-5a3da219-1ff8-4d3e-8e0a-b7c8042e338c.png)

- [ ] Extra white space in dashboard tabs heading (might be the same issue as before)

![Screenshot 2022-03-22 at 12-54-11 Manage - Adrià 33333 - Users - CKAN](https://user-images.githubusercontent.com/200230/160822769-e1aa0d85-9df9-4ddd-a5d2-a57e53b8f479.png)

![Screenshot 2022-03-22 at 12-54-18 Manage - Adrià 33333 - Users - CKAN](https://user-images.githubusercontent.com/200230/160822729-399318a2-21c5-4347-8ab9-01228c033a5d.png)

I could not find any other glaring issue but if you do please report it here.

**Comment by hussnainwithss** [comment]
@amercader can you assign me this. i can fix this.

**Comment by hussnainwithss** [comment]
@amercader found another possible design issue at the dashboard page 
![image](https://user-images.githubusercontent.com/47157583/162358320-0d3c243f-b29e-4a09-ac6b-b92e1186030f.png)
