### ISSUE TITLE
Datatables view formatting / rendering issues

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan#6792]
**CKAN version**
master ~ 2.10.0a

**Describe the bug**
There are a few formatting issues with the updated datatables view in the current master. 

1. It seems the view is designed to fit within the resource view iFrame, but is slightly too large resulting in the 2nd (outer) vertical scroll bar.
2. The icons for sorting in the column headings are missing
3. On mouseover of longer table entries, the text wrapping changes resulting in a broken table appearance.
4. The content below the table (dataset info & sorting details) seems squished or laid out incorrectly.

![image](https://user-images.githubusercontent.com/47568003/161569185-1e51646f-fd19-47df-a702-1e134356571d.png)

![image](https://user-images.githubusercontent.com/47568003/161569687-5ab7400b-a227-4b96-a4d8-5fe917e496f5.png)

**Additional details**
These observation were made using Chrome 100.0.4896.60

**Comment by jqnatividad** [comment]
@pdekraker-epa It needs some attention - the vendored plugin needs to be updated, and I need to clean up the JS a bit.

Will be sure to ping you once its done.

**Comment by jqnatividad** [comment]
pinging @twdben.  Let's team up on this...
