### ISSUE TITLE
Overwriting package_show auth function raises dataset not found

### ISSUE THREAD

**Issue by jannettim** [ckan/ckan#6795]
**CKAN version**
2.9.3

**Describe the bug**
Overwriting the package_show auth function in an extension produces dataset not found error for anonymous users when they attempt to access a package's webpage. This occurs both with code to limit access to remove access restrictions. Other auth overwrites seem to work as expected.

If the user is logged in, access is granted.

**Steps to reproduce**

1. Create an extension with a function that overwrites the package_show function with a custom one (such as the one included in the code below).
2. in the extension, overwrite the `get_auth_functions()` as below

```
# outside plugin class
def package_show(context, data_dict):

    return {'success': True}

# Inside the plugin class
def get_auth_functions(self):

   return {
		   "package_show": package_show
		   }
```

3. install extension
4. make sure you are logged out 
5. attempt to open a dataset's webpage

**Expected behavior**
Users should be able to access package pages regardless of permissions. Alternatively, if access is restricted, the package_show function should return custom error message or redirect.

**Additional details**

ERROR [ckan.config.middleware.flask_app] 404 Not Found: Dataset not found
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/venv/src/ckan/ckan/views/dataset.py", line 438, in read
    return base.abort(404, _(u'Dataset not found'))
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/base.py", line 66, in abort
    flask_abort(status_code, detail)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 774, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 755, in __call__
    raise self.mapping[code](*args, **kwargs)

**Comment by TomeCirun** [comment]
This happens because the default implementation of `package_show`  has an attribute `auth_allow_anonymous_access`. 
https://github.com/ckan/ckan/blob/2e63e7fbaf7208f122e8c90a419f7c71485423b9/ckan/authz.py#L84-L95

If you track down your `auth_function` you will see it will fail here: 
https://github.com/ckan/ckan/blob/2e63e7fbaf7208f122e8c90a419f7c71485423b9/ckan/authz.py#L233
to avoid this you can use decorator on your auth_func: 

```
import ckan.plugins as p 

@p.toolkit.auth_allow_anonymous_access
def package_show()
```

**Comment by Zharktas** [comment]
If you would call the api directly, it would so the reason for failure which in this case is that it requires authenticated user. The UI shows 404 Not found for both non-existing datasets and those where user does not have permission due to security reasons.

**Comment by Zharktas** [comment]
Currently it's not possible to customize the error messages except by changing the localizations. One improvement for this could be that instead of "Dataset not found" the error message would "Dataset not found or you've no permission to view it"

**Comment by jannettim** [comment]
Thank you for the help, the provided code addresses my immediate need. Additionally, something like the error message @Zharktas wrote might have preempted the user feedback that preceded my attempt to change the error message.

**Comment by Gauravp-NEC** [comment]
@jannettim @Zharktas , I am interested to work on this issue.
