### ISSUE TITLE
CKAN version is exposed to the public

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#6827]
**CKAN version**

2.8, 2.9

**Describe the bug**

The exact version of CKAN is visible to the public in the status_show API call and as a header on all emails. This makes reconnaissance by malicious third parties easier.

**Steps to reproduce**

Visit /api/action/status_show

**Expected behavior**

There should be an option to hide the CKAN version in use.

**Additional details**

Will raise a pull request soon.

**Comment by knudmoeller** [comment]
There is a related issue: #6833 (Action status_show has no corresponding auth function).

**Comment by ThrawnCA** [comment]
@knudmoeller Related, but I think that each approach offers something the other doesn't.

**Comment by knudmoeller** [comment]
@ThrawnCA Yes, absolutely! The approaches are not mutually exclusive. I just wanted to point out the relatedness.
