### ISSUE TITLE
WARNING: ftell mismatch with expected position -- ftell used

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [ckan/ckan#6856]
**CKAN version**
2.9.3
**Describe the bug**
Try to use:
sudo -u postgres pg_restore --clean --if-exists -d ckan_default < ckan.dump
with a dump from my database
I got this error:
`pg_restore: [custom archiver] WARNING: ftell mismatch with expected position -- ftell used`

**Expected behavior**
dump goes into the database

**Comment by Zharktas** [comment]
Did you follow the documentation creating the dump http://docs.ckan.org/en/2.9/maintaining/database-management.html#dumping-and-loading-databases-to-from-a-file ?

If you did and the it still doesn't work, its probably not a ckan bug https://stackoverflow.com/a/53405737/622796
