### ISSUE TITLE
No "Previous" button in Dataset edit form page

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#6857]
**CKAN version**
Master
**Describe the bug**
There is no "Previous" button available in Dataset edit form page. If a user changes his mind not to edit Dataset form page or mistakenly reached to Dataset edit form page, there should be a "Previous/back" button to go back to previous page. 

**Steps to reproduce**
Edit any Dataset.

**Expected behavior**
 There should be a "Previous/back" button to go back to previous page. 

**Additional details**
Currently, user can only go back using `browser` back arrow.

**Comment by Gauravp-NEC** [comment]
This issue is related to the https://github.com/ckan/ckan/issues/6623

**Comment by wardi** [comment]
There are a couple of ways a user could arrive at the dataset edit page so adding a back button might be unclear. Also the breadcrumbs can be used to return to the dataset view page, so this feature would be duplicative.
