### ISSUE TITLE
Getting Missing header token when using right-time-context plugin

### ISSUE THREAD

**Issue by Nisha-1212** [ckan/ckan#6867]
**CKAN version** 2.7.2

**Describe the bug**
I have installed the "ckanext-right_time_context" plugin in ckan source code setup. And also enabled this plugin in ckan.ini file.
I have followed the [ckanext-right_time_context ](https://github.com/conwetlab/ckanext-right_time_context) site link. Add one new resource by performing the  all steps mentioned in this above link. I am getting the below error.

**Error:** 
HTTPError: DataPusher received a bad HTTP response when trying to download the data file status=401 url=https://robin.fs.in/orion/v2.0/entities?type=AirQualityObserved response=<ams:fault xmlns:ams="[http://wso2.org/apimanager/security"><ams:code>900902</ams:code><ams:message>Missing](http://wso2.org/apimanager/security%22%3E%3Cams:code%3E900902%3C/ams:code%3E%3Cams:message%3EMissing) Credentials</ams:message><ams:description>Required OAuth credentials not provided. Make sure your API invocation call has a header: "Authorization: Bearer ACCESS_TOKEN"</ams:description></ams:fault>

Can any one help that how the CKAN code get this header token in the request when accessing the orion resource url.

**Comment by Zharktas** [comment]
ckanext-right_time_context is not develop by the CKAN core team, so you should post the issue on their github repo instead.
