### ISSUE TITLE
Fixtures and setup() methods order of execution changed on current master

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#6880]
**CKAN version**
master (CKAN 2.10)

**Describe the bug**

Consider the following test:

```python
# test_hello.py
@pytest.fixture
def hello():
    print("Hello")

@pytest.mark.usefixtures("hello")
class TestHello:

    def setup(self):
        print("world")

    def test_hello(self):
        pass
```

In CKAN 2.9 (pytest 4.x) -> First fixtures get executed, then `setup()` methods:

```
pytest --ckan-ini=test-core.ini -s --disable-warnings test_hello.py                                                                                                                          
======================================================== test session starts =========================================================
platform linux -- Python 3.8.10, pytest-4.6.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/adria/dev/pyenvs/ckan-29/src/ckan/ckan, inifile: setup.cfg
plugins: rerunfailures-8.0, ckan-0.0.12, cov-2.7.1, freezegun-0.4.1, pyfakefs-3.2, split-tests-1.0.9, Faker-8.8.1
collected 1 item                                                                                                                     
test_hello.py Hello
world
.

```

In CKAN 2.10 (pytest 7.x) -> First `setup()` methods get executed, then fixtures:

```
pytest --ckan-ini=test-core.ini -s --disable-warnings test_hello.py        
==================================================================== test session starts ====================================================================
platform linux -- Python 3.8.10, pytest-7.1.1, pluggy-0.13.1
rootdir: /home/adria/dev/pyenvs/ckan-py3/src/ckan, configfile: pyproject.toml
plugins: requests-mock-1.9.3, freezegun-0.4.2, mock-3.7.0, split-0.7.0, cov-3.0.0, rerunfailures-10.2, factoryboy-2.1.0, pyfakefs-3.2, split-tests-1.0.9, Faker-13.3.4
collected 1 item                                                                                                                                            

test_hello.py world
Hello
.
```

This is bad, because you generally want the 2.9 behaviour, eg to clean up the db or the index using fixtures, and then on the `setup()` method create some datasets, etc.

I need to investigate if this is a pytest version issue or because of the way CKAN runs the tests

**Comment by amercader** [comment]
On second thought this should have likely impacted the core tests before so maybe is something on my environment, I'll keep digging

**Comment by TomeCirun** [comment]
Same here @amercader, i set 2 breakpoints, when i execute the class `TestHello`, first, it stops on `setup` then on the `fixture hello`, this only happens on `CKAN 2.10`...

**Comment by TomeCirun** [comment]
@amercader  I found that, if we pass: `scope='class'` as a parameter,  `fixtures` get executed  first, then `setup()` methods

```python
@pytest.fixture(scope='class')
def hello():
    print("Hello")
```

**Comment by amercader** [comment]
Behaviour changed between pytest 6.x and 7.x. I've asked a question on the pytest repo: https://github.com/pytest-dev/pytest/discussions/10005

**Comment by amercader** [comment]
Looks like regardless than this is a pytest a regression or not it's worth updating your tests to not rely on `setup()` and `teardown()` methods anymore.
I've put down some guidelines in our 2.9 to 2.10 migration doc:

**Comment by TomeCirun** [comment]
should i make PR ?

**Comment by amercader** [comment]
@TomeCirun what for?

**Comment by amercader** [comment]
@TomeCirun oh, you meant to update tests in core that still use `setup()`? That makes sense if you have spare time but it's not a priority, there aren't many of them and they are obviously passing

**Comment by amercader** [comment]
Looks like this is [not going to get fixed in pytest](https://github.com/pytest-dev/pytest/discussions/10005), so let's just recommend rewriting the tests:

https://github.com/ckan/ckan/wiki/CKAN-2.9-to-2.10-migration-tips#test-classes-setup-methods-not-firing-or-firing-in-wrong-order
