### ISSUE TITLE
Member_delete causes not found errors even though everything should be present

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#6886]
**CKAN version**
2.9, master

**Describe the bug**
Clicking delete member from organization results in not found.

**Steps to reproduce**
Create an organization.
Add an user to it.
Delete the user from it.

**Expected behavior**
Member is deleted and the UI returns to member view 

**Additional details**
Most likely bug resides in this line https://github.com/ckan/ckan/blob/91c9366cf8df0dc4e12a9a043756eda5e40534b0/ckan/views/group.py#L548 as it calls `group_show` with user id.

**Comment by Zharktas** [comment]
This actually requires that javascript is disabled for whatever reason, which is why it wasn't caught before. The modal works, but the url from the delete button does not. Can be reproduced by copying the url from the button and pasting it to the browser url bar.

**Comment by kowh-ai** [comment]
@TomeCirun - just confirming the bug/error is the following:

![Screenshot 2022-06-06 at 11 25 01 am](https://user-images.githubusercontent.com/54408245/172134112-56c8e3e9-92a5-4424-b037-73a6050ea4f1.png)

I'll test the fix once confirmed  - thanks!
