### ISSUE TITLE
Delete User Web UI

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [ckan/ckan#6893]
**CKAN version**
2.9.3

**Describe the bug**
I delete a user with the web-ui. Now I try to add a user with the same e-mail and I got an error the email already exists, but
the user is removed.

**Steps to reproduce**
Create a user an try to delete the user in the web ui. Then create a user with the same email address.

**Expected behavior**
Removing a user removes all data.

**Additional details**
Where is the e-mail saved? In the database I found nothing.

**Comment by TomeCirun** [comment]
The current workflow is as follows: when you delete a user, we are actually changing its state from 'active' to 'deleted', we are not deleting it from the database.
https://github.com/ckan/ckan/blob/89c7b6063a9cf0e0198ce2c4aa04030f2ed9be8b/ckan/model/core.py#L19-L21

Thanks

**Comment by MichaelHarmsTIB** [comment]
In the user table there are no other users except postgres.
If you save users where you save it?

**Comment by MichaelHarmsTIB** [comment]
ckan_default there all tables from ckan.

**Comment by EricSoroos** [comment]
I literally _just_ got an identical support request here. 

` select * from "user" ` gets you ckan users.
```
                  id                  |              name               |                apikey                |          created           |                                         about                                         |                                                              password                                                              | fullname |                   email                   |            reset_key             | sysadmin | activity_streams_email_notifications |  state  | plugin_extras | image_url 
--------------------------------------+---------------------------------+--------------------------------------+----------------------------+---------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+----------+-------------------------------------------+----------------------------------+----------+--------------------------------------+---------+---------------+-----------
...
(5 rows)
```
` select * from user` gets you your current user.
```
ckan=> select * from user;
 user 
------
 ckan
(1 row)
```

**Comment by MichaelHarmsTIB** [comment]
Interesting:
ckan_default=# select * from user;
   user   
----------
 postgres
(1 row)
If I do that.
Thx for the hint.

**Comment by EricSoroos** [comment]
Possible solutions to this from the CKAN side:
1) The validator only checks emails from active accounts, so that instead of unique(email), it's unique(email) where state=active
2) When deleting the user, the email address is munged or deleted.
3) Duplicate email addresses permitted.

**Comment by wardi** [comment]
Re solution 1: what happens when the old account is re-activated? Maybe we can validate email uniqueness on users only when active is set to True. I think this is workable.

Re solution 3: This goes against https://github.com/ckan/ckan/pull/6748 which has been a very frequently requested feature.

**Comment by EricSoroos** [comment]
Yeah. I understand the duplicate email thing. 

I think we've potentially got one too many identifiers for the user. 

1) Internal id. This is what we should always use for referential integrity.
2) Display name. I don't care what it is (other than it shouldn't allow xss and has length limits) but it's used in public display. 
3) Email. Contact method. Type-able identifier. 

Leaving username as a why-bother identifier, other than it's shorter than the email address for typing purposes when logging in.

**Comment by EricSoroos** [comment]
I think it's fair that if someone has a deleted account, and then they make a new account with the same email, that the original one can't be reactivated without deleting the other one. At any rate, the confusing errors that would come from that would be at least 10x less common than this case.
