### ISSUE TITLE
Issues with Ckanext-saml2auth extension on xmlsec1 dependency

### ISSUE THREAD

**Issue by abhisheksridh** [ckan/ckan#6904]
### Discussed in https://github.com/ckan/ckan/discussions/6903

<div type='discussions-op-text'>

<sup>Originally posted by **abhisheksridh** June 10, 2022</sup>
We are having issues with xmlsec1 library, which has some outdated libraries as follows:

-xmlsec1-devel (1.2.25)
-xmlsec1-openssl-devel (1.2.25)
-libtool-ltdl-devel (2.4.6)
</div>

**Comment by duskobogdanovski** [comment]
Hey @abhisheksridh, if it's related ckanext-saml2auth please move it to the extension repository and please add some more details for the issue.
