### ISSUE TITLE
CKAN licences for resources manageable at the user interface

### ISSUE THREAD

**Issue by ondics** [ckan/ckan#6927]
Our project experiences with CKAN is that quite different resources are attached to datasets in the CKAN filestore, e.g. excel-files, images, csv-files, shape-files, and so on.

Considering the creation processes of this resource files, there may apply different licenes for these files. E.g. images could have licence constraints that don't allow to change the licences to the dataset licence.

So we need per-resource licences in the CKAN core that can by managed at the user interface.

This feature got more attention recently since DCAT-AP and national harvesting processes require licences at the resource level-

_Originally posted by @ondics in https://github.com/ckan/ckan/issues/2091#issuecomment-1160478288_

**Comment by Zharktas** [comment]
The default schema shouldn't be changed to accommodate individual needs as the change would then be applied to everyone who hasn't customized their schemas. This change can already be done by customizing the schema in your extension.
