### ISSUE TITLE
Robots.txt can no longer be easily customised

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#6930]
**CKAN version**

2.9

**Describe the bug**

`robots.txt` was moved back to the `public` directory as part of #4801. However, this reverts the implementation of https://github.com/ckan/ideas-and-roadmap/issues/178 and makes it harder to customise the file (it can still be overridden with a different version, but not using Jinja syntax).

**Comment by ThrawnCA** [comment]
In case it's relevant to anyone, serving `robots.txt` from the templates directory can be re-enabled with a blueprint rule similar to:

    blueprint.add_url_rule(u'/robots.txt', 'robots', view_func=lambda: render('robots.txt'))

(Also, if the `robots.txt` file contains `{% ckan_extends %}`, that directive will need to be removed.)

**Comment by duttonw** [comment]
yes very strange

routing removed here: https://github.com/ckan/ckan/commit/8ee21484d3ceb6c0f0d9eb8d239a3a97baf2e5ac
jinja template parts removed here: https://github.com/ckan/ckan/commit/4a05d5cd09ada5abde1dd74ae545679eef61aad8

**Comment by wardi** [comment]
@amercader was there a reason for serving robots.txt from the public directory instead of a view?
