### ISSUE TITLE
Circle-CI not hilighting errors

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#6938]
**CKAN version**
master

**Describe the bug**
on our circle-CI builds errors used to be called out and easy to find in the reports, this was done by exporting junit.xml along with our tests: `--junitxml=/root/junit/junit.xml` https://github.com/ckan/ckan/blob/bfcc37596bf37113c2ad3774dd3a0b5002e071ed/.circleci/config.yml#L25

**Steps to reproduce**
Have a test fail

**Expected behavior**
See the exception in circle-CI without having to scroll through many screens of output

**Additional details**
Not sure if this was a change in circle-CI or to something about the way we configure test runs now

**Comment by smotornyuk** [comment]
Yes, it's a change of how CircleCI detects JUnit-files. Now it discovers only files inside a subfolder of the directory that contains artifacts. I've added a fix in #6940
