### ISSUE TITLE
CKAN 2.9 is not compatible with Python 3.9, should be documented

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#6974]
**CKAN version**

2.9

**Describe the bug**

CKAN 2.9 relies on Markdown 2.6.7, which is incompatible with Python 3.9 (see https://github.com/Python-Markdown/markdown/issues/953). This should be documented at http://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html

**Steps to reproduce**

- Install Python 3.9.
- Install CKAN 2.9.5 from source.
- Attempt to install the CKAN `requirements.txt`

**Expected behavior**

Incompatibilities should be documented on docs.ckan.org

**Additional details**

Installing collected packages: webencodings, webassets, unicodecsv, sqlparse, simplejson, shutilwhich, repoze.lru, pytz, python-magic, python-editor, pyjwt, polib, passlib, nose, markdown, funcsigs, certifi, beaker, zope.interface, werkzeug, webob, watchdog, urllib3, tzlocal, sqlalchemy, six, routes, redis, pyyaml, psycopg2, markupsafe, lxml, itsdangerous, idna, dominate, click, chardet, babel, rq, requests, repoze.who, pyutilib, python-dateutil, mako, jinja2, fanstatic, bleach, pysolr, flask, feedgen, alembic, flask-multistatic, flask-babel
  Running setup.py install for markdown: started
  Running setup.py install for markdown: finished with status 'error'
  error: subprocess-exited-with-error
  × Running setup.py install for markdown did not run successfully.
  │ exit code: 1
  ╰─> [78 lines of output]
      /tmp/pip-install-gf569cqa/markdown_b08317b0f93f43f9abe2a4632b7d77f7/setup.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
        import imp
      running install
      running build
      running build_py
      creating build/lib
      creating build/lib/markdown
      copying markdown/util.py -> build/lib/markdown
      copying markdown/serializers.py -> build/lib/markdown
      copying markdown/__main__.py -> build/lib/markdown
      copying markdown/blockprocessors.py -> build/lib/markdown
      copying markdown/inlinepatterns.py -> build/lib/markdown
      copying markdown/postprocessors.py -> build/lib/markdown
      copying markdown/blockparser.py -> build/lib/markdown
      copying markdown/__init__.py -> build/lib/markdown
      copying markdown/treeprocessors.py -> build/lib/markdown
      copying markdown/__version__.py -> build/lib/markdown
      copying markdown/preprocessors.py -> build/lib/markdown
      copying markdown/odict.py -> build/lib/markdown
      creating build/lib/markdown/extensions
      copying markdown/extensions/smarty.py -> build/lib/markdown/extensions
      copying markdown/extensions/attr_list.py -> build/lib/markdown/extensions
      copying markdown/extensions/sane_lists.py -> build/lib/markdown/extensions
      copying markdown/extensions/fenced_code.py -> build/lib/markdown/extensions
      copying markdown/extensions/nl2br.py -> build/lib/markdown/extensions
      copying markdown/extensions/headerid.py -> build/lib/markdown/extensions
      copying markdown/extensions/__init__.py -> build/lib/markdown/extensions
      copying markdown/extensions/toc.py -> build/lib/markdown/extensions
      copying markdown/extensions/tables.py -> build/lib/markdown/extensions
      copying markdown/extensions/def_list.py -> build/lib/markdown/extensions
      copying markdown/extensions/extra.py -> build/lib/markdown/extensions
      copying markdown/extensions/footnotes.py -> build/lib/markdown/extensions
      copying markdown/extensions/smart_strong.py -> build/lib/markdown/extensions
      copying markdown/extensions/codehilite.py -> build/lib/markdown/extensions
      copying markdown/extensions/meta.py -> build/lib/markdown/extensions
      copying markdown/extensions/abbr.py -> build/lib/markdown/extensions
      copying markdown/extensions/admonition.py -> build/lib/markdown/extensions
      copying markdown/extensions/wikilinks.py -> build/lib/markdown/extensions
      running build_scripts
      creating build/scripts-3.10
      copying and adjusting bin/markdown_py -> build/scripts-3.10
      changing mode of build/scripts-3.10/markdown_py from 644 to 755
      running build_docs
      Converting docs/cli.txt -> build/docs/cli.html
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-gf569cqa/markdown_b08317b0f93f43f9abe2a4632b7d77f7/setup.py", line 234, in <module>
          setup(
        File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/app/ckan/default/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.10/distutils/command/install.py", line 568, in run
          self.run_command('build')
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-gf569cqa/markdown_b08317b0f93f43f9abe2a4632b7d77f7/setup.py", line 184, in run
          out = template % self._get_context(src, outfile)
        File "/tmp/pip-install-gf569cqa/markdown_b08317b0f93f43f9abe2a4632b7d77f7/setup.py", line 116, in _get_context
          c['body'] = self.md.convert(src)
        File "/tmp/pip-install-gf569cqa/markdown_b08317b0f93f43f9abe2a4632b7d77f7/build/lib/markdown/__init__.py", line 375, in convert
          newRoot = treeprocessor.run(root)
        File "/tmp/pip-install-gf569cqa/markdown_b08317b0f93f43f9abe2a4632b7d77f7/build/lib/markdown/treeprocessors.py", line 361, in run
          brs = root.getiterator('br')
      AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
      [end of output]

**Comment by TomeCirun** [comment]
You can always find the supported python versions if you look at the setup.cfg/setup.py in any CKAN versions, but you are right, that should be in the ckan docs too.

 ![image](https://user-images.githubusercontent.com/72216462/179323392-e1aa2472-480a-4762-9e05-218276bbfd25.png)

**Comment by robin-NEC** [comment]
Hi @ThrawnCA , I would like to work on this issue.

**Comment by wardi** [comment]
would be much better to fix the incompatibility. python 3.9 is common these days

**Comment by amercader** [comment]
I agree, seems like an easy fix changing the version pinned. We should test the latest released version against different Python versions to catch stuff like this. Maybe not in the main repo, but on a separate one where we run a test matrix before each release

**Comment by amercader** [comment]
@smotornyuk @ThrawnCA got bitten by this and I updated the Markdown requirement on `dev-v2.9` (https://github.com/ckan/ckan/commit/46e443dedebedc40895bbfd63618f4200b21d086) so will be on 2.9.6. [Tests pass](https://app.circleci.com/pipelines/github/ckan/ckan/4167/workflows/04bf4ea7-b842-4ef7-b3f4-490362280745/jobs/12054/parallel-runs/3?filterBy=ALL)
