### ISSUE TITLE
Extend User Model

### ISSUE THREAD

**Issue by tpgmartin** [ckan/ckan#6977]
How do I add an attribute to the existing CKAN user model?

**Comment by amercader** [comment]
There is still no full support for scheming-like customization of the user schema (we need `IUserForm` for that, https://github.com/ckan/ckan/issues/6070). But the underlying `plugin_extras` that support this are already in place so with a bit of fiddling you can create custom user fields from an extension.

I wrote about the approach that needs to be followed here:

https://github.com/GenderDataLab/ckanext-genderdatalab/issues/5#issuecomment-881388621

Hopefully that will start you on the right path

**Comment by tpgmartin** [comment]
@amercader many thanks for your response. The link to the ckanext-genderdatalab returns 404 for me, can you please reshare the issue? Thanks

**Comment by amercader** [comment]
Apologies, didn't realise it was a private repo, here's a copy:

Sadly extending the user schema (ie metadata fields associated with a user object) is severely lacking behind datasets and orgs/groups, where thanks to [ckanext-scheming](https://github.com/ckan/ckanext-scheming) it's just a matter of editing a JSON/YAML file. That doesn't mean it's not possible, it will just take a bit more code to get working :slightly_smiling_face: 

For reference, to get full scheming support on user objects the following is needed:
1. `plugin_extras` support at the User model level: [done](https://docs.ckan.org/en/2.9/api/index.html#ckan.logic.action.create.user_create)
2. `IUserForm` to provide the necessary hooks and logic for plugins to extend the schema: not yet done (https://github.com/ckan/ckan/issues/6070)
3. Use the above interface to add user support in ckanext-scheming

There are no current plans to work on 2 and 3 in the short term, so you'll need to put something together with `plugin_extras` (or a separate table as we'll see in  a second).

Regardless of the actual implementation that you end up choosing, you will need to [extend the core user actions](https://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IActions) (`user_create` and `user_update` for input, `user_show` for output) to process the extra fields. The recommended way to do that is via [chained actions](https://docs.ckan.org/en/latest/extensions/plugins-toolkit.html#ckan.plugins.toolkit.ckan.plugins.toolkit.chained_action), here's a quick overview of the steps:

```python
@toolkit.chained_action
def user_create(up_func, context, data_dict):

    # Check data_dict for extra fields, validate if necessary

    # Store extra fields

    # Call core action
    return up_func(context, data_dict)

# Same for user_update

@toolkit.chained_action
def user_show(up_func, context, data_dict):

    # Get the default user dict with the standard fields
    user_dict = up_func(context, data_dict)

   # Add the extra fields to the output dict

   return user_dict
```

The goal is that when you call the `user_show` action (from your plugin or via the API) to get a particular user details, your custom fields are transparently added to the standard ones, eg:

```js
{
    // Core fields
    "id": "",
    "name": "amercader",
    "email": "amercader@example.com",
     // ...
     // Custom ones
    "social_url_twitter": "https://twitter.com/amercader",
    "city": "Tarragona",
     // ...
}
```


Now, on the topic of how to store the extra fields I see two options, which one two you use will depend on your plans and use case, and maybe even on the specific field.

1. Store as `plugin_extras`. The extra data will be stored against the user record in the database. You'll need to provide code in your custom actions to store incoming custom fields as `plugin_extras` on the way in and to retrieve them to the root level again on the way out. These make sense for properties that you always want close to the user, which are probably most of them
2. Store in a separate table linked by `user_id`. [Create a custom table](https://docs.ckan.org/en/2.9/extensions/best-practices.html?#use-migrations-when-introducing-new-models) with a field for the user id and store / retrieve data from there as necessary. This makes sense for fields that might be more related to other workflows or that don't need to be closely linked to the user (perhaps "How do you want to get involved?"), or of course it's an option if working with `plugin_extras` proves too cumbersome.

I perhaps would try to go with option 1 and see how it goes.

Here's a public implementation that follows the same pattern described, from where you can copy all the boilerplate code to work with `plugin_extras`:
* [`user_create`](https://github.com/okfn/ckanext-unhcr/blob/2a06af292768c48fc676a99d990d7d7f41e6771f/ckanext/unhcr/actions.py#L1219)
* [`user_update`](https://github.com/okfn/ckanext-unhcr/blob/2a06af292768c48fc676a99d990d7d7f41e6771f/ckanext/unhcr/actions.py#L1255)
* [`user_show`](https://github.com/okfn/ckanext-unhcr/blob/2a06af292768c48fc676a99d990d7d7f41e6771f/ckanext/unhcr/actions.py#L1203)
