### ISSUE TITLE
Inconsistent behaviuor in non-authorized errors (2.10)

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#6987]
**CKAN version**
2.10 (master)

**Describe the bug**

Following up from https://github.com/ckan/ckan/pull/6560, here's what happens when a user is not authorized to perform an action on the UI:

| CKAN Version | Logged in user | HTTP status, result |
| --- | --- | --- |
| <= 2.9 (tested 2.9 and 2.8) | No | 403 - Not authorized message
| <= 2.9 (tested 2.9 and 2.8) | Yes | 403 - Not authorized message
| 2.10, default behaviour | No | 302 + 200, Redirect to login page
| 2.10, default behaviour | Yes |  403 - Not authorized message
| 2.10, if `ckan.redirect_to_login_if_not_authorized` is False | No | 403 - Not authorized message
| 2.10, if `ckan.redirect_to_login_if_not_authorized` is False | Yes | 403 - Not authorized message

It seems that at the very least, we should 

1. fix the inconsistency between logged in users and non-logged in users in 2.10. Looks like we don't need to check `if current_user.is_anonymous` here:

https://github.com/ckan/ckan/blob/ed155dca25265562e1a9125ee6917b832d514b10/ckan/config/middleware/flask_app.py#L542

2. Decide if we want to change the default behaviour to redirect to the login page or keep the 403 error.

**Comment by wardi** [comment]
another option is to keep the 403 but render a login page on the error response. (bonus points for including a hidden parameter in the form to redirect to the original page after login)

**Comment by TomeCirun** [comment]
@amercader, @wardi it's true that anonymous users get redirected to the login page if 403 happens, but after they log in, ckan redirects them back to where they were and shows 403 if not authorized.

Isn't that what we needed?

**Comment by amercader** [comment]
@TomeCirun We discussed this in the dev meeting. It's probably best not to change the status code returned between CKAN versions (I had some tests broken because of this). But we can make easier for non-logged in users to login adding a link to the login page to the 403 or 401 error pages (embedding the form would make things more complicated for extensions overriding the authentication logic). So basically rendering `error_document_template.html` with a custom `content` [here](https://github.com/ckan/ckan/blob/ed155dca25265562e1a9125ee6917b832d514b10/ckan/config/middleware/flask_app.py#L551) instead of redirecting.

And then we can remove the `ckan.redirect_to_login_if_not_authorized` setting and simplify things.

Does this make sense?

**Comment by TomeCirun** [comment]
Everything coming from the dev meetings makes sense :), btw I remember we wanted the same behavior as on 2.9, you can see a comment from @pdelboca [here](https://github.com/ckan/ckan/pull/6560#issuecomment-1111859579 ) asking for that change, maybe we can check this before going any further?

@amercader

**Comment by amercader** [comment]
@TomeCirun I think extensions should gradually migrate to emit 403s instead of 401s to be consistent with the CKAN core behaviour so let's go ahead with the plan (cc @pdelboca)
