### ISSUE TITLE
Add a method for user to get a reminder of their username

### ISSUE THREAD

**Issue by darwinp** [ckan/ckan#699]
At the moment there is no way in CKAN 2.0 for a user to get a reminder of their username if they forget it.

This is a bit of an issue as users will often forget what username they signed up to an instance with. Could this be added or is it blocked by the fact that we don't insist that email addresses are unique?

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it. 

We're expecting an issue related to user-management/processing, so this will also be an old dupe.
