### ISSUE TITLE
Error when trying to install CKAN in a VM running Ubuntu 20.4

### ISSUE THREAD

**Issue by flaviofrancisco** [ckan/ckan#6996]
**CKAN version 2.9**

I am stuck trying to install CKAN from a package. The following error is happening during the installation:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Steps to reproduce**
- I have created a new Linux 20.4 VM instance in a Hyper-V
- Followed the steps 1 to 3 from the CKAN installation guide from package and
- Run the following command:
```bash
wget https://packaging.ckan.org/python-ckan_2.9-py3-focal_amd64.deb
```

**Expected behavior**
Install CKAN from package.

**Additional details**
```
flavio@ubuntu:~$ sudo dpkg -i python-ckan_2.9-py3-focal_amd64.deb
(Reading database ... 267176 files and directories currently installed.)
Preparing to unpack python-ckan_2.9-py3-focal_amd64.deb ...
Unpacking python-ckan (2.9.5-py3-focal1) over (2.9.5-py3-focal1) ...
sudo dpkg -i python-ckan_2.9-py3-focal_amd64.debSetting up python-ckan (2.9.5-py3-focal1) ...
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by flaviofrancisco** [comment]
Never mind, I was using Ubuntu 20.04 Jammy Jellyfish. It should be Ubuntu 20.04.4 LTS (Focal Fossa).

**Comment by S-mardii** [comment]
@flaviofrancisco are you meaning that CKAN is not running well on Ubuntu 22.04 Jammy Jellyfish, and you need to use Ubuntu Focal Fossa instead to have it working?

**Comment by shoully** [comment]
I had the same error on Ubuntu 22.04.1 LTS

"No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy"

**Comment by answerquest** [comment]
yikes, this means ckan can't be installed on ubuntu 22.x ?

**Comment by flaviofrancisco** [comment]
> 

Sorry for the long delay. Yes, that is it. We can't install it on Linux 22.04 LTS.

**Comment by kowh-ai** [comment]
Check out: https://github.com/ckan/ckan/wiki/CKAN-2.10-(aka-master-@1-Dec-2022)-install-on-Ubuntu-22.04
