### ISSUE TITLE
IConfigurer plugin load order

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#7009]
**CKAN version**
(all)

**Describe the bug**
`update_config` runs through all IConfigurer plugins from first to last calling `plugin.update_config`. The pattern for other interfaces is that the "first plugin wins", but this is difficult to implement when later plugins override values from earlier ones in the list.

**Steps to reproduce**
Enable two plugins that set the same config value using IConfigurer

**Expected behavior**
First plugin value should win, like with other interfaces.

**Additional details**
ckanext-envvars recommends adding `envvars` last in the list of plugins, which makes sense but if other plugins depend on/override values configured in envvars (e.g. ckanext-scheming) they won't be available at `update_config` time.

**Comment by amercader** [comment]
We decided to reverse the order in which `IConfigurer` plugins are read to be consistent with other hooks. Add a changelog entry.

**Comment by TomeCirun** [comment]
> We decided to [reverse the order](https://github.com/ckan/ckan/blob/f2eb20ebf9de21016fd3d15ed028be1cce8d447c/ckan/config/environment.py#L118) in which `IConfigurer` plugins are read to be consistent with other hooks. Add a changelog entry.

Great, I can work on this one :)
