### ISSUE TITLE
Provide a mechanism to support CSRF on extensions that support older CKAN version

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7016]
@TomeCirun @pdelboca 

After #6863, [best practices](https://github.com/ckan/ckan/blob/master/doc/extensions/best-practices.rst) say:

> To add CSRF protection to your extensions use the CSRF macro in all your forms

> {% import 'macros/form.html' as form %}
> ...
> {{ form.csrf_protection() }}

This won't work on CKAN<=2.9 because that macro doesn't exist. Similarly, trying to add the input directly like in [here](https://github.com/ckan/ckan/pull/6863/files#diff-09d2291ff01f465bfadf71b865872b83bd0301fc32f72e3fc96964a74a1619b0R7) will fail because the `csrf_token()` function is not defined.

My suggestion would be:

1. Consolidate all CSRF inputs into a single `{{ h.csrf_input() }}` call (both the ` {{ form.csrf_protection() }}` ones and the direct ` <input type="hidden" ...` ones). Using a helper will allow extensions to override it if necessary. Then we can use the same template markup everywhere.
2. Provide `h.csrf_input()` stubs on CKAN<2.9 that don't actually return anything. This could be done either:
   2.1. Patching CKAN core so 2.9.6 and 2.8.11 register `csrf_input()` template helpers, but they return an empty string
   2.2 Something similar but using ckantoolkit. I think this would be messier and even impossible.

At the end of this, an extension wanting to support CKAN<=2.9 and CKAN 2.10 with CSRF protection can just add the same code as core, and it will work across CKAN versions without messy checks on each extension:

```
  <form class="dataset-form add-member-form" method='post'>
    {{ h.csrf_input() }}
```

Does this make sense?

**edit**: updated to use a template helper instead of a Jinja tag

**Comment by amercader** [comment]
Forgot to say that this should be validated on everyone's favourite forms extension, ckanext-scheming!

**Comment by amercader** [comment]
@TomeCirun Does the above make sense? would you have time to work on it?

**Comment by TomeCirun** [comment]
Yes @amercader, I can work on this
