### ISSUE TITLE
IFacets implementation with organization_facets not present in v2.9 (backport master)

### ISSUE THREAD

**Issue by JVickery-TBS** [ckan/ckan#7017]
**CKAN version**
Version 2.9

**Describe the bug**
`organization_facets` is unused in the group view: https://github.com/ckan/ckan/blob/2.9/ckan/views/group.py#L375

**Steps to reproduce**

- Have a plugin class which implements `IFacets`
- Define `organization_facets` method in plugin class and return a custom dict of facets
- Try to access the custom facets in an organization template

**Expected behavior**
Plugin classes which implement `IFacets` and define `organization_facets` should load the returned facet dict.

**Additional details**
This is already corrected in the master branch: https://github.com/ckan/ckan/blob/master/ckan/views/group.py#L378
So this just needs a backport into ckan 2.9

Related commit: https://github.com/ckan/ckan/commit/560c9a259b6623001d72872e94eabe2081e10bb2

**Comment by amercader** [comment]
https://github.com/ckan/ckan/pull/6682 is marked for backporting, so it will be available in the next patch release
