### ISSUE TITLE
CSRF Protection changes not applied on BS3 template

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#7026]
**CKAN version**
Master

**Describe the bug**
This issue originates from https://github.com/ckan/ckan/pull/6863. Changes are not applied on BS3 template.

**Expected behavior**
Changes should be applied on BS3 template.

**Comment by Gauravp-NEC** [comment]
If dev team agree to have work on this issue. I will submit the PR. Thanks

**Comment by tino097** [comment]
@Gauravp-NEC Bootstrap 3 support will be removed for CKAN 2.10 where CSRF protection changes are applied.

**Comment by amercader** [comment]
@tino097 Are we removing the Bootstrap 3 templates from CKAN 2.10? I thought we would keep them for a version and then remove it to allow sites to migrate:

https://github.com/ckan/ckan/blob/34401f000846aa59559c77e755e56656cf1355f9/ckan/config/environment.py#L179

If that's the case then forms in templates-bs3 also need the `{{ h.csrf_input() }}` snippet

**Comment by Gauravp-NEC** [comment]
> @tino097 Are we removing the Bootstrap 3 templates from CKAN 2.10? I thought we would keep them for a version and then remove it to allow sites to migrate:
> 
> https://github.com/ckan/ckan/blob/34401f000846aa59559c77e755e56656cf1355f9/ckan/config/environment.py#L179
> 
> If that's the case then forms in templates-bs3 also need the `{{ h.csrf_input() }}` snippet

@amercader , If forms in templates-bs3 also need the `{{ h.csrf_input() }}` snippet then I will do this activity.

**Comment by tino097** [comment]
My bad https://github.com/ckan/ckan/pull/6307#issuecomment-995863296
@Gauravp-NEC you can provide the solution for this

**Comment by Gauravp-NEC** [comment]
> My bad [#6307 (comment)](https://github.com/ckan/ckan/pull/6307#issuecomment-995863296) @Gauravp-NEC you can provide the solution for this

@tino097 , Yes I will update the BS3 template. I will submit a PR.

**Comment by Gauravp-NEC** [comment]
@amercader @tino097 , Please assign this issue to me. Thanks:)
