### ISSUE TITLE
Block `extra_fields` empty in edit_user_form template-bs3

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#7053]
**CKAN version**
Master
**Describe the bug**
The block `extra_fields` is empty in edit_user_form template-bs3
Ref :https://github.com/ckan/ckan/blob/master/ckan/templates-bs3/user/edit_user_form.html#L26-L27
**Expected behavior**
Should include extra fields code like edit_user_form template.

**Comment by amercader** [comment]
Sure, go ahead
