### ISSUE TITLE
resource_patch does not update file size

### ISSUE THREAD

**Issue by bzar** [ckan/ckan#7075]
**CKAN version**
2.9.5, probably others

**Describe the bug**
Updating an uploaded resource file through API does not update the resource's `size` field

**Steps to reproduce**
1. Create a dataset and a file upload resource
1. Observe the resource's `size` field value
1. Change the file through the UI
1. Observe the resource's `size` field value changes as it should
1. Use the action API to upload a new file with `resource_patch` (or `resource_update`, I assume)
1. Observe the resource's `size` field value stays the same

**Expected behavior**
The file size should reflect the uploaded file regardless of the method used to upload it

**Additional details**
I assume this is because the resource already has a `size` field when `resource_update` calls  `package_update`, which assumes it is already set to the correct value. In `resource_create` the size is set, but `resource_update` just keeps the same value as before. Thus the new file size is not set.

**Comment by amercader** [comment]
TODO  https://github.com/ckan/ckan/blob/97d48e1d5ad0c52ba7352baa155bb320c74f0ae6/ckan/logic/action/update.py#L305

**Comment by robin-NEC** [comment]
Hi @amercader , I would like to work on this issue.

**Comment by bzar** [comment]
@amercader seems to fix the issue with a quick test. Since @robin-NEC has not PR'd yet I'll do it.
