### ISSUE TITLE
Update CKAN to Flask 2.2.2 (or latest)

### ISSUE THREAD

**Issue by pdelboca** [ckan/ckan#7083]
CKAN 2.9.5 and next 2.10.0 will be running under Flask 2.0.3.

Migration to Flask 2.2.2 will have some work that we would address once 2.10.0 is released. Some of the key points to be able to run the latest version:
- [x] We will need to update from Flask-Login `0.6.1` to `0.6.2` (See #7064 description)
- [X] We will need to fix/patch/replace `flask-multistatic` since it will not work with latest Werkzeug. It looks like the package it's not being maintained in a while, since it only and last release was 6 years ago: https://pypi.org/project/flask-multistatic/#history 
- [x] Fixing all tests ~122 failing tests when quickly fixing `flask-multistatic` locally.
- [x] We still can't update Flask-Babel to 2.0.0 as it breaks ITranslation (see https://github.com/ckan/ckan/issues/6708 and
https://github.com/python-babel/flask-babel/pull/194 cc @TkTech ) -> PR https://github.com/ckan/ckan/pull/7436
- [ ] `dev-requirements.txt`: docutils pinnned at 0.17 because sphinx-rtd-theme doesn't support a bigger version
- [ ] `dev-requirements.txt`: pytest-factoryboy pinnned at 2.4.0 because on 2.5.0 we get:

**Comment by amercader** [comment]
On the Flask-login failures, I'm pretty sure that they are caused by this change: https://github.com/maxcountryman/flask-login/pull/691

Somehow the combination of storing the logged in user in `g` instead of the stacks and the way CKAN tests with the `app` fixture are run breaks tings. We need to keep digging.
