### ISSUE TITLE
POST requests to API don't work with CSRF, tests bypass CSRF protection

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7095]
**CKAN version**
2.10

**Describe the bug**
The API is completely unusable since https://github.com/ckan/ckan/pull/7058 was merged.

Any POST API call (and presumably PUT, DELETE etc) returns a `400 Bad Request: The CSRF token is missing` error, which in hindsight makes sense because we removed the `@csrf.exempt` decorator from the `api.action` endpoint. We'll need to see how we can implement:

* API call + Cookie authentication = CSRF enabled (to support current frontend API usage)
* API call + Header authentication = CSRF disabled (to support external API calls)

But more worryingly,I found out that the tests are happily ignoring all these issues,  by bypassing CSRF protection entirely.

https://github.com/ckan/ckan/blob/367fed2fa572e896c5eb703db9c663e097133e41/ckan/tests/helpers.py#L271-L272

This might made sense while we were implementing the feature, but I think we need to discuss what we want going forward.

**Comment by duttonw** [comment]
Hit this issue in trying to get ckanext-validation on qld-gov-au progressing with our test setup configuration.

```
TEST_ORG=$( \
    curl -LsH "Authorization: ${API_KEY}" \
    --data "name=${TEST_ORG_NAME}&title=${TEST_ORG_TITLE}" \
    ${CKAN_ACTION_URL}/organization_create
)
```
https://github.com/qld-gov-au/ckanext-validation/blob/master/.docker/scripts/create-test-data.sh#L48


```
ckan_1      | 2022-10-13 00:08:04,366 INFO  [ckan.config.middleware.flask_app]  200 /api/3/action/status_show render time 0.025 seconds
ckan_1      | 2022-10-13 00:08:04,367 INFO  [werkzeug] 127.0.0.1 - - [13/Oct/2022 00:08:04] "GET /api/3/action/status_show HTTP/1.1" 200 -
ckan_1      | 2022-10-13 00:08:11,158 INFO  [ckan.config.middleware.flask_app] 400 Bad Request: The CSRF token is missing.
ckan_1      | 2022-10-13 00:08:12,302 INFO  [ckan.config.middleware.flask_app]  400 /api/action/organization_create render time 1.163 seconds
ckan_1      | 2022-10-13 00:08:12,303 INFO  [werkzeug] 172.19.0.5 - - [13/Oct/2022 00:08:12] "POST /api/action/organization_create HTTP/1.1" 400 -
```

**Comment by amercader** [comment]
@duttonw CKAN 2.10 (master) is not yet released so this kind on instability is to be expected
