### ISSUE TITLE
Delete dataset CSRF issue

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#7097]
**CKAN version**
master

**Describe the bug**
"400 Bad Request The CSRF token is missing" on deleting datasets with the web form.

**Steps to reproduce**
Click delete on the dataset edit form with JS enabled
![Screenshot from 2022-09-22 10-07-47](https://user-images.githubusercontent.com/153258/191770038-c59bcc83-58d4-4e67-800b-00d1a87987fb.png)
then click confirm

**Expected behavior**
deleted dataset

**Additional details**
Deletion works with JS disabled (plain confirm form instead of pop-up is used)

**Comment by TomeCirun** [comment]
@wardi it's already fixed https://github.com/ckan/ckan/blob/master/ckan/public/base/javascript/modules/confirm-action.js#L108

**Comment by amercader** [comment]
@TomeCirun please confirm if it's still an issue

**Comment by amercader** [comment]
Working as expected
