### ISSUE TITLE
User ID does not have to be unique?

### ISSUE THREAD

**Issue by jonathansberry** [ckan/ckan#7104]
**CKAN version**
CKAN 2.9.5

**Describe the bug**
The `id` field can be set by the user when calling the user_create API action. It appears that no check for ID uniqueness is made when doing so. This surprised me!  I was able to send multiple requests with the same `id` field, so long as they had different `name` fields, without any error being thrown.

**Steps to reproduce**
Perhaps the simplest way to reproduce is to run the following test:
```
import pytest
import ckan.tests.factories as factories

def test_user_id_uniqueness(self):
    factories.User(id='test-id')
    with pytest.raises(Exception):
        factories.User(id='test-id')
```

**Expected behavior**
I'd have expected the test above to pass, i.e. an exception to be raised (presumably a ValidationError) when creating a second user with the same ID. But no error is thrown, so the test fails. Furthermore I have confirmed the same behaviour appears when making similar requests as a sysadmin using the user_create action. 

Since the id is actually the primary key of the user table in the model, I'm assuming something odd is happening under the hood. 

**Is this a bug or intended behaviour?**

**Comment by smotornyuk** [comment]
Yes, you are right, this is a bug. We have started working on a fix
