### ISSUE TITLE
Is ckan.datasets_per_page not being used?

### ISSUE THREAD

**Issue by ddazal** [ckan/ckan#7111]
**CKAN version**
CKAN 2.9.5

**Describe the bug**
I set the _ckan.datasets_per_page_ configuration options to 10 and this is working fine on routes:
- /dataset/id
- /group
- /organization

 But is not working in the routes*
- /group/id
- /organization/id

where it always shows 20 results per page. Reading through the source code I noticed that the _read_ function called in *those routes receives a _limit_ parameter with a default value of 20, but it is not updated in the function body with something like

```python
the_limit = config.get('ckan.datasets_per_page', limit)
```
I added this change in my local installation and it worked. Is this by design or is it a bug? I just want to be sure that this is a bug before opening a PR.

https://github.com/ckan/ckan/blob/dc49cece33e447858d0008bc71b9a4ab724602ee/ckan/views/group.py#L408-L411

Thanks.

**Comment by amercader** [comment]
@ddazal That makes sense, want to submit a PR?
