### ISSUE TITLE
Add `csrf_input.html` in templates-bs3/snippets

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#7124]
**CKAN version**
Master
**Describe the bug**
Add csrf_input.html in templates-bs3/snippets like here https://github.com/ckan/ckan/blob/master/ckan/templates/snippets/csrf_input.html

**Expected behavior**
csrf_input.html should be added in templates-bs3/snippets

**Comment by Gauravp-NEC** [comment]
If dev team agree to have work on this issue. I will submit the PR.

**Comment by wardi** [comment]
yes, please

**Comment by Gauravp-NEC** [comment]
> yes, please

@wardi, Please assign this issue to me. Thanks
