### ISSUE TITLE
The resources on Transifex are obsolete

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#7151]
**CKAN version**

2.9.6

**Describe the bug**

The last update of the translation strings for CKAN 2.9 was on 2020-07-21.

**Steps to reproduce**

Navigate to https://www.transifex.com/okfn/ckan/2-9/.

**Expected behavior**

The resources should be updated.

**Additional details**

For example, the new string `Reorder resource view`  in the #6089 is missing.

**Comment by amercader** [comment]
The 2.9 resource in Transifex has been updated with the latest strings. There are about 18 new strings that need translation
Thanks for flagging @u10313335
