### ISSUE TITLE
docs.ckan.org is down

### ISSUE THREAD

**Issue by avdata99** [ckan/ckan#7154]
![image](https://user-images.githubusercontent.com/3237309/197840115-c5effccf-b938-4b4f-9554-509383e70b44.png)

**Describe the bug**
403 error trying to access CKAN documentation site

**Comment by wardi** [comment]
@avdata99 working for me now, do you see it? I clicked the "save" button on the domain page as readthedocs prompted.

**Comment by avdata99** [comment]
Is working now, closing.
Thanks @wardi

**Comment by avdata99** [comment]
No, it's not working
Reopening 🙃
