### ISSUE TITLE
allow plugins to implent old and new method names

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#7166]
**CKAN version**
master, 2.10

**Describe the bug**
In the past it has been possible for plugins to implement both the old and new names of methods, but since #7148 the new method gets overwritten by the old method.

**Steps to reproduce**
Use e.g. scheming_nerf_index plugin which implements both `before_index` and `before_dataset_index` for compatibility

**Expected behavior**
Not an infinite loop :upside_down_face: 

**Additional details**

**Comment by pdelboca** [comment]
We discussed this in the PR implementation because I detected that `ckanext-showcase` had a similar issue: https://github.com/ckan/ckan/pull/7148#issuecomment-1290327093

It was a recommendation that the issue was on the plugin's side and it will be better to fix it there. Maybe it is up to debate?

**Comment by wardi** [comment]
This is a small change that allows compatibility with extensions that try to support multiple versions of ckan. IMHO this makes more sense than forcibly replacing methods in plugins and requiring all extensions be aware of this quirk.
