### ISSUE TITLE
testing posts to forms from extensions

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#7168]
**CKAN version**
2.10, master

**Describe the bug**
posting to a view created by IDatasetForm in ckanext-scheming tests is triggering a CSRF protection failure:
https://github.com/ckan/ckanext-scheming/actions/runs/3364978110/jobs/5579953087#step:7:466

I've tried adding a token to the request headers the way it's done in `ckan/tests/controllers/test_package.py` to no avail.

Looking for guidance on fixing these test failures, @amercader I know you worked on fixing the related core tests, any suggestions?

**Comment by wardi** [comment]
here's the branch where I tried to make the tests work like the ones in master https://github.com/ckan/ckanext-scheming/tree/form-test-fixtures

**Comment by wardi** [comment]
problem was on my end, this is the test fixture I'm using in ckanext-scheming now: https://github.com/ckan/ckanext-scheming/blob/b53bb92a4ba6dc4b3e9087721a025534211e32ea/ckanext/scheming/tests/test_form.py#L11-L21

**Comment by amercader** [comment]
Great, I added it to the 2.9 to 2.10 migration notes:
https://github.com/ckan/ckan/wiki/CKAN-2.9-to-2.10-migration-tips#requests-with-the-test-client-and-csrf-failures
