### ISSUE TITLE
member_list action returns deleted users

### ISSUE THREAD

**Issue by avdata99** [ckan/ckan#7170]
**CKAN version**
2.9.7

**Describe the bug**
The `member_list` action with  `'object_type': 'user'` returns all member users, including deleted ones
This was fixed with #3078 but relies on the `user_delete` action.
If I manually delete a user from the DB, this will fail.

**Steps to reproduce**
Trying to iterate all members, you will get `toolkit.ObjectNotFound` for deleted users

```py
 users = toolkit.get_action('member_list')(context, {
            'id': container['id'],
            'object_type': 'user',
        })
       
for user in users:
     duser = toolkit.get_action('user_show')(context, {'id': user[0]})
```

**Expected behavior**
`member_list` action must return only active users

**Possible fix**
Add an extra DB query to filter only active users

**Comment by amercader** [comment]
To mimic the behaviour at the Python level introduced in #3078 (mark membership records as deleted when you delete a user via `user_delete`) we need to implement a foreign key with the proper `CASCADE` behaviour between the `user` and `member` tables. 
Additionally we can add an extra check to the SQLAlchemy query in `member_list` that filters member records who don't have a record in the `user` table.
The same fix can probably be applied for datasets

**Comment by chetan-NEC** [comment]
@avdata99, @amercader I'm interested to work on this issue.
