### ISSUE TITLE
Test Python versions supported for each CKAN version

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7261]
We should be confident about the Python versions that each CKAN version supports and be able to test support for new versions easily.
Also have a good test environment to discuss issues like https://github.com/ckan/ckan/pull/6613.

So let's create a monitor repo like the one that @pdelboca created for extensions (https://github.com/ckan/ckan-extensions-monitor) but running the CKAN core tests under different Python versions:

* CKAN 2.9: Python 3.7 to 3.9
* CKAN 2.10: Python 3.7 to 3.10
* [Optional] Master

I know tests will take a long time to run as we won't split them as we do in CircleCI but we should fall well within [GitHub Actions limits](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration) and this are not meant to be constantly monitored.
In the future we can add other combinations like CKAN + Postgres or Solr versions

**Comment by abedkhooli** [comment]
So, does this mean that 2.10 actually works with Python 3.10?

**Comment by pdelboca** [comment]
@abedkhooli yes. CKAN 2.10 should work with Python 3.10.

I will close this ticket since the Python Monitor for CKAN core has been implemented: https://github.com/ckan/ckan-python-monitor
