### ISSUE TITLE
clean_db fixture does not clear tables created by extensions

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#7332]
## CKAN version

2.9, master

## Describe the bug

Adding a table in an extension, either with alembic or with old way of initializing the tables from setup function adds to tests as well, this is all well and good.

Adding 'clean_db' fixture to a test in extension does not clear those tables, below is a log from clearing:

```
INFO     ckan.model:__init__.py:250 deleting from table resource_view
INFO     ckan.model:__init__.py:250 deleting from table package_tag
INFO     ckan.model:__init__.py:250 deleting from table user_following_user
INFO     ckan.model:__init__.py:250 deleting from table user_following_group
INFO     ckan.model:__init__.py:250 deleting from table user_following_dataset
INFO     ckan.model:__init__.py:250 deleting from table tag
INFO     ckan.model:__init__.py:250 deleting from table resource
INFO     ckan.model:__init__.py:250 deleting from table rating
INFO     ckan.model:__init__.py:250 deleting from table package_relationship
INFO     ckan.model:__init__.py:250 deleting from table package_member
INFO     ckan.model:__init__.py:250 deleting from table package_extra
INFO     ckan.model:__init__.py:250 deleting from table member
INFO     ckan.model:__init__.py:250 deleting from table group_extra
INFO     ckan.model:__init__.py:250 deleting from table dashboard
INFO     ckan.model:__init__.py:250 deleting from table api_token
INFO     ckan.model:__init__.py:250 deleting from table activity_detail
INFO     ckan.model:__init__.py:250 deleting from table vocabulary
INFO     ckan.model:__init__.py:250 deleting from table user
INFO     ckan.model:__init__.py:250 deleting from table tracking_summary
INFO     ckan.model:__init__.py:250 deleting from table tracking_raw
INFO     ckan.model:__init__.py:250 deleting from table term_translation
INFO     ckan.model:__init__.py:250 deleting from table task_status
INFO     ckan.model:__init__.py:250 deleting from table system_info
INFO     ckan.model:__init__.py:250 deleting from table package
INFO     ckan.model:__init__.py:250 deleting from table group
INFO     ckan.model:__init__.py:250 deleting from table activity
INFO     ckan.model:__init__.py:253 Database table data deleted 
```

Only core tables are emptied and extensions need to find means to clear their tables themselves.

### Steps to reproduce
Create an extension.
Create a migration where table is added.
Add two tests which both add data to table.
Clean databases with clean_db.

### Expected behavior
As an extension developer, I would assume clean_db to clear the extension tables as well.

**Comment by smotornyuk** [comment]
`clean_db` cleans only tables that are registered in [the `Metadata` object](https://github.com/ckan/ckan/blob/master/ckan/model/meta.py#L87)
I assume you are creating models using a "new" declarative approach, i.e. you are doing something like this:
```python

from sqlalchemy.orm.declarative import declarative_base
Base = declarative_base()

class MyModel(Base):
   id = Column(...)
```

In this case you have to reuse CKAN's metadata when `Base` is created. For example, this should work:
```python
import ckan.model as model
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base(metadata=model.meta.metadata)
```


In CKAN v2.10 we have [a shared `Base` class](https://github.com/ckan/ckan/blob/master/ckan/model/base.py#L15-L17) initialized, so you can reuse it instead of creating your own.

**Comment by Zharktas** [comment]
Yeah this seemed to work coupled with migrate_db_for fixture. these could be documented on https://docs.ckan.org/en/2.9/extensions/best-practices.html#use-migrations-when-introducing-new-models
