### ISSUE TITLE
Create user "one line command" in Command Line Interface(CLI) Doc

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#7343]
## CKAN version
2.9
## Describe the bug
There is no one line command for user create.

### Steps to reproduce
For example, to create a new user called ‘admin’ below command needs to be executed.
`ckan -c /etc/ckan/default/ckan.ini user add admin` after that `email` and `name` to be given as input then user will be created. It would be great to have a one line command for create user.

### Expected behavior
There should be a one line command for user create.

**Comment by Gauravp-NEC** [comment]
If Dev-team agree to have work on this issue. I will submit the PR.

**Comment by Gauravp-NEC** [comment]
Related to https://github.com/ckan/ckan/pull/7301

**Comment by Gauravp-NEC** [comment]
@kowh-ai , What is your opinion on this issue? Should I proceed and submit a PR?

**Comment by kowh-ai** [comment]
Are you trying to **create** a new user or **remove** an existing user? It's a bit hard to tell from your "_Steps to reproduce_" text

**Comment by Gauravp-NEC** [comment]
> Are you trying to **create** a new user or **remove** an existing user? It's a bit hard to tell from your "_Steps to reproduce_" text

@kowh-ai , I am trying to **create** a new user by one line command.

**Comment by kowh-ai** [comment]
@Gauravp-NEC - thanks, please base the PR off https://github.com/ckan/ckan/pull/7301
