### ISSUE TITLE
Add reference of "create user" in Installing CKAN from source

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#7366]
## CKAN version
Master
## Describe the bug
There is no reference of create user in installing CKAN from source doc (https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html). This will help beginner's in creating user.

### Expected behavior
Add step `10. Create  CKAN user` and add note about user create and manage (https://docs.ckan.org/en/latest/maintaining/cli.html#user-create-and-manage-users) 

### Additional details
Installing CKAN with Docker Compose already have create user information here: https://docs.ckan.org/en/latest/maintaining/installing/install-from-docker-compose.html#create-ckan-admin-user similarly Installing CKAN from source doc should have reference about creating a user.

**Comment by Gauravp-NEC** [comment]
If Dev-team agree to have work on this issue. I will submit the PR.

**Comment by Gauravp-NEC** [comment]
maybe related to https://github.com/ckan/ckan/issues/6704

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Please assigned this issue to me. Thanks:)

**Comment by kowh-ai** [comment]
no need to assign to you. Please just create the associated PR.

**Comment by Gauravp-NEC** [comment]
> no need to assign to you. Please just create the associated PR.

@kowh-ai , I have raise the PR https://github.com/ckan/ckan/pull/7377, waiting for your review.
