### ISSUE TITLE
`build_nav_icon` Helper on Resource Edit and Views

### ISSUE THREAD

**Issue by JVickery-TBS** [ckan/ckan#7372]
## CKAN version
master branch (latest)
AND 2.9.7

## Describe the bug
The `build_nav_icon` helper does not set the active class for the urls of `<package_type>/<id>/resource/<resource_id>/edit` and `<package_type>/<id>/resource/<resource_id>/views`

### Steps to reproduce
* Navigate to a url such as `/dataset/<id>/resource/<resource_id>/edit`

### Expected behavior
The "Edit Resource" and "Views" tab/nav_icon links should be visually active with the active class.

### Additional details
![Edit Resource Tab](https://user-images.githubusercontent.com/97247789/216089875-0df2ab6a-fcc6-4ed4-b644-e0aa419af6f6.png)

**Comment by JVickery-TBS** [comment]
Looks like the helper calls `blueprint, endpoint = p.toolkit.get_endpoint()` which returns `resource, edit`. But then the matching controller and action is `dataset_resource, edit`.

So the `get_endpoint` function (which just uses the `ckan.common.request,endpoint`), is resolving the request endpoint to the non-prefixed resource routes, instead of the prefixed resource routes. E.g. it is resolving to `resource.edit` and not `<package_type>_resource.edit`.

Same thing with the views.

**Comment by JVickery-TBS** [comment]
Created PR with suggested changes: https://github.com/ckan/ckan/pull/7373

**Comment by JVickery-TBS** [comment]
@smotornyuk if that other PR suggestion is too big, and the `resource` blueprint needs to stay in: I have made this PR with a small addition to the helper functions https://github.com/ckan/ckan/pull/7379

It just adds `highlight_blueprint_endpoints` option much like the `highlight_controllers` option.

**Comment by smotornyuk** [comment]
I like #7373, but removing blueprint may break extensions, so let's change it a bit. I'll add a couple of comments there
