### ISSUE TITLE
2.10.0 - Link to CKAN-API in footer points to 404

### ISSUE THREAD

**Issue by tgurr** [ckan/ckan#7411]
## CKAN version
2.10.0

## Describe the bug
CKAN-API link in the footer points to 404 site: http://docs.ckan.org/en/2.1/api/
![ckan_api_404](https://user-images.githubusercontent.com/414984/220368786-68cac0db-552c-4265-b65a-9f4e73cfd8c3.png)

### Steps to reproduce
See/Click the CKAN-API link in the footer.

### Expected behavior
Landing on a working site with details about the CKAN-API, probably: https://docs.ckan.org/en/2.10/api/

### Additional details
*

**Comment by Mikanebu** [comment]
@amercader Could you please review PR  https://github.com/ckan/ckan/pull/7420 for this issue?
