### ISSUE TITLE
Upgrading-postgres is not updated for CKAN 2.9 release.

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#7442]
## CKAN version
2.9
## Describe the bug
Upgrading-postgres for the CKAN 2.9 release is not updated (https://docs.ckan.org/en/2.9/maintaining/upgrading/upgrade-postgres.html#upgrading). It is still for the older version CKAN 2.6.

### Steps to reproduce
Visit: https://docs.ckan.org/en/2.9/maintaining/upgrading/upgrade-postgres.html

### Expected behavior
Upgrading-postgres must be updated for CKAN 2.9 release.

### Additional details
Also PR https://github.com/ckan/ckan/pull/5567 seems to be missing

**Comment by Gauravp-NEC** [comment]
If Dev-team agree to have work on this issue. I will submit the PR.

**Comment by Gauravp-NEC** [comment]
@amercader, please let me know your opinion on this issue.

**Comment by amercader** [comment]
@Gauravp-NEC See https://github.com/ckan/ckan/issues/7443#issuecomment-1469742409
