### ISSUE TITLE
No upgrade-postgres doc for CKAN 2.10 release.

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#7443]
## CKAN version
master, 2.10
## Describe the bug
There is no upgrade-postgres document for CKAN 2.10 release.

### Steps to reproduce
Visit:https://docs.ckan.org/en/2.10/maintaining/upgrading/upgrade-postgres.html
### Expected behavior
There should be upgrade-postgres  document for CKAN 2.10 release.

**Comment by Gauravp-NEC** [comment]
If Dev-team agree to have work on this issue. I will submit the PR.

**Comment by amercader** [comment]
The "Upgrading Postgres" page was really outdated, and it really it is out of scope for the CKAN documentation, so we decided to drop it. We'll do the same on the 2.9 docs
