### ISSUE TITLE
Activity stream does not appear in dashboard

### ISSUE THREAD

**Issue by madelinekosse** [ckan/ckan#7517]
## CKAN version
2.10.0

## Describe the bug
Nothing appears on the "news feed" tab of the dashboard page when activity plugin is enabled, though the feed is visible on other pages and activity notifications are working.

### Steps to reproduce

1. With the activity plugin enabled, log into an account and follow a dataset. 
2. Log in as the dataset owner and modify the dataset to ensure there is some activity present, and confirm this is the case by selecting the "activity feed" tab on the dataset page. 
3. When logged in as the user who followed the dataset, navigate to the dashboard page and select the "news feed" tab. You will see that it is empty, as shown in the screenshot.

### Expected behavior
The activity feed for the followed dataset should appear on the news feed tab. I expect it to look similar to the feed you see on the dataset page, just as we saw in version 2.9.7 when the activity plugin was included in the base installation.

### Additional details

This is what I see on the news feed page, whether logged in as the user who follows the changed dataset or the administrator:
![image](https://user-images.githubusercontent.com/20282373/229565805-3e986711-902e-42a7-9120-543d42a1cfa4.png)

The activity feed is certainly present, as I can see it on the dataset page, regardless of who I am logged in as.

When the administrator updates a dataset, the notification bubble appears on the dashboard icon for users who follow the dataset, but goes away when the (empty) dashboard is viewed. When email notifications are enabled, and the user has not viewed the dashboard page since the dataset was changed, the email is also sent as expected.

Calling `ckan.logic.action.get.dashboard_activity_list` from another extension returns the activity feed as expected. When the user views the empty news feed page, the `is_new` field of the items return is set to `False`.

**Comment by smotornyuk** [comment]
Fixed by #7482
