### ISSUE TITLE
CKAN 2.11 release

### ISSUE THREAD

**Issue by pdelboca** [ckan/ckan#7542]
As discussed in the Tech Meeting today, we will slowly start with the release of CKAN 2.11. Our goal as a community is to improve the process to have a more frequent release cycle.

This release will be lead by me as an opportunity to review our process, suggest improvements, update documentation and give our beloved @amercader some holidays 🏖️ 🍸 🏊🏼 .

Of course, the whole @ckan/core team members will support and help in the process.

# CKAN 2.11

The huge motivation around CKAN 2.11 it to have an official release with the latest versions of our core dependencies (Flask, Werkzeug, Jinja, etc). This will allow us to quickly create a Patch Release with security fixes when they are fixed upstream. Running CKAN on latest versions of all it's dependencies should start being the norm and for that, we need to have a new release.

# First steps

## Core
- [X] Create this ticket using previous release as a template
- [X] Create `Backport 2.11.0` label
- [x] Review with @ckan/core all tickets/PR that **must** be finished and add them to the milestone: https://github.com/ckan/ckan/milestone/15
- [x] Create the `dev-v2.11` branch and change the version number on this branch to `2.11.0b`. From that moment on, everything that needs to go into the release needs to be merged first to master
- [x] Update version on `master` to `2.12.0a0` (we can always change it to `3.0.0a0`later)
- [ ] Update beta.ckan.org to run using `dev-v2.11`, ideally updated daily
- [x] Extract translations and push a new `2.11` resource to Transifex. Full instructions on point 5 [here](https://docs.ckan.org/en/2.9/contributing/release-process.html#doing-the-beta-release)
- [x] Create `dev-v2.11` images (base + dev) and upload to: https://github.com/ckan/ckan-docker-base
- [x] Update the CKAN Dockerfiles to use `dev-v2.11` in the https://github.com/ckan/ckan-docker repo
- [x] Announce on the mailing list the start of the release process. From this moment on, anything that needs to go into 2.11 needs to be first merged to master and then cherry-picked to 2.11 (use the [Backport dev-v2.11](https://github.com/ckan/ckan/labels/Backport%20dev-v2.11) label to mark the relevant PRs)
- [x] Finish pending issues / PRs (https://github.com/ckan/ckan/milestone/15), basically:
    - [x] ... (add if necessary)
- [x] Announce end of life of CKAN 2.9 once  2.11 is out.

## Extensions

- [x] Set up the `ckan/ckan-dev:2.11` Docker image to be automatically built from `dev-v2.11` 
- [x] Re-test extensions using https://github.com/ckan/ckan-extensions-monitor as a guideline
- [x] Announce end of life of CKAN 2.9 once  2.11 is out.

# Following weeks: Stabilization

The following steps will likely be need to be repeated as we put more changes on the release branch. The idea is to keep it as usable and up to date as possible for testers:

- [x] Create the documentation branch from the release branch (`dev-v2.11`). This branch should be named `2.11` and should be kept up to date
- [x] Build CSS (`ckan sass`)
- [x] Update changelog in `dev-v2.11`. Run towncrier command plus manually add anything missing.
- [x] Test fixes for cherry-picked issues locally and on beta.ckan.org
- [x] Test that Debian package builds fine
- [x] Call for testing: blog post, mailing list and twitter
- [x] Call for translations

# Feature and translation freeze

A couple of weeks before the release date the release branch is frozen, no more merges except for fixes. We follow the standard [release process](http://docs.ckan.org/en/latest/contributing/release-process.html):

* [x] Pull translations
* [x] Rebuild CSS
* [x] Changelog

# Release day

* [x] Change version and tag 
* [x] Build and upload packages
* [x] Build and upload Docker images
* [x] Update docs (RTD)
* [x] Create a GitHub Release 
* [x] PyPI
* [x] Announce
* [x] Post-release actions:
    * [x] Cherry-pick i18n changes from latest version to master
    * [x] Cherry-pick changelog entries for all new versions to master
    * [x] Update versions in `dev-v*` branches to the next version, including `b0`
    * [x] Update the Github labels to tag Backports to the next patch release number
- [x] :beers: :tropical_drink:

**Comment by amercader** [comment]
@anuveyatsu could you coordinate on your end to get https://beta.ckan.org running of the `dev-v2.11` branch? And ideally bump demo.ckan.org, which is still on 2.9. Many thanks!

**Comment by amercader** [comment]
CKAN 2.11.0 and 2.10.5 we released on August 21st 2024
