### ISSUE TITLE
CKAN bulk_update_delete not reflecting changes in frontend

### ISSUE THREAD

**Issue by jamxiao2025** [ckan/ckan#7548]
### Steps to reproduce
data_dict = {
            "id": f"{id}",
            "organization_id": f"{ORGANIZATION_ID}"
        }
url = 'http://your-site/api/3/action/bulk_update_delete'
response = requests.post(url, data=data_dict, headers=HEADERS)
        response_dict = response.json()
        json_pretty = json.dumps(response_dict, indent=2)
        print(json_pretty)
### Expected behavior
There should be a dictionary returned as such(which I receive):
{
  "help": "http://your-site/api/3/action/help_show?name=dataset_purge",
  "success": true,
  "result": null
}
and when I view the site the packages should not appear on the frontend.

### Additional details
There was a previous issue opened on a similar topic and a user said that it was fixed, but it seems to not be working again.

**Comment by smotornyuk** [comment]
Check the documentation of [bulk_udate_delete](https://docs.ckan.org/en/2.9/api/index.html#ckan.logic.action.update.bulk_update_delete). You are calling it with parameters that have no sense for this action:
* there is no param `id`. Use `datasets` instead. And pay attention to its type
* there is no param `organization_id`. Use `org_id` instead
