### ISSUE TITLE
CKAN resource_create API

### ISSUE THREAD

**Issue by batey870** [ckan/ckan#7567]
## CKAN version
2.10 (via Docker compose - https://github.com/ckan/ckan-docker )

## Environment
Windows 10 + Docker Desktop v4.18.0

## Describe the bug
We are trying to create/add resource to an existing Dataset using the following Java Code:

	public void createResourceXYZ() {
		try (CloseableHttpClient httpClient = HttpClientBuilder.create().build()) {
			String CkanAPI = "https://localhost:8443/api/action/resource_create";
			HttpPost httpPostRequest = new HttpPost(CkanAPI);
			String authorizationToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1REkzVXBFbEVrMDNCWXBqb1pqaXlkcmFDMHB6LXA3Uk5fYW9abDYxN0YwIiwiaWF0IjoxNjgzMDEzNjI3fQ.erz3aSe6xAdeDQQk8gPpQVgdSN6uKFFC4vkzAiZXfrA";
			httpPostRequest.setHeader("Authorization", authorizationToken);
			String packageId = "4c4bbf87-a9b4-4d4d-9575-efe8d6ccbea1";
			String filePath = "C:/Temp/AAA_20220421_REGSIC/NeTEx_RS1.xml";
			HttpEntity mpEntity = MultipartEntityBuilder.create().addBinaryBody("upload", new FileInputStream(filePath))
				.addTextBody("package_id", packageId)
				.addTextBody("name", "NeTEx Statico2")
				.addTextBody("format", "XML")
				.addTextBody("url_type", "upload")
				.addTextBody("mimetype", "text/xml")
				.addTextBody("url", "netex_rs1.xml")
				.addTextBody("descritpion", "Dati statici in formato NeTEx").build();
			httpPostRequest.setEntity(mpEntity);
			HttpResponse response = httpClient.execute(httpPostRequest);
			if (response.getStatusLine().getStatusCode() < 200 ||   response.getStatusLine().getStatusCode() >= 300) {
				throw new RuntimeException("failed to add the file to CKAN storage. response status line from "
						+ CkanAPI + " was: " + response.getStatusLine());
			}
			HttpEntity responseEntity = response.getEntity();
			System.out.println(responseEntity.toString());
			System.out.println("STATUS CODE: " + response.getStatusLine().getStatusCode());
		} catch (IOException e) {
			// log error
			
		}
	}	
The resource is added correctly but when we try to push “dowload” button (or click URL link), we get an “Internal Server Error”. 

### Steps to reproduce
Create a datasource and then create/add a resource using java code or curl command.

### Expected behavior
The resource is addedd correctly and we are able to download it using the download button or URL Link.

### Additional details
We registered the same behaviour using the following curl command on CKAN:

curl -H'Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1REkzVXBFbEVrMDNCWXBqb1pqaXlkcmFDMHB6LXA3Uk5fYW9abDYxN0YwIiwiaWF0IjoxNjgzMDEzNjI3fQ.erz3aSe6xAdeDQQk8gPpQVgdSN6uKFFC4vkzAiZXfrA' 'http://0.0.0.0:5000/api/action/resource_create' --form upload=/tmp/tmp2/NeTEx.RS1.xml --form package_id=4c4bbf87-a9b4-4d4d-9575-efe8d6ccbea1 --form resource_type=upload --form url_type=upload --form name= NeTEx Statico2 --form url=netex_rs1.xml --form mimetype=text/xml --form format=XML
The resource is added but we are not able to dwonload it (same internal server error).
We have noticed that if we try to add a resource from the web interface the system create some folders under /var/lib/ckan/resources. For istance if the resource ID is:

059e1e39-ae22-44f3-a52d-040791d1d8a9

the system creates the following folders:

/059/e1e/39-ae22-44f3-a52d-040791d1d8a9

This is not true using curl of Java Code.

**Comment by pdelboca** [comment]
Hello @batey870 ! Can you provide the traceback of the error?

**Comment by batey870** [comment]
Hello Patricio,
thanks for your help.
This is the traceback when we try to download resource:

2023-05-02 09:32:37,720 ERROR [ckan.config.middleware.flask_app] [Errno 2] No such file or directory: '/var/lib/ckan/resources/e28/dd0/36-f761-4938-be8a-58969d74d6d8'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/app/src/ckan/ckan/config/middleware/../../views/resource.py", line 174, in download
    resp = flask.send_file(filepath, download_name=filename)
  File "/usr/lib/python3.10/site-packages/flask/helpers.py", line 612, in send_file
    return werkzeug.utils.send_file(
  File "/usr/lib/python3.10/site-packages/werkzeug/utils.py", line 701, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/ckan/resources/e28/dd0/36-f761-4938-be8a-58969d74d6d8'
2023-05-02 09:32:37,761 INFO  [ckan.config.middleware.flask_app]  500 /dataset/4c4bbf87-a9b4-4d4d-9575-efe8d6ccbea1/resource/e28dd036-f761-4938-be8a-58969d74d6d8/download/netex_rs1.xml render time 0.099 seconds

**Comment by pdelboca** [comment]
CKAN is intended to be run in Linux, not in Windows. So it might be related to that?

`/var/lib/ckan/...` doesn't seems like a valid Windows path? What's your configuration file?

I would suggest you to debug what's going on when CKAN is trying to store the file. Is a file actually being created? Can you navigate to it using your filesystem?

**Comment by batey870** [comment]
CKAN is istalled on Linux Docker image (on window using Docker Desktop): I'm using the one suggested by CKAN docs (https://github.com/ckan/ckan-docker). 
I'm able to access to the web interface using, from windows, https://localhost:8443. I'm also able to call CKAN API using, for instance:
https://localhost:8443/it/api/action/package_list
or
https://localhost:8443/it/api/action/group_list

all works correctly. Also https://localhost:8443/it/api/action/resource_create works correctly but the problem seems related to the resource upload (in my case the .XML file but I've tried also vith CSV).

/var/lib/ckan/... is not a windows folder: it is the folder, on CKAN Linux image, where the system saves resources.

About your question: Is a file actually being created?
No, it is not and this is the problem but I don't know why.

The file is created only if I create/add the resource from web interface but not if I try to create/add resource from Java code or Curl.

**Comment by wardi** [comment]
@batey870 try not setting the `url` parameter when you're passing an `upload` value. `url` is used for resources that are linked, not uploaded.

**Comment by batey870** [comment]
Hi wardi, thanks for your help.
I've tried to eliminate the url param but now there is no way to download the resource (there is no a download button).

![Immagine 2023-05-02 150750](https://user-images.githubusercontent.com/43578861/235675195-45bd56fa-ae0b-4a48-8a85-d10fe1b81003.png)

**Comment by wardi** [comment]
It's possible that the filename is expected in the upload parameter. Your curl example doesn't seem to be uploading the file itself, just passing the path. Try curl again with `upload=@/tmp/tmp2/NeTEx.RS1.xml` and don't pass the url parameter.

Requiring a file name as part of the upload parameter isn't documented, and shouldn't lead to a server error, so it would be nice to have this issue fixed.

**Comment by wardi** [comment]
What's missing is the filename that curl and web browsers include along with the `form/multipart` data. I'm not sure how to add the name with MultipartEntityBuilder, but I expect there should be an optional parameter in there somewhere.

an example from stackoverflow:
```
...
Content-Type: multipart/form-data; boundary=---------------------------9051914041544843365972754266
Content-Length: 554

-----------------------------9051914041544843365972754266
Content-Disposition: form-data; name="text"

text default
-----------------------------9051914041544843365972754266
Content-Disposition: form-data; name="file1"; filename="a.txt"
Content-Type: text/plain

Content of a.txt.

-----------------------------9051914041544843365972754266
```

The "text" parameter has is a plain text field and the "file1" parameter is a file upload including a `filename="a.txt"`. That's what ckan is expecting for the upload parameter

**Comment by batey870** [comment]
Hi wardi, thank you.
I'll do some checks
