### ISSUE TITLE
IAuthFunction override no longer prevents anonymous access

### ISSUE THREAD

**Issue by jannettim** [ckan/ckan#7572]
## CKAN version
2.10.0

## Describe the bug
Overriding the package_show IAuthFunction no longer prevents anonymous users from accessing the data as it did in 2.9

### Steps to reproduce
1. Create an extension
2. Create a new `package_show` method that should return success: False for anonymous users (see code example below)
```python
def package_show(context, data_dict):

    if context.get("auth_user_obj") is not None:
        return {"success": True}

    return {"success": False, "msg": "You must be signed in to view this page"}

class PluginClass(p.SingletonPlugin, tk.DefaultDatasetForm, DefaultTranslation):
    p.implements(p.IDatasetForm)
    p.implements(p.IConfigurer)
    p.implements(p.ITemplateHelpers)
    p.implements(p.IAuthFunctions)
    p.implements(p.IPackageController, inherit=True)
    p.implements(p.ITranslation)
	
    def get_auth_functions(self):

        return {"package_show": package_show}
```
3. Install plugin
4. Go to a package page

### Expected behavior
The page should not be able to load; however, anonymous users should still be able to search for datasets and see the titles/descriptions of the datasets (see screenshots below)

### Additional details
Here is an example of how it works the 2.9.3 version of site that is currently live and what we would like to happen on the upcoming 2.10.0 version of the site.

The /dataset search page appears like this:

![image](https://user-images.githubusercontent.com/16616130/235754158-44d6fc75-959e-470f-953c-76f8cf3773f0.png)

But when an anonymous user attempts to click on any of the links, instead of being able to see all of the package metadata and download links they are thrown an error message like this:

![image](https://user-images.githubusercontent.com/16616130/235753433-ca09b467-a7c0-4444-b88b-8bddfb303d94.png)

The goal of this is to allow people to be able to see what datasets we have (I do not believe we particularly need to hide package metadata but would like them to at least see a title and a short description) but require people to register to be able to access the resources and download the data.

**Comment by jannettim** [comment]
A suggestion from @JVickery-TBS solved this issue for me. The problem was that the when a user is anonymous, the context["auth_user_obj"] was returning an AnonymousUser object and not None, so my conditional was unexpectedly returning true and providing access. I updated my code like this:

```python
# not sure if there's a better way to import this from the plugin toolkit
from ckan.model.user import AnonymousUser

def package_show(context, data_dict):

    if not isinstance(context["auth_user_obj"], AnonymousUser):
        return {"success": True}

    return {"success": False, "msg": "You must be signed in to view this page"}
```

As a result, the request redirects to the login page and back to the package after a successful authentication (which I think is better than what currently happens in 2.9.3 as depicted above).

But the CKAN 2.10 documentation may contain an error about this. In [this section](https://docs.ckan.org/en/2.10/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IAuthFunctions.get_auth_functions) of the CKAN documentation, it still says "an auth_user_obj containing the actual model.User object (or None if it is an anonymous request)." That might no longer be true (or no longer always be true).

**Comment by smotornyuk** [comment]
Yes, it's no longer true, and currently recommended strategy(for v2.10 and newer) is to use `context['user']` which is set to username of the current user or empty string(`''`) if user is anonymous. Such check looks more readable:

```python
if context["user"]:
   return {"success": True}

return {"success": False}
```

Or you can use [auth_is_anon_user](auth_is_anon_user), which hides implementation and will be updated in the future if something else changes in `context`:

```python
from ckan.authz import auth_is_anon_user:

if auth_is_anon_user(context):
   return {"success": False}

return {"success": True}
```
