### ISSUE TITLE
Edit navigation in fewer clicks

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#7586]
Example: I'm at a dataset page and I want to edit the data dictionary for resource number 2.

Option 1:
- click "manage" (page refresh)
- click resources tab (page refresh)
- click on resource number 2 (page refresh)
- click data dictionary tab (page refresh)

Option 2:
- click "Explore" drop-down next to resource 2
- click "more information" (page refresh)
- click "manage" (page refresh)
- click data dictionary tab (page refresh)

There are some shortcuts, e.g. we can click the text of the resource name on the dataset page to save one click.

I'd like to be able to navigate to resource editing features in 1/2 clicks instead of 3/4 clicks and page refreshes.

### Proposed solution:

Dataset Page:
- [X] add "Manage", "Data Dictionary" and "Views" buttons to the "Explore" drop-down.

Resource Page:
- [X] add "Data Dictionary" and "Views" buttons next to "Manage"
- [X] add "Manage", "Data Dictionary" and "Views" drop-down for the other resources on the sidebar

Dataset Edit Page:
- [x] in sidebar add resource list + edit drop-downs like on resource page

Dataset Edit Resources Tab:
- [x] rename to "Reorder resources"
- [x] in sidebar add resource list + edit drop-downs like on resource page

Resource Edit/Data Dictionary/Views Pages:
- [x] in sidebar add resource list + edit buttons like on resource page

**Comment by ThrawnCA** [comment]
I like the faster access to "Add new resource". However, the eventual solution used for this has a problematic look and feel.

- Datasets still have a "Manage" button, but resources now have an "Edit resource" button - even though they are basically doing the same job as each other, plus "Edit resource" is doing the same job that "Manage" used to do. Furthermore, the resource button takes you to a list of tabs for managing the resource in various ways, of which only one is specifically labelled "Edit resource". It would be more consistent and make more sense for the button to still be labelled "Manage". Why was it renamed?

- The dataset "Manage" button is at the right end of the buttons, and the previous resource "Manage" button was the same, but the "Edit resource" button was moved to the left. Why?

- Although the "Add new resource" button is now available on more pages, it is also smaller and less conspicuous, with simple black text on a white background, which isn't great for such an important action. It is also on the opposite side of the page from the "Manage" button (which was probably clicked immediately beforehand), making it even less obvious. Moreover, the sidebar now appears to be the _only_ way to access the button - which isn't how a sidebar should work. It should just be a shortcut to a function that is available in other ways. Can the previous "Add new resource" button be restored, to have the best of both?

**Comment by wardi** [comment]
* :+1: to restoring the "Manage" button text for resources and moving the edit button back to the right.
* IIUC the for A11y we shouldn't have two buttons on the same page that go to the same place. We *could* add an "Add new resource" button to the dataset page below the list of resources for users that have the right permissions, WDYT?

This is a pretty old ticket and the latest UI discussions are
https://github.com/ckan/ckan/discussions/8188 I believe. Let's suggest these changes there too (ideally with screenshots) to get feedback from the people working on the new theme, then we can review/work on PRs that address both at the same time.

**Comment by wardi** [comment]
@ThrawnCA now I remember: the resource Edit button was moved to the left to match the button order to the tabs that appear when managing the resource.

**Comment by ThrawnCA** [comment]
> [@ThrawnCA](https://github.com/ThrawnCA) now I remember: the resource Edit button was moved to the left to match the button order to the tabs that appear when managing the resource.

That makes some sense if the button is renamed. But I don't think it _should_ be renamed, since it's taking the user to all the resource management tabs, not just the Edit tab - in which case, it's better for it to be consistent with the dataset Manage button.

> (ideally with screenshots)

That's complicated by having a custom theme, but we could arrange something if you have specific suggestions of what screenshots would be helpful.

**Comment by ThrawnCA** [comment]
One of our product managers has pointed out that the sidebar "Add new resource" button now appears even if you're already on the Add Resource page, which seems redundant and potentially confusing.

**Comment by wardi** [comment]
@ThrawnCA that's a bug for sure, do you mind creating an issue?
