### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/var/lib/ckan/default'

### ISSUE THREAD

**Issue by aggelospincha** [ckan/ckan#7594]
PermissionError: [Errno 13] Permission denied: '/var/lib/ckan/default'
Ckan 2.10 from source using solr manually

**Comment by kowh-ai** [comment]
Yes, common problem. You'll need to open the permissions (to world read) of the `/var/lib/ckan/` directory or change ownership to the user running the CKAN process(es)

**Comment by hongjie123** [comment]
Hello, when I accessed through "http://server IP: 5000", I also encountered the same problem: "PermissionError: [Errno 13] Permission denied: '/var/lib/ckan'", as shown in the following figure:
![image](https://github.com/ckan/ckan/assets/54384385/9e8a283b-aead-4b94-87c8-c97d9bae3e5f)
![image](https://github.com/ckan/ckan/assets/54384385/77b010c3-bd1b-49c6-a453-15fc309affd1)

But I didn't find the directory '/var/lib/ckan' on the server, why? May I ask how to solve this situation?
![image](https://github.com/ckan/ckan/assets/54384385/dc724e77-17d8-4379-881d-85689d879fc8)

**Comment by aggelospincha** [comment]
Hi ,
Ok maybe try to create this folder and give it all the permissions?

Στις Τετ 11 Οκτ 2023 στις 06:33 ο χρήστης 邓鸿杰 ***@***.***>
έγραψε:
