### ISSUE TITLE
Ckan_doc_version is incorrect

### ISSUE THREAD

**Issue by C0d9Hunter** [ckan/ckan#7626]
## CKAN version
2.10.0
## Describe the bug
The ckan version (ckan_doc_version) returns the value 2.1 instead of 2.10. This means that all links to the ckan site are incorrect. 

### Additional details
I think this is due to the fact that the value has been badly truncated. I suggest : 
`self.ckan_doc_version = self.ckan_version[:4]` instead `self.ckan_doc_version = self.ckan_version[:3]` in __init__ function in app_globals.py

**Comment by Vishal-NEC** [comment]
Hi @C0d9Hunter I think this issue is resolved in latest version.
Is we need to do anything in this or we can close this issue?

**Comment by mike-cochrane** [comment]
Hi @C0d9Hunter 

This still seems to be a problem on 2.10.1
