### ISSUE TITLE
Footer link to API docs broken

### ISSUE THREAD

**Issue by BonaBeavis** [ckan/ckan#7702]
## CKAN version

2.10.1

## Describe the bug

Footer links to https://docs.ckan.org/en/2.1/api/ instead of https://docs.ckan.org/en/2.10/api/

### Additional details

Guess there was an assumption that the decimals will always be single digit.

**Comment by kowh-ai** [comment]
Issue mentioned [here](https://github.com/ckan/ckan/pull/7424) too
