### ISSUE TITLE
Redirect to login if not authorized config not working

### ISSUE THREAD

**Issue by sagargg** [ckan/ckan#7707]
## CKAN version
CKAN v2.10.1
## Describe the bug
 The` ckan.redirect_to_login_if_not_authorized` configuration option in CKAN is not functioning as expected. This configuration setting is intended to redirect users to the login page when users are not logged in. 
 
 https://docs.ckan.org/en/2.10/maintaining/configuration.html#ckan-redirect-to-login-if-not-authorized

**Comment by smotornyuk** [comment]
This feature was removed after a discussion in #6987. Config option `ckan.redirect_to_login_if_not_authorized` was overlooked and must be removed as well.

**Comment by Pradyumn-NEC** [comment]
Hi @smotornyuk, I am interested to work in this issue. As per my understanding we need to remove  `ckan.redirect_to_login_if_not_authorized` from https://docs.ckan.org/en/2.10/maintaining/configuration.html#ckan-redirect-to-login-if-not-authorized. Kindly confirm my understanding.

**Comment by smotornyuk** [comment]
@Pradyumn-NEC, yes, exactly. Thank you for the interest:)

**Comment by Pradyumn-NEC** [comment]
@smotornyuk , Thanks for the confirmation. I will submit a PR.
