### ISSUE TITLE
CKAN 2.10 Bootstrap 3 template config not working with datastore and datapusher extensions

### ISSUE THREAD

**Issue by markstuart** [ckan/ckan#7710]
## Describe the bug
In the [Changelog for 2.10.0](https://docs.ckan.org/en/2.10/changelog.html#v-2-10-0-2023-02-15) it states you can use the bootstrap 3 templates via:
```
ckan.base_public_folder=public-bs3
ckan.base_templates_folder=templates-bs3
```

However, this config makes the template search path assume that there are template overrides for the datastore and datapusher extensions (bundled into CKAN core) at these locations:
```
/ckanext/datastore/templates-bs3
/ckanext/datapusher/templates-bs3
```
These folder don't exist, so the template overrides don't get applied for those extensions if you have them in your `ckan.plugins` list.

### Steps to reproduce
In a CKAN 2.10.x site with datastore and datapusher enabled, create a dataset with a csv resource that will get pushed to the datastore. When you view the resource, the Data Dictionary is not displayed (from the "block resource_data_dictionary" in /ckanext/datastore/templates/package/resource_read.html).

If you copy the templates folder to templates-bs3 (cp -r /ckanext/datastore/templates /ckanext/datastore/templates-bs3) then the Data Dictionary is displayed.

### Expected behavior
Either the ckan.base_templates_folder config should only affect the template resolution for /ckan/templates, or the bundled extensions would have the templates folders copied as part of the Bootstrap 5 work.

**Comment by Zharktas** [comment]
If the current templates do not need any migration for bootstrap 3 and 5 compatibility, the configuration logic in https://github.com/ckan/ckan/blob/9956f92925740957b119bd7c6719ee202eb51082/ckanext/datapusher/plugin.py#L38 and https://github.com/ckan/ckan/blob/9956f92925740957b119bd7c6719ee202eb51082/ckanext/datastore/plugin.py#L80 should be removed.
