### ISSUE TITLE
Default to strict config mode in 2.11- config options

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7711]
As discussed in https://github.com/ckan/ckan/pull/7450#issuecomment-1597310416 we want default to `strict` mode for configuration options starting from CKAN 2.11. The code changes are easy enough, but I want to check what is the preferred way to handle it via config options.

In CKAN 2.10:

| `config.mode` | Behaviour |
| ------------------ | --- |
| Not set | Invalid values are left unprocessed |
| `default` | Invalid values are left unprocessed |
| `strict` | CKAN does not start unless all options are valid |

For CKAN 2.11:

**Option 1**

Just change the internal default. Leave the config options as they are. I'm very -1 on this one because `default` doesn't actually mean default.

| `config.mode` | Behaviour |
| ------------------ | --- |
| Not set | CKAN does not start unless all options are valid |
| `default` | Invalid values are left unprocessed |
| `strict` | CKAN does not start unless all options are valid |

**Option 2**

New `legacy` option to support the traditional behaviour (what was `default` in 2.10)

_Option 2a_

| `config.mode` | Behaviour |
| ------------------ | --- |
| Not set | CKAN does not start unless all options are valid |
| `default` | CKAN does not start unless all options are valid |
| `strict` | CKAN does not start unless all options are valid |
| `legacy` | Invalid values are left unprocessed  |

_Option 2b_

| `config.mode` | Behaviour |
| ------------------ | --- |
| Not set | CKAN does not start unless all options are valid |
| `default` | CKAN does not start unless all options are valid |
| `legacy` | Invalid values are left unprocessed  |

_Option 2c_

| `config.mode` | Behaviour |
| ------------------ | --- |
| Not set | CKAN does not start unless all options are valid |
| `strict` | CKAN does not start unless all options are valid |
| `legacy` | Invalid values are left unprocessed  |

**Option 3**

Drop the traditional behaviour entirely, deprecate and ignore the contents of `config.mode` and always assume `strict`

Any other options?
What are your preferences? @ckan/core

**Comment by wardi** [comment]
:three:

**Comment by smotornyuk** [comment]
3
