### ISSUE TITLE
Datastore test fails on master branch

### ISSUE THREAD

**Issue by smotornyuk** [ckan/ckan#7714]
CircleCI reports [broken test](https://app.circleci.com/pipelines/github/ckan/ckan/5635/workflows/96e733f8-224d-42be-9331-59aa90ead84c/jobs/13645/tests)

I did a small investigation. We have the following scenario:

1. Test [creates a view(alias)](https://github.com/ckan/ckan/blob/master/ckanext/datastore/tests/test_create.py#L644) for a resource that has **two columns**
2. [Later](https://github.com/ckan/ckan/blob/master/ckanext/datastore/tests/test_create.py#L662) test makes an attempt to create an alias(view) for the same resource
3. During the second attempt, the resource's table in datastore [altered](https://github.com/ckan/ckan/blob/master/ckanext/datastore/backend/postgres.py#L2023). Old columns get deleted.
4. At this moment PostgreSQL throws an error: column cannot be removed from table because it's still referred from the view(alias).

If we add `CASCADE` to [the drop-column statement](https://github.com/ckan/ckan/blob/master/ckanext/datastore/backend/postgres.py#L1100), the view that blocks us will be removed as well and it solves the current problem. But it introduces two new problems:
1. When you call `datastore_create` trying to create existing alias, it behaves differently, depending on the payload: 
  * if you are **not** removing any old field(fields are unchanged, or new fields are added) - you'll get 409 because alias already exists
  * if you are removing at least one field that was there when the alias was created, the alias gets dropped and successfully created later 
2. When you call `datastore_create` without an `alias` parameter, the old alias is kept if no columns are removed from the datastore. But it gets dropped if at least one column is removed from the datastore table.

PS it's strange, but there were no such problem when [PR](https://github.com/ckan/ckan/pull/7625) was merged.

**Comment by wardi** [comment]
Was also wondering why it didn't come up in #7625 . Could some of the tests not be running?

Since aliases that `datastore_create` creates never modify the columns the best fix might be to drop and recreate all aliases any time columns are changed.

**Comment by wardi** [comment]
fixed by #7749 

turns out this was not due to #7625 after all
