### ISSUE TITLE
user's email is not unique

### ISSUE THREAD

**Issue by FuhuXia** [ckan/ckan#7723]
## CKAN version
2.10.1

## Describe the bug
User's email field is case-sensitive, therefore user with one email address can be added multiple times. 

### Steps to reproduce
```
ckan user add user1 email=abc@local password=12345678
ckan user add user2 email=ABC@local password=12345678
```

### Expected behavior
second command should fail with message about email already exists.

**Comment by amercader** [comment]
The consensus on the dev meeting was that while we don't want to open the can of worms of fully checking what constitutes a unique email address according to the specs, this particular case (case-sensitiveness) is probably what most users will expect. We suggest not changing whatever the user inputs when storing the email, but making the comparison in the validator that checks for email uniqueness case-insensitive (eg `lower(input) != lower(emails_in_db)`). Tests covering this are required.

**Comment by Gauravp-NEC** [comment]
@amercader, I have investigated on this issue. I found that code changes is required in  `email_is_unique` method of https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/logic/validators.py#L1032
But, when I have updated the code and run the CKAN using command `ckan -c /etc/ckan/default/ckan.ini run` and create a new user my changes  are not reflected. As per my understanding my code change is not loaded by CKAN.

Please guide me. How can I test my changes in my environment?

**Comment by Vishal-NEC** [comment]
@amercader 
I also want to add a PR for this issue.
