### ISSUE TITLE
Lack of Proper install guides: Install with Docker Guide

### ISSUE THREAD

**Issue by Qodestackr** [ckan/ckan#7734]
## Describe the bug
I have an issue here. All materials recommend cloning repo, then moving into `contrib/docker` directory. However, `git clone https://github.com/ckan/ckan.git` only comes with a contrib folder with:`alembic` and `cookiecutter` directories. What is the recommended way?

### Steps to reproduce
Expect to find docker directory as the documentation says [here](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html)
```docs
2. Build Docker images
3. 
```

My goal is to run CKAN as a data portal and build my application served by django hopefully over a REST API and so on.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by Qodestackr** [comment]
Or is this the recommended way? [HERE](https://docs.ckan.org/en/2.5/maintaining/installing/install-using-docker.html)

**Comment by EricSoroos** [comment]
Start here: https://github.com/ckan/ckan-docker
