### ISSUE TITLE
Trouble with CKAN Installation and Docker on Ubuntu 23.04 (Lunar)

### ISSUE THREAD

**Issue by Sanjay-Manandhar** [ckan/ckan#7735]
**Description:**
I'm currently running Ubuntu 23.04 with the code name Lunar. I've been trying to set up CKAN using Docker, but I've encountered some issues that I need assistance with.

**Problem 1: Docker Volumes 
In my attempt to integrate local files into Docker using volumes and bind them to `srv/app/src/ckan/ckan` in the `docker-compose.dev.yml` file, I encountered a new problem. Upon doing this, the CKAN container becomes unhealthy, and I receive an error message indicating that `ckan-docker-ckan` is unhealthy. I need guidance on resolving this issue.

**Alternative Approach: Source Installation**
In light of the Docker issues, I tried to install CKAN using a different method involving source installation. During this process, I came across a problem related to `greenlet`. The error message states: "Failed to build greenlet. ERROR: Could not build wheels for greenlet, which is required to install pyproject.toml-based projects."

**Request for Assistance:**
I kindly request assistance in resolving the two aforementioned issues:

1. **Docker and CKAN Health:** How can I address the `ckan-docker-ckan` health issue when using Docker volumes as described above?
2. **Source Installation and Greenlet Error:** How can I resolve the `Failed to build greenlet` error when attempting the source installation method?

Your help will be greatly appreciated. Thank you in advance for your support.

**Environment Details:**
- Linux Distro: 23.04 (Lunar)
- CKAN Version: [2.10.1]
- Docker Version: [24.0.5]
- Python Version for source: [3.11.4]

**Steps Taken:**
1. Detailed list of steps you've followed to set up CKAN using Docker.

-   -  git clone https://github.com/ckan/ckan-docker
-   - cp -pr .env.example .env   
-   - docker compose up -d --build  (ckan-docker-ckan)=healthy]
-   - nano docker-compose.yml
-   -   map the volume and save it
-   - docker compose down
-   - docker compose up -d --build [ (ckan-docker-ckan)=unhealthy]

 
2.Using souce method:

- - sudo apt-get install python-dev postgresql libpq-dev python-pip python-virtualenv git-core solr-jetty openjdk-6-jdk
- - sudo mkdir -p /usr/lib/ckan/default
- - sudo chown `whoami` /usr/lib/ckan/default
- - virtualenv --no-site-packages /usr/lib/ckan/default
- - . /usr/lib/ckan/default/bin/activate
- pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.5.9#egg=ckan'
 [source installation error as mentioned above]
 
3. Any troubleshooting steps attempted to resolve the mentioned issues.

- For source installation I did try this  [issue #1919](https://github.com/gevent/gevent/issues/1919), and ecnounterd the same problem

Thank you for your time and assistance.

**Comment by kowh-ai** [comment]
A couple of things: 

1.  Ubuntu **23.04** is **not supported** (only Ubuntu 20.04 and 22.04 are supported)
2. Python **3.11** is **not supported** (only Python 3.7 to 3.10 are supported)

**Comment by Sanjay-Manandhar** [comment]
Thank you for your suggestion. However, reinstalling the operating system to a different version might not be compatible with our requirements. It seems that using Docker could be a viable solution. Additionally, as mentioned earlier, I am encountering some issues with Docker. Could you please assist me with resolving these problems? Your help would be greatly appreciated.

**Comment by kowh-ai** [comment]
Try again. I had missed out updating the `docker-compose.dev.yml` file with some environment variables for the db service

**Comment by Sanjay-Manandhar** [comment]
I tried again, but still it gives me same output.

**Comment by kowh-ai** [comment]
Please try the following

1. bring up the CKAN docker services in dev mode 
`docker compose -f docker-compose.dev.yml build`
`docker compose -f docker-compose.dev.yml up`

2. copy the CKAN source in the running container to the src/ directory
`docker cp <container-id>:/srv/app/src/ckan ./src`

3. You can now make (local dev) changes in `./src/ckan/*`

**Comment by Sanjay-Manandhar** [comment]
Thank you. very much. It wroked :smiley:

**Comment by Sanjay-Manandhar** [comment]
Thank you for your help.
