### ISSUE TITLE
Login page broken when using second Nginx reverse proxy

### ISSUE THREAD

**Issue by OfficialOwlElder** [ckan/ckan#7739]
## CKAN version
2.10

## Describe the bug
When using a second Nginx reverse proxy (Nginx 2) pointing towards the CKAN Nginx reverse proxy (Nginx 1) , we are unable to get past the login page when accessing our CKAN page from a public-facing domain. Once you enter your credentials and click login, it just refreshes the page. Nginx 2 is reverse proxied to Nginx 1. I checked the error logs for Nginx 1, Nginx 2, ckan-uwsgi, ckan-worker, and ckan-datapusher, but none of them show anything. Both machines are on the same network with no firewall configurations. I am able to access the CKAN page on the local network from another machine without any issues (if I change the site_url to the hostname of the CKAN machine). The problem only arises when I try to access the CKAN page like so: 
open internet on 3rd machine -> nginx 2 behind public domain -> nginx 1 -> ckan page

One thing to note, the rest of the webpage works just fine. I am able to click on Datasets, Organizations, etc. without issue. It's specifically the login portion of the login page that is causing me problems. It seems to 

Any help would be appreciated. Thank you !

### Steps to reproduce
1. Setup CKAN with all dependencies on an Ubuntu 20.04 machine following the [CKAN 2.10 package installation instructions](https://docs.ckan.org/en/2.10/maintaining/installing/install-from-package.html)
2. Modify ckan.site_url to http://public_facing_domain_name (ckan.ini)
3. Add ckan.root_path and set to /ckan (ckan.ini)
4. Restart ckan with supervisorctl reload
5. Install Nginx on a separate machine with Debian 11
7. Configure Nginx 2 with the same settings as Nginx 1, changing proxy_pass to http://ckan_machine_hostname
9. Restart Nginx 2 service
10. Go to ckan page using internet
11. Click Log in
12. Enter username and password
13. Click login
14. Page essentially just refreshes

### Expected behavior
You can access the CKAN page from the open internet and log into an account.

### Additional details
Nginx 1 configuration on Ubuntu 20.04 CKAN machine
![image](https://github.com/ckan/ckan/assets/22074181/052df6ea-857f-4313-8013-d99871027c3a)

Nginx 2 configuration on Debian 11 machine
![image](https://github.com/ckan/ckan/assets/22074181/4b0e071e-f390-4197-be80-cfab227b151b)

ckan.ini configuration on Ubuntu 20.04 CKAN machine
![image](https://github.com/ckan/ckan/assets/22074181/dccc85ca-f5bb-4f14-93bc-e196b2fb632f)
![image](https://github.com/ckan/ckan/assets/22074181/d70ec17a-967e-4b57-a56a-70e888e895fc)

The rest should all be default

Edit: 
Turns out that there is a sneaky 302 in the Nginx access.log from the CKAN machine
![image](https://github.com/ckan/ckan/assets/22074181/011841e5-0874-4be3-b411-4d25479c2595)

**Comment by OfficialOwlElder** [comment]
One thing to note, the rest of the webpage works just fine. I am able to click on Datasets, Organizations, etc. without issue. It's specifically the login portion of the login page that is causing me problems.

**Comment by OfficialOwlElder** [comment]
I was able to get it to work sometimes in both Chrome and Edge. It seems to have something to do with the cookies. If I try it in incognito, it works every time. It is hit or miss when not using incognito. It seems it could be similar to #7700

**Comment by kowh-ai** [comment]
What are the following config file variables set to:

`REMEMBER_COOKIE_*`(there’s potentially a few of these)
`beaker.session.cookie_domain`

**Comment by OfficialOwlElder** [comment]
I am unable to find any cooking variables in any of the ckan config files.

**Comment by OfficialOwlElder** [comment]
I tried disabling the reverse proxy 1 (NGINX reverse proxy on CKAN machine) and pointing reverse proxy 2 towards the uwsgi webserver on the CKAN machine and get another issue. After logging in, I start to a get a DNS_PROBE_START error. I can fix this by going to any other website (google.com for example) and going back to the CKAN page. It shows me as logged in. If I logout, I get the DNS_PROBE_START error again.

**Comment by OfficialOwlElder** [comment]
Alright, I was able to fix it by wiping all related cookies. I have no idea why the intermediary Nginx reverse proxy causes this issue, but something causes the cookies to break the login page. I'm closing this issue for now, though I'm happy to help out with resolving this in the future if needed.

**Comment by OfficialOwlElder** [comment]
Setting to close as not planned

**Comment by wardi** [comment]
Sounds like this is related to #7700
