### ISSUE TITLE
Dataset and resource names are truncated too aggressively

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#7742]
## CKAN version

2.9

## Describe the bug

Dataset and resource names are truncated to 25 or 30 characters too aggressively, which creates usability problems when eg a dataset contains multiple resources whose names start similarly.

Consider the resource at:

https://www.data.qld.gov.au/dataset/service_capacity_tracker_dashboard/resource/de2cc54c-4b83-4ab1-af55-fca04bf0e4fa

It is named "Service Capacity Tracker for Bus Routes 600 Onwards CSV" and the resources alongside it have names like "Service Capacity Tracker for Bus Routes 300 to 599 CSV", etc. In the resource listing sidebar (`templates/package/snippets/resources.html`), they all show up as "Service Capacity..." and there is no way for the user to tell them apart.

### Steps to reproduce

- Create a dataset containing resources whose names are the same for the first 25 characters.
- Browse to a resource.
- The resource listing in the sidebar has no way to distinguish resources.

### Expected behavior

There should always be a way to see the full name, eg via a tooltip, or expansion when you click on the ellipsis.

Truncation also should be used less often and/or made configurable.

### Additional details

https://www.data.qld.gov.au/dataset/service_capacity_tracker_dashboard contains examples of the problem.

**Comment by wardi** [comment]
How about a template helper function responsible for name truncation with a parameter that indicates the context, like "resource title list", in each template? That would allow sites to override the default truncation behaviour to whatever makes sense for them, let them choose how to truncate (e.g. include endings when many resources start with the same text) or disable truncation entirely.

**Comment by ThrawnCA** [comment]
> How about a template helper function responsible for name truncation

I thought CKAN just finished moving away from rolling its own truncation, replacing it with Jinja's truncate filter...not sure how you would incorporate that into a helper function.

> with a parameter that indicates the context, like "resource title list", in each template? That would allow sites to override the default truncation behaviour to whatever makes sense for them, let them choose how to truncate (e.g. include endings when many resources start with the same text) or disable truncation entirely.

Maybe, but it would be good to improve the baseline out-of-the-box solution.

**Comment by ThrawnCA** [comment]
We have applied a fix to our fork (qld-gov-au/ckan) that adds tooltips preserving the full name, so https://www.data.qld.gov.au/dataset/service_capacity_tracker_dashboard/resource/de2cc54c-4b83-4ab1-af55-fca04bf0e4fa is no longer a suitable example of the issue.

**Comment by ThrawnCA** [comment]
@wardi The pull request now passes tests.
