### ISSUE TITLE
Plugin Toolkit's `check_ckan_version()` handles pre-release versions incorrectly

### ISSUE THREAD

**Issue by themowski** [ckan/ckan#7777]
## CKAN version

2.9+, and likely older versions as well; most links to code in this writeup reference `master` at cff1cbad3d355bf393511b648314c15ca2cdf3ff.

## Overview

The CKAN Plugin Toolkit provides a function called [`check_ckan_version()`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/plugins/toolkit.py#L202) that can be used to verify whether the current CKAN version lies between specified min/max version values. The current implementation of this function relies on a helper function called [`_version_str_2_list()`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/plugins/toolkit.py#L193) that strips non-digit characters from an input string, and then splits the result on period `.` characters and applies the `int()` function, resulting in a list of integers. The `check_ckan_version()` function applies this helper to `ckan.__version__` and the requested min/max, then uses Python's built-in `list` comparison rules to determine the result. In addition to being a part of the Toolkit's public API, the `check_ckan_version()` function is also used by the Toolkit's [`requires_ckan_version()`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/plugins/toolkit.py#L236) function.

When this functionality was first introduced, this algorithm made sense and worked as expected. Alpha/beta releases were denoted simply by appending `a` or `b` to the end of `ckan.__version__`; some (much older) releases even use `c`, `d`, and other letters. Based on recent values of `ckan.__version__`, CKAN appears to be following Python best-practices by migrating toward a [PEP 440-compliant](https://peps.python.org/pep-0440/) versioning scheme. In the new scheme, alpha/beta releases are denoted as `X.Y.ZaN` or `X.Y.ZbN`, where `N` is a digit character. This results in unexpected behavior of `check_ckan_version()` when using a pre-release version of CKAN.

> [!NOTE]
> I was unable to find definitive, up-to-date documentation describing the exact versioning strategy used for CKAN. I found references to versioning in the [release process](https://docs.ckan.org/en/latest/contributing/release-process.html), but alpha/beta releases are not handled in the current PEP 440-compliant way. Similarly, the [releases](https://docs.ckan.org/en/latest/maintaining/releases.html) page has detailed information about the major/minor/patch versioning scheme used, but does not cover alpha/beta versions (likely because those are not officially released).

This bug report demonstrates scenarios in which `check_ckan_version()` returns "wrong" answers, and provides a suggestion for improvement.

### Motivation

You may find yourself saying, "This seems like an edge case. Should we really be supporting users who choose to run pre-release versions of CKAN?" I would argue that we should. Users typically do not _want_ to use a pre-release version, but rather do so because they need a feature that has been merged to a dev branch, but is not available in any released version. Additionally, extension developers may want to target multiple versions of CKAN, and the simplest way to do that is via the `check_ckan_version()` or `requires_ckan_version()` functions. Offering better support for pre-release versions gives those developers more control and lets them more confidently assert which versions of CKAN their plugins are compatible with.

A recent example of why this support is important is the replacement of repoze.who with Flask-Login in #6560. That was done during alpha development of `2.10`, and it changed the way that authentication plugins work, but there was no difference in version number after this breaking change was implemented. To be fair, that was an alpha release, so "buyer beware"; but, on the other hand, as a casual user or plugin developer, I would expect that a substantial breaking change like that would be reserved for a new _major_ version of the software. In any case, as a result, this is the situation:

* CKAN 2.9.x -- uses repoze.who
* CKAN 2.10.0a0 -- some commits use repoze.who, others use flask-login
* CKAN 2.10.0 -- uses Flask-Login

Developers of authentication plugins may decide to include a `check_ckan_version(min_version='2.10.0')` guard around [some Flask-login-specific code](https://github.com/NaturalHistoryMuseum/ckanext-ldap/issues/116), and can then assert that CKAN 2.10.0+ is supported. However, as we will see below, this call will return `True` for alpha builds of 2.10.0 -- so the Flask-Login code may get called unexpectedly. There is no way to support all versions of CKAN without some convoluted `try`-`except` logic that `check_ckan_version()` is theoretically supposed to help us avoid.

If we had better alpha-level tracking of CKAN version, particularly when significant breaking changes are merged (e.g., if `ckan.__version__` had been bumped to 2.10.0a1 when #6560 was merged), and if `check_ckan_version()` could correctly handle pre-release versions, then plugin developers would be able to seamlessly support all versions of CKAN -- both pre- and post-merge of that feature -- by targeting the relevant pre-release version.

### Case 1: `ckan.__version__ == '2.10.1b0'`

During development of CKAN 2.10.1, the `ckan.__version__` variable was [at one point](https://github.com/ckan/ckan/blob/ecf6574f2a999275633c52e3c214434b9db0c21b/ckan/__init__.py#L3) set to `2.10.1b0`, which represents the first beta version of CKAN 2.10.1.

The following Python REPL session (performed in the `ckan` repo at commit ecf6574f2a999275633c52e3c214434b9db0c21b) demonstrates that `_version_str_2_list()` gives the wrong version string, which results in `check_ckan_version()` also giving bogus answers:

```python
>>> import ckan
>>> from ckan.plugins import toolkit
>>> ckan.__version__
'2.10.1b0'
>>> toolkit._version_str_2_list(ckan.__version__)
[2, 10, 10]
>>> toolkit._version_str_2_list('2.10.10')
[2, 10, 10]
>>> toolkit._version_str_2_list('2.10.1b0') == toolkit._version_str_2_list('2.10.10')
True
```

The internal function parses the `1b0` component in the CKAN version as `10` (ten)! From this function's perspective, `2.10.1b0` and `2.10.10` are the same version. This results in some interesting, unexpected behavior.

First, let's see if this version is at least 2.10.2, which should be `False`, since this is a beta for 2.10.1:

```python
>>> toolkit.check_ckan_version(min_version='2.10.2')
True
```

Similarly, we can verify that this version is at most 2.10.1, which should be `True`, since a beta for a release is (strictly) less than the release:

```python
>>> toolkit.check_ckan_version(max_version='2.10.1')
False
```

### Case 2: `ckan.__version__ == '2.10.0a0'`

During development of CKAN 2.10.0, the `ckan.__version__` variable was [at one point](https://github.com/ckan/ckan/blob/8256f6ed2fefd8614c7dab8266b091696811f091/ckan/__init__.py#L3) set to `2.10.0a0`, which represents the first alpha version of CKAN 2.10.0.

Since 2.10.0a0 is an alpha version, it is strictly less than 2.10.0. As a user, I would expect `check_ckan_version(min_version='2.10.0')` to return `False` in this case. However:

```python
>>> import ckan
>>> from ckan.plugins import toolkit
>>> ckan.__version__
'2.10.0a0'
>>> toolkit.check_ckan_version(min_version='2.10.0')
True
```

### Case 3: `ckan.__version__ == '2.10.0'`

The final example takes place at the `ckan-2.10.0` tag in the Git repo. This time, we look at the behavior of `check_ckan_version(min_version='2.10.0a1')`. This is an alpha of `2.10.0`, so `check_ckan_version()` should return `True`.

```python
>>> import ckan
>>> from ckan.plugins import toolkit
>>> ckan.__version__
'2.10.0'
>>> toolkit.check_ckan_version(min_version='2.10.0a1')
False
```

## Proposed Solution: Leverage `packaging.version`

I recommend that the existing functionality be overhauled in favor of integrating with the Python Packaging Authority's [`packaging` package](https://github.com/pypa/packaging). Version 21.3 (the latest) is already in [`requirements.txt`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/requirements.txt#L85) as a dependency of `redis`, so adding it to `requirements.in` should be pretty straightforward.

Here is a high-level outline of how I see this working:

* CKAN officially adopts PEP 440-compliant versioning. Releases will continue to be `X.Y.Z`. For pre-release versions, use version numbers of the form `X.Y.Z[aN|bN]`. Update the comment for [`ckan.__version__` in `ckan/__init__.py`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/__init__.py#L3) with a statement explaining how to set the version correctly.

  * I also suggest that CKAN develop official instructions on how/when to bump the alpha/beta version, and actually bump it when significant, breaking changes are merged. This will allow extension authors to have finer control over min/max versions when using `check_ckan_version()` -- if their extension relies on a feature introduced in a pre-release version that was "new" at the time of their feature (e.g., `2.10.2a1`), then they can target that version directly, instead of the related release version.

* Explicitly add `packaging` to `requirements.in`.

* Remove [`ckan.plugins.toolkit._version_str_2_list()`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/plugins/toolkit.py#L193). This function is only used by `ckan.plugins.toolkit.check_ckan_version()`, does not work as expected, and is not part of the public API, so there is no issue with its removal.

* Re-implement[`ckan.plugins.toolkit.check_ckan_version()`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/plugins/toolkit.py#L202) to use `packaging.version` for version comparison/testing, and update the docstring to give more detail for users. Here is a 90% solution; one issue is that this function raises `ValueError`, so it is not compliant with the CKAN development guidelines.

```python
import packaging.version as pv

def check_ckan_version(min_version: Optional[str] = None,
                       max_version: Optional[str] = None) -> bool:
    '''
    Return ``True`` if the CKAN version is greater than or equal to
    ``min_version`` and less than or equal to ``max_version``,
    return ``False`` otherwise.

    If ``min_version`` is ``None`` (the default), then just check whether
    the CKAN version is less than or equal to ``max_version``.

    If ``max_version`` is ``None`` (the default), then just check whether
    the CKAN version is greater than or equal to ``min_version``.

    If not None, ``min_version`` and/or ``max_version`` must be a version
    string of the form ``'X.Y'``, ``'X.Y.Z'`` (release version),
    ``'X.Y.ZaN'`` (alpha pre-release version), or ``'X.Y.ZbN'`` (beta
    pre-release version), where ``X``, ``Y``, ``Z``, and ``N`` are
    nonnegative integers. Version ``'X.Y'`` is equivalent to ``'X.Y.0'``.

    All alpha versions of a release are less than all beta versions of that
    release, and all pre-release versions are less than the corresponding
    release version.

    :param min_version: the minimum acceptable CKAN version,
        e.g., ``'2.1.0'`` (optional, default: None)
    :type min_version: string or None

    :param max_version: the maximum acceptable CKAN version,
        e.g., ``'2.3.0'`` (optional, default: None)
    :type max_version: string or None

    :raises: ValueError, if ``min_version`` or ``max_version`` is not a
        valid version identifier

    :returns: True if the current CKAN version is in the specified interval
    :rtype: bool

    '''
    # This will only fail if someone defines ckan.__version__ incorrectly;
    # unit tests should ensure that this never happens
    current = pv.parse(ckan.__version__)

    try:
        at_least_min = (min_version is None) or (current >= pv.parse(min_version))
    except pv.InvalidVersion:
        # TODO: This should be a custom error per the CKAN dev guidelines
        raise ValueError(f"min_version '{min_version}' is not a valid version identifier")

    try:
        at_most_max = (max_version is None) or (current <= pv.parse(max_version))
    except pv.InvalidVersion:
        # TODO: This should be a custom error per the CKAN dev guidelines
        raise ValueError(f"max_version '{max_version}' is not a valid version identifier")

    return at_least_min and at_most_max
```

* Update [`ckan.plugins.toolkit.requires_ckan_version()`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/plugins/toolkit.py#L236) to catch the Exception that may be raised by the new `check_ckan_version()` call.

* Update the [Plugin Toolkit tests](`https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/tests/plugins/test_toolkit.py`) to test more items:

  * Explicitly test that `packaging.version.parse(ckan.__version__)` does not raise `packaging.version.InvalidVersion` (maybe this belongs somewhere else?)
  * Add some pre-release versions to the [`test_check_ckan_version()`](https://github.com/ckan/ckan/blob/cff1cbad3d355bf393511b648314c15ca2cdf3ff/ckan/tests/plugins/test_toolkit.py#L68) function
  * One or more tests related to the examples that I demonstrated above (can probably be done through `test_check_ckan_version()`)

* Revisit the [release process](https://docs.ckan.org/en/latest/contributing/release-process.html) and [releases](https://docs.ckan.org/en/latest/maintaining/releases.html) pages in the documentation to add information about pre-releases and make sure that examples are up to date.

I probably missed something, but I'm hopeful that this is enough of an outline to get the ball rolling.

**Comment by wardi** [comment]
@themowski sounds great to me, let's adopt PEP 440-compliant versioning. Would you submit this change as a pull request?

**Comment by themowski** [comment]
Sure, I'll work on it when I have some downtime. 👍

**Comment by Vishal-NEC** [comment]
@themowski I am interested to work on this issue. I am unable to reproduce the issue, can you please tell me how to reproduce this issue? How can I call `check_ckan_version()` method?

**Comment by themowski** [comment]
> @themowski I am interested to work on this issue. I am unable to reproduce the issue, can you please tell me how to reproduce this issue? How can I call `check_ckan_version()` method?

@Vishal-NEC if you read the "Demonstration" section in my bug report, you can see examples from the Python REPL that show how to call all of the functions. Here's the snippet from Demonstration, Case 1:

```
>>> import ckan
>>> from ckan.plugins import toolkit
>>> ckan.__version__
'2.10.1b0'
>>> toolkit._version_str_2_list(ckan.__version__)
[2, 10, 10]
>>> toolkit._version_str_2_list('2.10.10')
[2, 10, 10]
>>> toolkit._version_str_2_list('2.10.1b0') == toolkit._version_str_2_list('2.10.10')
True
```

The `check_ckan_version()` function can be called with `toolkit.check_ckan_version()` in the snippet above.

To replicate the examples, you need to do these steps (this is off the top of my head, so it may not be 100% accurate):

```bash
# Clone the CKAN repo
git clone https://github.com/ckan/ckan

# Enter the repo
cd ckan

# Check out a commit -- I wrote commit hashes in the description
git checkout COMMIT_HASH

# Start a REPL
python
```

From here, you should be able to execute the REPL steps and see the behaviors I demonstrated.

**Comment by themowski** [comment]
Somehow I missed that there was a PR open for this, my apologies. (I would have thought GitHub would automatically contact me if a PR was open that fixes an issue I'm watching, maybe my notification settings need to be reviewed.)

I notice two things from my OP that are IMO important and didn't make it into PR #7888:

1. CKAN officially adopts PEP 440-compliant versioning. Releases will continue to be `X.Y.Z`. For pre-release versions, use version numbers of the form `X.Y.Z[aN|bN]`. Update the comment for `ckan.__version__` in ckan/__init__.py with a statement explaining how to set the version correctly.

2. Explicitly add packaging to requirements.in.

Item 2 is particularly important; right now, the implementation works because `packaging` happens to be included in the dependency tree by some other dependency, but if that changes in the future, this fix will break.
