### ISSUE TITLE
ckan is not running on  root_path

### ISSUE THREAD

**Issue by nisha-nec** [ckan/ckan#7803]
## CKAN version
V2.10.1

## Describe the bug
I set the below value in ckan.ini and used nginx for proxy the request. 
`ckan.root_path` = `/ckan/{{LANG}}`

Below is the nginx configuration:

```
location /ckan {
        resolver kube-dns.kube-system.svc.cluster.local valid=5s ipv6=off;
        set $ckan ckan.default.svc.cluster.local;
        #rewrite ^/ckan(.*)$ /ckan$1 break;
        proxy_pass http://$ckan:5000;
        proxy_set_header X-Url-Scheme $scheme;
        proxy_set_header Host $host;
        proxy_cache cache_ckan;
        proxy_cache_bypass $cookie_auth_tkt;
        proxy_no_cache $cookie_auth_tkt;
        proxy_cache_valid 10m;
        proxy_cache_key $host$scheme$proxy_host$request_uri;
        limit_rate 25M;
        #limit_req zone=ckan burst=100 nodelay;

}

```
### Expected behavior
The ckan should be running on root_path.

### Additional details
I am getting 404 not found error.

**Comment by MiguelGuzmanDev** [comment]
ya probaste revisando la documentación: https://docs.ckan.org/en/2.10/maintaining/installing/deployment.html

**Comment by Zharktas** [comment]
You need to configure your uwsgi to host ckan in root path, nginx just proxies into it. There's related PR for the configuration https://github.com/ckan/ckan/pull/5718

**Comment by nisha-nec** [comment]
Now, I am able to run CKAN on root_path.
