### ISSUE TITLE
URL validator does not support ":" for specifying ports

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#7812]
## Describe the bug
The URL validator https://github.com/ckan/ckan/blob/2.10/ckan/logic/validators.py#L775 does not support specifying a port.
E.g. ``https://example.com/some-data`` is valid, but ``https://example.com:8080/some-data`` is **not** valid.

### Expected behavior
IMO, Port numbers should be allowed in a URL.

### Additional details
The `pieces.netloc`-part of the check could be adapted such that it splits it into `server_name` and `port` and checks those separately. I would be willing to write a PR if this is an acceptable approach.

**Comment by TomeCirun** [comment]
@paulmueller , my sincere apologies for the oversight. During my initial visit to the issue, I didn't read the full text beyond the "Describe the Bug" section. I now see that you've not only identified the problem but have also provided a solution, and you were willing to create a PR. I truly appreciate your efforts, and I'm very sorry for my earlier mistake. My bad.

I can remove my PR...

**Comment by paulmueller** [comment]
Hi @TomeCirun, thanks a lot for your PR. I do not claim the right to fix this issue and your PR looks good to me :+1:
