### ISSUE TITLE
set datastore active slow (unsafe?) resource update

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#7832]
## CKAN version
all

## Describe the bug
When creating or deleting a datastore table the `datastore_active` flag is updated by reading resource extras, parsing and updating the json in python, then writing to the database. This is slower than necessary and may be unsafe with other updates happening at the same time causing loss of resource metadata changes.

A second related issue with this code: Resource extras are not expired from the cache when updated, so if a datastore table is created then removed, or removed then created in one session the datastore_active flag will be set incorrectly.

### Steps to reproduce
Use datastore_create or datastore_delete on a resource

### Expected behavior
field should be updated in database without round trip to python for parsing and updating

### Additional details
Updating json in db is supported since postgresql 10.x https://www.postgresql.org/docs/10/functions-json.html

**Comment by wardi** [comment]
@smotornyuk good point. It looks like `jsonb_set` has been available since postgresql 9.5: https://www.postgresql.org/docs/9.5/functions-json.html but I haven't tested this change with that version (it certainly won't work with earlier versions).

The only change *really* required for the backport is https://github.com/ckan/ckan/pull/7833/commits/61b8b35734cb254c45d9c3735e98ad0c0b6b2c9e which is still slow but fixes the flag being set incorrectly.

**Comment by wardi** [comment]
@smotornyuk here's a fix for that backport test failure https://github.com/open-data/ckan/commit/ed32f20d6149fb3af83dc26576763809915bd749

**Comment by amercader** [comment]
@wardi @smotornyuk this introduced a typing error when backporting to dev-v2.10, can you have a quick look?

https://github.com/ckan/ckan/actions/runs/6544586346/job/17771339195?pr=7864

```
 /home/runner/work/ckan/ckan/ckanext/datastore/logic/action.py
  /home/runner/work/ckan/ckan/ckanext/datastore/logic/action.py:664:64 - error: "package_id" is not a known member of "None" (reportOptionalMemberAccess)
```
