### ISSUE TITLE
Cannot create API token via API (hen and egg)

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#7836]
## Describe the bug
CKAN 2.9 supported API keys which made it possible to create a user via the API (`ckan.auth.create_user_via_api = true`) and automatically return the user's API key (`ckan.auth.create_default_api_keys = true`).

Since CKAN 2.10 does not support API keys, it is not possible anymore to use the API anonymously to create users and start working as them. An API token is required to create an API token for a user. So users would have to log in via the web interface first to create an API token.

**Comment by amercader** [comment]
> So users would have to log in via the web interface first to create an API token.

Just to be sure, if you use a sysadmin's token you can call [`api_token_create`](https://docs.ckan.org/en/2.10/api/index.html#ckan.logic.action.create.api_token_create) on the newly created user to get a token for that user back.

I don't know, but adding the option to create API tokens anonymously to users that already can be created anonymously (if `ckan.auth.create_user_via_api = true`) seems to make things too easy for spammers, even if this is turned off by default.


> Let's add an optional parameter to user_create or a new endpoint that creates a user and an API token at the same time

For authenticated users (sysadmins) I think the best option is a new `create_api_token` param. Note that API tokens creation requires at least a name, and may require additional parameters depending on plugins installed (eg `expire_api_token`) so we need to include a parameter for those as well

**Comment by paulmueller** [comment]
> > So users would have to log in via the web interface first to create an API token.
> 
> Just to be sure, if you use a sysadmin's token you can call [`api_token_create`](https://docs.ckan.org/en/2.10/api/index.html#ckan.logic.action.create.api_token_create) on the newly created user to get a token for that user back.
> 
> I don't know, but adding the option to create API tokens anonymously to users that already can be created anonymously (if `ckan.auth.create_user_via_api = true`) seems to make things too easy for spammers, even if this is turned off by default.

My use case is this: I have a testing CKAN instance where users can connect to with a software that I have written to familiarize themselves with it. I wanted to make signup of test accounts as simple as possible (click of a button in the application). I cannot use an admin account (shipping an admin API token with the application is not an option). The user has to create the token after an account is created with the API. I could also automate it with `curl` scripts, but using the API would be the preferred option.
