### ISSUE TITLE
CircleCI Builds

### ISSUE THREAD

**Issue by JVickery-TBS** [ckan/ckan#7858]
Related: https://discuss.circleci.com/t/announcing-a-more-secure-team-member-signup-experience/49007

There was a recent change to CircleCI which prevents miscellaneous users from being able to initialize a CircleCI build. Thus, GitHub users not part of the CKAN organization pushing Pull Requests will not be able to initialize the CircleCI Tests.

For instance, I make PRs but am not part of the CKAN GitHub org, so it will fail to run the tests with the message of:
```
Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
```

I personally got around this by making a BOT account for our Github org and CircleCI project and used a GitHub workflow to initialize everything: https://github.com/open-data/ckanext-canada/blob/master/.github/workflows/circleci.yml

The downfall to that is of course all the CircleCI tests will just show the BOT user as the initializer. Although, it does have the git hash in there, so you could always trace it back to the user who committed that hash.

I am not too sure if an outside of org user without write permissions to a GitHub repo is able to be added to the CircleCI project or not and have it all work. That being said, if it is possible, it would be annoying for you to always have to add users to the CircleCI projects. And then of course, you would have to then manage users in CircleCI.

I have talked to CircleCI support and this is all the new expected behavior as they were trying to make it all more secure.

Just another thing to note: even new GitHub org users will need to be separately added to the CircleCI project now. So if you add a user to the GitHub organization, you will need to manually add them to the CircleCI projects as well.

**Comment by EricSoroos** [comment]
CircleCI did run for my co-worker yesterday: https://github.com/ckan/ckan/pull/7857
