### ISSUE TITLE
Improper CLI Command for creating a new migration script

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#7860]
## CKAN version
Master
## Describe the bug
Creating a new migration script using CKAN CLI command `ckan generate migration -m "Add account table"` results in error as below:
![image](https://github.com/ckan/ckan/assets/66116382/8e6d3674-5c0d-4438-ba50-3aab8748746f)

After specifying the file path of the CKAN config (.ini) like `ckan -c /etc/ckan/default/ckan.ini ckan generate migration -m "Add account table"` it results in error as below:
![image](https://github.com/ckan/ckan/assets/66116382/55114266-c6f1-44cd-94cf-635aa7420f92)

### Steps to reproduce
1. Follow the Database migration docs: https://docs.ckan.org/en/2.10/contributing/database-migrations.html?highlight=migration#database-migrations
2. Create a new migration script, use CKAN CLI:
    `ckan generate migration -m "Add account table"`

### Expected behavior
**It is better to specify the exact CKAN CLI command for creating a new migration script.** 
i.e., `ckan -c /etc/ckan/default/ckan.ini generate migration -m "Add account table"`

**Comment by Gauravp-NEC** [comment]
If Dev-team agree to have work on this issue. I will submit the PR. Please assign this issue to me.

**Comment by tino097** [comment]
@Gauravp-NEC i think your command is wrong 

From the image you have provided, in terminal i can see
```
ckan  -c /etc/ckan/default/ckan.ini **ckan** generate migration -m"Add account taable"
```
The ckan between asteriks should be removed and try again

**Comment by Gauravp-NEC** [comment]
> @Gauravp-NEC i think your command is wrong
> 
> From the image you have provided, in terminal i can see
> 
> ```
> ckan  -c /etc/ckan/default/ckan.ini **ckan** generate migration -m"Add account taable"
> ```
> 
> The ckan between asteriks should be removed and try again

@tino097 , I think it would be better to specify the exact CKAN CLI command for creating a new migration script in docs. I.e., `ckan -c /etc/ckan/default/ckan.ini generate migration -m "Add account table"`

**Comment by Gauravp-NEC** [comment]
> @Gauravp-NEC i agree, you can update the docs with specifying the need of config file and provide PR

@tino097 , Thanks. I have raised the PR https://github.com/ckan/ckan/pull/7863 to fix this issue.
