### ISSUE TITLE
Ckan 2.10, Create_Package Failing with Bad Request Error

### ISSUE THREAD

**Issue by MLaunch** [ckan/ckan#7865]
## Describe the bug
I'm receiving a Bad Request HTTP error when calling the create_package api. The ckan documentation example for this uses urlib2, so it's a little old. I tried to advance the code to use python3 (specifically 3.12) and came up with below steps to reproduce. But it is failing with bad request, even though I know the values and api key is valid.

Also, I tried to find the logs where a more detailed error message would be recorded, but can't find them.

### Steps to reproduce
    dataset_dict = {
        'name': name,
        'notes': notes,
        'owner_org': owner_org
    }

    myurl = 'http://ckan.mydomain.com/api/3/action/package_create'
    request = urllib.request.Request(myurl)

    request.add_header('Authorization', 'Bearer ' + key)
    request.add_header('X-CKAN-API-Key', key)
    request.add_header('Content-Type', 'application/json')
    request.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 6.1)')

    response = urlopen(request, data_string)

### Expected behavior
I would expect a 200 status response and a package / data product created.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by MLaunch** [comment]
note, I tried multiple variants of this, but they all failed as well with bad request.

**Comment by MLaunch** [comment]
Could also be that the dictionary is wrong (names, missing required elements, etc), but dictionary was pulled from the documentation example, so I am assuming that is not the case.

**Comment by wardi** [comment]
Try using ckanapi.RemoteCKAN to make your calls. That library handles the requests parameters, unwrapping response envelopes and automatically converts errors into exceptions for you.

**Comment by MLaunch** [comment]
Hi Ian,

Excellent! Thanks so much Ian!
