### ISSUE TITLE
Activity plugin missing docs

### ISSUE THREAD

**Issue by octavportar** [ckan/ckan#7872]
## CKAN version
2.10.1

## Describe the bug
I added the configuration "ckan.auth.public_activity_stream_detail = True" and marked the dataset public but in dashboard not appeat Activity Stream and in activity table does not record the activities.

### Additional details
![image](https://github.com/ckan/ckan/assets/79480476/065bdfe0-4319-4eef-8d30-825ecadcf2fd)
![image](https://github.com/ckan/ckan/assets/79480476/fcaec913-673e-49a1-9f86-a5e2e5f3c4c9)

CKAN Configuration Option
ckan.auth.public_activity_stream_detail = True

**Comment by wardi** [comment]
@PortarescuOctavian you might need to enable the `activity` plugin.

This should be documented in https://docs.ckan.org/en/2.10/maintaining/configuration.html?highlight=activity#activity-streams-settings but I only see it in the changelog.

**Comment by PortarescuOctavian** [comment]
Thanks!

**Comment by Gauravp-NEC** [comment]
@wardi , I am interested to work on this issue. I will submit a PR.
