### ISSUE TITLE
The documentation should be updated to reflect the actual statistics.

### ISSUE THREAD

**Issue by sagargg** [ckan/ckan#7876]
The current [2.10.x documentation](https://docs.ckan.org/en/2.10/maintaining/tracking.html) indicates that it will provde the following stats:
- Sort datasets by popularity
- Highlight popular datasets and resources
- Show view counts next to datasets and resources
- Show a list of the most popular datasets
- Export page-view data to a CSV file

but instead, the actual provided stats are:

- Total Number of Datasets
- Dataset Revisions per Week
- Most Edited Datasets
- Largest Groups
- Top Tags
- Users Creating Most Datasets

Also on v2.9.x, it provides the following stats 

- Top rated datasets
- Largest group
- Top Tags
- Users who created most datasets.

**Comment by Zharktas** [comment]
Tracking page views and [stats extension](https://docs.ckan.org/en/2.10/maintaining/stats.html) are actually different things

**Comment by sagargg** [comment]
okay. thanks for clarifying @Zharktas
