### ISSUE TITLE
`asbool` cannot handle empty strings

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#7909]
## CKAN version

2.10

## Describe the bug

`ckan.common.asbool` can handle empty lists, empty dicts, empty sets, `0`, and `None`, all of which evaluate to `False`. However, if given an empty string, it will error out with "String is not true/false".

### Expected behavior

An empty string should be evaluated as `False`, like every other empty object.

**Comment by ThrawnCA** [comment]
I would be very careful about taking away functionality like that. How many people may have looked at asbool and thought, "Oh, this is like the standard truthiness check, but it also handles strings with truth values, let's use it everywhere"?

**Comment by wardi** [comment]
Based on both our arguments the only safe thing to do is leave the definition as it is and if we want a validator that is only for config value-type uses we can come up with a new name for it.
