### ISSUE TITLE
Catch AttributeErrors in license retrieval

### ISSUE THREAD

**Issue by thorge** [ckan/ckan#7931]
The following code segment may also result in an `AttributeError`:

https://github.com/ckan/ckan/blob/8ddc2e800793d683c856b4a56f3d3f0ad3f1d168/ckan/views/resource.py#L95-L96

If, for some reason, the license object returned by `model.Package.get_license_register()[license_id]` does not have an `isopen` attribute or method, trying to call `isopen()` would result in an `AttributeError`, as well if `model.Package.get_license_register()[license_id]` evaluates to `None`. Currently, only `KeyErrors` are being caught.

It is advisable to include `AttributeError` in the except handle of the try block:

```python
except (KeyError, AttributeError):
    package[u'isopen'] = False
```

**Comment by Gauravp-NEC** [comment]
@amercader @thorge , I am interested to work on this issue. I will submit a PR.
