### ISSUE TITLE
Python versions support

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7935]
After discussions in #6613 and #7886, here's my proposed way forward

| CKAN version | Minimum Python version supported | Actions needed |
| --- | --- | --- |
| 2.10 | 3.7 | In the `dev-v2.10` branch, add modifiers to `requirements.in`  for `backports-zoneinfo==0.2.1; python_version < '3.9'` and `greenlet==2.0.2 ; python_version > '3.10'` to allow install on Python 3.10
| 2.11 | 3.9 | Make the tests and other runners run on Python 3.9, compile `requirements.txt` using Python 3.9. Update setup.cfg and docs |
| 2.12 | 3.10 | Update setup.cfg and docs after 2.11 is branched. |

This makes sense to me looking at Python's [support schedule](https://devguide.python.org/versions/) and is inline with what other similar projects are doing:

| Project | Python versions supported on latest release | Python versions supported in development branch |
| --- | --- | --- |
| [GeoNode](https://github.com/GeoNode/geonode) | >= 3.7 (4.1.3) | >= 3.10 (master) |
| [Django](https://github.com/django/django) | >= 3.8 (4.2.7) | >= 3.10 (master) |

**Comment by amercader** [comment]
@ckan/core I'd like to get master usable on Python 3.10+ asap so would be good to get thumbs up or objections on this, cheers!

**Comment by amercader** [comment]
These changes would help get more green in here: https://github.com/ckan/ckan-python-monitor

**Comment by amercader** [comment]
All in favour at the dev meeting, we'll go ahead with this plan

**Comment by pdelboca** [comment]
Close as this one was implemented in #7936
