### ISSUE TITLE
failed to upload binary data

### ISSUE THREAD

**Issue by cybaj** [ckan/ckan#7956]
## CKAN version
2.10.1

## Describe the bug
failed to upload binary data
![image](https://github.com/ckan/ckan/assets/11937687/65d7dc63-5284-460f-90d9-defeba16b52c)
![image](https://github.com/ckan/ckan/assets/11937687/f4974d98-cb1f-46a5-9773-bf60ce23982b)

### Steps to reproduce
1. clone `ckan/ckan-docker.git`
2. `docker compose up -d`
3. `docker exec -it sh`, `ckan -c /srv/app/ckan.ini sysadmin add tomato email=tomato@localhost name=tomato`
4. enter `localhost:443` and login
5. create dataset and upload

### Expected behavior
binary data uploading success.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by kowh-ai** [comment]
I don't get a **404 Not Found** but I don't get a successful upload to the datastore either...Are you able to share any more details of the issue you are facing?

**Comment by kowh-ai** [comment]
However I'm not expecting it to work as the DataStore is designed to handle tabular data, such as CSV or Excel files...not binary data
