### ISSUE TITLE
API operation resource_view_list returns empty list although there are views created for this resource

### ISSUE THREAD

**Issue by dportoles** [ckan/ckan#7973]
## CKAN version
2.10.1

## Describe the bug
API operation resource_view_list returns empty list although there are views created for this resource

### Steps to reproduce
1. create datatables_view for a resource
2.  query API resource_view_list for this resource

### Expected behavior
API operation resource_view_list returns the list with existing views

### Additional details
I've solved it by commenting this line on code
https://github.com/ckan/ckan/blob/4974db6b05b4bf4bcb95f7f1216618e6105dbc05/ckan/logic/action/get.py#L1152

but it would be solved in a better way

**Comment by TomeCirun** [comment]
I've tested this on CKAN `2.10.1`, `2.10.3`, and `master` and it works on all three branches. I cannot reproduce the error described above.

`curl  http://localhost:5000/api/3/action/resource_view_list -d '{"id": "76332266-f5f8-4f0a-998b-ba6429c4bca2"}'
{"help": "http://localhost:5000/api/3/action/help_show?name=resource_view_list", "success": true, "result": [{"id": "5d8089f4-fd4b-437b-b8a5-cfc8e1c28cb6", "resource_id": "76332266-f5f8-4f0a-998b-ba6429c4bca2", "title": "Table", "description": "", "view_type": "datatables_view", "date_format": "llll", "ellipsis_length": 0, "filterable": true, "responsive": true, "show_fields": ["_id", "WIC", "Property", "Suburb", "Postcode", "Owned/Leased", "Longitude", "Latitude"], "package_id": "d6618047-d7f7-4bfe-8638-6a42680e409a"}]}%  `

![image](https://github.com/ckan/ckan/assets/72216462/b375656b-df04-423c-a4bc-bdda3e811add)

**Comment by dportoles** [comment]
Maybe it would be a misconfiguration of plugins or other changes with side effect.
If you have tested and it's ok, let's close it
Thank you
