### ISSUE TITLE
libmagic error when CKAN 2.10.3 is installed from source

### ISSUE THREAD

**Issue by managume** [ckan/ckan#7986]
## CKAN version

2.10.3 in Ubuntu 22.04 with Python 3.10.12

## Describe the bug
I'm trying to install CKAN 2.10.3 from source in Ubuntu 22.04 with Python 3.10.12 but when I run the `ckan` command in the virtual environment it returns an error related to python-magic (python-magic == 0.4.27) :

_ImportError: failed to find libmagic.  Check your installation_

### Steps to reproduce
Following the "Installing CKAN from source" instructions from official documentation:
(...)
sh bin/activate
pip install --upgrade pip
pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.10.3#egg=ckan[requirements]'
sh bin/deactivate
sh bin/activate
ckan

### Expected behavior
Runs correctly `ckan` command

**Comment by managume** [comment]
Installing the libmagic-dev package (apt install libmagic-dev) fixes the error.

**Comment by amercader** [comment]
@managume Looks like this should be added to the installed apt packages listed in the documentation, do you want to submit a PR?

**Comment by Gauravp-NEC** [comment]
@amercader , I am interested to work on this issue.  I will submit a PR.
