### ISSUE TITLE
/dataset responds 200 status code when solr down

### ISSUE THREAD

**Issue by FuhuXia** [ckan/ckan#8002]
## CKAN version
2.10.1

## Describe the bug
When solr is down, endpoints such as `/` and `/organization` return 500 response code, but `/dataset` returns 200.

### Steps to reproduce
Turn off solr, then
```
$ curl -Is http://localhost:5000/dataset | head -n 1
HTTP/1.0 200 OK

$ curl -Is http://localhost:5000/ | head -n 1
HTTP/1.0 500 INTERNAL SERVER ERROR
```

### Expected behavior
```/dataset``` returns 500 on solr down

### Additional details
This is bad because 200 response will be cached by CDN. The solr error stays even after Solr is back up, until the cache times out.

**Comment by Labuschagne-Miro** [comment]
@FuhuXia , I am working on this issue.

**Comment by Labuschagne-Miro** [comment]
@FuhuXia , I am working on this issue. Please acknowledge it।

**Comment by Labuschagne-Miro** [comment]
I will submit a Pull request

**Comment by duttonw** [comment]
Should we return, 500 custom with a nice page that search is offline then just a dead page?
