### ISSUE TITLE
Editing of resources unavailable from package view page

### ISSUE THREAD

**Issue by heaysa** [ckan/ckan#8025]
## Describe the bug
A dropdown list labeled "Explore" is available for all resources in a package after navigating to ../dataset/xxx .  The edit option is missing from this list even when edit permissions should be available (resource is still editable once navigating to its resource page).

### Additional details
Here is a screen shot logged in with administrator privileges but not able to edit a resource from the drop down menu.

![Screenshot_2024-01-24_16-12-00](https://github.com/ckan/ckan/assets/141369310/5797c67d-3105-4873-91cb-e742d481e21b)

Some investigation finds that the `can_edit` variable accessed in the jinja template `templates/package/snippets/resources_list.html` is undefined within the `resource_list_inner` block, and defined outside of it.  Adding the `scoped`  modifier to its block definition makes this variable available and the edit option appears in the dropdown menu: 

![Screenshot_2024-01-24_16-15-58](https://github.com/ckan/ckan/assets/141369310/0f5d7700-6565-4366-bce8-69df1303939f)

I believe this is the desired behaviour.

**Comment by wardi** [comment]
Sounds like a great fix for our next bugfix release, would you submit a PR?

**Comment by Labuschagne-Miro** [comment]
@wardi , I will submit a pull request. I am working on this issue.
