### ISSUE TITLE
Cannot decode JWT token: Signature verification failed

### ISSUE THREAD

**Issue by ChristianF88** [ckan/ckan#8028]
Hi,

I am using a dockerized version of `ckan 2.9.9` with `ckanext-envvars`.

When posting to the API, with a freshly generated token for a `sysadmin` user I get this error:
```
2024-01-25 13:08:14,776 ERROR [ckan.lib.api_token] Cannot decode JWT token: Signature verification failed
```

I have tried posting via `curl`, but also tried `ckanapi` - same issue. I also tried different ways of generating the token (via website, via cli), it did not make a difference.

The JWT encode and decode secrets are set via `string:`.

I **can** run **`package_search`**  but for example **`package_show` fails** and other things like **`package_create` fails** too.

Any suggestions?

**Comment by ChristianF88** [comment]
I have added an API key for testing, everything works with an API key.

**Comment by blagojabozinovski** [comment]
@ChristianF88  Is the value for the api_token in the production.ini file the same for both encode and decode secret when You create and test the api token? 
For example
api_token.jwt.encode.secret = string:ABC123456543
api_token.jwt.decode.secret = string:ABC123456543

**Comment by ChristianF88** [comment]
Hi @blagojabozinovski,

The strings for encoding and decoding are different:
```bash
CKAN___API_TOKEN__JWT__ENCODE__SECRET=string:712408sdghdavjcro3zg43o543
CKAN___API_TOKEN__JWT__DECODE__SECRET=string:ynccxbasdgeiuwqz538426432safh
```
They're defined via **ckanext-envs**.

**Comment by ChristianF88** [comment]
@blagojabozinovski thanks for responding so quickly. I will test this later and share my findings here. However if both secrets should be the same, why do two strings have to be defined? I have not looked into the JWT algortihm but that seems a bit weird to me.
