### ISSUE TITLE
GitHub homepage: Misleading "Releases - CKAN 2.10.1 Latest"

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#8042]
The homepage of this GitHub repository contains a list of releases in the right column:
![image](https://github.com/ckan/ckan/assets/486141/973d4369-3254-4828-84c6-a0d5652cc344)
Unfortunately:

1. It is incomplete, lacking in particular CKAN 2.10.3.
2. It indicates 2.10.1 as the latest, even though 2.10.3 has been since December 13th.

**Comment by amercader** [comment]
Sorry, forgot to create this on the latest release. Should be fixed now:

https://github.com/ckan/ckan/releases/tag/ckan-2.10.3
