### ISSUE TITLE
Broken Link for Font Awesome in Documentation

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan#8097]
## CKAN version
latest

## Describe the bug
Documentation update

https://github.com/ckan/ckan/blob/3b3ac6a2d8e990293a3d274ce75ac0013fc750d1/ckan/plugins/interfaces.py#L286

Contains a link that produces a 404 while also looking like it references a very old version of FA.  Happy to submit a PR, but am unsure if better to link to https://fontawesome.com or https://github.com/FortAwesome/Font-Awesome and if a specific version should be referenced.

**Comment by amercader** [comment]
Either is fine @pdekraker-epa let's drop the version, a PR would be great!
