### ISSUE TITLE
JS issue when add member flash an error

### ISSUE THREAD

**Issue by tino097** [ckan/ckan#8104]
## CKAN version 
master / 2.10.x

## Describe the bug
The autocomplete component not working if the Add Member have error when `debug = false` is set in the ini file 

### Steps to reproduce
`debug = false` in the ini file 
Go to Organization manage page
Navigate to Members
Click on Add member without input
Automplete gets broken

### Expected behavior
Just to see flash message that user is not slected

### Additional details
![image](https://github.com/ckan/ckan/assets/2707446/e2e3d351-bd79-4a08-906e-55f343319be8)

**Comment by Zharktas** [comment]
@tino097 seems that `notify.js` is bundled before `i18n.js` and that is failing in javascript when some notification is shown:
https://github.com/ckan/ckan/blob/f42547b7732a562b3be63c911cabe41b543ba4ed/ckan/public/base/javascript/webassets.yml#L25-L26

`ckan.i18n` hasn't been initialized when it tries to find translation for `Close`
https://github.com/ckan/ckan/blob/f42547b7732a562b3be63c911cabe41b543ba4ed/ckan/public/base/javascript/notify.js#L55

**Comment by Zharktas** [comment]
Doesn't happen in 2.9 since it doesn't have aria labels for which translations are required.

**Comment by tino097** [comment]
Also i've noticed that Datatables is having issues: 

```
  File "/home/tino097/.pyenv/versions/local/lib/python3.10/site-packages/webassets/env.py", line 216, in query_url_mapping
    raise ValueError('Cannot determine url for %s' % filepath)
```
From @smotornyuk [comment](https://github.com/ckan/ckan/issues/7369#issuecomment-1567226566) we should remove `cssrewrite` ?
