### ISSUE TITLE
Leverage HTMX in CKAN's Activity Stream

### ISSUE THREAD

**Issue by pdelboca** [ckan/ckan#8129]
## CKAN version
master

## Details

The current UI to display activity stream is a really good place to leverage HTMX. This will require some refactor on how the templates but both the `pagination` and the `filters` could be improved.

## Tasks
 - [ ] Use an `hx-get` attribute in our **Activity type** `select` element to apply the filters.
 - [ ] Use as well `hx-get` to move between pages instead of full page reload.

## Screenshot of the view to refactor

![image](https://github.com/ckan/ckan/assets/6672339/39d19385-d5e3-4958-969d-e7355958d0c2)

**Comment by Alexandra-Green** [comment]
@pdelboca should the url change without reloading the page?

**Comment by pdelboca** [comment]
@aleeexgreeen since our view logic depends on URL parameters you can push the URL to the browser history with `hx-push-url`:

https://htmx.org/attributes/hx-push-url/
