### ISSUE TITLE
Getting Started documentation page give incorrect command for docker install

### ISSUE THREAD

**Issue by jazzabeanie** [ckan/ckan#8177]
## Describe the bug
[Getting started documentation page](https://docs.ckan.org/en/2.10/maintaining/getting-started.html) says to create a new sysadmin with `ckan -c /etc/ckan/default/ckan.ini sysadmin add seanh email=seanh@localhost name=seanh`. The equivelent when installed through docker is `docker exec -it ckan ckan -c /etc/ckan/default/ckan.ini sysadmin add seanh email=seanh@localhost name=seanh`, however this gives `Config file not found: /etc/ckan/default/ckan.ini`

### Steps to reproduce
- install with docker
- run `docker exec -it ckan ckan -c /etc/ckan/default/ckan.ini sysadmin add seanh email=seanh@localhost name=seanh`

### Expected behavior
I would expect the commands given on the getting started page to successfully create a sysadmin user even when installed with docker.

### Additional details
If I run `docker exec -it ckan ckan config describe` I see that the ckan.ini file is at `/srv/app/ckan.ini`. If I change the create sysadmin user command to use this file then it works: `docker exec -it ckan ckan -c /srv/app/ckan.ini sysadmin add seanh email=seanh@localhost name=seanh`

**Comment by jazzabeanie** [comment]
Also on that same documentation page:

When running `ckan generate fake-data organization` from inside the docker container (with `docker exec -it ckan /bin/bash`) gives

```
7c6245926a1b:/srv/app# ckan generate fake-data organization
2024-04-10 03:26:52,060 INFO  [ckan.cli] Using configuration file /srv/app/ckan.ini
2024-04-10 03:26:52,060 INFO  [ckan.config.environment] Loading static files from public
2024-04-10 03:26:52,275 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2024-04-10 03:26:52,539 WARNI [ckanext.reclineview.plugin] The Recline-based views are deprecated andwill be removed in future versions
2024-04-10 03:26:52,563 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2024-04-10 03:26:52,704 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
No module named 'factory'
Make sure you have dev-dependencies installed:
        pip install -r dev-requirements.txt
Aborted!
```
I can't see any `dev-requirements.txt` file.

**Comment by houfu** [comment]
Are you using the docker images at [ckan/ckan-docker](https://github.com/ckan/ckan-docker)?

AFAICT, the images are set up differently and the getting started documentation refers to a plain install.
(In ckan-docker, the sysadmin user is created through environment variables)

**Comment by kowh-ai** [comment]
Yes, it's a bit unclear as to what type of install the [Getting started documentation page](https://docs.ckan.org/en/2.10/maintaining/getting-started.html) refers to however @houfu is correct says this documentation is for a plain (source) install...

@jazzabeanie  are you able to create a new PR to make this clearer?

**Comment by jjohnston-aims** [comment]
PR created: https://github.com/ckan/ckan/pull/8180

**Comment by rantoniuk** [comment]
@houfu sorry for discussion in an already closed issue, but that's not clear for me.
Re: `No module named 'factory'`, I see that a [factory dependency is listed in requirements-dev](https://github.com/ckan/ckan/blob/master/dev-requirements.txt#L7) but not in [requirements.txt](https://github.com/ckan/ckan/blob/master/requirements.txt).

Now, I would understand that `generate fake-data` command should work in a non-development mode/build, no?
