### ISSUE TITLE
package_patch breaks uploaded resources

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan#8179]
## CKAN version
2.10.4

## Describe the bug
When using package_patch to update a dataset, intending **not** to update an uploaded resource the resource filename appears to be lost

### Steps to reproduce
1. Create a dataset containing at least one uploaded file resource
2. Call package_patch to update the dataset, but for the resources only pass the resource ids like specified in the documentation 
(https://docs.ckan.org/en/2.10/api/#ckan.logic.action.patch.package_patch) like:
```
package_patch(**{'id':'b6cc8622-3334-4cdb-8960-e2a3c4269a8d', 
                 'description':'Updated description', 
                 'resources':[{'id':'a97b8889-5efb-440c-b6ad-fa9a9e4d7659'},
                              {'id':'bdbb977f-9faa-4715-88d3-c5e9042e69a4', 
                               'description':'Updated resource description'}]})
```
3. Browse to the updated resource, the download link is missing the file name probably replaced by ___ and the mimetype is lost

### Expected behavior
The resources should be unchanged when no changes are requested

### Additional details
I think part of this issue arises out of url being used to store the filename. It may be cleaner to just add filename as another field in uploaded resources which could also make renaming uploaded files easier.

**Comment by wardi** [comment]
Thanks @pdekraker-epa the `package_patch` docs added by https://github.com/ckan/ckan/pull/4563 are incorrect. I'll create a PR to remove them.

`package_patch` has no understanding of the package/resource structure and instead simply replaces any keys passed (including `resources`) through to `package_update`.

If you want to update some fields at the dataset level and other fields at the resource level you can use `package_revise` instead which lets you replace specific fields at any level of nesting without disturbing other existing fields.
