### ISSUE TITLE
Following /followers count not updated immediately.

### ISSUE THREAD

**Issue by Soumilgit** [ckan/ckan#8199]
## Describe the bug
The followers/following count is not updated inspite of refreshing multiple times and logging out and logging in again.

### Expected behavior
After changes happen in the followers/following count,it should be updated in the UI immediately upon refreshing.

**Comment by TomeCirun** [comment]
Hey @Soumilgit  I cannot reproduce the issue on the latest CKAN. Could you provide more information about the issue, including which CKAN version you are using?

cc @tino097

**Comment by Soumilgit** [comment]
The

**Comment by Soumilgit** [comment]
The issue has already been resolved.Thanks for your concern @TomeCirun 😃!Closing it with this comment!
