### ISSUE TITLE
After upgrading the ckan version, Page View Tracking cannot continue to be updated

### ISSUE THREAD

**Issue by hongjie123** [ckan/ckan#8216]
## CKAN version
ckan 2.10.2

## Describe the bug
Importing the tracking data (tracking_summary) from ckan2.5.2 into ckan2.10.2, the data cannot be updated, as shown in the following figure:
![image](https://github.com/ckan/ckan/assets/54384385/0ea7e136-4473-4c9b-b00c-48aadb5176f6)
![image](https://github.com/ckan/ckan/assets/54384385/d94af9fa-1330-4abc-aec5-be9174c5037b)

### Steps to reproduce
1. Import the tracking_summary table from ckan2.5 into the ckan2.10 database (previous data can be seen)
2. Reference documents（ https://docs.ckan.org/en/2.10/maintaining/tracking.html#page -View tracking, start the function, and manually execute the "ckan - c/etc/ckan/default/ckan. ini tracking update" command in the virtual environment, as shown in the following figure:
![image](https://github.com/ckan/ckan/assets/54384385/e5975686-882b-4e26-a86b-d4ea20c607ff)

3. At this point, an error occurred. And some of the imported data will also be deleted. The following is a comparison chart before and after the update:
![image](https://github.com/ckan/ckan/assets/54384385/4771001c-6cf2-4764-9108-48c1d78c7897)

![image](https://github.com/ckan/ckan/assets/54384385/64f24f85-4f3b-49db-ba61-39b01e2f3229)

### Expected behavior
We should continue to follow the new tracking_summary table on top of the imported old data.

### Additional details
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.

**Comment by pdelboca** [comment]
Hello @hongjie123 !

Sadly we cannot take a deep look at this since CKAN 2.5.2 has been long deprecated and we do not provide any more support for it.

I would suggest you to ask in the community channel just in case someone had the same problem: https://gitter.im/ckan/chat

Thanks!
