### ISSUE TITLE
Custom IAuthenticator in Ckan 2.10.4

### ISSUE THREAD

**Issue by vanquan223** [ckan/ckan#8229]
## CKAN version
2.10.4
## Describe the bug
My custom `authenticate ` method returns None, but I notice that `ckan_authenticator ` still calls `default_authenticate ` and the user logs in successfully.

### Steps to reproduce
I am trying to implement the IAuthenticator in my ckan, here is the documentation link [IAuthenticator.authenticate](https://docs.ckan.org/en/2.10/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IAuthenticator.authenticate)
![image](https://github.com/ckan/ckan/assets/37933762/736edc57-058d-449d-b5ad-c8f4146eef80)

My custom `authenticate ` method returns None, but I notice that `ckan_authenticator ` still calls `default_authenticate ` and the user logs in successfully.

### Expected behavior
I want the custom `authenticate ` method to display an error message and prevent the user from logging in if it returns None.

### Additional details
I have an idea to modify the ckan_authenticator method as follows:
![image](https://github.com/ckan/ckan/assets/37933762/143c65da-1d31-4e1a-bdc4-19fe16d75cae)

**Comment by smotornyuk** [comment]
you need to return `ckan.model.AnonymousUser()` from IAuthenticator.authenticate to break the chain. #8298 contains addition to interface docstring that mentions this solution.

**Comment by vanquan223** [comment]
Great, thanks @smotornyuk
