### ISSUE TITLE
Markdown formatting is not translated into the selected locale other than English

### ISSUE THREAD

**Issue by Nisha1293** [ckan/ckan#8254]
## Describe the bug
Markdown formatting is not translated into the selected locale other than English

### Steps to reproduce
**ckan.ini configuration**
ckan.locale_default = ja
ckan.locales_offered = ja
ckan.locale_order = ja

ckan.base_templates_folder = templates

**ckan.po for ja translation**
```
#: ckan/templates/macros/form/markdown.html:31
#, python-format
msgid ""
"You can use <a href=\"#markdown\" title=\"Markdown quick reference\" data-"
"target=\"popover\" data-content=\"%(markdown_tooltip)s\" data-"
"html=\"true\">Markdown formatting</a> here"
msgstr ""
"ここでは<a href=\"#markdown\" title=\"Markdown quick reference\" data-"
"target=\"popover\" data-content=\"%(markdown_tooltip)s\" data-"
"html=\"true\">Markdown形式</a>を使うことができます "
```

1. click on Add Dataset button.
2. With the above configuration,  markdown formatting is displayed in English on the screen as shown below.

<img width="358" alt="markdown_error" src="https://github.com/ckan/ckan/assets/89568228/6370ee41-b971-4ed1-b108-78552c3b5a7a">

### Expected behavior
It should be shown in selected locale .

**Comment by amercader** [comment]
See https://github.com/ckan/ckan/pull/8255#issuecomment-2160841410
