### ISSUE TITLE
Error displaying empty fields in XML with 'xsi ="true"' in CKAN Datastore

### ISSUE THREAD

**Issue by themasugo** [ckan/ckan#8311]
## CKAN version
2.9.10
## Describe the bug
When downloading a file from CKAN's Datastore in XML format, empty fields are represented with xsi:nil="true". However, when trying to view the file in a browser, an error appears stating that the xsi prefix is not defined, the browser throws an error: "Namespace prefix xsi for nil on NumInicialSocios is not defined".

### Steps to reproduce

1. Upload a file to CKAN's Datastore.
2. Download the file in XML format.
3. Try to view the XML file in a browser.

You can also try with this resource from the open data portal of the Government of Navarra:
https://datosabiertos.navarra.es/dataset/datos-de-cooperativas-vigentes-inscritas-en-el-registro-de-cooperativas-de-navarra/resource/5ee5a208-0299-4d3c-b0e8-5f7bb1f59876

### Expected behavior
The XML file should be viewable in the browser without namespace errors.

### Additional details
I have verified that the namespace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" is correctly defined in the root element of the XML document.
I believe this might be a bug in CKAN's Datastore tool.
![image](https://github.com/ckan/ckan/assets/104373019/ce01b2ba-053d-4b54-97ea-12e02e9c34ca)

Thanks in advance

**Comment by wardi** [comment]
@themasugo I don't get an error viewing files with nulls, just a warning about a missing stylesheet. Can you include an example of a file generated that triggers this error?
![xml-view-in-browser](https://github.com/ckan/ckan/assets/153258/e66e3eae-e2a3-4a79-a75c-9e7925992c7e)

**Comment by themasugo** [comment]
> @themasugo I don't get an error viewing files with nulls, just a warning about a missing stylesheet. Can you include an example of a file generated that triggers this error? ![xml-view-in-browser](https://private-user-images.githubusercontent.com/153258/345128460-e66e3eae-e2a3-4a79-a75c-9e7925992c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODU4MTIsIm5iZiI6MTcyMDA4NTUxMiwicGF0aCI6Ii8xNTMyNTgvMzQ1MTI4NDYwLWU2NmUzZWFlLWUyYTMtNGE3OS1hNzVjLTllNzkyNTk5MmM3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwOTMxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGUzNzRiMjFhOTg0OTMxOGYzZDk3NjkwOTk1NTJjNDZiNDY3OGU1YjA5N2QyNmRlYjdiMjcwZDUwZmViZWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GkGedv_anIOOHjGcyh_ubRQ5WWVICa9cAj6OAJJE_rM)

Wow, that's strange. Were you able to try with the resource mentioned on the Government of Navarra portal? Anyway, I'm going to try on a clean CKAN 2.9. Thanks again!

**Comment by themasugo** [comment]
Ok, I tried with a clean installation of ckan 2.9 and it works well ... so the problem it's from our ckan.
Thanks again!
