### ISSUE TITLE
API token generation not show generated token

### ISSUE THREAD

**Issue by gatiszeiris** [ckan/ckan#8313]
## CKAN version
2.10.1

## Describe the bug
After API token generation not show generated tokens. If I delete all CAN cookies (ckan, remember_token) from browser  - log in back API token generate and shows up in flush message.

### Steps to reproduce
After som time of using ckan with authorized user go to user profile API tokens tab.
Enter Api token name
Click "Create API Token"
New record shows up in token table but dont show API token value in flush message (page header block).

ckan.ini 

----Session settings --
ckan.user.last_active_interval = 600
cache_dir = /tmp/%(ckan.site_id)s
beaker.session.key = ckan
beaker.session.secret = 10slbG7Wg1x7yNCXqVk9-ujGujE
beaker.session.auto = false
beaker.session.cookie_expires = false
# beaker.session.cookie_domain = .example.com
beaker.session.save_accessed_time = true
beaker.session.secure = false
beaker.session.timeout =3600

### Expected behavior
A clear and concise description of what you expected to happen:
API token generation need work always with old or new session.

**Comment by gatiszeiris** [comment]
There is an issue with the frontend session when adding additional cookies with JSON content. The issue is mainly affected Flask flash messages mechanism. 

To reproduce the issue need to put any cookie with any JSON content (e.g. document.cookie="keyofcookie={\"extra\":\"cookie\"}"). In this case, CKAN cannot process flash messages correctly and lost "_flashes" message on the user session between the POST and GET requests. Therefore, the user can't copy the newly created API token, which is only displayed once when created. This affects the Beaker and Redis session store.

**Comment by arsh7023** [comment]
@kowh-ai , @gatiszeiris I have the same issue, is there any update on this? thanks

**Comment by gatiszeiris** [comment]
Still no update regarding this problem.

**Comment by arsh7023** [comment]
One way to see the token is in the backend edit the below file and print the result:

    vim /usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py

    result = api_token.add_extra({u'token': token})
    print(result)
    return result

This is a temporary solution until the UI gets fixed. @gatiszeiris

**Comment by blagojabozinovski** [comment]
@arsh7023 @gatiszeiris I had the same issue (api token value not showing on the frontend when created) but it turn out to be a css issue coming from the CKAN theme (not CKAN core). The opacity was set to 0 on the element that was displaying the value of the api token. In my case adding this to the custom css did the trick:
`.flash-messages .alert {
    box-shadow: 0 0 0 1px white;
    opacity: 1;
  }`

**Comment by gatiszeiris** [comment]
We solve our problem encode our custom cookie cc_cookie
![image](https://github.com/user-attachments/assets/b8781f38-cc0d-4727-9fe3-f38b9d96a0c2)

CKAN don't like if any cookie contain { } simbols.
