### ISSUE TITLE
High Costs with reCAPTCHA Enterprise Integration in CKAN

### ISSUE THREAD

**Issue by maukhillewaert** [ckan/ckan#8383]
## CKAN version
2.8.12
## Describe the issue
Hi CKAN team,

I have recently integrated reCAPTCHA into our CKAN instance using a public and private key. However, I am experiencing much higher costs than expected. Specifically, the costs are approximately €15 per day.

We are using reCAPTCHA Enterprise and I have a forecast of 1.46k billable assessments for August. Given that reCAPTCHA Enterprise normally offers 10,000 free assessments per month, I am puzzled about where these costs are coming from.

Could you provide some insights or guidance on why these costs might be so high, and if there are any configuration issues I should be aware of?

Thanks in advance for your assistance!

### Steps to reproduce
1. Integrate reCAPTCHA Enterprise into CKAN using a public and private key.
2. Monitor the usage and billing details from the reCAPTCHA dashboard.

### Expected behavior

Expected costs should be significantly lower, ideally within the free tier limit of 10,000 assessments per month.

### Additional details
/

**Comment by Zharktas** [comment]
I think ckan 2.8 only has recaptcha on register form so you might have bots spamming the form and thus incurring expenses. 

FYI: ckan 2.8 is out of support and has some security flaws, you should upgrade it if possible.

**Comment by maukhillewaert** [comment]
> I think ckan 2.8 only has recaptcha on register form so you might have bots spamming the form and thus incurring expenses.
> 
> FYI: ckan 2.8 is out of support and has some security flaws, you should upgrade it if possible.

Oh, okay, I see. Thank you for the quick response @Zharktas ! :)
