### ISSUE TITLE
Database migration 4eaa5fcf3092 erroneous

### ISSUE THREAD

**Issue by GerhardK90** [ckan/ckan#8390]
## CKAN version
2.11
## Describe the bug
I got a clean install of 2.11.
The database migration 4eaa5fcf3092 removes resource_revision, which is necessary by ckanext-harvester. 
The harvester function seems to work fine until the clear function is called. 
There the havester extension tries to delete entries in the resource_revision table.

Additionally a downgrade is not possible:
sqlalchemy.exc.CompileError: Can't emit DROP CONSTRAINT for constraint ForeignKeyConstraint(<sqlalchemy.sql.base.DedupeColumnCollection object at 0x79ab9b1cb750>, None, table=Table('resource', MetaData(), schema=None)); it has no name
### Steps to reproduce
1. Add a harvester source
2. Try to clear the harvester source

### Expected behavior
Working clearance of the harvester data.
Functional downgrade.

### Additional details
https://github.com/search?q=repo%3Ackan%2Fckanext-harvest%20resource_revision&type=code

**Comment by amercader** [comment]
This was fixed in the harvest extension: https://github.com/ckan/ckanext-harvest/pull/556
Should be available in the next release which will happen today or early next week
