### ISSUE TITLE
GitHub release for 2.11?

### ISSUE THREAD

**Issue by themowski** [ckan/ckan#8412]
Congratulations on the CKAN 2.11 release. Are there plans to create an official release through GitHub? It seems like the tag has been pushed, which is sufficient for my team's needs, but others may not realize that 2.11 is out since there's no "release" for it. That said, I see that the "releases" area has been used inconsistently, so maybe that's not part of your process?

https://github.com/ckan/ckan/releases

**Comment by amercader** [comment]
@themowski sorry, I just created now. Creating them is part of the process, but doing a release involves [many things](https://github.com/ckan/ckan/issues/7542) and we are trying to automate as many of them as possible, but this one slipped through the cracks.

https://github.com/ckan/ckan/releases/tag/ckan-2.11.0
