### ISSUE TITLE
ckan.auth.public_user_details breaks group display

### ISSUE THREAD

**Issue by brooks-eco** [ckan/ckan#8438]
## CKAN version
2.11

## Describe the bug
Setting the option `ckan.auth.public_user_details = false`  to hide members breaks the display of groups for public and registered members (but not sysadmin)
Error-log:  

>   File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 178, in member_list
>     _check_access('group_show', context, data_dict)
>   File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 391, in check_access
>     raise NotAuthorized(msg)
> ckan.logic.NotAuthorized: User xxxxxx not authorized to read group be2b8ec2-f0ca-4746-8d3...

Note the [docs ](https://docs.ckan.org/en/2.11/maintaining/configuration.html#ckan-auth-public-user-details) do say it will " will raise a Not Authorized exception." which does appear to be true but there is no graceful trapping of the exception.  The page is killed off part way through rendering (after the side bar generated but before CSS and main page (screenshot below)

### Steps to reproduce

1. set `ckan.auth.public_user_details = false`  and cycle the server
2. log out
3. go to the groups menu and display groups
4. click on a group

### Expected behavior
I was expecting either:

1. the interface tab with the members list to be hidden, but the group data and about tabs  to remain visible  (preferred)
or...
2. a graceful error message saying the group was for members only

### Additional details
related issue  [Hide list of users by default #3441](https://github.com/ckan/ckan/issues/3441)

screen shot

![image](https://github.com/user-attachments/assets/ae70b1bc-bcd4-4800-8202-da532e6c51e6)

**Comment by brooks-eco** [comment]
Confirm the PR fixes the broken display but IMO it would be an improvement if the members tab was removed for public users so they could not click on it in the first place. (403 forbidden messages are not a very professional look)

Where is the best place to record a feature request such as this?

**Comment by ThrawnCA** [comment]
> Where is the best place to record a feature request such as this?

If you think it's "not working as expected" then you can just raise another issue. If it's a new feature or other enhancement, the [Discussion forum](https://github.com/ckan/ckan/discussions) is the best place.
