### ISSUE TITLE
Social media links are not displayed on resource page when using ckanext-scheming

### ISSUE THREAD

**Issue by bellisk** [ckan/ckan#8454]
## CKAN version
2.11.0

## Describe the bug
When using the plugin [ckanext-scheming](https://github.com/ckan/ckanext-scheming), the sidebar of the resource page is not correctly displayed. Instead of the social media links as expected, the license of the resource is shown as text.

### Steps to reproduce
- Install ckanext-scheming and enable the `scheming_datasets` plugin
- Go to a resource page, `http://localhost:5000/en/dataset/{DATASET_NAME}/resource/{RESOURCE_ID}`
- See that the sidebar does not contain the social media links at the bottom, but does show the text `License` + the title of the resources's license, if there is one, or `License No License Provided` if not.

### Expected behavior
I expect to see the social media links in the sidebar, displayed the same way as they are on the dataset page.

### Additional details
![Screenshot 2024-09-23 at 15-58-17 Business organisations - future_timetable_business_organisation_versions_2024-09-19 csv zip - opentransportdata swiss](https://github.com/user-attachments/assets/3d3996dc-b8ff-4f37-8d2e-5010eae5cfe9)

**Comment by brooks-eco** [comment]
Honest question -  if you were sharing on social media wouldn't you want the share to be of the parent data set, not the individual resource?  I prefer the original behaviour ... but good to have choices.

**Comment by bellisk** [comment]
The original behaviour is to have social media share buttons in this sidebar, not a random piece of text that is unstyled and out of place. That's what this fix restores. It's not really about what I prefer either way.
