### ISSUE TITLE
Bootstrap Out-of-date Version

### ISSUE THREAD

**Issue by FuhuXia** [ckan/ckan#8462]
## CKAN version
2.10.5, 2.11.0

## Describe the bug

[Invicti](https://www.invicti.com/) scan reports: 

Out-of-date Version (Bootstrap)
Identified Version: **5.1.3**
Latest Version: **5.3.3**
Vulnerability Database:
Result is based on 09/10/2024 15:00:00 vulnerability database content.

### Steps to reproduce
Exam the main.css  (at path /webassets/base/#####_main.css)
```
Bootstrap v5.1.3 (https://getbootstrap.com/)
```
### Expected behavior
Bootstrap on the latest version 5.3.3

**Comment by wardi** [comment]
There's a PR for this already #8433 and issue #8427
