### ISSUE TITLE
 Cannot decode JWT token: Invalid crypto padding

### ISSUE THREAD

**Issue by zozol31** [ckan/ckan#8466]
## Describe the bug
when testing datastore write access I have an [ckan.lib.api_token] Cannot decode JWT token: Invalid crypto padding

### Steps to reproduce
I create api token on ckan web UI .
when I test with curl -X POST http://127.0.0.1:5000/api/3/action/datastore_create -H "Authorization: {YOUR-API-KEY}" -d '{"resource": {"package_id": "{PACKAGE-ID}"}, "fields": [ {"id": "a"}, {"id": "b"} ], "records": [ { "a": 1, "b": "xyz"}, {"a": 2, "b": "zzz"} ]}'

I replace {YOUR-API-KEY} by the api key given by ckan I get  [ckan.lib.api_token] Cannot decode JWT token: Invalid crypto padding on ckan server

### Expected behavior
I expect to get write access for datastore

### Additional details
Ckan 2.10 source install

(default) valadmin@ckan:~$ curl -X POST http://10.1.99.248:5000/api/3/action/datastore_create -H "Authorization: {eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJTRGgwSVZnMWhzUXlvSjNUQXJKNzhwQS1ubHRQQVFrN3p1ZG9JRjFORDZvIiwiaWF0IjoxNzI3NzI3OTA3fQ.yKI2ZGTL0gWUFYZz5mUms66-fy4FloMFkkOJn42_q1c}" -d '{"resource": {"package_id": "test"}, "fields": [ {"id": "a"}, {"id": "b"} ], "records": [ { "a": 1, "b": "xyz"}, {"a": 2, "b": "zzz"} ]}'
{"help": "http://10.1.99.248:5000/api/3/action/help_show?name=datastore_create", "error": {"__type": "Authorization Error", "message": "Acc\u00e8s non autoris\u00e9: L'utilisateur  n'est pas autoris\u00e9 \u00e0 modifier le jeu de donn\u00e9es ea129614-047b-464f-909b-35b31a22a580"}, "success": false}(default)

**Comment by zozol31** [comment]
when putting xloader plugin in ckan.plugins and run :ckan -c /etc/ckan/default/ckan.ini xloader status
I get
 File "/usr/lib/ckan/default/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/xloader/cli.py", line 22, in status
    cmd.print_status()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/xloader/command.py", line 130, in print_status
    job_params = eval(job.description.replace(
  File "<string>", line 1
    ({'api_key': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJuYnl4Ym9RWFJJV...)
                 ^
SyntaxError: unterminated string literal (detected at line 1)

**Comment by amercader** [comment]
@zozol31 The API token should not be wrapped in curly brackets, i.e. change this:

```
 -H "Authorization: {eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJTRGgwSVZnMWhzUXlvSjNUQXJKNzhwQS1ubHRQQVFrN3p1ZG9JRjFORDZvIiwiaWF0IjoxNzI3NzI3OTA3fQ.yKI2ZGTL0gWUFYZz5mUms66-fy4FloMFkkOJn42_q1c}"
```

to this:

```
 -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJTRGgwSVZnMWhzUXlvSjNUQXJKNzhwQS1ubHRQQVFrN3p1ZG9JRjFORDZvIiwiaWF0IjoxNzI3NzI3OTA3fQ.yKI2ZGTL0gWUFYZz5mUms66-fy4FloMFkkOJn42_q1c"
```
