### ISSUE TITLE
CKAN 2.11: Internal server error on all group and organization pages when user list is not public

### ISSUE THREAD

**Issue by bellisk** [ckan/ckan#8473]
## CKAN version
2.11.0

## Describe the bug
When accessing a group or organization page, if not logged in to CKAN, the user gets a 500 Internal Server Error response. This only happens when the config option `ckan.auth.public_user_details` is set to `False`.

### Steps to reproduce

1. Set `ckan.auth.public_user_details` to `False` in CKAN config and restart CKAN
2. In the browser, log out of CKAN if logged in
3. Go to any group or organization page, e.g. http://example.org/organization/my-org
4. See an Internal Server Error response and an unstyled page, because CSS also can't be loaded

### Expected behavior
I expect that group and organization pages are visible to logged-out users, and viewing them does not cause an internal server error.

### Additional details
This issue seems to have been introduced by this update: https://github.com/ckan/ckan/pull/7007. This added member counts to the templates for groups and organizations, but didn't take into account that if `ckan.auth.public_user_details` is set to `False`, checking access for `group_show` with the `object_type` `user` (so we only get the users of the group) returns that the user is unauthorized.

https://github.com/ckan/ckan/blob/a151eff2ba1e508f0829a5b088fb05181c980cc3/ckan/logic/auth/get.py#L158C1-L171C106

```
def group_show(context: Context, data_dict: DataDict) -> AuthResult:
    user = context.get('user')
    group = get_group_object(context, data_dict)
    if group.state == 'active':
        if config.get('ckan.auth.public_user_details') or \
            (not asbool(data_dict.get('include_users', False)) and
                (data_dict.get('object_type', None) != 'user')):
            return {'success': True}
    authorized = authz.has_user_permission_for_group_or_org(
        group.id, user, 'read')
    if authorized:
        return {'success': True}
    else:
        return {'success': False, 'msg': _('User %s not authorized to read group %s') % (user, group.id)}
```

**Comment by tino097** [comment]
@bellisk This is [fixed](https://github.com/ckan/ckan/pull/8449) in `master` and it will be part of the next patch releases

**Comment by bellisk** [comment]
Thanks, @tino097, that's great!

**Comment by ThrawnCA** [comment]
@tino097 Any idea how far away that patch release is? This is a blocker for us upgrading to CKAN 2.11.

**Comment by tino097** [comment]
hey @ThrawnCA we mentioned on the tech call yesterday that it should be soon
