### ISSUE TITLE
Tracking after_dataset_search treats some fields as mandatory

### ISSUE THREAD

**Issue by mutantsan** [ckan/ckan#8480]
## CKAN version

2.11+

## Describe the bug

The `tracking` extension `after_dataset_search` counts on `id` and `resources` fields of a search result package. Because we have the `fl` param, we can't guarantee that they will exist in a result dict.

### Steps to reproduce
1. Enable `tracking` extension
2. Try to access the `package_search` API endpoint providing the `fl` param that excludes the mentioned fields.
http://127.0.0.1:5000/api/action/package_search?fl=title

### Expected behavior
I'm not sure what is the desired behavior here. I assume we can skip the tracking if we can't identify the dataset. As for resources, just fallback for an empty list.

**Comment by tino097** [comment]
hey @mutantsan 
i was working on https://github.com/ckan/ckan/pull/8479 because there were some issues with tracking extension 
Not sure if this is related but knowing that the tracking was not recorded at all on CKAN 2.11, maybe thats why you got those results.

**Comment by mutantsan** [comment]
@tino097 Hello. Those issues aren't directly related. The only relation is that they all are inside the `tracking` extension. If you're already working on the fixes for the `tracking` extension, you might be interested in looking at this particular issue closely. Maybe you'll figure out the best approach to fixing it. 👀
