### ISSUE TITLE
CKAN 2.10.5: Additional Information Field Names on Resource Page Not Translated

### ISSUE THREAD

**Issue by TakumiMiyazawaAbel** [ckan/ckan#8532]
## CKAN version

2.10.5

## Describe the bug

I developed an extension plugin and added a new field to the "Additional Information" section on the resource page in CKAN. However, even after changing the language, the field name in the "Additional Information" section does not get translated.

<img width="567" alt="追加情報" src="https://github.com/user-attachments/assets/c9683a9d-ffc3-4837-b888-7f93c82aa8be">

### Steps to reproduce

１．Use the `before_resource_show` function in the `plugin.py` file to add a new field to the "Additional Information" section on the resource page:
```
def before_resource_show(self, resource_dict: dict[str, Any]):
        resource_dict['Downloads'] = (
                get_resource_download_count()
        )

        return resource_dict
```

２．Implement Japanese translations according to the [CKAN i18n documentation](https://docs.ckan.org/en/2.10/contributing/i18n.html?highlight=babel).
The `po` file created for translation is as follows:
```
msgid "Downloads"
msgstr "ダウンロード数"
```

３．Switch to Japanese on the resource screen using the `language selector`(language_selector.html).

４．Check if the field name in the "Additional Information" section changes from "Downloads" to "ダウンロード数."

### Expected behavior

The field names in the "Additional Information" section on the resource page should be translated according to the selected language.

### Additional details

In the "Additional Information" section of the dataset (package) page, field names appear to be translated using `_(...)`, as shown below:
```
<th scope="row" class="dataset-label" property="rdfs:label">{{ _(key|e) }}</th>
```
However, it seems that the translation handling for the field names in the "Additional Information" section on the resource page is not implemented, as shown below:
```
<th scope="row">{{ key | capitalize }}</th>
```
Shouldn’t the field names in the "Additional Information" section of the resource page support translation in the same way as the dataset (package) page?

**Comment by wardi** [comment]
See my comments here for other ways to provided translated resource field labels in ckan: https://github.com/ckan/ckan/pull/8533/files/e4407cc14f7b1d8f8ee4733236b5acbeed30c072#r1848370471
