### ISSUE TITLE
Show number of private datasets in LH column of organisation homepage

### ISSUE THREAD

**Issue by darwinp** [ckan/ckan#855]
The count of datasets in the left hand column of organisation pages is misleading for members of that group. 

![organization stark - ckan beta](https://f.cloud.github.com/assets/199920/445174/a6b40ad6-b1b5-11e2-8ac7-b564d8093aee.png)

If user is logged in as a member or editor of an organisation we should show a count of private datasets in the LH column

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.
