### ISSUE TITLE
Allow Order by Groups and Organizations by Number of Datasets

### ISSUE THREAD

**Issue by frank0051** [ckan/ckan#871]
This isn't so much of an issue as more so of a feature request. When you visit /organization or /group there are only two options in the Order by Drop Down in CKAN 2.0: "Name Ascending" or "Name Descending". Could we add two options for number of datasets (one ascending and one descending). Thoughts?

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
