### ISSUE TITLE
Translations need to be checked

### ISSUE THREAD

**Issue by tobes** [ckan/ckan#903]
Our translations strings need to be checked.

on the way out.

we want to check that we are providing nice stuff to the translators.  Some of this is hard because it is subjective but some can be done programatically eg `.. {0} ..` bad `... {descriptive_name} ..` good

See this email thread: http://lists.okfn.org/pipermail/ckan-dev/2013-April/004563.html

on the way in.

check that translation strings match as far as substituted vars is concerned

an example problem #900

At the moment I'm not sure where the best place to add these is.  it would be nice to have some in the coding standards tests but others eg checking translations keep vars needs doing probably as a paster command or as part of the translation build process.

**Comment by rossjones** [comment]
This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
