### ISSUE TITLE
ckan.i18n_directory setting usage

### ISSUE THREAD

**Issue by anibalpacheco** [ckan/ckan#922]
Could anyone make this setting work?

When I set this to a path inside a plugin containing a single translation that I want to override I get the error below when pointing the browser to homepage, using master:

```
~/venv/ckan2/src/ckan$ grep i18n development.ini
ckan.i18n_directory = %(here)s/../ckanext-agesic/translation
~/venv/ckan2/src/ckan$ tree ../ckanext-agesic/translation
../ckanext-agesic/translation
└── ckan
    └── i18n
        └── es
            └── LC_MESSAGES
                ├── ckan.mo
                └── ckan.po
```

```
LanguageError: IOError: [Errno 2] No translation file found for domain: 'ckan'
```

**Comment by KrzysztofMadejski** [comment]
See https://github.com/opendatatrentino/ckan-custom-translations#how-to-make-extensions-translatable
for translating extensions. 

Use update_catalog and compile_catalog instead of update_messages and compile_messages.

**Comment by KrzysztofMadejski** [comment]
As for original @anibalpacheco question. 
If anyone encounteres `LanguageError: IOError: [Errno 2] No translation file found for domain: 'ckan'`

having `ckan.i18n_directory = DIR`, make sure that file `DIR/i18n/<CURRENT_LANG>/LC_MESSAGES/ckan.mo` exists

**Comment by KrzysztofMadejski** [comment]
My script for aggregating translations from multiple plugins, excluding default ckan translations in plugin, overriding default ckan definitions.

https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/wiki/Modifying-translations
https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/i18n/aggregate_and_compile.sh
