### ISSUE TITLE
Allow users to enable the read-write mode for resources through the interface

### ISSUE THREAD

**Issue by domoritz** [ckan/ckan#934]
https://github.com/okfn/ckan/wiki/Spec:-DataStore-and-FileStore-Consolidation

Add a check box to the edit resource page. We should decide whether we want this, though.

**Comment by rossjones** [comment]
Didn't make it into 2.3. Or 2.4. Or 2.5.

This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.
