### ISSUE TITLE
Add paster command for the datapusher to datastore

### ISSUE THREAD

**Issue by domoritz** [ckan/ckan#937]
Something like `paster datastore push [package_id]`. Also note https://github.com/okfn/ckanext-datastorer/tree/36-datapusher.

- [x] Add paster command
- [x] Store job status with `task_status_update` (is done automatically when using the `datapusher_submit` action)

Related to #938

https://github.com/okfn/ckan/wiki/Spec:-DataStore-and-FileStore-Consolidation

**Comment by davidread** [comment]
Paster command is done here: https://github.com/ckan/ckan/pull/2246
